### ISSUE TITLE
Board Game Online | https://www.boardgame-online.com/

### ISSUE THREAD

**Issue by LyrBunny** [PreMiD/Presences#1009]
**Prerequisites and essential questions** 
* [x] Is it a popular site? 
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [x] Does the website feature NSFW content? (e.g. porn, etc...) - (No pornography but it does have NSFW themes)
* [x] Are you a donator/patron? ($50 Patreon)
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Lyric#1111

**What's the name of the service?** Board Game Online

**What should the Presence display?** Lobby name, how many players, what space your on and how many left, what place your player is.

**If possible, please provide a logo for the service (512x512 minimum)** Can't find one.

**Comment by frozaum** [comment]
What's your nickname over Patreon? @LyrBunny

**Comment by Alanexei** [comment]
#1138
Currently pending for review

**Comment by doomlerd** [comment]
Added.
