### ISSUE TITLE
Express Radio

### ISSUE THREAD

**Issue by AviaMisto2** [PreMiD/Presences#1027]
**Prerequisites and essential questions** 
* [ ] Is it a popular site? No
* [ ] Is the website older than 2 months?  Yes
* [ ] Is the site locked to a specific country/region? No
* [ ] Is the site a paid service? (e.g. Netflix, Hulu) No
* [ ] Does the website feature NSFW content? (e.g. porn, etc...) No
* [ ] Are you a donator/patron? No
* [ ] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? Yes

**What's your Discord username?**  chxrlie#2778

**What's the name of the service?** 
expressradio.co
**What should the Presence display?**  Current DJ and Song and Time Elasped on Website

**If possible, please provide a logo for the service (512x512 minimum)** 
![expressradiocircle](https://user-images.githubusercontent.com/59765752/74083630-65970a00-4a5e-11ea-80f6-c556a8d8b841.png)

**Comment by frozaum** [comment]
Hello, Your Website/Domain name must be at least 2 months old.
![](https://cdn.discordapp.com/attachments/526736087377248257/675849711772499989/unknown.png)
