### ISSUE TITLE
site presence bug (Dream Animes)

### ISSUE THREAD

**Issue by ysauron2** [PreMiD/Presences#1031]
**Describe the Bug**

the bug happens when watching the anime on the site, instead of appearing One Piece Movie 14 in the presence of Discord appears One Piece episode 14.
not only in this title, but in others too.

**Steps to Reproduce**

1. Log in and watch the movie so that the presence works: [(https://www.dreamanimes.com.br/online/legendado/one-piece/filme/14)](https://www.dreamanimes.com.br/online/legendado/one-piece/filme/14)
2. Then go to the Discord and see if the presence is appearing "One Piece Episode 14 or Movie 14" 

**Expected Behavior**

The correct thing was to show "One Piece Movie 14
**Screenshots**

1.  in Dream Animes: [(https://funkyimg.com/view/327Dq )](https://funkyimg.com/view/327Dq ) 
2.  in Discord: [https://funkyimg.com/view/327Dw](https://funkyimg.com/view/327Dw) 
**Environment**

 - OS: Windows 10 
 - Browser: Opera 
 - Version:  66.0.3515.72 (64-bit)
 
 
**Additional context**

**Comment by Bas950** [comment]
This is intended behavior, it shows:
- Show Title
- Episode
- Time Left

If you still do not agree with this, please contact the developer of the presence: Evil#8523

Invalid - Closed
