### ISSUE TITLE
crunchyroll.com (for 2.0)

### ISSUE THREAD

**Issue by frozaum** [PreMiD/Presences#104]
**What's the name of the service?**
Ex. www.crunchyroll.com | Crunchyroll

**What should the Presence display?**
Informations about the current episode/movie

**Why do you want support for this service?**
Crunchyroll is one of the biggest anime providers on the world, i still use it sometimes, unfortunately the presence got removed on 2.0, so i'm requesting 
to be added again

**Are you able to provide an image for the service? (512x512 minimum)**
![unnamed](https://user-images.githubusercontent.com/34042085/62475600-b9592b80-b77b-11e9-9d78-be8228d4ea8f.png)

**Comment by TheDropX** [comment]
Presence done.
