### ISSUE TITLE
Yahoo Finance | finance.yahoo.com

### ISSUE THREAD

**Issue by ghost** [PreMiD/Presences#1049]
* [x] Is it a popular site?
* [x] Is the website older than 2 months?
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**
frixi#2635

**What's the name of the service?**
finance.yahoo.com/ | Yahoo Finance

**What should the Presence display?**
Articles, that i am currently looking at, symbols that i am browsing or type of graph im currently looking at.

**If possible, please provide a logo for the service (512x512 minimum)** 
![yahoofinance](https://user-images.githubusercontent.com/18513533/74281746-44b10c00-4d1f-11ea-8a4a-b9ea1534cb51.png)

**Comment by Sazzo** [comment]
I will make that presence.

**Comment by doomlerd** [comment]
@Sazzo next time ask a verifier instead

**Comment by Sazzo** [comment]
sure (=
