### ISSUE TITLE
Amino Apps | aminoapps.com

### ISSUE THREAD

**Issue by Lesano** [PreMiD/Presences#1083]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** 
www.aminoapps.com | AminoApps

**What should the Presence display?** 
Information when reading a post, watching a chat and creating a post.

**If possible, please provide a logo for the service (512x512 minimum)** 
![](https://i.pinimg.com/originals/35/b2/d3/35b2d396cb9762bcc7e07a9597840db6.png)

**Comment by Sazzo** [comment]
I will make that presence.

**Comment by Isa27-0** [comment]
Ok, since the presence has been added, let's consider this Issue as closed
