### ISSUE TITLE
Duolingo Presence Doesn't Change While in a Lesson

### ISSUE THREAD

**Issue by Dyiing** [PreMiD/Presences#1088]
**Describe the Bug**
When a lesson is started using the duolingo presence, instead of switching to "Taking a X lesson", it remains on the "Choosing a level to learn..." status.

**Steps to Reproduce**
1. Start Duolingo and go to the /learn page
2. Enter any lesson
3. Check presence

**Expected Behavior**
The status should change to say that the User is in the given language lesson.

**Screenshot**
https://tinyurl.com/svfzm2q

**Environment**

 - OS: Windows 10 v1909
 - Browser: FireFox Developer Edition
 - Version: 74.7 (x64)

**Additional context**
Which language is chosen does not affect the issue.

**Comment by doomlerd** [comment]
It was fixed already for some time now, try again and if the issue occurs feel free to make another issue.
