### ISSUE TITLE
Express Radio Presence

### ISSUE THREAD

**Issue by AviaMisto2** [PreMiD/Presences#1091]
**Prerequisites and essential questions** 
* [ ] Is it a popular site? No
* [x] Is the website older than 2 months?  in 6 days yes
* [ ] Is the site locked to a specific country/region? No
* [ ] Is the site a paid service? (e.g. Netflix, Hulu) no
* [ ] Does the website feature NSFW content? (e.g. porn, etc...) no
* [ ] Are you a donator/patron? No
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? Yes

**What's your Discord username?** 
Catzer#2777
**What's the name of the service?**  expressradio.co

**What should the Presence display?** 
Current DJ, Current Song
**If possible, please provide a logo for the service (512x512 minimum)** 
![F654CD84-27C6-465A-B4AF-595B3E33A1E5](https://user-images.githubusercontent.com/59765752/75136480-beaca200-56dc-11ea-9620-f3994a118fbd.png)

**Comment by frozaum** [comment]
Like we said on #1027, your domain needs to be (at least) 2 months old.
![image](https://user-images.githubusercontent.com/34042085/75448504-19970100-594a-11ea-9e3a-b1d8b6346693.png)
