### ISSUE TITLE
Rich Presence for the broswer game Astr.io - https://astr.io/

### ISSUE THREAD

**Issue by Azrael206** [PreMiD/Presences#1117]
**Prerequisites and essential questions** 
* 

- [x] Is it a popular site?

* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** ⦂灸 Azrael#0031

**What's the name of the service?** 
https://astr.io/ - Astr.io
**What should the Presence display?**  It would be awesome for it show the server we are currently playing in and the region that server we are on for example: NA Domination I Mass: (current mass), and adding our current name we are using in-game to the presence 

**If possible, please provide a logo for the service (512x512 minimum)** 
![cover-256 1](https://user-images.githubusercontent.com/61640048/75618013-a0f49800-5b35-11ea-8268-b10cad1893fa.png)

**Comment by callumok2004** [comment]
I will begin working on this presence now.

**Comment by callumok2004** [comment]
The image you provided is not 512x512 Minimum :/

**Comment by Azrael206** [comment]
Ah ok, I’m at work right now, when I get home around 1ish, can I submit the new size?

**Comment by callumok2004** [comment]
Its alright, I found one in the end :)
