### ISSUE TITLE
Express Radio (3rd Attempt)

### ISSUE THREAD

**Issue by AviaMisto2** [PreMiD/Presences#1118]
**Prerequisites and essential questions** 
* [ ] Is it a popular site? No
* [ ] Is the website older than 2 months?  YES (This time I ACTUALLY mean yes)
* [ ] Is the site locked to a specific country/region? EU
* [ ] Is the site a paid service? (e.g. Netflix, Hulu) No
* [ ] Does the website feature NSFW content? (e.g. porn, etc...) No
* [ ] Are you a donator/patron? No
* [ ] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? Yes

**What's your Discord username?**  Catzer#2778

**What's the name of the service?** 
expressradio.co | Express Radio
**What should the Presence display?**  Current DJ, Song and when you hover over the play button it shows listeners.

**If possible, please provide a logo for the service (512x512 minimum)** 
![NEW EXPRESS LOGO](https://user-images.githubusercontent.com/59765752/75622546-5b69b680-5b99-11ea-90e7-697e4c1d210d.png)

**Comment by AviaMisto2** [comment]
![Express radio](https://user-images.githubusercontent.com/59765752/75622612-4d686580-5b9a-11ea-938d-c87b0fb8699e.png)
**Sorry about this, But PLEASE use this image instead!**

**Comment by callumok2004** [comment]
Your website is not 2 months old, I know this myself, you released in January, one month ago, and did not have a site a the time. You only recently got a site which is about 2/3 weeks old, unless you can provide proof otherwise, then we cannot make the presence at this current time. Sorry :/

**Comment by doomlerd** [comment]
Plus the template is used in a wrong way, please mark the check boxes like "[x]" the next time you open a new request.
