### ISSUE TITLE
Astr.io Presence Suggestion! 

### ISSUE THREAD

**Issue by Azrael206** [PreMiD/Presences#1121]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  ⦂灸 Azrael#0031

**What's the name of the service?**  https://astr.io/

**What should the Presence display?**  Ping, and tag the user is in, and the selected region at the main menu. For example, NA - Main Menu.

**If possible, please provide a logo for the service (512x512 minimum)**  Already a presence, only adding suggestions!

**IMPORTANT**

I understand this is already a presence, this is only a request to add extra features. The presence overall is really cool, and I thank the creator over and over in my head for doing this! No bugs or issues whatsoever :). If this is possible, can the presence show "(Region) - Main Menu, Gamemode: Domination" when at the main menu, so it states what region the user is in when at the main menu, and Gamemode: (current gamemode) is perfectly fine! 

Also, when clicking play the presence changes to the gamemode, current mass, and nickname, is it possible to add under the nickname part For example, NA Domination - Mass: 123
                                                                                        Nickname: Ryan G.
                                                                                        Tag: 123 
 "Tag:123" obviously not 123 but whatever the tag the user is in xD, this can also be put next to the users name as well to save space, for example: [123}Ryan G.

Thanks!

Just a couple of suggestions that would be cool! Thanks again for this flawless presence!

**Comment by callumok2004** [comment]
I will update the presence something this week :)

**Comment by Azrael206** [comment]
Thanks! My friends are like "Yo, how do the hell do you have it showing astr.io" I was like it's a secret just to piss them off and I sent them PreMiD after xD.

**Comment by doomlerd** [comment]
Please use the "[feature request](https://github.com/PreMiD/Presences/issues/new?template=feature_request.md)" template.
