### ISSUE TITLE
GogoAnime | gogoanime.pro

### ISSUE THREAD

**Issue by vzodac** [PreMiD/Presences#1122]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [x] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x ] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** ᴢᴏᴅɪᴀᴄ❥#7984

**What's the name of the service?**  https://gogoanime.pro/

**What should the Presence display?**  It should show what anime you are watching and what timestamp you are on and what have it where it shows if you have it paused or playing.

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by doomlerd** [comment]
remove the spacing between the checkboxes 
[ x] => [x]

**Comment by doomlerd** [comment]
It also does not seem to be region locked.

**Comment by doomlerd** [comment]
Has been added for a while, just under a different domain (.video/.io) : 
https://premid.app/store/presences/Gogoanime
