### ISSUE TITLE
Stan | stan.com.au

### ISSUE THREAD

**Issue by alazymeme** [PreMiD/Presences#1124]
**Prerequisites and essential questions**
* [x] Is it a popular site?
* [x] Is the website older than 2 months?
* [x] Is the site locked to a specific country/region?
* [x] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?**
www.stan.com.au | Stan

**What should the Presence display?**
What show is being watched/browsing, something similar to netflix (since it's a netflix-type service)

**If possible, please provide a logo for the service (512x512 minimum)**
![image](https://user-images.githubusercontent.com/12804673/75668358-f4492080-5cc4-11ea-8cde-558c9d3943be.png)

**Comment by jy1263** [comment]
ayyyy fellow aussie

**Comment by SlowLife1661** [comment]
I will take this
