### ISSUE TITLE
All MetaBrainz websites | metabrainz.org

### ISSUE THREAD

**Issue by fr0r** [PreMiD/Presences#1132]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
fror#9493
**What's the name of the service?** 
MetaBrainz | metabrainz.org
MusicBrainz | musicbrainz.org
MusicBrainz Picard | picard.musicbrainz.org
Cover Art Archive | coverartarchive.org
CritiqueBrainz | critiquebrainz.org
AcousticBrainz | acousticbrainz.org
BookBrainz | bookbrainz.org
ListenBrainz | listenbrainz.org
MessyBrainz | messybrainz.org
**What should the Presence display?** 
A lot of stuff (What page/book/album are you seeing, wiki, etc.)
**If possible, please provide a logo for the service (512x512 minimum)** 
*MetaBrainz*
![](https://menma.is-inside.me/xPzLZIqK.png)

*MusicBrainz*
![](https://menma.is-inside.me/emMQKmoD.png)

*MessyBrainz*
![](https://menma.is-inside.me/EzWcuhel.png)

*ListenBrainz*
![](https://menma.is-inside.me/Zyte3Uts.png)

*BookBrainz*
![](https://menma.is-inside.me/ETplt8Al.png)

*AcousticBrainz*
![](https://menma.is-inside.me/JRF84C2f.png)

*CritiqueBrainz*
![](https://menma.is-inside.me/EDFsBfEB.png)

*Cover Art Archive*
![](https://menma.is-inside.me/YuGwnPx3.png)

*MusicBrainz Picard*
![](https://menma.is-inside.me/nnFXk7Ua.png)

**Comment by doomlerd** [comment]
Will do this after searching by tags on the website is done ( due to the nature of the service ), and after I finish my tests, so approximately 3 weeks from now.

**Comment by frozaum** [comment]
aight this is abandoned
