### ISSUE TITLE
Plex Rich Presence - Add Plex Local Server Support

### ISSUE THREAD

**Issue by Azrael206** [PreMiD/Presences#1137]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
I would like for PreMiD to detect Plex when opening my plex media server from the start menu (Plex Local Server)

**Describe alternatives you've considered**
A cool feature would also be to have the presence show the movie you are currently viewing (not watching, it shows that), but when browsing your "Movies Library" and clicking on a movie "The Avengers" the presence goes from "Viewing Library: Movies" to "Plex". 

https://i.imgur.com/57GZIl2.png - viewing library 
https://i.imgur.com/micOsZP.png - viewing selected movie

**Additional context**
Important note for Bas950:

/com.plexapp.plugins.library - easy to detect

Discord: Johnᵐᵗ<space>#<space> 0031

**Comment by Bas950** [comment]
Added in: https://github.com/PreMiD/Presences/pull/1479
