### ISSUE TITLE
Senpa.io

### ISSUE THREAD

**Issue by Azrael206** [PreMiD/Presences#1144]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Johnᵐᵗ # 00 31

**What's the name of the service?** 
https://senpa.io/web/ - Senpa.io
**What should the Presence display?** Server name, Region of Server, Game mode, Current mass, and Elapsed time playing the game. tag player is in, what region the player is in at the main menu and what server is selected at the main menu, fps & ping

**If possible, please provide a logo for the service (512x512 minimum)** 
![512x512bb](https://user-images.githubusercontent.com/61640048/76016681-423f6d80-5eeb-11ea-8b2d-e12e9a17d4b8.jpg)

**Comment by EvilBrain** [comment]
![image](https://user-images.githubusercontent.com/49623340/77347794-ac07a600-6d38-11ea-95ab-c3dcd3c99a20.png)
its good ?

**Comment by Azrael206** [comment]
Looks great! Thank you for doing this, I thought this website was forgotten haha. By any chance, is it possible to add the tag the player is in? 

For example, Player: [Tag] Player1 

without tag, Player: Player1

**Comment by EvilBrain** [comment]
Yes! That is possible! I add that to the next update! You can contact me directly on the PreMid Discord server by pinging me (@Deleted 7.12i # 9425)!

**Comment by EvilBrain** [comment]
![image](https://user-images.githubusercontent.com/49623340/77358946-1f1a1800-6d4b-11ea-97fe-6d884c7ee45d.png)
c'est sympa pour toi?

**Comment by Azrael206** [comment]
Hey, sorry for getting back to you so late! I haven't had the time as crazy as it sounds, but yeah that looks awesome! I appreciate the time you put into this presence, it doesn't go unnoticed.

**Comment by Azrael206** [comment]
Also, whenever you can, I think it will make it easier for users to find other friends faster if the "73/200" was replaced with the "name of the server and region".

For example, "Playing on server: [NA] Dragon - Instant Merge"

Just a suggestion, but you have done plenty already, thank you again :)

**Comment by EvilBrain** [comment]
I cannot get the name and the region of the server
