### ISSUE TITLE
F1TV | f1tv.formula1.com

### ISSUE THREAD

**Issue by Lolihunter1337** [PreMiD/Presences#1153]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region? 
* [x] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**    "󠇰󠇰#8561"

**What's the name of the service?** https://f1tv.formula1.com - F1TV ( Formula 1 TV )

**What should the Presence display?** What race/interview your are watching.

**If possible, please provide a logo for the service (512x512 minimum)** 
![410yMUyZaVL](https://user-images.githubusercontent.com/17437302/76156232-9cad1980-60f7-11ea-82eb-4e7524fb3924.png)

**Comment by frozaum** [comment]
Not region locked.
