### ISSUE TITLE
Folding@home (Local)

### ISSUE THREAD

**Issue by ThisIsntNath** [PreMiD/Presences#1165]
This might not be possible seeing as it's extremely unique and the page runs locally, but Folding@home is basically a distributed computing project that allows anyone to harness their PC's power to simulate "protein folding" and help find a cure for viruses, etc.

**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [x] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Nath#0095

**What's the name of the service?** 
Folding@home - the site actually runs locally at http://127.0.0.1:7396.

**What should the Presence display?** 
Folding status - percentages for both CPU and GPU, maybe? Something like "Folding" on the first line, "CPU 5.31% | GPU 18.71%" on the second line for example?

**If possible, please provide a logo for the service (512x512 minimum)** 
![folding-at-home-logo](https://user-images.githubusercontent.com/62109782/76538319-08381380-6477-11ea-917e-803d1e088109.png)

**Comment by frozaum** [comment]
If the service has a web interface, yes, it is possible if you take some examples like the [VLC](https://premid.app/store/presences/VLC) presence

**Comment by theLMGN** [comment]
Alternately, the client runs at both the local IP, and https://client.foldingathome.org/. I'd try to make it, but I use macOS, and the macOS FaH client doesn't support GPU, so I'd have no idea way to test that

**Comment by SergioGlorias** [comment]
I have used Linux
Boot I have no GPU (at the time of comment)

But I can divide the CPU in half (4 colors divided 2)
to have 1 base as this would have 2 WUs working
![image](https://user-images.githubusercontent.com/9739913/78424057-d0318400-7662-11ea-81fb-1b6f2327a5bc.png)
![image](https://user-images.githubusercontent.com/9739913/78424073-e93a3500-7662-11ea-8a6b-8f54dd46dcd3.png)

But there is one thing that can complicate the development of the project
the site has a sleep system
causing the site to stop updating until it detects some movement of the mouse on the page
![image](https://user-images.githubusercontent.com/9739913/78424202-a75dbe80-7663-11ea-84e0-fc99cb3bd9e5.png)

I am also a donor and also creates this presence

**Comment by SnoweyFoxx** [comment]
:P
