### ISSUE TITLE
Floatplane | www.floatplane.com

### ISSUE THREAD

**Issue by tlgenzer** [PreMiD/Presences#1185]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [x] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Tlgenzer#8880
**What's the name of the service?** 
Floatplane | floatplane.com
**What should the Presence display?** 
The video you are watching on the site just like youtube.
**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/22181440/76835566-53e31800-67fd-11ea-8f9c-e5f32ca5f476.png)

**Comment by SnoweyFoxx** [comment]
I got this one 😎
