### ISSUE TITLE
Plex presence not updating status properly

### ISSUE THREAD

**Issue by aujwalkin** [PreMiD/Presences#1195]
**Describe the Bug**
The Plex presence displays the updated current activity (video watching, time remaining, and play/pause status) only after minimizing the video player.

**Steps to Reproduce**
https://cdn.discordapp.com/attachments/690565315284959262/690566384106602536/plexbug.webm
1. Open a video, it will show you're watching that.
2. Pause the video, it will still say it is playing.
3. Minimize the video player (not browser), it will correctly say paused.
4. After the episode is finished it will simply say "00:00 left" even when watching the next episode, until you minimize.

**Expected Behavior**
Display the updated/current information in real time.

**Environment**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 74.0 (64-bit)

**Comment by Bas950** [comment]
For information about the status of this bug report see #1129

**Comment by Bas950** [comment]
Should be fixed in: https://github.com/PreMiD/Presences/pull/1479
If not contact me in Discord, Bas950#0950
