### ISSUE TITLE
Randomtube | youtube-playlist-randomizer.valami.info

### ISSUE THREAD

**Issue by paz** [PreMiD/Presences#1203]
**Prerequisites and essential questions** 
* [X] Is it a popular site? i thought so? 
* [X] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  [@paz#0001](https://dscrd.co/131990779890630656)

**What's the name of the service?** 
**Youtube** playlist randomizer (randomtube) http://youtube-playlist-randomizer.valami.info/
**What should the Presence display?** 
Same as youtube, it's just adds true random/shuffle for playlists
**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by paz** [comment]
![Randomtube](https://user-images.githubusercontent.com/7887281/80348026-c389ff80-889f-11ea-87ce-431dbefe4b46.png)

**Comment by EncryptedDev** [comment]
I don't think the service is a thing anymore, close the issue please
