### ISSUE TITLE
Joyn | www.joyn.de

### ISSUE THREAD

**Issue by N0chteil** [PreMiD/Presences#1215]
**Prerequisites and essential questions**
* [x] Is it a popular site?
* [x] Is the website older than 2 months?
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** N0chteil ^^#6257

**What's the name of the service?** https://www.joyn.de

**What should the Presence display?** What you are looking at (As with the Netflix RPC)
**If possible, please provide a logo for the service (512x512 minimum)**

![Joyn-Icon](https://user-images.githubusercontent.com/53608074/77323867-35f24780-6d16-11ea-893c-dabdf1d05ded.jpg)

**Comment by OfficialCRUGG** [comment]
Why does this have the Paid Service Label? You just need the Subscription to watch specific series. There are many free ones and there is no need for one to have the Subscription to develop the Presence.

**Comment by N0chteil** [comment]
> Why does this have the Paid Service Label? You just need the Subscription to watch specific series. There are many free ones and there is no need for one to have the Subscription to develop the Presence.

I didn't choose this in the beginning, but Bas950 added it again.

**Comment by Bas950** [comment]
Cause someone told me to add it xD

**Comment by N0chteil** [comment]
I do not know how to remove a label xD

**Comment by Bas950** [comment]
I did it for you xD

**Comment by N0chteil** [comment]
AlhamduliMustafa

**Comment by N0chteil** [comment]
Can you tell me how? xD
