### ISSUE TITLE
https://www.jetanime.cc | jetanime.cc

### ISSUE THREAD

**Issue by Zaharno** [PreMiD/Presences#1217]
What's the name of the service?
Jetanime
https://www.jetanime.cc

What should the Presence display?
anime, episode and time remaining

Why do you want support for this service?
Jetanime is a french website with all animes and the new anime, it's a anime website in streaming

Are you able to provide an image for the service? (512x512 minimum)
No they don't have one

**Comment by frozaum** [comment]
Please use the correct format: https://github.com/PreMiD/Presences/issues/new?template=service_request.md
