### ISSUE TITLE
Implement presence status for "new" moderation view

### ISSUE THREAD

**Issue by alexbcberio** [PreMiD/Presences#1275]
**Describe the Bug**
Twitch has introduced a new view for moderators with more control over the stream. This new view is handled in a new url location: `https://www.twitch.tv/moderator/<channelName>`.

Currently the presence shows "hosting <channelName>", this location shold be handled as if the user was viewing the channel (same as `https://www.twitch.tv/<channelName>`)

**Steps to Reproduce**

1. Open a stream where you're an administrator
2. Press on the sword (left to "chat" button) located at the bottom of the chat.
3. You're redirected to the channel mod view.

**Expected Behavior**
Presence status should be the same as if you were on the standard channel view.

**Screenshots**

Current status on `/moderator/<channelName>`
![image](https://user-images.githubusercontent.com/22194879/78252540-4ca55500-74f3-11ea-8e65-3fdf026f5f7b.png)
Status on `/<channelName>`
![image](https://user-images.githubusercontent.com/22194879/78252617-6c3c7d80-74f3-11ea-8a0a-e5771df1a7f3.png)

**Environment**

- OS: Windows 10
- Browser: Opera
- Version: 67.0.3575.97

**Additional context**

Direct message me on Discord (already in premid discord and same username as on github) if you need any further details or the structure of the "moderator view".

**Comment by doomlerd** [comment]
Another small bug was introduced after this so i'll keep it open.
