### ISSUE TITLE
Google Docs word counter

### ISSUE THREAD

**Issue by Modzin** [PreMiD/Presences#1286]
**What is the name of the service?**
Google Docs
**What is the suggestion you have?**
Information on the word count of the project. If no text in the document highlighted, it should have something like '3000 / 3000 words'. When portion of text is highlighted, the word counter would change into '500 (amount of words highlighted) / 3000 (total word count) words'

**Comment by Alanexei** [comment]
@callumok2004

**Comment by doomlerd** [comment]
Wrong template, please repost it again with the appropriate one.
