### ISSUE TITLE
any way to make the "Custom Status" changeable for the user?

### ISSUE THREAD

**Issue by grigorypavlov** [PreMiD/Presences#1292]
i really like this presence, but itd be a lot nicer if i could change the main text of my status. is this possible to do?

sincerely
grigory

**Comment by callumok2004** [comment]
Sadly, this is not currently possible.

**Comment by doomlerd** [comment]
It is possible if you clone the repo, create an app on discord dev portal, modify the presences's clientID to your app, and load it locally in the extension ( by holding shift while having it open ).
