### ISSUE TITLE
Update for Reading/typing RP status when in discord.gg

### ISSUE THREAD

**Issue by erwin1234777** [PreMiD/Presences#1301]
**Describe the Bug**
The presence isnt being updated on the web client when in the specified page (discord.gg)

**Steps to Reproduce**
1.Open discord.gg. 
2.Log in.
3. Go to any guild, any channel. Presence should not be updated when inside while reading nor typing.

**Expected Behavior**
RP should be updated and show the reading/typing status on the channel/guild/dm

**Screenshots**
self explanatory

**Environment**
Windows 10 Home 64x
Chrome Latest version as of this report

**Additional context**
Nothing needed

**Comment by Bas950** [comment]
Fixed in https://github.com/PreMiD/Presences/pull/1299
