### ISSUE TITLE
The presence of roblox doesn't appear

### ISSUE THREAD

**Issue by AlexCFW-DevOfPhp** [PreMiD/Presences#1303]
**Describe the Bug**
   The presence of roblox doesn't appear on any page I go to on the roblox site

**Steps to Reproduce**

[https://streamable.com/s/fnbqn5](url)

**Expected Behavior**

**Screenshots**

<a href="https://ibb.co/5FJvjMw"><img src="https://i.ibb.co/tX1c2mF/Screenshot-328.png" alt="Screenshot-328" border="0"></a>
**Environment**

- OS: Windows 10
- Browser: Chrome
- Version: 80.0.3987.149
  

**Additional context**

**Comment by doomlerd** [comment]
Confirmed to be still working, make a support ticket and we'll assist you with the issue.
