### ISSUE TITLE
Kodi support | www.kodi.tv

### ISSUE THREAD

**Issue by Cheapek** [PreMiD/Presences#1304]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Cheap_#2037

**What's the name of the service?**  Kodi

**What should the Presence display?**  What movie/tv show is now playing, something like Netflix.

**If possible, please provide a logo for the service (512x512 minimum)** 
![Kodi logo](https://kodi.wiki/images/f/fe/Thumbnail-symbol-darkbg.png)

**Comment by SnoweyFoxx** [comment]
maybe
