### ISSUE TITLE
[Presence | Bug] Branitube

### ISSUE THREAD

**Issue by maz1no** [PreMiD/Presences#1309]
**Describe the Bug**
Presence does appear only 'Browsing', as if we were still on the home page even we're in a episode page.

**Steps to Reproduce**

1. Visiting an episode page
2. Going to Discord
3. Not showing the video details, just only "Browsing"

**Expected Behavior**
Presence showing details of the video.

**Environment**

- OS: Windows 10
- Browser: Chrome
- Version: 80.0.3987.163 (64-bit)

**Additional context**
They added one more player to the website.

**Comment by DarkVillager** [comment]
Can't reproduce.
![image](https://user-images.githubusercontent.com/42322979/118105714-094b3480-b3dd-11eb-9133-d245af954281.png)
