### ISSUE TITLE
Google Domains | domains.google

### ISSUE THREAD

**Issue by OfficialCRUGG** [PreMiD/Presences#1316]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  CRUGG#0001

**What's the name of the service?** 
domains.google | Google Domains

**What should the Presence display?** 
The Domain "Settings" Pages etc.

**If possible, please provide a logo for the service (512x512 minimum)** 
https://domains.google/static/images/logo/new_logo_beta.svg
(Would need to be cut, I can also provide a PNG with just the Logo if required)

I don't have a Domain on Google Domains nor can I buy one in Germany, so I cannot access the full part of the Website.

**Comment by Cairo2k18** [comment]
@frozaum this is region restricted
