### ISSUE TITLE
BBC Sounds | bbc.co.uk/sounds

### ISSUE THREAD

**Issue by MattTMLive** [PreMiD/Presences#1338]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Matt#8038
**What's the name of the service?** 
www.bbc.co.uk/sounds | BBC Sounds
**What should the Presence display?** 
What you're listening to (show name/time remaining). Different if you're listening live. They have a nice epoch timetable system in their website code as well.
**If possible, please provide a logo for the service (512x512 minimum)** 
![bbcsounds](https://user-images.githubusercontent.com/40129227/79413393-bf0c3f80-7f9f-11ea-9359-b5a2900fc6f9.png)

**Comment by Isa27-0** [comment]
Yeah, it's still open, even though it's already been resolved. (#3209)

**Comment by MattTMLive** [comment]
Yeah, I saw this a while back. Thanks to the person who added it 😄
