### ISSUE TITLE
Apple Music doesn't work anymore

### ISSUE THREAD

**Issue by xHatchx** [PreMiD/Presences#1372]
**Describe the Bug**

The rich presence integration for Apple Music isn't working anymore.

**Steps to Reproduce**

1. Open Apple Music
2. Play a song
3. It doesn't show up in Discord

**Expected Behavior**

Discord should show the song that is currently playing

**Screenshots**

**Environment**

- OS: 
- Browser: 
- Version: 
  
OS: Windows 10
Browser: Firefox
Version: 75.0

**Additional context**

I think the problem occurs because Apple Music switched from "beta.music.apple.com" to "music.apple.com"

**Comment by frozaum** [comment]
going to check it

**Comment by IgorZimmermann** [comment]
Can confirm.. It still doesn't work.

**Comment by Smaltin** [comment]
I fixed this issue 2 days ago, if this could be closed @frozaum

**Comment by IgorZimmermann** [comment]
Thanks for the fix! 😊
