### ISSUE TITLE
Einthusan (Indian Movie Website)

### ISSUE THREAD

**Issue by Xpert87** [PreMiD/Presences#1374]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Xpert#6337

**What's the name of the service?** Einthusan

**What should the Presence display?** The presence should display the movie you are watching, the director of the movie (if possible) , and the time remaining for the movie.

**If possible, please provide a logo for the service (512x512 minimum)**  
![512x512bb](https://user-images.githubusercontent.com/62971625/79923861-7079fd80-8404-11ea-860b-cdfae0e5d60e.jpg)

**Comment by Gurrman375** [comment]
Can you provide a description for the website?

**Comment by Gurrman375** [comment]
So I've gotten the base molded but I need to figure out if I need regexp.
Also how does the music part of the site work?

**Comment by Xpert87** [comment]
On my end, the music part of the site doesn't work. I would forget that part and focus on the movie section. However, if Einthusan fixes the music part of the site, I'll let you know.

**Comment by Gurrman375** [comment]
![image](https://user-images.githubusercontent.com/25113575/80434205-110d6900-88ae-11ea-9b06-99441dce7fd6.png)
![image](https://user-images.githubusercontent.com/25113575/80434222-1e2a5800-88ae-11ea-886e-89874aea8490.png)
![image](https://user-images.githubusercontent.com/25113575/80434254-38643600-88ae-11ea-95a9-8b8a6136b92d.png)
I am almost done with the presence.

**Comment by Xpert87** [comment]
Looks amazing! One quick thing. For the director part of the presence, that's not the director. That's one of the actors in the movie. If you go to any movie and scroll down, you'll see a bunch of faces with names. It should say who the director of the movie is when it goes through all of the actors. I've provided a picture of the same movie and where the director is. 
![{F80DB2F8-F124-4F01-83EE-7CC4A627CD08} png](https://user-images.githubusercontent.com/62971625/80434732-f7c9e400-88d0-11ea-8e3a-c76e980af428.jpg)

**Comment by Gurrman375** [comment]
Thanks for reporting.
For One of the reference movies I was using the director was not listed. If you have one that doesn't list the director that would be good. Currently it's fixed.
![image](https://user-images.githubusercontent.com/25113575/80435231-d22ce280-88b0-11ea-90c4-3cdc5a033557.png)

**Comment by Gurrman375** [comment]
Okay The presence is complete. Please close this request.

**Comment by Bas950** [comment]
Closed by https://github.com/PreMiD/Presences/pull/1421
https://premid.app/store/presences/Einthusan
