### ISSUE TITLE
Repl.it fails to show the student links

### ISSUE THREAD

**Issue by Gurrman375** [PreMiD/Presences#1377]
**Describe the Bug**

The presence detects the site as a valid and show a presence but fails to show any vaild info other than just browsing a site.
**Steps to Reproduce**

Visit https://repl.it/student.

**Expected Behavior**

To show: Viewing Classes or Viewing Student Page
**Screenshots**

![image](https://user-images.githubusercontent.com/25113575/79936060-4972fa00-840b-11ea-9e34-69e030e8bdd4.png)
![image](https://user-images.githubusercontent.com/25113575/79936082-57c11600-840b-11ea-88c5-a097f788116c.png)
![image](https://user-images.githubusercontent.com/25113575/79936136-7a532f00-840b-11ea-9783-e7c05c275813.png)

**Environment**

- OS: Windows 10
- Browser: Chrome 
- Version: 1.3.1
  

**Additional context**

Links:
https://repl.it/student
https://repl.it/student/classrooms/
      Elements to grab:
      The Class Name (EXAMPLE = CS 111 Spring 2020):
      document.querySelector("#classroomsPage > header > h2")
      The Program Language or Description (EXAMPLE = Java):
      document.querySelector("#classroomsPage > header > div")
https://repl.it/student/submissions/
      Elements To Grab:
      Title:
      document.querySelector("#root > div > div:nth-child(2) > div > div.jsx-1946904232.dynamic-header-center")

**Comment by MrBartusek** [comment]
![image](https://user-images.githubusercontent.com/23432278/95995250-87d4f900-0e31-11eb-9212-5f5ba03e862e.png)
`repl.it/student` and `repl.it/student/classrooms` are 404 now, can be closed
