### ISSUE TITLE
Ignite Radio

### ISSUE THREAD

**Issue by EthanTK** [PreMiD/Presences#1379]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Ethan#6302

**What's the name of the service?** 
Ignite - https://igniteonline.net/

**What should the Presence display?** 
The presence needs to display the logo, the station name, what Presenter is on and what current song it's playing.

**If possible, please provide a logo for the service (512x512 minimum)** 
https://imgur.com/uMxC88K.png

**Comment by frozaum** [comment]
Please edit your issue by adding a URL of the website.

**Comment by EthanTK** [comment]
> Please edit your issue by adding a URL of the website.

@frozaum Added

**Comment by frozaum** [comment]
Hello @EthanTK, the website/domain must be at least 2 months old.
![whois](https://user-images.githubusercontent.com/34042085/80025235-ae375e80-84b6-11ea-8fb0-453a64cb2733.png)

Please re-apply in 2 months.
