### ISSUE TITLE
StreamKiste & KinoZ | StreamKiste.tv\KinoZ.to 

### ISSUE THREAD

**Issue by Konstey** [PreMiD/Presences#1400]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** konstey#0217 

**What's the name of the service?** kinoz.to and streamkiste.tv its the same like bs.to but you can watch movies 

**What should the Presence display?** watching a movie same like on bs.to or s.to 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Venipa** [comment]
will do this one, will probably come in a pack (hd-streams.org, streamkiste.tv, kinox/kinoz)
