### ISSUE TITLE
Joyn.de

### ISSUE THREAD

**Issue by Feyagirl** [PreMiD/Presences#1402]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

❤️ Feyagirl ❤️ ACNH ❤️#4976

**What's the name of the service?** 

joyn.de

**What should the Presence display?** 

Die presence soll den namen der serie/film anzeigen die man gerade schaut so wie den namen der folge / staffelnummer, und die stunde/minute/sekunde (zeit) anzeigen.
Sorry ich kann kein englisch deswegen die google übersetzung

The presence should show the name of the series / film you are watching as well as the name of the sequence / season number, and the hour / minute / second (time).
Sorry I don't speak english so google translation

**If possible, please provide a logo for the service (512x512 minimum)** 

![joyn-logo](https://user-images.githubusercontent.com/61389926/80283102-a45f6680-8715-11ea-968c-6f915364a7e7.jpg)

**Comment by frozaum** [comment]
duplicate #1215
