### ISSUE TITLE
YGGTorrent | yggtorrent.si

### ISSUE THREAD

**Issue by marcpinet** [PreMiD/Presences#1404]
**Prerequisites and essential questions**>
 * [x]  Is it a popular site?
 * [x]  Is the website older than 2 months?
 * [ ]  Is the site locked to a specific country/region?
 * [ ]  Is the site a paid service? (e.g. Netflix, Hulu)
 * [x]  Does the website feature NSFW content? (e.g. porn, etc...)
 * [ ]  Are you a donator/patron?
 * [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

 **What's your Discord username?** Roux#3064
 
 **What's the name of the service?** https://www4.yggtorrent.li

**What should the Presence display?** It should show which torrent are you looking for/browsing.
 
**If possible, please provide a logo for the service (512x512 minimum)**

![image](https://user-images.githubusercontent.com/52708150/80286257-91a35c80-872a-11ea-98a3-183fdbe665e0.png)

**Comment by Roux55** [comment]
Sooo when are you going to add this website ?

**Comment by Roux55** [comment]
up

**Comment by ririxidev** [comment]
there arent any bumps etc. if someone will want to do it, will do.

**Comment by marcpinet** [comment]
okay
