### ISSUE TITLE
Team Shazoo | www.teamshazoo.uk

### ISSUE THREAD

**Issue by RichieMedia** [PreMiD/Presences#1406]
- [x] Is it a popular site? Its a semi-popular eSports team.
- [x] Is the website older than 2 months?  Yes.
- [x] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) No
- [ ] Does the website feature NSFW content? (e.g. porn, etc...) No
- [ ] Are you a donator/patron? No
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? Yes

**What's your Discord username?**  rvb53#2725

**What's the name of the service?**  https://www.teamshazoo.uk/

**What should the Presence display?**  Should show the team shazoo logo. "Playing a game" with the title of "Team Shazoo" -- there should be an option to chose weather it says "Twitch Streamer" or "Content Creator" -- if not, then "Viewing Home Page" etc.

**If possible, please provide a logo for the service (512x512 minimum)**  https://user-images.githubusercontent.com/64364124/80309639-36c34100-87ce-11ea-84c6-fdf3b1995a77.jpg

**Comment by DiacoreHD** [comment]
If any other specifics or info is needed please send a DM on discord :D

**Comment by frozaum** [comment]
Not region-locked.

**Comment by DiacoreHD** [comment]
It is locked to the UK i believe?
