### ISSUE TITLE
JKanime | JKanime.net

### ISSUE THREAD

**Issue by Qepz** [PreMiD/Presences#1415]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Lyx#5025 

**What's the name of the service?** www.jkanime.net | JKanime 

**What should the Presence display?** Me gustaria que se muestre el anime que estoy viendo y el tiempo que falta por terminar a cada capitulo. 

**If possible, please provide a logo for the service (512x512 minimum)** 
![screen-0](https://user-images.githubusercontent.com/62877149/80403704-a7796480-8885-11ea-8954-4ad91785d275.jpg)

**Comment by Slowftw** [comment]
interesting

**Comment by Venipa** [comment]
website is dead
