### ISSUE TITLE
Canais Globo | canaisglobo.globo.com

### ISSUE THREAD

**Issue by ysauron2** [PreMiD/Presences#1423]
Prerequisites and essential questions 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  ! Lieselotte#0052

**What's the name of the service?**  https://globosatplay.globo.com

**What should the Presence display?**  should inform which channel, the name of the program I am watching and the duration of each program

**If possible, please provide a logo for the service (512x512 minimum)**  https://imgur.com/pBc2Mjc

**Comment by frozaum** [comment]
going to assign me since i can try to request access for the platform.

**Comment by frozaum** [comment]
Got it!
![image](https://user-images.githubusercontent.com/34042085/80632399-9bc8a200-8a2d-11ea-9ab7-bb63a69488e9.png)

**Comment by fr0r** [comment]
instagram 2
![image](https://user-images.githubusercontent.com/34042085/93260805-41c83f00-f778-11ea-9aca-a0043d9078fb.png)

**Comment by fr0r** [comment]
presence is almost done, just need to fix something related to video detection.

**Comment by fr0r** [comment]
update: almost done.

![image](https://user-images.githubusercontent.com/34042085/113790193-25d9ba00-9717-11eb-81df-b01a78f62587.png)
