### ISSUE TITLE
Dizilla | dizilla.com

### ISSUE THREAD

**Issue by Tolhann** [PreMiD/Presences#1426]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  ℝ𝔼𝔻#6666

**What's the name of the service?** https://dizilla.com | Dizilla 

**What should the Presence display?**  Which series watched, what episode, what season, how many minutes it has finished and whether it is watching at that moment, that is, what should be done for other series sites, in short, it should be the same.

**If possible, please provide a logo for the service (512x512 minimum)** 
![imagen-dizilla-0big](https://user-images.githubusercontent.com/64492807/80520248-d846c000-8991-11ea-980c-ea5c81b8002a.png)

**Comment by eggsywashere** [comment]
![image](https://user-images.githubusercontent.com/13917975/81132397-f3e43480-8f56-11ea-90dd-d56b7abbdf89.png)

**Comment by Tolhann** [comment]
![atom-bombasi-atilinca-yapilmasi-gerekenler_1264093](https://user-images.githubusercontent.com/64492807/81182303-4acd2680-8fb6-11ea-83a1-d73b9ea1e508.png)

**Comment by eggsywashere** [comment]
back here
