### ISSUE TITLE
Crunchyroll presence is stuck on browsing

### ISSUE THREAD

**Issue by Ikuya0** [PreMiD/Presences#144]
**Describe the bug**
When watching an anime on Crunchyroll, the discord presence is stuck on "browsing"

**To Reproduce**
1. Just watch an anime on crunchyroll

**Expected behavior**
To show what anime / episode I'm watching

**Desktop (please complete the following information):**
 - Browser: Chrome

**Additional context**
I did pay for patreon to get access to v2.0

**Comment by frozaum** [comment]
@TheDropX
