### ISSUE TITLE
Webtoons

### ISSUE THREAD

**Issue by YoElectric** [PreMiD/Presences#1445]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ x] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Electric#5044

**What's the name of the service?**  https://www.webtoons.com/en/ | WEBTOON

**What should the Presence display?**  WebToons with Webtoon icon and Reading (insert series name and what chapter they are on) example is Reading Tower Of God Chapter 201

**If possible, please provide a logo for the service (512x512 minimum)** 
![Naver_Line_Webtoon_logo](https://user-images.githubusercontent.com/64504975/80629182-784b2a80-8a20-11ea-87bb-e2a6284bf657.png)

**Comment by frozaum** [comment]
[Already added](https://premid.app/store/presences/Webtoon) and duplicate #162
