### ISSUE TITLE
Could not load content Error: status code 404

### ISSUE THREAD

**Issue by Gurrman375** [PreMiD/Presences#1465]
**Describe the Bug**

Whenever coding a presence in TS for the first run you get the error: 
Could not load content for yoursite/presence.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)
**Steps to Reproduce**

You can use this example:
1. In your repo make WatchCartoonsOnline:
![image](https://user-images.githubusercontent.com/25113575/80774456-f0dde400-8b11-11ea-8e1d-fcaa792b60da.png)
2. make presence.ts
```typescript
var presence = new Presence({
    clientId: "" // If you want my client link dm me at GURRMAN375D#3014
});
presence.on("UpdateData", async() => {
    var presenceData: presenceData = {
        largeImageKey: "logo"
    };
    var browsingStamp = Math.floor(Date.now() / 1000);
    if(document.location.pathname == "/"){
        presenceData.startTimestamp = browsingStamp;
        presenceData.details = "Viewing home page";
    }
    else{
        console.log("Unable to read");
    }
    if (presenceData.details == null) {
        presence.setTrayTitle(); 
        presence.setActivity();
    } 
    else {
        presence.setActivity(presenceData);
    }
});
```
Make a dist folder and put in that folder metadata.json:
```json
{
    "author": {
      "name": "GURRMAN375D",
      "id": "446528923535278082"
    },
    "service": "Watch Cartoons Online",
    "description": {
      "en": "We are cartoon’s fans, we build this website for all cartoon lovers. We are small dedicated team, we want to help everyone can find and watch free their cartoon. Maybe you can find your childhood cartoon in here: watchcartoonsonline.info."
    },
    "url": "watchcartoonsonline.info",
    "version": "1.0.0",
    "logo": "https://i.imgur.com/gRKaZaW.png",
    "thumbnail": "https://i.imgur.com/CKMIGQX.png",
    "color": "#3232ff",
    "tags": ["watch-movies","cartoon"],
    "category": "videos"
}
```
![image](https://user-images.githubusercontent.com/25113575/80774498-081cd180-8b12-11ea-9c76-6d5d3e216fb6.png)
Also Make a tsconfig.json before making dist:
```json
{
    "extends": "../tsconfig.json",
    "compilerOptions": {
      "outDir": "./dist"
    }
 }
```
Then Load in to your extension and refresh the page.
**Expected Behavior**

What is expected to happen is that it binds to the website
**Screenshots**

![image](https://user-images.githubusercontent.com/25113575/80774233-4239a380-8b11-11ea-834a-2d143dee3bc9.png)
![image](https://user-images.githubusercontent.com/25113575/80774254-4e256580-8b11-11ea-8000-a52f8ee07c9b.png)
![image](https://user-images.githubusercontent.com/25113575/80774274-5f6e7200-8b11-11ea-8690-8c4c87d3dcfa.png)

**Environment**

- OS:  Windows 10
- Browser: Chrome
- Version:  81.0.4044.129
  

**Additional context**

**Comment by Gurrman375** [comment]
It shows in log that it is functioning correctly, but it keeps the same message.
![image](https://user-images.githubusercontent.com/25113575/80828487-33e39a00-8b9a-11ea-950d-9492ea970aa8.png)

**Comment by doomlerd** [comment]
1. Don't use `iframe: false` when not using it
2. You never send any data to the extension.

**Comment by Gurrman375** [comment]
1. I did try without iframe but the message continued.
2. I don't understand what you mean by no data was sent. If you go to the main site it should show the logo image, with the text Viewing home page and starting a browsing stamp.

**Comment by Gurrman375** [comment]
I'm an idiot.

**Comment by doomlerd** [comment]
@Gurrman375 was it fixed?

**Comment by Gurrman375** [comment]
yes I posted the Updated code above
