### ISSUE TITLE
Board Game Arena | boardgamearena.com

### ISSUE THREAD

**Issue by bastien09** [PreMiD/Presences#1468]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Calys#9504

**What's the name of the service?** https://boardgamearena.com/ | Board Game Arena

**What should the Presence display?** The game you're currently playing

**If possible, please provide a logo for the service (512x512 minimum)** Not exactly 512, but that's the highest resolution I found for their logo https://x.boardgamearena.net/data/newsimg/logo2016.png

**Comment by frozaum** [comment]
Can you prove that you are a Patron/Donator?

**Comment by DoggoKt** [comment]
Working on it!

**Comment by bastien09** [comment]
> Working on it!

Thanks ! :partying_face:
