### ISSUE TITLE
Coub | Coub.com

### ISSUE THREAD

**Issue by ImLuxion** [PreMiD/Presences#1470]
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?*Luxion#7001* 

**What's the name of the service?*www.coub.com*

**What should the Presence display?*Home page, in which community i'm browsing * 

**If possible, please provide a logo for the service (512x512 minimum)*
![download](https://user-images.githubusercontent.com/60518831/80850750-e0059f00-8bf3-11ea-946d-61bdc29002fc.png)
*

**Comment by Mirazex** [comment]
I will do it
