### ISSUE TITLE
CBS All Access | www.cbs.com

### ISSUE THREAD

**Issue by ChampOTF** [PreMiD/Presences#1486]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Champ#0001

**What's the name of the service?** 
CBS All Access

**What should the Presence display?** Current Season number, episode number & name, movie name, time elapsed, etc.

**If possible, please provide a logo for the service (512x512 minimum)** 
![d6e805dc84423422610b69a38da50813f9eb2143c85136931c6b66f9d59fe071](https://user-images.githubusercontent.com/61640048/80921243-2ddced00-8d43-11ea-9426-4af8d48b8124.png)

Additional Notes? You can try it for free so no purchase is necessary, only if you choose to continue the service after the trial.

**Comment by frozaum** [comment]
Videos are region-locked
