### ISSUE TITLE
animedao

### ISSUE THREAD

**Issue by DoublePum4s** [PreMiD/Presences#1487]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 

**What should the Presence display?** 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by DoublePum4s** [comment]
DoublePum4s is my username  
The name of the service is animedao

**Comment by frozaum** [comment]
[https://premid.app/store/presences/AnimeDao](already added)
