### ISSUE TITLE
Starz Rich Presence Bug (Not showing movie or show activity)

### ISSUE THREAD

**Issue by ChampOTF** [PreMiD/Presences#1490]
**Describe the Bug**

I've been watching a movie in STARZ for about 45 mins now and the RP still shows "STARZ - Browsing" it doesn't show the movie name & time elapsed. I've refreshed the site, disabled/enabled the extension, and none of that seems to fix the issue
**Steps to Reproduce**

1. Log in to STARZ
2. Choose Movie
3. Play Movie
3. Go to discord - it will say "STARZ - Browsing" 

**Expected Behavior**

I expected the rich presence to show the movie name & time elapsed of the movie I'm currently watching
**Screenshots**

https://i.imgur.com/gtONCYz.png - 45 mins in 
https://i.imgur.com/duoh4DG.png - still shows browsing
**Environment**

- OS:  Windows 10
- Browser:  Chrome
- Version:  Version 81.0.4044.129 (Official Build) (64-bit)
  

**Additional context**

I just tried to see if it works for shows, and it's doing the same thing as well. Now it's not even showing the RP on my profile, I keep refreshing & it comes and goes, definitely something wrong behind the scenes

Here's what it shows in console - https://i.imgur.com/8HlLGdR.png

**Comment by frozaum** [comment]
Hello, I just want to know some questions, only the movies are affected?

**Comment by Azrael206** [comment]
Shows are affected too, I playing a show rn as we speak, and it still shows "browsing" the show is called "Power"
