### ISSUE TITLE
4chan | 4chan.org/4channel.org

### ISSUE THREAD

**Issue by ILiKChikun** [PreMiD/Presences#1491]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** ILiKChikun#8403

**What's the name of the service?** 
4chan.org/4channel.org | 4chan

**What should the Presence display?** 
Browsing (name of board)
ex. Browsing /b or Browsing jp/

**If possible, please provide a logo for the service (512x512 minimum)** 
![logo-transparent](https://user-images.githubusercontent.com/20148447/80948211-a8e3e900-8dbf-11ea-97ae-efa99baf9621.png)

**Comment by ILiKChikun** [comment]
misread image resolution requirement as 512 maximum, here's an alternative 
![00rdaM0TQOOz0mjOlgMSr1g-1 fit_scale size_2698x1517 v1569484003](https://user-images.githubusercontent.com/20148447/80948682-9ddd8880-8dc0-11ea-8e88-c89999813a9d.jpg)

**Comment by Slowftw** [comment]
👀

**Comment by frozaum** [comment]
Edited some stuff to add 4channel.org here

**Comment by Slowftw** [comment]
nsfw or not
