### ISSUE TITLE
Super Animes | www.superanimes.org

### ISSUE THREAD

**Issue by nenilves** [PreMiD/Presences#1498]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Nenilves#5642

**What's the name of the service?** 
https://www.superanimes.org

**What should the Presence display?** 
must show the anime you are watching at the moment, what is the episode and the elapsed time

**If possible, please provide a logo for the service (512x512 minimum)** 
https://lh3.googleusercontent.com/gAj3IvJ9YU2Z8nY6udc3PuN-kK5nDT4iEPowIRYVtBhZIiaisl2J8hRKV0dRSuZHlbQ

**Comment by Sazzo** [comment]
I will make that presence.
