### ISSUE TITLE
Media Player Classic - Home Cinema (MPC-HC)

### ISSUE THREAD

**Issue by ghost** [PreMiD/Presences#1514]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** namles#5949

**What's the name of the service?** https://mpc-hc.org/ | Media Player Classic - Home Cinema

**What should the Presence display?** Title of video playing, Current time/time remaining of video playing, Total time of video playing.

**If possible, please provide a logo for the service (512x512 minimum)** 
![logo-256x256](https://user-images.githubusercontent.com/25493005/81330789-9f33dd00-906e-11ea-828e-7d311ecf3db9.png)

**Comment by Scomz** [comment]
Just want to add that this is not a site, but an app similar to VLC Media Player. MPC-HC has as a built in web interface like VLC, so it should function similarly.

**Comment by Scomz** [comment]
Something akin to this: https://github.com/angeloanan/MPC-DiscordRPC
The one above interferes with PreMiD though, so it would be best if it was a presence in premid.

**Comment by Slowftw** [comment]
@Scomz 
The logo does not meet the minimum size requirements (512x512)

**Comment by LewisTehMinerz** [comment]
Might be best to hold off on doing these types of presences (using a web API of a program) until PreMiD supports programs.

**Comment by doomlerd** [comment]
> Might be best to hold off on doing these types of presences (using a web API of a program) until PreMiD supports programs.

support will be very basic, still won't be better than the current one

**Comment by Razi1660** [comment]
Will PreMiD have support for programs anytime soon?

**Comment by Isa27-0** [comment]
If I'm not mistaken, the program has been discontinued since 2017. It may be difficult to create a presence from the API.

**Comment by Razi1660** [comment]
Development on it is being continued unofficially here https://github.com/clsid2/mpc-hc

**Comment by ririxidev** [comment]
There is already presence for this program no need to have it in PreMiD.

**Comment by itsmeboy0** [comment]
> There is already presence for this program no need to have it in PreMiD.

@ririxichan Not built-in but third party (much like VLC before). This is still needed and would be great if it was on PreMiD, so I don't need to setup another program.

**Comment by Isa27-0** [comment]
> > There is already presence for this program no need to have it in PreMiD.
> 
> @ririxichan Not built-in but third party (much like VLC before). This is still needed and would be great if it was on PreMiD, so I don't need to setup another program. Can this be reopened?

It's been a long time since you answered this question, so I don't think Ririxi can answer (even because she's not checking Issues around here), just @ImRodry @TheDropX can answer for you.

**Comment by ImRodry** [comment]
Yeah no I don’t do tickets anymore but PreMiD doesn’t support programs yet so this wouldn’t work from what I understood

**Comment by itsmeboy0** [comment]
> Yeah no I don’t do issues anymore but PreMiD doesn’t support programs yet so this wouldn’t work from what I understood

VLC is available in PreMiD. It uses it's Web API to get its rich presence info. We can do the same thing for MPC-HC.

**Comment by itsmeboy0** [comment]
> Might be best to hold off on doing these types of presences (using a web API of a program) until PreMiD supports programs.

If this is your concern, then why is VLC available in PreMiD? The best solution would be to use Web APIs until PreMiD supports programs.

**Comment by itsmeboy0** [comment]
> Yeah no I don’t do issues anymore

Maybe someone who does? @EncryptedDev

**Comment by rollingmoai** [comment]
Looks like someone opened another issue: #6446

**Comment by angeloanan** [comment]
Heya, I was mentioned on #6446 as an author of a project which does Discord Rich Presence integration for MPC-HC. I apologize for not responding in a timely manner; Honestly, I have forgotten that I was pinged, but also completely forgot that I created an integration for MPC-HC.

In the past, I've been thinking of moving the integration into a better / more established integration platform as running a node app for a singular program / presence integration is kinda painful UX-wise.

Is there any ongoing efforts for this specific integration or is this issue up for grab? If I have the time, I might be able to help contributing to this!

**Comment by theusaf** [comment]
Hey, thanks for reaching out! This issue seems to be up for grabs.
