### ISSUE TITLE
Peloton | members.onepeloton.com

### ISSUE THREAD

**Issue by HQv2** [PreMiD/Presences#1516]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
HQv2#7594

**What's the name of the service?** 
Peloton

**What should the Presence display?** 
Current class you are taking, ride number, distance, time elapsed

**If possible, please provide a logo for the service (512x512 minimum)** 
![peloton_640x640](https://user-images.githubusercontent.com/42633588/81333173-2f275600-9072-11ea-8af8-f1e3ba72331e.png)

**Comment by TheGamerzs** [comment]
.

**Comment by TheGamerzs** [comment]
I will make the presence

**Comment by TheGamerzs** [comment]
#1574

**Comment by TheGamerzs** [comment]
Released
