### ISSUE TITLE
AI Dungeon | aidungeon.io

### ISSUE THREAD

**Issue by bastien09** [PreMiD/Presences#1552]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Bastien#9504

**What's the name of the service?**  https://aidungeon.io/ | AI Dungeon

**What should the Presence display?**  Playing AI Dungeon

**If possible, please provide a logo for the service (512x512 minimum)**  no, sorry

**Comment by Gurrman375** [comment]
![ailogo](https://user-images.githubusercontent.com/25113575/82364078-a68aad00-99c3-11ea-8570-c1164083d892.png)

**Comment by bastien09** [comment]
>  Also can you update your discord username:

Ooops, yes, sorry

**Comment by doomlerd** [comment]
Has been added : 
https://premid.app/store/presences/AI%20Dungeon
