### ISSUE TITLE
PreMiD doesn't show when viewing a streamer in normal mode

### ISSUE THREAD

**Issue by KiritoStorm** [PreMiD/Presences#1559]
**Describe the Bug**
Normaly PreMiD shows that you are viewing the streamer, but if you only watch one streamer it only shows that you are watching if you viewing it in squad mode, this works correctly and i think it's a bug of the presence. 
I don't this is an Issue with VIvaldi, i have turn off my ad and tracker blocker but it doesn't worked. :/
It worked for me, a short time ago. And the same behavior is also on Opera and Chrome on normal viewing.

**Steps to Reproduce**
1. View any streamer
2. PreMiD is still showing that you are browsing on Twitch

**Expected Behavior**
Showing that you are watching a stream, on any streamer it doesn't work.

**Screenshots**
-

**Environment**
- OS: Windows 10 Pro (Version 1909)
- Browser: Vivaldi
- Version: 3.0.1874.38 (based on Chromeium/81.0.4044.142)

**Additional context**
-

Thank you for providing us this great feature to Discord, i hope this is a small bug :)

**Comment by frozaum** [comment]
#1561
