### ISSUE TITLE
WikiHow doesnt display artictle name

### ISSUE THREAD

**Issue by ddomino007** [PreMiD/Presences#1570]
When browsing an article, the rich presence displays "Viewing a page: Homepage"
It only displays either the search results [which by the way look like they were outright copied from the url and left unformatted, for example "Searching for: Overcome+art+block"] or when on the homepage or reading an article, in both cases it displays "Viewing a page: Homepage"

Screenshots;
![image](https://user-images.githubusercontent.com/23064460/82440548-d063d280-9a9c-11ea-9ce2-39ff4dbdcabd.png)
![image](https://user-images.githubusercontent.com/23064460/82440567-d78ae080-9a9c-11ea-9b62-70cae7a46866.png)

**Comment by PeeQueno** [comment]
![image](https://user-images.githubusercontent.com/65591076/82806765-d66f0000-9e5c-11ea-9eea-eceb2cd4215e.png)
i have fixed it, but now the author displays wrong hahaha, and i don't know how i can fix the author

![image](https://user-images.githubusercontent.com/65591076/82806972-47161c80-9e5d-11ea-9590-a9c20c0931bb.png)
But, i did the search work correctly
