### ISSUE TITLE
Dizilla | dizilla.com

### ISSUE THREAD

**Issue by MFI96** [PreMiD/Presences#1571]
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region? 
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  ! Degurechaff !#6567

**What's the name of the service?** Dizilla

**What should the Presence display?** For example : 
https://dizilla.com/ (link removed)
Title : Chicago P.D. 1. Sezon 9. Bölüm'ü izliyor.

**https://i.imgur.com/aAVldYD.png**

**Comment by Gurrman375** [comment]
Is the site region locked?
![image](https://user-images.githubusercontent.com/25113575/82486028-2468ba00-9a91-11ea-8659-20e828cb5a65.png)

**Comment by frozaum** [comment]
same issue here, site is region-locked

**Comment by eggsywashere** [comment]
Moving on in #1426
