### ISSUE TITLE
Requesting Google Stadia on the Presence Store

### ISSUE THREAD

**Issue by Installity** [PreMiD/Presences#1589]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Insanity#1738

**What's the name of the service?**  Stadia | stadia.google.com

**What should the Presence display?**  The presence should display that you are at least on the Stadia website, It should display whether you are on the home menu or on the store menu. It would also be nice if it showed what game you are playing but that is hard to develop.

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/58996536/82717378-a45e7200-9c93-11ea-8c1a-7eacc3378e02.png)

**Comment by frozaum** [comment]
duplicate #884
