### ISSUE TITLE
Gitbook | gitbook.com

### ISSUE THREAD

**Issue by R4zzerYT** [PreMiD/Presences#1600]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
Gitbook | gitbook.com

**What should the Presence display?** 
if i edit a wiki with the domain, if I'm not editing it, only what article i read and in what wiki.

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Gurrman375** [comment]
I'll take this one
