### ISSUE TITLE
Mr.Piracy | mrpiracy.site

### ISSUE THREAD

**Issue by Ubastii** [PreMiD/Presences#1615]
![mrpiracy](https://user-images.githubusercontent.com/64856723/82842532-d8bf7180-9ed1-11ea-8c86-5b5e18b9e8ac.PNG)
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Bastet#6368

**What's the name of the service?** Mr.Piracy |  https://mrpiracy.site/

**What should the Presence display?** What movie/tv show is now playing, something like Netflix.

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Ubastii** [comment]
The most famous site to watch movies, series, animes, etc on Portugal.
Please, add it

**Comment by Gurrman375** [comment]
I'll take this one

**Comment by sluzy-nos4a2** [comment]
Please add this presence

**Comment by Gurrman375** [comment]
@Ubastii or @sluzy-nos4a2 Do you have a description of the site?

**Comment by sluzy-nos4a2** [comment]
> @Ubastii or @sluzy-nos4a2 Do you have a description of the site?

Something like this?

The MrPiracy website has been one of the reference sites for moviegoers in Portugal who want to see Films and Series for free. In fact, by creating an account, which is also free, the site offers a huge variety of properly subtitled and categorized streams.
