### ISSUE TITLE
Qwant | www.qwant.com

### ISSUE THREAD

**Issue by GreepTheSheep** [PreMiD/Presences#1621]
**Prerequisites and essential questions**
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Greep#3022

**What's the name of the service?** https://www.qwant.com/

**What should the Presence display?** Home page, search page (like Google), images, maps, junior and music (if possible)

**If possible, please provide a logo for the service (512x512 minimum)**
![image](https://user-images.githubusercontent.com/42576124/82900611-19180180-9f5d-11ea-96fc-1cc1d3c1318c.png)

**Comment by Gurrman375** [comment]
This one is mine
