### ISSUE TITLE
HBO Max | www.hbomax.com

### ISSUE THREAD

**Issue by Azrael206** [PreMiD/Presences#1630]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Champ#7166

**What's the name of the service?** HBO Max

**What should the Presence display?** Current show with season number & episode name, movie being watch, time elapsed of movie or show, what genre were browsing when looking for a movie, what part of the page were on, what movie or show were viewing when looking for a movie. 

Example: "Viewing: Joker (2019)" , "Browsing Genre: Action & Adventure"

**If possible, please provide a logo for the service (512x512 minimum)** 
![3xj-pOFB_400x400512x512](https://user-images.githubusercontent.com/61640048/83047649-a4a19900-a016-11ea-83b4-08b83182b7d5.png)

**Comment by Azrael206** [comment]
Realized Joker came out in 2019, not 2020 xd. But, you get the point ;P

**Comment by doomlerd** [comment]
I didn't know I had an account on this lmao

**Comment by doomlerd** [comment]
[Added](https://premid.app/store/presences/HBO%20Max)

**Comment by ChampOTF** [comment]
I realized I never said thank you, I think I said it in some other form on discord. But, Thank You! You didn’t have to do this, you took your own personal time to do it, it’s much appreciated.
