### ISSUE TITLE
Dream Animes DNE

### ISSUE THREAD

**Issue by Gurrman375** [PreMiD/Presences#1631]
The site Dream Animes does not exist. I have tried to contact Viruz about this issue but got no response. The presence should be taken down.

**Comment by frozaum** [comment]
nope.

**Comment by frozaum** [comment]
not now.

**Comment by Gurrman375** [comment]
Alright I get it.

**Comment by frozaum** [comment]
alright, re-opening it because of #1635

**Comment by frozaum** [comment]
rip
