### ISSUE TITLE
PrimeVideo Presence no longer shows the currently playing movie

### ISSUE THREAD

**Issue by bastien09** [PreMiD/Presences#1649]
**Describe the Bug**

When you play a movie/tv show in prime video the presence no longer display the title of the movie

**Steps to Reproduce**

1. Go to https://www.primevideo.com
2. start playing something

**Expected Behavior**

Showing the title of the movie. It still display "Browsing" instead.

**Environment**

- OS:  Windows 10
- Browser:  Firefox
- Version:  76.0.1 (64 bits)

**Comment by Bas950** [comment]
When watching the video could you open the inspect element and give me the JS Path `document.querySelector(".....")` for the video object, if you need further help please dm me in discord:
Bas950#0950
