### ISSUE TITLE
DooMLorD - Presences TODO List

### ISSUE THREAD

**Issue by doomlerd** [PreMiD/Presences#1652]
bippity boppity your presence is now my property 😀

* [x] - [HBO Max](1630) > Added ( [PR](1742), [Store](https://premid.app/store/presences/HBO%20Max) )
* [ ] - The CW > Abandonned

**Comment by StrikerFRFX** [comment]
Hey, if you're not working on Kickassanime (Since it hasn't been added yet from what I see) would you mind if I do it? I feel like I might be able to do it (not 100% sure yet as I haven't fully looked into how I would do it). Thanks!

**Comment by doomlerd** [comment]
Hey @StrikerFRFX, that's completely fine, feel free to take it.
