### ISSUE TITLE
YouTube: Showing playlist creator instead of video uploader

### ISSUE THREAD

**Issue by TheLastZombie** [PreMiD/Presences#1659]
**Describe the Bug**
When playing a video within a YouTube playlist, PreMiD displays the creator of said playlist instead of the uploader of the video in the second line.

**Steps to Reproduce**
1. Open a YouTube playlist
2. Select/play a video
3. Enable PreMiD and take a look at the presence

**Expected Behavior**
PreMiD displaying the uploader of the currently playing video.

**Screenshots**
| Video within playlist | Same video played separately |
| --- | --- |
| ![dIJtyUBq9c](https://user-images.githubusercontent.com/8181990/83336701-de43ff80-a2b5-11ea-8b42-ddac24bc5658.png) | ![Discord_VpFBtrOxAm](https://user-images.githubusercontent.com/8181990/83336711-eef47580-a2b5-11ea-8f45-ed82ff6cd189.png) |

**Environment**
- OS: Windows 10 Home, version 2004, build 19619.1000
- Browser: Firefox Nightly
- Version: 78.0a1

**Additional context**
- This continues the discussion from #1065, since that issue was closed for not following the bug report template. Couldn't really figure out why honestly, but hopefully this issue should follow the template.
- The mentioned video can be found [here](https://www.youtube.com/watch?v=cXFmqapcP8Y), and the channel is indeed called "This Is".

**Comment by frozaum** [comment]
strangely, i didn't have this issue here
![image](https://user-images.githubusercontent.com/34042085/83340043-10e7fb00-a2aa-11ea-8dc6-6b634b22787a.png)

**Comment by frozaum** [comment]
going to try on firefox

**Comment by frozaum** [comment]
same with Firefox Developer Edition 77.0b9
![image](https://user-images.githubusercontent.com/34042085/83340143-0f6b0280-a2ab-11ea-93c5-4563de816759.png)

**Comment by TheLastZombie** [comment]
So it doesn't ssem to be related to any extension. Disabling all of them (except PreMiD obviously) still results in the same behavior.

**Comment by doomlerd** [comment]
That's a very rare occurrence, I've tried to fix it after the old issue and my fix was really more of just a way to make it very rare. We can't do anything about it due to YouTube limitations.
If you have any ideas, make sure to make a PR.

P.S. it almost never occurs in chromium based browsers.
