### ISSUE TITLE
CDA | www.cda.pl

### ISSUE THREAD

**Issue by hikusia** [PreMiD/Presences#1661]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  egzo#5407

**What's the name of the service?**  https://www.cda.pl I cda

**What should the Presence display?**  title and time to the end of show, possibly exploring

**If possible, please provide a logo for the service (512x512 minimum)** 
![cda-logo](https://user-images.githubusercontent.com/57454113/83339481-8fef2a80-a2ce-11ea-81a3-c17298f12ff3.jpg)

**Comment by kawakaami** [comment]
i will try do this today :)
