### ISSUE TITLE
kreskóweczki | www.kreskoweczki.pl

### ISSUE THREAD

**Issue by hikusia** [PreMiD/Presences#1662]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  egzo#5407

**What's the name of the service?**  Kreskóweczki I https://www.kreskoweczki.pl

**What should the Presence display?**  title, the number of episod, time to end of show, maybe exploring

**If possible, please provide a logo for the service (512x512 minimum)**  
![123](https://user-images.githubusercontent.com/57454113/83339790-3fc59780-a2d1-11ea-967a-57a75b1d336e.jpg)

**Comment by Gurrman375** [comment]
I think this is region restricted. I can seem to load the page.

**Comment by MrBartusek** [comment]
Not working from Poland too, ownforeveryoneorjustme also cannot reach it
 
![image](https://user-images.githubusercontent.com/23432278/85315764-f1647c80-b4bb-11ea-85e6-1b0b73bd76df.png)

**Comment by frozaum** [comment]
Website still alive, only region-locked to Polish people

**Comment by MrBartusek** [comment]
> Website still alive, only region-locked to Polish people

Was checking a while ago, checked now again, not reachable from Poland

**Comment by frozaum** [comment]
> > Website still alive, only region-locked to Polish people
> 
> Was checking a while ago, checked now again, not reachable from Poland

I got someone to work though 🤔, this is kinda odd.

**Comment by ririxichan** [comment]
Should work actually, so if someone wants, feel free to do it.
