### ISSUE TITLE
Improve Senpa.io Presence

### ISSUE THREAD

**Issue by MistikSenpa** [PreMiD/Presences#1682]
**Describe the Bug**
Not really a bug, but more of a change required to the senpa presense. I was asked to submit it was a bug

**Steps to Reproduce**
N/A

**Expected Behavior**
What should the Presence display?
It should display the server the play is connected to + region. e.g if they are on the overworld server it should say EU Overworld
Also should display player nickname they are using ingame
Also should display how much mass they have.
And how long/time elapsed they been playing

An example of something similar
https://prnt.sc/ssddj4

Also an updated icon
https://i.imgur.com/iyCyaUz.jpg

**Screenshots**
N/A

**Environment**
N/A

**Additional context**
Improvement suggestion

Here is the current presence
https://github.com/PreMiD/Presences/tree/master/websites/S/Senpa.io

**Comment by frozaum** [comment]
wrong template, but going to leave it opened

**Comment by frozaum** [comment]
@EvilBrain, want to take a look into it?

**Comment by EvilBrain** [comment]
I look at this

**Comment by MistikSenpa** [comment]
> wrong template, but going to leave it opened

thankyou and sorry about that

**Comment by MistikSenpa** [comment]
EDIT.

Added an updated icon

**Comment by MistikSenpa** [comment]
EDIT.

Added an updated icon

**Comment by MistikSenpa** [comment]
Add some stuff to Senpa.io to get data easier
 type in console
- window.info
for server info
 - window.nick 
for the nick

Also updated the icon
https://i.imgur.com/iyCyaUz.jpg

I want the format of the senpa.io presense something like this
https://prnt.sc/ssddj4

**Comment by xN3BULA** [comment]
I checked the updates and they work good

**Comment by MistikSenpa** [comment]
> Add some stuff to Senpa.io to get data easier
> type in console
> 
> * window.info
>   for server info
> * window.nick
>   for the nick
> 
> Also updated the icon
> https://i.imgur.com/iyCyaUz.jpg
> 
> I want the format of the senpa.io presense something like this
> https://prnt.sc/ssddj4

@EvilBrain ^^

**Comment by MistikSenpa** [comment]
opened a new one, as cant seem to get any contact with the developer this was assigned to, tried discord etc, no reply from them :(
