### ISSUE TITLE
Kissanime.ru presence request

### ISSUE THREAD

**Issue by lonelyhikiko** [PreMiD/Presences#1695]
**Prerequisites and essential questions** 
- [x] Is it a popular site? Yes , Kissanime.ru is popular 
- [x] Is the website older than 2 months?  Created in 2012 as far as i know
- [x] Is the site locked to a specific country/region? i dont think so , no
- [x] Is the site a paid service? (e.g. Netflix, Hulu) it isnt a paid service
- [x] Does the website feature NSFW content? (e.g. porn, etc...) certain ads do show , but never are nsfw
- [x] Are you a donator/patron? no im not
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? well idk about that 

**What's your Discord username?**  Hikiko#4469

**What's the name of the service?**  Kissanime.ru

**What should the Presence display?**  well the site , then the anime youre watching and the episode , 

**If possible, please provide a logo for the service (512x512 minimum)**  i assume that the site has a logo , i do have a cropped one , ill attach it regardless. 
![kissanime logo](https://user-images.githubusercontent.com/66532673/83953111-cc7ed100-a84e-11ea-8138-b73d2041215d.PNG)

**Comment by frozaum** [comment]
[Already added](https://premid.app/store/presences/KissAnime).
