### ISSUE TITLE
https://collabd.xyz/

### ISSUE THREAD

**Issue by JedrikDS** [PreMiD/Presences#1701]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?**  collabd.xyz | CollabD

**What should the Presence display?**  The music being played by the user (The title of the website changes depending on which music is being played, for example if you're listening to Bitch Lasagna by Pewdipie the title will be "Bitch lasagna - PewDiePie" so that could make it easier

**If possible, please provide a logo for the service (512x512 minimum)**  
![1f3a7](https://user-images.githubusercontent.com/63572830/83970255-525e5300-a907-11ea-8117-882a0fb214b9.png)

**Comment by frozaum** [comment]
The domain is not two months old yet, please re-apply in 28 days.
