### ISSUE TITLE
buff163 | buff.163.com

### ISSUE THREAD

**Issue by ghost** [PreMiD/Presences#1706]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
Buff

**What should the Presence display?** 
What item im browsing, similar to Aliexpress rich presence.

**If possible, please provide a logo for the service (512x512 minimum)** 
![buff](https://user-images.githubusercontent.com/18513533/83999202-92065880-a962-11ea-8720-a0a6c8f36744.png)

**Comment by Cairo2k18** [comment]
Can I be assigned to this presence please
