### ISSUE TITLE
Online Soccer Manager | onlinesoccermanager.com

### ISSUE THREAD

**Issue by Xzer0o0** [PreMiD/Presences#1726]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Xzer0o0#9615

**What's the name of the service?** https://en.onlinesoccermanager.com

**What should the Presence display?**  games stuff like if you are in "career" and if you chose a team from the 4 available it tells what team u r in , and another things like "transfer list" or "training ground" etc.

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by marinofranz** [comment]
I will be doing this Presence, refer to #1750 for progress
