### ISSUE TITLE
Padlet | padlet.com

### ISSUE THREAD

**Issue by geenva** [PreMiD/Presences#1734]
**Prerequisites and essential questions** 
- [X] Is it a popular site?
- [X] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** geneva#0058 

**What's the name of the service?** Padlet 

**What should the Presence display?** Padlet, Padlet name and time used to view Padlet 

**If possible, please provide a logo for the service (512x512 minimum)**  
![image](https://user-images.githubusercontent.com/34730060/84370086-58577b00-ac0a-11ea-9c31-53ce0064dfb7.png)

**Comment by Mirazex** [comment]
I will do it

**Comment by flarely** [comment]
Thank you!
