### ISSUE TITLE
Wikiwand | wikiwand.com

### ISSUE THREAD

**Issue by flarely** [PreMiD/Presences#1735]
**Prerequisites and essential questions** 
- [X] Is it a popular site?
- [X] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Flare#9202 

**What's the name of the service?** Wikiwand 

**What should the Presence display?** Wikiwand, article and time used to view article 

**If possible, please provide a logo for the service (512x512 minimum)**  
![image](https://user-images.githubusercontent.com/34730060/84370396-c4d27a00-ac0a-11ea-817d-8d1faf6cd786.png)

**Comment by flarely** [comment]
It can also be a website.

**Comment by Hans5958** [comment]
I'll give this a shot.
