### ISSUE TITLE
AnimeHeaven | animeheaven.ru

### ISSUE THREAD

**Issue by ArchieTheGreat** [PreMiD/Presences#1736]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Naofumi Iwantani#0808

**What's the name of the service?** animeheaven.ru

**What should the Presence display?**  can you just please add like kissanime rich presence there's browsing and the title of the anime and for how long is gonna take to finish ?

**If possible, please provide a logo for the service (512x512 minimum)**  
![download (2)](https://user-images.githubusercontent.com/66778324/84375946-dd469280-ac12-11ea-9029-1488201ac233.jpg)

**Comment by ArchieTheGreat** [comment]
i  hope you can do this <3

**Comment by Gurrman375** [comment]
This one is mine

**Comment by ArchieTheGreat** [comment]
> This one is mine

Thanks

**Comment by ArchieTheGreat** [comment]
thanks


Noong Lin, Hun 14, 2020 nang 5:13 PM, sinulat ni Gurrman375 <
notifications@github.com> ang:
