### ISSUE TITLE
Google Hangouts | hangouts.google.com

### ISSUE THREAD

**Issue by geenva** [PreMiD/Presences#1756]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Flare#9202 

**What's the name of the service?** Google Hangouts 

**What should the Presence display?** Service name, name of person talking to, typing or just reading chat 

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/34730060/84607776-c12c4500-aee1-11ea-9dc3-b53a3429207e.png)

**Comment by ChampOTF** [comment]
Hmm, I thought hangouts was reportedly shutting down?

**Comment by flarely** [comment]
> Hmm, I thought hangouts was reportedly shutting down?

nah... it's gonna be up for some time

**Comment by MaXfAa** [comment]
Google abandons Hangouts in favor of Chat.
Request moved : #3947
