### ISSUE TITLE
YouTube and YouTube Music's rich presence doesn't show up.

### ISSUE THREAD

**Issue by ATrueShadow** [PreMiD/Presences#1774]
**Describe the Bug**
YouTube and YouTube Music doesn't show rich presence when video or song with & is playing. Also, YouTube Music can't show a rich presence with % in the song name.
Sometimes this bug just breaks rich presence for those websites and I need to restart my browser to fix it.

**Steps to Reproduce**

1. Open YouTube/YouTube Music
2. Find a video/song with & in it (or with % if on YT Music). For example [& by Tally Hall](https://www.youtube.com/watch?v=pLJ85XExZtQ)
3. Done.

**Expected Behavior**
Video/song is displayed in Discord.

**Screenshots**

![YTMBug(&)](https://user-images.githubusercontent.com/36447671/85026576-81838880-b181-11ea-8ab5-53ac7f9834a0.png)
![YTMBug(%)](https://user-images.githubusercontent.com/36447671/85026574-80eaf200-b181-11ea-9993-eaf6ee5db700.png)
#### Here the working YT front page
![YTWorking](https://user-images.githubusercontent.com/36447671/85026581-821c1f00-b181-11ea-8247-72b425f40882.png)
#### and when I open the song.
![YTBug(&)](https://user-images.githubusercontent.com/36447671/85026564-7f212e80-b181-11ea-840f-f579ff619822.png)

**Environment**

- OS: Windows 10 1909
- Browser: Vivaldi
- Version: 83.0.4103.98 (64 bit)

**Comment by Bas950** [comment]
That's because the title ins't 3 characters or longer. 
Nothing we can do about it, it is something in discord, that it has to be at least 3 characters.
