### ISSUE TITLE
Neocities | neocities.org

### ISSUE THREAD

**Issue by MineBoom32** [PreMiD/Presences#1776]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
MineBoomGaming#0967

**What's the name of the service?** 
neocities.org | Neocities

**What should the Presence display?** 
The title of the specific page being accessed, as well as the name of the page's creator

**If possible, please provide a logo for the service (512x512 minimum)** 

![neocatAgain](https://user-images.githubusercontent.com/67128084/85080855-45a7ed80-b198-11ea-96d0-935298e79880.png)

**Comment by MineBoom32** [comment]
Note that the website appears to be free of _porn_, but certain pages may contain blood and/or gore.

**Comment by doomlerd** [comment]
Seems to have none of such content (at least not in the homepage) so it's safe to assume that it's not nsfw.
