### ISSUE TITLE
SoloLearn | www.sololearn.com

### ISSUE THREAD

**Issue by QuarentineDev** [PreMiD/Presences#1784]
**Prerequisites and essential questions** 
- [x] Is it a popular site? Yep
- [x] Is the website older than 2 months?  yep
- [ ] Is the site locked to a specific country/region? As far as I know, learning different programming languages is not forbidden for anyone?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)Nop
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** QuarentineDev#7796

**What's the name of the service?**  That name is SoloLearn, Link: https://www.sololearn.com/

**What should the Presence display?** Show him the language he is studying, how long he has been and his name in Sololearn

**If possible, please provide a logo for the service (512x512 minimum)** 
I don’t have any kind of picture of what the program is as such and with those measures it is almost difficult for me

**Comment by drull1000** [comment]
There is already a SoloLearn presence

**Comment by Bas950** [comment]
https://premid.app/store/presences/SoloLearn
