### ISSUE TITLE
deno.land

### ISSUE THREAD

**Issue by Timeraa** [PreMiD/Presences#1787]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Are you a donator/patron? I am creator duh
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Timeraa#7947
**What's the name of the service?** 
deno
**What should the Presence display?** 
stuff :>
**If possible, please provide a logo for the service (512x512 minimum)** 
https://deno.land/logo.svg

**Comment by Timeraa** [comment]
@SnoweyFoxx ^

**Comment by SnoweyFoxx** [comment]
👀
