### ISSUE TITLE
Vanis.io

### ISSUE THREAD

**Issue by Air69789** [PreMiD/Presences#1788]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Air#3167
**What's the name of the service?** 
Vanis.io 
**What should the Presence display?** 
Logo, server, region, nickname, amount of time played, service name, amount of mass.
**If possible, please provide a logo for the service (512x512 minimum)** 
https://media.discordapp.net/attachments/216222655664226304/725035485818519643/image0.jpg

**Comment by MrBartusek** [comment]
Fixed in #1788, can be closed
