### ISSUE TITLE
[Presence | Feature Request] Senpa.io

### ISSUE THREAD

**Issue by Mistik** [PreMiD/Presences#1809]
Describe the Bug
Not really a bug, but more of a change required to the senpa presense. I was asked to submit it was a bug

Steps to Reproduce
N/A

Expected Behavior
What should the Presence display?
It should display the server the play is connected to + region. e.g if they are on the overworld server it should say EU Overworld
Also should display player nickname they are using ingame
Also should display how much mass they have.
And how long/time elapsed they been playing

An example of something similar
https://prnt.sc/ssddj4

EXTRA
Added some stuff to Senpa.io to get data easier
type in console

window.info
for server info
window.nick
for the nick

Also an updated icon
https://i.imgur.com/iyCyaUz.jpg

Screenshots
N/A

Environment
N/A

Additional context
Improvement suggestion

Here is the current presence
https://github.com/PreMiD/Presences/tree/master/websites/S/Senpa.io

**Comment by MistikSenpa** [comment]
bumps

**Comment by Mirazex** [comment]
I will do it

**Comment by ririxidev** [comment]
@Mirazex when? :)
Pinging owner of this presence too: @EvilBrain
