### ISSUE TITLE
Gitlab | gitlab.com

### ISSUE THREAD

**Issue by NightYoshi370** [PreMiD/Presences#181]
**What's the name of the service?**
Ex. https://gitlab.com | Gitlab

**What should the Presence display?**
Informations about the current file the user is editing

**Why do you want support for this service?**
I'd like to show my users what I'm working on at the moment. It'd be great to see what the user is looking at what file so that they can help them out with an implementation

**Are you able to provide an image for the service? (512x512 minimum)**
It is an SVG file and as such I have no idea how to post it

**Comment by MulverineX** [comment]
Gitlab is as much a paid service as GitHub is, public/open-source code hosting is free and is one of the main uses of the platform

**Comment by codepupper** [comment]
Gitlab is not a paid Service. While yes, it has more paid stuff than Github does, if I remember correctly, the Editor/IDE on the Site is completely free.

I suggest removing the `paid service` label

**Comment by alazymeme** [comment]
Gitlab icon pulled from their press kit FYR
![image](https://user-images.githubusercontent.com/12804673/76142958-54bdd080-60be-11ea-9836-6bb9e176eecc.png)

**Comment by Gurrman375** [comment]
Is anyone currently working on this presence?

**Comment by frozaum** [comment]
I mean, no @Gurrman375, if you want to do it, go ahead and i will assign you on this issue.

**Comment by Gurrman375** [comment]
Okay I can get this done.
