### ISSUE TITLE
Good 

### ISSUE THREAD

**Issue by i9lam** [PreMiD/Presences#1811]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [ ] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? 

**What's your Discord username?**  No heart feelings Fuck ♪#8680

**What's the name of the service?**  https://www.okanime.com/

**What should the Presence display?** 

**If possible, please provide a logo for the service (512x512 minimum)**  https://cdn.discordapp.com/attachments/642034175335202826/727751108499472445/unknown.png

**Comment by i9lam** [comment]
Yes go

**Comment by i9lam** [comment]
> **Prerequisites and essential questions**
> 
> * [x]  Is it a popular site?
> * [ ]  Is the website older than 2 months?
> * [x]  Is the site locked to a specific country/region?
> * [ ]  Is the site a paid service? (e.g. Netflix, Hulu)
> * [ ]  Does the website feature NSFW content? (e.g. porn, etc...)
> * [ ]  Are you a donator/patron?
> * [x]  Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?
> 
> **What's your Discord username?**
> 
> **What's the name of the service?**
> 
> **What should the Presence display?**
> 
> **If possible, please provide a logo for the service (512x512 minimum)**

**Comment by frozaum** [comment]
[already added](https://premid.app/store/presences/OKanime)
