### ISSUE TITLE
Pixlr | pixlr.com

### ISSUE THREAD

**Issue by egeolge** [PreMiD/Presences#1821]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
yvnc#3441
**What's the name of the service?** 
Pixlr
**What should the Presence display?** 
Idk
**If possible, please provide a logo for the service (512x512 minimum)** 
https://lh3.googleusercontent.com/a-Cm56JAmr8UC0MSub0e1GbA82AsAXuUqO_7z5V2mQg_DsQc3RKnUUyyAepLbfjmSw

**Comment by Uhev-png** [comment]
I'll take this one
