### ISSUE TITLE
Webflow | webflow.com

### ISSUE THREAD

**Issue by xenforq** [PreMiD/Presences#1832]
**Prerequisites and essential questions**
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Are you a donator/patron? (as seen [here](https://github.com/PreMiD/Presences/issues/504))
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**
xenforq#0001

**What's the name of the service?**
Webflow, https://webflow.com/

**What should the Presence display?**
_While in the designer state:_
First line: [Project name/title]
Second line: Editing [Page name]
and elapsed time

_While anywhere else:_
First line: Browsing
and elapsed time

**If possible, please provide a logo for the service (512x512 minimum)**

![Webflow](https://user-images.githubusercontent.com/56734956/86622988-1202fb00-bfc1-11ea-8c64-f11dc1294801.png)

**Comment by MrBartusek** [comment]
I am working on that
