### ISSUE TITLE
Twitch.tv Not Working

### ISSUE THREAD

**Issue by Mooonblaze** [PreMiD/Presences#1875]
PreMiD v2.1.3, Firefox browser

Normal Discord, Twitch with BetterTTV extension. 
Other presences (YouTube, Netflix, etc.) working. Twitch.tv has no presence.

**Comment by frozaum** [comment]
> @Mooonblaze @Zeltcon [media.discordapp.net/attachments/526736087377248257/733929575771406447/PresenceSettings.gif](https://media.discordapp.net/attachments/526736087377248257/733929575771406447/PresenceSettings.gif)
> Toggle the settings and it should work, using third-party Twitch extensions aren't supported at the moment.

BTTV and FFZ extensions should not affect the Twitch presence.
