### ISSUE TITLE
Invidious

### ISSUE THREAD

**Issue by Xpert87** [PreMiD/Presences#1883]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Xpert#6337

**What's the name of the service?**  Invidious | All instances are at this [link](https://github.com/iv-org/invidious/wiki/Invidious-Instances)

**What should the Presence display?** It should be exactly like the Youtube presence (Title, Channel Name, Time Remaining)
**If possible, please provide a logo for the service (512x512 minimum)** 
![maxresdefault](https://user-images.githubusercontent.com/62971625/87955013-2643ff00-ca7b-11ea-8d03-5f907a4ad1b3.jpg)

**Comment by frozaum** [comment]
that's interesting 👀

**Comment by marinofranz** [comment]
It seems like the instance is shutting down on September 1st

**Comment by fr0r** [comment]
only the main instance, the rest should be fine @marinofranz

**Comment by Xpert87** [comment]
Sorry for the late reply. Yes, as João said, the main instance of
Invidio.us is shutting down. The rest should be up.

**Comment by Isa27-0** [comment]
Hi, I came to tell you that the presence is already being made (#2267) :)
