### ISSUE TITLE
Kickassanime | www1.kickassanime.rs

### ISSUE THREAD

**Issue by BvBUndeader** [PreMiD/Presences#1885]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x ] Does the website feature NSFW content? (e.g. porn, etc...) [if ads count]
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
SekkiYato#4200
**What's the name of the service?** 
https://www1.kickassanime.rs/ | Kickassanime
**What should the Presence display?** 
like what anime is being watched rn
**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/68561242/87973413-253dbc80-cad1-11ea-9029-2eb63d682c81.png)

**Comment by EncryptedDev** [comment]
Striker added this :) https://premid.app/store/presences/Kickassanime

**Comment by ririxidev** [comment]
Closing. https://premid.app/store/presences/KickAssAnime
