### ISSUE TITLE
Animes Online | animesonline.games

### ISSUE THREAD

**Issue by ipaddysz** [PreMiD/Presences#1904]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Koalin#6339 

**What's the name of the service?** www.animesonline.games | AnimesOnline.Games

**What should the Presence display?** Title of anime and time left
**If possible, please provide a logo for the service (512x512 minimum)**  https://cdn.discordapp.com/attachments/725820850363826327/736972600764268615/discord.png

**Comment by frozaum** [comment]
region-locked

**Comment by MirayXS** [comment]
I live in Italy,

Error 1020 Ray ID: 5bb8c8fce843dfcb • 2020-07-31 16:44:37 UTC
Access denied
What happened?
This website is using a security service to protect itself from online attacks.

**Comment by ipaddysz** [comment]
> I live in Italy,
> 
> Error 1020 Ray ID: 5bb8c8fce843dfcb • 2020-07-31 16:44:37 UTC
> Access denied
> What happened?
> This website is using a security service to protect itself from online attacks.

The website is brazilian, the security service you must have seen that a bot raid was taking place in Italy while you were trying to access.

**Comment by ririxidev** [comment]
Why are you closing it?

**Comment by ipaddysz** [comment]
@ririxidev I'm closing because the presence is currently done, the pull request only needs approval 
Pull Request: https://github.com/PreMiD/Presences/pull/4045

**Comment by ririxidev** [comment]
Then this pull request will close this issue when it will be merged

**Comment by ipaddysz** [comment]
okay thanks
