### ISSUE TITLE
Netflix not working

### ISSUE THREAD

**Issue by g-empr** [PreMiD/Presences#1905]
**Describe the Bug**
About two weeks before, Netflix Presence has become not working.
Until that time, it  was working normally.

**Steps to Reproduce**
1. Start up PreMiD and Discord.
1. Open Netflix in the browser.
1. Play any video.

**Expected Behavior**
Discord Presence works normally.

**Environment**
- OS: Win10 home 64-bit
- Browser (confirmed)
  - Vivaldi 3.1.1929.45 64-bit
  - Google Chrome 84.0.4147.89 64-bit
- PreMiD
  - extension ver : v2.1.0 
  - app ver : v2.1.3

**Comment by Bas950** [comment]
Press F12 and click console while watching a netflix movie, does it display any errors (Red text) in the console?
