### ISSUE TITLE
Twitch not showing up with premid

### ISSUE THREAD

**Issue by timmytomt** [PreMiD/Presences#1927]
When watching something on Twitch, premid doesn't seem to detect it.

 - OS: Win
 - Browser: Opera 66.0.3515.115

**Comment by Bas950** [comment]
This should fix your issue: https://media.discordapp.net/attachments/526736087377248257/735934633706913812/PresenceSettings.gif

If it doesn't, feel free to contact in a ticket in our Discord server (https://discord.premid.app/)
