### ISSUE TITLE
Twitch.tv not working

### ISSUE THREAD

**Issue by hexann1** [PreMiD/Presences#1937]
**Describe the bug**
No twitch presence on discord when i am browsing/watching twitch

**To Reproduce**
1.Open a Twitch.tv stream
2. Check presence in Discord
3. No presence

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 2.1.3

**Comment by Bas950** [comment]
This should fix your issue: https://media.discordapp.net/attachments/526736087377248257/735934633706913812/PresenceSettings.gif

If it doesn't, feel free to contact us in a ticket in our Discord server (https://discord.premid.app/)
