### ISSUE TITLE
Peacock | www.peacocktv.com

### ISSUE THREAD

**Issue by thread90** [PreMiD/Presences#1938]
**Prerequisites and essential questions** 
- [x] Is it a popular site? 
- [ ] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region? 
- [x] Is the site a paid service? (e.g. Netflix, Hulu) 
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? 

**What's your Discord username?**  _bear#0001

**What's the name of the service?**  Peackock

**What should the Presence display?** 
- Time watched in show
- Episode in show/movie
- Season in show
- Website name
- Name of show/movie

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/39356292/89214812-1c4af180-d58d-11ea-84ef-c462d10aaf1b.png)

**Comment by frozaum** [comment]
website is region-locked for U.S. users and has required subscription options.
