### ISSUE TITLE
botsbase

### ISSUE THREAD

**Issue by Roxza** [PreMiD/Presences#1943]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
! Roxza mutlu olan#2719
**What's the name of the service?** 
BotsBase | https://botsbase.net/
**What should the Presence display?** 

api,bot,user,addbot ...

**If possible, please provide a logo for the service (512x512 minimum)** 

https://i.hizliresim.com/B2T73G.png
#

**Comment by frozaum** [comment]
Service is not 2 months old.
Please re-apply in two months.

CLOSED
