### ISSUE TITLE
Watch2Gether | wg2.tv

### ISSUE THREAD

**Issue by tzockt** [PreMiD/Presences#1945]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Darth Vader#4655

**What's the name of the service?** Watch2Gether w2g.tv

**What should the Presence display?** Name of the Website, current Video in the Room, Time left of the Video

**If possible, please provide a logo for the service (512x512 minimum)**  https://w2g.tv/static/watch2gether-share.jpg

**Comment by sineckers** [comment]
Working on it now

**Comment by sineckers** [comment]
I have some problems with my pc so i cant do it 
Unassigned

**Comment by DoggoKt** [comment]
🚀 I'll pick up on this one.

**Comment by DoggoKt** [comment]
Nevermind, I don't have much time. If anyone is going to pick up on it, let me know (@) and I can provide some of the code I managed to write.

**Comment by slow** [comment]
@DoggoKt I'm willing to pick up on this, could you add me on discord? It's in my bio.

**Comment by slow** [comment]
Picking this up.

**Comment by mlunax** [comment]
Is this still in developement?
Cuz I am interested in developing this presence.
@DoggoKt

**Comment by DoggoKt** [comment]
> Is this still in developement?
> Cuz I am interested in developing this presence.
> @DoggoKt 

No, feel free to pick it up. Sadly I also don't have the code anymore so you're on your own. Enjoy!
