### ISSUE TITLE
Hide presence when no longer in the browser

### ISSUE THREAD

**Issue by werymanen** [PreMiD/Presences#1957]
**Is your feature request related to a problem? Please describe.**
Yes.
I don't like it when I go on a site, for example, Twitter, and leave, do something in another program, and it still says that I'm on Twitter.

**Describe the solution you'd like**
Hide the presence if the window is not active.
So when I click away, it no longer says that I'm on that site.
Exceptions are streams, like music and video, where it continues to play when I click away.

**Describe alternatives you've considered**
Hide the presence if the user isn't active for a few seconds.
Exceptions are music and video sites, and things we read, like newspapers.

**Additional context**
none

**Comment by kawakaami** [comment]
Move it to https://github.com/PreMiD/Extension/issues please as it isn't problem with presences. Thank you :)

**Comment by werymanen** [comment]
Moved to https://github.com/PreMiD/Extension/issues/36
