### ISSUE TITLE
iQIYI | iq.com/iqiyi.com

### ISSUE THREAD

**Issue by JB220** [PreMiD/Presences#1966]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu) Payment is only required if the user buys a VIP subscription.
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?**  iQIYI - Note - This service has two versions of the site. The english version and the chinese version. I feel most will use the english version, but i'll link both anyways https://www.iq.com/ (English), https://www.iqiyi.com/ (Chinese)

**What should the Presence display?**  
Should show when the user is browsing. (If user is looking at the episodes of a show, the presence should have something along the lines of (Browsing for episodes of, 'Show/Movie Name')
Presence should display what drama/movie etc the user is watching, the episode and name (if there is one) they are on, preferably a countdown timer too, to show how long is left and showing when user has paused (similar to that used in the Netflix presence)

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Isa27-0** [comment]
https://premid.app/store/presences/iQIYI 
Now this request has been completed
