### ISSUE TITLE
itch.io

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#1969]
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
   ° From the tags: Erotic and/or Adult Content
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** Itch.io: https://itch.io

**What should the Presence display?** Service name, game name (if possible, for web games, show what you are playing) and the time you are on the page

**If possible, please provide a logo for the service** 
![w1htiJ0v_400x400](https://user-images.githubusercontent.com/68751594/90315590-03c6c980-def3-11ea-9367-89e0b04502e0.png)

**Comment by Alanexei** [comment]
#2111

**Comment by Isa27-0** [comment]
@Alanexei I had seen it before, even so, thanks
