### ISSUE TITLE
NVIDIA GeForce NOW | play.geforcenow.com

### ISSUE THREAD

**Issue by ghost** [PreMiD/Presences#1982]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
**There are membership options, but its free**
- [x] Does the website feature NSFW content? (e.g. porn, etc...) 
**Depends on the game you’re playing**
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  christian#1111

**What's the name of the service?**  NVIDIA GeForce Now https://play.geforcenow.com/

**What should the Presence display?**  What game is the user playing and how long whenever they are playing it.

**If possible, please provide a logo for the service (512x512 minimum)**  https://i.ibb.co/xmdr1rG/73-F33769-93-CB-4-AD0-950-F-CD3-E4-D9-C4-F79.jpg

You need to follow these steps to access GFN on browser: https://www.reddit.com/r/GeForceNOW/comments/ichfaw/guide_play_gfn_play_on_any_computer_via_chrome/

**Comment by Isa27-0** [comment]
I don't know if programming will be able to give a Rich Presence with games. Since, as you said yourself, you need to create a custom agent using the User-Agent Switcher.
But on the other hand, the site can be accepted more by the store, example: https://www.nvidia.com/en-us/shop/geforce/?page=1&limit=9&locale=en-us&gpu=RTX%202080%20Ti

Sorry if I said something wrong, I can be a layman at it

**Comment by doomlerd** [comment]
It's possible, I guess.

**Comment by JakeR04** [comment]
Geforce now already does this in discord

**Comment by Isa27-0** [comment]
> Geforce now already does this in discord

@JakeR04  How did you find that out?

**Comment by Overimaginer** [comment]
> Geforce now already does this in discord

yes but only the desktop client does, not the browser client

**Comment by Overimaginer** [comment]
> > Geforce now already does this in discord
> 
> @JakeR04 How did you find that out?

**Comment by Overimaginer** [comment]
oops

**Comment by Overimaginer** [comment]
> 
> 
> Geforce now already does this in discord

not the browser version no

**Comment by Overimaginer** [comment]
> 
> 
> > Geforce now already does this in discord
> 
> @JakeR04 How did you find that out?

https://github.com/PreMiD/Presences/issues/1982#issuecomment-696397353

**Comment by Isa27-0** [comment]
> #1982 (comment) 

@Overimaginer It's like I thought days ago
