### ISSUE TITLE
Trello presence shows private boards.

### ISSUE THREAD

**Issue by n3oney** [PreMiD/Presences#2006]
**Describe the Bug**

When you are browsing a private board on Trello, the Trello presence still shows it normally. I believe that should not happen or should be togglable in the settings.

**Steps to Reproduce**

1. Open a private Trello board

**Expected Behavior**

You don't have a presence.

**Screenshots**

-

**Environment**

- OS:  Windows 10
- Browser:  Chrome
- Version: 84.0.4147.135
  

**Additional context**

To fix the issue, it probably is really simple, just check if `document.getElementById("permission-level").textContent === "Private"`. I will not attempt to fix that as I do not havea coding environment installed, so I will just leave this here. Thanks for anyone who makes a pull to fix it.

**Comment by marinofranz** [comment]
Will definitely try to fix this!

**Comment by marinofranz** [comment]
Pull request pending approval #2017

**Comment by n3oney** [comment]
Awesome!

**Comment by n3oney** [comment]
Alright, I see it's merged. I'll check if the issue is resolved and close it.

**Comment by doomlerd** [comment]
was it resolved for you?

**Comment by marinofranz** [comment]
If it's not resolved, maybe try to re-add the presence?
