### ISSUE TITLE
Google Photos | photos.google.com

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#2024]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** Google Photos: https://photos.google.com

**What should the Presence display?** The name of the service, the name of the album and the time you are on the screen

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/68751594/127357423-d5f430e9-c82f-4bbf-ab5f-044cda969465.png)

**Comment by marinofranz** [comment]
Adding to my to-do list!

**Comment by Isa27-0** [comment]
Thanks!
