### ISSUE TITLE
Blackboard | blackboard.com

### ISSUE THREAD

**Issue by josegoust** [PreMiD/Presences#2038]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
\|ψ|/ Reverse Eye79g \|ψ|/#9853
**What's the name of the service?** 
Collaborate or blackboard: blackboard.com, ca.bbcollab.com
**What should the Presence display?** 
 if I am studying or in a virtual classroom, and the name of matter
**If possible, please provide a logo for the service (512x512 minimum)**  ![images](https://user-images.githubusercontent.com/70378172/91560638-89457300-e910-11ea-94d1-8a1815208f28.png)

**Comment by josegoust** [comment]
![bb-logo-330x250](https://user-images.githubusercontent.com/70378172/91561219-96169680-e911-11ea-92ff-7c300793ac8c.png)

**Comment by Isa27-0** [comment]
I resized the current icon to the appropriate size (512x512)
![blackboard_collaboratte_issue](https://user-images.githubusercontent.com/68751594/91575261-bc423380-e91d-11ea-8531-223aa86cf955.png)

**Comment by josegoust** [comment]
Thx Isa

**Comment by flarely** [comment]
please rename to Blackboard | blackboard.com
