### ISSUE TITLE
Bug Report | Google’s presence doesn’t appear on Opera

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#2039]
**Describe the Bug**
Google’s presence doesn’t appear on Opera (#937), just like it did for GitHub

**Steps to Reproduce**

1. Install Opera or Opera GX, or if you have already installed it, open it
  ° Install the PreMiD extension, if you have installed Opera now and apply the Google presence in the store
2. Open on the Google website, or do a search on the browser home screen (Speed Dial, in the case)
   ° If you're on the site, do a search

**Expected Behavior**
This has happened most of the time, even my friend was able to show his search (He uses the 'New Edge'). I saw that you didn't understand anything in the Issue I mentioned above, so I ended up creating a new one now

**Screenshots**
On the home screen:
![unknown](https://user-images.githubusercontent.com/68751594/91578367-6e7afa80-e920-11ea-985a-8cdbd9124734.png)
In a search: 
![unknown (1)](https://user-images.githubusercontent.com/68751594/91578530-b00ba580-e920-11ea-8382-b96c05e50cda.png)

**Environment**

- OS: Windows 10 Home Single Language, version 1903 (x64)
- Browser: Opera 
- Version: 70.0.3728.133 (I don't remember if mine is 32bits or 64bits, sorry), but this already happened in previous versions

**Comment by kawakami** [comment]
Could you provide errors from console? Thanks.

**Comment by Isa27-0** [comment]
> Could you provide errors from console? Thanks.

When I find a mistake, I will warn it here :)

**Comment by ririxichan** [comment]
Still didn't get any errors from console.

**Comment by Isa27-0** [comment]
After being dumb and not understand what the 'console errors' were, I went to check and strangely there was no error, just this message:

> Opera has modified script or content on www.google.com (PATCH- `browser.js:61` 1269, Hide Chrome ad from Google pages). See browser.js for details

I don't know if that was the cause of not showing this presence here:
![image](https://user-images.githubusercontent.com/68751594/97186715-63a5e000-1780-11eb-8ce9-e60515ae79c8.png)
About these 2 or 3 errors, I don't know if it has anything to do with this problem of the presence:
![image](https://user-images.githubusercontent.com/68751594/97188995-e4fe7200-1782-11eb-8eb9-445a01a8d223.png)
In a search, the sentence changes:

> Opera has modified script or content on www.google.com `localhost/browser.js:61m` (PATCH-1269, Hide Chrome ad from Google pages). See browser.js for details

![image](https://user-images.githubusercontent.com/68751594/97190117-19bef900-1784-11eb-8641-d1b573c7dbc8.png)

Days before that I tested on Chrome without checking the console, but it was working normally. (as expected)
@ririxichan

**Comment by CyberByte-js** [comment]
I think it is something in the Opera AdBlocker that is causing the problem, look: 

> Opera has modified script or content on www.google.com localhost/browser.js:61m (PATCH-1269, **Hide Chrome ad from Google pages**). See browser.js for details

**Comment by CyberByte-js** [comment]
I found it! In the extensions menu, just go to PreMid and check "Allow access to search page results"
![image](https://user-images.githubusercontent.com/71409005/97312273-0f643400-1844-11eb-954a-6be8f39d0547.png)

**Comment by Isa27-0** [comment]
> I found it! In the extensions menu, just go to PreMid and check "Allow access to search page results"
> ![image](https://user-images.githubusercontent.com/71409005/97312273-0f643400-1844-11eb-954a-6be8f39d0547.png)

Oh boy, I think that can at least get into the presence's presence. Well, I think I'm going to close the Issue
