### ISSUE TITLE
Bonk | bonk.io

### ISSUE THREAD

**Issue by josegoust** [PreMiD/Presences#2042]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
\|ψ|/ Reverse Eye79g \|ψ|/#9853
**What's the name of the service?** 
bonk,io
**What should the Presence display?** 
The name of the game and the time, similar to slither.io
**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by PiggyPlex** [comment]
Considering it's a flash game, it'll be hard to extract much information. We can only show that you're playing the game, but not much more without using dodgy tools such as OCR.

**Comment by josegoust** [comment]
U can make similar to slither.io 👍

**Comment by safan41** [comment]
iirc the creator worked on http://bonk2.io/ which implemented pretty much everything from the original including its maps and is in html5 which can make things easier to scrape. It's not the request but I feel this would be more feasible.
