### ISSUE TITLE
TORN | torn.com

### ISSUE THREAD

**Issue by Jorc0** [PreMiD/Presences#2044]
[TORN](https://www.torn.com/)

- [x] Is it a popular site? **Probably yes (30k+ daily online users, 1,184,290 registered players)**
- [x] Is the website older than 2 months? **15 years old**
- [ ] Is the site locked to a specific country/region? **No**
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) **No**
- [ ] Does the website feature NSFW content? (e.g. porn, etc...) 
- [ ] Are you a donator/patron? **No**
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? **Yes**

> 
**As it is played online usually on browser, id like PreMiD to have it and let my friends know that im playing it, if you want to know more details about it, what to show on the presence and  other stuff tell me and i'll do**

**What should the Presence display?** 
The city we are, (Torn, Africa, George Island, etc)
In hospital/jail/Okay
And travelling to... or returning to Torn from.... With elapsed or remaining time

**What's the name of the service?**
Torn.com 

![image](https://user-images.githubusercontent.com/48130077/92666566-e0cce100-f309-11ea-85cc-d0ea448f409a.png)

Here's whats the game about, directly extracted from Torn.com

> Torn is a text-based online RPG set in Torn City, a dark, murky underworld where only the sharpest survive. In Torn City you can be anyone and do anything. Build your character to infinite strengths and play it your way.
> 
> Torn City is a massively multiplayer game with thousands of active players around the world. Join them, attack them, befriend them, marry them, trade with them, compete with them. Whatever you do - Do it now!
> 
> Torn City is an exciting, gritty, real-life text based game. Text-based games are addictive and great fun to play. Torn City is no exception!
> 
> New players start off weak and poor. Beware, the murky underworld of Torn City shows no mercy so be on your guard from the off. Opportunists will not think twice to mug or hospitalize you for a few bucks. As an online crime RPG game, the rules are very simple; Build a new life. Get to the top. Avoid being killed. Choose any route to get there. In Torn City you can be ANYONE and do ANYTHING.
> 
> To earn money and increase your status you'll need to get your hands dirty, commit crimes and attack other players. The stronger you are the more battles you win so prepare to train hard to become the best.
> 
> Other game features include starting or joining a faction, collecting and trading items, invest in Torn City stocks, avoid jail and hospital, undertake missions, race cars, get married, get a job or start a company, take education courses, win big in the casino, play poker, invest in the bank, shop for items, program viruses, read or write for the Torn City Times newspaper, buy multiple properties, travel, hunt... The list is endless, but there's plenty of help in the Torn Wiki.
> 
> Torn City is one of the largest text based RPG's online with tens of thousands of active daily players. Like most indie MMORPGs, Torn City is deep and constantly evolving with feature rich updates, so there's always something new to discover. This is what sets Torn City aside from other text-based RPG / PBBG.
> 
> Register Now and keep playing to unlock hidden features, opportunities and discover more truths about this murky city.
> 
> Browser Games and Online Strategy Games
> These days, with the most advanced personal computers and consoles in the world running games with cutting edge graphics, we can sometimes forget where we came from. The true essence of a game is in its gameplay and the way in which it involves players, which is why the browser based online strategy game is as popular as ever.
> 
> Everybody remembers the Runescape craze from a few years ago. That made browser games mainstream once again, but since its decline there has been a large gap. And we believe that Torn City is the perfect game to fill that gap. This browser game is so appealing because it's also the type of game you can play at a pace that suits you. It's the type of game you can spend hours on or it's the type of game you can sneak onto whilst at work or to take a break. That's why Torn City has tens of thousands of people playing each day.
> 
> Online strategy games are even better when it comes to playing within a browser, as the whole game is geared towards the casual player. This is what has made them so popular.
> 
> Torn City is the ultimate online strategy game. It encompasses the depth and scale of a MMORPG with the ease-of-play of the simplest browser games. Now you can play anywhere, any time and enjoy this browser game in all its glory.
>

**Comment by fr0r** [comment]
guns and drugs are not nsfw

**Comment by Jorc0** [comment]
> guns and drugs are not nsfw

Oh really?

**Comment by Isa27-0** [comment]
> Oh really?

Yes, I think NSFW is only accepted for pornographic content

**Comment by Alanexei** [comment]
Guns and drugs in a game setting isn't an issue. What would be an issue is if these were real guns and drugs being sold over a market.

**Comment by Alanexei** [comment]
You can unmark it as nsfw
