### ISSUE TITLE
[Request] Anime Soul Network Discord Rich Precense

### ISSUE THREAD

**Issue by heavenkev1n** [PreMiD/Presences#2056]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
`[絶剣] Zekken🌸#0523`

**What's the name of the service?** 
https://animesoul.com/

**What should the Presence display?** 
The most basic things, such as "Fusing cards" when I visit animesoul.com/fusion
and other sub sites inside animesoul.com
and should have a timer as well

**If possible, please provide a logo for the service (512x512 minimum)** 
Seems hard to find the logo at 512x512 so I uploaded a 100x100
![637463575299883024](https://user-images.githubusercontent.com/40920488/91737429-13920f00-eb7d-11ea-9e5d-68664ecd7a2d.png)

**Comment by heavenkev1n** [comment]
[絶剣] Zekken🌸#0523
idk why the 0 disappeared

**Comment by Bas950** [comment]
Fixed it for you :)

**Comment by fr0r** [comment]
[Already added](https://premid.app/store/presences/Anime%20Soul)
