### ISSUE TITLE
tvtime.com

### ISSUE THREAD

**Issue by frozaum** [PreMiD/Presences#207]
**What's the name of the service?**
Ex. www.tvtime.com | TV Time

**What should the Presence display?**
Informations about the current show i'm looking and what episodes i watched so far

**Why do you want support for this service?**
TV Time is like MyAnimeList but for shows and movies itself, it's a good service even tho the web version is a bit meh, still i would love to see a presence for this service.

**Are you able to provide an image for the service? (512x512 minimum)**
![image](https://user-images.githubusercontent.com/34042085/63891520-c1436e80-c9bb-11e9-8ba8-054c94d0cd1b.png)

**Comment by OfficialCRUGG** [comment]
Added in V2 :)
