### ISSUE TITLE
G1 | g1.globo.com

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#2089]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** G1: http://g1.globo.com/

**What should the Presence display?** Service name, the subject you are reading and the time you are on the page.

**If possible, please provide a logo for the service (512x512 minimum)** 
![unnamed](https://user-images.githubusercontent.com/68751594/92125981-03c13780-edd6-11ea-87ba-129b75eee5b9.png)

**Comment by fr0r** [comment]
not region-locked

**Comment by Isa27-0** [comment]
Oh, ok
