### ISSUE TITLE
Amazon Music

### ISSUE THREAD

**Issue by DJClement50** [PreMiD/Presences#209]
**What's the name of the service?**
https://music.amazon.ca/ | Amazon Music Canada
https://music.amazon.fr/ | Amazon Music FR
https://music.amazon.com | Amazon Music

** What should the presence show? **
Music in progress

** Why do you want assistance for this service? **
When you have a Twitch Prime subscription you can use this music service and I think it will be nice to post it in the discord rich.

** Can you provide an image for the service? (512x512 minimum) **
If you can provide the logo pls paste a link here or picture
https://images-eu.ssl-images-amazon.com/images/I/41KV82tMKYL.png

**Comment by frozaum** [comment]
added #227
