### ISSUE TITLE
Brainly | brainly.com

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#2094]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
   * Contains subscription, but the site is not paid.
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** Brainly:  https://brainly.com

**What should the Presence display?** Service name, the question you’re looking at and the length of time you’re on the page

**If possible, please provide a logo for the service (512x512 minimum)** 
_The icon is from the mobile version_
![unnamed](https://user-images.githubusercontent.com/68751594/92149841-f0719480-edf4-11ea-950b-78b5305aec5e.png)

**Comment by fr0r** [comment]
not region-locked
