### ISSUE TITLE
TechTudo | www.techtudo.com.br

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#2100]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** TechTudo: https://www.techtudo.com.br

**What should the Presence display?** The name of the service, the subject you are reading and the time you are on the page (Similar to G1 and TecMundo)

**If possible, please provide a logo for the service (512x512 minimum)** 
![1](https://user-images.githubusercontent.com/68751594/92239530-91159200-ee91-11ea-916a-d513dbfac3e6.png)

**Comment by fr0r** [comment]
not region-locked
