### ISSUE TITLE
Set Filmizle | www.setfilmizle.vip

### ISSUE THREAD

**Issue by vutix** [PreMiD/Presences#2113]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** ◈ VutiX#6666

**What's the name of the service?** https://www.setfilmizle.vip/

**What should the Presence display?** what we watch what we do on the site and more

**If possible, please provide a logo for the service (512x512 minimum)** https://hizliresim.com/p9scfv

**Comment by eggsy** [comment]
Maybe later.
