### ISSUE TITLE
New suggestion for presence: Microsoft Teams

### ISSUE THREAD

**Issue by MatadorProBr** [PreMiD/Presences#2117]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Matador#2690

**What's the name of the service?** Microsoft Teams

**What should the Presence display?** If you are in a meeting, how many people are in the same meeting, just like Meet.

**If possible, please provide a logo for the service (512x512 minimum)** 
![Microsoft Teams](https://user-images.githubusercontent.com/71022656/92609897-75ddc480-f28d-11ea-8233-c8478f81d4d9.jpeg)

**Comment by Bas950** [comment]
#2118

**Comment by MatadorProBr** [comment]
> #2118

what?
