### ISSUE TITLE
Microsoft Teams | teams.microsoft.com

### ISSUE THREAD

**Issue by MatadorProBr** [PreMiD/Presences#2119]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
_(It's free but it's also paid)_
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Matador#2690

**What's the name of the service?** https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/group-chat-software | Microsoft Teams

**What should the Presence display?** If you are in a meeting, how many people are in the same meeting, just like Meet.

**If possible, please provide a logo for the service (512x512 minimum)** 
![Microsoft Teams](https://user-images.githubusercontent.com/71022656/92611069-c7d31a00-f28e-11ea-841a-d7c5b8843da4.jpeg)
_(I couldn't find it for 512x512 so I put this)_

**Comment by Bas950** [comment]
bruh why do you keep making new ones instead of editting the old ones... xD

**Comment by MatadorProBr** [comment]
> bruh why do you keep making new ones instead of editting the old ones... xD

I joined now so I don't know how to edit, sorry xd

**Comment by v262001** [comment]
I am also join

**Comment by AnishDe12020** [comment]
You guys developing the presence for MS Teams?
If so by when will it be out?

**Comment by Snazzah** [comment]
Added from #2533 
cc @AnishDe12020
