### ISSUE TITLE
Linus Tech Tips | linustechtips.com

### ISSUE THREAD

**Issue by itswillum** [PreMiD/Presences#2120]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
yes, around 660000 accounts
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
itswillum#0001 (may change once my nitro runs out)
**What's the name of the service?** 
linustechtips.com | Linus Tech Tips Forum
**What should the Presence display?** 
It should show which thread you're viewing, profile you're viewing, or category you're viewing (if not in a thread).
**If possible, please provide a logo for the service (512x512 minimum)** 
![unnamed](https://user-images.githubusercontent.com/45744989/92614449-103c0900-f28a-11ea-85c9-f3db69c609c4.jpg)

**Comment by Isa27-0** [comment]
Hi, I came to tell you that the presence is already being made (#2149) :)
