### ISSUE TITLE
Jstris | jstris.jezevec10.com

### ISSUE THREAD

**Issue by itswillum** [PreMiD/Presences#2121]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
Around 50-100k users I believe, but don't quote me on that
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
itswillum#0001 discriminator may change, but I'll be in the support server
**What's the name of the service?** 
jstris.jezevec10.com | Jstris
**What should the Presence display?** 
It should show how long you've been playing for, what room/gamemode you're playing, and whether you're viewing leaderboards or a specific profile. There are several different public rooms to play in, and the possibility to create a private room (in which the status would just say **Private room.** As for gamemodes, there are different names for them but that's pretty much it unless you want to go really into detail about how many lines left you have to clear, and so on.
**If possible, please provide a logo for the service (512x512 minimum)** 
![unnamed](https://cdn.discordapp.com/emojis/560548686552104992.png?v=1)

**Comment by Snazzah** [comment]
#2261 was merged, so this issue is cleared
