### ISSUE TITLE
Line TV | tv.line.me/linetv.tw

### ISSUE THREAD

**Issue by alterlove** [PreMiD/Presences#2124]
- [x] Is it a popular site?  (This depends of the person)
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

Line TV

The presence should display the name of the presence "Line TV", the name of what are you currently playing, the chapter, and if possible, the minute.

![image](https://user-images.githubusercontent.com/38593578/92754061-cedf5280-f38a-11ea-9927-c20280fdeb09.png)

**Comment by Isa27-0** [comment]
URL: https://tv.line.me 
~~You didn't put in the suggestion~~

**Comment by fr0r** [comment]
not region-locked in Brazil

**Comment by SlowLife1661** [comment]
Working on this right now
