### ISSUE TITLE
Town of Salem

### ISSUE THREAD

**Issue by 13xens** [PreMiD/Presences#2127]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?**
blankmediagames.com
blankmediagames.com/TownOfSalem

**What should the Presence display?** 
Playing: Town of Salem
In Lobby/In Games (Classic/Custom/Ranked)
Day #/Night # (i don't know if this is possible though, might be difficult so i think can make do without it)

**Comment by Isa27-0** [comment]
Please close one of the Issue (#2126) made. You duplicated
