### ISSUE TITLE
Google Podcasts | podcasts.google.com

### ISSUE THREAD

**Issue by Razi1660** [PreMiD/Presences#2141]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** フクロウ#3262

**What's the name of the service?** Google Podcasts | https://podcasts.google.com 

**What should the Presence display?** It should display the name of the service (Google Podcasts), the name of the podcast that the user is listening to and it's cover art. Lastly, a progress bar to show how much of a particular episode the user has listened to. 

**If possible, please provide a logo for the service (512x512 minimum)** ![Google_Podcasts_Logo](https://user-images.githubusercontent.com/71204553/93010961-3219e200-f54f-11ea-9473-1ad571315b9d.png)

**Comment by snoweyfoxx** [comment]
👌

**Comment by MrBartusek** [comment]
![image](https://user-images.githubusercontent.com/23432278/95618027-a8d1ce80-0a6c-11eb-8ea2-a75613a9cfd9.png)
I don't think google podcast is really possible, classes are quite possibly randomly generated every session/day/build or something

**Comment by snoweyfoxx** [comment]
> ![image](https://user-images.githubusercontent.com/23432278/95618027-a8d1ce80-0a6c-11eb-8ea2-a75613a9cfd9.png)
> I don't think google podcast is really possible, classes are quite possibly randomly generated every session/day/build or something

They aren't randomly generated, nor does changing accounts or browsers change the classes. The information can possibly be grabbed by using the jsnames as well, which for sure do not change.

**Comment by MrBartusek** [comment]
I am working on that!
