### ISSUE TITLE
Udemy Presences | Wrong Section | 

### ISSUE THREAD

**Issue by monish-1234** [PreMiD/Presences#2143]
Udemy Presences shows the first section by default. Does not update as we proceed through the course.

![Screenshot (540)](https://user-images.githubusercontent.com/26372820/93015564-26263280-f5d8-11ea-9e2e-72d79bae883d.png)
![Screenshot (541)](https://user-images.githubusercontent.com/26372820/93015567-28888c80-f5d8-11ea-93e5-c1756044011e.png)

**Comment by fr0r** [comment]
Hello @monish-1234 please, use the [correct format](https://github.com/PreMiD/Presences/issues/new?template=bug_report.md) next time you're reporting a bug, thanks.

(closed)
