### ISSUE TITLE
Dash Radio | dashradio.com

### ISSUE THREAD

**Issue by coledeb** [PreMiD/Presences#2167]
**Prerequisites and essential questions**
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [X] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**
Cole#0001

**What's the name of the service?**
https://dashradio.com/ | Dash Radio

**What should the Presence display?**
The presence would ideally display the logo, the name of the service (Dash Radio), the title of the current track - the artist name, and the channel name. (Very similarly or identically to how the SiriusXM presence is implemented)

**If possible, please provide a logo for the service (512x512 minimum)**
![Dash Radio Logo](https://user-images.githubusercontent.com/27379200/93336855-ed5fa680-f7ed-11ea-81fc-1b1d5263e1d3.png)
![Dash Radio Logo White Large](https://user-images.githubusercontent.com/27379200/93336885-f6507800-f7ed-11ea-873b-c7801a127ed9.png)

**Comment by misapprehending** [comment]
I have opened a pull request for this.

https://github.com/PreMiD/Presences/pull/2271

**Comment by ririxichan** [comment]
~~protip: just add to pr desc ``Resolves #2167`` and it will close this issue after merging pr~~
