### ISSUE TITLE
Amazon Music: Region Specific Sites

### ISSUE THREAD

**Issue by STK101** [PreMiD/Presences#2169]
**Is your feature request related to a problem? Please describe.**
I am from India, and we here don't use the 'music.amazon.com' site, our accounts are registered on 'music.amazon.in' so the rich presence feature can't be availed. 

**Describe the solution you'd like**
I'd like the development team to please add "music.amazon.in" too in the supported URLs.

**Comment by ririxichan** [comment]
Should work since it has regex and detects all tld.
