### ISSUE TITLE
Agar-ar | agar-ar.com

### ISSUE THREAD

**Issue by Mustatafa11** [PreMiD/Presences#2170]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Developer: hendawi# 7592 |  Game Admin: Ahmad .# 1111 |  Game Supervisor:ᴹ𝔲𝔰t𝔞𝔣𝔞 ꋬ𝔩-ᴳ𝔥𝔞𝔫𝔦𝔪# 0001

**What's the name of the service?**  agar-ar.com

**What should the Presence display?** 
At first the player accesses the link to the game through any type
Of the types of browser that it has
on the computer and be through this link agar-ar.com
 
The player can play agar-ar by accessing via his private email on the networking site
Facebook or play directly. But when you play in this game by
Entering his private email on Facebook can share his points in
The game with his friends on the social networking site Facebook. 

Then, after choosing the way to play, he has to enter his name in the box that appears to him.               
The game is then started.                           
Be mindful that this game needs to be played using fast net in order to get the best quality.
 But when using the player slow net, you will notice a slow use of the game and the cutting of the game while playing.

**If possible, please provide a logo for the service (512x512 minimum)**  https://cdn.agar-ar.com/images/agar.png

**Comment by ririxichan** [comment]
@Mustatafa11 please upload logo with size 512x512 actual one is 400x400
