### ISSUE TITLE
Add presence AnimesOneHD

### ISSUE THREAD

**Issue by Shadowz496** [PreMiD/Presences#2180]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [no] Is the site a paid service? (e.g. Netflix, Hulu)
- [no] Does the website feature NSFW content? (e.g. porn, etc...)
- [no] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Enricø#2020

**What's the name of the service?** animesonehd

**What should the Presence display?**  AnimeOneHd

**If possible, please provide a logo for the service (512x512 minimum)**   
![download](https://user-images.githubusercontent.com/71602318/93717311-59723f80-fb4b-11ea-82c4-be9df31fdac2.jpg)

**Comment by Isa27-0** [comment]
URL: https://animesonehd.xyz/
