### ISSUE TITLE
Viz presence

### ISSUE THREAD

**Issue by Yo-Electric** [PreMiD/Presences#2194]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [x ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ NO] Does the website feature NSFW content? (e.g. porn, etc...)
- [x ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Electric#4444

**What's the name of the service?** 
VIZ

**What should the Presence display?** 
Viz
Reading One Piece (series name)
Chapter 900 (Chapter number)

**If possible, please provide a logo for the service (512x512 minimum)** 
![yhuba2ricrt3zgihfbwv](https://user-images.githubusercontent.com/71672601/93824286-2ace9480-fc31-11ea-96a6-fceb335924bc.jpg)

**Comment by Isa27-0** [comment]
Duplicate, someone has requested a request before: (#1089) and it's already being done by Bas950 (#1418)
