### ISSUE TITLE
Flickr | www.flickr.com

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#2199]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- Contains PRO subscription
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** Flickr: https://www.flickr.com

What is the Flickr?

>Flickr is an American image hosting and video hosting service, as well as an online community. It was created by Ludicorp in 2004 and has been popular with hosting high resolution photos by amateur and professional photographers. It has changed ownership several times and has been owned by SmugMug since April 20, 2018.
As of March 20, 2013, Flickr had a total of 87 million registered members and more than 3.5 million new images uploaded daily, as reported by The Verge. On August 5, 2011, the site reported that it was hosting more than 6 billion images. Photos and videos can be accessed from Flickr without the need to register an account, but an account must be made to upload content to the site. Registering an account also allows users to create a profile page containing photos and videos that the user has uploaded and also grants the ability to add another Flickr user as a contact. (Wikipédia: https://en.wikipedia.org/wiki/Flickr)

**What should the Presence display?** Name of the service, the name of the photo or video, the author's name and the time it is on the page

**If possible, please provide a logo for the service (512x512 minimum)** 
There are two types of logo, but I chose this:
![unnamedflicko](https://user-images.githubusercontent.com/68751594/93920915-37f98b00-fce6-11ea-8061-bbfb2d3b406f.png)

**Comment by MySixSenses** [comment]
I'll try to work on this, but since my PreMID is cursed I probably won't be able to test it.

**Comment by MySixSenses** [comment]
Also, could you put the logo on [imgur](imgur.com)? PreMID rejects any images that aren't on [imgur](imgur.com)

**Comment by MySixSenses** [comment]
> I'll try to work on this, but since my PreMID is cursed I probably won't be able to test it.

Working now.
