### ISSUE TITLE
VVVVID | VVVVID.it

### ISSUE THREAD

**Issue by Fox3n** [PreMiD/Presences#22]
**What's the name of the service?**
https://www.vvvvid.it | VVVVID

**What should the Presence display?**
Informations about the current video

**Why do you want support for this service?**
mh well, same as animeworld I suggested earlier. This is a legal site btw OwO

**Are you able to provide an image for the service? (512x512 minimum)**
https://lh5.ggpht.com/SrdgZ8Rk8t4YxvMbRucC-FZEHhHEp9XMToEzWdFI7SVFaiKQfMxqees_nj5wq5iRVw=w300

**Comment by Bas950** [comment]
Not available in my country.
