### ISSUE TITLE
Animeindo | animeindo.cc

### ISSUE THREAD

**Issue by FozuX** [PreMiD/Presences#2205]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** ! Tomo愛#9766

**What's the name of the service?** animeindo.cc 

**What should the Presence display?**  show what anime we watch

**If possible, please provide a logo for the service (512x512 minimum)** 
![logo](https://i.imgur.com/vzvViuH.png)

**Comment by Isa27-0** [comment]
The logo is not in its proper size (The correct one is 512x512)
