### ISSUE TITLE
Suggest Presence discord phone (apple and android, with apple music and google play music)

### ISSUE THREAD

**Issue by CAPSMOIQUI** [PreMiD/Presences#2216]
**Prerequisites and essential questions** 
- [x] Is it a popular site? Yes, iTunes and Google play music
- [x] Is the website older than 2 months?  sure.
- [ ] Is the site locked to a specific country/region? I dont know.
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) yes (i dont know for itune) but you can pay for Google play music.
- [ ] Does the website feature NSFW content? (e.g. porn, etc...) no
- [ ] Are you a donator/patron? No
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? No

**What's your Discord username?**  𝕮_𝕬𝕻𝕾_𝕸𝕺𝕴_𝕼𝖀𝕴#0001

**What's the name of the service?** 
Google play music for Android and iTunes for Apple

**What should the Presence display?**  We can see the song we listen on  Android, apple, smartphone, its the same of Spotify Activity

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by flarely** [comment]
Existing.

**Comment by ririxichan** [comment]
PreMiD will not be on phones and these presences already exists with web version. Check store.

**Comment by Isa27-0** [comment]
@CAPSMOIQUI 
PreMiD is not supported on mobile OS, as an extension is required to run. Besides Discord has not yet added 'Rich Presence' on these platforms

**Comment by fr0r** [comment]
as stated above, PreMiD is not supported on mobile devices (and probably will never be) due to both of those apps have no support for RPC, and for that reason, this issue is invalid.
