### ISSUE TITLE
SySAlfie Service Request

### ISSUE THREAD

**Issue by alfiefroggoman** [PreMiD/Presences#2219]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [ ] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** MrAlfieGamer#2202

**What's the name of the service?** SySAlfie - www.sysalfie.xyz

**What should the Presence display?** SySAlfie is a service that creates discord bots

**If possible, please provide a logo for the service (512x512 minimum)** https://sysalfie.xyz/logo.png

**Comment by ririxichan** [comment]
![image](https://user-images.githubusercontent.com/9348108/94310701-93877b00-ff69-11ea-906c-25292659690a.png)

**Comment by Mirazex** [comment]
![image](https://user-images.githubusercontent.com/22584144/94324071-ea5c7700-ffa0-11ea-8089-2d213b9862ac.png)

**Comment by alfiefroggoman** [comment]
Hello,

I’m sorry about that, I will get it fixed today.

Thanks
Alfie

**Comment by alfiefroggoman** [comment]
Hello,

This issue has been fixed.

Thanks
Alfie
