### ISSUE TITLE
SySAlfie.Xyz | Service Request

### ISSUE THREAD

**Issue by alfiefroggoman** [PreMiD/Presences#2222]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [ ] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** MrAlfieGamer#2202

**What's the name of the service?** SySAlfie - www.sysalfie.xyz

**What should the Presence display?** Make the image the SySAlfie logo and place the description as Viewing the website. Make sure the title is SysAlfie too. 

**If possible, please provide a logo for the service (512x512 minimum)** https://sysalfie.xyz/logo.png

**Comment by Isa27-0** [comment]
The domain has less than 1 day (in the image), the minimum accepted is 2 months. In addition to being a website about your service (#2223), it is without anything very important to the point of having a presence. I'm sorry, but your request is currently invalid.
![image](https://user-images.githubusercontent.com/68751594/94342403-37fbd280-ffe7-11ea-96e7-8f4048cf3e41.png)

**Comment by alfiefroggoman** [comment]
Okay, I'll apply in 2 months time.
