### ISSUE TITLE
Musify.co.uk | Spotify Visualizer 

### ISSUE THREAD

**Issue by alfiefroggoman** [PreMiD/Presences#2223]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** MrAlfieGamer#2202 

**What's the name of the service?** www.musify.co.uk |  Musify 

**What should the Presence display?**  Playing Musify, Display the logo and list that Musify is a free Spotify Visualiser,  Make it elapsed too.

**If possible, please provide a logo for the service (512x512 minimum)** https://imgur.com/a/QRGCJrf

**Comment by Isa27-0** [comment]
It is impossible to put it as 'listening', it may break Discord's Terms of Service (ToS)
https://github.com/PreMiD/PreMiD/issues/541

**Comment by Isa27-0** [comment]
And another, please add the website URL, there are many services with the same name @alfiefroggoman

**Comment by alfiefroggoman** [comment]
Hello,

Put it as playing please. Its www.musify.co.uk

Thanks @Isa27-0

**Comment by alfiefroggoman** [comment]
The domain "musify.co.uk" is not affiliated with "sysalfie.xyz". They were seperate requests.

I would like "Musify.co.uk" as a presence as it has been around longer than "sysalfie.xyz"
