### ISSUE TITLE
9anime status doen't show up when watching an anime or movie because of a url change

### ISSUE THREAD

**Issue by Superbug50** [PreMiD/Presences#2229]
**Describe the Bug**

9anime Status doesn't show up when watching anime or a movie.
**Steps to Reproduce**

1.Go to https://9anime.to
2. Search/Find a anime or movie
3.Watch the anime

**Expected Behavior**

Should show a status that you are watching "Some random anime"
**Screenshots**

**Environment**

- OS:  Linux mint 20
- Browser:  Firefox
- Version:  81.0 (64-Bit)
  

**Additional context**

Please add the url https://www12.9anime.to .

**Comment by Alanexei** [comment]
Unfortunately, the maintainer for this presence has quit the team and left the server. Updates won't be released anytime soon.

**Comment by Superbug50** [comment]
Oh.. ok..

**Comment by Mirazex** [comment]
I can do this?

**Comment by ririxichan** [comment]
Will fix it tomorrow.

**Comment by Isa27-0** [comment]
Hi, your bug is already being solved (#2253)
