### ISSUE TITLE
Mixcloud

### ISSUE THREAD

**Issue by OllieRadio** [PreMiD/Presences#223]
**What's the name of the service?**
https://mixcloud.com | Mixcloud

**What should the Presence display?**
The current mix/show, the uploader, and progress.

**Why do you want support for this service?**
It's similar to soundcloud, and it'd be cool to show what we're listening to on Mixcloud with PreMiD.

**Are you able to provide an image for the service? (512x512 minimum)**
https://www.brandeps.com/logo-download/M/Mixcloud-Icon-01.svg

**Comment by frozaum** [comment]
Mixcloud is already a presence (#140), so i will consider this as duplicate
Closed.
