### ISSUE TITLE
NetGalley | netgalley.com

### ISSUE THREAD

**Issue by jeijeisan** [PreMiD/Presences#2246]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  jeijeisan#5105

**What's the name of the service?**  NetGalley | https://www.netgalley.com

**What should the Presence display?**  Playing/Browsing NetGalley, Browsing Dashboard, Browsing Your Shelf, Finding a title/Searching, Browsing [book title + author]

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Isa27-0** [comment]
URL: https://www.netgalley.com

**Comment by ririxichan** [comment]
@jeijeisan please upload logo with size 512x512
