### ISSUE TITLE
Goodreads | goodreads.com

### ISSUE THREAD

**Issue by jeijeisan** [PreMiD/Presences#2247]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  jeijeisan#5105

**What's the name of the service?**  Goodreads | https://www.goodreads.com

**What should the Presence display?**  Playing/Browsing Goodreads, Browsing Home, Browsing [book title and author], Searching for..., Browsing profile

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Isa27-0** [comment]
URL: https://www.goodreads.com
The site is not blocked, at least, here in Brazil

**Comment by jeijeisan** [comment]
> URL: https://www.goodreads.com
> The site is not blocked, at least, here in Brazil

Oh! That's great!

**Comment by ilikestohack** [comment]
Anyone working on this currently? If not I might start working on it

**Comment by jeijeisan** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.goodreads.com%2Fabout%2Fpress&psig=AOvVaw3xwkY2BTz30ZOf6np5qo2N&ust=1603014913013000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJisv4Suu-wCFQAAAAAdAAAAABAD
