### ISSUE TITLE
Tidal Presence

### ISSUE THREAD

**Issue by ElmaCannon** [PreMiD/Presences#2252]
**Describe the Bug**

**Steps to Reproduce**

1. listen.tidal.com

**Expected Behavior**
 
When i play the music in tidal nothing is happend in de status of discord

**Screenshots**

![image](https://user-images.githubusercontent.com/63790220/94602419-1de71c00-0295-11eb-9310-da8cd4a26546.png)
![image](https://user-images.githubusercontent.com/63790220/94602448-293a4780-0295-11eb-9306-bb526440c135.png)

**Environment**

- OS:  /           Windows 10 Home
- Browser:  /         Edge
- Version: /           85.0.564.63 (64-bit)
  

**Additional context**

**Comment by Isa27-0** [comment]
Hi, your bug is already being solved (#2253)
