### ISSUE TITLE
EA Origin | origin.com

### ISSUE THREAD

**Issue by ghost** [PreMiD/Presences#2254]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**
web#0385

**What's the name of the service?** 
www.origin.com I EA Origin
**What should the Presence display?**
What page the user is on, time elapsed. Nothing too complicated.

**If possible, please provide a logo for the service (512x512 minimum)** 
<img src="https://i.imgur.com/M5aQ6b2.png" alt="presence" data-canonical-src="https://i.imgur.com/M5aQ6b2.png" style="max-width:100%;">

**Comment by CoopJax** [comment]
Is origin locked in any countries?

**Comment by ririxichan** [comment]
No.
