### ISSUE TITLE
Musify | Musify.co.uk

### ISSUE THREAD

**Issue by alfiefroggoman** [PreMiD/Presences#2266]
#**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** MrAlfieGamer#2202 

**What's the name of the service?** www.musify.co.uk |  Musify 

**What should the Presence display?**  Playing Musify, Display the logo and list that Musify is a free Spotify Visualiser,  Make it elapsed too.

**If possible, please provide a logo for the service (512x512 minimum)** https://imgur.com/a/QRGCJrf

**Comment by MicroBotCodes** [comment]
The logo can't be a banner.

**Comment by ririxichan** [comment]
@MicroBotCodes this is logo actually but not in 512x512 @alfiefroggoman please provide 512x512 logo

**Comment by MicroBotCodes** [comment]
Yes, I know.

**Comment by MicroBotCodes** [comment]
Also @alfiefroggoman I need to know what JS to fetch what is the valuable name of the song name.

**Comment by alfiefroggoman** [comment]
Hello,
I do NOT want a song they are listening to. Check the link for the new resized image.
https://imgur.com/a/lnqSnTJ

**Comment by alfiefroggoman** [comment]
I just want this to be a Playing Musify then the logo & elapsed.

[@MicroBotCodes @ririxichan ]

**Comment by MicroBotCodes** [comment]
You need it to say something there.

**Comment by alfiefroggoman** [comment]
Playing Musify and Listening to the Music.

[@MicroBotCodes]

**Comment by ririxichan** [comment]
Please update logo with better quality. Thanks.

**Comment by alfiefroggoman** [comment]
https://imgur.com/a/NIbrUiv
