### ISSUE TITLE
browsing crunchyroll 

### ISSUE THREAD

**Issue by Lukezinho** [PreMiD/Presences#2272]
**Describe the Bug**

**Steps to Reproduce**

1.
2.
3.

**Expected Behavior**

**Screenshots**

**Environment**

- OS: 
- Browser: 
- Version: 
  

**Additional context**

**Comment by Isa27-0** [comment]
What?

**Comment by Bas950** [comment]
Yea... info? xD

**Comment by Isa27-0** [comment]
Please fill in everything you have submitted (Now with a new Issue). So, your bug report is valid
@Lukezinho
