### ISSUE TITLE
Tranimeizle | www.tranimeizle.net

### ISSUE THREAD

**Issue by tranimeizle** [PreMiD/Presences#2273]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username? kira#9507

**What's the name of the service? www.tranimeizle.net | Tranimeizle

**What should the Presence display Tranimeizle is a site where you can watch Turkish subtitle anime & read manga.

**If possible, please provide a logo for the service (512x512 minimum) 
![Untitled-2](https://user-images.githubusercontent.com/72321988/95002514-a3dccd00-05dd-11eb-9faa-351a768d63a6.png)

**Comment by Isa27-0** [comment]
"What should the Presence display" It was to say what the presence will show, not about the site

And I verified that the site was registered in August, I recommend waiting until October 14 to complete 2 months
![image](https://user-images.githubusercontent.com/68751594/95014199-bb3aab00-061b-11eb-84a2-b231e4c76f8e.png)

**Comment by tranimeizle** [comment]
"What should the Presence display" => Tranimeizle, türkçe altyazılı anime izleyebileceğiniz bir site.

aitr.tv=>turkceanimeizle.com=>tranimeizle.com=>tranimeizle.net 301 redirect stuation. Site active more than 5 years.

**Comment by Isa27-0** [comment]
Oh, ok
