### ISSUE TITLE
nhentai not working 

### ISSUE THREAD

**Issue by anujbhaktashrestha** [PreMiD/Presences#2280]
**Describe the Bug**

**Steps to Reproduce**

1.
2.
3.

**Expected Behavior**

**Screenshots**

**Environment**

- OS: 
- Browser: 
- Version: 
  

**Additional context**

**Comment by ririxichan** [comment]
Please edit issue description with all details.

**Comment by Isa27-0** [comment]
Please fill in everything you have submitted. So, your bug report is valid
@anujbhaktashrestha

**Comment by Isa27-0** [comment]
~~He didn't reply 2 days ago, better to close~~

**Comment by fr0r** [comment]
nhentai presence is working as usual

![image](https://user-images.githubusercontent.com/34042085/95418988-ffc19180-090e-11eb-8801-658df14ec205.png)
