### ISSUE TITLE
Deezer.com

### ISSUE THREAD

**Issue by CloudMaker97** [PreMiD/Presences#23]
**What's the name of the service?**
Deezer | https://www.deezer.com

**What should the Presence display?**
Title of current track, album (interpret)
Remaining time of track

**Why do you want support for this service?**
Deezer is used often in europe and is one of my favorite music streaming provider. It have a bigger libary then spotify.

**Are you able to provide an image for the service? (512x512 minimum)**
https://static.mydealz.de/live/threads/thread_full_screen/default/1208758_1.jpg

**Comment by frozaum** [comment]
k it's done
can we close this?
