### ISSUE TITLE
Picrew

### ISSUE THREAD

**Issue by Caleri** [PreMiD/Presences#2301]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Caleri#0006

**What's the name of the service?**  Picrew | https://picrew.me/
**What should the Presence display?** A site where you can create avatars

**If possible, please provide a logo for the service (512x512 minimum)**  https://cm1.narvii.com/7556/8e5adc66245fd36c643040de630bac280aaa21bb_00.jpg

**Comment by Isa27-0** [comment]
"What should the Presence display" It was to say what the presence will show, not about the site 
@Caleri

**Comment by Caleri** [comment]
Ah okay.. ''Using picrew'' its good

**Comment by Slowftw** [comment]
I'm making
