### ISSUE TITLE
[Presence | Bug] Apple Music

### ISSUE THREAD

**Issue by magumboi** [PreMiD/Presences#2302]
**Describe the Bug**
Apple Music presence is unable to load metadata when a playlist from the "Listen Now" tab plays. 
Console shows the following error: 
`TypeError: Cannot read property 'textContent' of null`

**Steps to Reproduce**
1. Go to music.apple.com
2. Go to the "Listen Now" tab from the left menu.
3. Click on any playlist within.

**Expected Behavior**
Display status on my discord profile the song I'm listening to.

"Listen now" tab playlists example:
![Screenshot_1](https://user-images.githubusercontent.com/27692047/95666246-716f2a80-0b1d-11eb-882a-ed141e153093.png)

**Environment**

- OS: Windows 10
- Browser: Chromium
- Version: 85.0.4183.121 (64-bit)

**Comment by ririxidev** [comment]
@N0chteil could you look into it?

**Comment by N0chteil** [comment]
yes

**Comment by DarkVillager** [comment]
Resolved.
![image](https://user-images.githubusercontent.com/42322979/128700462-03638bcf-bb1c-451a-9e80-f92013d0b533.png)
Environment

OS: Windows 10
Browser: Chrome
Version: 92.0.4515.131 (64-bit)

**Comment by EncryptedDev** [comment]
Cannot reproduce, likely to of been fixed over the last year. Reopen if the issue is still apparent
