### ISSUE TITLE
KickAssAnime Request [KAA]

### ISSUE THREAD

**Issue by huh-code** [PreMiD/Presences#2303]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
KickAssAnime (https://www1.kickassanime.rs/)

**What should the Presence display?** 
The name of the status should be 'KickAssAnime'
The first line of text should display 'Browsing...' and the Anime name once it starts playing
The second line of text should display the episode number
Once a video is playing, it should have the countdown displayed
Pause and play feature, basically all the same as other anime streaming service presences.

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/65111632/95666535-4f6dba80-0ba6-11eb-8583-e3a2074590e9.png)

**Comment by Isa27-0** [comment]
It has already been requested (#834)

**Comment by ririxichan** [comment]
Already suggested (#1885)
