### ISSUE TITLE
[Zoom] Presence Request

### ISSUE THREAD

**Issue by DevNoahh2** [PreMiD/Presences#2306]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**
`Noahh#0001` 

**What's the name of the service?** 
`Zoom [Web Version]`

**What should the Presence display?** 
`If they are in a meeting or not, what the meeting title is, how many people are in the meeting.`

**If possible, please provide a logo for the service (512x512 minimum)** 
`https://i.imgur.com/R4guHwc.png`

**Comment by MrBartusek** [comment]
I will work on that
