### ISSUE TITLE
RideSims | ridesims.com

### ISSUE THREAD

**Issue by Qualter** [PreMiD/Presences#2307]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? 
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

Discord:
QualterZam#7909
Website + Name:
www.ridesims.com Ride Sims
What should the Presence display?
What simulator people are using (There are different ride simulators, it could show what sim they're using and maybe their score). If you want to voice call let me know :)

Logo:
https://imgur.com/a/7WlQ7RV

**Comment by ririxichan** [comment]
@Qualter please update logo to 512x512 actual one is 480x480
