### ISSUE TITLE
[Feature Request] Show "Playing [site]", but not show what I'm doing on this site

### ISSUE THREAD

**Issue by vitormathews** [PreMiD/Presences#2310]
For instance:
- I would like to show "Playing YouTube" in my Discord status, but not reveal what video I'm watching;
- I would like to show "Playing Twitter", but not show what profile I'm looking at.

This option is already availabe for Twitch and Soundcloud:
![image](https://user-images.githubusercontent.com/51209382/95690264-c332b600-0bec-11eb-902d-8567dec3761f.png)

**Comment by Bas950** [comment]
The developers of this presence may add this themselves, or if you know to code yourself then you can add this right now!
But since developing presences is voluntary this may take song time to be supported.

I might add it when we add support for Presence Language Settings.

**Comment by vitormathews** [comment]
> The developers of this presence may add this themselves, or if you know to code yourself then you can add this right now!
> But since developing presences is voluntary this may take song time to be supported.
> 
> I might add it when we add support for Presence Language Settings.

I don't know how to code, unfortunately.
Where can I find who's the presence dev?

**Comment by Bas950** [comment]
> > The developers of this presence may add this themselves, or if you know to code yourself then you can add this right now!
> > But since developing presences is voluntary this may take song time to be supported.
> > I might add it when we add support for Presence Language Settings.
> 
> I don't know how to code, unfortunately.
> Where can I find who's the presence dev?

![image](https://user-images.githubusercontent.com/34792838/95695478-5c86ba00-0c37-11eb-9a48-77c7baec7727.png)
When you click on their name, it will take you to their profile, which shows their Discord name with # and in the URL is their Discord ID.

**Comment by ririxidev** [comment]
It's added :3
