### ISSUE TITLE
ESPN | espn.com

### ISSUE THREAD

**Issue by vitormathews** [PreMiD/Presences#2311]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Vitor#5695

**What's the name of the service?** 
ESPN | www.espn.com

**What should the Presence display?** 
What page the user is on; current event the user is watching on WatchESPN (https://espn.com/watch)

**If possible, please provide a logo for the service (512x512 minimum)** 
![espn-logo-0 copy](https://user-images.githubusercontent.com/51209382/95691502-fcbbef00-0bf5-11eb-9504-c56372d132a1.png)

**Comment by ririxichan** [comment]
Upload logo and it needs more info what presence should display

**Comment by vitormathews** [comment]
> Upload logo and it needs more info what presence should display

done

**Comment by ririxichan** [comment]
Also this is paid service so 
![image](https://user-images.githubusercontent.com/9348108/95882813-6d8c1400-0d7a-11eb-8e0c-144f8dc67d2e.png)
please add it to description too 
![image](https://user-images.githubusercontent.com/9348108/95882831-741a8b80-0d7a-11eb-8b1f-26963e6a8176.png)
