### ISSUE TITLE
GaiaOnline | gaiaonline.com

### ISSUE THREAD

**Issue by jeijeisan** [PreMiD/Presences#2329]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 🎃 j e i j e i s a n 🎃#5105

**What's the name of the service?**  Gaia Online | https://www.gaiaonline.com

**What should the Presence display?**  Playing Gaia Online and the rest is up to your hands I know you guys are good at this

**If possible, please provide a logo for the service (512x512 minimum)** 
![808075_logo_512x512](https://user-images.githubusercontent.com/72079584/95954459-ed26eb00-0e2d-11eb-92ce-ee4a51cbc560.png)

**Comment by Isa27-0** [comment]
URL: https://www.gaiaonline.com

**Comment by jeijeisan** [comment]
Gaia Online Logo and it should say "Playing Gaia Online"on Discord is fine. ^^!! But it would be perfect if you will add the Games subs. I don't know how you will do it, it might be a lot of work for you. It's fine if you don't. We just its own presence ^^!! Thank you in advance.
![image](https://user-images.githubusercontent.com/72079584/95987564-2ffeb800-0e5a-11eb-83a5-7751b06d2f6f.png)

**Comment by Isa27-0** [comment]
> Gaia Online Logo and it should say "Playing Gaia Online"on Discord is fine. ^^!! But it would be perfect if you will add the Games subs. I don't know how you will do it, it might be a lot of work for you. It's fine if you don't. We just want its own presence ^^!! Thank you in advance.
> ![image](https://user-images.githubusercontent.com/72079584/95987564-2ffeb800-0e5a-11eb-83a5-7751b06d2f6f.png)

Eh, unfortunately I'm not a developer, I just help and check the sites. Maybe it may take a while for someone to create it...
