### ISSUE TITLE
Q-Dance Radio

### ISSUE THREAD

**Issue by Dams678** [PreMiD/Presences#233]
**What's the name of the service?**
https://www.q-dance.com/ | Q-Dance Radio

**What should the Presence display?**
Informations about the current music  , time remaining 

**Why do you want support for this service?**
I love this radio the style of music and I listen to it every day

**Are you able to provide an image for the service? (512x512 minimum)**
https://image.noelshack.com/fichiers/2019/36/5/1567724811-3tbp-oum-400x400.jpg
https://image.noelshack.com/fichiers/2019/36/5/1567725065-q-dance-logo.jpg

**Comment by Timeraa** [comment]
Done
