### ISSUE TITLE
presence request

### ISSUE THREAD

**Issue by wfxjz** [PreMiD/Presences#2336]
https://taganime.com/ 
https://v1.taganime.com/
https://v2.taganime.com/
https://kiss.taganime.com/

**Comment by ririxichan** [comment]
Follow template once again.

**Comment by Isa27-0** [comment]
@wfxjz 
Please use the template (https://github.com/PreMiD/Presences/issues/new?template=service_request.md) to suggest presence. Your orders are invalid and the "Issue" (beyond #2332) can be closed
