### ISSUE TITLE
CS-Online | cs-online.club

### ISSUE THREAD

**Issue by wfxjz** [PreMiD/Presences#2338]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Wayne#9958

**What's the name of the service?**  https://cs-online.club/ | CS-ONLINE.CLUB

**What should the Presence display?**  Playing, Maps, In-Lobby Room , Mode

**If possible, please provide a logo for the service (512x512 minimum)**  
![images](https://user-images.githubusercontent.com/65273502/96140961-1bdab980-0f33-11eb-845c-217a99c95d81.png)

**Comment by ririxichan** [comment]
Could you edit request with your discord tag? Thanks.
