### ISSUE TITLE
GalaxyBot | galaxybot.de

### ISSUE THREAD

**Issue by Phyroks** [PreMiD/Presences#2346]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Phyroks#0504
**What's the name of the service?** 
https://galaxybot.de | GalaxyBot Dashboard
**What should the Presence display?** 
What you edit in the dashboard
**If possible, please provide a logo for the service (512x512 minimum)** 
https://cdn.galaxybot.de/branding/logo/gb_icon_c_big.png

**Comment by Isa27-0** [comment]
Logo:
![gb_icon_c_big](https://user-images.githubusercontent.com/68751594/96369616-80636780-1131-11eb-86f1-c1ff0f521c2a.png)
URL: https://galaxybot.de ~~And I already realized that you are the creator of the bot~~

**Comment by ririxichan** [comment]
@Isa27-0 .de domains doesn't have whois records for no reason. But yeah site has 2 months as i see updating date.

**Comment by Isa27-0** [comment]
> .de domains doesn't have whois records for no reason. But yeah site has 2 months as i see updating date.

Huh, worse, just a whois site showed me the update date... Thanks anyway :)
