### ISSUE TITLE
AnimeFenix | animefenix.com

### ISSUE THREAD

**Issue by FALISO** [PreMiD/Presences#2349]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
PAN#7077
**What's the name of the service?** 
https://www.animefenix.com
**What should the Presence display?** 
basically almost the same as animeflv
**If possible, please provide a logo for the service (512x512 minimum)** 
![AveFenix](https://user-images.githubusercontent.com/73078072/96377710-c1717100-115d-11eb-86be-90123d598942.png)

**Comment by ririxichan** [comment]
Change title to site url.

**Comment by geenva** [comment]
please use the boxes correctly

**Comment by Isa27-0** [comment]
@FALISO ^
