### ISSUE TITLE
Twitch presence doesn't works

### ISSUE THREAD

**Issue by CyberByte-js** [PreMiD/Presences#2359]
**Describe the Bug**
Twitch.tv presence don't work.

**Steps to Reproduce**
1. Install Discord and PreMid
2. Open a Twitch stream
3. Go to Discord and see the presence not working

**Expected Behavior**
Show the Twitch presence in Discord status

**Screenshots**
![image](https://user-images.githubusercontent.com/71409005/96513376-6c565d80-1238-11eb-9fa3-d3463f988ba9.png)
![image](https://user-images.githubusercontent.com/71409005/96516545-bc83ee80-123d-11eb-900f-d53da1061976.png)

**Environment**
- OS: Windows 10
- Browser: Opera GX
- Version: PreMid: 2.1.4 Opera: LVL2 (core: 71.0.3770.234) Windows: 2004

**Additional context**
It is happening since the first time I used PreMid

**Comment by ririxichan** [comment]
https://docs.premid.app/presencesettings.gif do this and close this issue.
