### ISSUE TITLE
SoundCloud Presence says "Playing a Game" instead of "Listening to"

### ISSUE THREAD

**Issue by supremethememe** [PreMiD/Presences#2360]
**Describe the Bug**
SoundCloud status says "Playing a game" instead of "Listening to"
**Steps to Reproduce**
1. Listen to a song on SoundCloud
2.
3.

**Expected Behavior**
Say Listening to

**Screenshots**
![unknown](https://user-images.githubusercontent.com/39014019/96525907-33bf7f80-124a-11eb-8a6a-69d7b819fe03.png)

**Environment**

- OS: Windows 10
- Browser: Brave (Chromium)
- Version: 86.0.4240.99

**Comment by ririxichan** [comment]
It cant be changed. It is restricted by Rich Presence https://discord.com/rich-presence Please close it and next time talk to us on our discord https://discord.premid.app to ask for these things.
