### ISSUE TITLE
Wrong channel name - Youtube presence

### ISSUE THREAD

**Issue by CyberByte-js** [PreMiD/Presences#2365]
**Describe the Bug**
Showing the wrong channel name in the presence.

**Steps to Reproduce**
1. Install PreMid
2. Turn on the Youtube presence
3. Get into a video and then go to another(not 100% chance to the bug happen)

**Expected Behavior**
Show the right name of the channel.

**Screenshots**
![image](https://user-images.githubusercontent.com/71409005/96620792-484d5780-12de-11eb-87b8-d678c22b9cdf.png)
![image](https://user-images.githubusercontent.com/71409005/96620874-5d29eb00-12de-11eb-99d4-1c268432e00b.png)

**Environment**

- OS: Windows 10
- Browser: Opera GX
- Version: PreMid: 2.1.4 Opera: LVL2 (core: 71.0.3770.234) Windows: 64-bit

**Additional context**
I think it happened when I switched from a video to another.

**Comment by ririxidev** [comment]
Should be fixed 🤷
