### ISSUE TITLE
[Presence | Bug] TuMangaOnline

### ISSUE THREAD

**Issue by Chocolateunu** [PreMiD/Presences#2366]
**Describe the Bug**
The presence of "TuMangaOnline" does not seem to work, since it has a new link. Now it is called "lectortmo"

**Steps to Reproduce**
1. Get https://premid.app/store/presences/TuMangaOnline
2. Go to https://tmofans.com
3. It will notice that the page does not exist and will redirect it to the new page, which is https://lectortmo.com

As Premid detects the tmofans link, it does not recognize the new link

**Expected Behavior**
I hope the presence works as it should

**Environment**
- OS: Windows 10
- Browser: Google Chrome
- Version: Versión 86.0.4240.75 (Build oficial) (64 bits)
  
**Additional context**
I suggest checking the link of the page from time to time, since on certain occasions they can change the link (as has happened in this case)

**Comment by ririxidev** [comment]
Should be fixed in #3591
