### ISSUE TITLE
Service request - PotPlayer

### ISSUE THREAD

**Issue by yannawrgit** [PreMiD/Presences#2374]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Yanna#0551

**What's the name of the service?** PotPlayer

**What should the Presence display?** Playing PotPlayer
Watching X

**If possible, please provide a logo for the service (512x512 minimum)** 

PS* The presence should work similar to the VLC presence
![PotPlayer_logo_(2017)](https://user-images.githubusercontent.com/73317883/96938655-4f709300-14a1-11eb-8493-66a299209b40.png)

**Comment by Isa27-0** [comment]
But does the application have anything like localhost for example? Like, VLC and Kodi have. Simplifying, have some kind of connection?

**Comment by ririxichan** [comment]
I don't think it has API localhost. For now I will close it, but if you have some proof that i'm wrong post it there.

**Comment by Isa27-0** [comment]
> I don't think it has localhost site. For now I will close it, but if you have some proof that i'm wrong post it there.

@ririxidev 
Today I went to check on this part, and apparently it doesn't have a localhost site. The only way to add presence is to create an extension for PotPlayer in `.as` (AngelScript) which communicates with the application and the PreMiD extension, and put in the directory (Windows): `C:\Program Files\DAUM\PotPlayer\Extension\Media\UrlList`

Ex: YouTube
![image](https://user-images.githubusercontent.com/68751594/123961672-00132880-d987-11eb-8a7d-84acd61d7f6e.png)

Extension `.as` file:
![image](https://user-images.githubusercontent.com/68751594/123962666-153c8700-d988-11eb-9fbc-6eed8b5d3031.png)

**Comment by ririxidev** [comment]
Meh :/
