### ISSUE TITLE
Emby | emby.media

### ISSUE THREAD

**Issue by 123321mario** [PreMiD/Presences#238]
**What's the name of the service?**
Ex. http://emby.media | Emby

**What should the Presence display?**
Informations about the current media for example if it's a TV show, write the show name on the first line, then the episode count on the second and the remaining time on the last one.

**Why do you want support for this service?**
It's one of the best media servers and the only free way to watch content is with the browser so I thought about adding premid to it.

**Are you able to provide an image for the service? (512x512 minimum)**

https://emby.media/notificationicon.png

Important note : it's a media server that you need to host so the URL is not emby.media, it's your IP (local or global) or a domain name if you have one.

Thanks

**Comment by OfficialCRUGG** [comment]
Currently, something like this with self hosted services is not possible, as every presence needs to have a fixed domain. Maybe @Timeraa can add some functionality for this in the future.

**Comment by alexbcberio** [comment]
I've started implementing this presence for the neighbour Jellyfin (a fork of Emby), currently is on a pull request but it could easyily be ported from Jellyfin to Emby. 

The version 1.0 works for movies and tv show libraries.

**Comment by Bas950** [comment]
https://premid.app/store/presences/Emby
