### ISSUE TITLE
Google Podcasts Support

### ISSUE THREAD

**Issue by GCS7** [PreMiD/Presences#2380]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** https://podcasts.google.com "Google Podcasts"

**What should the Presence display?** What podcast are you listening.

**If possible, please provide a logo for the service (512x512 minimum)** https://imgur.com/a/fUncTQs

**Comment by Isa27-0** [comment]
It has already been requested (#2141)
