### ISSUE TITLE
Just Dance Skylight | justdanceskylight.tk

### ISSUE THREAD

**Issue by heyimyunyl** [PreMiD/Presences#2383]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
jennie#3775

**What's the name of the service?** 
justdanceskylight.tk | Just Dance Skylight

**What should the Presence display?** 
When the user is scrolling through the menu, looking for which song to select and dance, it should show "Scrolling through songlist..." and whenever a user starts a song/dance in-game, I think the best way to show what song they are playing would be getting the current' songs m3u8 URL or else. It should show what song the player is dancing to with title, artist and the song's image as the logo. The song's image can be get through the menu.

**If possible, please provide a logo for the service (512x512 minimum)** 
![512](https://user-images.githubusercontent.com/32681723/97107804-7d8ce780-16da-11eb-9e04-16d895f9c527.jpg)

**Comment by heyimyunyl** [comment]
If there is anyone that is interested into know how the API of this fangame works, I can let you know in Discord.

**Comment by ririxichan** [comment]
Free domain, we are not accepting these.
