### ISSUE TITLE
popsauce.sparklinlabs.com - Pop Sauce (Game)

### ISSUE THREAD

**Issue by Dams678** [PreMiD/Presences#239]
**What's the name of the service?**
http://popsauce.sparklinlabs.com/ | PopSauce
**What should the Presence display?**
Informations about the current channel name like (Playing - "Channel Name" + elapsed time 
Name of the site "Sparklin Labs"

**Why do you want support for this service?**
It's a really cool game easy to understand and I play it often

**Are you able to provide an image for the service? (512x512 minimum)**
https://image.noelshack.com/fichiers/2019/36/6/1567871543-popsauce2.png

**Comment by MrVoltox30** [comment]
good idea !

**Comment by frozaum** [comment]
Added #254
