### ISSUE TITLE
Twitch.tv not showing the presence.

### ISSUE THREAD

**Issue by iiLeafy** [PreMiD/Presences#2402]
**Describe the bug**
Twitch.tv presence not working.

**To Reproduce**
1. Install Twitch.tv presence
2. Go to twitch.tv
3. Check discord and see you have no presence/status

**Expected behavior**
I expected it to show the presence in discord.

**Screenshots**
None, it's self-explanatory.

**Desktop (please complete the following information):**
 - OS: Laptop Windows 10
 - Browser - Brave
 - Version - PremID - 2.1.4, Brave - 1.15.75 Chromium: 86.0.4240.99

**Additional context**
I have it enabled, still doesn't work, re-enabled it also doesn't work my friend also has this problem.

**Comment by ririxichan** [comment]
Check things that guys above said ^
