### ISSUE TITLE
Pylon | pylon.bot

### ISSUE THREAD

**Issue by PhantomNimbi** [PreMiD/Presences#2403]
**Prerequisites and essential questions**
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**
Nimbi#4961
**What's the name of the service?** 
https://pylon.bot | Pylon

**What should the Presence display?**
Website Name [e.g. Pylon]
Current Activity [e.g. Editing filename.ts]

**If possible, please provide a logo for the service (512x512 minimum)** 
![56440847](https://user-images.githubusercontent.com/17615050/97372860-d2af3180-1871-11eb-8ede-539edb03ef96.png)

**Comment by Snazzah** [comment]
[This already exists](https://premid.app/store/presences/Pylon)

**Comment by ririxidev** [comment]
oof it didn't show for me before kek
