### ISSUE TITLE
Vimeo.com

### ISSUE THREAD

**Issue by TheLastZombie** [PreMiD/Presences#241]
**What's the name of the service?**
vimeo.com | Vimeo

**What should the Presence display?**
Title and uploader of the video with the time left. Similar to, for example, YouTube.

**Why do you want support for this service?**
Vimeo is a pretty well-known site similar to YouTube and currently sits at [#154 on the worldwide Alexa ranking](https://www.alexa.com/siteinfo/vimeo.com).

**Are you able to provide an image for the service? (512x512 minimum)**
https://press.vimeo.com/clients/vimeo/vimeo_icons-3.zip

**Comment by frozaum** [comment]
Added #253
