### ISSUE TITLE
Wcostream | www.wcostream.com

### ISSUE THREAD

**Issue by ShadowLegendCZ** [PreMiD/Presences#2414]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** *Furuhashi Fumino#8496* / *ID : 428984613935775765*

**What's the name of the service?** https://www.wcostream.com/ | Wcostream

**What should the Presence display?** *Anime you're watching, episode, time left, etc.*

**If possible, please provide a logo for the service (512x512 minimum)** i couldn't find the size, you're looking for, but i got an icon from their webpage.
![Here](https://user-images.githubusercontent.com/50084293/97808969-50a47b80-1c6a-11eb-8744-1dcec923a5fd.gif)

**Comment by ShadowLegendCZ** [comment]
Normally, i would make it myself, but i don't know Typescript.

**Comment by ririxichan** [comment]
You can still resize this image, so please do it.

**Comment by ShadowLegendCZ** [comment]
I resized the image, here it is .
![wcostream presence](https://user-images.githubusercontent.com/50084293/97852406-fd2c3f00-1cf6-11eb-90bf-49ba92c7e179.png)

**Comment by ShadowLegendCZ** [comment]
I resized the image to 512x512 as you wanted :D
![wcostream presence](https://user-images.githubusercontent.com/50084293/97852634-47152500-1cf7-11eb-9159-6cef851c5c85.png)

**Comment by ShadowLegendCZ** [comment]
Just wanted to ask, is this request accepted ? Like, if it's going to be developed.

**Comment by ririxichan** [comment]
![](https://i.ririxi.dev/b9kCJ2sgd)

**Comment by ShadowLegendCZ** [comment]
I know, I know, just wanna know if it's valid
