### ISSUE TITLE
Hulu | www.hulu.com

### ISSUE THREAD

**Issue by icantstopme** [PreMiD/Presences#2425]
When I open Hulu it works just fine. It shows that I'm looking through categories and if I click on a movie to see the description it'll also show it. The problem starts when I actually watch a movie/show. Sometimes it shows what I'm watching but the majority of the time it just disappears completely. The extension only shows certain shows/movies. If I quit the movie I'm watching to go back to the menu (when it doesn't show the movie) then the extension won't show that I'm back in the menu and it won't work again until I restart my browser. The same thing happens again if restart. The other extensions work fine, it's just Hulu.

- OS: Windows 10
- Browser: Chrome
- Version:  86.0.4240.111 (64-bit)

**Comment by tedahn** [comment]
I can't seem to recreate this problem.
Anyone else having this issue?

**Comment by Kaisarion** [comment]
I think this issue can be closed. I've tested it on over 100 movies and I'm getting nothing lol
