### ISSUE TITLE
[Presence | Feature Request] NicoVideo

### ISSUE THREAD

**Issue by Slasar41** [PreMiD/Presences#2426]
**Is your feature request related to a problem? Please describe.**
While https://www.nicovideo.jp is already supported, https://sp.nicovideo.jp is not supported.

**Describe the solution you'd like**
Add https://sp.nicovideo.jp to niconico presence.
Accessing from this URL, you watch the video full screen with a flying comment text.

**Comment by ririxidev** [comment]
@eai04191
