### ISSUE TITLE
LinkedIn | linkedin.com

### ISSUE THREAD

**Issue by steeveeMS** [PreMiD/Presences#2431]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** steevee#1644

**What's the name of the service?** https://linkedin.com | LinkedIn

**What should the Presence display?** Browsing LinkedIn or learning on LinkedIn Learn

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/73078498/98100773-a149ed80-1e91-11eb-8bbb-ceee1e30b0f6.png)

**Comment by ririxichan** [comment]
Please upload logo :)

**Comment by steeveeMS** [comment]
> Please upload logo :)

sorry missed that. added the logo now 👍🏻

**Comment by ririxidev** [comment]
merged #2727
