### ISSUE TITLE
Pluralsight | www.pluralsight.com

### ISSUE THREAD

**Issue by steeveeMS** [PreMiD/Presences#2432]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** steevee#1644

**What's the name of the service?** https://www.pluralsight.com | Pluralsight

**What should the Presence display?** Learning on Pluralsight or whichever specific course you're viewing...

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/73078498/98100483-326c9480-1e91-11eb-871e-9ba06d41d7c7.png)

**Comment by ElryDev** [comment]
ill second this but i tryed to make it

**Comment by ElryDev** [comment]
Also here are far better logos without an fake transparancy 
![image](https://user-images.githubusercontent.com/74990141/100151272-42c8cb80-2ea1-11eb-9bd2-9358f98ac7dd.png)
And the banner
![image](https://user-images.githubusercontent.com/74990141/100151301-48beac80-2ea1-11eb-80d2-2faebe9af3f8.png)
