### ISSUE TITLE
ririxi TODO list

### ISSUE THREAD

**Issue by ririxidev** [PreMiD/Presences#2436]
**NOTE:** If you want me to do presence, feel free to suggest there with ID of service request (issue).
Presences to do:
  - [x] cda.pl (#1661)
  - [ ] Origin (#2254)
  - [ ] Gerforce NOW (#1982)

Soon I will do more presences.

**Comment by CoopJax** [comment]
I might work on the Origin presence later, although this is fine

**Comment by Chocolateunu** [comment]
May I suggest you make my request? #2400

**Comment by ririxidev** [comment]
For now I don't have time to do these stuff, closing till I will have some free time. @Chocolateunu sure I will

**Comment by Chocolateunu** [comment]
> For now I don't have time to do these stuff, closing till I will have some free time. @Chocolateunu sure I will

Thanks !!!
