### ISSUE TITLE
s.to - SerienStream.to

### ISSUE THREAD

**Issue by MauriceX24** [PreMiD/Presences#244]
**What's the name of the service?**
www.s.to | S.TO

**What should the Presence display?**
Informations about the current series and episode

**Why do you want support for this service?**
This site deserves to be seen. They are the best for streaming series and the fastest service

**Are you able to provide an image for the service? (512x512 minimum)**
![sto](https://user-images.githubusercontent.com/35397688/64486231-88609080-d22a-11e9-9219-948c7fc82e05.png)

**Comment by frozaum** [comment]
done #311
