### ISSUE TITLE
[Repository | Enhancement] Automate the presence requests review process

### ISSUE THREAD

**Issue by MrBartusek** [PreMiD/Presences#2448]
### Motivation
In Presences repo revivers follow a standard procedure of reviving a presence request:
- Is the schema of issues proper?
- Are all checkboxes valid? (is website really two months old etc.)
- Is the logo attached and really 512x512?
- If everything is valid, add "presence requests" label

### The automation of the current process

- `Is it a popular site?` Can be removed from a template and checked by the bot using any website traffic API (like [similarweb](https://www.similarweb.com/corp/developer/) one). The bot then give labels ![popular](https://img.shields.io/badge/popular-blueviolet) and ![unpopular](https://img.shields.io/badge/unpopular-orange)
- `Is the website older than two months?` Can be removed from a template and checked by the bot using any whois API. The bot then shall close requests with websites not older than two months
- ` Is the site locked to a specific country/region?` i am not sure if there are *check websites from multiple locations* API. Needs further elaboration but here bot could assing ![region-restricted](https://img.shields.io/badge/region%20restricted-yellow) or close not reachable ones. Might be not possible to do, then just leave that box and assign label depending on it
- `Does the website feature NSFW content?` no way to check it I guess, leave the box and add ![nsfw](https://img.shields.io/badge/nsfw-black) if marked
- ` Is the site a paid service?` again, no way ![paid](https://img.shields.io/badge/paid%20service-brown) if marked
- `Are you a donator/patron?` not sure if can be checked, if not ![paid](https://img.shields.io/badge/donator%20priority-yellow) if marked
-  `Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?` if not checked, remind author about that
-  `What's your Discord username? ` is it provided and looks like discord username? `something#xxxx`
-  `What's the name of the service?` is the name and URL provided? needed for a couple of above steps
-  `If possible, please provide a logo for the service ` check if there is a logo and if it is at least 512x152px

### Final Thoughts
I would love to work on that, I just need to confirm that it is worth the hustle!

**Comment by ririxichan** [comment]
Thanks for suggestion. We will provide this automatic process at our v3 release. Leaving it as open still.
