### ISSUE TITLE
Horizon GO | horizon.tv

### ISSUE THREAD

**Issue by Flowyan** [PreMiD/Presences#245]
**What's the name of the service?**
Ex. https://www.horizon.tv | Horizon GO

**What should the Presence display?**
Informations about the current tv channel im watching

**Why do you want support for this service?**
i feel like some people would want this

**Are you able to provide an image for the service? (512x512 minimum)**
https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/ad/cf/80/adcf8082-c6fb-4ec3-ac9c-961af34aa002/source/512x512bb.jpg

**Comment by hamsterofficial** [comment]
I will do it tommorow, bc this i have access.

**Comment by hamsterofficial** [comment]
can be closed bc merge :^)
