### ISSUE TITLE
TheWatchCartoonOnline | thewatchcartoononline.tv

### ISSUE THREAD

**Issue by Staticmau5** [PreMiD/Presences#2454]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Tarrabyte#2999
**What's the name of the service?** 
https://www.thewatchcartoononline.tv/
**What should the Presence display?** 
I guess their logo. 
**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by ririxichan** [comment]
Give more info what presence should display and upload logo
