### ISSUE TITLE
[Presence Request] Plex

### ISSUE THREAD

**Issue by Flowyan** [PreMiD/Presences#246]
**What's the name of the service?**
Ex. https://app.plex.tv | Plex

**What should the Presence display?**
Informations about the current movie, tv show that im watching

**Why do you want support for this service?**
I think a lot of people use plex and would want to show what they are watching on discord.

**Are you able to provide an image for the service? (512x512 minimum)**
https://pbs.twimg.com/profile_images/877289188747427840/LUfuf8ow.jpg

**Comment by frozaum** [comment]
duplicated #18
