### ISSUE TITLE
Google Play Movies & TV presence

### ISSUE THREAD

**Issue by Billie5381** [PreMiD/Presences#2468]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Billie#5381

**What's the name of the service?**  https://play.google.com/store/movies | Google Play Movies & Tv

**What should the Presence display?** Same thing as all the Netflix, Youtube and CartoonCrazy :   _Google Play Movies & TV_ (As app title like Netflix) under : _Title of movie_ and under that the time remaining for this movie _02 h 20 min 25 s restantes_

**If possible, please provide a logo for the service (512x512 minimum)** https://ibb.co/tmbM9h4

**Comment by Isa27-0** [comment]
That would fit the presence I asked for, as the Google Play Store has Play Movies too (#2164)

**Comment by MaXfAa** [comment]
Google abandons Play Movies & TV in favor of YouTube (and its catalog of films).
