### ISSUE TITLE
Own WordPress installation (WordPress plugin)

### ISSUE THREAD

**Issue by GreepTheSheep** [PreMiD/Presences#2470]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Greep#3022

**What's the name of the service?** 
Own WordPress installation.

**What should the Presence display?** 
The page name where we are

**If possible, please provide a logo for the service (512x512 minimum)** 

https://media.wordpresstraining.com/wp-content/uploads/2013/07/wordpress-logo.png

**Note:**
I think we can use custom Discord presence if we input our own ID from the Discord dev apps. A Wordpress plugin should be useful for that, if no ID is set, we can use the default WordPress presence

**Comment by ririxichan** [comment]
Actually, If I got what you want is just setting up wordpress blog url. But unfortunately we don't support it. Here is suggestion that someone did and you just need to wait till it it will be added https://github.com/PreMiD/Extension/issues/29. Or if someone will just do support for every subdomain from wordpress but not everyone has wordpress hosted on their site.
