### ISSUE TITLE
https://soap2day.to

### ISSUE THREAD

**Issue by Mev25** [PreMiD/Presences#2476]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** ꒰мєν꒱｡◍🍰メヴ#1824 

**What's the name of the service?**  https://soap2day.to

**What should the Presence display?** The website logo plus what you are watching atm

**If possible, please provide a logo for the service (512x512 minimum)** https://soap2day.to/title.png

**Comment by ririxichan** [comment]
Already suggested #2327
