### ISSUE TITLE
repl.it | https://repl.it

### ISSUE THREAD

**Issue by isuckatprogram** [PreMiD/Presences#2485]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
repl.it | Repl.it
**What should the Presence display?** 
What the user is doing, (creating a repl, coding in a repl, on the talk page, browsing a post on the talk page)

**If possible, please provide a logo for the service (512x512 minimum)** 
![logo](https://repl.it/public/images/favicon.ico)

**Comment by ririxidev** [comment]
Already added, but it is broken for now.

**Comment by isuckatprogram** [comment]
can someone fix it pls? 👀
