### ISSUE TITLE
Chrome Web Store | chrome.google.com/webstore

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#2487]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
MaXfAa#1068

**What's the name of the service?** 
Chrome Web Store | https://chrome.google.com/webstore/

**What should the Presence display?** 
First line: Chrome Web Store
Second line: The status (for example: "seeks" or "in the productivity category")
Third line: The name of the extension / topic
(Regarding the logo: Large the Chrome Web Store logo and small at the bottom right: either a puzzle for an extension, or a brush for a theme.
See: https://zupimages.net/up/20/47/c72a.jpg)

**If possible, please provide a logo for the service (512x512 minimum)** 
![Chrome_Web_Store_Logo_2012-2015](https://user-images.githubusercontent.com/71935156/99537516-121df900-29ac-11eb-81d2-61081e849b8c.jpg)

**Comment by MrBartusek** [comment]
Working on that!

**Comment by MaXfAa** [comment]
I meant "theme" not "topic" ... I use Google Translate because I speak French...

**Comment by ririxidev** [comment]
Forgot, Extensions can't inject to chrome web store so this can't be done.
