### ISSUE TITLE
[Presence Request] Open.Spotify.com

### ISSUE THREAD

**Issue by zabersan** [PreMiD/Presences#2512]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Senko#0001

**What's the name of the service?** 
https://open.spotify.com

**What should the Presence display?**  the same features as the default Spotify Discord integration, ex: current playing song, time remaining, album art, button to invite other to listen as well (start a jam session), artist name, playlist author name,

**If possible, please provide a logo for the service (512x512 minimum)** 
![tier1_1024x](https://user-images.githubusercontent.com/30378622/99910738-bca05f80-2cbd-11eb-8a6a-2eb169e98991.png)

**Comment by ririxidev** [comment]
Discord already has spotify support and it works with spotify web too.
