### ISSUE TITLE
MonkeyType | monkeytype.com

### ISSUE THREAD

**Issue by aballandofselfworth** [PreMiD/Presences#2514]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**
alan lmao#0003

**What's the name of the service?**
 www.monkeytype.com

**What should the Presence display?** 
kinda like typeracer, it should be like "Testing the keys" and at the end of the race show the results would be the wpm accuracy etc

**If possible, please provide a logo for the service (512x512 minimum)** 
![mtsocial](https://user-images.githubusercontent.com/74885759/99923992-63a8e980-2d06-11eb-92ad-139f3e70e0c2.png)
idk if that link will work, if it doesnt hit me up on discord i posted it above

**Comment by ririxidev** [comment]
merged
