### ISSUE TITLE
[Presence | Feature Request] e621.net

### ISSUE THREAD

**Issue by Mr-Foxtrot** [PreMiD/Presences#2542]
**What's the name of the service?**
e621.net

**Is your feature request related to a problem? Please describe.**
Well, I am aware the presence already exists. What I came here to request however was a settings page for it, as unlike other presences which lets you hide your search results or what page you are specifically viewing (an example is the Furaffinity rich presence) the e621 rich presence doesn't have any settings. So anyone who views your discord profile knows exactly what you are searching on the site, what post you are on, etc. A option to hide those details would be great and having it just show "Browsing e621" would be lovely. 

I don't believe a lot of people want to know exactly what you are searching up on e6 =/

**Comment by ririxidev** [comment]
Next time use feature request template

**Comment by Mr-Foxtrot** [comment]
Alrighty, sorry!

**Comment by ririxidev** [comment]
@rogi27 idk if you want to add it since you are owner of this presence, your decision.

**Comment by rogi27** [comment]
> @rogi27 idk if you want to add it since you are owner of this presence, your decision.

would be better for someone else to take care of it...
