### ISSUE TITLE
fnac | fnac.com / fnac.be

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#2544]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
MaXfAa#1068

**What's the name of the service?** 
fnac.com / www.fr.fnac.be

**What should the Presence display?** 
Much the same as the Amazon presence...

**If possible, please provide a logo for the service (512x512 minimum)** 
https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Fnac_Logo.svg/1200px-Fnac_Logo.svg.png

**Comment by KnuffelBeestje** [comment]
I may look into this. I am from Belgium as well, thanks for the request.
