### ISSUE TITLE
myCANAL - CANAL+

### ISSUE THREAD

**Issue by Dams678** [PreMiD/Presences#255]
**What's the name of the service?**
https://www.mycanal.fr | myCANAL

**What should the Presence display?**
Informations about the current video + remaining time (Live or Replay)

**Why do you want support for this service?**
Tell us why you want to have support for this website. Please don't just tell us "I use it all the time"

**Are you able to provide an image for the service? (512x512 minimum)**
https://image.noelshack.com/fichiers/2019/37/1/1568032844-246x0w.jpg

**Comment by frozaum** [comment]
Added #256
