### ISSUE TITLE
SecretHitler | SecretHitler.io

### ISSUE THREAD

**Issue by GCS7** [PreMiD/Presences#2561]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?*

**What's the name of the service?** SecretHtiler.io

**What should the Presence display?** One of the most fun and best Role Playing Board Game's online version.
**If possible, please provide a logo for the service (512x512 minimum)** https://ibb.co/P660V0D

**Comment by GCS7** [comment]
NOTE: The site has a player base of 200 approx. people online

**Comment by mlunax** [comment]
In any developement?
