### ISSUE TITLE
Naruto Game | nxb-nt-en.enza.fun

### ISSUE THREAD

**Issue by Overimaginer** [PreMiD/Presences#2563]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
NARUTO X BORUTO NINJA TRIBES | https://nxb-nt-en.enza.fun/
**What should the Presence display?** 
The Presence should display what menu you're on, and if your playing, it should say what you're doing and display what mission you're doing. It should also display the time you've been in that mission.
**If possible, please provide a logo for the service (512x512 minimum)** 
https://i.imgur.com/kic23Se.png (This is the Play/App Store Logo.)

**Comment by ririxidev** [comment]
oops, I forgot we do not accept subdomains. So I'm closing this request
