### ISSUE TITLE
Rabbit's BS Viewer | skystudioapps.com/bs-viewer

### ISSUE THREAD

**Issue by Flowyan** [PreMiD/Presences#2568]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Flowyan#1111
**What's the name of the service?** 
+1 Rabbit's BS Viewer | https://skystudioapps.com/bs-viewer/
**What should the Presence display?** 
The current map playing and its difficulty
**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by ririxidev** [comment]
Provide logo for it
