### ISSUE TITLE
skribbl.io (Game)

### ISSUE THREAD

**Issue by Dams678** [PreMiD/Presences#257]
**What's the name of the service?**
Ex. https://skribbl.io/ | skribbl.io

**What should the Presence display?**
Playing - "Round Number" "Number of points" (If is possible) + Eleapsed time

**Why do you want support for this service?**
I very love this game and i think some peopole like this game

**Are you able to provide an image for the service? (512x512 minimum)**
https://image.noelshack.com/fichiers/2019/37/1/1568065012-skribbl.png

**Comment by MrVoltox30** [comment]
suus

**Comment by Dams678** [comment]
> oh yes i very like this game too, i play it everyday

Ahhhhh

**Comment by frozaum** [comment]
Added #259
