### ISSUE TITLE
Mangago | mangago.com

### ISSUE THREAD

**Issue by Stangtang** [PreMiD/Presences#2586]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**weewow#7272** 

**http://www.mangago.me** 

**What manga you are reading, what chapter, what page, and how long you have been reading.** 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by ririxidev** [comment]
Provide logo
