### ISSUE TITLE
Minecraft Wiki

### ISSUE THREAD

**Issue by Stangtang** [PreMiD/Presences#2588]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**weewow#7272** 

**https://minecraft.gamepedia.com/Minecraft_Wiki** 

**What page you are on and how long you have been on it.** 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by ririxidev** [comment]
Actually, better option would be to support whole gamepedia so you can request it tho, but this I'm closing.

**Comment by Hans5958** [comment]
Come on, it's been a year since I created the presence for Gamepedia!

#756
