### ISSUE TITLE
Hdfilmcehennemi

### ISSUE THREAD

**Issue by ekmekeren** [PreMiD/Presences#2591]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Ekmek Eren ˢᵒᵘˡ#5618

**What's the name of the service?** https://www.hdfilmcehennemi.net/

**What should the Presence display?** Is watching ... movie , take a glance at .... movie

**If possible, please provide a logo for the service (512x512 minimum)** 
![hdfilm](https://user-images.githubusercontent.com/37958395/101412416-a3b9c000-38f3-11eb-86f0-bc1224b75af1.png)

**Comment by ririxidev** [comment]
https://www.hdfilmcehennemi2.pw this domain is already different thing so you should do another request :)

**Comment by RedS-DEV** [comment]
I will look into it

**Comment by RedS-DEV** [comment]
@erentan12 Done. #3174
You can DM me on Discord for anything about this presence. (RedS#6100)

**Comment by ekmekeren** [comment]
> @erentan12 Done. #3174
> You can DM me on Discord for anything about this presence. (RedS#6100)

Cool thanks. I will send friend request soon to you with my Eren Ekmek#5618 account.
