### ISSUE TITLE
Apple Music (Web)

### ISSUE THREAD

**Issue by evansims** [PreMiD/Presences#260]
**What's the name of the service?**
Ex. https://beta.music.apple.com | Apple Music

**What should the Presence display?**
Current track/album/artist information of song being played back.

**Why do you want support for this service?**
The Apple Music streaming service is finally launching a web client, currently in beta at the URL above. I primarily use Apple Music and would love to see it supported, as I'm sure others would.

**Are you able to provide an image for the service? (512x512 minimum)**
![image](https://user-images.githubusercontent.com/3093/64629069-71689c80-d3ea-11e9-8039-d77a010259f3.png)

I donated to the Patreon to help inceltivize work toward this, under the $50 tier. I love this project and hope to see it continue to flourish! Thanks.

**Comment by frozaum** [comment]
Added #262
