### ISSUE TITLE
AniMixPlay | animixplay.to

### ISSUE THREAD

**Issue by sakamotodesu1** [PreMiD/Presences#2600]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** 
animixplay.to | AniMixPlay

**What should the Presence display?** 
Show and episode you are watching, time elapsed/left

**If possible, please provide a logo for the service (512x512 minimum)** 
![icon512](https://user-images.githubusercontent.com/66633018/101959586-ef000580-3c48-11eb-8031-9603e9ec509d.png)

**Comment by jackkelly-bayliss** [comment]
Hello @sakamotodesu1,

I'll be more than happy to develop this presence for you. What's your Discord Tag? I'll keep you updated with the progress :)

Kind Regards,
Jack

**Comment by sakamotodesu1** [comment]
thank you
SakamotoDesu#1000
