### ISSUE TITLE
Musixmatch | musixmatch.com

### ISSUE THREAD

**Issue by KorpeZ** [PreMiD/Presences#2605]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
wl#0604 

**What's the name of the service?** 
https://www.musixmatch.com/ | Musixmatch 

**What should the Presence display?** 
- What lyrics you're viewing and the timestamp
Ex. Viewing lyrics
     Travis Scott - goosebumps
     01:43 elapsed
or
 Put a reading little image (like the playback paused or resume on YouTube) and "Viewing lyrics" as text 
      goosebumps (Music)
      Travis Scott (Artist)
      01:43 elapsed
- If you're transcribing show at the presence what is the music and the timestamp
      Transcribing lyrics
      Travis Scott - goosebumps
      01:43 elapsed
or 
 Put a writting little image and "Transcribing lyrics" as text 
      goosebumps
      Travis Scott 
      01:43 elapsed

Looking a profile (no need but if you wanna), if someone is not viewing any lyrics or transcribing, show "Browsing" instead
Looking a artist and who's the artist that you're seeing.
![Musixmatch_logo_icon_only svg](https://user-images.githubusercontent.com/52265455/102015718-01a73700-3d3c-11eb-9f66-c9f4dd217cdc.png)

**Comment by NMW03** [comment]
I'm making this

**Comment by KorpeZ** [comment]
Sure, thanks :)
