### ISSUE TITLE
AnimesHD | animeshd.org

### ISSUE THREAD

**Issue by minicocoxt** [PreMiD/Presences#2621]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Smiths#0001
**What's the name of the service?** 
animeshd.org | AnimesHD
**What should the Presence display?** 
Show and episode you are watching, time elapsed/left

**If possible, please provide a logo for the service (512x512 minimum)** 
![icon](https://user-images.githubusercontent.com/26691265/102102441-937d7580-3e0a-11eb-9e88-6bdcee286c50.png)

**Comment by jackkelly-bayliss** [comment]
Hello @minicocoxt,

If someone is not already working on this project (@ririxidev), I'll be happy to develop it for you :)

Kind Regards,
Jack

**Comment by minicocoxt** [comment]
Hello @jackkelly-bayliss 

There is still no one working on the project, I would be happy if you helped me with that.

Kind Regards,
Smiths

**Comment by jackkelly-bayliss** [comment]
Hello @minicocoxt,

I can certainly help with that, do you have Discord to communicate on or would you prefer it to be via this?

Kind Regards,
Jack

**Comment by minicocoxt** [comment]
Hi @jackkelly-bayliss 

My discord is Smiths # 0001 I think it would be better if we communicate there.

Kind Regards,
Smiths

**Comment by minicocoxt** [comment]
Hi @jackkelly-bayliss 

Still interested?

**Comment by Slowftw** [comment]
@minicocoxt ✋
