### ISSUE TITLE
New presence

### ISSUE THREAD

**Issue by parisoui** [PreMiD/Presences#2623]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** pais#0003
**What should the Presence display?** The presence should display the movie you are watching, how far into it you are, the cover art for the movie and the title

**If possible, please provide a logo for the service (512x512 minimum)** 

The website is called MoviesJoy

**Comment by ririxidev** [comment]
upload logo
