### ISSUE TITLE
Rat Fiesta! | http://ratfiesta.com

### ISSUE THREAD

**Issue by Mytherals** [PreMiD/Presences#2632]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Mytherals#5553

**What's the name of the service?** http://ratfiesta.com/ | Rat Fiesta!

**What should the Presence display?** On click, start a timer that displays how long you have been listening to Rat Fiesta.

**If possible, please provide a logo for the service (512x512 minimum)** 
![rat](https://user-images.githubusercontent.com/58233750/102293738-ad57af00-3f15-11eb-92c5-4eaa171d4f8d.png)

**Comment by ririxidev** [comment]
um, no this site is so low quality xD
