### ISSUE TITLE
Shudder | shudder.com

### ISSUE THREAD

**Issue by Skeptator** [PreMiD/Presences#2634]
**Prerequisites and essential questions** 
- [x] Is it a popular site? 
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Skeptator#1337

**What's the name of the service?** https://www.shudder.com/member

**What should the Presence display?** Like Netflix, Name of the movie/series, timer (Start to Finish), paused , resumed , and the name of the service with the logo.

**If possible, please provide a logo for the service (512x512 minimum)** 
![_NFSqiVr_400x400](https://user-images.githubusercontent.com/64229258/102316598-2551c380-3f6e-11eb-8f2e-2a9b952dd8fd.png)

**Comment by jackkelly-bayliss** [comment]
Hello @Skeptator,

I'll be happy to develop this for you. Could you possibly message me on Discord please? Thank you.

**Jack Hansen#2297**

Kind Regards,
Jack

**Comment by kagbogre** [comment]
Are you developing this @jackkelly-bayliss? If not I can get it done. Just don’t want to work on it if you already have progress.
