### ISSUE TITLE
Cookie Clicker (DashNet) Presence Update Rate

### ISSUE THREAD

**Issue by Duckrinium** [PreMiD/Presences#2639]
**Is your feature request related to a problem? Please describe.**
I started to notice that my game runs not as smooth as if without presence, and then I noticed It's updating way too often, which slows down the game and use a lot of CPU resources.

**Describe the solution you'd like**
Limiting update rate to around 10-15 seconds.

**Describe alternatives you've considered**
Allowing user to change update rate with setting in PreMiD extension menu.

**Additional context**
This is how it looks for me | This is how it looks for others:
![vYdphI3Xsn](https://user-images.githubusercontent.com/37019004/102386095-b0b76d00-3fdf-11eb-9ba9-8b9f34c8e3d3.gif) ![s5yraPqe](https://user-images.githubusercontent.com/37019004/102390454-79e45580-3fe5-11eb-9b06-bda6224836ed.gif)
This is only client-side issue.

_[Link](https://github.com/PreMiD/Presences/tree/master/websites/D/DashNet) to presence itself._

**Comment by ririxidev** [comment]
Um, actually it isn't possible to fix. PreMiD will not change updaterate to 10-15 seconds only for this presence. Discord handles ratelimit itself in this and like you see it isn't changing every 10ms.
