### ISSUE TITLE
Issue with Twitch Presence Not Displaying Status on Discord as it's supposed to...

### ISSUE THREAD

**Issue by NYISLANDERFAN** [PreMiD/Presences#2642]
For months and months, I've noticed that the Twitch Presence is not displaying any Discord Activity as it's supposed to....
I'm not sure exactly what the problem could be but hope that it can be resolved by me reporting the issue here so that someone with [the] experience in building these statuses & with Twitch to be able to possibly hopefully identify and repair or fix this presence so it may be used and so it works properly.
Thank you.

**Comment by ririxidev** [comment]
We know about it just check this
![image](https://docs.premid.app/presencesettings.gif)
This is caused by extension bug that is fixed already in beta version.
