### ISSUE TITLE
Radiooooo | radiooooo.com

### ISSUE THREAD

**Issue by onrdrsy** [PreMiD/Presences#2645]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Nderian#0217
**What's the name of the service?** 
Radiooooo | https://radiooooo.com
**What should the Presence display?** 
Song name, artists, song duration and song image
**If possible, please provide a logo for the service (512x512 minimum)** 
![radiooooo](https://user-images.githubusercontent.com/20243362/102639246-ce184280-4169-11eb-8f0d-542f744d8fd0.png)

**Comment by jackkelly-bayliss** [comment]
Hello @onrdrsy,

I’ll be happy to create this presence for you but unfortunately it won’t be possible to show the song image - are you happy to continue?

Kind Regards,
Jack

**Comment by onrdrsy** [comment]
@jackkelly-bayliss 
Song image is not so important. Doing it for me would make me very happy. Thank you!

**Comment by ririxidev** [comment]
Maybe provide url to this site?

**Comment by jackkelly-bayliss** [comment]
> Maybe provide url to this site?

http://radiooooo.com/

**Comment by ririxidev** [comment]
I wanted it because he didn't provide it to description where it says to provide url site.

**Comment by onrdrsy** [comment]
> Hello @onrdrsy,
> 
> I’ll be happy to create this presence for you but unfortunately it won’t be possible to show the song image - are you happy to continue?
> 
> Kind Regards,
> Jack

Any progress?

**Comment by SlowLife1661** [comment]
I'd love to work on this if they were changed thier mind xd

**Comment by Isa27-0** [comment]
Ok, this Issue can now rest
