### ISSUE TITLE
fmovies.to presence request

### ISSUE THREAD

**Issue by vis-rr** [PreMiD/Presences#2646]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
vis#0001
**What's the name of the service?** 
fmovies.to 
**What should the Presence display?** how a default presence is displayed (like netflix)

**If possible, please provide a logo for the service (512x512 minimum)** 
https://i.imgur.com/1su7PGh.png
![1su7PGh](https://user-images.githubusercontent.com/75807920/102642545-c51d7600-4155-11eb-82bb-ecd1131647c3.png)

**Comment by ririxidev** [comment]
Not possible to do, I had this presence but now it can be fixable due of their some "jses"
