### ISSUE TITLE
Monkeytype | monkeytype.com

### ISSUE THREAD

**Issue by MichaelRom19** [PreMiD/Presences#2647]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

MichaelRom#7158 (feel free to text me anytime, if you have any questions).

monkeytype.com | Monkeytype 

Display the WPM (words per minute) [during and] after a "test", as well as the accuracy (in %). If it is possible, try to fit in the test "type" (e.g. "time 30", "words 50", "quote medium"). If it is impossible to show the WPM during the test, show the WPM of the previous one (and show that you are typing a new test right now. Something like: "In a test. Last WPM = 71, acc. = 96%, type = time 30"). I would highly recommend opening the presence.ts for a similar website - Typeracer (or Nitrotype), and using it as an example. 

![image](https://user-images.githubusercontent.com/41574425/102645022-16336700-4162-11eb-9503-896dc6389d9c.png)

**Comment by ririxidev** [comment]
Merged: https://premid.app/store/presences/Monkeytype
