### ISSUE TITLE
FreeCodeCamp not working

### ISSUE THREAD

**Issue by tom-logging** [PreMiD/Presences#2667]
**Describe the Bug**
I deleted the account that the presence "FreeCodeCamp" was using so it will no longer but all that needs to make it work again is changing the clientID.

**Steps to Reproduce**
1. Change the ClientId to "790880432954409000"

**Expected Behavior**
Because I deleted the account which the FreeCodeCamp presence was using, the clientID also got deleted.

**Environment**

OS - Windows 10, Linux
Browser  - All of them?

https://user-images.githubusercontent.com/67664316/102876987-ede78900-443d-11eb-9583-67a72a2c3d31.mp4

**Comment by ririxidev** [comment]
So change it by pull request? Why you even create issue for that? xD

**Comment by tom-logging** [comment]
I didnt know... I'm very sorry
