### ISSUE TITLE
Discord Merch | discordmerch.com

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#2669]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
MaXfAa#1068

**What's the name of the service?** 
https://discordmerch.com/ | Discord Merch (the official clothes store of Discord)

**What should the Presence display?** 
1. Discord Merch
2. The collection
3. The product

**If possible, please provide a logo for the service (512x512 minimum)** 
https://cdn.shopify.com/s/files/1/1033/1885/files/logo-transparent_185x.png?v=1603867104

**Comment by ScypterDev** [comment]
I'll be able to do it!

**Comment by MaXfAa** [comment]
> I'll be able to do it!

That's great ! 😀

**Comment by MaXfAa** [comment]
It's over ! Perfect !
