### ISSUE TITLE
RTBF Auvio | auvio.be

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#2670]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
Belgium
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Maxou#1909

**What's the name of the service?** 
RTBF Auvio | auvio.be

**What should the Presence display?** 
1. RTBF Auvio
2. Watching content / Listen show
3. The program name

**If possible, please provide a logo for the service (512x512 minimum)** 
https://www.static.rtbf.be/tv/media/images/rtbf-auvio-logo-318x68.png?v=2

**Comment by ScypterDev** [comment]
I will be able to do this request since I am dutch.
