### ISSUE TITLE
SCR Premid Service Request.

### ISSUE THREAD

**Issue by VGJonno** [PreMiD/Presences#2673]
**Prerequisites and essential questions** 
- [x] Is it a popular site? average of 10 - 20 listeners concurrent
- [x] Is the website older than 2 months? Yes! 
- [ ] Is the site locked to a specific country/region? No!
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) No.
- [ ] Does the website feature NSFW content? (e.g. porn, etc...) No.
- [ ] Are you a donator/patron? No.
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? Yes.

**What's your Discord username?** Jonno_Playz#6672 

**What's the name of the service?** Simulation Community Radio 

**What should the Presence display?** Song Metadata, Current Song, Artist and Current Listeners.

**If possible, please provide a logo for the service (512x512 minimum)** 
![SCR Pure](https://user-images.githubusercontent.com/66536962/102938135-98de5e00-44a3-11eb-89fd-cd08725e3817.png)

**Comment by ririxidev** [comment]
Please update url for this site. For now closing this request since it isn't complete.
