### ISSUE TITLE
Netflix not showing Running tile keeps saying browsing

### ISSUE THREAD

**Issue by nuz-cinel** [PreMiD/Presences#2681]
**Describe the Bug**

when i start watching anything on netflix it just keeps saying browsing... instead of displaying the watching time and title ect and ive tried uninstalling all of it and reinstalling and tried redoing the chrome extension but not working :( everything else works fine youtube google ect just netflix does not display the title keeps saying browsing
**Steps to Reproduce**

![image](https://user-images.githubusercontent.com/76576367/103116080-f538ad80-465c-11eb-81cd-7e9f4757a7a7.png)

1.
2.
3.

**Expected Behavior**

not showing the running title or time remaining or episode ect just says browsing...
**Screenshots**

![image](https://user-images.githubusercontent.com/76576367/103116089-fe297f00-465c-11eb-9190-455809b85bfb.png)

**Environment**

- OS: 
- windows 10
- Browser: 
chrome
- Version: 
  
v2.1.4
**Additional context**

**Comment by ririxidev** [comment]
It can be because: Netflix is rolling out new UI or in some countries netflix has different UI and it is not possible to fix it.
