### ISSUE TITLE
Sitting on Clouds | *.squid-radio.net

### ISSUE THREAD

**Issue by solitonmedic** [PreMiD/Presences#2687]
**Describe the Bug**
Rich presence does not appear as it should.

**Steps to Reproduce**
1. Go on either the "Woomy", "Sonic" or "Persona" radios.
2. Check rich presence.

**Expected Behavior**
Discord rich presence displaying the song's name and radio being used.

**Environment**
- OS: Linux Mint 20 Cinnamon
- Browser: Brave
- Version: Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)

**Comment by ririxidev** [comment]
@sks316

**Comment by sks316** [comment]
The site seems to have changed its design at the beginning of the month, which broke the presence. I don't have PreMiD installed on my computer anymore, but I'll get it installed whenever I can so I can update the presence. If anyone else wants to tackle it until then, feel free.
