### ISSUE TITLE
JustDanceNow | justdancenow.com

### ISSUE THREAD

**Issue by Vilanelli** [PreMiD/Presences#2694]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Marianna#0101

**What's the name of the service?** https://justdancenow.com/

**What should the Presence display?** It would be interesting to show the name of the song we danced and the time left to finish. Also show when we are changing the avatar and choosing another song.

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/76649737/103170543-b3a62f00-4823-11eb-8239-acd003a9e9dc.png)

**Comment by ririxidev** [comment]
blep #1001
