### ISSUE TITLE
Pocket Casts | play.pocketcasts.com

### ISSUE THREAD

**Issue by cedricksusername** [PreMiD/Presences#2696]
**Describe the Bug**

When you launch a podcast on Pocket Casts, the presence just says "viewing subscriptions" no matter what.

**Steps to Reproduce**

1. Go on https://play.pocketcasts.com.
2. Click play on a podcast.
3. Watch as nothing changes in the presence on Discord.

**Expected Behavior**

I'm expecting it to show the episode name of whatever I'm listening to, which podcast it's from and maybe the time stamp.

**Screenshots**

![Bug in action](https://i.imgur.com/JadAYVe.png)

**Environment**

- OS:  Windows 10 20H2
- Browser:  Firefox (but I think it happens on every browser)
- Version:  84.0.1 (64-bit)
  

**Additional context**

This is a major bug that makes the presence unusable.

**Comment by ririxidev** [comment]
@TheLastZombie is owner of this presence, but I don't know if they will fix it.

**Comment by realtofuine** [comment]
Reproducible

It doesn't even do anything anymore lol
