### ISSUE TITLE
Yandex.Translate | translate.yandex.com

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#2699]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
MaXfAa#1068

**What's the name of the service?** 
https://translate.yandex.com | Yandex.Translate

**What should the Presence display?** 
Same that Google Translate

**If possible, please provide a logo for the service (512x512 minimum)** 
https://s1.qwant.com/thumbr/0x380/b/8/159fcda2bd0b275590c209db0161034cf3178bd1c1e859f23cf0e82ec76144/Yandex_Translate_logo.jpg?u=http%3A%2F%2Fwww.velior.ru%2Fwp-content%2Fuploads%2F2018%2F10%2FYandex_Translate_logo.jpg&q=0&b=1&p=0&a=1

**Comment by ririxidev** [comment]
offtop: yandex, for real? who is using yandex translate xDD like it has 8seconds respond time in API XDDDD

**Comment by MaXfAa** [comment]
> offtop: yandex, for real? who is using yandex translate xDD like it has 8seconds respond time in API XDDDD

Over 90 million internet users use Yandex every month. So if one in 90 people use the translation tool, that's 1M users per month. So a lot of users 😉
Despite the latency...

**Comment by StrikerFRFX** [comment]
I'm going to work on this :)

**Comment by MaXfAa** [comment]
> I'm going to work on this :)
Yes ! 🥳 Thx !!

**Comment by StrikerFRFX** [comment]
> > I'm going to work on this :)
> 
> Yes ! 🥳 Thx !!

Done :) just waiting to be reviewed

**Comment by MaXfAa** [comment]
> > > I'm going to work on this :)
> > 
> > 
> > Yes ! 🥳 Thx !!
> 
> Done :) just waiting to be reviewed

Ok 😉
