### ISSUE TITLE
VRV | vrv.co

### ISSUE THREAD

**Issue by Zewia** [PreMiD/Presences#27]
**What's the name of the service?**
vrv.co | VRV

**What should the Presence display?**
Informations about the current video

**Why do you want support for this service?**
VRV hosts many different anime streaming services in one site allowing for much wider coverage if VRV is supported. VRV (to me atleast) seems to be the successor of Crunchyroll and other services.

**Are you able to provide an image for the service? (512x512 minimum)**
![image](https://user-images.githubusercontent.com/25493071/50065882-c8f11900-0186-11e9-9efd-44be3c2b59a3.png)

**Comment by Bas950** [comment]
Not available in my region
