### ISSUE TITLE
Telegrsm Presence

### ISSUE THREAD

**Issue by playday3008** [PreMiD/Presences#2700]
**Is your feature request related to a problem? Please describe.**
So that's problem with confidentiality, sometimes nicknames of interlocutors contain sensitive data (eg. phone number, mail, etc.)

**Describe the solution you'd like**
Please add the option "Show the name of the interlocutor" to this presence 

**Describe alternatives you've considered**
Rename interlocutors in Telegram, but this is stupid solution

**Additional context**
Enabled: Talking to this user: Dad (for example)
Disabled: Talking to someone

**Comment by ririxidev** [comment]
use feature request template 😉

**Comment by playday3008** [comment]
@ririxidev edited, I don't want to create a new issue

**Comment by AyamDobhal** [comment]
telegram? or is telegrsm something i dont know about?

**Comment by playday3008** [comment]
#2718
