### ISSUE TITLE
[Presence | Bug] FUNimation

### ISSUE THREAD

**Issue by Ushiora** [PreMiD/Presences#2708]
This started happening sometime this week.
When watching something on FUNimation it will now display as:

"**Funimation
Looking at:
[Anime Title/Episode here]
05:12 elaspsed**"

Instead of what it originally did, which was something like:
"**Funimation
[Anime Title here]
[Season/Episode/Name of Episode here]
22:46 left**"

Note: I have reinstalled/updated both PreMiD and the Firefox extension.

PreMiD: **v2.1.4**
Extension: **v2.2.0.1**

**Comment by Ushiora** [comment]
Bump, VRV's site also has the same issue.

**Comment by Ushiora** [comment]
VRV's site also has the same issue.

**Comment by ririxidev** [comment]
@Bas950
