### ISSUE TITLE
[Bug | Presence] HBO Max

### ISSUE THREAD

**Issue by zredrum** [PreMiD/Presences#2711]
**Bug Description:**
- When opening a show, it simply shows "feature" and the amount of time elapsed.
- ![See Here](https://i.imgur.com/HKmysmJ.png)

**Steps to Reproduce**
1. Open HBO Max,
2. Open any show on it or movie,
3. View results.

**Expected Behavior**
- Show the name of the show and elapsed time of it, not normally continue the time if it's stopped.
- Play/pause logo used to be there, disappears after refreshing page?

**Environment**
- OS: MacOS Big Sur Version 11.1
- Browser: Chrome
- Version: 87.0.4280.88

**Additional context**
Just rather odd. No matter where I go, elapsed time still doesn't alter either.

**Comment by beasleeps** [comment]
New error as well:
![HBO Error](https://i.imgur.com/kkDffZx.png)

**Comment by Ushiora** [comment]
VRV and FUNimation also have the same problem.
But Netflix works properly though.

**Comment by ririxidev** [comment]
Ok cool but stop writing it everywhere thanks.

**Comment by ririxidev** [comment]
Should be fixed lol
