### ISSUE TITLE
Tokopedia | tokopedia.com

### ISSUE THREAD

**Issue by pemujakentang** [PreMiD/Presences#2736]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
www.tokopedia.com | Tokopedia

**What should the Presence display?** 
   General activities on the site or just site activity

**If possible, please provide a logo for the service (512x512 minimum)
![tokped logo 3](https://user-images.githubusercontent.com/76871428/103457849-33a52b00-4d35-11eb-92ec-ecd21daf8547.png)
**

**Comment by WilloIzCitron** [comment]
im ready for making it

**Comment by pemujakentang** [comment]
How do we make it? I've edited the code from the guides on premid website, then what should I do?

**Comment by WilloIzCitron** [comment]
> How do we make it? I've edited the code from the guides on premid website, then what should I do?

i created on my fork

**Comment by pemujakentang** [comment]
mantap wis, ada yang lebih berpengalaman. saya kurang ngerti juga soalnya hehehehe, masih pemula. makasih banget kak :) kalo misalnya ada yang perlu saya bantu, chat aja kak @WilloIzCitron , saya juga mau belajar soalnya
(nice, somebody more experienced to do this. I don't really understand, as i am new. thanks man!)

**Comment by ririxidev** [comment]
english only pls

**Comment by pemujakentang** [comment]
i've made a fork from @WilloIzCitron 's fork, what should i do now?

**Comment by ririxidev** [comment]
You nothing... If he is doing it he will need to do pull request with it. You just wait...

**Comment by pemujakentang** [comment]
ah, yes i understand, thx

**Comment by WilloIzCitron** [comment]
i created a presence

after merge a pr close this issues
