### ISSUE TITLE
Tetr.io | tetr.io

### ISSUE THREAD

**Issue by Hyruled** [PreMiD/Presences#2743]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Hyruled#1567

**What's the name of the service?** tetr.io

**What should the Presence display?** Level on profile, gamemode, time elapsed

**If possible, please provide a logo for the service (512x512 minimum)** 
![pN9ULwc6_400x400](https://user-images.githubusercontent.com/76912519/103483453-9ce57680-4de7-11eb-848f-3139e199ba36.jpg)

**Comment by magumboi** [comment]
ok, let me look into it

**Comment by magumboi** [comment]
[https://github.com/PreMiD/Presences/pull/3128](url)

**Comment by StrikerFRFX** [comment]
Done :+1:
