### ISSUE TITLE
Rich Presence does not display on my Discord Status

### ISSUE THREAD

**Issue by glimeball** [PreMiD/Presences#2751]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**gwallah#5555** 

**Literally every single presence I use** 

**Any presence I use; nothing shows up**

**Comment by ririxidev** [comment]
https://docs.premid.app/troubleshooting
