### ISSUE TITLE
Crunchyroll presence only stuck on "Browsing" on Discord

### ISSUE THREAD

**Issue by glimeball** [PreMiD/Presences#2752]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**gwallah#5555** 

**crunchyroll.com** 

**It should display what I'm currently watching on Crunchyroll when I click play, because as soon as it starts streaming, my Discord status still remains as "Browsing" and not the usual activity**

**Comment by ririxidev** [comment]
already known because extension issue.
