### ISSUE TITLE
Agar.io | Only shows playing Agar.io

### ISSUE THREAD

**Issue by CyberByte-js** [PreMiD/Presences#2753]
**Describe the Bug**

**Steps to Reproduce**

1. Install Agar.io presence;
2. Enter in Agar.io;
3. Open Discord.

**Expected Behavior**

Show something else.

**Screenshots**

![image](https://user-images.githubusercontent.com/71409005/103575162-092bad00-4eb0-11eb-85f8-fdad86c25a01.png)
![image](https://user-images.githubusercontent.com/71409005/103575193-19438c80-4eb0-11eb-80bb-b3f90f5d36a0.png)

**Environment**

- OS: Windows 10
- Browser: Google Chrome
- Version: Browser: 87.0.4280.88 PC: 20H2
  

**Additional context**

**Comment by isladot** [comment]
This behavior means that the presence matches the related URL, in this case `agar.io`, but does not match any case within the
```typescript
presence.on('UpdateData', async () => {
  const presenceData: PresenceData = {
    largeImageKey: //asset name
  };

  //your cases here.

  if (presenceData.details == null) {
    presence.setTrayTitle();
    presence.setActivity();
  } else {
    presence.setActivity(presenceData);
  }
}
```
I don't know what your presence should display in that specific case, but i think a RegExp could be useful.

**Comment by ririxidev** [comment]
It uses iframe 🤷
