### ISSUE TITLE
Ryuten.io | ryuten.io

### ISSUE THREAD

**Issue by GawdlyOTF** [PreMiD/Presences#2765]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Gawdly#0066

**What's the name of the service?** Ryuten.io

**What should the Presence display?** Currently there are 3 servers; America, Europe, and Asia. The presence should show what server the player is playing in. Currently, there are 4 game modes; Classic, Ultra Fission, Multibox 1v1, and Instant Merge. It should show the game mode the player is playing. There's an option called "Spectate", the presence should show when the player is spectating. There's also an option for "Settings", the presence should when the player is browsing their settings. 

Another important feature this presence should have is, the player's in-game name, mass (score), and there tag the player is using. The in-game name for the tag is called "Team".

An example of how the presence should look can be shown below:
Ryuten.io
NA: Classic or North America: Classic
Gawdly - 42.9K mass (if the player is in a team) [Hello]Gawdly - 42.9k mass 

For the other features I mentioned, it can look something like this:
Ryuten.io
Spectating  (If possible, the presence can show what server and game mode the player is currently spectating in)

Ryuten.io
Browsing Settings

**If possible, please provide a logo for the service (512x512 minimum)** 
![logo-new-sm](https://user-images.githubusercontent.com/77090162/103856464-b0603e00-5082-11eb-92a6-af0758077998.jpg)

**Comment by PiggyPlex** [comment]
As far as I have looked (for about 2 mins in chrome console), I can't find any variables storing the mass data. However, it is possible to get the username of the user, skins, and server. Does anyone know if it is possible to find the mass?
