### ISSUE TITLE
Game Jolt | gamejolt.com

### ISSUE THREAD

**Issue by daiocu** [PreMiD/Presences#277]
**What's the name of the service?**
https://gamejolt.com/ | Game Jolt

**What should the Presence display?**
Information about the page, as it is in Steam's presence

**Why do you want support for this service?**
As with Steam's presence, it would be nice to have more PreMiD-enabled gaming sites.

**Are you able to provide an image for the service? (512x512 minimum)**
yes
![GameJolt](https://user-images.githubusercontent.com/47509694/64995247-171b8000-d8b1-11e9-991b-c545c4da2858.png)

**Comment by eggsywashere** [comment]
Working on it... I'll publish it in less than 30 minutes. _IT'S BEEN 28 DAYS O.O_
