### ISSUE TITLE
Khanacademy.org | KhanAcademy

### ISSUE THREAD

**Issue by saieeshb** [PreMiD/Presences#2774]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Gummy#7679
**What's the name of the service?** KhanAcademy | khanacademy.org

**What should the Presence display?** 
If watching a video, The Course, the unit,  and the name of the video.
If reading an article. The Course, the unit and the name of the article
If browsing a profile, maybe theirs or someone else's, "Browsing (name of person)'s profile"
If on hompage, "On Homepage"
If on a Course page "Browsing (this) course"
If coding, "Coding (name of project)"
If taking a quiz, "Taking a quiz on (name of unit)"

**If possible, please provide a logo for the service (512x512 minimum)** 
![unnamed](https://user-images.githubusercontent.com/66863579/104092977-69a25c00-52ad-11eb-82f8-bd5bd586025e.jpeg)

**Comment by ririxidev** [comment]
#751 :)
