### ISSUE TITLE
[YT Music] Reports last 4 characters of Album for Songs/Albums without a Year

### ISSUE THREAD

**Issue by Alipoodle** [PreMiD/Presences#2775]
**Describe the Bug**

YouTube Music Presences reports the Last 4 characters of the Album due if there is no Year present on the Track/Album which is currently playing providing a strange ending to the Album info.

**Steps to Reproduce**

1. Upload a Song to YouTube Music which does not contain ID3 Metadata for Year.
2. Play said Song
3. Look at the Presences and notice that it goes
    `{Artist} - {Album} ({Last 4 characters of Album})`

**Expected Behaviour**

No information is shown as there is no Year.

**Screenshots**

![Example Image of issue](https://user-images.githubusercontent.com/17199186/104105110-edefe180-52a3-11eb-9cbc-348698888f71.png)
Notice lack of year displayed here.
![image](https://user-images.githubusercontent.com/17199186/104105176-58088680-52a4-11eb-8b45-353351ffc352.png)

**Environment**

- **Discord:** Canary 74289 (b11448a) // Host 1.0.16
- **OS:** Windows 10 64-Bit (10.0.19041)
- **Chrome:** Version 87.0.4280.141 (Official Build) (64-bit)

**Additional context**

The issue lies [here](https://github.com/PreMiD/Presences/blob/master/websites/Y/YouTube%20Music/presence.ts#L22) As it just grabs the information and gets the Last 4 Characters.

**Comment by ririxidev** [comment]
Known, has to be fixed in new rewrite made by ytm presence dev.
