### ISSUE TITLE
Wuxia World presence (https://www.wuxiaworld.com/)

### ISSUE THREAD

**Issue by 505reaper** [PreMiD/Presences#2778]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** <!-https://www.wuxiaworld.com/->

**What should the Presence display?** <--It should display the chapter and novel you're reading at that time and how long you have been reading it -->

**If possible, please provide a logo for the service (512x512 minimum)** <!--- Optional, it is recommended to upload the image here instead of using a 3rd-party host. --
>![image](https://user-images.githubusercontent.com/77228113/104839334-519e8e00-58e6-11eb-9c35-ffee553404f3.png)

**Comment by ririxidev** [comment]
Not complete service request. Please fill it by creating new issue
