### ISSUE TITLE
Crunchyroll only shows browsing 

### ISSUE THREAD

**Issue by Gunwok** [PreMiD/Presences#2784]
**Describe the Bug**

**Steps to Reproduce**

1.
2.
3.

**Expected Behavior**

**Screenshots**

**Environment**

- OS: windows 10
- Browser: chrome 
- Version: 2.2.0
  

**Additional context**

**Comment by PiggyPlex** [comment]
I know we know what you mean, but please at least fill the form out properly 😂

**Comment by ririxidev** [comment]
bruh
