### ISSUE TITLE
DramaCool | dramacool.so

### ISSUE THREAD

**Issue by makalameow** [PreMiD/Presences#2787]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**makalee#0606** 

**https://dramacool.so/** 

**Display what you're watching and episode you're on (time-lapse)** 

**https://gyazo.com/4246d5992dbeda7955103749d5f25541**

**Comment by SlowLife1661** [comment]
Assign me this one
