### ISSUE TITLE
EDX | edx.org

### ISSUE THREAD

**Issue by TrismPrism** [PreMiD/Presences#2789]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username? prismtrism#5112** 

**What's the name of the service? https://edx.org/ | EDX** 

**What should the Presence display? The current site, current learning subject, and chapter.** 

**If possible, please provide a logo for the service (512x512 minimum) https://edx-cdn.org/v3/prod/logo.svg
**

**Comment by DarkVillager** [comment]
Im gonna try my best to make this presence idea a reality asap.
