### ISSUE TITLE
hanime.tv

### ISSUE THREAD

**Issue by NurMarvin** [PreMiD/Presences#28]
**What's the name of the service?**
Ex. www.hanime.tv | HanimeTv

**What should the Presence display?**
Informations about the current video

**Why do you want support for this service?**
HanimeTv is a big hentai provider that is widely used by many users and they also have a discord server, so people could install PreMiD and share their current hentai with other users on the server. In general, HanimeTv should be relevant enough to be implemented.

**Are you able to provide an image for the service? (512x512 minimum)**
![50220724-69b42400-0393-11e9-95f0-60c500efe198](https://user-images.githubusercontent.com/17235016/50221275-e0055600-0394-11e9-9dd5-381fafc966fc.png)

**Comment by frozaum** [comment]
so guys it's finally done
#282
