### ISSUE TITLE
Premid does not display Youtube, but other sites work just fine.

### ISSUE THREAD

**Issue by Jeggie-Ex** [PreMiD/Presences#2801]
**Describe the Bug**
Premid only have issues when trying to display youtube. Other sites tested, and they all work fine. (Youtube Music, Mangadex, and Custom Status work with no issues.)

**Steps to Reproduce**
1. Install Premid
2. Install the Youtube Presence
3. Open www.youtube.com
4. Check your discord status
5. It shows nothing.

**Expected Behavior**
Premid will display on discord what youtube video am i watching, the uploader, and duration left.

**Screenshots**

**Environment**

- OS: OS: Windows 10 version 2004 build 19041.685
- Browser: Opera GX version LVL 2 (core: 72.0.3815.459)

**Additional context**
It used to work flawlessly. Also, i am used to toggle the youtube presence quite often, if that actually affects it. Already tried reinstalling both the extension and the application.

**Comment by darklight147** [comment]
i was able to reproduce this behavior, i'll look into it

**Comment by ririxidev** [comment]
this is... issue on your end... just check troubleshooting page: https://docs.premid.app/troubleshooting.

**Comment by Isa27-0** [comment]
@Jeggie-Ex
