### ISSUE TITLE
Amazon Music Presence Does Not Work

### ISSUE THREAD

**Issue by Redcakes** [PreMiD/Presences#2802]
**Describe the Bug**
When using the Amazon Music presence it does not show anything as your Discord status when listening to Amazon Music.

**Steps to Reproduce**
1. Enable the Amazon Music presence
2. Listen to a song on Amazon Music
3. Look at your Discord status

**Expected Behavior**
The song you are listening to should show as your Discord status along with the time left. It should also show that you are listening on Amazon Music.

**Environment**

Windows 10
Microsoft Edge
Version 87.0.664.75 (Official build) (64-bit)

**Comment by Isa27-0** [comment]
Did you check the [troubleshooting](https://docs.premid.app/en/troubleshooting) page?

**Comment by awarre** [comment]
I have tried the troubleshooting page. the PreMID website and Youtube plugins both work as expected. Amazon Music does not work at all.

**Comment by awarre** [comment]
Quick check and it doesn't appear any of the selectors being used in the Amazon Music presence are valid anymore.

**Comment by Isa27-0** [comment]
Huh, so it's a problem. Let's wait for a developer to solve it.
