### ISSUE TITLE
9anime presence does not display current player time, time left etc as ideally should

### ISSUE THREAD

**Issue by StrikerFRFX** [PreMiD/Presences#2805]
**Describe the Bug**
Not sure if it is EXACTLY a bug but it seems it could be. TLDR; unlike youtube, netflix etc and other streaming sites, 9anime does not show the current status of the player (i.e paused, playing) and the time (when relevant). Not sure if this is right to report as a bug or not and whether it should be a feature request but this seemed most applicable.

**Steps to Reproduce**
Use 9anime presence

**Expected Behavior**
When paused, show paused like Netflix extension (below)
![image](https://user-images.githubusercontent.com/34070194/104652164-9d67f200-56b0-11eb-9e39-813cc7f372a8.png)

When playing, show time left like Netflix extension (below)
![image](https://user-images.githubusercontent.com/34070194/104652235-b83a6680-56b0-11eb-90ef-37e85329a850.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/34070194/104652312-d56f3500-56b0-11eb-9fb6-8e4a0b283a6d.png)

**Environment**

- OS: Windows 10
- Browser: Chrome
- Version: 87.0.4280.141 (Official Build) (64-bit) (cohort: Stable)

**Comment by ririxidev** [comment]
yes broken. im aware of this. extension issue 😉

**Comment by StrikerFRFX** [comment]
Oh right okay, thanks for confirming :)
