### ISSUE TITLE
Undercards

### ISSUE THREAD

**Issue by AltergeistX** [PreMiD/Presences#2810]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
It posses certain amount of players considering game was developed for Undertale/Deltarune fanbase.

- [x] Is the website older than 2 months? 
Website has been around 5 years if my memory serves me right.

- [x] Is the site locked to a specific country/region?
No website is for all languages,but main chat is used for english, thou it posses specific language channels.

- [x] Is the site a paid service? (e.g. Netflix, Hulu)
No game is completly free to play, except you can purchase virtual currency.

- [x] Does the website feature NSFW content? (e.g. porn, etc...)
No,website is 13+ and it's always highly moderated by staff team.

- [x] Are you a donator/patron?
No. I've recently discovered about your project and i will be glad to support it.

- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?
Yes, i'm fully aware of it and i hope my request at least ends up, even if it takes time for it to be created.

**What's your Discord username?** 
Altergeist#9969

**What's the name of the service?** 
https://undercards.net/

**What should the Presence display?** 
All aspects of the game if possible, aka: Home Page, Searching for Game (Ranked), Searching for Game (Standard), Decks, Crafting, Browsing Hub etc

**If possible, please provide a logo for the service (512x512 minimum)** 
![undercardsLogo](https://user-images.githubusercontent.com/77038082/104797151-451e1680-57bc-11eb-8396-daa7dac8be7a.png)

**Comment by ririxidev** [comment]
merged
