### ISSUE TITLE
Nutaku | nutaku.net

### ISSUE THREAD

**Issue by apoleon33** [PreMiD/Presences#2813]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 579#3440 

**What's the name of the service?** www.nutaku.net 

**What should the Presence display?** The Presence should show what game people are playing.

**If possible, please provide a logo for the service (512x512 minimum)** 
![logo nutaku](https://user-images.githubusercontent.com/71031475/104823864-8b6f8600-584d-11eb-8533-68e67ffae924.jpg)

**Comment by darklight147** [comment]
Please add the the **nsfw**

**Comment by apoleon33** [comment]
i think i alkready added it

**Comment by ririxidev** [comment]
yikes

**Comment by Venipa** [comment]
will do the presence the next days 👍

**Comment by Venipa** [comment]
#3332

**Comment by apoleon33** [comment]
thank you
