### ISSUE TITLE
Aniorb.me | Aniorb 

### ISSUE THREAD

**Issue by ICEPrey** [PreMiD/Presences#2816]
**Prerequisites and essential questions** 
- [] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** ICEPrey#0514

**What's the name of the service?** https://aniorb.me/ | Aniorb (Also the site is older than two month, I am the owner)

**What should the Presence display?** What the person is watching (title), timestamp (include playing/paused).

**If possible, please provide a logo for the service (512x512 minimum)** https://cdn.discordapp.com/attachments/768631221906571284/797158183637876736/Logo.png

**Comment by darklight147** [comment]
Nice website

**Comment by Abuws** [comment]
> Nice website

Thanks

**Comment by darklight147** [comment]
i have similare thing, but for games

**Comment by Abuws** [comment]
> i have similar thing, but for games

O Nice link?

**Comment by darklight147** [comment]
https://game-linter.com/

**Comment by ICEPrey** [comment]
Its really nice, I also wanna try dynamic search, never really took out my time to learn how to do it tho.

**Comment by darklight147** [comment]
it should be pretty straight forward depending on how you send data to your front-end, i also recommend you use SSR for your site, in order to get more organic traffic, i also had my site built in MERN stack in the past, but i converted it to Next.js and am actually liking it, oh more thing, how did you get google adsense on to your website, i had no luck with that

**Comment by ICEPrey** [comment]
> it should be pretty straight forward depending on how you send data to your front-end, i also recommend you use SSR for your site, in order to get more organic traffic, i also had my site built in MERN stack in the past, but i converted it to Next.js and am actually liking it, oh more thing, how did you get google adsense on to your website, i had no luck with that

Thanks for the advice. Also about the adsense thing, I didn't get accepted It says I need to have content on my website (which I do, but it can't detect it). So I am going to remove that code soon.

**Comment by ririxidev** [comment]
Do I really need to mute all of you? It isn't chat for discussions. Go to discord or whatever. This is presence repo.

**Comment by ICEPrey** [comment]
> Do I really need to mute all of you? It isn't chat for discussions. Go to discord or whatever. This is presence repo.

Sorry
