### ISSUE TITLE
[Bug | Presence] Jellyfin

### ISSUE THREAD

**Issue by ephibu** [PreMiD/Presences#2831]
When viewing an episode on Jellyfin, the presence shows that I am watching "unknown content" and that no metadata could be obtained. 

Steps to Reproduce
1. Turn on the Jellyfin presence
2. Launch Jellyfin
3. Choose an episode
4. The discord presence does not display the information of the episode

Expected behaviour: The presence should show what I am watching, episode number, season etc. 

Here is a screenshot of the error: https://imgur.com/a/TADD3Ao

OS: Windows 10
Browser: Chrome
Version: 87.0.4280.141 (64-bit)

**Comment by ririxidev** [comment]
@alexbcberio

**Comment by alexbcberio** [comment]
Thanks for the report I'll take a look at it

**Comment by alexbcberio** [comment]
@ephibu do you access Jellyfin from "/" or you have set it up under a custom path such as "/jellyfin"

**Comment by ephibu** [comment]
> @ephibu do you access Jellyfin from "/" or you have set it up under a custom path such as "/jellyfin"

It should be the default path

**Comment by ephibu** [comment]
> Yeah, as I though. I wasn't checking on the previous versions if the installation was done under a subpath, it should work now.

Yep it works. However, some shows still display the error, so im guessing its because of file metadata itself and not the presence?

**Comment by alexbcberio** [comment]
When does it show that error, while playing back the video? Check if it also happens while you're on the details page. If there isn't I'll need more information to fix it

**Comment by ephibu** [comment]
> When does it show that error, while playing back the video? Check if it also happens while you're on the details page. If there isn't I'll need more information to fix it

Renaming the files according to seems TVDB fix it. One last thing: when viewing a video, the presence disappears from the Active Now section in the friends tab. But when i browsing the details, it shows up. Is this a Discord related thing?

**Comment by alexbcberio** [comment]
No idea about the "Active Now" section, I'm checking if I'm displayed in there from my secondary account but I that section is not being displayed.

**Comment by ephibu** [comment]
Yeah, seems like the only time its not displayed is when a video is being played, which is weird because it shows for other media presences like plex and youtube

**Comment by alexbcberio** [comment]
I'm setting the presence status as stated in the docs, no idea why is not appearing in there. Maybe due to low user usage? (guessing)

**Comment by ephibu** [comment]
Hmm, actually it might be because when browsing the details, it shows the amount of time elapsed rather than time left (only difference i've found between the two). Would it be possible for you to implement a time elapsed option when watching a video/episode?

**Comment by alexbcberio** [comment]
Sorry I couldn't reply earlier, had a busy day 😅 
I've found the way to display the "active now" section, I only had to make the window wider 🤣 (dumb me). I made some tests and no idea what should I do in order to display content playback in this section, YouTube presence also shows with "time left" format.

I will test if its shown having "elapsed" format

**Comment by ephibu** [comment]
> Sorry I couldn't reply earlier, had a busy day 😅

No worries, appreciate you taking time out of your day to help me
> 

> I will test if its shown having "elapsed" format

Sounds good, thanks!

**Comment by alexbcberio** [comment]
> Hmm, actually it might be because when browsing the details, it shows the amount of time elapsed rather than time left (only difference i've found between the two).
After doing some tests **I think** the issue is because I'm deleting the startTimestamp, I really don't know why this is making a issue as is the standard and preferred way of doing it.

**Comment by ephibu** [comment]
> After doing some tests **I think** the issue is because I'm deleting the startTimestamp, I really don't know why this is making a issue as is the standard and preferred way of doing it.

Hmm interesting, definitely odd behaviour

**Comment by ririxidev** [comment]
Is it fixed?

**Comment by alexbcberio** [comment]
> Is it fixed?

Yes, the issue is fixed
