### ISSUE TITLE
Veepee | veepee.com

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#2834]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Maxou#1909

**What's the name of the service?** 
Veepee |
1. https://www.veepee.fr/
2. https://www.veepee.be/
3. https://www.veepee.com/

**What should the Presence display?** 
A bit like Zalando

**If possible, please provide a logo for the service (512x512 minimum)** 
https://s1.qwant.com/thumbr/0x380/b/4/88b8e2c08f2ce747af0abc8d671297f4107abd79bb92846fcf0347408d7946/512x512bb.jpg?u=https%3A%2F%2Fis2-ssl.mzstatic.com%2Fimage%2Fthumb%2FPurple124%2Fv4%2F07%2F54%2F61%2F0754611c-ff41-6f8a-1697-f9d9721097fb%2Fsource%2F512x512bb.jpg&q=0&b=1&p=0&a=1

**Comment by ririxidev** [comment]
.com is country restricted and redirects to polish site for me

**Comment by DarkVillager** [comment]
> .com domain is country restricted and redirects to polish site for me

It redirects me to the dutch site. So it just redirect you to your local site?

**Comment by Isa27-0** [comment]
> .com domain is country restricted and redirects to polish site for me

Worse than the .com is not restricted, I was able to access normally here in Brazil. But maybe the store only works in some countries: 
![Screenshot_20210531-101533_Opera.jpg](https://user-images.githubusercontent.com/68751594/120199058-311e0300-c1f9-11eb-9a2b-04f3dad81abc.jpg)

**Comment by ririxidev** [comment]
I just think veepee are contracted with other companies in other countries for example; In my country (in this example Poland) `veepee.com` redirects me to `zlotewyprzedaze.pl` that is not them for 100%, like it says under their rules:
`The users using the website at www.zlotewyprzedaze.pl are obliged to act in accordance with these Terms of Use and comply with the rules laid down herein. The website is administered by Złote Wyprzedaże S.A. with its registered office in Warsaw, at 9 Mołdawska Street, entered into the Register of Entrepreneurs kept by the District Court for the Capital City of Warsaw in Warsaw, 12th Commercial Department of the National Court Register under the KRS number 0000426614, with the share capital of PLN 2,035,146.20, holding tax identification number (NIP): 5213633950 (hereinafter referred to as "Złote Wyprzedaże"), which users may contact at the following email address: kontakt@zlotewyprzedaze.pl` so probs this presence would be kinda junky and would only work for some countries.
