### ISSUE TITLE
Improvements to Youtube Music images

### ISSUE THREAD

**Issue by LeptoFlare** [PreMiD/Presences#2840]
**Is your feature request related to a problem? Please describe.**
The current youtube music presence is pretty great, but there are still some differences between youtube music and spotify that can be adapted.

**Describe the solution you'd like**
Here is what the current Youtube Music image displays look like:
![image](https://user-images.githubusercontent.com/47790183/105088914-76237300-5a6a-11eb-99bf-474fdeb528c2.png)

The solution has 2 changes:
1. I would like for the main image to be the song cover art, similar to Spotify
![image](https://user-images.githubusercontent.com/47790183/105089275-e6ca8f80-5a6a-11eb-9ab2-3ce41aed93dc.png)

2. I would like for the corner image, rather than stating loop, to instead be the icon of Youtube Music, with the text on hover stating "Playlist on loop" etc.

**Comment by ririxidev** [comment]
Not possible due to discord rpc restrictionsm
