### ISSUE TITLE
Animeyabu and Hentaiyabu

### ISSUE THREAD

**Issue by ToukaON** [PreMiD/Presences#2841]
Prerequisites and essential questions. Required, please answer the following questions as honestly as possible by changing the "[ ]" to "[x]" or by marking it after creating the issue (easier), not marking a question counts as "NO"->
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

What's your Discord username? ->  .Touka#5252

What's the name of the service? -> animeyabu.com and hentaiyabu.com | Animeyabu and Hentaiyabu.

What should the Presence display? -> Anime/Hentai + Episodes.

If possible, please provide a logo for the service (512x512 minimum) ->Unfortunately I don't know how to get an image from the website.

**Comment by ririxidev** [comment]
one site per request.
