### ISSUE TITLE
di.fm

### ISSUE THREAD

**Issue by kenkit** [PreMiD/Presences#285]
**What's the name of the service?**
https://www.di.fm/

**What should the Presence display?**
Information about the currently playing song

**Why do you want support for this service?**
it's an online streaming service like spootify

**Are you able to provide an image for the service? (512x512 minimum)**
![Capture](https://djmp3.live/wp-content/uploads/2018/07/di-fm-02-2.png)

**Comment by callumok2004** [comment]
I have created a presence for the site, once the pull request is approved, you will be able to use it!

**Comment by kenkit** [comment]
Thank you, I received this message late.
