### ISSUE TITLE
Presence request Speedtest.net

### ISSUE THREAD

**Issue by Portee** [PreMiD/Presences#2851]
**Prerequisites and essential questions** 
- [x] Is it a popular site? 
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Chemar##0777

**What's the name of the service?** speedtest,net

**What should the Presence display?**  Internet speeds after a test, in particular download speed, upload speed and ms. 

**If possible, please provide a logo for the service (512x512 minimum)**  https://store-images.s-microsoft.com/image/apps.52586.13510798887693184.740d7baf-50aa-4e26-adec-ae739ac12068.c9ef9495-f245-4367-872b-c5cc7b48841d

**Comment by ririxidev** [comment]
Eh.... This presence will be no-sense. Closing this request
