### ISSUE TITLE
New York Times | newyorktimes.com

### ISSUE THREAD

**Issue by Vagabondit** [PreMiD/Presences#2852]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username? Vagabond.it#0005** 

**What's the name of the service?** New York Times | https://newyorktimes.com 

**What should the Presence display?** The presence should display how long you've been looking at something, the page or article you're looking at, and yeah that's it. If the dev thinks of more, it would be cool :) 

**If possible, please provide a logo for the service (512x512 minimum) Uhh I don't have a logo but it's easily findable, just look up New York Times on google. **

**Comment by PiggyPlex** [comment]
Assign Me

**Comment by Vagabondit** [comment]
how?

**Comment by NMW03** [comment]
Website link is wrong. New York Times' website is https://nytimes.com

**Comment by Vagabondit** [comment]
true! Thanks for noticing that

**Comment by EncryptedDev** [comment]
Presence has been added to the store - https://premid.app/store/presences/The%20New%20York%20Times

**Comment by Vagabondit** [comment]
Thank you  very much!
