### ISSUE TITLE
TheWatchCartoonOnline | thewatchcartoononline.tv

### ISSUE THREAD

**Issue by Raaghibm10** [PreMiD/Presences#2861]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** !.RAAGHIBM10#2834

**What's the name of the service?** www.thewatchcartoononline.tv | Online watch cartoon

**What should the Presence display?** the name of the anime show,the time it needs to be like the Netflix presence

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Raaghibm10** [comment]
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfLoGT0w3-ibYY2PJYMiq6_jO1yoQKsXjYQatqO7Vo5T7LcZvmmDyh9OQ&s=10

**Comment by Isa27-0** [comment]
Someone has already placed an order (#2454), this issue is duplicated

**Comment by ririxidev** [comment]
Gj github search
