### ISSUE TITLE
Animelon | animelon.com

### ISSUE THREAD

**Issue by knxfe** [PreMiD/Presences#2884]
**Prerequisites and essential questions**  Can you please add animelon.com to the presence store?
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  knxfe#0582

**What's the name of the service?**  https://animelon.com/

**What should the Presence display?**  The anime im watching and which episode im watching

**If possible, please provide a logo for the service (512x512 minimum)**  
![image](https://user-images.githubusercontent.com/71389473/106035530-e66e6c00-60dc-11eb-9198-40043af5312a.png)

**Comment by StrikerFRFX** [comment]
Sure I'll make this one. Adding to my TODO

**Comment by frankysetiawan** [comment]
It is currently not working as expected / broken.

**Steps to reproduce**
1. Download PreMid as instructed (Windows + Chrome plugin)
2. Download Animelon presence in Presence Store
3. It is not working. Whilst YouTube and Netflix presence are working as usual.

**Bench**
Chrome Version 114.0.5735.110 (Official Build) (32-bit)
PreMid v2.2.0
Windows 11
Discord latest version possible

**Test Videos**
https://animelon.com/video/5d3cf9c5a11bb231046310ab
https://animelon.com/video/57986e7c641f6457395b6b22
and all Animelon videos tried
