### ISSUE TITLE
can you add nulled.to/ 

### ISSUE THREAD

**Issue by Stairzzz** [PreMiD/Presences#2886]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [ ] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 

**What should the Presence display?** 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by StrikerFRFX** [comment]
You need to include the details of your discord username, the service name, what it should display and a logo.

**Comment by Stairzzz** [comment]
Stairz#5499

**Comment by Stairzzz** [comment]
![image](https://user-images.githubusercontent.com/78107615/106045546-c002fd80-60e9-11eb-8568-5323c193a33c.png)

**Comment by Stairzzz** [comment]
More stuff?

**Comment by Stairzzz** [comment]
?

**Comment by ririxidev** [comment]
do it in description.
