### ISSUE TITLE
nulled.to 

### ISSUE THREAD

**Issue by Stairzzz** [PreMiD/Presences#2888]
my discord - Stairz#5499
this is the logo - ![image](https://user-images.githubusercontent.com/78107615/106055299-db740580-60f5-11eb-9a61-908cc954187f.png)
![image](https://user-images.githubusercontent.com/78107615/106055175-b5e6fc00-60f5-11eb-8f3c-f6c82c44a9c2.png)
![image](https://user-images.githubusercontent.com/78107615/106055194-baabb000-60f5-11eb-92f4-346e3a4ca40d.png)
![image](https://user-images.githubusercontent.com/78107615/106055207-bed7cd80-60f5-11eb-9e0b-ad71f2ddf707.png)
![image](https://user-images.githubusercontent.com/78107615/106055213-c26b5480-60f5-11eb-9fbf-9ad8d49e4aee.png)
![image](https://user-images.githubusercontent.com/78107615/106055228-c7300880-60f5-11eb-9447-f13cffa904dc.png)
![image](https://user-images.githubusercontent.com/78107615/106055237-ca2af900-60f5-11eb-8ca6-c03cc21f7a3f.png)

**Comment by Stairzzz** [comment]
this is the site

**Comment by ririxidev** [comment]
Use service request template
