### ISSUE TITLE
Yummyanime don't work

### ISSUE THREAD

**Issue by MrLivixx** [PreMiD/Presences#2889]
**Describe the Bug**
PremID doesn't work on https://yummyanime.club
**Steps to Reproduce**
1. Go to https://yummyanime.club
2. Open any anime

**Expected Behavior**
There will be no presence in Discord and errors in js console

**Screenshots**
![image](https://user-images.githubusercontent.com/54632865/106055054-ec287980-60fd-11eb-8479-29338d84f672.png)

**Environment**
- OS: Windows 10
- Browser: Opera GX
- Version: LVL2 (core: 72.0.3815.487), PreMiD Extension version: 2.2.0.7, Program version: 2.1.4

**Additional context**

**Comment by StrikerFRFX** [comment]
Will PR a fix :) added to TODO
