### ISSUE TITLE
(Android) Messages | messages.google.com

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#2894]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Maxou#1909

**What's the name of the service?** 
(Android / Google) Messages | https://messages.google.com/ or https://messages.google.com/web

**What should the Presence display?** 
Same that Messenger

**If possible, please provide a logo for the service (512x512 minimum)** 
https://play-lh.googleusercontent.com/OY4rxeNTPaHwyOTZ-RUooqJvPnO5QUYmQcw0dhD90Mu6UWItOSZfQv7ks_FscbBow0M=s180-rw

**Comment by NMW03** [comment]
Doing this

**Comment by PiggyPlex** [comment]
Assign Me

**Comment by MaXfAa** [comment]
Already exists
