### ISSUE TITLE
VIU | viu.com

### ISSUE THREAD

**Issue by sogoodkart** [PreMiD/Presences#2898]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 

- [x] Is the site locked to a specific country/region?
This site is available in Hong Kong, India, Singapore, Malaysia, Thailand, Philippines, United Arab Emirates, Bahrain, Egypt, Indonesia, Jordan, Kuwait, Oman, Qatar, Saudi Arabia, Myanmar and South Africa

- [x] Is the site a paid service? (e.g. Netflix, Hulu)
premium account and free account

- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
www.viu.com | VIU

**What should the Presence display?** 
This site is about video streaming service I think it should be show like Youtube or Netflix (series or movie name and have time progess)

**If possible, please provide a logo for the service (512x512 minimum)** 

![viu](https://user-images.githubusercontent.com/78160355/107844728-a27fa480-6e08-11eb-822e-6a9b38b84675.png)

Thank you

**Comment by SlowLife1661** [comment]
Working on it, might take a while since I was busy 👍

**Comment by sogoodkart** [comment]
**Nice! Thanks for the presence** 👍 👍 
ขอบคุณที่ช่วยทำ presence ให้รวดเร็วมาก ๆ ครับ ขอบคุณครับ

깟Kart2#9999

**Comment by SlowLife1661** [comment]
ว้ายเจอคนไทยด้วย 😉

**Comment by sogoodkart** [comment]
Video player has been buffering many times while using the presence.
btw. the others presences are normally and have no this problem.
Should i open a new request issue for fix the bug or just leave a comment here?

ลองใช้มาสักพักแล้วรู้สึกว่ามันบัฟเฟอร์ค่อนข้างบ่อยเลยครับ พอปิด presence ปุ้ปคลิปเล่นได้ปกติ ไม่บัฟเฟอร์เลยเฉย
แจ้งแก้ไขในนี้ได้เลยไหมครับ หรือต้องไปเปิด issue ใหม่

**Comment by SlowLife1661** [comment]
Dm มาใน Discord ก็ได้
