### ISSUE TITLE
tcrf.net

### ISSUE THREAD

**Issue by 123321mario** [PreMiD/Presences#290]
What's the name of the service?
Ex. https://tcrf.net/ | The Cutting Room Floor

What should the Presence display?
The page and/or subpage name
OR
The game and the platform seen on the page

Why do you want support for this service?
It's a very interesting website showing unused and cut content in video games, it might be easy to grab the info for PreMiD because it's just a wiki and most info is in the URL.

Are you able to provide an image for the service? (512x512 minimum)
This is the official logo but it's 150x150 :
https://upload.wikimedia.org/wikipedia/en/d/d1/TCRFLogo.png
This is their twitter logo :
https://pbs.twimg.com/profile_images/666676666987474944/GghKPjuR.png

Thanks

**Comment by sunx2** [comment]
✨  Completed this presence. ✨ 
It can be found [Here in presence store](https://premid.app/store/presences/TCRF).

**Comment by frozaum** [comment]
#413
