### ISSUE TITLE
Office 365 | www.office365.com 

### ISSUE THREAD

**Issue by kyuti7** [PreMiD/Presences#2906]
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

The presence should display something similar to google docs, like if you are working in a specific word document, powerpoint, or excel document, it can be seen. The name of the document can be seen, how long you have been working on it, and which application in office 365 you are using (if possible). It can help when students are working on assignments and their teachers are on discord (online classes). 

www.office365.com

![Office-logo](https://user-images.githubusercontent.com/78059606/106340004-58be8800-6266-11eb-9203-b38c6100c830.jpg)

**Comment by ririxidev** [comment]
WebAssembly websites can't be done.
