### ISSUE TITLE
HiDive

### ISSUE THREAD

**Issue by jzqv** [PreMiD/Presences#2924]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**JonJon#6969 

**What's the name of the service?**HiDive 

**What should the Presence display?**The HiDive logo 

**If possible, please provide a logo for the service (512x512 minimum)** 
![hidive](https://user-images.githubusercontent.com/78390373/106533172-a681fd00-64bf-11eb-85f3-61b98572078d.jpg)

**Comment by Isa27-0** [comment]
It has already been requested (#33)

**Comment by ririxidev** [comment]
#3
