### ISSUE TITLE
Animes Online games Premid add

### ISSUE THREAD

**Issue by bloodzone09** [PreMiD/Presences#2927]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 

**What should the Presence display?** 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by ImRodry** [comment]
Please answer the questions properly

**Comment by Bas950** [comment]
Already a thing... https://premid.app/store/presences/Animes%20Online

**Comment by ImRodry** [comment]
The user mentioned to me that they wanted to use this presence on https://animesonline.games/ and it wasn't working so I assume it isn't the same thing and the suggestion is valid, however, they need to provide more detail clearly

**Comment by bloodzone09** [comment]
is not the same site

Bas950 <notifications@github.com> escreveu no dia terça, 2/02/2021 à(s)
15:30:

**Comment by ririxidev** [comment]
Service request is not fully completed.
