### ISSUE TITLE
gogoanime.bu presence request

### ISSUE THREAD

**Issue by sparky8287** [PreMiD/Presences#2945]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** gogoanime.bu 

**What should the Presence display?** same as gogoanime and it has English titles so people can actually understand what i am watching
![download](https://user-images.githubusercontent.com/78614624/107071604-f7b92600-680a-11eb-929f-8bd8ab14c299.jpg)
 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by ririxidev** [comment]
Already a thing. https://premid.app/store/presences/Gogoanime
