### ISSUE TITLE
Add Pronote en presence (FR)

### ISSUE THREAD

**Issue by Engip** [PreMiD/Presences#2947]
Hey 

Pronote est un site utiliser par tout les collégiens et lycéens de France.
Il permet de voir l'emploi du temps, le repas a la cantine le midi, nos absence justifier ou non
C'est pour cela qu'il est tres populaire et qu'il serais bien de le mettre en presence 

site: https://www.index-education.com/fr/logiciel-gestion-vie-scolaire.php

**Comment by ririxidev** [comment]
use feature request, and requests are only in english.
