### ISSUE TITLE
Add Pronote presense

### ISSUE THREAD

**Issue by Engip** [PreMiD/Presences#2949]
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [] Is the site locked to a specific country/region?
- [x] Is the site a paid service?
- [] Does the website feature NSFW content?
- [] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? 

**What's your Discord username?**  Engip#0935

**What's the name of the service?** Pronote (Index-education)

**What should the Presence display?**  The logo and the Presence name "Pronote"; why not an indication like "look at his schedule"

**If possible, please provide a logo for the service (512x512 minimum) ! **

![Logo pronote](https://user-images.githubusercontent.com/78657793/107126154-816dff80-68ae-11eb-99a3-0fb7c6c29173.png)

**Comment by ririxidev** [comment]
no link to site.
