### ISSUE TITLE
Google Docs

### ISSUE THREAD

**Issue by BlueDeadpool** [PreMiD/Presences#295]
**What's the name of the service?**
Google Docs

**What should the Presence display?**
Information about the document being worked on, time elapsed

Maybe allow people to toggle the name of the doc being shown for privacy reasons? Like, if they're working on a private document that they don't want the name being shown but the fact they are on docs being shown instead

**Why do you want support for this service?**
It'll be nice to let people know that I'm busy or working on something cool

**Are you able to provide an image for the service? (512x512 minimum)**
![pngguru com-id-bmyao](https://user-images.githubusercontent.com/16626098/66156337-6388ee80-e619-11e9-9d38-5f270af85dd5.png)

**Comment by callumok2004** [comment]
I have made a presence for google docs earlier today, including forms, sheets, slides and documents
