### ISSUE TITLE
SyncLounge | synclounge.tv

### ISSUE THREAD

**Issue by tzockt** [PreMiD/Presences#2953]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Darth Vader#4655

**What's the name of the service?** http://app.synclounge.tv/#/ | SyncLounge

**What should the Presence display?** the Movie or series Name, time and remaning time 

**If possible, please provide a logo for the service (512x512 minimum)** 
https://synclounge.tv/logo.png

**Comment by ririxidev** [comment]
provide logo

**Comment by tzockt** [comment]
Logo: https://synclounge.tv/logo.png
