### ISSUE TITLE
The Apple Music presence seems to be broken 

### ISSUE THREAD

**Issue by sarcasm-noise** [PreMiD/Presences#296]
**Describe the bug**
The presence for Apple Music seems to be completely broken on all browsers. I tried loading in music from beta.music.apple.com, and it never managed to display any information in my status whatsoever. 

**To Reproduce**
1. Make sure the PreMiD app and plugin are installed on any browser
2. Go to the Apple Music web player and try playing any song. Normally it should not show anything in your Discord status, at least not on my end.

**Expected behavior**
I expected the presence to behave like any other presence in the PreMiD store. It's a shame that it doesn't work as I use Apple Music much more than I ever use Spotify, and I'd love to show what I'm listening to in my Discord status.

**Screenshots**
![image](https://user-images.githubusercontent.com/48383618/66158258-d4ce9e80-e625-11e9-88c0-e73efb5307f2.png)
![image](https://user-images.githubusercontent.com/48383618/66158273-def09d00-e625-11e9-985b-8e7e6f027af2.png)
As seen in the second image, there is nothing showing up as the status. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 1903
 - Browser: Chrome (though this should be possible on Firefox and Opera as well)
 - Version: Plugin version is 1.0, PreMiD version is 2.0

**Comment by RisingChops** [comment]
Thank you for the report! I've fixed the issue,the changes just need to be accepted.
