### ISSUE TITLE
Vider | vider.info

### ISSUE THREAD

**Issue by d6mian** [PreMiD/Presences#2966]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  -

**What's the name of the service?**  https://vider.info/

**What should the Presence display?**  Title, Episode, and timestamp

**If possible, please provide a logo for the service (512x512 minimum)**  https://vider.info/static/img/favicon/apple-touch-icon-72_1.png

**Comment by NMW03** [comment]
Website isn't working for me
