### ISSUE TITLE
musescore.com

### ISSUE THREAD

**Issue by 123321mario** [PreMiD/Presences#297]
**What's the name of the service?**
https://musescore.com/ | MuseScore Sheet Music

**What should the Presence display?**
Name of the score + artist / profiles / clubs

**Why do you want support for this service?**
MuseScore is a big network for sharing sheet music between musicians and enthusiasts. It can be nice to share this passion with others on Discord!

**Are you able to provide an image for the service? (512x512 minimum)**
https://s3.amazonaws.com/s.musescore.org/about/images/design_MU3/musescore_sticker+11%403x.png

**Comment by OfficialCRUGG** [comment]
Will do later today or tomorrow!

**Comment by CobyPowers** [comment]
#341 It has been added.
