### ISSUE TITLE
alltheflavors.com

### ISSUE THREAD

**Issue by Hexical1** [PreMiD/Presences#298]
**What's the name of the service?**
https://alltheflavors.com | AllTheFlavors

**What should the Presence display?**
Current Recipe
Current Flavour
Current Search

**Why do you want support for this service?**
Its widely used by a lot of DIY e-Juice makers and is a helpful website. It would help a lot of others display recipes they are currently browsing and definitely bring more discussions about flavours and recipes in the DIY e juice discord, and others possibly

**Are you able to provide an image for the service? (512x512 minimum)**
https://imgur.com/a/c3Amqof

**Comment by sunx2** [comment]
Added All The Flavors presence .  [Presence Store Link](https://premid.app/store/presences/All%20The%20Flavors)

**Comment by doomlerd** [comment]
@sunx2 thank you.
