### ISSUE TITLE
Keybr | Keybr.com

### ISSUE THREAD

**Issue by Suhalb** [PreMiD/Presences#2996]
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Mashallah#0868

**What's the name of the service?** www.keybr.com | Keybr

**What should the Presence display?** WPM, Accuracy, Idle, Typing.

**If possible, please provide a logo for the service (512x512 minimum)** Cannot find one.

**Comment by ririxidev** [comment]
It's fine that you didn't find logo! We hope that if someone will want to do this, will get some cool logo 😎

**Comment by PiggyPlex** [comment]
Assign me

**Comment by PiggyPlex** [comment]
Implemented ref #3090
