### ISSUE TITLE
play.google.com

### ISSUE THREAD

**Issue by AlekEagleYT** [PreMiD/Presences#30]
**What's the name of the service?**
https://play.google.com/music/listen | Google Play Music

**What should the Presence display?**
Song, Album, Playing State

**Why do you want support for this service?**
Google Play Music is one of the biggest music platforms and is one of the few platforms that allow you to upload your own music to be accessible on many devices, it supplies high-quality audio and is directly related to Google Play and its sub-services.

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image
https://alekeagle.tk/screenshots/VCvaMeauvf.png

**Comment by theLMGN** [comment]
SVG Logo:
![GPM Logo SVG](http://lmgn.uk/xGc.svg)
http://lmgn.uk/xGc.svg
