### ISSUE TITLE
Add Metastream - Alternative for Rabbit

### ISSUE THREAD

**Issue by maz1no** [PreMiD/Presences#300]
**What's the name of the service?**
https://getmetastream.com | Metastream

**What should the Presence display?**
Surely informations about the current video. What was Rabbit like.

**Why do you want support for this service?**
Metastream is our alternative pick for Rabbit because Rabbit is dead. It haves superior live synchronization playback. It uses its proprietary technology to bring enhanced live streaming to multiple people and with almost zero latency. Besides that, Metastream looks absolutely great with on-screen chat, video queuing, and quick user management. Further, it supports all major streaming services like Netflix, YouTube, Prime Video, etc. Having said that, it does not have popular Rabbit features like streaming downloaded media, webcam, and audio support. If you can live with that, Metastream is an awesome choice for streaming watch parties.

**Are you able to provide an image for the service? (512x512 minimum)**
![logo](https://user-images.githubusercontent.com/38970314/66182957-538b0200-e64d-11e9-924b-57c237cac4f3.png)

**Comment by CobyPowers** [comment]
#357 Added :)

**Comment by maz1no** [comment]
> #357 Added :)

Ty!
