### ISSUE TITLE
Linkvertise Presence

### ISSUE THREAD

**Issue by SentexYT** [PreMiD/Presences#3003]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**Sentex#0001** 

**https://linkvertise.com/ and https://publisher.linkvertise.com** 

**If someone is viewing his Dashboard and if someone is creating a link (which one he is creating if it is possible)** 

**https://linkvertise.com/assets/img/final-Logo.png (512x512 minimum)**

**Comment by ririxidev** [comment]
Unfortunately, this site has nothing to offer. Sorry for that!
