### ISSUE TITLE
LucaModzZ Website

### ISSUE THREAD

**Issue by SentexYT** [PreMiD/Presences#3004]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**Sentex#0001** 

**LucaModzZ GTA V Modding Website** 

**If someone is viewing the Website and which Tab he is viewing (GTA, CSGO, SHOP etc.)** 

**![unnamed](https://user-images.githubusercontent.com/70211174/107865723-e951b680-6e69-11eb-84f1-2345989c2d27.jpg)** ]

**Comment by ririxidev** [comment]
Unfortunately, this site has nothing big to offer. Sorry for that 😞 (~~Anyway, we don't wanna pay TakeTwo for "supporting" this site~~)
