### ISSUE TITLE
animenewsnetwork.com

### ISSUE THREAD

**Issue by maz1no** [PreMiD/Presences#301]
**What's the name of the service?**
Ex. https://www.animenewsnetwork.com/ | AnimeNewsNetwork

**What should the Presence display?**
Informations about the current page

**Why do you want support for this service?**
Anime News Network was created as a news source that focuses on the medium of Japanese Animation(anime) and Japanese Comics (manga). ANN was founded in July of 1998, and has since lead the online anime news medium with a tradition of strong unbiased coverage of major breaking news. With in-depth coverage, analysis and commentary to provide insight into the world of anime and manga, ANN has been and continues to be the #1 English language source for anime and manga news on the Internet. ANN's goal is to make the latest, most comprehensive Anime news available to new fans and veteran Otaku alike.

**Are you able to provide an image for the service? (512x512 minimum)**
![ANN_Logo_dots_512x512](https://user-images.githubusercontent.com/38970314/66183238-75d14f80-e64e-11e9-9409-f2ca1bbd3d0b.png)

**Comment by sunx2** [comment]
can i do this?

**Comment by sunx2** [comment]
doing it rn 😄

**Comment by sunx2** [comment]
Added [Anime News Network ](https://premid.app/store/presences/Anime%20News%20Network)   on presence store.
If  i missed any presence do let me know.

![image](https://user-images.githubusercontent.com/24259556/66513276-5d52b080-eaf8-11e9-9ed5-6bb64fe2e914.png)

**Comment by maz1no** [comment]
Thank you @sunx2! I aprecciate **a lot**.

As you requested, i noticed that interviews page presence are missing. And thank you again for the good work :)

**Comment by frozaum** [comment]
#422
