### ISSUE TITLE
Vostfree | vostfree.com

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#3021]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Maxou#1909

**What's the name of the service?** 
https://vostfree.com/ | Vostfree

**What should the Presence display?** 
Same that ADN (AnimeDigitalNetwork)

**If possible, please provide a logo for the service (512x512 minimum)** 
https://vostfree.com/templates/Animix/images/favicon.ico
Could not find better, sorry

**Comment by ririxidev** [comment]
Logo is okay! At least we should hope that developer that will do that, will make it better 😎
