### ISSUE TITLE
MediaFire | www.mediafire.com

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#3022]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
     * Has a PRO subscription
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
MediaFire: https://www.mediafire.com

> MediaFire is a file hosting, file synchronization, and cloud storage service based in Shenandoah, Texas, United States. Founded in June 2006 by Derek Labian and Tom Langridge, the company provides client software for Microsoft Windows, macOS, Linux, Android, iOS, BlackBerry 10, and web browsers. MediaFire has 43 million registered users and attracted 1.3 billion unique visitors to its domain in 2012.

**What should the Presence display?** 
It works similarly to the presence of MEGA, Google Drive among others for cloud storage and file sharing, then the presence can be similar to these.

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/68751594/107965227-0cbf5300-6f89-11eb-895f-01550ba1f8bb.png)

**Comment by DarkVillager** [comment]
Add the label **Presence Request** & Add your discord so someone can contact you.

**Comment by DarkVillager** [comment]
I will try my best to make a good presence for this website.
