### ISSUE TITLE
Spotify Podcasts

### ISSUE THREAD

**Issue by tealyt** [PreMiD/Presences#3027]
**Describe the Bug**

It literally just doesn't work
**Steps to Reproduce**

1. Just try to use it

**Expected Behavior**

It doesn't show
**Screenshots**

**Environment**

- OS: MacOS
- Browser: Chrome
- Version: 88.0.4324.96 (64-Bit)
  

**Additional context**

**Comment by tealyt** [comment]
I removed it and now none of the other Presences are working wtf...

**Comment by ririxidev** [comment]
Could you, provide more information about it? Thank you! 😄 If you want you can talk to one of our Support Agents at our Discord Server that is available from [this address](https://discord.premid.app)!
