### ISSUE TITLE
Manga-TR | manga-tr.com

### ISSUE THREAD

**Issue by nicotinexgucci** [PreMiD/Presences#3037]
**Prerequisites and essential questions** 
- [x] Is the website older than 2 months? 
- [x] Is it a popular site?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

мой никотин#1952

www.manga-tr.com

Manga-TR is a website for people to watch animes, so you need to show what episode of the anime people are watching and show the timestamps of what the episode.

If possible, please provide a logo for the service (512x512 minimum)
![logo_512x512](https://user-images.githubusercontent.com/78096621/108357941-27026680-71ff-11eb-9e9e-490a545daf23.png)

**Comment by eggsy** [comment]
I tried my luck but the website isn't well-designed in my opinion. It doesn't include any prefix for categories, mangas nor animes. Everything is under the `/ ` route which makes it so hard to distinguish all those pages from each other. I will not try making this again. Hopefull, someone else will join.
