### ISSUE TITLE
Kijk | kijk.nl

### ISSUE THREAD

**Issue by alltimemarr** [PreMiD/Presences#3047]
**Prerequisites and essential questions**
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [x] Is the site locked to a specific country/region? [I don't know if it's geo-blocked for sure, but I assume it is. It's a Dutch website)
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) (yes and no, there's free content and after certain amount of days they are only viewable with a subscription. Some older stuff is just free to watch. Much like NPO Start (free version), NPO Plus (paid version/RTL XL (paid and free) in the Netherlands, and it would be cool if those could be added too! Same answers apply.)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** lifeiscrazy『marr』#3604

**What's the name of the service?** https://kijk.nl

**What should the Presence display?** Like with Netflix. The movie or series name, episode number, remaining time

**If possible, please provide a logo for the service (512x512 minimum)**

![62602514](https://user-images.githubusercontent.com/12399392/108548263-e3d1f180-72eb-11eb-81ce-95994e6ab3f7.png)
SVG logo link: https://images.ctfassets.net/0w1d9hjfek5f/3FZroCvgcgYMGmaImuIKEK/356ce7a5b35fc83431a75155bb358693/brand-kijk2.0.svg

**Comment by DarkVillager** [comment]
Assing me this one chief!
