### ISSUE TITLE
just dance now

### ISSUE THREAD

**Issue by coolax1337** [PreMiD/Presences#3070]
**Prerequisites and essential questions** 
- [x] Is it a popular site?  
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ x] Is the site a paid service? (e.g. Netflix, Hulu)    < not at all >
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ x] Are you a donator/patron? 
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
https://justdancenow.com/

**What should the Presence display?**  icon, game : just dance now and current song (time 00:00)

**If possible, please provide a logo for the service (512x512 minimum)** 
https://ubistatic19-a.akamaihd.net/ubicomstatic/en-us/global/buy-now/jdnow_boxshot_mobile_177287.png

**Comment by ririxidev** [comment]
blep #1001
