### ISSUE TITLE
Jetanimes | jetanimes.com

### ISSUE THREAD

**Issue by YuiKozFR** [PreMiD/Presences#308]
**What's the name of the service?**
Jetanimes
https://www.jetanimes.com

**What should the Presence display?**
anime, episode and time remaining

**Why do you want support for this service?**
Jetanimes is a french website with all animes and the new anime, it's the biggest anime website in streaming

**Are you able to provide an image for the service? (512x512 minimum)**
![ezgif-1-7b955994a124](https://user-images.githubusercontent.com/38916609/66233554-f5612c00-e6eb-11e9-9801-e36e7b9a7671.png)

**Comment by eggsywashere** [comment]
Hey @YuiKozFR, can you provide me the French of these strings so I can use them since it's a French service:
"Homepage"
"Viewing a page:"
"Searching for:"
"Viewing an actor:"
"Searching animes with genre:"
"Viewing a serie:"
I don't want to use translate, I want to be 100% sure about they're right.

**Comment by doomlerd** [comment]
hehe

**Comment by eggsywashere** [comment]
Well you know I get mails right? @doomlerd :^)

![image](https://user-images.githubusercontent.com/13917975/71450406-4e33e400-2772-11ea-9095-93edeaa05eb1.png)

**Comment by doomlerd** [comment]
OOPSIE
