### ISSUE TITLE
pornhub.com

### ISSUE THREAD

**Issue by xenforq** [PreMiD/Presences#31]
What's the name of the service?
PornHub

What should the Presence display?
Information about the current video playing, maybe who posted it too.

Why do you want support for this service?
I think we all know what it is.

Are you able to provide an image for the service? (512x512 minimum)
![logo](https://user-images.githubusercontent.com/32591110/50736493-9010f680-11be-11e9-9831-7e4e6e664ee9.jpg)

**Comment by frozaum** [comment]
**AND DONE**
https://beta.premid.app/store/PornHub

**Comment by TheDropX** [comment]
Presence done.
