### ISSUE TITLE
Tweetdeck.twitter.com

### ISSUE THREAD

**Issue by barbiehunter** [PreMiD/Presences#310]
**What's the name of the service?**
https://tweetdeck.twitter.com/

**What should the Presence display?**
-How many Columnn you have
-Add just a text like "Read tweets"  "Relax on twitter"
-idk

**Why do you want support for this service?**
Because there is also a twitter rich presence, one for tweetdeck would also be well appropriate in my opinion.

**Are you able to provide an image for the service? (512x512 minimum)**
![image](https://user-images.githubusercontent.com/38357837/66241329-21d27380-e6ff-11e9-8de2-b11764106d36.png)

**Comment by CobyPowers** [comment]
Added TweetDeck to the Twitter presence.
