### ISSUE TITLE
WorldHideAway | worldhideaway.com

### ISSUE THREAD

**Issue by srjoelgamer** [PreMiD/Presences#3101]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
srjoel#0251

**What's the name of the service?** 
www.worldhideaway.com

**What should the Presence display?** 
The different sections of web (Guides section, news, home)

**If possible, please provide a logo for the service (512x512 minimum)** 
![Sin título-1_Mesa de trabajo 1](https://user-images.githubusercontent.com/79596909/109039462-d37a9780-769a-11eb-999c-058065829ca2.png)

**Comment by DarkVillager** [comment]
assign me this one chief
