### ISSUE TITLE
AsianCrush | asiancrush.com

### ISSUE THREAD

**Issue by noahlovescats** [PreMiD/Presences#3104]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Noah#4986

**What's the name of the service?** 
www.asiancrush.com | AsianCrush

**What should the Presence display?** 
Similar to what other presences for other streaming services display, such as the Netflix presence, Hulu presence, etc.

**If possible, please provide a logo for the service (512x512 minimum)** 
![41REfTyH1aL](https://user-images.githubusercontent.com/79289128/109082220-24a18000-76c9-11eb-849e-e5f54324cde7.png)

**Comment by SlowLife1661** [comment]
Website is still in progress it seems

**Comment by noahlovescats** [comment]
> Website is still in progress it seems, - would be fine if there will be no breaking change anytime soon

Ah, alright.

**Comment by SlowLife1661** [comment]
Also site is locked to a specific country/region.

**Comment by ririxidev** [comment]
> Website is still in progress it seems, - would be fine if there will be no breaking change anytime soon
