### ISSUE TITLE
Midnight Pulp | midnightpulp.com

### ISSUE THREAD

**Issue by noahlovescats** [PreMiD/Presences#3105]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Noah#4986

**What's the name of the service?** 
www.midnightpulp.com | Midnight Pulp

**What should the Presence display?** 
Similar to what other presences for other streaming services display, such as the Netflix presence, Hulu presence, etc.

**If possible, please provide a logo for the service (512x512 minimum)** 
![61EDBjJevYL](https://user-images.githubusercontent.com/79289128/109081557-1d2da700-76c8-11eb-915c-14848b1f54fc.png)

**Comment by SlowLife1661** [comment]
Site is locked to specific county/region.

**Comment by ririxidev** [comment]
> Website is still in progress.
