### ISSUE TITLE
Crackle | crackle.com

### ISSUE THREAD

**Issue by n-oah** [PreMiD/Presences#3107]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Noah#4986

**What's the name of the service?** 
www.crackle.com | Crackle

**What should the Presence display?** 
Similar to what other presences for other streaming services display, such as the Netflix presence, Hulu presence, etc.

**If possible, please provide a logo for the service (512x512 minimum)** 
![crackle-logo-512x512](https://user-images.githubusercontent.com/79289128/109082735-23248780-76ca-11eb-8c01-9c969a122d78.png)

**Comment by SlowLife1661** [comment]
Site is locked to a specific country/region.
