### ISSUE TITLE
Smodin | smodin.me

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#3111]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Maxou#1909

**What's the name of the service?** 
https://smodin.me | Smodin
Smodin is a site offering different service including text rewriting service. This service is available in 48 languages and has already rewritten more than 477,000 characters. (48 languages on the site but more than 100 languages are supported via the API).
https://smodin.me/free-english-rewriter-and-spinner

**What should the Presence display?** 
1. Smodin
2. Th service (Rewrite or other)
3. Time

**If possible, please provide a logo for the service (512x512 minimum)** 

![télécharger](https://user-images.githubusercontent.com/71935156/109143876-ccb65800-7760-11eb-90ed-8e2f830b973b.png)

**Comment by SlowLife1661** [comment]
*The logo is just too big*

**Comment by ririxidev** [comment]
This website is not known tbh, so don't mislead.
