### ISSUE TITLE
Waze | waze.com

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#3116]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Maxou#1909

**What's the name of the service?** 
https://www.waze.com | Waze
(livemap)

**What should the Presence display?** 
Example for the livemap :
1. Waze
2. Planning a route
3. From [city] to [city]
4. Time elapsed

**If possible, please provide a logo for the service (512x512 minimum)** 

https://play-lh.googleusercontent.com/r7XL36PVNtnidqy6ikRiW1AHEIsjhePrZ8W5M4cNTQy5ViF3-lIDY47hpvxc84kJ7lw=s180-rw

**Comment by ririxidev** [comment]
only livemap*
