### ISSUE TITLE
Google Store | store.google.com

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#3123]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Maxou#1909

**What's the name of the service?** 
https://store.google.com | Google Store

**What should the Presence display?** 
Example :
1. Google Store
2. Browse a category
3. Connected home

**If possible, please provide a logo for the service (512x512 minimum)** 

Same that Google
https://pbs.twimg.com/profile_images/781203065454022674/DghC5a3s_400x400.jpg

**Comment by ririxidev** [comment]
eh... not really worth.
