### ISSUE TITLE
Google About | about.google & Sustainability

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#3125]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Maxou#1909

**What's the name of the service?** 
https://about.google | Google - About
**It would be nice if this presence also supports Google Sustainability.** :
https://sustainability.google | Google Sustainabilty

**What should the Presence display?** 
Example :
1. Google About
2. Read an article
3. How, with the help of Google Maps, a bicycle bookseller delivers his customers to their delight.
or
1. Google Sustainabality
2. Progress page
3. Carbon free energy

**If possible, please provide a logo for the service (512x512 minimum)** 
For Google About, it's the same logo as Google

Sustainability : (the logo is beautiful)
https://sustainability.google/static/images/GoogleG-GLeaf_%402x-noloop.gif

**Comment by PiggyPlex** [comment]
Assign me

**Comment by MaXfAa** [comment]
> Assign me

Thanks ! 🥳

**Comment by PiggyPlex** [comment]
Still active; do not unassign

**Comment by PiggyPlex** [comment]
Implement in #3576

**Comment by ririxidev** [comment]
Issue of being it closed is in linked pull request.
