### ISSUE TITLE
PayPal | paypal.com

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#3130]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Maxou#1909

**What's the name of the service?** 
https://paypal.com | PayPal
Also https://paypal.me

**What should the Presence display?** 
1. Paypal
2. On the supply source page
3. Manage her cards

**If possible, please provide a logo for the service (512x512 minimum)** 

https://play-lh.googleusercontent.com/Y2_nyEd0zJftXnlhQrWoweEvAy4RzbpDah_65JGQDKo9zCcBxHVpajYgXWFZcXdKS_o=s180-rw

**Comment by ririxidev** [comment]
Too many risk info and no.

**Comment by MaXfAa** [comment]
> Too many risk info and no.

Ok 😢😅
