### ISSUE TITLE
ADKami | adkami.com

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#3136]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Maxou#1909

**What's the name of the service?** 
https://www.adkami.com | ADKami

**What should the Presence display?** 
Same that Crunchyroll

**If possible, please provide a logo for the service (512x512 minimum)** 

https://www.adkami.com/image/xsprit.png,q8.pagespeed.ic._hcQgMFK74.png
![Capture web_27-2-2021_211818_www adkami com](https://user-images.githubusercontent.com/71935156/109399223-d6e37c80-7941-11eb-8dc1-eedc51572d13.jpeg)

**Comment by Venipa** [comment]
- [x] contains paid services (premium streams and delayed free streams)
