### ISSUE TITLE
Anime Planet | anime-planet.com

### ISSUE THREAD

**Issue by noahlovescats** [PreMiD/Presences#3138]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Noah#4986

**What's the name of the service?** 
www.anime-planet.com | Anime Planet

**What should the Presence display?** 
Anime Planet allows users to watch anime through its website via anime streaming services such as Crunchyroll and HIDIVE, so it if it could display watching anime like those services, that would be great. Anime Planet also allows users to rate anime, and put anime on "currently watching," "wanting to watch," "dropped," lists, similar to MyAnimeList and Anilist, so it should display similar to what the presences for those websites display.

**If possible, please provide a logo for the service (512x512 minimum)** 
![DzJ9UFDUwAAKj9C](https://user-images.githubusercontent.com/79289128/109400437-55bec200-790e-11eb-97f6-af5b969d18ce.jpg)

**Comment by SlowLife1661** [comment]
*Working on it*
