### ISSUE TITLE
Google Classroom | classroom.google.com

### ISSUE THREAD

**Issue by retapic** [PreMiD/Presences#3146]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**
account/retapic/#5890

**What's the name of the service?**
[Google Classroom](https://premid.app/store/presences/Google%20Classroom)

**What should the Presence display?** 
Ability to enable "Privacy" mode, [as in the presence of "YouTube"](https://i.imgur.com/UZnsUyP.jpg)

**Comment by MaXfAa** [comment]
Already exist :
https://premid.app/store/presences/Google%20Classroom

**Comment by retapic** [comment]
> Already exist

ofc. I just pointed out the link to the presence.
I suggested making an option in this presence.

**Comment by SlowLife1661** [comment]
Use feature request template.

**Comment by ririxidev** [comment]
Like @SlowLife1661 said.
