### ISSUE TITLE
Reverso | reverso.net

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#3153]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Maxou#1909

**What's the name of the service?** 
https://www.reverso.net | Reverso

**What should the Presence display?** 
Same that Google Translate.
The presence will have to supported; translation, proofreader, synonyms, conjugations as well as the other tools of Reverso.

**If possible, please provide a logo for the service (512x512 minimum)** 

https://play-lh.googleusercontent.com/YOiP93_wcINsl8rNvC4hlBuAn_MeeO5DK5xd70DatbJgVGDlCH2I4U4HyH8GEhV1xIXm=s180-rw

**Comment by llacb47** [comment]
Since you can't seem to read "512x512 minimum":

https://play-lh.googleusercontent.com/YOiP93_wcINsl8rNvC4hlBuAn_MeeO5DK5xd70DatbJgVGDlCH2I4U4HyH8GEhV1xIXm=s0?imgmax=0

**Comment by MaXfAa** [comment]
> Since you can't seem to read "512x512 minimum":
> 

Thank you, but the next time you address me, do it more politely.

**Comment by llacb47** [comment]
Sir yes sir

**Comment by PiggyPlex** [comment]
Assign me?

**Comment by PiggyPlex** [comment]
Implement in #3576
