### ISSUE TITLE
[Presence | Bug] ProBot 

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#3155]
**Describe the Bug**

At me, the presence shows nothing.

**Expected Behavior**

Despite several Ctrl + R in Discord and other things, the presence does not display anything.

**Environment**

- OS: Windows 10
- Browser: Edge
- Version: 88.0.705.81 (Version officielle) (64 bits)

**Additional context**

PreMiD ; v2.2.0
Extension : v2.2.3 (from Microsoft Edge Addons)

**Comment by EncryptedDev** [comment]
I've tried to reproduce this issue and cannot reproduce. Note, from browsing the code, viewing the homepage isn't suppose to display anything, but all the other paths do display presence data. 
If it still doesn't work after that, please provide me the link of the page which isn't working and I can see if I can reproduce the issue.

**Comment by MaXfAa** [comment]
> I've tried to reproduce this issue and cannot reproduce. Note, from browsing the code, viewing the homepage isn't suppose to display anything, but all the other paths do display presence data.
> If it still doesn't work after that, please provide me the link of the page which isn't working and I can see if I can reproduce the issue.

No this is not the home page. That's all. And the page I visited is "Auto Reply" on one of my servers.
https://www.probot.io/server/801467663418523650/auto_responder

**Comment by EncryptedDev** [comment]
Yeah, dodgy code. I'll add this on my to do list; bare with me, thanks

**Comment by ririxidev** [comment]
@DarkVillager maybe wanna do it someday?

**Comment by DarkVillager** [comment]
> @DarkVillager maybe wanna do it someday?

I'm currently taken into a mental hospital but will do it when I can.
