### ISSUE TITLE
[Feature Request | Presence] YouTube

### ISSUE THREAD

**Issue by hwalker928** [PreMiD/Presences#3157]
**Is your feature request related to a problem? Please describe.**
When watching an unlisted YouTube video, the button to watch the video is still present on your status - causing a private video to become public to whoever sees your status.

**Describe the solution you'd like**
The button(s) to be removed if the video is unlisted.

**Describe alternatives you've considered**
Disabling all buttons, but I would still like public videos to show.

**Additional context**
None.

**Comment by callumok2004** [comment]
![sexy image](https://i.callumdev.pw/pq2mq.png)

**Comment by callumok2004** [comment]
temporary solution ^

**Comment by hwalker928** [comment]
> 
> 
> temporary solution ^

I have already done that in the meantime.
Describe alternatives you've considered
> Disabling all buttons, but I would still like public videos to show.
