### ISSUE TITLE
Gogo Anime new domain closed recently !!!!

### ISSUE THREAD

**Issue by prorounak2005** [PreMiD/Presences#3167]
**Prerequisites and essential questions** 
- [x] Is it a popular site? Yes 
- [x] Is the website older than 2 months?  yes
- [x] Is the site locked to a specific country/region? no 
- [x] Is the site a paid service? (e.g. Netflix, Hulu) no 
- [x] Does the website feature NSFW content? (e.g. porn, etc...) no 
- [x] Are you a donator/patron? no 
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? yes 

**What's your Discord username?**  Mr Disguised#9944

**What's the name of the service?**  https://gogoanime.ai/

**What should the Presence display?**  When Browsing website - [Browsing] { gogoanime home page } and when watching anime - [ Watching ] {Anime Name }

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/69617708/109940453-19b5a380-7cf8-11eb-84af-e900750e6e60.png)

**Comment by prorounak2005** [comment]
The recent website of gogoanime - https://www2.gogoanime.sh which was already in premid store was closed recently due to server problems and some other reasons so please add the new website link- https://gogoanime.ai/ in premid store and remove the old one as the old link https://www2.gogoanime.sh redirects us to https://gogoanime.ai/    .           - THANK YOU

**Comment by SlowLife1661** [comment]
#3166
