### ISSUE TITLE
Regarding New Gogoanime New Website Request 

### ISSUE THREAD

**Issue by prorounak2005** [PreMiD/Presences#3168]
**Prerequisites and essential questions** 
- [x] Is it a popular site? yes 
- [x] Is the website older than 2 months?  tes
- [x] Is the site locked to a specific country/region? no 
- [x] Is the site a paid service? (e.g. Netflix, Hulu) no 
- [x] Does the website feature NSFW content? (e.g. porn, etc...) no 
- [x] Are you a donator/patron? no 
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? yes 

**What's your Discord username?**  Mr Disguised#9944

**What's the name of the service?**  https://gogoanime.news/

**What should the Presence display?**  When on homepage {Viewing gogoanime new } and when on particular new {Viewing News } [ News Name ] 

**If possible, please provide a logo for the service (512x512 minimum)**  
![image](https://user-images.githubusercontent.com/69617708/109942512-47035100-7cfa-11eb-88a7-bac9db63cee8.png)

**Comment by prorounak2005** [comment]
This will be the new gogo anime website for new and Important annoucement along with other two websites - https://gogoanime.ai/ and https://gogoanime.vc/ and another issue has also been created regarding the new website https://gogoanime.ai/ which should be replaced with the old website  https;//www2.gogoanime.sh . Please Kindly look to it . 

ISSUE REGARDING THE NEW WEBSITE - https://github.com/PreMiD/Presences/issues/3167                                                                                        
                                                                                                                                                                                   -THANK YOU

**Comment by SlowLife1661** [comment]
#3166 <
