### ISSUE TITLE
idk what to say, I'm requesting to add http://themostseconds.com/ 

### ISSUE THREAD

**Issue by jujehkkokko** [PreMiD/Presences#3170]
**Prerequisites and essential questions** 
- [no] Is it a popular site?
- [yes] Is the website older than 2 months? 
- [no] Is the site locked to a specific country/region?
- [no] Is the site a paid service? (e.g. Netflix, Hulu)
- [no] Does the website feature NSFW content? (e.g. porn, etc...)
- [no] Are you a donator/patron?
- [yes] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
jujeh#1444
**What's the name of the service?** 
http://themostseconds.com/
**What should the Presence display?** 
the number of seconds you have wasted, that's all the website do, it counts the seconds you've been on the website for :v
**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by ririxidev** [comment]
Do it again how it should be.
