### ISSUE TITLE
Glimesh | glimesh.tv

### ISSUE THREAD

**Issue by DigiZTV** [PreMiD/Presences#3173]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service?
- [ ] Does the website feature NSFW content?
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** DigiZ#1591

**What's the name of the service?** Glimesh - https://glimesh.tv

**What should the Presence display?** Who you are watching at the moment similar to twitch and possibly when you are streaming to display that.

**If possible, please provide a logo for the service (512x512 minimum)** 
![Glimesh](https://user-images.githubusercontent.com/80080429/110056852-872ff700-7d2d-11eb-9389-21cf22021927.png)

**Comment by SlowLife1661** [comment]
Please use the check list correctly.

**Comment by DigiZTV** [comment]
> Please use the check list correctly.

Sorry tbh this is my first time doing this, I think I've resolved the issue tho

**Comment by SlowLife1661** [comment]
Site's work in progess

**Comment by ririxidev** [comment]
@SlowLife1661 it's functional tho xD

**Comment by ItzNathaniel** [comment]
Currently working on this. Will create a submission when done. It's almost done.

**Comment by ItzNxthaniel** [comment]
Presences Added,
https://github.com/PreMiD/Presences/pull/3451

Issue can be closed.
