### ISSUE TITLE
[Bug | Presence] Genius

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#3185]
**Describe the Bug**

No details are displayed with the Genius presence.

**Expected Behavior**

Normally, details should be displayed (e.g.; what lyrics I'm looking at etc...).

**Screenshots**

https://media.discordapp.net/attachments/815922844990177331/817722969420988436/unknown.png

**Environment**

- OS: Windows 10
- Browser: Edge **(<- I think it's related)**
- Version:  89.0.774.45 (Official build) (64-bit)

**Additional context**

I tested several things like : change the language of the presence, change the language of my computer, change DNS but nothing happens.

---
PreMiD ; v2.2.0
Extension : v2.2.3 (from Microsoft Edge Addons)

**Comment by StrikerFRFX** [comment]
Show a screenshot of the page you visited and the link.

**Comment by MaXfAa** [comment]
> Show a screenshot of the page you visited and the link.

![image](https://user-images.githubusercontent.com/71935156/110354641-a930be80-8038-11eb-99c2-445db6db7de3.png)

https://genius.com/Lil-mosey-blueberry-faygo-lyrics

**Comment by mlunax** [comment]
I am taking this.
