### ISSUE TITLE
Friday Night Funkin | ninja-muffin24.itch.io/funkin

### ISSUE THREAD

**Issue by Sudo-sudo-commits-brokencommands** [PreMiD/Presences#3195]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  user is rio#5133

**What's the name of the service? **  https://ninja-muffin24.itch.io/funkin
**What should the Presence display?**  friday night funkin

**If possible, please provide a logo for the service (512x512 minimum)**  
![friday-night-funkin-1](https://user-images.githubusercontent.com/80180013/110231056-49b4a080-7eca-11eb-989c-c42a5b40ce2a.jpeg)

**Comment by EncryptedDev** [comment]
What do you want the presence to display exactly? You're extremely vague by saying: 
> What should the Presence display? friday night funkin

**Comment by Isa27-0** [comment]
But the site is from the Itch.io platform, and it already has a presence for it: https://premid.app/store/presences/Itch.io
It looks like this:
![image](https://user-images.githubusercontent.com/68751594/110347978-ecc30280-800f-11eb-9925-92ac5f38603a.png)

**Comment by ririxidev** [comment]
Already a thing.
