### ISSUE TITLE
[Feature Request | Presence] Google Classroom

### ISSUE THREAD

**Issue by retapic** [PreMiD/Presences#3196]
**Is your feature request related to a problem? Please describe.**
There is no way to hide the activity in this presence.

**Describe the solution you'd like**
Ability to enable "Privacy" mode, [as in the presence of "YouTube"](https://i.imgur.com/UZnsUyP.jpg) 

**Describe alternatives you've considered**
Nope

**Additional context**
Nope

**Comment by EncryptedDev** [comment]
I'm happy to look into doing this for you, sure
