### ISSUE TITLE
MatrixBots | matrixbots.xyz

### ISSUE THREAD

**Issue by OGMatrix** [PreMiD/Presences#3211]
**Prerequisites and essential questions**
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** OGMatrix#0001

**What's the name of the service?** MatrixBots | https://www.matrixbots.xyz

**What should the Presence display?** It shows wich Bot the user is visiting, shows wich user the user is visiting, shows if he is in the Main Page, shows if the user is adding a Bot

**If possible, please provide a logo for the service (512x512 minimum)** https://cdn.discordapp.com/attachments/805485700719312947/818444701307764736/Matrix_Logo.jpg

**Comment by SlowLife1661** [comment]
It's not possible to check if user is adding bot or not, can only show what bot is user viewing

**Comment by OGMatrix** [comment]
> It's not possible to check if user is adding bot or not, can only show what bot is user viewing

no, I have an add site

**Comment by SlowLife1661** [comment]
Oh you mean the matrixbots.xyz/add? Just logged in.

**Comment by EncryptedDev** [comment]
I can do this!

**Comment by SuperzZyntexYT** [comment]
> I can do this!

Oh I thought I can add it here to the website lmao no sorry already did it myself

**Comment by EncryptedDev** [comment]
> > I can do this!
> 
> 
> 
> Oh I thought I can add it here to the website lmao no sorry already did it myself

So you have done it yourself? You requested a presence lol 
If you made the presence, make a PR and close this
