### ISSUE TITLE
Tureng | tureng.com

### ISSUE THREAD

**Issue by kyoyacchi** [PreMiD/Presences#3213]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
Tureng | tureng.com
**What should the Presence display?** 
which word dictionary page you are looking, mainpage, and other all pages.
**If possible, please provide a logo for the service (512x512 minimum)** 
![tureng](https://user-images.githubusercontent.com/63583961/110356791-84d1e380-8032-11eb-9773-bc241d2508ea.png)

**Comment by SuperzZyntexYT** [comment]
I can do this for you.

**Comment by kyoyacchi** [comment]
> I can do this for you.

Ok

**Comment by OGMatrix** [comment]
> > I can do this for you.
> 
> Ok

Please give me your Discord Tag, where we  can speak bec of more information

**Comment by kyoyacchi** [comment]
> > > I can do this for you.
> > 
> > 
> > Ok
> 
> Please give me your Discord Tag, where we can speak bec of more information

Hi, I'm sorry for late response. You can send friend request to Kyoya#3900 in Discord.

**Comment by kyoyacchi** [comment]
Any changes about this?

**Comment by ririxidev** [comment]
![image](https://user-images.githubusercontent.com/9348108/124263393-7b194200-db33-11eb-8047-9a66a3cb5bdb.png)

**Comment by kyoyacchi** [comment]
@ririxidev wow, that was quick response
