### ISSUE TITLE
songsterr.com

### ISSUE THREAD

**Issue by aberaalper** [PreMiD/Presences#3222]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**bera#5796** 

**songsterr.com | Songsterr** 

**Which song i am trying to learn rn** 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Isa27-0** [comment]
It has already been requested #2853
