### ISSUE TITLE
diziroll.com

### ISSUE THREAD

**Issue by 2qke** [PreMiD/Presences#3229]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** ZyuzAx#8780

**What's the name of the service?** www.diziroll.com | diziroll

**What should the Presence display?** Dizi/Film isimleri, Dizi/Film resimleri, Dizi/Film süreleri.

**If possible, please provide a logo for the service (512x512 minimum)** 
![diziroll](https://user-images.githubusercontent.com/49843411/110617336-9fc56480-81a6-11eb-928d-1cd9f5133219.png)

**Comment by erdem85** [comment]
https://github.com/PreMiD/Presences/pull/3220
