### ISSUE TITLE
Trackmania.io | https://trackmania.io/

### ISSUE THREAD

**Issue by GreepTheSheep** [PreMiD/Presences#3233]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Greep#3022

**What's the name of the service?** 
Trackmania.io (named like that)

**What should the Presence display?** 
The tab name and the informations on that page (example the map name if we're on a map page)

**If possible, please provide a logo for the service (512x512 minimum)** 
https://trackmania.io/img/square.png

**Comment by ririxidev** [comment]
If you made presence, why you made issue eh??? *Confused*

**Comment by GreepTheSheep** [comment]
I didn't think I would do it before
