### ISSUE TITLE
South Park | southpark.lat

### ISSUE THREAD

**Issue by Pikauwu** [PreMiD/Presences#3236]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** ! 𝑷𝒊𝒌𝒂#8280

**What's the name of the service?**  South Park https://www.southpark.lat/

**What should the Presence display?**  The name of the chapter, season and episode. Same as Netflix

**If possible, please provide a logo for the service (512x512 minimum)** ]
![unnamed](https://user-images.githubusercontent.com/76514771/110916774-25502e00-82e7-11eb-85ed-32d47600615c.jpg)

**Comment by SlowLife1661** [comment]
I will be working on this one
