### ISSUE TITLE
Add the new ' gogoanime.news ' domain.

### ISSUE THREAD

**Issue by prorounak2005** [PreMiD/Presences#3237]
**Prerequisites and essential questions** 
- [x] Is it a popular site? yes 
- [x] Is the website older than 2 months?  yes 
- [ ] Is the site locked to a specific country/region? no 
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) no 
- [ ] Does the website feature NSFW content? (e.g. porn, etc...) no 
- [ ] Are you a donator/patron? no 
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? yes 

**What's your Discord username?**  Mr Disguised#9944

**What's the name of the service?**  https://gogoanime.news/

**What should the Presence display?**  When seeing a specific news it should show - Reading news {News Topic} and when on homepage -{ On hompage of gogoanime}

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/69617708/110938995-b90f1200-835a-11eb-8d43-c00992cbcd05.png)

**Comment by SlowLife1661** [comment]
#3231
