### ISSUE TITLE
Presence Request // HentaiHaven 

### ISSUE THREAD

**Issue by huh-code** [PreMiD/Presences#3244]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?**  HentaiHaven | https://hentaihaven.xxx/ 

**What should the Presence display?** 
Title - HentaiHaven
Image - (attatched)
Smaller image - play/pause icon
Line 1 - Name of series
Line 2 - Series tags (anal, bdsm, etc)
Time remaining if playing video

(can add an extra button for 'view episode') 

**If possible, please provide a logo for the service (512x512 minimum)**  
![sdafgsedg](https://user-images.githubusercontent.com/65111632/111064149-93267080-8506-11eb-85b5-df25f48cc875.png)

**Comment by ririxidev** [comment]
That's not real hentaihaven LOL
