### ISSUE TITLE
BlockBench | blockbench.net

### ISSUE THREAD

**Issue by FrostbearDeluxe** [PreMiD/Presences#3246]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** my user is Black Ice Frostbear#8257

**What's the name of the service?** https://blockbench.net/

**What should the Presence display?** 
Large Imege: (shown below)
Small Image: (depending on the type of model that is being edited the image may change)
title: Blockbench
details (upper text): 
when editing: Editing a (type of model) Model (if it is a model) Entity (if it is a entity)
when animating: Animating a (type of model) Model (if it is a model) Entity (if it is a entity)
etc etc
State (lower text): (name of the project or model being edited)
(TimeStamps)
There may be more things but I don't remember very well, if you need more information you could be guided by the rich presence of Block Bench app

**If possible, please provide a logo for the service (512x512 minimum)** 
![OIBs4kpI](https://user-images.githubusercontent.com/80645869/111081862-1387aa00-84e4-11eb-89b9-39b2403598c5.jpg)

**Comment by v30xy** [comment]
I'm working on it 👍

**Comment by FrostbearDeluxe** [comment]
> 
> 
> I'm working on it +1

perfect, thank you very much

**Comment by v30xy** [comment]
> > I'm working on it 👍🏽
> 
> perfect, thank you very much

Everything is good but the project name and model type not included because not specifying. I'll open Pull Request soon.

**Comment by FrostbearDeluxe** [comment]
> 
> 
> > > I'm working on it 👍🏽
> > 
> > 
> > perfect, thank you very much
> 
> Everything is good but the project name and model type not included because not specifying. I'll open Pull Request soon.

as it is not specified?

**Comment by v30xy** [comment]
> > > > I'm working on it 👍🏽
> > > 
> > > 
> > > perfect, thank you very much
> > 
> > 
> > Everything is good but the project name and model type not included because not specifying. I'll open Pull Request soon.
> 
> as it is not specified?

The selection is nowhere to be seen so I cannot add it.

**Comment by v30xy** [comment]
No in url or window. If there is a another way, i'll add.

**Comment by FrostbearDeluxe** [comment]
the selection between type of models or entities and images?

**Comment by v30xy** [comment]
> the selection between type of models or entities and images?

Can you send screenshot?

**Comment by FrostbearDeluxe** [comment]
> 
> 
> > the selection between type of models or entities and images?
> 
> Can you send screenshot?

screenshot of what?

**Comment by v30xy** [comment]
![image](https://user-images.githubusercontent.com/41836521/111658224-346e3900-881d-11eb-9535-22af24711810.png)
These model types. Selecting and starting editing. But the selection of the model type not including anywhere so i cant add it to presence. I mean here `when editing: Editing a (type of model) Model (if it is a model) Entity (if it is a entity)`

**Comment by v30xy** [comment]
Here is some example how it looks like in Web App.
![image](https://user-images.githubusercontent.com/41836521/111660841-8a43e080-881f-11eb-9397-f807a9278c9a.png)
![image](https://user-images.githubusercontent.com/41836521/111660885-9465df00-881f-11eb-9900-a6ae98e1aeb0.png)
![image](https://user-images.githubusercontent.com/41836521/111660912-9c258380-881f-11eb-9c9a-3f6bef995265.png)
![image](https://user-images.githubusercontent.com/41836521/111660947-a5165500-881f-11eb-843a-0d0cb53aae48.png)

**Comment by ririxidev** [comment]
Move convo to discord.

**Comment by FrostbearDeluxe** [comment]
Sorry, I was busy these days and I didn't check the answers.

**Comment by FrostbearDeluxe** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/41836521/111658224-346e3900-881d-11eb-9535-22af24711810.png)
> These model types. Selecting and starting editing. But the selection of the model type not including anywhere so i cant add it to presence. I mean here `when editing: Editing a (type of model) Model (if it is a model) Entity (if it is a entity)`

it is actually those types of models and entities, "Generic Entity", "Java Block / Item", "Bedrock Model", "Modded Entity", "OptiFine Entity", "OptiFine Part" and "Minecraft Skin", for example: "Editing a Bedrock Model" or "Painting a Minecraft Skin" and etc.

**Comment by FrostbearDeluxe** [comment]
> 
> 
> Here is some example how it looks like in Web App.
> ![image](https://user-images.githubusercontent.com/41836521/111660841-8a43e080-881f-11eb-9397-f807a9278c9a.png)
> ![image](https://user-images.githubusercontent.com/41836521/111660885-9465df00-881f-11eb-9900-a6ae98e1aeb0.png)
> ![image](https://user-images.githubusercontent.com/41836521/111660912-9c258380-881f-11eb-9c9a-3f6bef995265.png)
> ![image](https://user-images.githubusercontent.com/41836521/111660947-a5165500-881f-11eb-843a-0d0cb53aae48.png)

It's fine although it would be good to put in the part where it says "Model" the type of model that is editing / painting / animating / etc and that the small image is the icon of each type of model

**Comment by FrostbearDeluxe** [comment]
> 
> 
> Move convo to discord.

ok that's it

**Comment by v30xy** [comment]
#3329, close the issue please.
