### ISSUE TITLE
HBO Max

### ISSUE THREAD

**Issue by bruv7569** [PreMiD/Presences#3256]
<img width="234" alt="hbo max" src="https://user-images.githubusercontent.com/80703714/111181754-4a110380-857c-11eb-9c05-2da22c4f1d87.PNG">

**The HBO Max presence used to work perfectly until an update from about 2 or 3 months ago, it stopped showing the episode you're watching and now it just says the word "episode". It doesn't even specify what show it is.**

- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**jaron#7569** 

**hbomax.com** 

**It should say the tv show or movie you're watching and the name of the episode**

**Comment by SlowLife1661** [comment]
Use bug report template, and close this.
