### ISSUE TITLE
[Bug | Presence] V LIVE

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#3260]
**Describe the Bug**
The VLIVE presence doesn't work at me.
All the other presences work but not this one.

**Expected Behavior**
Normally my status should be :
"Playing VLIVE"
"Browsing..." or "Watch (...)"

**Screenshots**
![image](https://user-images.githubusercontent.com/71935156/111282741-9ae93080-863e-11eb-9b40-aa97797cf3cf.png)
(Nothing 😬)

**Environment**
- OS: Windows 10
- Browser: Chrome
- Version: 89.0.4389.82 (Official Build) (64-bit)

**Additional context**
I use 3 antivirus :
AVG, McAfee and Avira

---
By Maxou (Maxou#1909)
**For [@angelii#9109](https://discord.com/users/443997287023116288)**

**Comment by MaXfAa** [comment]
Replay works but live stream don't...

**Comment by SlowLife1661** [comment]
Can't reproduce.

**Comment by Bas950** [comment]
Cant't reproduce either :/
![image](https://user-images.githubusercontent.com/34792838/111317397-6ab48880-8664-11eb-8798-ca5a2969c711.png)
Please give some more information.
