### ISSUE TITLE
[Presence | Bug] Microsoft Teams

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#3261]
**Describe the Bug**
The MS Teams presence does not work at me. (And other people from the Discord server have the same problem.)

**Expected Behavior**
Normally my status should be :
"Playing Microsoft Teams"
"Viewing their assignements"

**Screenshots**
![image](https://user-images.githubusercontent.com/71935156/111303012-54063580-8654-11eb-9f3b-ed0d9d300cf4.png)
(Nothing 😬)

**Environment**
- OS: Windows 10
- Browser: Edge
- Version: 89.0.774.54 (Official build) (64-bit)

**Additional context**
Also I've noticed that privacy mode keeps turning off occasionally automatically for all presences I have. I don't know if that's the intended behaviour but i prefer them to stay on until and unless I turn them back off.

---
By Maxou (Maxou#1909)
**For [@Marcello#5091](https://discord.com/users/747370380221612112)**

**Comment by Esdeath-GK** [comment]
Can confirm this one.

**Comment by ririxidev** [comment]
@MatStef132

**Comment by SlowLife1661** [comment]
Fixed
