### ISSUE TITLE
HBO Max

### ISSUE THREAD

**Issue by bruv7569** [PreMiD/Presences#3265]
**The HBO Max presence used to work perfectly until an update from about 2 or 3 months ago, it stopped showing the episode you're watching and now it just says the word "episode". It doesn't even specify what show it is.**

**Screenshots**

<img width="234" alt="hbo max" src="https://user-images.githubusercontent.com/80703714/111412379-53988980-86aa-11eb-8045-0594ef725048.PNG">

**Environment**

- OS:  Windows 10
- Browser:  Chrome
- Version:  64-bit

**Comment by ririxidev** [comment]
Already a issue
