### ISSUE TITLE
Paramount+

### ISSUE THREAD

**Issue by bruv7569** [PreMiD/Presences#3266]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [ ] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** jaron#7569 

**What's the name of the service?** Paramount+

**What should the Presence display?** Whatever show or movie you're watching on Paramount+

**Comment by ririxidev** [comment]
Do new service request when you will kindly add img and link.
