### ISSUE TITLE
KhanAcademy - Presence Request

### ISSUE THREAD

**Issue by Jyneric** [PreMiD/Presences#3269]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
! s*jit™# 0001
**What's the name of the service?** 
KhanAcademy | https://www.khanacademy.org/
**What should the Presence display?** 
It should display what your doing (Like What Subject), What unit you are doing of the specific subject, and what Video/Quiz you are doing on the unit.
**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by ririxidev** [comment]
#751
