### ISSUE TITLE
WWE presence req

### ISSUE THREAD

**Issue by ab0ba** [PreMiD/Presences#3273]
**Prerequisites and essential questions** 
- [Yes] Is it a popular site?
- [Yes] Is the website older than 2 months? 
- [No ] Is the site locked to a specific country/region?
- [Yes ] Is the site a paid service? (e.g. Netflix, Hulu)
- [No] Does the website feature NSFW content? (e.g. porn, etc...)
- [No ] Are you a donator/patron?
- [No] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** aboba#8842

**What's the name of the service?**  _wwe.com / watch.wwe.com_

**What should the Presence display?**  time _and title of the video_ 

**If possible, please provide a logo for the service (512x512 minimum)** 
![wwe](https://user-images.githubusercontent.com/80864061/111557554-28d33180-878d-11eb-9e17-6dd2e944adcf.png)

**Comment by SlowLife1661** [comment]
Make it how it supposed to be.

**Comment by ririxidev** [comment]
Already requested
