### ISSUE TITLE
GenoAnime | genoanime.com

### ISSUE THREAD

**Issue by Tharki-God** [PreMiD/Presences#3274]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**ℓσɳεωεεɓ αɦℓαωαƭ#7464** 

**genoanime.com | GenoAnime** 

**1. Add Name Of Anime and Episode no When Something is Being watched 
2.Browsing as a Status if surfing /browse (Genre as detail if any selected)
3.Searching as a status if surfing /search(Searched text as detail)
4.Checking Schedule as a status if surfing /schedule.php(Searched text as detail)
5. Checking AMVs as status  if Surfing /amv
6.Checking Favourites as status if surfing/favorite
7.May add Watch Same Button which redirects to the episode URL
8..May add Check the Same Button which redirects to the Anime Details URL
-->

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by LoneWeebGod** [comment]
[GenoAnime.zip](https://github.com/PreMiD/Presences/files/6174722/GenoAnime.zip)
A Rough Coding for it From My Side I can't do anything further about this

**Comment by SlowLife1661** [comment]
#3423

**Comment by Genoanime** [comment]
Thanks

**Comment by Tharki-God** [comment]
My Final Code [genoanime]( https://github.com/Tharki-God/Presences/tree/patch-2)
