### ISSUE TITLE
Tanki Online | tankionline.com

### ISSUE THREAD

**Issue by Helios09** [PreMiD/Presences#3277]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Sir karot#6476

**What's the name of the service?** https://tankionline.com/ | Tanki Online

**What should the Presence display?** 
* It should display if the user is idol
* It should display the battle mode (CTF, ASL, DM, CP, JGR) the user is playing 
* It should also display how much time the battle has left

**If possible, please provide a logo for the service (512x512 minimum)** 
![tanki-onlinepng-custom-skin-agario-skinscom-tanki-online-png-512_512](https://user-images.githubusercontent.com/76133230/111765255-27c80000-8872-11eb-8864-4cdef42a683a.png)

**Comment by IF6plus** [comment]
Seeing as I used to play this game, I don't see why now...

**Comment by Helios09** [comment]
eh its a pretty ok game
