### ISSUE TITLE
Displaying presence depending on some criteria

### ISSUE THREAD

**Issue by NYRI4** [PreMiD/Presences#3278]
**Describe the solution you'd like**
Adding an option to whether display your presence or not depending on a whitelist/blacklist option in the extension. This list would either : 
- Target the last elements of the URL, for example : 5qap5aO4i9A of <https://www.youtube.com/watch?v=5qap5aO4i9A> to only display the presence when I'm listenning to Chilled Cow
- Target the channel name if it's possible.

**Additional context**
![Capture](https://user-images.githubusercontent.com/65369563/111778669-50251e00-88b5-11eb-8e9a-b7864bcd3be6.PNG)

**Comment by ririxidev** [comment]
Kinda useless option for me.
