### ISSUE TITLE
Paramount+ | paramountplus.com

### ISSUE THREAD

**Issue by bruv7569** [PreMiD/Presences#3279]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  jaron#7569

**What's the name of the service?**  Paramount+ | paramount.com

**What should the Presence display?**  Whatever show or movie you're watching on Paramount+

https://paramountplus.com/

![image](https://user-images.githubusercontent.com/80703714/111803681-4394cb80-889d-11eb-91a1-56f58cb3e5e5.png)

![image](https://user-images.githubusercontent.com/80703714/111803777-5f986d00-889d-11eb-825a-295224d97e40.png)

**Comment by IF64** [comment]
I've been working on one. I'd say I'll have it done by around tuesday

**Comment by IF64** [comment]
Preview: 
![image](https://user-images.githubusercontent.com/62923115/111924251-eace5a00-8a79-11eb-8d92-39d778d893f0.png)

**Comment by IF64** [comment]
Forgot to leave this here:
![image](https://user-images.githubusercontent.com/62923115/111924266-fe79c080-8a79-11eb-9a7f-6538961accf0.png)

**Comment by IF64** [comment]
Here's how it looks so far...
![image](https://user-images.githubusercontent.com/62923115/111924286-194c3500-8a7a-11eb-9b4d-bed710e3e2f7.png)

**Comment by IF64** [comment]
Update: made PR. Waiting for approval

**Comment by IF64** [comment]
Submitted and got feedback. I made the requested changed and I'm now waiting for the checks to complete

**Comment by IF64** [comment]
Codacy is going brrrrrr. That 2nd check isn't loading.

**Comment by bruv7569** [comment]
Thank you for updating me.

**Comment by IF64** [comment]
You're welcome. 
I need 1 more approval in order to get it published. Bas950 had suggested changes earlier.

**Comment by IF6plus** [comment]
The presence is out. Thank you for your patience

**Comment by bruv7569** [comment]
OMG THANK YOU
