### ISSUE TITLE
[Bug | Presence] Spotify Podcasts

### ISSUE THREAD

**Issue by godianxd** [PreMiD/Presences#3289]
**Describe the Bug**

its not showing the what podcast im listening to at all
**Steps to Reproduce**

1. The presence doesnt work
2.
3.

**Expected Behavior**

Suppose to show the podcast im listening to
**Screenshots**

**Environment**

- OS: 
- Browser: 
- Version: 
  

**Additional context**

**Comment by ririxidev** [comment]
Hey @godianxd,
Could you provide more information like Environment and more steps to reproduce this? Will be very helpful.

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Comment by ririxidev** [comment]
Closing since no additional things has been provided.
