### ISSUE TITLE
AniCloud.io Rich Presence

### ISSUE THREAD

**Issue by ZUNII** [PreMiD/Presences#3290]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region? 
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
「ZXИII」#7777

**What's the name of the service?** 
https://anicloud.io

**What should the Presence display?** 
The same like Netflix or Youtube as far it is possible

**If possible, please provide a logo for the service (512x512 minimum)** 
https://anicloud.io/public/img/facebook.jpg

**Comment by ririxidev** [comment]
Hey @ZUNII,
We are so sorry, but this site is not qualified for presence yet because of this thing:
 - Domain is not 2 months old.
 
You can always re-do this presence request when their domain will be old enough!

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721
