### ISSUE TITLE
Nextcloud Request

### ISSUE THREAD

**Issue by froghopgaming** [PreMiD/Presences#3291]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [    Yes!   ] 
- [x] Is the website older than 2 months? 
- [    Yes!   ] 
- [x] Is the site locked to a specific country/region?
- [    No!   ] 
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [    No! As it is self hosted   ] 
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [   No!   ] 
- [ ] Are you a donator/patron?
- [   No, but am a avid user!    ] 
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority!
- [    Of course! And I thank any dev that picks it up!   ] 

**What's your Discord username?** 
-  Alex The Zoomer#9314

**What's the name of the service?** 
- Does not have a set URL , as is self hosted. Regexp expressions can be used! **Nextcloud**

**What should the Presence display?** 
- I'd want the presence to display custom files and user made customisations at first
  Here is the discord convo!

-1  https://i.imgur.com/ILqz7GI.png
-2  https://i.imgur.com/HtzgSQd.png
-3  https://i.imgur.com/jL0Eldr.png

**If possible, please provide a logo for the service (512x512 minimum)** 

Would perfer to have custom icons that have been set by users in custom theming, but if that is not possible, this icon can be used!
https://icons.iconarchive.com/icons/papirus-team/papirus-apps/512/nextcloud-icon.png

Thank you so much for your time! And if this is not possible, that's okay! It was just an idea...
Thank you all so much for your time!

-Alex

**Comment by ririxidev** [comment]
Hey @froghopgaming,
Please keep service request template in markdown instead of changing whole thing. Please re-do your request by creating new pull request and changing necessary things by markdown.

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721
