### ISSUE TITLE
GeForce NOW

### ISSUE THREAD

**Issue by Helios09** [PreMiD/Presences#3294]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu) (paid service by choice)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Sir karot#6476

**What's the name of the service?** https://www.nvidia.com/en-us/geforce-now/ | GeForce NOW
https://www.nvidia.com/en-us/geforce/forums/discover/ | GeForce NOW Forums

**What should the Presence display?** 
* Browsing (though the site)
* Forum
* Topic of the forum page

**If possible, please provide a logo for the service (512x512 minimum)**  
![image](https://user-images.githubusercontent.com/76133230/111899676-1ad71800-89fc-11eb-83e9-9099ab121e35.png)

**Comment by ririxidev** [comment]
Hey @Helios09,
It's already requested #1982.

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721
