### ISSUE TITLE
Shiro | Shiro.is

### ISSUE THREAD

**Issue by ConfusedJonas** [PreMiD/Presences#3297]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** https://shiro.is/

**What should the Presence display?**  Borwsing shiro/watching xxx on shiro

**If possible, please provide a logo for the service (512x512 minimum)** 

On shiro.is you wan watch anime adfree with HD quality. Shiro v.2 will soon be released which will make it one of the best anime sites. currently it does not have a lot of users (2000 accounts) but i am sure it will become a big site once v.2 is released

**Comment by ririxidev** [comment]
Hey @ConfusedJonas,
Would be cool if you would provide their logo.

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Comment by ConfusedJonas** [comment]
![752971028765868062](https://user-images.githubusercontent.com/80989172/111918139-f6bf1980-8a83-11eb-8886-38c8928be2b0.png)

**Comment by SlowLife1661** [comment]
I will add this in my todo list
