### ISSUE TITLE
Netflix doesn't work

### ISSUE THREAD

**Issue by Ushiora** [PreMiD/Presences#330]
**Describe the bug**
It will show that you're browsing Netflix, but once you start a certain shows, it will
disappear on Discord as if PreMiD isn't active. 
Version: 2.0 and using Firefox's extension v2.0
an example of this is an Anime show called "K". 

**To Reproduce**
1. Run PreMID 2.0
2. Go to Netflix
3. Click and start "K" (anime show)

**Expected behavior**
It should show the "Show title" along with the
Season/Episode and the remaining time of the episode.

**Screenshots**
No screenshots needed since Discord just shows you're not active with any app.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 69.0.2 (64-bit)

**Additional context**
Nothing other than fix this please.

**Comment by frozaum** [comment]
fixed #386

**Comment by Bas950** [comment]
fixed #399
