### ISSUE TITLE
Manga Plus shueisha page for PreMiD

### ISSUE THREAD

**Issue by Skeldritch** [PreMiD/Presences#3305]
Hi, they suggest that they add manga plus to the Premid Store.I am surprised that this is not
https://mangaplus.shueisha.co.jp/manga_list/all

**Comment by ririxidev** [comment]
Hey @Skeldritch,
Please use service request template that you can access here: https://github.com/PreMiD/Presences/issues/new?assignees=&labels=&template=service_request.md

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721
