### ISSUE TITLE
DuckDuckGo | duckduckgo.com

### ISSUE THREAD

**Issue by greensneke** [PreMiD/Presences#3316]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
``banana#0009``
**What's the name of the service?** 
DuckDuckGo
**What should the Presence display?** 
Same as the google presence but instead with the duckduckgo logo and support for it.
**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by ririxidev** [comment]
Hey @greensneke,
Please add logo to description. Thanks.

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Comment by v30xy** [comment]
Already exists
https://premid.app/store/presences/DuckDuckGo 
https://github.com/PreMiD/Presences/tree/master/websites/D/DuckDuckGo
