### ISSUE TITLE
BBC iPlayer | bbc.co.uk/iplayer

### ISSUE THREAD

**Issue by BlueDeadpool** [PreMiD/Presences#333]
**What's the name of the service?**
bbc.co.uk/iplayer (BBC iPlayer)

**What should the Presence display?**
Information about the thing being watched and how long left

**Why do you want support for this service?**
It's a very popular way to watch shows in the UK and a lot of people would enjoy showing that they are watching a film or movie on BBC iPlayer such as Peaky Blinders or Bodyguard

**Are you able to provide an image for the service? (512x512 minimum)**
https://images-eu.ssl-images-amazon.com/images/I/413g7zSWatL.png

**Comment by Bas950** [comment]
Not for my country

**Comment by doomlerd** [comment]
> BBC iPlayer only works in the UK.
Users with access are needed to help make the presence.

**Comment by Bas950** [comment]
You need a tv lisence to view.
