### ISSUE TITLE
Replit Web IDE | https://replit.com

### ISSUE THREAD

**Issue by ZonaBRDev** [PreMiD/Presences#3337]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Zona#0001
**What's the name of the service?** 
replit.com | Repl.it
**What should the Presence display?** 
${User} Editing: ${file} / ${user} Viewing Profile / Viewing Community 
**If possible, please provide a logo for the service (512x512 minimum)** 
![at](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Repl.it_logo.svg/768px-Repl.it_logo.svg.png)

**Comment by ZonaBRDev** [comment]
[Replit.com.zip](https://github.com/PreMiD/Presences/files/6199408/Replit.com.zip)

**Comment by SlowLife1661** [comment]
Already exists, but there are domain and DOM changes

**Comment by ririxidev** [comment]
Hey @ZonaBRDev,
It already exists, https://premid.app/store/presences/Repl.it, if you need to report bug that it doesn't work use bug template not service request one.

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721
