### ISSUE TITLE
NPO | npostart.nl

### ISSUE THREAD

**Issue by alltimemarr** [PreMiD/Presences#3341]
**Prerequisites and essential questions**
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**
lifeiscrazy『marr』#3604

**What's the name of the service?**
https://www.npostart.nl | NPO
(NPO Start is free/free with account, NPO Plus is paid with account, same site I'd suggest just calling it NPO)

**What should the Presence display?**
Like with Netflix. The movie or series name, episode number, remaining time

**If possible, please provide a logo for the service (512x512 minimum)**
![image](https://user-images.githubusercontent.com/12399392/112397448-62aeb580-8d02-11eb-9515-e288d2169a92.png)
SVG logo link: https://www.npostart.nl/images/npo-start.svg

**Comment by DarkVillager** [comment]
Assign me pls
