### ISSUE TITLE
[Presence | Feature Request] BigBlueButton

### ISSUE THREAD

**Issue by martinbndr** [PreMiD/Presences#3344]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
A way to change the meeting room name of the presence. Like so we can put custom text instead of having the room name. And/Or a privacy mode

**Describe alternatives you've considered**
-

**Additional context**
Would be nice to let us change the text of the presence, because some teachers define a really personal name thats related to the class and teachers abbreviation.
So its a reason of privacy to change it.
Or Maybe a privacy mode would be nice too.

**Comment by ririxidev** [comment]
@kuba2k2
