### ISSUE TITLE
Side bar(on opera)

### ISSUE THREAD

**Issue by Bozic421** [PreMiD/Presences#3349]
Okay so the bug is on the side-bar of opera we can open apps like youtube music ,instagram etc. Premid only detects apps which are fully open can they not detect it when it is partially open like from the side bar not a major issue but..it would be great if premid could detect the app from the side-bar.
![image](https://user-images.githubusercontent.com/81369341/112501965-b0352c00-8daf-11eb-8b34-647a2d635a42.png)

**Comment by Isa27-0** [comment]
There is no way, as far as I know, this part does not support extensions.

**Comment by ririxidev** [comment]
No way to detect these things + we are supporting every chromium browsers and we are not going to add things that are reserved for only Opera.
