### ISSUE TITLE
Bionluk | bionluk.com

### ISSUE THREAD

**Issue by ReXulEc** [PreMiD/Presences#3350]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Is the site locked to a specific country/region?
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**ReXulEc#5707** 

**bionluk.com** 

**This is a plugin that shows what actions users are doing** 

**https://lh3.googleusercontent.com/XDKGzDD_jjY_KrqZg3COTdV9oW5e4lZjgOPGP07aOIaNsCqNdvcmVrocc7XFr01PdR0P**

**Comment by v30xy** [comment]
Assign me please.
