### ISSUE TITLE
AnimeSuge | AnimeSuge.io

### ISSUE THREAD

**Issue by Fox3058** [PreMiD/Presences#3368]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Whitzy#0001

**What's the name of the service?**  Animesuge.io

**What should the Presence display?**  What you are watching.

**If possible, please provide a logo for the service (512x512 minimum)**  Sadly I do not have one for it.

**Comment by ririxidev** [comment]
Provide logo.

**Comment by Venipa** [comment]
is it just me or is it just a copy of 9anime? same UI elements but differently styled.

**Comment by ririxidev** [comment]
> is it just me or is it just a copy of 9anime? same UI elements but differently styled.

Only you xD
