### ISSUE TITLE
[Presence | Bug] 9anime

### ISSUE THREAD

**Issue by alltimemarr** [PreMiD/Presences#3373]
**Describe the Bug**
it always shows [9anime](https://premid.app/store/presences/9anime) content as paused.

**Steps to Reproduce**
1.  Go to 9anime and select a random show. I was watching some episodes of [this show](https://9anime.to/watch/legend-of-black-heaven.pp66)
2. Play an episode
3. Check your Discord status. No matter if you play or pause, it'll always show the same pause behavior.

**Expected Behavior**
I expected there to be a play instead of stop icon, and maybe time remaining.

**Screenshots**
![image](https://user-images.githubusercontent.com/12399392/112757695-2bceed00-8feb-11eb-8872-97c0ebae002b.png)
![image](https://user-images.githubusercontent.com/12399392/112757874-d34c1f80-8feb-11eb-8faf-6c48d4dcba95.png)

**Environment**
- OS: macOS Catalina 10.15.7 (19H524)
- Browser: Safari
- Version: Version 14.0.3 (15610.4.3.1.6, 15610)

**Additional context**
Previously, I had this same issue with the [Kijk presence](https://premid.app/store/presences/Kijk) on Chrome. Among some other PreMiD issues as not updating the status when I closed a tab after watching a few episodes, no matter the presence. Those issues got resolved when I switched from Chrome to Safari. However, now I have the issue with 9anime. Kijk works fine, for what it's worth!

**Comment by ririxidev** [comment]
Will try to fix it tomorrow. Thanks for report.

**Comment by ririxidev** [comment]
Wasn't really fixing it but it works from what I see on other users profile
![image](https://user-images.githubusercontent.com/9348108/118486369-cdd0a300-b719-11eb-9322-d4c89f019f7e.png)
