### ISSUE TITLE
Picarto | picarto.tv

### ISSUE THREAD

**Issue by LeviSnoot** [PreMiD/Presences#3384]
**Describe the Bug**
Container only says "Browsing..", does not show streams that are playing or play/paused status.

**Steps to Reproduce**
1. Go to picarto.tv
2. Open any stream

**Expected Behavior**
Expected to see the name of the streamer I'm watching in Discord RPC, however it's either only saying "Browsing.." or isn't picking up the page at all.

**Environment**
- OS: Windows 10 Pro 20H2
- Browser: Vivaldi
- Version: 3.6.2165.40 (Stable channel) (64-bit)
- PreMiD Extension Version: 2.2.0.7 beta
- PreMiD App Version: 2.2.0

**Additional context**
Picarto appears to have recieved a major update recently, so I'm not surprised it's not working as expected, but figured it would be good to let the devs of the container know.

**Comment by ririxidev** [comment]
I suggest you updating your extension version still bc there is **2.2.3** that is stable but good report.

**Comment by LeviSnoot** [comment]
> I suggest you updating your extension version still bc there is **2.2.3** that is stable but good report.

Good catch, I've done that now 👌

**Comment by tERB00** [comment]
It's still broken. Can anyone look in to it?

**Comment by RisingSunLight42** [comment]
> It's still broken. Can anyone look in to it?

I'm looking into it and I have patched the bug since then. I will PR in no time in order to correct (finally) the presence ^^
