### ISSUE TITLE
AlbionOnline Forum Presence

### ISSUE THREAD

**Issue by salvadorgeracao** [PreMiD/Presences#3387]
**Is your feature request related to a problem? Please describe.**
No, I just would want that you guys create a albiononline.com Rich Presence.

**Describe the solution you'd like**
I would love that you guys create a albiononline.com Rich Presence. Please make it :)

**Describe alternatives you've considered**
I dont have any alternative, but i would love if you guys make it c:

**Additional context**
None

**Comment by ririxidev** [comment]
Please use [service request template](https://github.com/PreMiD/Presences/issues/new?assignees=&labels=&template=service_request.md).

**Comment by salvadorgeracao** [comment]
Oh thx.
