### ISSUE TITLE
Albion Online Rich Presence

### ISSUE THREAD

**Issue by salvadorgeracao** [PreMiD/Presences#3399]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Salva#3017

**What's the name of the service?** albiononline.com | The official website of the game Albion Online

**What should the Presence display?** If they are on the main page, on the news page (What new he/se is seeing), the forum page and the support page (And more stuff that i cant remember now.)

**If possible, please provide a logo for the service (512x512 minimum)** I cant find the website logo image, sorry

**Comment by ririxidev** [comment]
To be honest, this site doesn't have a lot to offer so I will close it for now and think about it.
