### ISSUE TITLE
Amazon Music India Presence

### ISSUE THREAD

**Issue by FaZeAditya** [PreMiD/Presences#3402]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [x ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?**  music.amazon.in | Amazon Music India

**What should the Presence display?**  What song you are playing.

**If possible, please provide a logo for the service (512x512 minimum)**  
![Amazon Music](https://user-images.githubusercontent.com/81750038/113281275-f3892080-9302-11eb-9e8d-b8267a5489c0.jpg)

**Comment by EncryptedDev** [comment]
What? It already works with the [Amazon Music](https://premid.app/store/presences/Amazon%20Music) presence as the presence uses RegExp

**Comment by StrikerFRFX** [comment]
The presence you have requested is already added as @EncryptedDev mentioned above ^

If there is a bug preventing usage of this presence, please open a support ticket in the Discord and I, as the developer, can help and see if anything needs fixing👍
