### ISSUE TITLE
presence for animumu.ga 

### ISSUE THREAD

**Issue by Shirogane-Miyuki** [PreMiD/Presences#3418]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ]Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
www.animumu.ga | AniMumu
**What should the Presence display?** 
The anime that the user is watching real time
**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by SlowLife1661** [comment]
Close #3410

**Comment by Shirogane-Miyuki** [comment]
done is it all good now

**Comment by ririxidev** [comment]
It's free domain duh.
![image](https://user-images.githubusercontent.com/9348108/113506567-e9a32f80-9545-11eb-9754-9335e493e90a.png)
