### ISSUE TITLE
Read Manga Online | readm.org

### ISSUE THREAD

**Issue by Almeidolaz** [PreMiD/Presences#3424]
**Prerequisites and essential questions** 
- [x] Is it a popular site? Yes
- [x] Is the website older than 2 months?  Yes
- [ ] Is the site locked to a specific country/region? No
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) No
- [ ] Does the website feature NSFW content? (e.g. porn, etc...) No
- [ ] Are you a donator/patron? No
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? Yes

**What's your Discord username?** 

**What's the name of the service?**  www.readm.org | Read Manga Online

**What should the Presence display?**  Name of the manga that is being read and number of the chapter.

**If possible, please provide a logo for the service (512x512 minimum)**  
![Captura de ecrã 2021-04-04 121518 (1)](https://user-images.githubusercontent.com/81871524/113507022-f7ee4d00-953f-11eb-9ccd-57e7087624fd.png)

**Comment by ririxidev** [comment]
Resize logo that you found to 512x512 and upload it thanks.

**Comment by MareGraphics** [comment]
I'll work on this
