### ISSUE TITLE
[Presence | Bug] HBO Max

### ISSUE THREAD

**Issue by Mxvcy** [PreMiD/Presences#3428]
**Describe the Bug**

**Steps to Reproduce**

1. Add the HBO Max presence from the premid store
2. Login into HBO Max on the website and click any show or movie
3. View the results on discord

**Expected Behavior**

Before the presence broke, it showed the movie and time left of the movie. 
Now, it just say's "HBO Max - Feature" nothing else.
**Screenshots**

![image](https://user-images.githubusercontent.com/81921125/113515285-8dd6a780-9541-11eb-9835-63ebf5f37557.png)

**Environment**

- OS:  Windows 10
- Browser:  Microsoft Edge
- Version:  Version 89.0.774.68 (Official build) (64-bit)
  

**Additional context**

Also, if it's possible to add the feature to make the presence show which category we're browsing. 
For example, there's different categories like, Series, Movies, Originals, Just added, Last Chance, Coming soon, Action, Comedy, 
etc. 
![image](https://user-images.githubusercontent.com/81921125/113515405-469ce680-9542-11eb-86f2-50029100b859.png)
![image](https://user-images.githubusercontent.com/81921125/113515395-3a188e00-9542-11eb-898d-b6c34d369c26.png).
 The presence just show's "Browsing" when you click on a category - and when we click a movie to view what it's about it, it can say "Browsing Movie - The Avengers (2012)". Also, a feature to show what you're searching up on HBO Max, same like the netflix rich presence from Tim.

**Comment by ririxidev** [comment]
It's bug since idk when. No one has it to fix it, no one maintains it for now. Last time someone removed feature to show things bc presence was crashing app or whatever so yeah...

**Comment by Mxvcy** [comment]
anyone willing to fix the presence if they got paid for it and maintained it?

**Comment by Mxvcy** [comment]
> It's bug since idk when. No one wants to fix it, no one maintains it for now. Last time someone removed feature to show things bc presence was crashing app or whatever so yeah...
> (since this service is USA only)

anyone willing to fix the presence if they got paid for it and maintained it?

**Comment by ririxidev** [comment]
I mean, if someone will want to fix it and has access to this site and is from USA then probably?

**Comment by zredrum** [comment]
As of about a week ago, I mentioned in the Discord that I'd begin attempting to fix it. As I'm just trying to get around presence development etc, it's gonna take me a bit. I'm also subscribed to HBO Max and in NY, so it's not an issue. If someone wants to help me as well just reach out (REDRUM#0001)

**Comment by yaasin12** [comment]
> I mean, if someone will want to fix it and has access to this site and is from USA then probably?

use nord vpn to bypass geo restriction, also i can provide account to whoever can/want to fix it.

**Comment by ririxidev** [comment]
@yaasin12 not everyone is willing to buy HBO Max sub :)

**Comment by fr0r** [comment]
Well, with the release of the service in the Latin America region and seeing that it's all on the same domain, I may take a look at it.

**Comment by ririxidev** [comment]
Will be nice.

**Comment by jxviercc** [comment]
What happened with the people that said they were gonna fix it? It's still not working properly.

**Comment by fr0r** [comment]
> What happened with the people that said they were gonna fix it? It's still not working properly.

@jxviercc i tried to mess with it but I couldn't get the video player to be detected.

**Comment by tedahn** [comment]
I'm taking a look at this. 


If you're nosy:

HBO Max Web Video Viewer seems to be really bare with no helpful `class` names or `data-id`s
So the last guy made a method that took in the selector for the header `span` based on a pretty brittle `querySelectorAll()` and found a match based on the fontSize & fontFamily. 

So any time HBO Max adds an extra HTML element, changes the font or font size, the presence will break.
We might want to refactor it to be at least easier to modify when there are updates.

Not sure if I can find a good solution but I'll revisit this after work today.

**Comment by kagbogre** [comment]
These would probably be better and more simple selectors:

Container would be `[role=heading]:first` which is this section:

![image](https://user-images.githubusercontent.com/4789757/130493662-763dee75-81d4-4936-b91f-8a619caa29ba.png)

Iterate over spans with text in them:

![image](https://user-images.githubusercontent.com/4789757/130495196-c8b96c0a-f542-4db5-aeca-d5f110049082.png)

Iterate and ignore the "" symbol which is the HBO Max logo which only appears sometimes.

Next in line will always be will be the series title and series episode. 

With movies it changes a little, but you can still differentiate with the same code:

![image](https://user-images.githubusercontent.com/4789757/130495438-450c4f4e-3591-4c47-a00d-077fdd6861df.png)


General procedure:

1. Use `[role=heading]:first span span` to select the titles.
2. Ignore first span if the text length is 1 (it will be an HBO logo).
3. Next position will be the main title.
4. Next position will be the episode (only if it’s a series, if it’s a movie this will not be present).

This will be less likely to change.
