### ISSUE TITLE
iVoox | ivoox.com

### ISSUE THREAD

**Issue by Jorc0** [PreMiD/Presences#3429]
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region? 
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) **(Premium independent content, but completely free)**
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Ori#2107

**What's the name of the service?** 
www.ivoox.com

**What should the Presence display?**
Listening to:
Duration:
Channel name:

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/48130077/113523775-43d5dc00-95aa-11eb-840e-12f80c2babd0.png)
![image](https://user-images.githubusercontent.com/48130077/113523792-5b14c980-95aa-11eb-8e51-875a0351a539.png)

**Comment by StrikerFRFX** [comment]
Will do when i get a spare mo'

**Comment by Jorc0** [comment]
> Will do when i get a spare mo'

Any update?
