### ISSUE TITLE
Animix Play Episode failure to Display in Rich Presence

### ISSUE THREAD

**Issue by SecretiveBastard** [PreMiD/Presences#3436]
**Describe the Bug**

I'm not sure if it is a bug or lacking feature but the episode does not show in rich presence. Only what you are watching, elapsed time/time left is shown. The features work on other website while it doesn't work here.
**Steps to Reproduce**

1.Opening Animix Play
2.Playing an Anime
3.Viewing Profile and Activity on Discord

**Expected Behavior**

The episode number must be shown.
**Screenshots**

![Capture](https://user-images.githubusercontent.com/81961756/113565860-48e46b00-963e-11eb-9d1c-5d1bbc55152d.PNG)

**Environment**

- OS:  Windows 10
- Browser:  Chrome
- Version:  Version 89.0.4389.114 (Official Build) (64-bit)
  

**Additional context**

Premid also fails sometimes to detect when I open Animix Play

**Comment by SlowLife1661** [comment]
And how do I view someone profile lmao

**Comment by SlowLife1661** [comment]
Not a bug

**Comment by SecretiveBastard** [comment]
Thanks
