### ISSUE TITLE
[Presence | Feature Request] Animix Play

### ISSUE THREAD

**Issue by SecretiveBastard** [PreMiD/Presences#3437]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
The frustrates me sometimes because the episode number when watching animix play does not show in the rich presence. The format  is also somewhat lacking in context
**Describe the solution you'd like**
I would like to request for adding the episode number of whatever show I am watching and improving the format shown in the rich presence by putting hyphens, etc.
**Describe alternatives you've considered**

**Additional context**

**Comment by ririxidev** [comment]
@jackkelly-bayliss @TheColorman

**Comment by TheColorman** [comment]
This has already been slightly addressed by #3868, but I do agree that the format still leaves a lot to be desired. I'll take a look at it as soon as I have time.
