### ISSUE TITLE
Diziyo | diziyo10.net

### ISSUE THREAD

**Issue by nicotinexgucci** [PreMiD/Presences#3439]
Prerequisites and essential questions

- [ ]  Is it a popular site?
- [x]  Is the website older than 2 months?
- [x]  Is the site locked to a specific country/region?
- [ ]  Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Are you a donator/patron?
- [x]  Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

What's your Discord username?
мое сердце#1952

*What's the name of the service?
[https://www.diziyo10.net/](url)

What should the Presence display?
the presence should display the content as in the Netflix asset

If possible, please provide a logo for the service (512x512 minimum)
![23621570_1553630844726149_4942256249898571797_n_512x512](https://user-images.githubusercontent.com/78096621/113616571-ef8c3400-965d-11eb-869e-7ac237c20f71.jpg)

**Comment by ririxidev** [comment]
Not 2 months old domain.
