### ISSUE TITLE
Suggestions for presences premid

### ISSUE THREAD

**Issue by Directinho** [PreMiD/Presences#3443]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?*T I O  D I R E C T　宛ゝ雲#0666* 

**What's the name of the service?*
1v1 lol (Games for browser) =[ 1v1.lol](https://1v1.lol)
GameBanana (Mods for games) = [gamebanana.com](https://gamebanana.com)
SaveFrom (Download Youtube Videos) = [Savefrom](https://en.savefrom.net/19/)
Happy Wheels (Game For Browser) = [totaljerkface](https://totaljerkface.com/happy_wheels.tjf)
Pixlr Editor (Image Editor for broser) = [Pixlr](https://pixlr.com/br/editor/)
Just Dance Now (Game For Browser) = [Just Dance Now](https://justdancenow.com)
Ruffle (Flash Player emulator) = [Ruffle](https://ruffle.rs/demo/) or (https://ruffle.rs)
MCPEDL (Mods for minecraft Bedrock/PE) = [MCPEDL](https://mcpedl.com)
SteamGridDB (Steam logos) = [SteamGridDB](https://www.steamgriddb.com)
Convertio (File Converter for browser) = [Convertio](https://convertio.co/en/)
* 

**What should the Presence display?*
**1v1 lol** => Tags: Games    ----- Game multiplayer in browser!
**GameBanana** => Tags: Games ----- Download mods for games!
**SaveFrom**  => Tags: Others ----- download Youtube videos, instagram videos and more!
**Happy Wheels** => Tags: Games ------ Game for browser(Violent content)
**Pixlr Editor** => Tags: Others ----------- Effects and images editor 
**Just Dance Now** => Tags: Game ----------- Game for browser
**Ruffle** => Tags: Games ------- Emulator flash player games
**MCPEDL** => Tags: Games ---- minecraft Bedrock/PE Mods download
**SteamGridDB** =>Tags: Others ------ Logos and more for you steam
**Convertio** => Tags: Others -------- Convert Photos and Videos

* 

**If possible, please provide a logo for the service (512x512 minimum)** 

1v1 lol icon => ![image](https://user-images.githubusercontent.com/69155843/113655702-b5785d80-9670-11eb-8fbc-58d9bf9edee7.png)

1v1 lol  Background => ![image](https://user-images.githubusercontent.com/69155843/113655661-a5607e00-9670-11eb-8a0d-43172c9ccc59.png)

------------------------------------------------------------------------------------------------

GameBanana Icon => ![image](https://user-images.githubusercontent.com/69155843/113655782-d50f8600-9670-11eb-9037-902ac36995f4.png)

GameBanana Background => ![image](https://user-images.githubusercontent.com/69155843/113655839-f83a3580-9670-11eb-8c51-e4b8c5476a7d.png) 

------------------------------------------------------------------------------------------------

SaveFrom Icon =>![image](https://user-images.githubusercontent.com/69155843/113655945-37688680-9671-11eb-83d1-57af3e7550cb.png)

SaveFrom BackGround =>![image](https://user-images.githubusercontent.com/69155843/113655977-48b19300-9671-11eb-81d6-b4007d12fca1.png)

------------------------------------------------------------------------------------------------

Happy Wheels Icon => ![image](https://user-images.githubusercontent.com/69155843/113656137-9c23e100-9671-11eb-90c9-aabb63ca3c64.png)

Happy Wheels Background => ![image](https://user-images.githubusercontent.com/69155843/113656178-ae9e1a80-9671-11eb-8e44-a2300ab8ebea.png)

------------------------------------------------------------------------------------------------

Pixlr Icon =>![image](https://user-images.githubusercontent.com/69155843/113656269-e73df400-9671-11eb-9736-f7dc54a8aedd.png)

Pixlr Background => ![image](https://user-images.githubusercontent.com/69155843/113656304-f9b82d80-9671-11eb-9c0c-6ff87a41ecf4.png)

------------------------------------------------------------------------------------------------

Just Dance Now Icon => ![image](https://user-images.githubusercontent.com/69155843/113656363-22402780-9672-11eb-995e-4f16eba41e87.png)
 
Just Dance Now BackGround =>![image](https://user-images.githubusercontent.com/69155843/113656420-40a62300-9672-11eb-9370-6f5cd5af199d.png)

------------------------------------------------------------------------------------------------

Ruffle Icon => ![image](https://user-images.githubusercontent.com/69155843/113656593-94187100-9672-11eb-833f-256f9e40e3a5.png)

Ruffle Background => ![image](https://user-images.githubusercontent.com/69155843/113656646-b14d3f80-9672-11eb-99ba-d21d9ef76bd9.png)

------------------------------------------------------------------------------------------------

MCPEDL icon => ![image](https://user-images.githubusercontent.com/69155843/113656703-c9bd5a00-9672-11eb-8360-5cfcf6767f4b.png)

MCPEDL Background => ![image](https://user-images.githubusercontent.com/69155843/113656796-f7a29e80-9672-11eb-86df-4e41fe21e242.png)

------------------------------------------------------------------------------------------------

SteamGridDB icon => https://www.steamgriddb.com/static/img/logo-512.png

SteamGridDB Background =>![image](https://user-images.githubusercontent.com/69155843/113656931-44867500-9673-11eb-9faa-77f7323764e5.png)

------------------------------------------------------------------------------------------------

Convertio icon =>![image](https://user-images.githubusercontent.com/69155843/113657023-74ce1380-9673-11eb-9cc7-27bb374de73a.png)

Convertio BackGround => ![image](https://user-images.githubusercontent.com/69155843/113657073-8e6f5b00-9673-11eb-8823-93bb6ac80f53.png)

------------------------------------------------------------------------------------------------

**BONUS**

a program just for everyone to create their personalized presences （￣︶￣） ↗

Bye :D

**Comment by Isa27-0** [comment]
Just Dance Now has already been requested (#1001)

**Comment by EncryptedDev** [comment]
As Isa27 said, some of your requests are duplicate requests - check before requesting in the future. Also, each suggestion should be a new issue afaik

**Comment by StrikerFRFX** [comment]
Duplicated requests, please make individual issues for presence requests (without spamming) and check in the future which ones have already been requested before doing this. Also, there will be no program for everyone to create their personalized presences, if you're looking for something customized I suggest looking into Custom Status in the Presence Store.
