### ISSUE TITLE
[Presence | Bug] Medium

### ISSUE THREAD

**Issue by eri** [PreMiD/Presences#3444]
# Describe the Bug
Currently, the Medium presence is partially broken. I have noticed many issues with it, for example it always returns "Viewing the page: Home" when it couldn't retrieve the information from the page or displays the "Reading a story" presence when it's not needed.

# Steps to Reproduce

### First issue - Authors are never displayed
1. Install the Medium presence from the store
2. Go to: https://medium.com/ and click to any story
3. Watch your presence change with the correct title but "Open in app" as author

### Second issue - New stories are displayed as "Home"
1. Install the Medium presence from the store
2. Login to your Medium account and go to: https://medium.com/new-story
3. Watch your presence change to "Writing a new story: No title set"
4. Start typing a title and press enter
5. Observe your presence turning into "Viewing the page: Home"

### Third issue - Viewing the list of stories turns into "Reading a story"
1. Install the Medium presence from the store
2. Login to your Medium account and go to: https://medium.com/me/stories/public
3. Possibly have at least one story to make it happen
4. Watch your presence weirdly turn into "Reading a story" presence

# Expected Behavior
### First issue - Authors are never displayed
The author's name is supposed to be displayed (Sean Kernan for my example in my screenshot below)

### Second issue - New stories are displayed as "Home"
The initial presence is supposed to be updated, "Writing a new story: No title set" should now get the title once you start typing (the first paragraph is always considered as title by Medium, doesn't matters if you follow the title preset of Medium or not).

### Third issue - Viewing the list of stories turns into "Reading a story"
The presence should turn into "Viewing a page: Your stories"

# Screenshots
![presence](https://i.imgur.com/2ZnRIF1.png)
![author-not-displayed](https://i.imgur.com/PVjeAeW.png)
![list-of-stories-issue](https://i.imgur.com/aLqIFy0.png)

# Environment
- OS: Windows 10 Version 10.0.19042 Build 19042
- Browser: Chrome
- Version: 89.0.4389.114 (Official build) (64 bits)

# Additional context

- [x] Checked if the PreMiD extension and client are up to date
- [x] Checked through (closed and open) issues to see if the issues above were reported before

**Comment by ririxidev** [comment]
@eggsy
