### ISSUE TITLE
Mangasee | mangasee123.com

### ISSUE THREAD

**Issue by Wistci** [PreMiD/Presences#3445]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

Wisty#2774

**What's the name of the service?** 

https://www.mangasee123.com/ | MangaSee

**What should the Presence display?** 

What manga you're currently reading and what chapter you're reading

**If possible, please provide a logo for the service (512x512 minimum)** 
![mangasee](https://user-images.githubusercontent.com/82051463/113750381-b93fca80-96d8-11eb-8c07-662c3533937e.png)

Or maybe

![mangaseeses](https://user-images.githubusercontent.com/82051463/113750444-c8267d00-96d8-11eb-825e-7a84df50ab44.png)

**Comment by EncryptedDev** [comment]
I'd take it the proper URL is this - https://mangasee123.com/. You should include it in the original message.

**Comment by Wistci** [comment]
> I'd take it the proper URL is this - https://mangasee123.com/. You should include it in the original message.

ah thanks

**Comment by Wistci** [comment]
> I'd take it the proper URL is this - https://mangasee123.com/. You should include it in the original message.

![image](https://user-images.githubusercontent.com/82051463/113760979-e72b0c00-96e4-11eb-8acf-8fe885e29701.png)

When I open the site it pops up like this so I copy pasted it

**Comment by Wistci** [comment]
> I'd take it the proper URL is this - https://mangasee123.com/. You should include it in the original message.

thanks

**Comment by roronoaD** [comment]
The logo in my mangasee request is better tho.

**Comment by MareGraphics** [comment]
I'm on it :)

**Comment by Wistci** [comment]
> I'm on it :)

Thanks :0
