### ISSUE TITLE
Vostfree for premid

### ISSUE THREAD

**Issue by rynmec** [PreMiD/Presences#3446]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [] Is the site locked to a specific country/region?
- [] Is the site a paid service? (e.g. Netflix, Hulu)
- [] Does the website feature NSFW content? (e.g. porn, etc...)
- [] Are you a donator/patron?
- [] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**ryn.#2005** 

**Vostfree** 

**L'animé qu'on regarde, le temps, et l'épisode, comme crunchyroll** 

**https://lh3.googleusercontent.com/HNC_c_h6MSt87qUAo2fDYUQfGidKwdM4PXS7L3_Ou2aPE2Nf9VzY7_tQZNckIGOOI3fz**

**Comment by EncryptedDev** [comment]
Hello, you need to fill in the form properly - including the checkbox questions. Also, should be in English so others can understand.

**Comment by StrikerFRFX** [comment]
Use the format correctly next time, & in English.
