### ISSUE TITLE
Pornhub.com domain has been changed to pornhub.org .

### ISSUE THREAD

**Issue by prorounak2005** [PreMiD/Presences#3452]
**Prerequisites and essential questions** 
- [x] Is it a popular site? 
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Mr Disguised#9944

**What's the name of the service?**  https://www.pornhub.org/

**What should the Presence display?**  When oh hompage is should display {browsing} and when watching {Watching [Video title] }

**If possible, please provide a logo for the service (512x512 minimum)**  
![image](https://user-images.githubusercontent.com/69617708/113830924-b3afb680-97a4-11eb-8dfe-3e7f6b261f88.png)

**Comment by EncryptedDev** [comment]
Hello, from what I can see, you're reporting a bug with a presence, but using the Presence Request template. Close this and reopen another request using the Bug Report template, found [here](https://github.com/PreMiD/Presences/issues/new?assignees=&labels=&template=bug_report.md)

**Comment by EncryptedDev** [comment]
https://pornhub.com/ is the main domain. https://pornhub.org redirects back to https://pornhub.com.

// close this issue

**Comment by callumok2004** [comment]
bruh... `.org` redirects to `.com`

**Comment by prorounak2005** [comment]
But the presence is not working bro
