### ISSUE TITLE
direct links are not detected

### ISSUE THREAD

**Issue by FrenkyDema** [PreMiD/Presences#3453]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
FrenkyDema#8439

**What's the name of the service?** 
AnimeSaturn

**What should the Presence display?** 
The links of Anime Saturn are not detected
Example:
https://www.animesaturn.it/watch
When I open this kind of URL the extension doesn't detect that it is an AnimeSaturn URL

It only happens if that page is opened without going to the main site
Example:
https://www.animesaturn.it > https://www.animesaturn.it/anime/ > https://www.animesaturn.it/watch (works)

https://www.animesaturn.it/watch (does not work)

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by EncryptedDev** [comment]
Hello, from what I can see, you're reporting a bug with a presence, but using the Presence Request template. Close this and reopen another request using the Bug Report template, found [here](https://github.com/PreMiD/Presences/issues/new?assignees=&labels=&template=bug_report.md)
