### ISSUE TITLE
Amazon Prime Vídeo

### ISSUE THREAD

**Issue by mackchronus** [PreMiD/Presences#346]
**What's the name of the service?**
www.primevideo.com | Amazon Prime Vídeo

**What should the Presence display?**
The information is pretty much the same as Netflix Presence. If it is for example a series, it has the information of the name of the series, the season, the episode and the remaining time, and if it is a movie, the name, and the remaining time of it. , and the pause and play of course

**Why do you want support for this service?**
That would be the same reason why there is a Netflix presence, because Amazon Prime is its biggest competitor, and has very good series and movies.

**Are you able to provide an image for the service? (512x512 minimum)**
![411j1k1u9yL](https://user-images.githubusercontent.com/56230761/66272602-45ea9d80-e842-11e9-993c-254f688f44eb.png)

**Comment by CobyPowers** [comment]
#14
