### ISSUE TITLE
[Presence | Bug] AnimeSaturn

### ISSUE THREAD

**Issue by FrenkyDema** [PreMiD/Presences#3462]
**Describe the Bug**

The links of Anime Saturn are not detected
Example:
https://www.animesaturn.it/watch
When I open this kind of URL the extension doesn't detect that it is an AnimeSaturn URL

It only happens if that page is opened without going to the main site
Example:
https://www.animesaturn.it > https://www.animesaturn.it/anime/ > https://www.animesaturn.it/watch (works)
https://www.animesaturn.it/watch (doesn't work)
**Steps to Reproduce**

1.use a direct link to a page
https://www.animesaturn.it/watch

without going to the main page
https://www.animesaturn.it > https://www.animesaturn.it/anime/ > https://www.animesaturn.it/watch
2.
3.

**Expected Behavior**

venga rilevata la pagina
https://www.animesaturn.it/watch
come pagina di anime saturn e venga aggiornato lo stato Discord

**Screenshots**

**Environment**

- OS: Windows 10
- Browser: Opera Gx
- Version: LVL 2 (core: 73.0.3856.424)
  

**Additional context**

it's not too important a problem, but for me who often use direct links to see anime it is a bit broken

**Comment by ririxidev** [comment]
No one maintains this presence; so someone, feel free to fix it.
