### ISSUE TITLE
gogoanime.ai domain change

### ISSUE THREAD

**Issue by prorounak2005** [PreMiD/Presences#3463]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Mr Disguised#9944

**What's the name of the service?**  https://www1.gogoanime.ai/

**What should the Presence display?** 
When on homepage {Browsing Homepage.....} . When watching an anime [Watching {anime name} {Time Left}]
**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/69617708/113996584-efb24c80-9874-11eb-8d2b-54714e18c7ed.png)

**Comment by prorounak2005** [comment]
It is not showing the name of the anime and duration of the anime properly.

**Comment by ririxidev** [comment]
So use bug report template not service request.
