### ISSUE TITLE
Cemetech | cemetech.net

### ISSUE THREAD

**Issue by KnightsWhoSayNi0** [PreMiD/Presences#3470]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
KnightsWhoSayNi#6921

**What's the name of the service?** 
[https://www.cemetech.net/](https://www.cemetech.net/) | Cemetech

**What should the Presence display?** 
Info about where you are in the site, what you're doing, etc...

**If possible, please provide a logo for the service (512x512 minimum)** 
![icon](https://user-images.githubusercontent.com/62893792/114107282-ad056a00-989e-11eb-9c82-106bf420771a.png)

I've already coded the presence [here](https://github.com/KnightsWhoSayNi0/CemetechPreMid)
There are more links in the repo.
Thanks!

## Screenshots
Edit: added the screenshots directly.
![aQdUWc2](https://user-images.githubusercontent.com/62893792/114107553-3cab1880-989f-11eb-972c-69b04f178d95.png)
![asJLI5G](https://user-images.githubusercontent.com/62893792/114107554-3cab1880-989f-11eb-96db-da229f2edb33.png)
![JsxBwP8](https://user-images.githubusercontent.com/62893792/114107555-3cab1880-989f-11eb-91de-755b12c21e8a.png)
![MDjjDw2](https://user-images.githubusercontent.com/62893792/114107556-3cab1880-989f-11eb-81d5-369658091b81.png)
![n5oAzhF](https://user-images.githubusercontent.com/62893792/114107557-3d43af00-989f-11eb-9246-5633ff6e88a1.png)
![Z3oZWjB](https://user-images.githubusercontent.com/62893792/114107559-3d43af00-989f-11eb-9567-7694d49483f8.png)
![3FthYt5](https://user-images.githubusercontent.com/62893792/114107560-3d43af00-989f-11eb-813f-c79af7ed48a2.png)

**Comment by ririxidev** [comment]
Yeah em, even if you would do pull request with this presence, it wouldn't be accepted since site doesn't offer to much to show on status. sorry :/

**Comment by KnightsWhoSayNi0** [comment]
I kind of agree with you, but there is tons of stuff you can show. Take a look at the repo [here](https://github.com/KnightsWhoSayNi0/CemetechPreMid).

**Comment by ririxidev** [comment]
I already checked it and I'm saying it by your coded presence and site.

**Comment by KnightsWhoSayNi0** [comment]
Ok, but can I still do a pull request? I think there are a bunch of presences with the same amount of info shown?
