### ISSUE TITLE
PREMID NOT WORKING ON OPERA GX

### ISSUE THREAD

**Issue by Piffyx** [PreMiD/Presences#3478]
**Describe the bug**
PreMid not working on Opera GX,.

**To Reproduce**
1. It worked fine when I used Firefox, but when I moved to Opera GX it stopped working. I made sure I had the Addon for chrome addons to work and the PreMid addon yet it doesn't work.

**Expected behavior**
For PreMid to work on Opera GX

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX
 - Version (Not sure exactly what this is asking. version of OS? Version of browser?  Just in case I probably have the newest version of Opera GX)

**Comment by Bas950** [comment]
Please try this on presences that have language settings (Youtube, Twitch, Netflix, and more):
https://gyazo.com/f067c4725cb122322f239717067a64d9
If that doesn't help you, then please make a ticket in #support on our [Discord server](https://discord.premid.app/).
