### ISSUE TITLE
[Presence | Bug] Gogoanime

### ISSUE THREAD

**Issue by prorounak2005** [PreMiD/Presences#3480]
**Describe the Bug**
 Due to the recent domain change of gogoanime.ai to https://www1.gogoanime.ai/ . The presence is not working . While watching anime it is not showing the name of the anime and duration and time left . It is only showing a broken gogoanime presence with no link / buttons and title of the anime we are watching.
**Steps to Reproduce**
 
![image](https://user-images.githubusercontent.com/69617708/114225439-ef5aa400-998f-11eb-868e-cdd8dd85be8c.png)
![image](https://user-images.githubusercontent.com/69617708/114225510-06999180-9990-11eb-991a-a42430d76f71.png)

1.
2.
3.

**Expected Behavior**
 Normally it should show the name of the anime which we are watching and there should be a button . On clicking that button we will automatically visit gogoanime. But it is not working.

**Screenshots**

![image](https://user-images.githubusercontent.com/69617708/114226243-f504b980-9990-11eb-8d3d-2fd0ef47c836.png)

**Environment**

- OS:  WIndows 10 
- Browser:  I am using chrome 
- Version: 
   Version 89.0.4389.114 (Official Build) (64-bit)

**Additional context**

**Comment by prorounak2005** [comment]
Oh thanks . I am closing the Issue.

**Comment by ririxidev** [comment]
huh?
