### ISSUE TITLE
Audiomack | audiomack.com

### ISSUE THREAD

**Issue by sarm0** [PreMiD/Presences#3484]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

What's your Discord username?
sarm?#5839
What's the name of the service?
www.audiomack.com
What should the Presence display?

Shows the audomack logo, shows the song, the artist, the album or single cover.
https://cdn.discordapp.com/attachments/790017286671958026/830186452645838888/Screenshot_299.png

If possible, please provide a logo for the service (512x512 minimum)
https://cdn.discordapp.com/attachments/790017286671958026/830188539286650931/Screenshot_300.png

**Comment by SlowLife1661** [comment]
I mean you can just edit #3483
