### ISSUE TITLE
Pornhub presence not working

### ISSUE THREAD

**Issue by prorounak2005** [PreMiD/Presences#3487]
**Describe the Bug**
 Pornhub presence is not working when I am in https://www.pornhub.org/

**Steps to Reproduce**

![image](https://user-images.githubusercontent.com/69617708/114265033-27073180-9a0c-11eb-9c9e-e7cb26c778b3.png)

1.
2.
3.

**Expected Behavior**
 It should show the title of the video and a button should be there which will allow us to go to pornhub . 

**Screenshots**
 NA

**Environment**

- OS:  Windows 10
- Browser:  Chrome
- Version:  Version 89.0.4389.114 (Official Build) (64-bit)
  

**Additional context**

**Comment by ririxidev** [comment]
so use pornhub.com lol
