### ISSUE TITLE
AniCloud | anicloud.io

### ISSUE THREAD

**Issue by ZUNII** [PreMiD/Presences#3488]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
「ZXИII」#7777
**What's the name of the service?** 
https://anicloud.io
**What should the Presence display?** 
The same like Netflix, Youtube or Anime4you if possible
**If possible, please provide a logo for the service (512x512 minimum)** 
https://anicloud.io/public/img/facebook.jpg

**Comment by Emijor** [comment]
Ich nehme mal an dass du Deutsch sprichst.....
Hast du dir das ca. so vorgestellt?
![12313134](https://user-images.githubusercontent.com/55028218/114327374-025ca800-9b39-11eb-868b-30b5e61e9fb3.png)

**Comment by ZUNII** [comment]
Genau so hab ich es mir vorgestellt :)

**Comment by Emijor** [comment]
Ok, Ich bei mein Code noch ein paar lines optimieren und dann werde ich das veröffentlichen

**Comment by ZUNII** [comment]
Cool cool

Danke dir

**Comment by ZUNII** [comment]
Hey,

du hast es dir vielleicht schon gedacht.. AniCloud bzw. ja jetzt AniWorld.
Ist es für dich möglich das zu updaten damit es auch auf dem neuen Namen klappt? 

:)

**Comment by ZUNII** [comment]
Hey,

du hast es dir vielleicht schon gedacht.. AniCloud bzw. ja jetzt AniWorld.
Ist es für dich möglich das zu updaten damit es auch auf dem neuen Namen klappt?

:)

**Comment by joerkig** [comment]
#6203
