### ISSUE TITLE
BetterAnime | betteranime.net

### ISSUE THREAD

**Issue by kikajoestar** [PreMiD/Presences#3512]
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**
!Kikss#4400

**What's the name of the service?**
https://betteranime.net/ 

**What should the Presence display?**
What you are watching, just like other sites (e.g. Crunchyroll, Netflix, 9anime, etc...) 

**If possible, please provide a logo for the service (512x512 minimum)**
![BetterAnime LOGO 2](https://user-images.githubusercontent.com/82381655/114564125-f4f20b80-9c67-11eb-98dd-ca068540fbe0.png)

**Comment by SlowLife1661** [comment]
Will make this
