### ISSUE TITLE
Sushiroll | sushiroll.co.id

### ISSUE THREAD

**Issue by rayyplay** [PreMiD/Presences#3514]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** rayyplay#4999 

**What's the name of the service?** sushiroll.co.id | Sushiroll 

**What should the Presence display?** Watching Sushiroll, title anime, duration, play/pause/stop 

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/42858646/114428192-16aaae80-9be6-11eb-9b10-00713797ded5.png)

**Comment by SlowLife1661** [comment]
*Is the site locked to a specific country/region? I can't seems to watch anything*
![image](https://user-images.githubusercontent.com/54318514/117473460-33879700-af84-11eb-8e8b-8019437e9c40.png)
