### ISSUE TITLE
Google Colab | colab.research.google.com

### ISSUE THREAD

**Issue by dalhaqq** [PreMiD/Presences#3515]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
Google Colab
**What should the Presence display?** 
The filename of notebook I'm working on
**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by ririxidev** [comment]
provide logo.

**Comment by dalhaqq** [comment]
![colab](https://user-images.githubusercontent.com/63442570/114590941-8a66bd00-9cb3-11eb-994c-5809a84bc88c.png)
