### ISSUE TITLE
wakanim.tv

### ISSUE THREAD

**Issue by Draewyn** [PreMiD/Presences#352]
**What's the name of the service?**
Ex. https://www.wakanim.tv/fr/v2 | Wakanim

**What should the Presence display?**
Browsing, Episodes, Time remaining, same as the Crunchyroll integration does

**Why do you want support for this service?**
Because it's one of the 3 services of legal Anime Streaming services available here in France and i believe that i'm not the only one using it. (With Anime Digital Network and Crunchyroll that are both already available on the PreMiD store)

**Are you able to provide an image for the service? (512x512 minimum)**
![Wakanim Logo](https://user-images.githubusercontent.com/9287378/66274438-0db58000-e87f-11e9-976b-1c73798f35ad.jpg)

**Comment by frozaum** [comment]
duplicate #50
