### ISSUE TITLE
Ruffle | ruffle.rs

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#3526]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** Ruffe: https://ruffle.rs/ (The page for the emulator itself is: https://ruffle.rs/demo/)

**What should the Presence display?** 

As it is a flash emulator, it may be impossible to put the name of the game (only if it is one of the predefined ones) and yes, the name of the file that is running.
So it would be as it is in this example: 
![image](https://user-images.githubusercontent.com/68751594/114611517-83ba5480-9c77-11eb-9c48-56fb5756c367.png)

**If possible, please provide a logo for the service (512x512 minimum)** _I had to create_
![ado](https://user-images.githubusercontent.com/68751594/114611631-9fbdf600-9c77-11eb-93f5-a53c56c94ce6.png)

**Comment by ririxidev** [comment]
I literally don't know if demo site should have presence but I will leave it for now :/

**Comment by Isa27-0** [comment]
> I literally don't know if demo site should have presence but I will leave it for now :/

Ok
