### ISSUE TITLE
https://mangasee123.com/

### ISSUE THREAD

**Issue by zainmalik890** [PreMiD/Presences#3527]
**Prerequisites and essential questions** 
- [yes] Is it a popular site?
- [yes] Is the website older than 2 months? 
- [no ] Is the site locked to a specific country/region?
- [no ] Is the site a paid service? (e.g. Netflix, Hulu)
- [no ] Does the website feature NSFW content? (e.g. porn, etc...)
- [no ] Are you a donator/patron?
- [yes] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** https://mangasee123.com/

**What should the Presence display?** just like the presence of mangakakalot

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by EncryptedDev** [comment]
Duplicate of #3445
