### ISSUE TITLE
HentaiHeaven presence?

### ISSUE THREAD

**Issue by SuperNaaWorld** [PreMiD/Presences#3532]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
SuperNaaWorld04#5764
**What's the name of the service?** 
https://hentaihaven.xxx/
**What should the Presence display?** 
basicly the same as plex but just HentaiHeaven
**If possible, please provide a logo for the service (512x512 minimum)** 
![hentai-haven-logo-B9D8C4B3B8-seeklogo com](https://user-images.githubusercontent.com/78053392/114774804-de83a700-9d70-11eb-9ccb-bb771c79d19c.png)

**Comment by ririxidev** [comment]
It's not hentaihaven :///
