### ISSUE TITLE
[Presence | Bug] Udemy

### ISSUE THREAD

**Issue by yannawrgit** [PreMiD/Presences#3537]
**Describe the Bug**
The presence doesn't recognize the Course I'm watching

**Steps to Reproduce**
Watch any Course in Udemy website
Verify if the presence is working as it should

**Expected Behavior**
The presence should show the name of the Course and the episode, instead it shows as "Unknown Course" and "Unknown Episode". It doesn't matter what course I'm watching.

**Screenshots**
![DiscordCanary_TkannJ9owA](https://user-images.githubusercontent.com/73317883/114893463-1972f280-9de4-11eb-910a-811f9c5ab9ac.png)

**Environment**

- OS: Windows 10
- Browser: Opera GX / Brave
- Version: Opera GX: LVL2 (core: 73.0.3856.431) / Brave: Versão 1.22.72 Chromium: 89.0.4389.128 (Versão oficial) 64 bits

**Comment by yaasin12** [comment]
same here

**Comment by ririxidev** [comment]
@eggsy

**Comment by AlperSal** [comment]
Additional: I am having the same problem in Chrome and Firefox. Presence is not working properly with them too.
