### ISSUE TITLE
Podcast Addict | podcastaddict.com

### ISSUE THREAD

**Issue by noahlovescats** [PreMiD/Presences#3542]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Noah#4986

**What's the name of the service?** 
www.podcastaddict.com | Podcast Addict

**What should the Presence display?** 
What page or podcast you are browsing and what podcast you are listening to

**If possible, please provide a logo for the service (512x512 minimum)** 
![podcastaddict](https://user-images.githubusercontent.com/79289128/115134201-b942a300-9fd3-11eb-9795-1c078e2045d8.png)

**Comment by MareGraphics** [comment]
Does this website work as of yesterday? I started working on it and it just broke, gives me 404 whatever I do. @noahlovescats

**Comment by MareGraphics** [comment]
I'm on it.
