### ISSUE TITLE
Suggesting to add a new presence/Dubbedanime.net

### ISSUE THREAD

**Issue by FujiYamamoto** [PreMiD/Presences#3555]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [ ] Yes, it is a popular website.
- [x] Is the website older than 2 months?
- [ ] Yes, it is older than 2 months
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] As far as I know, No
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] No.
- [x] Are you a donator/patron?
- [ ] no.
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?
- [ ] yes.

**What's the name of the service?** 
https://ww5.dubbedanime.net/ | Dubbed anime.net

**What should the Presence display?** 
the anime which is being watched, the season, and the episode number ( A replica of the Netflix presence is best)

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/82749800/115336387-c2429880-a1bc-11eb-9bf4-4e47b29e5399.png)
![image](https://user-images.githubusercontent.com/82749800/115336397-c8387980-a1bc-11eb-9064-8dc08023c82b.png)

**Comment by ririxidev** [comment]
fix template. it wasn't like that.

**Comment by Copimox** [comment]
So... Are you guys planning to add this to PreMiD? Cause in my opinion this is the best anime site. Only maximum 2 popup ads, nothing else

**Comment by ririxidev** [comment]
and? still it wasn't re-requested because template is not OK in this issue.
