### ISSUE TITLE
One Piece Drip

### ISSUE THREAD

**Issue by BerfanK** [PreMiD/Presences#3559]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Nykloon#0002

**What's the name of the service?** 
https://www2.onepiece-drip.com/

**What should the Presence display?** 
Example:
**One Piece**
Skypia Saga
Episode 138
12 minutes left

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/69632575/115464361-3e74c480-a22d-11eb-9c2c-e3456a48b50b.png)

**Comment by ririxidev** [comment]
Yeah can't even pass bot verification. For now closing - since can't even check site.
