### ISSUE TITLE
Repl.it

### ISSUE THREAD

**Issue by GamingWithAky** [PreMiD/Presences#3567]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**~𝓐𝓴𝔂 𝓥𝓲𝓫𝓮𝓼~#0001** 

**repl.it** 

**repl.it** 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by SlowLife1661** [comment]
https://premid.app/store/presences/Replit
