### ISSUE TITLE
Pressence on website kpv.ac.th

### ISSUE THREAD

**Issue by Porton0071** [PreMiD/Presences#3578]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 

**What should the Presence display?** 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Porton0071** [comment]
username = #8557
service = Klangdong-Poonna-Vitthaya
Presence display  = web site school in thai
https://media.discordapp.net/attachments/692263962204700675/835623618741272616/logo_kpv512.png?width=473&height=473

**Comment by SlowLife1661** [comment]
I don't think anyone gonna use this Presence, and I don't think you can say that it's "popular" 🐱

**Comment by ririxidev** [comment]
Literally, no xD
