### ISSUE TITLE
Webtoon | webtoon.xyz

### ISSUE THREAD

**Issue by zeejayzxc** [PreMiD/Presences#3581]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**zee #0691?** 

**www.webtoon.xyz | Webtoon** 

**Just like the webtoon presence?** 

**Same as the webtoon icon**

**Comment by MareGraphics** [comment]
I'm on it
