### ISSUE TITLE
[Presence | Bug] TuMangaOnline

### ISSUE THREAD

**Issue by mlunax** [PreMiD/Presences#3583]
**Describe the Bug**
Domain change from https://tmofans.com to https://lectortmo.com/

**Steps to Reproduce**
N/A

**Expected Behavior**
TuMangaOnline to be shown as my discord status

**Screenshots**
N/A

**Comment by mlunax** [comment]
I can take it.

**Comment by ririxidev** [comment]
~~so you dont need to create bug report if you want to fix it~~
