### ISSUE TITLE
Hoyolab | hoyolab.com

### ISSUE THREAD

**Issue by FeverZ** [PreMiD/Presences#3590]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** 
www.hoyolab.com | Hoyolab

**What should the Presence display?** 
The name of the current page you watching (category, post, user etc...)

**If possible, please provide a logo for the service (512x512 minimum)** 
![hoyolab](https://user-images.githubusercontent.com/16353516/116108776-81fb8280-a6b4-11eb-805f-3338cecb0a17.png)
_This is the best I can found_

**Comment by MareGraphics** [comment]
On it.
