### ISSUE TITLE
Carrd

### ISSUE THREAD

**Issue by manueldotcom** [PreMiD/Presences#3606]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Manuel xd# 0285

**What's the name of the service?** Carrd/carrd.co

**What should the Presence display?** Developing a page/Creando una pagina,Watching a Carrd/Mirando una Carrd[watch the name and the link of carrd]

**If possible, please provide a logo for the service (512x512 minimum)** 
![icon-color](https://user-images.githubusercontent.com/83319408/116328076-cf97ee00-a78d-11eb-8d53-44f2f66b61de.png)

**Comment by ririxidev** [comment]
Eh... doesn't provide a lot of info to develop presence.
