### ISSUE TITLE
Niantic Wayfarer | wayfarer.nianticlabs.com

### ISSUE THREAD

**Issue by GiraffeCubed** [PreMiD/Presences#3615]
**Describe the Bug**
If using the extension "Wayfarer+" and using the Niantic Wayfarer presence, whilst on https://wayfarer.nianticlabs.com/review - it only ever displays "Getting ready to review a location..." instead of actually showing the title and description. This is due to the Wayfarer+ option "Description links to Google search...", which turns the description in to a clickable Google link

**Steps to Reproduce**
You just need to sign in to Wayfarer and begin a review whilst having the Wayfarer+ extension installed, the presence doesn't display title or description correctly with the "Description links to Google search..." option enabled.

**Expected Behavior**
The title and/or description of the nomination should be displayed in the presence, instead of always "Getting ready to review a location..."

**Screenshots**
https://prnt.sc/129spl9
https://prnt.sc/129sq1r

**Environment**
- OS: Windows 10
- Browser: Firefox
- Version: 90.0a1 (2021-04-28) (64-bit)

**Additional context**
I think the presence should be updated to support the Wayfarer+ extension, it is extremely commonly used within the Niantic Wayfarer community. Most people who use this website will use the extension, and unfortunately it breaks this presence.

**Comment by GiraffeCubed** [comment]
Closed and reopened after further investigating and to word it a bit better.

**Comment by ririxidev** [comment]
@Bas950

**Comment by theusaf** [comment]
As the extension is no longer working and no longer maintained, this issue no longer applies.
