### ISSUE TITLE
[Presence | Bug] Jellyfin

### ISSUE THREAD

**Issue by Dirky14** [PreMiD/Presences#3617]
**Describe the Bug**
When I see a content on Jellyfin, it shows on discord "Watching unknown content, no metadata could be obtained". I'm on Linux, with premid v 2.3.2 and ext 2.2.3

**Steps to Reproduce**
1. Install Jellyfin plugin
2. Go watch Jellyfin content
3. See the status on discord

**Expected Behavior**
Show the episode information

**Screenshots**
![image](https://user-images.githubusercontent.com/34884665/116669830-5243c780-a99f-11eb-8ee7-d3c83f9049f9.png)

**Environment**

- OS: Debian 10 
- Browser: Firefox
- Version: Premid 2.3.2, extension 2.2.3

**Comment by alexbcberio** [comment]
Thanks for the report, could you check what version of Jellyfin are you using?
I'll take a look at it

**Comment by Dirky14** [comment]
The last version, 10.7.2 ! Thanks !

**Comment by alexbcberio** [comment]
What type of content are you watching? I checked with a TV-Show and a Movie and its working fine. Some library types are not supported and are treated as "unknown" it could be that.

Here are some screenshots of what I'm getting.

![Watching TV-Show](https://user-images.githubusercontent.com/22194879/116790871-008e6080-aab7-11eb-98df-ac796305bc21.png)
![Watching Movie](https://user-images.githubusercontent.com/22194879/116790885-13a13080-aab7-11eb-88c8-1f7ca2774c46.png)

**Comment by Dirky14** [comment]
Films, anime, and TV show. The three are watching unknown content

**Comment by alexbcberio** [comment]
Hmm, I cannot reproduce the issue. Could we take a look at it through Discord?

**Comment by Dirky14** [comment]
Yup ! I will send you an PM

**Comment by alexbcberio** [comment]
Hello, I've updated the presence. It should be working ok now on Firefox.
