### ISSUE TITLE
Gentoo Wiki | https://wiki.gentoo.org/wiki/

### ISSUE THREAD

**Issue by 0ae** [PreMiD/Presences#3619]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
https://wiki.gentoo.org/wiki/

**What should the Presence display?** 

Show which page you're on (i.e. you're on https://wiki.gentoo.org/wiki/Systemd , then it'd display the playing as

Gentoo Wiki
Browsing the Systemd article (or something like that i'm not entirely sure.
xx:xx elapsed (xx:xx is the time spent on that site)

(button here to click on to get to the page to read it

**If possible, please provide a logo for the service (512x512 minimum)** 

(I don't know how to upload images on GitHub)

https://upload.wikimedia.org/wikipedia/commons/4/48/Gentoo_Linux_logo_matte.svg

https://www.gentoo.org/assets/img/logo/gentoo-3d-small.png (smaller than 512x512 though)

https://www.gentoo.org/assets/img/logo/gentoo-3d.png

**Comment by ririxidev** [comment]
Ehhh... I don't see sense to have presence for this sorry.
