### ISSUE TITLE
Reddit Presence doesn't work

### ISSUE THREAD

**Issue by itsHanSolo** [PreMiD/Presences#3626]
**Describe the Bug**

Reddit Presence doesn't work

**Steps to Reproduce**

1.
2.
3.

**Expected Behavior**

**Screenshots**

**Environment**

- OS:  Windows 10
- Browser:  Edge
- Version:   Version 90.0.818.51 (Official build) (64-bit)
  

**Additional context**

**Comment by ririxidev** [comment]
provide more info.
