### ISSUE TITLE
[Bug | Presence] Crunchyroll: Presence doesn't work on the beta site

### ISSUE THREAD

**Issue by ZigTag** [PreMiD/Presences#3627]
**Describe the Bug**

When using the beta version of the website no statuses show up

**Steps to Reproduce**

1. Try viewing https://beta.crunchyroll.com/watch/GR8V1MJ9R
2. Then try to look at your status

**Expected Behavior**

The status should show up displaying that I am watching a show

**Screenshots**

**Environment**

- OS: Windows 10 
- Browser: Firefox Developer Edition 
- Version: 89.0b6 (64-bit) 
  

**Additional context**

I tried fixing this myself actually by adding the URL to the crunchyroll metadata file, but I could not get the file to compile without having to basically rewrite the entire thing due to the abundant use of the `any` type and my lack of knowledge of this extension

**Comment by ZigTag** [comment]
I noticed #3600 exists but it seems to be closed by the author for some reason so I opened a new one

**Comment by ririxidev** [comment]
obviously, site is only for stable version as far I know. Closing.
