### ISSUE TITLE
AnimeFLV URL Links

### ISSUE THREAD

**Issue by Douta178** [PreMiD/Presences#3628]
Hi, My name si Douta, I want to recommend a new URL for animeflv which is this one here: https://m.animeflv.net/ . Thanks for your attention.

**Comment by ririxidev** [comment]
Check out [Bug report template](https://github.com/PreMiD/Presences/issues/new?assignees=&labels=&template=bug_report.md) or [Feature request template](https://github.com/PreMiD/Presences/issues/new?assignees=&labels=&template=feature_request.md)
