### ISSUE TITLE
Funcraft Shop Premid.

### ISSUE THREAD

**Issue by sunqo** [PreMiD/Presences#3635]
1: The site is visited a lot, over 2 million people registered on the site.

2: The site dates from 2016.

3: No.

4: No.

5: No.

6: No.

7: Yes because a lot of people playing on the server expect the site on premid, And the visual and voluntary for the kind of site.

8: .sunqo # 0003

9: https://www.funcraft.net/

10: ex: Look at the Profile of ... / Version Français if possible : Regarde le Profil de ...
Look at the Forum ... / Regarde Le Forum ...
See The Leaderboard (Game Mode) (Date) / Regarde Le Classement (Mode de jeu) (Date)
Check out The Funcraft Store. /  Regarde La Boutique Funcraft.
Look at The Funcraft Home. / Regarde L'Accueil Funcraft.

[11:]([url]([url](url)))
![logo fc](https://user-images.githubusercontent.com/83520570/116797782-e0c46000-aae9-11eb-828e-40f13b795642.png)

**Comment by ririxidev** [comment]
Use service request template
