### ISSUE TITLE
Hotstar Presence Add

### ISSUE THREAD

**Issue by itsELECTRON** [PreMiD/Presences#3648]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 

**What should the Presence display?** 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by itsELECTRON** [comment]
1. Yes this website is famous
2. Yes , it is older than 2months
3. Yes , for India
4. Yes it is , its Disney+ for India
5. Yes , it does have some 18+ webseries like Game Of Thrones , The Wire , etc
6. No im not a donator
7. Yeah  i do acknowledge it
8. My discord username is itsELECTRON#4573
9. The name of the service is Disney+ Hotstar
10. The presence should display either HOtstar or Disney+
11. Logo attached ..

![hotstarlogo](https://user-images.githubusercontent.com/66776648/116894704-fe133e80-ac4f-11eb-83ba-a303e118a17e.png)

**Comment by FujiYamamoto** [comment]
It's already there..
![image](https://user-images.githubusercontent.com/82749800/116901593-be505500-ac57-11eb-8ddf-753f1a637428.png)

**Comment by itsELECTRON** [comment]
No Sir ,
It's Disney+ and no Disney+ Hotstar
Disney+ has tied up with the Indian streaming platform Hotstar in order to
function in India
The presence websites for Disney+ only include www.disneyplus.com which
isn't available in India
This website in India is availible as www.hotstar.com rather and it is not
present in the presence store for Premid

I appreciate your work and hope this gets added too soon

Waiting for a revert

Thank You

**Comment by ririxidev** [comment]
@itsELECTRON This presence works with Hotstar too.

**Comment by ririxidev** [comment]
This presence works on `disneyplus.com` and on `hotstar.com`. It doesn't show it but regex url is good and detects two of these domains. Don't say misleading things thanks.

**Comment by itsELECTRON** [comment]
Oh
I'm sorry about that
But it doesn't work with me :-(

**Comment by itsELECTRON** [comment]
[image: image.png]
fyi

**Comment by ririxidev** [comment]
So create bug report not service request.

**Comment by itsELECTRON** [comment]
Ok, thanks.
