### ISSUE TITLE
EverSkies | everskies.com

### ISSUE THREAD

**Issue by pixieguts** [PreMiD/Presences#3649]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** https://everskies.com/ 

**What should the Presence display?** on forums, on profile, on another persons profile, playing games, on the shops 

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/83602559/116905683-eb274c80-ac04-11eb-9263-43359f5373b2.png)

**Comment by SlowLife1661** [comment]
Will be working on this
