### ISSUE TITLE
Funcraft | funcraft.net

### ISSUE THREAD

**Issue by sunqo** [PreMiD/Presences#3650]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  .sunqo#0003

**What's the name of the service?**  www.funcraft.net

**What should the Presence display?**  Look at the Profile of ... / Version Français if possible : Regarde le Profil de ...
Look at the Forum ... / Regarde Le Forum ... (fr)
See The Leaderboard (Game Mode) (Date) / Regarde Le Classement (Mode de jeu) (Date) / (fr
)Check out The Funcraft Store. / Regarde La Boutique Funcraft. (fr)
Look at The Funcraft Home. / Regarde L'Accueil Funcraft. (fr)

**If possible, please provide a logo for the service (512x512 minimum)**  ![116797782-e0c46000-aae9-11eb-828e-40f13b795642](https://user-images.githubusercontent.com/83520570/116914279-d077c680-ac4a-11eb-8fd6-6e7d89d0c432.png)

**Comment by MareGraphics** [comment]
Could you contact me on discord: Harold#7518, @sunqo
