### ISSUE TITLE
PreMid doesnt work for Spotify podcast 

### ISSUE THREAD

**Issue by Kush2211** [PreMiD/Presences#3654]
**Describe the Bug**
 Premid is not able to show what spotify podcast am listening to 

**Steps to Reproduce**

1.
2.
3.

**Expected Behavior**
 when I play a podcast on Spotify it is supposed to show what am listening to in my discord profile but it doesn't show. 

**Screenshots**

![image](https://user-images.githubusercontent.com/83632092/116969109-58091800-acd3-11eb-81bc-85820af6f900.png)

**Environment**

- OS:  Windows 10
- Browser:  Chrome
- Version:   90.0.4430.93 (Official Build) (64-bit)
  

**Additional context**
 ffd

**Comment by ririxidev** [comment]
Well, obviously. PreMiD only works with website apps not applications.
