### ISSUE TITLE
Wizarding World | wizardingworld.com

### ISSUE THREAD

**Issue by winnerzRBLX** [PreMiD/Presences#3658]
**Prerequisites and essential questions** 
- [x] Is it a popular site? 
- [x] Is the website older than 2 months?  
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** winner#0001

**What's the name of the service?** https://wizardingworld.com | Wizarding World

**What should the Presence display?** If you're taking any sorting quizzes, HP quizzes, etc. and if you're browsing through articles!

**If possible, please provide a logo for the service (512x512 minimum)** 
![345808K1h_PatchBuild_WZD_LogoGoblet_On_Black-Lo-Rez](https://user-images.githubusercontent.com/83658630/117027838-15434200-accb-11eb-924f-03aee24958b2.jpg)

**Comment by joerkig** [comment]
Presence was added
#3754

**Comment by ririxidev** [comment]
Resolved in #3754
