### ISSUE TITLE
scratch.mit.edu

### ISSUE THREAD

**Issue by BluebellGamer** [PreMiD/Presences#367]
**What's the name of the service?**
scratch.mit.edu

**What should the Presence display?**
Current Search, editor, or viewer 

**Why do you want support for this service?**
 I want support for this service so other people can see the projects i am looking at.

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image
![image](https://user-images.githubusercontent.com/42038239/66277801-1438fd00-e869-11e9-9461-27c57e53e6e0.png)

**Comment by callumok2004** [comment]
I will see if I can get this done tomorrow!

**Comment by callumok2004** [comment]
Update:
I have gotten a huge amount done today, but for private reasons, it will have to be tomorrow or later in the week that I get the presence finished and published for you!

**Comment by frozaum** [comment]
#385
