### ISSUE TITLE
PicoTube | picotube.online

### ISSUE THREAD

**Issue by picotube** [PreMiD/Presences#3671]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Shoichi#3085 

**What's the name of the service?** PicoTube 

**What should the Presence display?** must show the anime you are watching at the moment, what is the episode and the elapsed time "If possible the time"
Just like other sites (e.g. Crunchyroll, Netflix) 

**If possible, please provide a logo for the service (512x512 minimum)** 
![picotube logo](https://user-images.githubusercontent.com/77746168/117337605-31a5d100-aebb-11eb-843f-f3d384122af5.jpg)

**Comment by DarkVillager** [comment]
Assign me chief!
