### ISSUE TITLE
Zombs Royale | zombsroyale.io

### ISSUE THREAD

**Issue by BitCrack** [PreMiD/Presences#3680]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
BitCrack#2024

**What's the name of the service?** 
zombsroyale.io | Zombs Royale

**What should the Presence display?** 
Title: Zombs Royale / zombsroyale.io
State: In-game [or] Waiting in lobby/Waiting for a game
Details: Time elapsed [and/or] Players/Teams left [and/or] Players/Teams killed
(Details can either display one of the suggested stats or alternate between them)

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/19538752/117521331-7f026b00-afad-11eb-9eae-178408a06432.png)
or
![image](https://user-images.githubusercontent.com/19538752/117521335-84f84c00-afad-11eb-9273-559d02827977.png)

**Comment by ririxidev** [comment]
From what I see - it's not possible to get any info since it is rendered in html canvas.

**Comment by BitCrack** [comment]
> From what I see - it's not possible to get any info since it is rendered in html canvas.

Wouldn't it be possible to get the values directly through Javascript?
There were various methods for finding out pointers and offsets to get correct values when I was playing with reverse-engineering games, so I thought the same could be possible with these types of games?

**Comment by ririxidev** [comment]
I was looking at `window` object rn and I don't see anything that has assigned variables that you can use to show on presence.

**Comment by BitCrack** [comment]
> I was looking at `window` object rn and I don't see anything that has assigned variables that you can use to show on presence.

Does it need to be something "inside" the `window` object?
I found a simple global called `game` after guessing possible names for anything that can hold the game's state, but I haven't looked into it deeper and it might be worth doing so.
Either way, I think this should be opened because I'm sure there is a way to get information about the game since you well, can't hide it from the client if it's using it. And if there's someone dedicated enough to fight against the possible obfuscation, they might find appropriate variables, functions, or whatever.

**Comment by MrBartusek** [comment]
Yep `game.currentGameState` holds current game state, I'll work on this

**Comment by MrBartusek** [comment]
Okay, to be honest, I'm not sure if that is possible, there is no way to access `game` from premid, it just isn't there. I can without problems access it from the console or programmatically created from `<script>` elements but not from the presence script itself. Maybe it can be done by creating `<script>` element and somehow moving data from it to presence script but from my research, it's not possible.

**Comment by ririxidev** [comment]
Because you can only access window.`<stuff>` variables with getPageletiable()

**Comment by ririxidev** [comment]
If you really need that - try checking [Rythm Presence](https://github.com/PreMiD/Presences/blob/master/websites/R/Rythm/presence.ts#L461) that has custom function for it - I'm allowing you to do it
