### ISSUE TITLE
[Bug | Presence] Youtube

### ISSUE THREAD

**Issue by DarkVillager** [PreMiD/Presences#3683]
**Describe the Bug**

Youtube Presence doesn't show on home page if you go to it using [a direct link](https://www.youtube.com/) but it does if you go to e.g. subs and then after go to the home page by clicking the home button.
**Steps to Reproduce**

1. Go to the homepage by pasting the url
2. Check Discord for the presence not showing

**Expected Behavior**

To Show Homepage even when visiting it by url.
**Screenshots**

![image](https://i.gyazo.com/0c371baf699b9436e68208f1a4d66ef6.gif)

**Environment**

- OS:  Windows 10 (Newest Version)
- Browser:  Chrome
- Version:  90.0.4430.93
  

**Additional context**

**Comment by ririxidev** [comment]
Works fine for me just by going to youtube.com
![image](https://user-images.githubusercontent.com/9348108/117535756-8484a300-aff7-11eb-8741-28d36c43c3c1.png)
