### ISSUE TITLE
Taiko Web | taiko.bui.pm

### ISSUE THREAD

**Issue by CLJKEDS** [PreMiD/Presences#3702]
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

** 太鼓ウェブ - Taiko Web https://taiko.bui.pm/ ** EX https://youtu.be/-6RHAyghrPc

** Thinks that should be added are see that your in the menu and looking around for song and what song is playing in game when you start playing a song. If it 1p or 2p game that your in and if there something that interest you guys that wood be interesting to add than add it. **

**
![Taiko Web](https://user-images.githubusercontent.com/64808358/117623631-5082bc80-b174-11eb-9d92-82e832a566d0.png) **

**Comment by ilovetaikonotatsujin** [comment]
I can’t get in the website
