### ISSUE TITLE
[Presence | Bug] Emby

### ISSUE THREAD

**Issue by JReverse** [PreMiD/Presences#3703]
**Describe the Bug**
My Emby site not showing on discord RPC

**Steps to Reproduce**
1. Install emby presense
2. Goto emby domain of yours example myembysite.com
3. Play video

**Expected Behavior**
Show videos playing

**Screenshots**
![image](https://user-images.githubusercontent.com/40630518/117624479-9458d000-b13a-11eb-8598-a64107e1f608.png)

**Environment**
- OS:  Windows 10
- Browser: Chrome
- Version: 90.0.4430.93

**Additional context**
None

**Comment by ririxidev** [comment]
@alexbcberio

**Comment by alexbcberio** [comment]
I will take a look at it, it has been long since I last updated it.
I will also sync it with Jellyfin presence features as that is the one I mainly focus.

**Comment by alexbcberio** [comment]
I've updated the Emby presence and it should be working fine now, check once the pull request gets merged.
