### ISSUE TITLE
slither.io

### ISSUE THREAD

**Issue by BluebellGamer** [PreMiD/Presences#371]
**What's the name of the service?**
Slither.io

**What should the Presence display?**
Rank, Length

**Why do you want support for this service?**
So people can see that i am playing slither and if i am good at the game or not lol

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image
![Slither](https://user-images.githubusercontent.com/42038239/66281075-45242c80-e87f-11e9-91f4-ca40825329de.png)

**Comment by callumok2004** [comment]
I will create a presence for slither.io within the next 24 hours, I will let you know once it is done!

**Comment by callumok2004** [comment]
I have finished this presence, it has now been added to the store!
