### ISSUE TITLE
[Presence | Bug] Reddit

### ISSUE THREAD

**Issue by prorounak2005** [PreMiD/Presences#3711]
**Describe the Bug**
 Reddit presence is not working. 

**Steps to Reproduce**

1. Go to https://www.reddit.com/
2. Make sure Premid application is working and the reddit presence is installed.
3. Go to ur activity status and it doesnt work.

**Expected Behavior**
 I was expecting the reddit presence to work.

**Screenshots**

https://imgur.com/a/cnO7prC
https://imgur.com/a/99xW2f3

**Environment**
 
- OS:  Windows 10 Pro x64
- Browser:  Brave 
- Version:  Brave  v1.24.84  (x64)

**Comment by ririxidev** [comment]
![image](https://user-images.githubusercontent.com/9348108/117964282-b6607700-b321-11eb-998c-167ef1dae353.png)

**Comment by DarkVillager** [comment]
Can't reproduce.
**Environment**

OS: Windows 10 OS Version 2009 (Build 19042.985)
Browser: Chrome
Version: 90.0.4430.212

**Comment by Isa27-0** [comment]
> Can't reproduce.
> **Environment**
> 
> OS: Windows 10 OS Version 2009 (Build 19042.985)
> Browser: Chrome
> Version: 90.0.4430.212

Maybe it only happens with this browser, for me it is also working correctly  (Opera GX)

**Comment by ririxidev** [comment]
![image](https://user-images.githubusercontent.com/9348108/118931645-8c253f80-b947-11eb-9043-f69e600f7e06.png)
![image](https://user-images.githubusercontent.com/9348108/118931737-934c4d80-b947-11eb-8925-4a3baef6c456.png)

Tested with:
Browser: `Microsoft Edge Version 92.0.892.0 (Official build) canary (64-bit)`
OS: `Windows 10 & macOS`
Extensions: `PreMiD, uBlock Origin, Honey, Dark Reader, Bitwarden, SponsorBlock for YT`

**Comment by Isa27-0** [comment]
I checked again in the console, but there is no error, at least in my browser, as I said before.
(Opera GX (x64) Version: LVL 2 (core: 75.0.3969.267)
 
![image](https://user-images.githubusercontent.com/68751594/119210329-fcd07700-ba81-11eb-81ca-b89df73e24c6.png)

Of course, I am not saying that the bug should be dismissed, but it is probably only occurring in some browsers.

**Comment by prorounak2005** [comment]
It is not working for me though and there are lot of errors in my console
1) Browser - `Brave` 
2) Extensions - `Premid Beata 2.2.4.1` , `Ublock Origin` , `AutoCookie Delete `, `Mal Sync`,  `Sponsor Blocker for youtube` . I tried it with chrome and edge but still it didn't work.

**Comment by callumok2004** [comment]
Works for me, chrome, premid beta.
![image](https://user-images.githubusercontent.com/35779365/119242635-6d959300-bb57-11eb-943b-ab5d6178f24c.png)

**Comment by prorounak2005** [comment]
Not working for me 
![image](https://user-images.githubusercontent.com/69617708/119251481-648edb00-bbc4-11eb-916a-f15abb3c8bfd.png)

**Comment by DarkVillager** [comment]
I made some discoveries:

Chrome:
Logged in: Works. Console logging document.querySelector("span._1GieMuLljOrqnVpRAwz7VP") returns span.
Logged out: Doesn't work but No error. Console logging document.querySelector("span._1GieMuLljOrqnVpRAwz7VP") returns null.
Edge:
Logged in: Works. Console logging document.querySelector("span._1GieMuLljOrqnVpRAwz7VP") returns span.
Logged out: Doesn't work & Errors. Console logging document.querySelector("span._1GieMuLljOrqnVpRAwz7VP") returns null.

Proof it works on edge while logged in:
![image](https://user-images.githubusercontent.com/42322979/119252552-44075680-bbad-11eb-9fbd-baafcf5a7023.png)

**Comment by Isa27-0** [comment]
Really the error is only from this page
![image](https://user-images.githubusercontent.com/68751594/119266449-4b385f80-bbc1-11eb-8180-7b73ecce4391.png)
