### ISSUE TITLE
Anitube.in | anitube.in

### ISSUE THREAD

**Issue by ericlyssyllas** [PreMiD/Presences#3719]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Ericlys Syllas (Pain Tendo)#9748

**What's the name of the service?** 
https://www.anitube.in/

**What should the Presence display?** 
Show that I am on the homepage, what I am watching at the moment, in addition to some secondary pages such as list of anime, dramas, tokusatsus and so on. 

**If possible, please provide a logo for the service (512x512 minimum)** 
- https://i.imgur.com/pL1fgAo.jpg
- https://i.imgur.com/hjxgxyG.png

**Comment by vahya** [comment]
I can do this
