### ISSUE TITLE
DailyWire | dailywire.com

### ISSUE THREAD

**Issue by winnerzRBLX** [PreMiD/Presences#3743]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) - somewhat, but mostly free
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** winner#0001

**What's the name of the service?** https://www.dailywire.com/ | The Daily Wire

**What should the Presence display?** It should display what article you're reading, if you're browsing the home page, or if you are watching a video.

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/83658630/118406804-719f4d80-b64b-11eb-99be-babb43102100.png)

**Comment by joerkig** [comment]
Presence was added
 #3758

**Comment by ririxidev** [comment]
Resolved in #3758
