### ISSUE TITLE
[Presence | Bug] Crunchyroll

### ISSUE THREAD

**Issue by MineSenpai** [PreMiD/Presences#3757]
**Describe the Bug**
If I change the episode, the status is not updated, but the old episode remains with the timestap 0:00 
**Steps to Reproduce**

1. Start the Crunchyroll Presence
2. Start Crunchyroll
3. Watch any episode for a few minutes and switch episodes  

**Expected Behavior**

The episode should be updated in status

**Screenshots**

**Environment**

- OS: MacOS High Sierra
- Browser: Opera GX
- Version: 75.0.3969.244 (64 Bit)

**Comment by ririxidev** [comment]
@TheDropX

**Comment by EncryptedDev** [comment]
Unable to reproduce, likely isn't an issue anymore, reopen if it is
