### ISSUE TITLE
Remove a Goyabu Presence

### ISSUE THREAD

**Issue by Yuujet** [PreMiD/Presences#3761]
**Describe the Bug**

**Steps to Reproduce**

1. Because of this way of opening the player in another tab, it is not possible to get the video iframe.
2. So, I humbly ask you to exclude that presence.

**Expected Behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/42509424/118517534-4b3de880-b705-11eb-8974-2203cad999ea.png)
*Image translation*
- For security reasons and so that the site does not fall.
- The episode will open on a new page.

**Environment**

- OS: 
- Browser: 
- Version: 
  

**Additional context**

**Comment by ririxidev** [comment]
Well - that's not a bug. And you can do this by yourself by creating pull request then :)
