### ISSUE TITLE
[Presence | Bug] SuperAnimes

### ISSUE THREAD

**Issue by Gabriel4927** [PreMiD/Presences#3770]
**Describe the Bug**

The url of the presence "SuperAnimes" is wrong, update to "https://www.superanimes.com"
**Steps to Reproduce**

1. Start SuperAnimes presence
2. Start SuperAnimes
3. Watch any episode

**Expected Behavior**
The status be updated on the Discord

**Screenshots**
https://i.imgur.com/5UYdiXw.png

**Environment**

- OS: Windows 7 
- Browser: Edge
- Version: 90.0.818.62 (32 bits)
  

**Additional context**

They changed the URL and now the presence doesn't work anymore

**Comment by ririxidev** [comment]
@Nanashinn
