### ISSUE TITLE
CFR | Council on Foreign Relations

### ISSUE THREAD

**Issue by Vagabondit** [PreMiD/Presences#3771]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Vagabond# 0001
**What's the name of the service?** 
Council on Foreign Relations
**What should the Presence display?** 
It should display the following:
- Articles being read
- Pages being viewed
- Time Stamp of how long said page is being viewed
- Buttons that link to the pages you're on

**If possible, please provide a logo for the service (512x512 minimum)** 
![cfr](https://user-images.githubusercontent.com/48355895/118723154-55f39d00-b82d-11eb-9505-dbb0c737b86b.png)

**Comment by ririxidev** [comment]
That's kinda meh :/

**Comment by Vagabondit** [comment]
> That's kinda meh :/

What do you mean? It's one of, if not the most powerful organizations in the world lol

- Current and past presidents
- Members of the press from all around the world
- World renowned scientists
- world-renowned foreign policy experts

It's as big as it gets, plus they do legitimate journalism.

**Comment by ririxidev** [comment]
And? I'm talking about website itself not organization. I don't look what this organization is or something. I look on website.

**Comment by Vagabondit** [comment]
> And? I'm talking about website itself not organization. I don't look what this organization is or something. I look on website.

The website is a world-renowned research and news publisher. I got the NYT made, I'm sure I could get BBC made, why is the CFR an issue? Perhaps I'm missing something
