### ISSUE TITLE
[Presence | Bug] Google Meet

### ISSUE THREAD

**Issue by JustCoding227** [PreMiD/Presences#3775]
**Describe the Bug**
When I install the Google Meet Presence from the Presence Store, the Presence doesn't show my Meet status. The status works for FireFox, but does not work for Chrome.

**Steps to Reproduce**
Example of the errors I get when I'm in a Meet https://imgur.com/a/jIym4Yl

Also, sometimes when I go into a Meet from meet.google.com and not directly from another page, the status, "Waiting on page" doesn't appear when I'm actually on the page, but stays even when I go into a meet.

**Expected Behavior**
When I go into a Google Meet on Chrome, my Discord status should be reflected to what's happening. If there are 30 users in the room, my status should say that I'm playing Google Meet with 30 users in the room.

**Environment**

- OS: Windows 10
- Browser: Chrome
- Version: Version 90.0.4430.212 (Official Build) (64-bit)
  

**Additional context**
Nothing really to add, it's basically just the presence not working from the errors I linked above.

**Comment by ririxidev** [comment]
Fixed in 7e1a07d3b7f2e1f2550c260dd99005cfd035ca00
