### ISSUE TITLE
A video tutorial on how to develop a PreMid Presence

### ISSUE THREAD

**Issue by Rxann** [PreMiD/Presences#3784]
**Is your feature request related to a problem? Please describe.**
No, I am suggesting that PreMid creates a video tutorial on how to develop a presence. 
I have attempted to create a PreMid presence and I read all of the Documentation and I was very frustrated when I couldn't follow the documentation and got lost. I also belive that many members of the PreMid community would create presences if they had a video tutorial to follow.

**Describe the solution you'd like**
I would like PreMid to make a video tutorial to go through the steps of making a presence and then the people wishing to create a presence can tweak the things shown in the video.

**Describe alternatives you've considered**
I have searched the Youtube and Google to try to find a tutorial on developing a PreMid presence, but no one makes content on this topic.

**Additional context**
None

**Comment by ririxidev** [comment]
https://docs.premid.app/dev/presence - will be rewrited soon - and we don't really havesomeone that would do that.

**Comment by Rxann** [comment]
Thank You very much.
