### ISSUE TITLE
HackTheBox | hackthebox.eu

### ISSUE THREAD

**Issue by BLITZ-GIT** [PreMiD/Presences#3785]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** BLITZ#7777 

**What's the name of the service?** www.hackthebox.eu 

**What should the Presence display?** What you're doing on the website, like which competition are you doing right now

**If possible, please provide a logo for the service (512x512 minimum)** https://www.google.com/imgres?imgurl=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1278681947531644928%2FGpj6Vi6h_400x400.jpg&imgrefurl=https%3A%2F%2Ftwitter.com%2Fhackthebox_eu&tbnid=LXlBfMLUgvctJM&vet=12ahUKEwi9ve3lrtvwAhWFgKQKHbneDJIQMygBegUIARCkAQ..i&docid=XKiNLNmRqGahcM&w=400&h=400&q=hackthebox&ved=2ahUKEwi9ve3lrtvwAhWFgKQKHbneDJIQMygBegUIARCkAQ

**Comment by Rxann** [comment]
Hey,
Would you be cool if I developed this presence?

**Comment by BLITZ-GIT** [comment]
> Hey,
> I am going to develop this an I will comment the link to the presence when I am done

Thanks Rxann

**Comment by Rxann** [comment]
Hey,
I am going to try my best it just will take a little bit because I am newer.
