### ISSUE TITLE
learn.keshart.in

### ISSUE THREAD

**Issue by Johii-OOF** [PreMiD/Presences#3790]
**Prerequisites and essential questions** 
- [X] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Johii#6944

**What's the name of the service?** 
_https://learn.keshart.in/_  | Kesh Art

**What should the Presence display?** 
_Teacher, time left, duration, Percentage of the course completed._

**If possible, please provide a logo for the service (512x512 minimum)**  
![image](https://user-images.githubusercontent.com/79909868/119221642-e112b280-bb0d-11eb-8ef3-441ca3394be7.png)

**Comment by ririxidev** [comment]
Site doesn't provide a lot of info and it would need to be whole domain not only this specific subdomain.
