### ISSUE TITLE
MinecraftTR | minecrafttr.com

### ISSUE THREAD

**Issue by turknone** [PreMiD/Presences#3791]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** TurkNigga#0522

**What's the name of the service?** https://minecrafttr.com | MinecraftTR

**What should the Presence display?** [TR]Hangi forum konusunu okuduğunu, sitede nerede dolaştığı vb. [EN Translate] What forum topic he's reading, where he's navigating the site, etc

**If possible, please provide a logo for the service (512x512 minimum)**  
![minecrafttr](https://user-images.githubusercontent.com/82033370/119232704-da486780-bb2e-11eb-97d1-335c5a2204f8.png)

**Comment by callumok2004** [comment]
Can you also provide a square image? 512x512 minimum.

**Comment by turknone** [comment]
thanks

Callum OKane ***@***.***>, 23 May 2021 Paz, 01:40 tarihinde
şunu yazdı:

**Comment by turknone** [comment]
![minecrafttr](https://user-images.githubusercontent.com/82033370/119250508-3223b480-bba9-11eb-931c-74a9d90869b1.png)
