### ISSUE TITLE
Updating the "voiranime" presence.

### ISSUE THREAD

**Issue by takasensei** [PreMiD/Presences#3795]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** taka`#0012

**What's the name of the service?**  https://voiranime.com/

**What should the Presence display?** 
If it can be displayed in the same way as Crunchyroll it would be perfect (name of the anime, number of the episode + title of the episode, real-time display of where we are in the episode). Everything would be displayed in French since the site is French, and when looking for an anime, it would simply be displayed "seeks. There is already a presence for this site but the site is very old and no longer works while this one is newer and used by a lot of people, that's why I suggest that we replace the old "voiranime" by this one.

**If possible, please provide a logo for the service (512x512 minimum)** 

![voiranime](https://user-images.githubusercontent.com/84666157/119260078-6d39de00-bbd1-11eb-83ba-66e9ac9cc788.png)

**Comment by ririxidev** [comment]
Already a thing; create bug report if it doesnt work or feature request
