### ISSUE TITLE
[Presence | Bug] Voiranime

### ISSUE THREAD

**Issue by takasensei** [PreMiD/Presences#3797]
**Describe the Bug**

When I go the website "https://voiranime.com/" it shows in my discord status that I'm searching something and that I'm in the home page but when I click on an anime it no longer displays anything. Furthermore it shows in my discord that I'm in the home page and everything ONLY when I go on the website fromthe link in your website (in the presence store), so when I go on the website by searching it on Google it doesn't show anything. 

**Steps to Reproduce**

1. Go on https://voiranime.com/ (from the link here or from the link on Premid website)
2. If you go on voiranime from the link here it doesn't show anything, if you go by the 2nd method it will show that you are on the home page, searching something.
3. With the 1st method it will doesn't show anything whatever you do. With the 2nd method the presence will either stop displaying when you start an episode of anything or it will continue to display "searching" and "home page"

**Expected Behavior**

Normally it should just display the anime you are watching, with the real time display.. and the title of the anime, the episode number.

**Screenshots**

![voiranime presence](https://user-images.githubusercontent.com/84666157/119265425-f7d90800-bbe6-11eb-8566-d535ba609539.PNG)
I can't get any further.

**Environment**

- OS:  Windows 10
- Browser:  Chrome
- Version:  90.0.4430.212 (Build officiel) (64 bits)
  

**Additional context**

**Comment by ririxidev** [comment]
No one maintains that presence; so someone, feel free to fix it.
