### ISSUE TITLE
Mangarock.com

### ISSUE THREAD

**Issue by LordHainzAniflix** [PreMiD/Presences#38]
**What's the name of the service?**
https://mangarock.com/ | Mangarock

**What should the Presence display?**
Informations about the current Manga i want to read 

**Why do you want support for this service?**
Many people i know use premid and mangarock and it would be great if we could see another what they are reading when we dont have time to speak or write.

**Are you able to provide an image for the service? (512x512 minimum)**
![manga-rock-best-manga-reader-premium-v3-2-2-apk_1](https://user-images.githubusercontent.com/46389324/50719061-41b50800-1097-11e9-88d0-7e49af80d1a4.jpg)

**Comment by TheDropX** [comment]
Presence done.
