### ISSUE TITLE
Coursera | coursera.org

### ISSUE THREAD

**Issue by akashdeepghosh** [PreMiD/Presences#3806]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
https://www.coursera.org

**What should the Presence display?** 
Viewing which page (homepage or course page etc.), learning which course. PreMiD has an extension for Udemy, a similar service.

**If possible, please provide a logo for the service (512x512 minimum)** 
I could not find a 512x512 logo. Here is the logo from their [branding page](https://about.coursera.org/brand-guide/):
https://i.imgur.com/N1JD9gz.png

**Comment by yaasin12** [comment]
+1
