### ISSUE TITLE
Heroku | heroku.com

### ISSUE THREAD

**Issue by Rxann** [PreMiD/Presences#3808]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
https://heroku.com | Heroku

**What should the Presence display?** 
The presence should display That you are visiting the Heroku site, and if you are making an app it should display that.

**If possible, please provide a logo for the service (512x512 minimum)** 

![logo](https://user-images.githubusercontent.com/80224521/119348708-3d3f1900-bc6b-11eb-987e-445e0c4af100.png)

**Comment by ririxidev** [comment]
Heroku doesn't provide a lot - but I will leave it as open (but without presence request tag since I don't think that it would be good for presence)
