### ISSUE TITLE
Various sites to add

### ISSUE THREAD

**Issue by csantos987** [PreMiD/Presences#3809]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

pDragons#9847, ID 777759954086002728

**What's the name of the service?** 

Several:

- Kickstarter ( https://kickstarter.com )
- Indiegogo ( https://indiegogo.com )
- various other crowd-funding sites
- Oculus ( https://oculus.com )
- HTC ( https://htc.com )
- Deca ( https://www.deca.net )
- various other sites for VR-making
- Nintendo main pages ( https://nintendo.com/* )
- Nintendo Store pages ( https://store.nintendo.com )
- various computer and smart device manufacturers (HP, Dell, Toshiba, Samsung, LG, Xiaomi, Huawei, etc.)
- various car manufacturer companies and aggregate sellers
- various movie ticket sellers
- various movie-critic sites (Rotten Tomatoes, Metacritic)
- Patreon ( https://patreon.com )
- Ko-fi ( https://ko-fi.com )
- Toyhouse ( https://toyhou.se/ )

**What should the Presence display?** 

Crowd-funding sites:

Line 1: whether a user's browsing the home page, search, or a campaign page
Line 2: if in a search query, show search terms. If on a campaign page, show title of campaign page

Creator-based sites:

Line 1: title of user/character page being browsed or donated to

Others:

Figure it out.

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by ririxidev** [comment]
1 site per request
