### ISSUE TITLE
SubscribeStar | subscribestar.com

### ISSUE THREAD

**Issue by csantos987** [PreMiD/Presences#3812]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)*
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 

https://www.subscribestar.com | SubscribeStar

**What should the Presence display?** 

What page/profile is being viewed

**If possible, please provide a logo for the service (512x512 minimum)** 

https://ss-staging-assets.s3-us-west-1.amazonaws.com/brand/ss_logomark.png

----
*optional to view, although it is sometimes a hook vs with Patreon

**Comment by ririxidev** [comment]
Site hasn't been qualified for presence.
