### ISSUE TITLE
ToyHouse | toyhou.se

### ISSUE THREAD

**Issue by csantos987** [PreMiD/Presences#3813]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)*
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 

https://toyhou.se | ToyHouse

**What should the Presence display?** 

What user/character page a person is looking at.

**If possible, please provide a logo for the service (512x512 minimum)** 

https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/a999e788-3c89-4d2a-8907-dd8020ff0b04/ddb5gai-705a7321-ad2f-4726-9aa6-353bd9bf35a6.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2E5OTllNzg4LTNjODktNGQyYS04OTA3LWRkODAyMGZmMGIwNFwvZGRiNWdhaS03MDVhNzMyMS1hZDJmLTQ3MjYtOWFhNi0zNTNiZDliZjM1YTYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.wTKIvRGhANxVU7H8Aw1lCl4WrkHnU-8Q7s8ij7ZLRyE

--------------
*VERY much a very not-focused-upon feature of the site. Most people consider the site "SFW," with "here and there" people choosing to put in NSFW images as they please. It is unlike FurAffinity, where it's almost a _draw_ for furries who draw NSFW almost strictly.

**Comment by ririxidev** [comment]
Invite-only website. Most likely only community. Site hasn't been qualified for presence.

**Comment by csantos987** [comment]
I'm aware signup is invite-only, but the site itself actually has its character pages accessible to non-members and members alike, depending on how users choose to share the content of their characters.

Here's an example of a viewable character with a lot of development:
https://toyhou.se/5072128.vasciel-aplisto-g-isidore

**Comment by ririxidev** [comment]
Yeah sure but these profiles must be linked to even see them since there are no links on homepage to for example view popular profiles etc.

**Comment by csantos987** [comment]
Well, Google can also bring up pages for non-members when they're wanting to search without signing up.

https://www.google.com/search?client=opera-gx&q=vasciel+aplisto+g+isidore&sourceid=opera&ie=UTF-8&oe=UTF-8

**Comment by ririxidev** [comment]
You don't get my point. I already told that these profiles must be linked. It means that even if you will search it in google it will still be "linked by Google". Just site not worth presence from my perspective because of:
 - invite-only
 - you can only access profiles when they have been linked or search them in Google.
