### ISSUE TITLE
Kickstarter | kickstarter.com

### ISSUE THREAD

**Issue by csantos987** [PreMiD/Presences#3814]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 

https://kickstarter.com | Kickstarter

**What should the Presence display?** 

Line 1: whether a user's browsing the home page, search, or a campaign page
Line 2: if in a search query, show search terms. If on a campaign page, show title of campaign page

**If possible, please provide a logo for the service (512x512 minimum)** 

https://play-lh.googleusercontent.com/r4wBopBrIEeH8ICromEm1mDuzawUquXzZzYmeG22nqy_M0_KyRJKNn2v4gjfcsiOZZ0

**Comment by EncryptedDev** [comment]
Working on this, assign me
