### ISSUE TITLE
GoFundMe | gofundme.com

### ISSUE THREAD

**Issue by csantos987** [PreMiD/Presences#3816]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 

https://gofundme.com | GoFundMe

**What should the Presence display?** 

Line 1: whether a user's browsing the home page, search, or a campaign page
Line 2: if in a search query, show search terms. If on a campaign page, show title of campaign page

**If possible, please provide a logo for the service (512x512 minimum)** 

https://image.flaticon.com/icons/png/512/2111/2111427.png

**Comment by jaydenkoh** [comment]
If no one is working on it then I'll make this presence

**Comment by jaydenkoh** [comment]
do i have to make the presence for the homepage, search and campaign page only or the whole site's features

**Comment by jaydenkoh** [comment]
#4116
