### ISSUE TITLE
[Presence | Feature Request] Codecademy

### ISSUE THREAD

**Issue by RWCL** [PreMiD/Presences#3836]
**Is your feature request related to a problem? Please describe.**
While at course's syllabus , the activity status shows Looking at a course "Learn Java". Then when I click on resume course at the course's syllabus. It stays there, and disappear if I switch tabs back and forth meaning activity status will show nothing

**Describe the solution you'd like**
When learning a course I'd like to be shown I'm learning *course* in the discord activity status.

**Describe alternatives you've considered**
Adding Learning *course* (Java , Python etc).

**Comment by ririxidev** [comment]
@DoggoKt

**Comment by yaasin12** [comment]
Also doesn't show when doing a project on codecademy, it stays on dashboard and it stays on looking at a path when doing a course, doesn't show the syllabus or what topic you're learning
