### ISSUE TITLE
iBroadcast | ibroadcast.com

### ISSUE THREAD

**Issue by acid-0verride** [PreMiD/Presences#3841]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
acid_0verride#0420
**What's the name of the service?** 
iBroadcast
**What should the Presence display?** 
"Listening to xxx" .. similar to any music app
**If possible, please provide a logo for the service (512x512 minimum)** 
branding guidllines are located here: https://devguide.ibroadcast.com/?p=branding

**Comment by Isa27-0** [comment]
URL: https://www.ibroadcast.com
I realized that it is an interesting alternative to Google Play Music, unfortunately it seems that it is not famous here in Brazil, even though it is old.

**Comment by acid-0verride** [comment]
Fair enough! I might take a stab and making the presence myself in a few days
