### ISSUE TITLE
Soap2day : Presence Request

### ISSUE THREAD

**Issue by MizuleFX** [PreMiD/Presences#3845]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
www.soap2day.to | Soap2Day
www.ssoap2day.to | Soap2Day

**What should the Presence display?** 
It's a free movie/series streaming site so it should display movie/series title, time left for it to end, when did they start watching and all. Basically, what PreMid has for Netflix.

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by ririxidev** [comment]
PR is already opened
