### ISSUE TITLE
Hello, DNA has changed its DOM so it must be updated for the extension to work correctly on the site, it was just to warn you, because some features of PreMid no longer work on this site ^^.

### ISSUE THREAD

**Issue by NotSynowz** [PreMiD/Presences#3853]
**Describe the Bug**

**Steps to Reproduce**

1.
2.
3.

**Expected Behavior**

**Screenshots**

**Environment**

- OS: 
- Browser: 
- Version: 
  

**Additional context**

**Comment by ririxidev** [comment]
use description instead of title to report issue
