### ISSUE TITLE
[Presence | Bug] Wattpad

### ISSUE THREAD

**Issue by Takamiie** [PreMiD/Presences#3870]
Stories aren't showing up on Wattpad preMiD, only the home website when u browse through. the homepage shows but everything else doesn't show if u exit the home page out. also, the preMiD store itself isn't showing up on my profile as a status either. I have Game activity on, and I have PreMiD running and I have the chrome extension connected and running as well. I also tried to restart my pc but nothing worked

this is the link (https://imgur.com/i9zfXZS)
It will show the homepage only. and if u click a story or exit out the homepage and open a new tab it wouldn't show at all or if u click on a story it will always show the homepage, or show "Somewhere on the Site."
--------------
This is what it's supposed to look like. (https://imgur.com/dsYrl10)

OS: Windows 10
Browser: Chrome
Version: Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by ririxidev** [comment]
@StrikerFRFX
