### ISSUE TITLE
AnimeUltima | animeultima.to

### ISSUE THREAD

**Issue by coolads934** [PreMiD/Presences#3872]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
ecchi and harem stuff soo sure
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Adam#6362
**What's the name of the service?** 
https://www1.animeultima.to/
**What should the Presence display?** 
browsing anime
what anime is being viewed
episode number, that probably covers all of it really
**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by VocalZero** [comment]
If no one is currently doing it I would do it

**Comment by VocalZero** [comment]
@coolads934 Do you maybe have a logo of AnimeUltima?

**Comment by coolads934** [comment]
[image: image.png]

**Comment by VocalZero** [comment]
Presence is now available. Issue can be closed
