### ISSUE TITLE
DataCamp | datacamp.com

### ISSUE THREAD

**Issue by yaasin12** [PreMiD/Presences#3876]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) It is both free and paid for additional courses
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 
https://www.datacamp.com/
**What should the Presence display?** 
Showing the courses you're browsing, lesson you're viewing and exercises you're doing.
**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by MohammedGamal98** [comment]
Presence request
