### ISSUE TITLE
[Presence | Request] Plurall 

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#3881]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 

Plurall: 

- https://www.plurall.net (homepage)
- https://conta.plurall.net (URL that leads to the 'my account' tab, the start of the site after you have logged in with your account)
- https://maestro.plurall.net (URL that gives access to student content)

**What should the Presence display?** 
It is a site similar to Google Classroom, and others for studies, so it will show about activities, disciplines, etc.

**If possible, please provide a logo for the service (512x512 minimum)**
![image](https://user-images.githubusercontent.com/68751594/120664884-aee44780-c461-11eb-8328-8e87c616c804.png)

**_Help wanted:_**

This is a very restricted site, because to gain access, you must be at a school where you use the service, or use a book from affiliated publishers, which contains a QR Code for access, but we have several differences from a textbook for the another (for example, I don't have access to some functions that others who use a book have)
So, this Issue will be closed for now, if it finds some way of access for someone else, or I develop a presence, this request goes back to active.

**Comment by ririxidev** [comment]
why closed 🤔

**Comment by Isa27-0** [comment]
> why closed 🤔

It is not a qualified site at the moment. It's almost at the restriction level of the ToyHouse (#3813)
