### ISSUE TITLE
[Presence | Feature Request] Fandom

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#3883]
**Is your feature request related to a problem? Please describe.**
Fandom has updated, and received a new interface (FandomDesktop), and since it is a new interface, presence is no longer working on this particular one.

**Describe the solution you'd like**
Add support for the new theme.

**Describe alternatives you've considered**
None.

**Additional context**
I just didn't put it as a bug because presence is still supporting the old theme (Oasis):
![image](https://user-images.githubusercontent.com/68751594/120678044-16a08f80-c46e-11eb-897e-f73b53b706a5.png)

**Comment by ririxidev** [comment]
@Hans5958

**Comment by Hans5958** [comment]
Thanks for the ping. Didn't notice that FandomDesktop (the new skin) is started to being rolled out. I'll see what I can do.

Also, if I'm not wrong, this also affects the Gamepedia presence.

**Comment by Hans5958** [comment]
Apparently the new skin is still hasn't been rolled out, so this is not quite urgent. Still, I need to anticipate this for the future.

**Comment by Isa27-0** [comment]
> Apparently the new skin is still hasn't been rolled out to the public (it's still on beta), so this is not quite urgent. Still, I need to anticipate this for the future.

Okay, thank you.
