### ISSUE TITLE
ROCKRADIO.COM

### ISSUE THREAD

**Issue by kenkit** [PreMiD/Presences#389]
**What's the name of the service?**
https://www.rockradio.com/

**What should the Presence display?**
Information about the currently playing song

**Why do you want support for this service?**
Rockradio is a very popular site for streaming audio. Each track is played separately just like spotify and as a result  users can get better quality tracks.

**Are you able to provide an image for the service? (512x512 minimum)**
![apps 22785 13510798882873389 58b33862-cbf0-446a-a3fd-b7e45c7624c9](https://user-images.githubusercontent.com/1732471/66335248-47e85580-e943-11e9-8c33-9a560bb0cfbc.png)

**Comment by callumok2004** [comment]
I will see if I can get this done within the week, may I ask what would you like to see on the presence?
