### ISSUE TITLE
[Presence | Bug] Kodi

### ISSUE THREAD

**Issue by lukypisek** [PreMiD/Presences#3890]
**Describe the Bug**

So, the problem is that Kodi presence isnt working, it just dont show on discord status. I tried everything that i was told in the description, but still doesnt show. 
**Steps to Reproduce**

1.  https://github.com/PreMiD/Presences/blob/master/websites/K/Kodi/readme.md

**Expected Behavior**

I expected that the Kodi would show on my discord status
**Screenshots**

![image](https://user-images.githubusercontent.com/59487486/120904061-53c17900-c64a-11eb-97d3-947d95afd175.png)
![image](https://user-images.githubusercontent.com/59487486/120904072-676cdf80-c64a-11eb-8043-8e455dc8eab9.png)

**Environment**

- OS:  Windows 10
- Browser:  Brave
- Version:  1.25.70 Chromium: 91.0.4472.77 (Official Build) (64-bit)
  

**Additional context**

**Comment by DiscordAnaxes** [comment]
Uhh why is the website URL localhost... Only the creator of the service can access that if they are localhosting it.

**Comment by ririxidev** [comment]
obviously lol kodi is selfhosted 🤦

**Comment by Isa27-0** [comment]
I went to test, and apparently it's not working here, what's your version? @lukypisek

**Comment by lukypisek** [comment]
> I went to test, and apparently it's not working here, what's your version of Kodi? @lukypisek
> Mine is still version 18.8

Its
![image](https://user-images.githubusercontent.com/59487486/121058805-116e7800-c7c1-11eb-9612-b4092c226bf6.png)

**Comment by lukypisek** [comment]
Why was it closed? It still don’t work

Odesláno z iPhonu
