### ISSUE TITLE
Please make Presence for Codeforces

### ISSUE THREAD

**Issue by hasanakhiar** [PreMiD/Presences#3892]
**Prerequisites and essential questions** 
- [x] Is it a popular site? Of course, it is. Millions of programmers, students from all over the world visit this site on regular basis.
- [x] Is the website older than 2 months? Yes this site is more than 10 years old.
- [x] Is the site locked to a specific country/region? No
- Is the site a paid service? No
- Does the website feature NSFW content? 
-  Are you a donator/patron? No, just a regular user
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? 

**What's the name of the service?** https://codeforces.com/

**What should the Presence display?** 
Reading Blog: Blog A
Time elapsed:....

Solving Problem: Problem A
Time elapsed: .....

Banner:
![image](https://user-images.githubusercontent.com/26836162/120924337-149c3200-c6f5-11eb-8e57-55aa639f8855.png)

**Comment by ririxidev** [comment]
Edit template like it should be. No deleting or changing way how it looks.

**Comment by hasanakhiar** [comment]
> Edit template like it should be. No deleting or changing way how it looks.

Is it ok now?

**Comment by hasanakhiar** [comment]
I think template is ok now

**Comment by ririxidev** [comment]
it's not 
![image](https://user-images.githubusercontent.com/9348108/121004728-4f52a880-c78f-11eb-931c-7f939823022b.png)
