### ISSUE TITLE
StreamCraft.com

### ISSUE THREAD

**Issue by AdventureZ** [PreMiD/Presences#39]
**What's the name of the service?**
streamcraft.com | StreamCraft

**What should the Presence display?**
Informations about the current Live and streamer.

**Why do you want support for this service?**
Well, I want to display in my profile the Live (Shows) I'm currently watching on streamcraft, and I think it's cool to have more support for multiple sites.

**Are you able to provide an image for the service? (512x512 minimum)**
https://files.catbox.moe/aesxjs.png

**Comment by TheDropX** [comment]
The presence has been added. Currently available for beta users.
