### ISSUE TITLE
Edit Presence | TuMangaOnline

### ISSUE THREAD

**Issue by Litoersx33** [PreMiD/Presences#3921]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** 

**What should the Presence display?** 

**If possible, please provide a logo for the service (512x512 minimum)**

![image](https://user-images.githubusercontent.com/53166897/121730528-6b1ebd00-cab5-11eb-9b3b-1b32511d5124.png)

**Comment by ririxidev** [comment]
Already a thing
