### ISSUE TITLE
[Presence | Bug] Mangadex

### ISSUE THREAD

**Issue by alphastigma117** [PreMiD/Presences#3926]
**Describe the Bug**
Mangadex extension doesn't work. The site is back after being down for several months and i guess it needs updating

**Steps to Reproduce**

1. Opening any MD link doesn't work.
2.
3.

**Expected Behavior**
Rich presence should detect mangadex site open and display according manga title, chapter etc.

**Screenshots**

**Environment**

- OS: Windows 10
- Browser: Opera
- Version: 78.0.4079.0 64-bit
  

**Additional context**

**Comment by Isa27-0** [comment]
Apparently, the site has changed layout, that must be why the presence is not working.

----------------------------------------

Environment

- OS: Windows 10
- Browser: Opera GX
- Version: LVL 2 (core: 75.0.3969.282)
