### ISSUE TITLE
[Presence | Bug] Magister

### ISSUE THREAD

**Issue by adi170-alt** [PreMiD/Presences#3932]
**Describe the Bug**
Hi, I have an issue with magister(magister is a Netherlands school agenda system that a lot of schools in the Netherlands use), it looks like my school has subdomains, so it is not magister.net but isw.magister.net, I don't know for sure if that is the issue, but it looks like it, I don't know for sure if this is the issue, but magister is the only one that does not show op on discord

**Comment by ririxidev** [comment]
This shouldn't be the issue, since this presence has regex. I will mention presence author. @QkeleQ10

**Comment by QkeleQ10** [comment]
Hello! I can't reproduce this. Could you send me the exact URL you're on? @adi170-alt

**Comment by adi170-alt** [comment]
just the link that my school magister uses? https://isw.magister.net

**Comment by adi170-alt** [comment]
@QkeleQ10

**Comment by QkeleQ10** [comment]
@adi170-alt I'm sorry! I didn't get any notification for some reason 🤔 for me it all works. Could you send me a screenshot of the Console tab in the menu that pops up when you hit F12?

**Comment by QkeleQ10** [comment]
Actually, I can't get it to work anymore either. It worked just fine for me a couple of days ago. I'll try and see if something has changed perhaps.

**Comment by QkeleQ10** [comment]
Found it - human error. I let something expire but I've fixed it, should be resolved once my pull request gets merged.

**Comment by QkeleQ10** [comment]
Should all be fixed! @adi170-alt please close this issue if you aren't experiencing any issues anymore.

**Comment by adi170-alt** [comment]
yes, it works now, Thank u!
