### ISSUE TITLE
Alienware Arena | alienwarearena.com

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#3935]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
ItsYoBoiMario#5091

**What's the name of the service?** 
https://alienwarearena.com/ | Alienware

**What should the Presence display?** 
I have asked him and I am waiting for his answer. I will change the issue as soon as I get his answer.

**If possible, please provide a logo for the service (512x512 minimum)** 

https://cdn.browsercam.com/com.alienwarearena-logo.png

---
By Maxou (MaXfAa#1341)
**For [@ItsYoBoiMario#5091](https://discord.com/users/747370380221612112)**

**Comment by ririxidev** [comment]
ehhhh. not really for now :/

**Comment by MaXfAa** [comment]
> ehhhh. not really for now :/

Euh... Why ? 😢

**Comment by ririxidev** [comment]
because just no xd tbh; this site doesnt offer a lot
