### ISSUE TITLE
Mavanimes | mavanimes.co

### ISSUE THREAD

**Issue by MQHX** [PreMiD/Presences#3951]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

'MQHX#0314 

http://www.mavanimes.co/ 

something who looks like 4anime for example, just to see what anime you're watching and which episode, with time left ( if possible )  

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by EncryptedDev** [comment]
Presence added, #4291.
