### ISSUE TITLE
Gogoanime | gogoanime.*

### ISSUE THREAD

**Issue by 9Craft** [PreMiD/Presences#3952]
**Describe the Bug**
I have tried reinstalling the Gogoanime presence from the store, even the extension but it seems there is some problem with the presence after I talked with the moderators at the PreMiD discord server. The timestamp is broken and sometimes need to restart the browser to show presence, even after that the icon and other details fail to show up.

**Steps to Reproduce**

1.Just install PreMiD go to the presence store and get the Gogoanime presence.
2.Now go to the Gogoanime site and try to play any video and see your discord presence.

**Expected Behavior**
The timestamp is showing perfectly as it is supposed to, and the website icon is visible in presence.

**Screenshots**
![image](https://user-images.githubusercontent.com/85939913/122050211-e1e2ef80-ce00-11eb-9b5c-35076a6fd5c5.png)
![image](https://user-images.githubusercontent.com/85939913/122050231-e7403a00-ce00-11eb-9272-4f80f25250d4.png)

**Environment**

- OS: Microsoft Windows 10 Pro 10.0.19043 Build 19043
- Browser: Google Chrome
- Version: 91.0.4472.101 (Official Build) (64-bit)

**Additional context**
Not required.

**Comment by DarkVillager** [comment]
Can't reproduce. Tested with both sites.
![image](https://user-images.githubusercontent.com/42322979/128631640-714d5280-e780-401a-be39-659dc435d48e.png)
![image](https://user-images.githubusercontent.com/42322979/128631669-602321e6-a21f-4f5d-8f02-b154a1943ba3.png)
