### ISSUE TITLE
Happy Wheels

### ISSUE THREAD

**Issue by MartinSherwood1** [PreMiD/Presences#3954]
**Prerequisites and essential questions** 
- [x] Is it a popular site? 
- [x] Is the website older than 2 months?  
- [x] Is the site locked to a specific country/region?
- [0] Is the site a paid service? (e.g. Netflix, Hulu) 
- [x] Does the website feature NSFW content? (e.g. porn, etc...) 
- [0 Are you a donator/patron? 
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? 

**What's your Discord username?** MartinSherwood#5072 

**What's the name of the service?** https://totaljerkface.com/happy_wheels.tjf 

**What should the Presence display?** the happy wheels logo, the level name  

**If possible, please provide a logo for the service (512x512 minimum)**  
![image](https://user-images.githubusercontent.com/85963118/122110422-2ed9bc80-ce27-11eb-8ff7-86dbf3e060a7.png)

**Comment by ririxidev** [comment]
Well idk tbh because Happy Wheels game is on a lot of sites and it would need to be supported on these sites as well so nah.
