### ISSUE TITLE
1v1.lol

### ISSUE THREAD

**Issue by laikrai** [PreMiD/Presences#3961]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**laikrai#OOO1** 

**1v1.lol | 1v1 LOL** 

**If i'm in matchmaking** it should say for what game mode am I matchmaking
**If i'm in lobby** it should say if i'm in a party or not
**If i'm in-game** it should say what game mode am I playing and how much players is left, but if i'm playing zombies it should say on what wave am I 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by ririxidev** [comment]
I don't see anything that you could pull data from since game is made in Unity and exported to WebGL.
