### ISSUE TITLE
"Website Supported" Popup | Feature Request

### ISSUE THREAD

**Issue by dzlandis** [PreMiD/Presences#3971]
**Is your feature request related to a problem? Please describe.**
My feature is not related to a problem, just an enhancement to encourage users to use presences on PreMiD.

**Describe the solution you'd like**
My idea is for PreMiD to have a little popup that appears when a user visits a website which has presence support for the first time.

**Additional context**
I think it could be a nice little feature to PreMiD and would encourage users to use presences on websites which they did not know had a presence before or recently had a presence made.

**Comment by ririxidev** [comment]
Already requested, will be implemented.
