### ISSUE TITLE
Request for new presence anime category for indonesian subtitle

### ISSUE THREAD

**Issue by hanshinhan** [PreMiD/Presences#3975]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**hanshinhan#0001** 

**https://nontonanimeid.com/** 

**This is a website that can stream anime in full and with Indonesian subtitles** 

**https://imgur.com/a/CDbYLCW** 
![Screenshot (43)](https://user-images.githubusercontent.com/81286248/122662070-66938c00-d1ba-11eb-9919-e65239661eca.png)

**Comment by EncryptedDev** [comment]
Please provide a logo as it was on the required template

**Comment by hanshinhan** [comment]
![nontonanimeid](https://user-images.githubusercontent.com/81286248/122671832-b42beb00-d1f2-11eb-8e44-6ba45948bc28.png)
sorry i dont know about that, this is a logo

**Comment by ririxidev** [comment]
Sorry, but no. Site doesn't have a lot of subpages and only thing that would be useful would be support for video player but it wouldn't be enough to accept this presence
