### ISSUE TITLE
Zoro | zoro.to

### ISSUE THREAD

**Issue by azuxxs** [PreMiD/Presences#3976]
**Prerequisites and essential questions** 
- [x] Is it a popular site? 
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
azu#3000

**What's the name of the service?** https://zoro.to

**What should the Presence display?** A "watch on zoro.to" button in which if you click it will redirect you to the episode you are watching on the site

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by EncryptedDev** [comment]
Hi, you forgot to provide the logo 🤔
