### ISSUE TITLE
FBOX | www3.fbox.to

### ISSUE THREAD

**Issue by rabbiii** [PreMiD/Presences#3985]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** <Rushifā#6129>

**What's the name of the service?** <www3.fbox.to>

**What should the Presence display?** <like gogoanime/ animepahe it should show what i'm watching (for movie--> Movie title) (Fore series--> Season & Episode) , searching/ browsing, time left, watch now button, if possible maybe the poster of the movie>

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by vahya** [comment]
> if possible maybe the poster of the movie

Is this possible? I haven't seen it on any other presence.

**Comment by Isa27-0** [comment]
> > if possible maybe the poster of the movie
> 
> Is this possible? I haven't seen it on any other presence.

I think there's no way

**Comment by rabbiii** [comment]
> > if possible maybe the poster of the movie
> 
> Is this possible? I haven't seen it on any other presence.

![Screenshot (107)](https://user-images.githubusercontent.com/64384904/123678983-cea43b00-d868-11eb-97d3-8196a27ec43e.png)

so, When you wish to watch a particular movie and click on that, the site takes you to  a page like one in the photo where the  site provide a poster for the movie. Yes I haven't seen this feature in any other presence before but Isn't it possible to get the poster from the page itself and convert it to a proper resolution for showing it on Discord's square shaped box instead of the site's logo only?( IMO it makes sense when it's possible to even show the play/pause status and time stamp)

**Comment by ririxidev** [comment]
Look, it isn't possible because discord has limitations. Closing the topic.

**Comment by vahya** [comment]
@rabbiii do you have a good quality logo?

**Comment by rabbiii** [comment]
> @rabbiii do you have a good quality logo?

![D26CCE35-BE61-4B73-8012-56E606C61948](https://user-images.githubusercontent.com/64384904/124650825-f8d6a800-debb-11eb-89f3-dd44f4d4587a.png)
![EAD490A2-78F7-44A0-92E9-0DF8B2B5BA42](https://user-images.githubusercontent.com/64384904/124650831-faa06b80-debb-11eb-840f-01df08247676.jpeg)
taken from their twitter.
