### ISSUE TITLE
https://animedigitalnetwork.fr/ | Anime Digital Network - ADN

### ISSUE THREAD

**Issue by Zaitooo** [PreMiD/Presences#3997]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  : Zaito ✨#1666

**What's the name of the service?**  : https://animedigitalnetwork.fr/ | Anime Digital Network - ADN

**What should the Presence display?**  : Everything you do on the site

**If possible, please provide a logo for the service (512x512 minimum)**  : https://cdn.animedigitalnetwork.fr/logo/adn_logo/adn_logo_white.svg

**Comment by ririxidev** [comment]
Already a thing https://premid.app/store/presences/AnimeDigitalNetwork

**Comment by Zaitooo** [comment]
> Already a thing https://premid.app/store/presences/AnimeDigitalNetwork

Its coding is basic there is not a lot of things while I have put all the full more as the site has changed a lot its module becomes obselete but I do not want to be ungrateful or selfish in front of his work

**Comment by ririxidev** [comment]
It doesn't mean that you need to create service request when it's already in store.

**Comment by ririxidev** [comment]
If you say that code is basic, add features for yourself.

**Comment by Zaitooo** [comment]
Ah I didn't know that we could I will do the same

**Comment by Zaitooo** [comment]
> If you say that code is basic, add features by yourself.

I don't say its to hurt anyone
