### ISSUE TITLE
[Presence | Bug] Nightwave Plaza

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#3998]
**Describe the Bug**
Nightwave Plaza presence is not working.

**Steps to Reproduce**

1. Check if presence has been added, if not, add.
2. Access the website.

**Expected Behavior**
Lately the site is changing its design, and I think PreMiD is no longer recognizing it because of that.

**Screenshots**
![image](https://user-images.githubusercontent.com/68751594/123487388-34cc5c00-d5e4-11eb-94eb-89ba20e1b251.png)

**Environment**
- OS: Windows 10
- Browser: Opera GX
- Version: LVL 2 (core: 76.0.4017.208)
 

**Additional context**
None.

**Comment by vahya** [comment]
I can do this
