### ISSUE TITLE
nicovideo.jp

### ISSUE THREAD

**Issue by ManshionProd** [PreMiD/Presences#4]
**What's the name of the service?**
https://www.nicovideo.jp | NicoNicoVideo
https://live.nicovideo.jp/ | NicoNicoLive
https://game.nicovideo.jp | NicoNicoGame(RPG)
http://seiga.nicovideo.jp/manga | NicoNicoManga (also NicoNicoImage)

**What should the Presence display?**
Informations about the current video (for NicoNico Video)
Informations about the current live (for NicoNico Live)
Informations about the current played game (for NicoNicoGame)
Informations about the current Manga (for NicoNicoManga)

**Why do you want support for this service?**
NicoNico video is a very large video site, it is certainly not used much in the West, but it is the most used in Asis (much more than Youtube in Japan for example). NicoNicoVideo also integrates many additional services (some of which are exclusive) and has a large community.
NicoNico also has other services, such as NicoNico Live, or NicoNico Image/manga (and many more) .

**Are you able to provide an image for the service? (512x512 minimum)**
Sorry, but all the images I found are too small (or I didn't search very well).

(PS:sorry for my bad English)

**Comment by eai04191** [comment]
![image](https://user-images.githubusercontent.com/3516343/62752908-40701180-baa4-11e9-9ed0-b11c84733764.png)

I created a Nico Nico Live presence. It seems to be doing well.
I would like to make this public, but I don't know the correct English notation of Nico Nico Service. Can someone tell me?
Also, since the service name cannot be changed from PreMiD, it was created as a different presence now. Should they be integrated?

**Comment by frozaum** [comment]
FINALLY SOMEONE IS DOING GOD'S WORK

but answering your question @eai04191 i don't know certainly what do you mean by "Nico Nico service"and i think it shouldn't integrated with other niconico services (at least for now)

**Comment by eai04191** [comment]
thanks for the response.
Nico Nico Service means NicoNico Video, NicoNico Live, and NicoNico Seiga. English service of niconico is not found now, so I did not know if this is of a correct English of the service name.
Anyway, I'm going to create a niconico presence that combines Video, Live, and Seiga.

**Comment by frozaum** [comment]
@eai04191 yeah, by what i'm seeing niconico doesn't have a translation to niconico seiga and niconico live in english, but niconico video is correct
