### ISSUE TITLE
Xvideos.com

### ISSUE THREAD

**Issue by frorstuff** [PreMiD/Presences#40]
What's the name of the service?
XVideos

What should the Presence display?
Information about the current video playing, maybe who posted it too.

Why do you want support for this service?
because xvideos is the best brazilian porn website alongside ''a casa das brasilerinhas" and i will love to see the rich presence

Are you able to provide an image for the service? (512x512 minimum)
https://seeklogo.com/images/X/xvideos-logo-77E7B4F168-seeklogo.com.png

**Comment by TheDropX** [comment]
Presence done.
