### ISSUE TITLE
Rainmeter | *.rainmeter.net

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#4014]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** Rainmeter:

- https://www.rainmeter.net (homepage)
- https://docs.rainmeter.net (documentation page)
- https://forum.rainmeter.net (Rainmeter Forums)

**What should the Presence display?** 
Something kind of based on what we have with the presence of PreMiD itself, but also showing the name of the post and the author, in relation to the forum.

**If possible, please provide a logo for the service (512x512 minimum)** ~Unfortunately I couldn't find the classic version in a suitable size.~
![image](https://user-images.githubusercontent.com/68751594/123682423-5fefbf00-d821-11eb-9165-0ade4a69aa41.png)

**Attention**: Do not get confused with the [R-RPC (Rainmeter Rich Presence)](https://github.com/Strazdonis/R-RPC), this is a presence made by the program, not the tool's websites.

**Comment by Tharki-God** [comment]
I may try that
easy shit ig
