### ISSUE TITLE
KissAnime | kissanime.si

### ISSUE THREAD

**Issue by Mykesss** [PreMiD/Presences#4016]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Mykes#2021

**What's the name of the service?**  kissanime.si | KissAnime

**What should the Presence display?**  Same as other streaming sites (Title, Episode count, Time left etc)

**If possible, please provide a logo for the service (512x512 minimum)**  ![KissAnimeLogo](https://user-images.githubusercontent.com/50587061/123827406-2c04be80-d933-11eb-9691-ad5b1f6f2f9a.png)

**Comment by ririxidev** [comment]
create feature request.
