### ISSUE TITLE
ADDING Shopify presence

### ISSUE THREAD

**Issue by ants81** [PreMiD/Presences#4018]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** = Shopify 

**What should the Presence display?** = Time on site and/or which category your are in

**If possible, please provide a logo for the service (512x512 minimum)** http://assets.stickpng.com/images/58482ec0cef1014c0b5e4a70.png

**Comment by ririxidev** [comment]
Nope.
