### ISSUE TITLE
Songoda | songoda.com

### ISSUE THREAD

**Issue by AustinFRG** [PreMiD/Presences#4019]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
AustinFRG#**0001**

**What's the name of the service?** 
songoda.com | Songoda

**What should the Presence display?** 
Just the Songoda logo, the bold text saying Songoda, and then the other text saying "Viewing <insert page title here>"
Maybe a button that links to the page they're on.

**If possible, please provide a logo for the service (512x512 minimum)** 
![icon](https://user-images.githubusercontent.com/18236516/123848751-0ef5ce80-d8e6-11eb-949d-68e8cd2c24da.png)

**Comment by ririxidev** [comment]
not for now.
