### ISSUE TITLE
Nvidia || nvidia.com

### ISSUE THREAD

**Issue by Rxann** [PreMiD/Presences#4040]
**Is your feature request related to a problem? Please describe.**
I would like Nvidia to be added so PreMid can display when I am browsing the site.

**Describe the solution you'd like**
I would like a presence created for nvidia.com

**Describe alternatives you've considered**
I have considered building my own but I tried and it didn't work. I am building some other ones.

**Additional context**
No other context.

**Comment by ririxidev** [comment]
Ehh. No, for whole `nvidia.com` no but there is already suggestion for GeForce now!
