### ISSUE TITLE
A Problem regarding a Rich Presence text

### ISSUE THREAD

**Issue by Adicoder05** [PreMiD/Presences#4056]
I don't have any problems regarding Pre mid, Its working absolutely fine, But still just a suggestion, If you guys manage to give a space between episode no. and title will be much appreciated in the rich presence of Disney+. Thank You
![unknown](https://user-images.githubusercontent.com/86926681/124394558-98116900-dd1d-11eb-8f1c-16a277a85069.png)

**Comment by ririxidev** [comment]
Use feature request template. I gave you direct link to it.
