### ISSUE TITLE
Deezer presence bug

### ISSUE THREAD

**Issue by SnoopieTheBest** [PreMiD/Presences#4067]
**Describe the Bug**

the presence doesn't work on my discord i don't know why 

**Steps to Reproduce**

1. I restart my browser
2. I restart my premid
3. I restart my computer
4.  I remove deezer and reinstall deezer presence but nothing
**Expected Behavior**

**Screenshots**

![Capture d’écran 2021-07-06 100654](https://user-images.githubusercontent.com/52360053/124565935-dc4a5980-de42-11eb-8b25-b14e656155e0.png)

**Environment**

- OS: Windows 10
- Browser: Opera GX
- Version: 76.0.4017.208 64 bits
  

**Additional context**

**Comment by ririxidev** [comment]
it works only when you play music, it doesn't show browsing etc

**Comment by SnoopieTheBest** [comment]
I play music it that the problem
