### ISSUE TITLE
MovieBoxPro | movieboxpro.app

### ISSUE THREAD

**Issue by idknoob9OnRoblox** [PreMiD/Presences#4072]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  24kVib3z#9999

**What's the name of the service?**  www.movieboxpro.app

**What should the Presence display?**  time of the video,  button to say "watch this aswell" and what they are watching

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by vahya** [comment]
>Is the site a paid service? (e.g. Netflix, Hulu)

From what I see the site is paid/invite only
