### ISSUE TITLE
TripSit Suggestion

### ISSUE THREAD

**Issue by Hipperooni** [PreMiD/Presences#4080]
**Prerequisites and essential questions** 
- [x] Is it a popular site? Absolutely
- [x] Is the website older than 2 months?  Many years old
- [ ] Is the site locked to a specific country/region? No
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) No
- [ ] Does the website feature NSFW content? (e.g. porn, etc...) Drug centered so possibly
- [ ] Are you a donator/patron? No
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? Yes :D

**What's your Discord username?**  Hipperooni#1337

**What's the name of the service?**  TripSit and/or TripSit IRC

**What should the Presence display?**  That you're chatting in the irc, or what page you're looking at on the tripsit factsheet page

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Isa27-0** [comment]
An IRC? Huh, can it be accessed from the website? @Hipperooni 

---------------
I came back from the future to say that: I checked the site and there is access there, I don't know if it can be accepted in the [rules](https://github.com/PreMiD/Presences/blob/87163ea079f60bd42dc258f4a822584856f33f60/.github/CONTRIBUTING.md).

**Comment by vahya** [comment]
I want to do this, but only if it's allowed, can anyone confirm whether it is allowed? @ririxidev?

**Comment by ririxidev** [comment]
No.
