### ISSUE TITLE
Animes Online | animesonline.org

### ISSUE THREAD

**Issue by minicocoxt** [PreMiD/Presences#4082]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Fushi#6666
**What's the name of the service?** 
animesonline.org | Animes Online
**What should the Presence display?** 
Show and episode you are watching, time elapsed/left

**If possible, please provide a logo for the service (512x512 minimum)** 
![favicon](https://user-images.githubusercontent.com/26691265/125122098-4a08b680-e0cb-11eb-8eab-6a19aa0281a0.png)

**Comment by Faelayis** [comment]
I'm doing this

**Comment by Faelayis** [comment]
#4231
