### ISSUE TITLE
Anikuru Rich Presence Request

### ISSUE THREAD

**Issue by Omuricee** [PreMiD/Presences#4087]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**omuricee#6969** 

**https://anikuru.me | AniKuru** 

**The presence should display every aspect of the site. We will include WatchParty, Search, Genre, HomePage, Episodes and Viewing anime sections** 

**![kuru b07622a6](https://user-images.githubusercontent.com/78228716/125174116-a5e54500-e188-11eb-8d1a-b452d66d768a.png)** 

Note: This is an invite only anime website. This means only people in the discord server have access to the website. We give out invite keys from time to time.

**Comment by Isa27-0** [comment]
> Note: This is an invite only anime website. This means only people in the discord server have access to the website. We give out invite keys from time to time.

So the site is not eligible to receive a presence, see the case of ToyHouse (#3813), if I'm not mistaken, sites that are only accessed by invitation are not accepted.

**Comment by ririxidev** [comment]
No.
