### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by TheKubaPolska** [PreMiD/Presences#41]
**What's the name of the service?**
www.reddit.com | Reddit

**What should the Presence display?**
Subreddit you're in, eventually the post you're looking at

**Why do you want support for this service?**
Frequently used by me, would just do the general purpose of this app - what you're searching for.

**Are you able to provide an image for the service? (512x512 minimum)**
https://pmcvariety.files.wordpress.com/2014/10/reddit-logo.jpg

**Comment by OfficialCRUGG** [comment]
Will start making the presence for V2 now :)

**Comment by frozaum** [comment]
done #127
