### ISSUE TITLE
MoviesJoy | moviesjoy.to

### ISSUE THREAD

**Issue by lesigit** [PreMiD/Presences#4108]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** MoviesJoy

**What should the Presence display?** The presence should display the movie you are watching, how far into it you are, the cover art for the movie and the title 

**If possible, please provide a logo for the service (512x512 minimum)**  https://moviesjoy.to/images/group_1/theme_8/logo.png

**Comment by Jackelele** [comment]
Sheesh Virgin Media did me in here.. 

![57u0pH](https://user-images.githubusercontent.com/20693601/126153447-ae225884-c32d-4d2e-9a0c-2bc8fabbd221.png)

**Comment by lesigit** [comment]
bruv
