### ISSUE TITLE
Nsfw toggle button for presence creator page

### ISSUE THREAD

**Issue by sunx2** [PreMiD/Presences#412]
Problem The creator page shows NSFW presences by default which can be a problem to unwilling users.

Suggested solution: A NSFW toggle button in creator's page like the store has.

![image](https://user-images.githubusercontent.com/24259556/66438190-a13aac80-ea49-11e9-8b20-c2f68ce40f24.png)

**Comment by doomlerd** [comment]
Wrong repo, make the issue in the website repository.
