### ISSUE TITLE
Google Keep | keep.google.com

### ISSUE THREAD

**Issue by Johii-OOF** [PreMiD/Presences#4127]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Johii#6944

**What's the name of the service?**  **Google Keep**

**What should the Presence display?**  Reading Tasks, List name, 

**If possible, please provide a logo for the service (512x512 minimum)**  
![image](https://user-images.githubusercontent.com/79909868/126304638-35c508a6-864b-4957-a530-cba290695d92.png)

**Comment by Edwin1424** [comment]
yea its a good one

**Comment by jaydenkoh** [comment]
if no one is working on it, I can make a presence for it

**Comment by Johii-OOF** [comment]
> if no one is working on it, I can make a presence for it

Yeah, you can :)

**Comment by Isa27-0** [comment]
> If possible, please provide a logo for the service (512x512 minimum)

Now yes a logo with the proper size, ye
![image](https://user-images.githubusercontent.com/68751594/126347695-21098598-0931-4ac9-be44-34b27da20d5a.png)
