### ISSUE TITLE
ReadComicsOnline | readcomiconline.li

### ISSUE THREAD

**Issue by mambasape** [PreMiD/Presences#4143]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**Sape#1733** 

**https://readcomiconline.li/ | ReadComicsOnline** 

**The presence should include the name of the comic, the issue number, and the page number. When looking for a specific comic, the presence should show what you are searching for. Also, if the presence is idle on the home page or if someone so happens to be scrolling, make it say "Looking for something to read" in similarity to the youtube presence. When you select a comic, there is a page you are sent to before you the actual comic which is the page where it shows all the issues of said comic. Make it say (for example) "Star Wars: Darth Vader: Selecting issue" something along the lines. If there's anything that i said that isn't clear enough, reach out to my discord as I am in the premid server.** 

**If possible, please provide a logo for the service (512x512 minimum)**             
![readcomicsonlineicon](https://user-images.githubusercontent.com/87881810/126850372-20bb1233-49e0-4d81-8615-02ec9d13012e.png)

**Comment by vahya** [comment]
I can do this

**Comment by vahya** [comment]
Better logo

![rco_logo](https://user-images.githubusercontent.com/85792429/126867971-df5f72f3-bad3-4cd2-8ae3-f284d07a3bef.png)
