### ISSUE TITLE
Futemax

### ISSUE THREAD

**Issue by Haisezera** [PreMiD/Presences#4151]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
! sтσям'haise#0666
**What's the name of the service?** 
https://futemax.gratis/
**What should the Presence display?** 
jogos de futebol

**If possible, please provide a logo for the service (512x512 minimum)** 
[https://imgur.com/a/UpBUU4x](url)

**Comment by Isa27-0** [comment]
The site is pirated, I was only able to open it using VPN, as my operator probably blocked its access. And if I'm not mistaken, this type of site is [not qualified to have a presence](https://github.com/PreMiD/Presences/blob/master/.github/CONTRIBUTING.md), as it is illegal.

----------------------------------
@Haisezera, o site é pirata, só estou conseguindo abrir o mesmo usando uma VPN, pois a minha operadora (Oi) bloqueou o acesso dele. E esse tipo de site não é qualificado a ter uma presença, pois é ilegal.
