### ISSUE TITLE
mmmmmmmm

### ISSUE THREAD

**Issue by joyshyyy** [PreMiD/Presences#417]
**What's the name of the service?**
Ex. www.youtube.com | YouTube

**What should the Presence display?**
Informations about the current video

**Why do you want support for this service?**
Tell us why you want to have support for this website. Please don't just tell us "I use it all the time"

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image

**Comment by sunx2** [comment]
There is a [youtube  presence](https://premid.app/store/presences/YouTube) already .  and you are supposed to edit template with suitable details, not just post the template.


![image](https://user-images.githubusercontent.com/24259556/66463090-03bb9900-ea9a-11e9-8eec-e28b04284d6e.png)

**Comment by CobyPowers** [comment]
Next time, please add more detail and make sure the title of the issue is related to what you are trying to add.
