### ISSUE TITLE
Red Bull TV | www.redbull.com

### ISSUE THREAD

**Issue by kkrypt0nn** [PreMiD/Presences#4206]
**Prerequisites and essential questions**
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**
Krypton#7331 (ID: 562359123086409729)

**What's the name of the service?**
www.redbull.com | Red Bull TV

**What should the Presence display?**
The title of the current event or short film you're watching and eventually the time elapsed and the total length of the video.
When browsing a category it could display "Browsing category {category}"

**If possible, please provide a logo for the service (512x512 minimum)**
![Red-Bull-TV](https://user-images.githubusercontent.com/43011723/128236357-abe4881f-7747-43a1-bd07-399edb417567.png)

Banner:
![Red-Bull-TV](https://user-images.githubusercontent.com/43011723/128243960-3cd00e98-d0b3-4283-85fb-fa78f806cd2a.jpg)

**Comment by vahya** [comment]
I am doing this
