### ISSUE TITLE
HBO GO | hbogo.*

### ISSUE THREAD

**Issue by amelinho** [PreMiD/Presences#4221]
**Describe the Bug**
 well my discord is not showing hbo as my status, but netflix is working fine

**Steps to Reproduce**
 

1. Add [HBO GO Presence](https://premid.app/store/presences/HBO%20GO)
2. Go to HBO GO site
3. Observe

**Expected Behavior**

The Presence shows on my profile

**Screenshots**

**Environment**

- OS:  windows 10
- Browser:  chrome
- Version:  newest 
  

**Additional context**

**Comment by Kaisarion** [comment]
This seems fine now. Can't reproduce. Can this be closed?
