### ISSUE TITLE
[Presence | Bug] SCP Wiki

### ISSUE THREAD

**Issue by ArciWithNoH** [PreMiD/Presences#4225]
The SCP Wiki presence is facing a number of issues. These issues are as follows:
1. Failure to display any activity on the English site due to wrong URLs supported
2. Several errors displaying activity in international, secondary site, or foreign branch sites
Below is a detailed explanation for both errors.

--

**English Site Error:**
The SCP Wiki presence is missing support for the URL scp-wiki.wikidot.com, which is the URL that the English site uses now. All other URLs for the English site, including those listed to work with the presence, redirect to the unsupported URL.
Old site URLs:
www.scp-wiki.net
www.scpwiki.com
New site URL:
www.scp-wiki.wikidot.com

**Steps to Reproduce:**
1. Download presence
2. Attempt to go to the English SCP Wiki through Google search or direct links to the current or former English site URLs
3. Notice that the URL is redirected to scp-wiki.wikidot.com, not scp-wiki.net or scpwiki.com
4. Notice that, in Discord, the presence does not activate for the site

**Expected Behavior:**
Due to the current URL of the English SCP Wiki site not being supported by the presence, activity on the site will not be displayed in any visits to the site.

--

**International/Secondary/Foreign Branch Website Errors:**
The presence displays the activity on other supported URLs with a handful of errors. The errors I have seen are as follows:
- Failure to display any homepage or forum activity
- Only displays article activity (SCPs, announcements, GOI Formats, etc.)
- Chance of short delay in showing activity when presence is activated
- Chance of activity display suddenly ceasing for unknown reason
These bugs are mostly consistent, with an exception to the last two listed bugs.

The following sites are affected by these bugs:
scp-wiki-cn.wikidot.com (Chinese branch)
scp-cs.wikidot.com (Czech branch)
fondationscp.wikidot.com (French branch)
scp-wiki-de.wikidot.com (German branch)
scp-int.wikidot.com (International Translation Archive)
fondazionescp.wikidot.com (Italian branch)
ko.scp-wiki.net (Korean branch)
scp-jp.wikidot.com (Japanese branch)
scp-wiki.net.pl (Polish branch)
scp-pt-br.wikidot.com (Portuguese branch)
scpfoundation.net (Russian branch)
scp-es.com (Spanish branch)
scp-th.wikidot.com (Thai branch)
scpclassic.wikidot.com (Old Article Preservation)
scpexplained.wikidot.com (Article Explanation Site)

The following site is NOT affected by these bugs:
scp-sandbox-3.wikidot.com (Current Author Sandbox Site)

**Steps to Reproduce:**
1. Open up any site from the list of affected sites
2. Notice that, in Discord, the presence does not activate
3. Open up any article, announcement, or similarly-formatted page
4. Notice that, in Discord, the presence activates and displays activity on the page, sometimes after a couple seconds of delay
5. Open a forum post of any kind
6. Notice that, in Discord, the presence does not activate and therefore does not display activity on the page

**Expected Behavior:**
The sites listed as affected should be expected to show the errors explained above. Homepages will likely not display in the presence, and only articles or similarly-formatted pages will display. However, the possibility of the presence suddenly deactivating despite following reproduction steps is slim but existent. The exact chances of this are unknown.

--

**Environment**
- OS: Windows 10
- Browser: Chrome
- Version: 92.0.4515.131 (Official Build) (64-bit)

**Comment by MrBartusek** [comment]
Hey, I just made a PR that fixes this issue. Presence now works for the new main branch URL and the front page now displays correctly.

However, I was not able to reproduce the forum issue. It works as expected at `master` and http://scp-wiki.net.pl/

![forum](https://i.imgur.com/Bwh9fg5.png)

Could you elaborate more on `Only displays article activity (SCPs, announcements, GOI Formats, etc.)` I am not sure what you mean by that? Could you provide an example URL to the site that doesn't work?

Lastly, *activity display suddenly ceasing* or *short delay in showing activity when presence is activated* are PreMiD, not presence, related.
