### ISSUE TITLE
[Presence | Bug] Netflix

### ISSUE THREAD

**Issue by umixo** [PreMiD/Presences#4228]
**Describe the Bug**
When you watch a show or a movie, it does not show up on discord, it simply says ''browsing'' and the time elapsed.

**Steps to Reproduce**
This bug wasn't caused by anything I did to be reproduced, I simply went on Netflix and it said browsing. I have tried to re-install many times and also re-install the presence, and still doesn't work. I even turned ''browsing'' off but it still shows it.

**Expected Behavior**
My show was expected to show up on my discord with buttons, but instead it stays on ''browsing.''

**Screenshots**
<img width="1286" alt="Screenshot 2021-08-09 at 01 27 37" src="https://user-images.githubusercontent.com/88637099/128650363-73cde887-a31e-479c-a199-4c13b904a60f.png">

**Environment**

- OS: iOs (Mac)
- Browser: Chrome
- Version: 92.0.4515.131 (Official Build) (arm64)
  

**Additional context**
None

**Comment by DarkVillager** [comment]
@umixo Can you reproduce this on safari (macOS)?

**Comment by Slowlife01** [comment]
Only with the new UI.

**Comment by meykuu** [comment]
I've been trying out this app "PreMiD" everytime i open my Netflix it only shows "browsing", I tried to re-downloading it for many times but it's still the same.

OS: Windows
Browser: Chrome

![Capture](https://user-images.githubusercontent.com/89119904/129838600-eb46bfa5-1843-45e7-bc8c-c6ab60172eb7.JPG)

**Comment by azumii18** [comment]
> I've been trying out this app "PreMiD" everytime i open my Netflix it only shows "browsing", I tried to re-downloading it for many times but it's still the same.
> 
> OS: Windows
> Browser: Chrome
> 
> ![Capture](https://user-images.githubusercontent.com/89119904/129838600-eb46bfa5-1843-45e7-bc8c-c6ab60172eb7.JPG)

Same here...
