### ISSUE TITLE
Spotify Podcast Fix

### ISSUE THREAD

**Issue by FaMeGlassify** [PreMiD/Presences#4252]
**Describe the Bug**

Premid is on v2.2.0 while Spotify Podcast Extension is on 2.1.5. An update to the Spotify Podcast Extension should fix it? 

![image](https://user-images.githubusercontent.com/88954535/129464851-89df215f-7517-45a5-93b6-79e30cdf4272.png)
![image](https://user-images.githubusercontent.com/88954535/129464859-939edd7a-2a0f-4b9f-8613-5e8709a741a9.png)

**Environment**
- OS: Windows 10
- Browser: Google Chrome is up to date
Version 92.0.4515.131 (Official Build) (64-bit)

**Comment by Slowlife01** [comment]
What?

**Comment by FaMeGlassify** [comment]
Sorry, I am new to GitHub and I happened to run into the Spotify Podcast Extension on PreMid not working on Discord. My suggestion is to update the extension if that is how it works?

**Comment by Slowlife01** [comment]
I wouldn't consider this as a bug yet so please go to [our Discord server](https://discord.gg/PreMiD) and open a ticket
