### ISSUE TITLE
AnimeKage | ak142.anime-kage.eu

### ISSUE THREAD

**Issue by ChainsmokerJK** [PreMiD/Presences#426]
**What's the name of the service?**
https://ak142.anime-kage.eu/ | or simply search on google animekage, is an anime site

**What should the Presence display?**
Informations about the current video. anime, episode and time remaining i think

**Why do you want support for this service?**
Um.. Idk what to say, cuz yes, the answer is really " i use it everytime ", tbh this is a romanian anime site with anime subbed in my country, and i really really want to have this presence in premid, because i "use it everytime", so.. please just add it <3 much love

**Are you able to provide an image for the service? (512x512 minimum)**
hmm, i think this is the logo for the site
![image](https://user-images.githubusercontent.com/56367650/66516833-a3087c80-eaea-11e9-9b27-08a94a997a6e.png)

yea so just please add this site, you will make my happy <3

**Comment by mariusdobre996** [comment]
halo

**Comment by ChainsmokerJK** [comment]
hi

În mie., 18 sept. 2024 la 11:44 mariusdobre996 ***@***.***> a
scris:
