### ISSUE TITLE
AnimesGG | animes.gg

### ISSUE THREAD

**Issue by Locutinho1** [PreMiD/Presences#4264]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Locutor# 0001
**What's the name of the service?** 
www.animes.gg | AnimesGG
**What should the Presence display?** 
Anime page, episode and watched time.
**If possible, please provide a logo for the service (512x512 minimum)** 
![agg](https://user-images.githubusercontent.com/89056478/129731227-5d84b0d9-d54a-496b-af8f-1aeab72a9c0f.png)

**Comment by MMDDKK6500** [comment]
i'm going to do it, might take a few days or weeks.

**Comment by Slowlife01** [comment]
Added in #4287
