### ISSUE TITLE
Presence not working properly on Soap2day

### ISSUE THREAD

**Issue by SAVAGENP7** [PreMiD/Presences#4266]
so,when i open soap2day it says checking out the homepage and when i start watching a movie it still shows checking out the homepage.It doesnot show the details of the movie.pls fix this issue.

**Comment by EncryptedDev** [comment]
Hi, please follow the proper format [here](https://github.com/PreMiD/Presences/issues/new?assignees=&labels=&template=bug_report.md)

**Comment by Slowlife01** [comment]
Note that it doesn't work with `soap2day.video` only works with the domains in `soap2day.com`
