### ISSUE TITLE
Omlet Arcade | omlet.gg

### ISSUE THREAD

**Issue by WillSilvah** [PreMiD/Presences#4268]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Doutor MoonCat#0001

**What's the name of the service?** 
https://omlet.gg/ | Omlet Arcade

**What should the Presence display?** 
What is being used, user is on the homepage, is watching someone's live and the like

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/68751594/129918560-b9f07c08-8f35-447f-aeb3-74a83cbb98c4.png)

**Comment by Isa27-0** [comment]
Logo:
![image](https://user-images.githubusercontent.com/68751594/129918560-b9f07c08-8f35-447f-aeb3-74a83cbb98c4.png)

----------------------------

I didn't even remember that his website existed.
