### ISSUE TITLE
Voiranime website not detected 

### ISSUE THREAD

**Issue by KhoZuN** [PreMiD/Presences#4280]
when i open premid it works with all other websites but only with voiranime website it doesn't detect it

The console of the website 
![fdfff](https://user-images.githubusercontent.com/79028296/130305322-045cfc38-3b25-43be-8a29-c075d07be954.png)
in attachments

**Comment by EncryptedDev** [comment]
Hi, please fill the template again

**Comment by Isa27-0** [comment]
@KhoZuN Use the [bug report template](https://github.com/PreMiD/Presences/issues/new?assignees=&labels=&template=bug_report.md), this issue is quite likely to close without it.
