### ISSUE TITLE
Zula | playzula.com

### ISSUE THREAD

**Issue by Stjepan2141** [PreMiD/Presences#4288]
**Prerequisites and essential questions** 
- [x] Is it a popular site? 
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region? 
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) 
- [ ] Does the website feature NSFW content? (e.g. porn, etc...) 
- [ ] Are you a donator/patron? 
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? Of course I accept, I think there is no need for any haste

**What's your Discord username?** Stjepan#9144

**What's the name of the service?**  https://www.playzula.com/ (Zula Global)

**What should the Presence display?**  I would like to show up every time I find myself in the lobby and write when I play a competitive / team deatmatch / or something else and also show me what time it is to play the game and write me if I am alone in the lobby or playing with someone (Playing Solo 1/5) for example. If you have any further questions feel free to contact me at discord if I have not clearly explained here

**If possible, please provide a logo for the service (512x512 minimum)**  

![ee03126ef5a76a05e26bc966de4649d5](https://user-images.githubusercontent.com/89356614/130366941-15fef386-0cc0-4ab1-889f-a2f32306003e.jpg)

**Comment by TheGamerzs** [comment]
@Stjepan2141 You only need to tick the checkboxes that apply to the site

**Comment by Stjepan2141** [comment]
I did it, thanks for the note

**Comment by Stjepan2141** [comment]
Now i fix that, 
sorry my mistake

**Comment by Stjepan2141** [comment]
If it's not a problem contact me at the discord when it's over, thanks

**Comment by Slowlife01** [comment]
Note that PreMiD only support websites.

**Comment by Stjepan2141** [comment]
I don't understand, I thought I could request a presence for the game, can you explain to me what this is about?

**Comment by Slowlife01** [comment]
It simply just don't support apps yet

**Comment by Stjepan2141** [comment]
I understand, but will you be adding a "zula" game or other games to the premid store soon?
