### ISSUE TITLE
Discourse | *.discourse.org

### ISSUE THREAD

**Issue by overwerked** [PreMiD/Presences#4289]
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** - 🌸Infinity🌸#6969

**What's the name of the service?** Discourse | forum hosting service with many urls

**What should the Presence display?** what forum and post the user is on

example
___
(website)Microsoft Flight Simulator Forums
(post)need help with installation
(button) View Post
___
**If possible, please provide a logo for the service (512x512 minimum)** 
![discourse_logo_icon_168263](https://user-images.githubusercontent.com/82577117/130366908-1b9f9248-60ea-4790-af3f-4067436e6003.png)

**Comment by Isa27-0** [comment]
Well, these forum sites can have different URLs, because the [official site](https://www.discourse.org) only demonstrates the service. So, it would be more acceptable if they created a presence for the forum, not the service that hosts them.
