### ISSUE TITLE
[Presence | Bug] Quora 

### ISSUE THREAD

**Issue by TheGamerzs** [PreMiD/Presences#4316]
**Describe the Bug**
Viewing Topic will error out with an undefined textContent

**Steps to Reproduce**
1. View any Topic

**Expected Behavior**
Show the title of the topic

**Screenshots**
![image](https://user-images.githubusercontent.com/44209534/131579143-ecf54ca0-7add-4485-8700-cf173a11e52f.png)

**Environment**

- OS: Windows 11
- Browser: Brave
- Version: 1.29.76 || 93.0.4577.58 (Official Build) (64-bit)

**Additional context**
To get the right title change
`document.querySelector("div.qu-bold:nth-child(2) > span:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > span:nth-child(1) > span:nth-child(1)").textContent`
to
`document.querySelector("span:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > span:nth-child(1) > span:nth-child(1)").textContent`

**Comment by EncryptedDev** [comment]
Couldn't you fix the error yourself if you know the resolution?

**Comment by TheGamerzs** [comment]
I hate debugging/hotfix presences due to the browser always lagging behind.

**Comment by xDeadsh0t** [comment]
Still waitin on a fix. How would I fix it myself?

**Comment by EncryptedDev** [comment]
> Still waitin on a fix. How would I fix it myself?

You do as it says here 
> **Additional context**
> To get the right title change
> `document.querySelector("div.qu-bold:nth-child(2) > span:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > span:nth-child(1) > span:nth-child(1)").textContent`
> to
> `document.querySelector("span:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > span:nth-child(1) > span:nth-child(1)").textContent`

**Comment by MrBartusek** [comment]
Fixed by https://github.com/PreMiD/Presences/pull/4360
