### ISSUE TITLE
MEE6 Bot | mee6.xyz

### ISSUE THREAD

**Issue by Dams678** [PreMiD/Presences#432]
**What's the name of the service?**
Ex. mee6.xyz | MEE6

**What should the Presence display?**
Informations about the page see +  info if is leaderboards or player card rank

**Why do you want support for this service?**

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image
https://image.noelshack.com/fichiers/2019/41/4/1570718533-mee6.png

**Comment by sks316** [comment]
The image you've provided is 128x128. It needs to be _at least_ 512x512.

**Comment by Bas950** [comment]
Will make.

**Comment by Bas950** [comment]
![image](https://user-images.githubusercontent.com/34792838/66614902-08339f00-ebcb-11e9-87bb-b2a007fd552d.png)
LOL

**Comment by Dams678** [comment]
Nice c:

**Comment by Bas950** [comment]
I finished it, it will be added when my last request is accepted.

**Comment by Dams678** [comment]
Nice good job thx
