### ISSUE TITLE
Presence Idea

### ISSUE THREAD

**Issue by agentopdev** [PreMiD/Presences#4336]
**Is your feature request related to a problem? Please describe.**
I would really like PreMiD to add Pterdactyl presence due to there are lots of people who make bots and edit code on pterdactyl panel. So it will be great if you add pterodactyl panel presence

**Describe the solution you'd like**
Add Pterodactyl Panel Presence

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Slowlife01** [comment]
Please use [Presence request](https://github.com/PreMiD/Presences/issues/new?assignees=&labels=&template=feature_request.md) template.
