### ISSUE TITLE
Keshart | learn.keshart.in

### ISSUE THREAD

**Issue by Johii-OOF** [PreMiD/Presences#4337]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Johii#6944

**What's the name of the service?** Keshart

**What should the Presence display?**  Lesson currently, time elapsed, time remaining, course name.

**If possible, please provide a logo for the service (512x512 minimum)**  
![image_2021-09-05_231750](https://user-images.githubusercontent.com/79909868/132136487-f8ed1353-6c6d-445e-92f4-18b5e80ead5d.png)

**Comment by Slowlife01** [comment]
Would appreciate if you could get better logo
