### ISSUE TITLE
DisFa | DisFa.ml

### ISSUE THREAD

**Issue by erfanstreamer** [PreMiD/Presences#4347]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [ ] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** **`PhUneR#6562`**

**What's the name of the service?** 

> **Active domains** 

- www.DisFa.ml | DisFa
- www.DisFa.gq | DisFa
- www.DisFa.ga | DisFa
- www.DisFa.tk | DisFa
- www.DisFa.cf | DisFa
- www.DisFa.ir | DisFa [Domain related to Iran]

**What should the Presence display?** **`The page that the user is viewing`**

**If possible, please provide a logo for the service (512x512 minimum)** [Logo[512x512]](https://cdn.discordapp.com/attachments/566204140494258206/886241648332406794/Dis-Fa.png)

**Comment by Jorc0** [comment]
As it doesnt have https protocol i dont think it will be aproved, but good luck :D

**Comment by Slowlife01** [comment]
Free domains are not allowed
