### ISSUE TITLE
WebProfiles | webprofiles.me

### ISSUE THREAD

**Issue by xdg6227** [PreMiD/Presences#4355]
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Night_Crown_#0001
**What's the name of the service?** 
https://webprofiles.me/
**What should the Presence display?** 
Which page (ex. discovery) or user profile (ex. /u/itsnightcrown) the client is on.
**If possible, please provide a logo for the service (512x512 minimum)** 
![w_logo](https://user-images.githubusercontent.com/45861163/133019818-f7b8e859-2aab-4f38-a5f4-f228f032e9cd.png)

**Comment by DiscordAnaxes** [comment]
I'll take a look into creating this presence.

**Comment by Slowlife01** [comment]
This likely won't be accepted as there isn't any much you can expose
