### ISSUE TITLE
Caards | caards.me

### ISSUE THREAD

**Issue by xdg6227** [PreMiD/Presences#4356]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Night_Crown_#0001
**What's the name of the service?** 
https://www.caards.me/
**What should the Presence display?** 
Which page (ex. themes) or user profile (ex. /u/itsnightcrown) the client is on.
**If possible, please provide a logo for the service (512x512 minimum)** 
![logo](https://pbs.twimg.com/profile_images/1395458514202529799/Gqdkks4q_400x400.jpg)

**Comment by DiscordAnaxes** [comment]
I'll take a look into creating this presence.
