### ISSUE TITLE
Chaturbate.com

### ISSUE THREAD

**Issue by NitroMehmet** [PreMiD/Presences#436]
**What's the name of the service?**
www.chaturbate.com | Chaturbate

**What should the Presence display?**
Streamer name with a small red "live now" indicator like Twitch Presence.
e.g. watching Auro_69

**Why do you want support for this service?**
Chaturbate is a popular NSFW streaming service. So the presence would be useful.

**Are you able to provide an image for the service? (512x512 minimum)**
![chaturbate_solid_512x512](https://user-images.githubusercontent.com/56390583/66560945-1ea51080-eb61-11e9-9bec-a20097a5c8ca.png)

![512px-Chaturbate_logo svg](https://user-images.githubusercontent.com/56390583/66560935-19e05c80-eb61-11e9-9e35-3b313d5cd39a.png)

**Comment by NitroMehmet** [comment]
Adding another image option.
![chaturbate_logo2](https://user-images.githubusercontent.com/56390583/66561865-ffa77e00-eb62-11e9-8e8b-cd08bff0c378.png)

**Comment by doomlerd** [comment]
I'll take care of this tomorrow.
