### ISSUE TITLE
feature request for google meet

### ISSUE THREAD

**Issue by Johii-OOF** [PreMiD/Presences#4364]
**Describe the solution you'd like**
asking to join the meeting feature

**Comment by Slowlife01** [comment]
Not possible & invalid issue. We can add join button but isn't really a good idea so it won't be added

**Comment by Johii-OOF** [comment]
> Not possible & invalid issue. We can add join button but isn't really a good idea so it won't be added

no, i meant like to show that we are currently trying to join the meeting.

**Comment by Slowlife01** [comment]
Open a new issue with valid template
