### ISSUE TITLE
LeoSight | leosight.cz 

### ISSUE THREAD

**Issue by Dzardys** [PreMiD/Presences#4369]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**Dzardys#3287** 

**www.leosight.cz | LeoSight** 

**It displays every activity you do during browsing the website.** 

**![lsheader](https://user-images.githubusercontent.com/75486641/133807568-16318df7-d7fd-455a-9f27-a66e747740cf.png)**

**Comment by EncryptedDev** [comment]
Pull request opened - #4374
