### ISSUE TITLE
SonyLIV | sonyliv.com

### ISSUE THREAD

**Issue by Johii-OOF** [PreMiD/Presences#4377]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Johii#6944

**What's the name of the service?**  www.sonyliv.com | SonyLIV

**What should the Presence display?**  watching movie, time remaining

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/79909868/133916975-47fdb7b4-34eb-4055-ace6-61cbc7b74f6a.png)

**Comment by Edwin1424** [comment]
yea thats actually a good one
