### ISSUE TITLE
720p | 720pizle.net

### ISSUE THREAD

**Issue by Tolhann** [PreMiD/Presences#4384]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?**  https://720pizle.net | 720p izle

**What should the Presence display?**  play pause, movie name and timer

**If possible, please provide a logo for the service (512x512 minimum)**  
![image](https://user-images.githubusercontent.com/64492807/133992114-3e0603e2-ed56-4b92-993a-398f5305bf2b.png)

**Comment by Slowlife01** [comment]
geo-locked?
