### ISSUE TITLE
[Presence | Bug] Stadia

### ISSUE THREAD

**Issue by jewkey** [PreMiD/Presences#4387]
**Describe the Bug**

The PreMiD presence for "Google Stadia", isn't displaying on my discord profile, while every other presence does.
**Steps to Reproduce**

1. Download and setup PreMid
2. go to premid.app/store
3. add the "stadia" presence and go to stadia.google.com and test it

**Expected Behavior**

It was expected to show up as my status or whatever on my discord profile.
**Screenshots**

**Environment**

- OS:  Windows 10
- Browser: Chrome 
- Version:  93.0.4577.82 (Official Build) (64-bit)
  

**Additional context**

**Comment by Slowlife01** [comment]
Author's Discord account is apparently deleted

**Comment by Slowlife01** [comment]
@snoweyfoxx

**Comment by snoweyfoxx** [comment]
My bad, looks like i never got around to this one when updating my presences. Will fix and release an update hopefully later today.

**Comment by snoweyfoxx** [comment]
https://github.com/PreMiD/Presences/pull/4740
