### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by blizma** [PreMiD/Presences#44]
**What's the name of the service?**
GitHub.com | GitHub

**What should the Presence display?**
Information about the current repository 

**Why do you want support for this service?**
I want my friends on discord to see what I'm working on like what project am I working on and etc.

**Are you able to provide an image for the service? (512x512 minimum)**
https://image.freepik.com/free-icon/github-character-silhouette_318-40485.jpg

**Comment by OfficialCRUGG** [comment]
On my Todo List for V2
