### ISSUE TITLE
HentaiHaven | hentaihaven.xxx

### ISSUE THREAD

**Issue by WeebyJay** [PreMiD/Presences#4400]
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

Weeby Jay#0556

hentaihaven.xxx

The name of the hentai, the episode, how far into it you are and if its paused or not

![bi0o1d5qw7y21](https://user-images.githubusercontent.com/83403908/134487000-e1d2ef43-521f-4e70-bc98-a4cc80a9157f.jpg)

**Comment by Isa27-0** [comment]
Cannot be accepted by this domain ``.xxx`` (#3532)
