### ISSUE TITLE
iHeartRadio | iheart.com

### ISSUE THREAD

**Issue by CallMeJwasTaken** [PreMiD/Presences#4416]
**Describe the Bug**
iHeartRadio presence does not properly display your status. it is frozen on browsing

**Steps to Reproduce**
1. go to https://www.iheart.com/
2. select live radio
3. pick any station then check your discord status

**Expected Behavior**
expected it to show what was playing instead of being stuck on browsing

**Environment**
- OS: Windows 10
- Browser: Chrome
- Version: Version 93.0.4577.82 (Official Build) (64-bit)

**Comment by EncryptedDev** [comment]
Seems like the service is region restricted, where would I be able to access it from in order to fix it?

**Comment by CallMeJwasTaken** [comment]
> Seems like the service is region restricted, where would I be able to access it from in order to fix it?

USA should do it
