### ISSUE TITLE
TikTok | tiktok.com

### ISSUE THREAD

**Issue by Simchan14** [PreMiD/Presences#4422]
**Describe the Bug**
. --> viewing undefined even im not when watching tiktok,and the link to watch that video appears in discord is wrong too
**Steps to Reproduce**
1.I need a video to help me fix this bug or an unambiguous set of steps to reproduce this bug.
**Expected Behavior**                                                                                                                                                                           
- Required, describe what was expected to happen.                                                                                      
**Screenshots**
im sorry i dont know how to add a screenshot here
**Environment**
-  Windows 10
- Chrome
- Version: 80.0.334.4 (64-bit) 

**Additional context**
Thanks

**Comment by Jackelele** [comment]
Seems to work for me on Windows 10 and using Brave. 

The only issue I can seem to see is that the buttons aren't working (to view the video). I recommend adding some screenshots if you can of the issue you are having, maybe upload them to imgur if you cannot upload them here.
