### ISSUE TITLE
krunker.io

### ISSUE THREAD

**Issue by jlkjlkjkljkljlkjkljkljkl** [PreMiD/Presences#443]
Krunker.io Free browser multiplayer fps

**What should the Presence display?**
Map, gamemode, time left. maybe class picked region etc?

**Why do you want support for this service?**
I think it would be a neat addon since it's a game, and skribbl.io has a presence.

**Are you able to provide an image for the service? (512x512 minimum)**
Included an image. Not sure what the official logo is.
![chrome_OboNBSnk8w](https://user-images.githubusercontent.com/38816611/66613853-23041480-ebc7-11e9-941a-043067c3a261.png)

**Comment by frozaum** [comment]
#442
