### ISSUE TITLE
animedao.com

### ISSUE THREAD

**Issue by HamsterBall57** [PreMiD/Presences#469]
**What's the name of the service?**
https://animedao.com/ | AnimeDao

**What should the Presence display?**
Informations about the current video, anime title, episode number and title

**Why do you want support for this service?**
Tell us why you want to have support for this website. Please don't just tell us "I use it all the time"
Best anime site for up to date animes and 0 buffer time players

**Are you able to provide an image for the service? (512x512 minimum)**
https://images.app.goo.gl/eGiWF9UuvprpcndTA

**Comment by frozaum** [comment]
duplicate #376
