### ISSUE TITLE
Rocket League Swaps | rlswaps.com

### ISSUE THREAD

**Issue by MegaAura** [PreMiD/Presences#472]
**What's the name of the service?**
www.rlswaps.com | Rocket League Swaps

**What should the Presence display?**
If the user is trading or browsing for items.
Most valuable/recent item in the trade.
Value of the trade in keys.
How many items are currently being traded.

**Why do you want support for this service?**
It would be pretty nice for other traders in the rocket league community to be able to see what items a player is currently looking.

**Are you able to provide an image for the service? (512x512 minimum)**
[original](https://cdn.discordapp.com/attachments/514960134846414869/514985454131740672/RLSwaps.com_Beta.png)
![RLSwaps.com](https://user-images.githubusercontent.com/37901613/66716262-76db4d00-edc3-11e9-8492-42b8beb75845.png)

**Comment by Bas950** [comment]
@MegaAura contact me on discord Bas950#0950
I am going to need your help to make this.

**Comment by MegaAura** [comment]
@Bas950 Alrighty
