### ISSUE TITLE
animepahe | animepahe.com

### ISSUE THREAD

**Issue by alltimemarr** [PreMiD/Presences#4759]
**Describe the Bug**
On Discord, the Rich Presence is in a constant state of pausing.

**Steps to Reproduce**
1. Open an episode on animepahe
2. Play the episode
3. Check you discord RPC

**Expected Behavior**
When playing the episode, normally the pause (||) icon changes to play icon (I>) and you see a countdown of time remaining, something like:
"animepahe
[anime title]
[SXXEXX or episode title]
mm:ss left"

**Screenshots**
![image](https://user-images.githubusercontent.com/12399392/137552887-9ccc04b6-bd6f-4202-a83d-e67d3c6f64a8.png)

**Environment**
- OS: macOS Catalina 10.15.7 (19H1419)
- Browser: Chrome & Safari
- Version: 94.0.4606.81 (Official Build) (x86_64) & 15.0 (15612.1.29.41.4, 15612)

**Additional context**
It happens both on the Safari extension, and the Chrome PreWrap extension, so I think it's a presence issue, and not due to the extension.

**Comment by Slowlife01** [comment]
# Cannot reproduce 
![image](https://user-images.githubusercontent.com/54318514/137578070-babff833-1e06-4581-93b8-f1f1b6ca1fb6.png)
