### ISSUE TITLE
Voiranime.com

### ISSUE THREAD

**Issue by BigBoss320** [PreMiD/Presences#476]
**Is your feature request related to a problem? Please describe.**
I am frustrated at not having the rich presence of a certain website

**Describe the solution you'd like**
I want the rich presence of http://voiranime.com/

**Additional context**
![image](https://user-images.githubusercontent.com/44122706/66719808-bb331100-edf4-11e9-8822-b7ea463efefd.png)

**Comment by frozaum** [comment]
Can you please provide us a logo to use?

**Comment by BigBoss320** [comment]
Hello, I think this can be used : https://www.google.com/search?q=voir+animé+logo&client=ms-android-huawei&prmd=nsiv&sxsrf=ACYBGNRO5_sQT_euX0z7bNIbYwqvobfAQQ:1571119063844&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi318zNyp3lAhXKzoUKHctTDnAQ_AUoA3oECA0QAw&cshid=1571119175709&biw=360&bih=518&dpr=3#imgrc=Wf5QcYQ68IJ8NM
