### ISSUE TITLE
VRV | vrv.co

### ISSUE THREAD

**Issue by curiositIy** [PreMiD/Presences#4809]
**Describe the Bug**
Doesn't display anything about the current episode you are watching on vrv.co, however it does show the info on the homepage

**Steps to Reproduce**
1. add the vrv presences 
2. go to an episode on vrv.co
3. and press play

**Expected Behavior**
should display the episode name, time left, current season, and more

**Screenshots**
my rpc while watching the episode: [link](https://i.imgur.com/3A48rOK.png)
my rpc while viewing the homepage: [link](https://i.imgur.com/SGJU5XD.png)

**Environment**
- OS: Win 11
- Browser: Brave
- Version: Version 1.31.87 Chromium: 95.0.4638.54 (Official Build) (64-bit)

**Additional context**
this only seems to be an issue while actually playing the episode, and doesn't happen on any other page of vrv

**Comment by DarkVillager** [comment]
Reproduced it, just can't find a way to fix it.

**Comment by RisingSunLight42** [comment]
I'll try to figure out later (few days maybe), if my region is not restricted, how to resolve that

**Comment by DarkVillager** [comment]
> I'll try to figure out later (few days maybe), if my region is not restricted, how to resolve that

US isn’t restricted so i used a vpn

**Comment by RisingSunLight42** [comment]
Can repro too, looks like the presence doesn't achieve to get the video element everytime, but this is weird since the right querySelector is present and the presence achieve to get it like 1 time for 4 attempts.
Since my VPN broke a bit the site, I think someone who is in the right region should monitor this issue.

**Comment by RisingSunLight42** [comment]
Bug finally understood.
Looks like the iframe targeted is not the right everytime, as you can see on this screen below :

![image](https://user-images.githubusercontent.com/85577959/182561731-4f6d8aca-eec1-4927-972d-228f998d4965.png)

The iframe is the current whole page and not the right iframe, sometimes the presence get the right, but its really often
