### ISSUE TITLE
HBO GO Hungary

### ISSUE THREAD

**Issue by Erviiin** [PreMiD/Presences#4857]
What's the name of the service?
https://hbogo.hu/ | HBO GO

What should the Presence display?
Informations about the current movie/tv series like Netflix presence.

Why do you want support for this service?
I want support for this service because i like to watch movies/tv series on Netflix and rich presence show on discord but sometimes i watch on hbo go and i dont have this facility.

**Comment by Slowlife01** [comment]
This presence is already exists, so please make a feature request instead and do that in discussions section
