### ISSUE TITLE
Skribbl.io | skribbl.io

### ISSUE THREAD

**Issue by TheX24** [PreMiD/Presences#4861]
**Describe the Bug**
I installed the extension and application yesterday, I installed the presence called "skribbl.io" and I was playing it right after it was installed, it just didn't work. I've tried probably everything I can think of, nothing happened.

**Steps to Reproduce**
https://youtu.be/xk3BYYDWuBA

1. Download the app and install the extension
2. Download the "skribbl.io" presence
3. Start playing

**Expected Behavior**
 PreMiD detects that I'm playing skribbl.io and starts the presence

**Screenshots**

**Environment**

- OS:  Windows 11 Home
- Browser:  Brave (Chromium)
- Version: 95.0.4638.69 64-Bit
  

**Additional context**

**Comment by Slowlife01** [comment]
# Cannot reproduce
![image](https://user-images.githubusercontent.com/54318514/139904430-68aa6228-b48e-45cc-bde7-afa009695356.png)
# Environment
- **OS**: Windows 10
- **Browser**: Edge (95.0.1020.40)
- **Version**:
   - **Extension**:  2.2.4.2
   - **App**: 2.2.0 
   - **Discord**: Canary 103265 (43aed33)
