### ISSUE TITLE
HentaiZ | hentaiz.*

### ISSUE THREAD

**Issue by AyanoKiru** [PreMiD/Presences#4879]
**Describe the Bug**
The Hentaiz presense not working anymore because hentaiz has change the domain from hentaiz.net to hentaiz.vip ( hentaiz.to)
**Steps to Reproduce**

1. https://hentaiz.vip/
2. change domain in presense from hentaiz.net to hentaiz.vip

**Expected Behavior**
The presence for hentaiz is working angain

**Screenshots**
![image](https://user-images.githubusercontent.com/66897456/140674040-75f9e97e-e61f-4c9a-ad05-0ed6bfdb5716.png)

**Environment**
- OS:  Windows 10, Windows 8.1, Windows 7 or Linux 
- Browser: Edge
- Version: 95.0.1020.44 (64-bit)

**Additional context**
nothing

**Comment by kyrie25** [comment]
It is being worked on

**Comment by AyanoKiru** [comment]
> It is being worked on

thanks
