### ISSUE TITLE
GitHub | github.com

### ISSUE THREAD

**Issue by mihaiofficialRO** [PreMiD/Presences#4904]
Hello,

Here is another issue, this time about GitHub... The issue is, if you are in the login page, the presence will look like this: https://cdn.discordapp.com/attachments/900797627413716994/909532115882893382/unknown.png

https://github.com/login

**Comment by ImRodry** [comment]
Please follow the issue template, thanks

**Comment by Slowlife01** [comment]
How is this even a bug? It's literally said that the page is unsupported. So please make a feature request in discussions section instead
