### ISSUE TITLE
[Presence | Bug] Plex

### ISSUE THREAD

**Issue by ThatOneJay** [PreMiD/Presences#4907]
### Description

Doesn't detect movie details, stays on "Viewing homepage". Sometimes it will detect movie but it stays on paused and doesn't show timestamp.
TV Shows work fine though.

### Steps to Reproduce

1. Play movie

### Expected Behavior

Expect it to show the movie playing and show timestamps

### Screenshots

Movie: https://prnt.sc/1zmk35a

### Operating System (OS)

Windows 10

### Browser

Chrome

### Browser Version

95.0.4638.69 (Official Build) (64-bit)

**Comment by Slowlife01** [comment]
Duplicate of #4098
