### ISSUE TITLE
Plex | app.plex.tv

### ISSUE THREAD

**Issue by ThatOneJay** [PreMiD/Presences#4908]
### Description

Doesn't detect movie details, stays on "Viewing homepage". Sometimes it will detect movie but it stays on paused and doesn't show timestamp.
TV Shows work fine though.
When playing TV Show
![Screenshot 2021-11-15 150742](https://user-images.githubusercontent.com/76684256/141721227-62214c4d-8c7e-463f-af3b-62e71aa43979.png)
When playing movie:
![Screenshot 2021-11-15 151055](https://user-images.githubusercontent.com/76684256/141721233-46ceed9d-c6c5-4f96-b3e7-a8be7c7a8ad5.png)

### Steps to Reproduce

1. Play movie

### Expected Behavior

Expect it to show the movie playing and show timestamps

### Operating System (OS)

Windows 10

### Browser

Chrome

### Browser Version

95.0.4638.69 (Official Build) (64-bit)

**Comment by 0xYami** [comment]
@theusaf Invalid Issue, it is working.
