### ISSUE TITLE
Request to add a site

### ISSUE THREAD

**Issue by MatheusALeal** [PreMiD/Presences#497]
**What's the name of the service?**
https://animeshouse.net | AnimesHouse

**What should the Presence display?**
Informations about the current video

**Why do you want support for this service?**
is a very used site to watch anime here in Brazil and I think it would be really cool to be able to use it on PreMiD

**Are you able to provide an image for the service? (512x512 minimum)**
Unfortunately I didn't find the 512x512 icon

**Comment by frozaum** [comment]
duplicate #215
