### ISSUE TITLE
Peacock | peacocktv.com

### ISSUE THREAD

**Issue by kagbogre** [PreMiD/Presences#4979]
### Description

The Peacock presence broke and stopped working correctly (video times not being obtained correctly anymore, page names not showing, incorrect series/movie titles being obtained).

Note: I made this Presence so I will look into this when I can, posted this issue in case anyone else wants to take a stab at it.

### Steps to Reproduce

1. Install the Peacock presence.
2. Go on peacocktv.com.
3. Start watching any series/movie, observe your Discord presence status.

### Expected Behavior

Should display series and movie titles correctly again.
Should display video element's progress again.
Should display page names when navigating the site again.

### Screenshots

Example while watching The Office (a series). It's not displaying the series title and video progress (timestamp).

![image](https://user-images.githubusercontent.com/4789757/144152891-1c265ac5-de94-42b0-8dd1-1e454a42d27c.png)

When navigating the site, no page name is displayed:

![image](https://user-images.githubusercontent.com/4789757/144153080-87298a94-308d-47f6-93d7-9bc1ed62dab2.png)

### Operating System (OS)

Windows 11

### Browser

Chrome

### Browser Version

96.0.4664.45

**Comment by SirDread** [comment]
is the presnece creator ever going to acknowledge this? Can't his Github be added to this?

**Comment by EncryptedDev** [comment]
> is the presnece creator ever going to acknowledge this? Can't his Github be added to this?

All work is voluntary, like any other open-source project (mostly) - we do not hassle presence developers to fix their presences. 
I was thinking about fixing this, but the entire presence is due a recode too and I don't have the time. Now you've boosted this, it might be seen sooner.

**Comment by CrypticXT** [comment]
service is region restricted
