### ISSUE TITLE
WikiHow only works on english site

### ISSUE THREAD

**Issue by 123321mario** [PreMiD/Presences#499]
**Describe the bug**
WikiHow integration only works in the english site

**To Reproduce**
Just go to the non-english versions of the site

**Expected behavior**
Exactly the same as the english site

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.4
 - Browser: Opera 64.0.3417.54
 - Version: v.2.0.1.3

**Additional context**
Here are all of the wikihow official translations urls:
https://es.wikihow.com/
https://www.wikihow.cz/
https://de.wikihow.com/
https://fr.wikihow.com/
https://hi.wikihow.com/
https://id.wikihow.com/
https://www.wikihow.it/
https://ja.wikihow.com/
https://nl.wikihow.com/
https://pt.wikihow.com/
https://ru.wikihow.com/
https://ar.wikihow.com/
https://th.wikihow.com/
https://www.wikihow.com.tr/
https://www.wikihow.vn/
https://ko.wikihow.com/
https://zh.wikihow.com/

You can check here if I missed any : https://www.wikihow.com/wikiHow:Language-Projects

**Comment by eggsywashere** [comment]
Thanks for letting us know about this, I've made necessary changes and they will update the presence soon.
