### ISSUE TITLE
Wakanim | Wakanim.tv

### ISSUE THREAD

**Issue by EnderTogether** [PreMiD/Presences#50]
What's the name of the service?
https://www.wakanim.tv/de/v2 | Wakanim

What should the Presence display?
Informations about the current video: anime, episode and time remaining

Why do you want support for this service?
Wakanim is the biggest official and legal anime streaming platform in Germany and is used by a huge amount of people. It would be very nice if it would be supported

Are you able to provide an image for the service? (512x512 minimum)
https://ftp.fau.de/osmc/osmc/download/kodi/addons/leia/plugin.video.wakanim/icon.png
https://images-eu.ssl-images-amazon.com/images/I/41OdQviPNjL.png

**Comment by Bas950** [comment]
Not for my county
