### ISSUE TITLE
Spotify Podcasts | *.spotify.com

### ISSUE THREAD

**Issue by BestName2020** [PreMiD/Presences#5001]
### Description

When I try to use the Spotify Podcasts presence, it's not working in any ways. 

### Steps to Reproduce

Make it work again.
If that's possible somehow, make it work with the downloaded Spotify too.

### Expected Behavior

It's gonna work again. Sorry, I can't say anything else.

### Operating System (OS)

Windows 10

### Browser

Opera GX

### Browser Version

LVL3 (core: 81.0.4196.61)

**Comment by Pjoottr** [comment]
You'll need to provide some more information than "Make it work again.", what doesn't work exactly? And what would you expect it to do?

**Comment by BestName2020** [comment]
When I add Spotify Podcasts to my Premid, when I go to Spotify or the web
version, nothing happens, it's not showing anything on Discord and even I
reinstalled it once and nothing got fixed with that.

Pjoottr ***@***.***> ezt írta (időpont: 2021. dec. 7., K,
15:18):

**Comment by Slowlife01** [comment]
#### Seems to be working fine for me.
![image](https://user-images.githubusercontent.com/54318514/145202030-747ee7ed-fdcd-41f0-ace0-13ae931700d0.png)

#### Have you tried changing the Presence's language? And please note that PreMiD currently do not support Applications.

**Comment by EncryptedDev** [comment]
Hello, could you provide me the url to the page which isn't displaying as your status?

**Comment by BestName2020** [comment]
I don't know how, but I tried it now and it worked after like the third try
when I changed podcasts.

Rhys ***@***.***> ezt írta (időpont: 2021. dec. 22., Sze,
14:48):
