### ISSUE TITLE
WhatsApp | web.whatsapp.com

### ISSUE THREAD

**Issue by mihaiofficialRO** [PreMiD/Presences#5007]
### Description

Hello,

yesterday i was putting all my whatsapp conversation to privacy mode, now is public again...

### Steps to Reproduce

1. launch & login on web.whatsapp.com
2. put whatsapp presence in privacy mode
3. wait another day, to see if its in privacy mode

### Expected Behavior

Soo, i was expected to be on privacy mode, all the time, not to disable ”show recipient name”, and then another day, to be enabled again by default...

### Screenshots

(https://prnt.sc/227yb0j)

### Operating System (OS)

Windows 10

### Browser

Brave

### Browser Version

Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

**Comment by Slowlife01** [comment]
Sound more like extension's bug, but can set default to false
