### ISSUE TITLE
Vizer | vizer.tv

### ISSUE THREAD

**Issue by yuukiee** [PreMiD/Presences#503]
**What's the name of the service?**
https://vizer.tv | Vizer | vizer.tv

**What should the Presence display?**
- Browsing
- Video Title
- Time left for video to finish

**Why do you want support for this service?**
Vizer is a very used site in Brazil for those who want to watch movies but can't afford it, so I decided to order ¯\_(ツ)_/¯

**Are you able to provide an image for the service? (512x512 minimum)**
![vizer-logo](https://user-images.githubusercontent.com/42496876/67111334-17a67f80-f1ab-11e9-82d6-e17678f3deef.png)

**Comment by yuukiee** [comment]
would look something like this (conceptual, I don't know how to make presences ;c)
![image](https://user-images.githubusercontent.com/42496876/67119808-44b05d80-f1be-11e9-864e-f809850fdd04.png)

**Comment by Bas950** [comment]
Vizer has shutdown...

**Comment by Bas950** [comment]
Just heard they are coming back online soon:tm: xD So tag me when its up.

**Comment by frozaum** [comment]
vizer is back so, rip on hold

**Comment by Bas950** [comment]
For information about the status of this suggestion see #1129
