### ISSUE TITLE
MangaDex | mangadex.org

### ISSUE THREAD

**Issue by jcatrdev** [PreMiD/Presences#5055]
### Description

The presence doesn't work. I even switched browsers but none of them work. It works 1 week ago, now it does not again.

### Steps to Reproduce

1. Run Premid
2. Launch the browser
3. Install mangadex presence from store
4. Check if mangadex presence is enabled
5. Go to mangadex official website, whether its .cc or .org
6. Check discord status

### Expected Behavior

Expected to show a presence with timer and shows where you are. (Title and chapter)

### Operating System (OS)

Linux (Arch Linux)

### Browser

Brave, Chrome, Firefox

### Browser Version

Brave: Version 1.32.115 Chromium: 96.0.4664.93 | Chrome: Version 96.0.4664.93 | Firefox: 95.0

**Comment by Slowlife01** [comment]
@StrikerFRFX, looks like the application for the presence was deleted

**Comment by StrikerFRFX** [comment]
![iindf0l0v4q41](https://i.imgur.com/WQ8ZRpe.png)
 looks fine to me.....

**Comment by Slowlife01** [comment]
> ![iindf0l0v4q41](https://camo.githubusercontent.com/7a5c5fcefe23e3381a437d0beca6ea270ee88470e274928a48733614d971d076/68747470733a2f2f692e696d6775722e636f6d2f5751385a5270652e706e67) looks fine to me.....

What's the id?
