### ISSUE TITLE
Deezer | www.deezer.com

### ISSUE THREAD

**Issue by KingKusuo** [PreMiD/Presences#5063]
### Description

It basically doesn't shows up in the discord activity status. It used to work perfectly fine, but now it seems like it's abandoned

### Steps to Reproduce

1. Open premid app (Perfectly configured)
2. Open deezer website
3. Check discord status (Nothing shows up)

### Expected Behavior

A couple months ago it was still working, it would show the current song that is playing, and also the time that is left for the song to end, would also show up some buttons like (Album page) and (Artist page)

I really hope it gets fixed, it's been a long time since it last worked and i really miss this presence.

### Screenshots

Don't have any screenshots of it working :/
![image](https://user-images.githubusercontent.com/69478539/146665221-46ba26da-8958-4d8c-a8c3-1d61acd3b1e1.png)

### Operating System (OS)

Windows 10

### Browser

Opera GX

### Browser Version

LVL 3 (core: 81.0.4196.61)

**Comment by Slowlife01** [comment]
![image](https://user-images.githubusercontent.com/54318514/146726808-3f1ce6c7-0a80-46a4-869c-97184e784374.png)
This likely happened because of the language setting please try re-adding the presence

**Comment by KingKusuo** [comment]
> ![image](https://user-images.githubusercontent.com/54318514/146726808-3f1ce6c7-0a80-46a4-869c-97184e784374.png) This likely happened because of the language setting please try re-adding the presence

This wasn't very useful, i've tried everything already, reinstalling it didn't really help

**Comment by Slowlife01** [comment]
Well, this isn't really presence's bug instead it's extension bug. So I highly recommend you to use beta extension https://premid.app/beta
