### ISSUE TITLE
AnimeKage | ak419.anime-kage.eu 

### ISSUE THREAD

**Issue by Koala5555** [PreMiD/Presences#5070]
### Description

Is a bug on presence on AnimeKage. The bug consists in not showing on Discord status the name of the anime/manga, episode number you watch, that timer where u see how much time is left, only u can see is the text 'AnimeKage' and the badge of site. The only time where the presence is working is in menu page of site.(You will see in screenshots). It's a shame it doesn't work, because is a popular site in Romania and is used by many people to be disregarded.

### Steps to Reproduce

1. Open all things(Premid app, extension, Discord app, the site).
2. You enter on any episode of anime/manga.
3. And play an episode.

### Expected Behavior

I was expecting to see the name of anime, the timer, the episode number you watch and all things on Discord status.

### Screenshots

![Untitled1](https://user-images.githubusercontent.com/96386888/146691999-a33286b8-45b5-4f5b-8d56-a6d191bf8587.png)
You can see in this screenshot, here is the only place where is working, the main page.

![Untitled](https://user-images.githubusercontent.com/96386888/146692002-2470ca48-5624-4b6c-afce-b95d07a32d2e.png)
Here is a One Piece episode and doesnt work. I've tried with many other anime, but nothing.

### Operating System (OS)

Windows 7

### Browser

Brave

### Browser Version

Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)

**Comment by Koala5555** [comment]
I hope that 'Service URL' mean the site link, because i put the link there. :sweat_smile:

**Comment by Koala5555** [comment]
Is someone working on this at least?

**Comment by Koala5555** [comment]
You have this site to help people or just to do nothing with their problems?

**Comment by Slowlife01** [comment]
> You have this site to help people or just to do nothing with their problems?

Please be patient, all the reports here are voluntary work. I can try to take a look at it later when I have time.

**Comment by Koala5555** [comment]
I saw a report from this summer, i just asked🤷‍♂️
