### ISSUE TITLE
PreMiD | premid.app

### ISSUE THREAD

**Issue by mihaiofficialRO** [PreMiD/Presences#5076]
### Description

Soo... when im on https://premid.app/ , is not detecting the website... but is detecting facebook, when im on the premid website itself...

Also the content is gone sometimes (*i need to refresh the page*), to show the content itself...

### Steps to Reproduce

1. launch premid.app
2. wait for discord to detect it
3. see the results

### Expected Behavior

i was expected to show premid ”Home - PreMiD” presence

### Screenshots

1. https://media.discordapp.net/attachments/554447633197039627/922981765931470868/unknown.png?width=960&height=571
2. https://media.discordapp.net/attachments/922983767281385492/922986364117606400/unknown.png
3. https://media.discordapp.net/attachments/922983767281385492/922986604186972160/unknown.png?width=910&height=664

### Operating System (OS)

Windows 10

### Browser

Brave

### Browser Version

Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)

**Comment by EncryptedDev** [comment]
Unable to reproduce, not an issue 
![image](https://user-images.githubusercontent.com/64903135/147010600-2aff4c9a-1858-4f7a-9236-bfd084adfa1c.png)

**Comment by mihaiofficialRO** [comment]
> Unable to reproduce, not an issue ![image](https://user-images.githubusercontent.com/64903135/147010600-2aff4c9a-1858-4f7a-9236-bfd084adfa1c.png)

yes, its an issue... on my end, is not working
