### ISSUE TITLE
Wikipedia | wikipedia.org

### ISSUE THREAD

**Issue by LeviOP** [PreMiD/Presences#5115]
### Description

I use wikipedia a lot, quite more than most normal people using premid, and I assume that's why no one has come across the issue that I am having. When editing wikipedia in source mode, there are little buttons next to each section that say "edit source." (See image)
![image](https://user-images.githubusercontent.com/35459268/147362912-31a4b85e-9b9f-4ee2-bfd9-89ada2c9ea8a.png)
I have a setting enabled in wikipedia to show this button on the top of the article, next to it's title. (See image)
![image](https://user-images.githubusercontent.com/35459268/147362984-899a5f24-3057-46f2-abe5-052f5173ad39.png)
This causes an issue in premid where it includes the "[edit source]" in the title of the page, which is inaccurate. (See image)
![image](https://user-images.githubusercontent.com/35459268/147363030-0aa93d13-acbc-43d7-9d15-e6c3659d77f5.png)

### Steps to Reproduce

1. Sign into/create a wikipedia account if you do not already have one (required to set preferences in wikipedia)
2. Click the preferences button on the top right of the screen
3. Click on the section entitled "Gadgets"
4. Scroll to the "Appearance" section
5. Enable the first setting, which says "Add an [edit] link for the lead section of a page"
6. Press save at the bottom of the screen
7. Navigate to any wikipedia page
8. View premid status

### Expected Behavior

The title of the wikipedia page would show, according to the site

### Actual Behavior

The title of the page shows, along with extra text

### Page URL

https://en.wikipedia.org/wiki/Example

### Operating System (OS)

Windows 10

### Browser

Firefox

### Browser Version

95.0.2

**Comment by Vukkyy** [comment]
> and I assume that's why no one has come across the issue that I am having

I have been able to reproduce this issue for a long time, but didn't report it for some reason.

**Comment by LeviOP** [comment]
Haha hi vukky didn't think I'd see any wikipedians that I'd recognize here, letalone any that use PreMiD! Hope this issue gets fixed.
