### ISSUE TITLE
myCanal domain has changed

### ISSUE THREAD

**Issue by LudaWeb01** [PreMiD/Presences#512]
**Describe the bug**
mycanal.fr redirects to canalplus.com and so the myCanal presence does not work anymore

**To Reproduce**
Just go to mycanal.fr

**Expected behavior**
The domain should be changed to canalplus.com

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Chrome 77
 - Version : 2.0.1.3

**Comment by frozaum** [comment]
fixed #513
