### ISSUE TITLE
Soundcloud | soundcloud.com

### ISSUE THREAD

**Issue by Sxvn1337** [PreMiD/Presences#5121]
### Description

Soundcloud RPC does not work. Tried refreshing and all other troubleshooting methods mentioned in the wiki. Every other presence seems to work fine for me. No other scripts are running on soundcloud.com (website) as well and I'm using default discord.

### Steps to Reproduce

1. Go to soundcloud.com
2. Play a song
3. Check discord and see its showing nothing for the presence.

### Screenshots

![image](https://user-images.githubusercontent.com/58984827/147384113-7e53b61f-8a2c-45f2-8f05-c114da3a0b94.png)
![image](https://user-images.githubusercontent.com/58984827/147384109-38a35d23-eadc-4149-bdfb-a46a6f9c33f2.png)

### Expected Behavior

Soundcloud presence showing what music I'm listening to on discord under my profile.

### Actual Behavior

Nothing. No rich presence.

### Page URL

Soundcloud.com

### Operating System (OS)

Windows 10

### Browser

Chrome

### Browser Version

Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by EncryptedDev** [comment]
This is not a presence related issue, this is a problem on your side. Please open a ticket in [#support](https://discord.com/channels/493130730549805057/566738846650335232) in our [Discord Guild](https://discord.premid.app/) and our Support Agents should help resolve this issue for you.
