### ISSUE TITLE
Netflix | www.netflix.com

### ISSUE THREAD

**Issue by Naricola** [PreMiD/Presences#5149]
### Description

_My Netflix Discord presence looks different, apparently it's because it's been updated but it doesn't work properly anymore:_ 
- It's not showing the episode's title (only its number)
- The icon isn't Netflix's anymore but the show's (might just be an update)
- The timer isn't working right (says **00:00 left** even though the episode didn't end, or **doesn't show up at all**).

I tried to skip to the next episode to test it out and nothing changed, the timer was still freezed and the title of the episode hadn't moved. I also tried closing and re-opening Discord and my browser, same issue. I checked my Netflix presence's settings and they're all the same as before, so I have no idea why it's doing this.

### Steps to Reproduce

1. Open Netflix, Discord, and Premid in whatever order.
2. Pick a show to watch.
3. Finish the episode or go straight to the end of it and/or move immediately to the next one.
4. Look at the timer on Discord.

### Screenshots

![image](https://user-images.githubusercontent.com/96703203/147421049-4835f43e-9f66-42cc-bd41-767782295c35.png)

### Expected Behavior

I expected the title of the episode I was currently watching to show up + timer being on point + presence detecting I switched from one episode to another.

### Actual Behavior

Instead of the episode's title, only its number appeared. The timer wasn't synchronized, freezed or just didn't show up at all. Moving from one episode to another didn't refresh the presence.

### Page URL

www.netflix.com

### Operating System (OS)

Windows 11

### Browser

Opera GX

### Browser Version

82.0.4227.50 (December 22, 2021)

**Comment by Bas950** [comment]
> It's not showing the episode's title (only its number)
Please try reinstalling the presence, we have changed a few of the settings and I think they didn't transfer 100% correctly.

> The icon isn't Netflix's anymore but the show's (might just be an update)
This is customizable in the settings
![image](https://user-images.githubusercontent.com/34792838/147421780-b7a6d6af-9ecb-4da9-941b-1e33fcb33340.png)

> The timer isn't working right (says 00:00 left even though the episode didn't end, or doesn't show up at all).
Will look into that.

**Comment by SerenModz21** [comment]
the netflix presence activity doesn't seem to update when i play something and only seems to update when i go from browsing to viewing (vice versa)

i tried reinstalling it but that didn't fix it

**Comment by EncryptedDev** [comment]
This is unlikely to be an issue with the presence itself, please could you open a ticket on our [Discord](https://discord.premid.app)
