### ISSUE TITLE
Manga Livre | mangalivre.com

### ISSUE THREAD

**Issue by yuukiee** [PreMiD/Presences#516]
**What's the name of the service?**
Mangá Livre | mangalivre.com

**What should the Presence display?**
- time the user is browsing
- name of the manga the user is seeing
- manga chapter the user is reading and how long he has been reading (basically the same things as Union Manga's presence)

**Why do you want support for this service?**
Manga Livre is a great site to read manga, and just like Union Manga, I'd love to have that site too

**Are you able to provide an image for the service? (512x512 minimum)**
![icon-facebook](https://user-images.githubusercontent.com/42496876/67160826-13a16b80-f32b-11e9-8f9e-44e98d42aefc.png)

**Comment by yuukiee** [comment]
could look like this (conceptual image)
![Discord_bSHS735xSI](https://user-images.githubusercontent.com/42496876/67161053-2452e100-f32d-11e9-89be-c831c5d025e3.png)
![Discord_KBFpNUQBZE](https://user-images.githubusercontent.com/42496876/67161059-33399380-f32d-11e9-95a1-0b651973058c.png)
![Discord_CdtIsGBaoS](https://user-images.githubusercontent.com/42496876/67161061-3b91ce80-f32d-11e9-85d4-34e5d14f8757.png)

**Comment by yuukiee** [comment]
yeah
![reading](https://user-images.githubusercontent.com/42496876/67161077-6a0fa980-f32d-11e9-8226-328524cbf7ca.png)

**Comment by eggsywashere** [comment]
Sad.
![tf](https://user-images.githubusercontent.com/13917975/67161219-00a98e00-f361-11e9-8f81-fb7102248c02.png)
