### ISSUE TITLE
Mixer.com

### ISSUE THREAD

**Issue by Chew** [PreMiD/Presences#52]
**What's the name of the service?**
Ex. https://mixer.com | Mixer

**What should the Presence display?**
Same as Twitch. It's a live stream platform. Show Stream, Streamer, time you've been watching the stream.

**Why do you want support for this service?**
We have support for Twitch, why not support Mixer? Mixer is an interactive live streaming platform owned by Microsoft. No need to skip right over it!

**Are you able to provide an image for the service? (512x512 minimum)**
![exactly 512x512](https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fteambeyond.net%2Fwp-content%2Fuploads%2F2017%2F05%2FMixer-Logo.png&f=1)

**Comment by frozaum** [comment]
AND IT'S DONE BOIS

**Comment by Chew** [comment]
Mixer!!

**Comment by Chew** [comment]
yeeyee
