### ISSUE TITLE
Best Gore (nsfw)

### ISSUE THREAD

**Issue by senfruit** [PreMiD/Presences#520]
**What's the name of the service?**
https://www.bestgore.com | Best Gore

**What should the Presence display?**
Information about the current video, image, or topic you're on, Time elapsed for video and maybe something with "Viewing image/video"

**Why do you want support for this service?**
Best Gore is a shock site that surprisingly a lot of people use. Pretty fun website to be on. I think it'd be cool to have it on my overlay.
**Are you able to provide an image for the service? (512x512 minimum)**
![best](https://user-images.githubusercontent.com/56458691/67277460-d658ed00-f494-11e9-98bf-3205e5e33b9e.png)

**Comment by frozaum** [comment]
Hey @senfruit, to comply with our guidelines we do not allow gore websites in the Presence Store, with that, this issue is closed and invalid.

**Comment by senfruit** [comment]
OOPS SORRY I DIDNT KNOW
