### ISSUE TITLE
Tiktok | tiktok.com

### ISSUE THREAD

**Issue by mihaiofficialRO** [PreMiD/Presences#5200]
### Description

Not showing what im watching on tiktok

### Steps to Reproduce

1. Watch a random video, from a random tiktok profile
2. Go back to discord
3. See the status activity on discord

### Screenshots

![image](https://user-images.githubusercontent.com/38259440/171289528-ac7a62a2-dfdc-4b6a-b2a3-2d2a794558cb.png)

### Expected Behavior

i was expected to show what im watching on tiktok

### Actual Behavior

Viewing profile of: undefined (@undefined)

### Page URL

https://www.tiktok.com/@studiodmofficial/video/7040533234383375622?is_copy_url=1&is_from_webapp=v1

### Operating System (OS)

Windows 10

### Browser

Brave

### Browser Version

Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)

**Comment by EncryptedDev** [comment]
Hello, I’m currently rewriting the presence, this has been included in the new presence (:

**Comment by mihaiofficialRO** [comment]
BUMP for this

**Comment by DarkVillager** [comment]
Resolved 
![image](https://user-images.githubusercontent.com/42322979/189525602-5151e762-78c7-44ae-9f96-d5259b923cde.png)
