### ISSUE TITLE
BetterAnime | betteranime.net

### ISSUE THREAD

**Issue by Baekkivers** [PreMiD/Presences#5206]
### Description

BetterAnime's presence doesn't work.

### Steps to Reproduce

1. https://betteranime.net/anime/legendado/ano-hi-mita-hana-no-namae-wo-bokutachi-wa-mada-shiranai/null
2. Click on the video to play.
3. What you are watching will not appear on your account.

### Expected Behavior

I was hoping that what I'm watching and doing on the site would show up.

### Actual Behavior

Even with everything turned on, presence didn't even appear on my profile.

### Page URL

https://betteranime.net

### Operating System (OS)

Windows 10

### Browser

Chrome

### Browser Version

96.0.4664.110

**Comment by Slowlife01** [comment]
Why did you close the first one
