### ISSUE TITLE
YouTube | youtube.com

### ISSUE THREAD

**Issue by mihaiofficialRO** [PreMiD/Presences#5213]
### Description

Hello,

the youtube presence is getting stuck, when im watching a video

P.S: i tried refresh the discord, but thats just a temporary fix, and i want a permanent fix...

### Steps to Reproduce

1. Go to youtube.com
2. Watch a random video (until its end)
3. Go watch another random video

### Screenshots

https://prnt.sc/25hqxjv

### Expected Behavior

i was expected to not to get stuck

### Actual Behavior

To working like a normal presece

### Page URL

https://www.youtube.com/watch?v=eaTawbEn_d4

### Operating System (OS)

Windows 10

### Browser

Brave

### Browser Version

Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)

**Comment by EncryptedDev** [comment]
This is an extension issue; not a presence issue and will be fixed in future versions of PreMiD.
