### ISSUE TITLE
SiriusXM | player.siriusxm.com

### ISSUE THREAD

**Issue by SnoweyFoxx** [PreMiD/Presences#522]
**What's the name of the service?**
Ex. player.siriusxm.com | SiriusXM

**What should the Presence display?**
Information about the current song and artist. (The station info isn't required, but would be nice.)
**Why do you want support for this service?**
SiriusXM is a great online radio streaming platform and I would love to have support for it, as it is one of my daily drivers for music. It would be nice to be able to share what I am listening to on it with my friends on Discord.

**Are you able to provide an image for the service? (512x512 minimum)**
![SiriusXM](https://user-images.githubusercontent.com/56901798/67913602-a1672d00-fb5b-11e9-94d0-f18297af306b.png)

**Comment by HQv2** [comment]
I was about to post this myself and saw the similar issues. This presence would be greatly appreciated!
