### ISSUE TITLE
Letterboxd | letterboxd.com

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5230]
### Discussed in https://github.com/PreMiD/Presences/discussions/4471

<div type='discussions-op-text'>

<sup>Originally posted by **fl34b4g** June 16, 2020</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular website?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** 
www.letterboxd.com | Letterboxd

**What should the Presence display?** 
What page you're browsing/viewing, what movie title you're watching.  If possible also what trailer ur watching. </div>

**Comment by elijaholmos** [comment]
I would like to see this added as well
