### ISSUE TITLE
OpenSea | opensea.io

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5235]
### Discussed in https://github.com/PreMiD/Presences/discussions/5000

<div type='discussions-op-text'>

<sup>Originally posted by **elijaholmos** December  6, 2021</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** 
OpenSea

**What should the Presence display?** 
Which page is being viewed, eg "Browsing Collection $COLL_NAME", "Looking at BillionaireZombiesClub #2558"

**If possible, please provide a logo for the service (512x512 minimum)** 
![opensealogo](https://user-images.githubusercontent.com/35435704/144887112-582c2f63-8134-4f19-bf61-0e0baefa82e2.png)
</div>

**Comment by CrypticXT** [comment]
Could you assign me? Currently working on that
