### ISSUE TITLE
AnimeOne | animeone.my.id

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5244]
### Discussed in https://github.com/PreMiD/Presences/discussions/4583

<div type='discussions-op-text'>

<sup>Originally posted by **CloudStriker** March 31, 2021</sup>
- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** ミナユキ#0500

**What's the name of the service?** AnimeOne.my.id | AnimeOne 

**What should the Presence display?** Show what ur watching with title, episode, and time

**If possible, please provide a logo for the service (512x512 minimum)** 
![logo](https://user-images.githubusercontent.com/67287660/113122346-8025d700-924e-11eb-8b8d-206f23b5ecfe.png)

</div>

**Comment by shiseni** [comment]
Wanted to make a presence for this site, but it doesn't seem to be available anymore.

**Comment by DarkVillager** [comment]
![image](https://user-images.githubusercontent.com/42322979/230726266-55ca3308-7f33-4084-842a-cad31f05e3e9.png)
@Bas950 Website doesn't exist anymore.
