### ISSUE TITLE
PuhHosting | puh.hosting

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5248]
### Discussed in https://github.com/PreMiD/Presences/discussions/4906

<div type='discussions-op-text'>

<sup>Originally posted by **YTToXy** November 14, 2021</sup>
**Prerequisites and essential questions**

- [x] Is it a popular site? 
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region? 
- [ ] Is the site a paid service? (e.g. Netflix, Hulu) 
- [ ] Does the website feature NSFW content? (e.g. porn, etc...) 
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? 

**What's the name of the service?** 
PuhHosting | https://www.puh.hosting/

**What should the Presence display?**
Name, Action, Page/Product, Time

**If possible, please provide a logo for the service (512x512 minimum)**
![InShot_20211115_071444348.jpg](https://user-images.githubusercontent.com/77928193/141731660-4254289a-d6a2-4d47-a212-2a71b4251feb.jpg)</div>

**Comment by SeMiD** [comment]
Converted to issue

**Comment by DarkVillager** [comment]
@Bas950 Website doesn't exist anymore.
![image](https://user-images.githubusercontent.com/42322979/230726304-495e0c37-887c-4744-a3a0-e329d2439321.png)
