### ISSUE TITLE
AnimeGenzai | animegenzai.xyz

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5249]
### Discussed in https://github.com/PreMiD/Presences/discussions/4911

<div type='discussions-op-text'>

<sup>Originally posted by **TokyoTF** November 15, 2021</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [x] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** www.animegenzai.xyz | AnimeGenzai

**What should the Presence display?** Show if it is on the main page or is in an episode and a button to go to see it 

**If possible, please provide a logo for the service (512x512 minimum)** ![ ](https://i.imgur.com/isxCRtS.png) </div>

**Comment by shiseni** [comment]
![image](https://user-images.githubusercontent.com/37224822/209398969-7198255e-6d45-4d63-9bcc-63455b1b47a9.png)

**Comment by V3CT0RBUG** [comment]
> ![ image](https://user-images.githubusercontent.com/37224822/209398969-7198255e-6d45-4d63-9bcc-63455b1b47a9.png)

the domain was changed https://animegenzai.net
