### ISSUE TITLE
Dscovery + | www.discoveryplus.com

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5251]
### Discussed in https://github.com/PreMiD/Presences/discussions/4889

<div type='discussions-op-text'>

<sup>Originally posted by **ComputerComa** November 10, 2021</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [x] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** 
www.discoveryplus.com | Discovery Plus
**What should the Presence display?** 
Similar to other streaming services (Eg, Netflix, Hulu, etc.) 
So something similar to 
 - Browsing Homepage (when on the homepage)
 - Watching {show/series/} 
      - {Season number} (if applicable) {Episode Number} (if applicable)
      - Time Remaining (If possible)
      - Status buttons to view the series and/or Episode
      
      
**If possible, please provide a logo for the service (512x512 minimum)** 
![favicon_512x512](https://user-images.githubusercontent.com/68386555/141153380-be666f62-66e7-4e0f-8838-0f1af932e708.png)

</div>

**Comment by DarkVillager** [comment]
Already done.
