### ISSUE TITLE
Fmovies | fmovies.to

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5254]
### Discussed in https://github.com/PreMiD/Presences/discussions/4868

<div type='discussions-op-text'>

<sup>Originally posted by **javereg** November  4, 2021</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

Discord name: Javere#3944

**What's the name of the service?** https://fmovies.to/ | Fmovies

**What should the Presence display?** 
- Show name
- Episode you are watching
- Time elapsed/left
- Browsing thru the webpage

**If possible, please provide a logo for the service**
![FMovies_Logo](https://user-images.githubusercontent.com/93702143/140275422-3fbae354-5d14-49a2-9659-c7a34f972917.png)

</div>

**Comment by mike-ul** [comment]
The discussion page you have listed here doesn't exist anymore, will this still be worked on or looked into?

**Comment by kyrie25** [comment]
> The discussion page you have listed here doesn't exist anymore, will this still be worked on or looked into?

Yes
