### ISSUE TITLE
MangaFreak | mangafreak.net

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5255]
### Discussed in https://github.com/PreMiD/Presences/discussions/4867

<div type='discussions-op-text'>

<sup>Originally posted by **javereg** November  4, 2021</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

Discord name: Javere#3944

**What's the name of the service?** https://w12.mangafreak.net/ | MangaFreak

**What should the Presence display?** 
-Manga title
-Chapter number
-Time spent reading that chapter
-Browsing thru the webpage

**If possible, please provide a logo for the service 
![7JHOJADN_400x400](https://user-images.githubusercontent.com/93702143/140274237-2be65608-00e2-48f3-9577-6348a83360c6.jpg)

</div>

**Comment by javereg** [comment]
Page updated: https://w13.mangafreak.net/

**Comment by RisingSunLight42** [comment]
I'll add this presence soon, website is not too complicated, maybe I'll PR the addition today or tomorrow.

**Comment by javereg** [comment]
> I'll add this presence soon, website is not too complicated, maybe I'll PR the addition today or tomorrow.

thank you
