### ISSUE TITLE
Mangago | mangago.me

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5266]
### Discussed in https://github.com/PreMiD/Presences/discussions/4747

<div type='discussions-op-text'>

<sup>Originally posted by **Ra1nnn** October 11, 2021</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

What's the name of the service? -> Mangago (https://www.mangago.me)

What should the Presence display? -> Name of the manga am reading and at what chapter, as well as the total time, reading.

logo;
![icon (2)](https://user-images.githubusercontent.com/92271963/136798224-bd902396-6eb2-42dd-b50e-108cfa03fdc9.png)</div>

**Comment by DarkVillager** [comment]
@Bas950 Website doesn't exist anymore.
