### ISSUE TITLE
Mr.Piracy | mrpiracy.site

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5300]
### Discussed in https://github.com/PreMiD/Presences/discussions/4466

<div type='discussions-op-text'>

<sup>Originally posted by **Ubastii** May 25, 2020</sup>
![mrpiracy](https://user-images.githubusercontent.com/64856723/82842532-d8bf7180-9ed1-11ea-8c86-5b5e18b9e8ac.PNG)
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Bastet#6368

**What's the name of the service?** Mr.Piracy |  https://mrpiracy.site/

**What should the Presence display?** What movie/tv show is now playing, something like Netflix.

**If possible, please provide a logo for the service (512x512 minimum)** 
</div>

**Comment by DarkVillager** [comment]
![image](https://user-images.githubusercontent.com/42322979/230732007-41b422fc-33c4-4bcc-a8cc-23ab91591bf9.png)
@Bas950 the site no longer exists.
