### ISSUE TITLE
IDLIX | 195.2.81.61

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5306]
### Discussed in https://github.com/PreMiD/Presences/discussions/4626

<div type='discussions-op-text'>

<sup>Originally posted by **kyotomizuko** August 24, 2021</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**IDLIX | idlix.cc (but the domain always changing)** 

**Watching which movie / series / episode** 

**If possible, please provide a logo for the service (512x512 minimum)** 
</div>

**Comment by theusaf** [comment]
The IP address in this issue seems to be outdated, replaced by #6894
