### ISSUE TITLE
Funimation Request

### ISSUE THREAD

**Issue by Hunterreach** [PreMiD/Presences#531]
**What's the name of the service?**
www.funimation.com | Funimation

**What should the Presence display?**
Information about the current video you are streaming

**Why do you want support for this service?**
Many people use this website to watch anime or shop on and I think it would go great with the Crunchyroll rich presence 
**Are you able to provide an image for the service? (512x512 minimum)**
https://www.google.com/imgres?imgurl=https%3A%2F%2Fmedia.licdn.com%2Fdms%2Fimage%2FC4E0BAQGR7zTdt48F5w%2Fcompany-logo_200_200%2F0%3Fe%3D2159024400%26v%3Dbeta%26t%3DZU5gF-xRNGgUqW_YiHN-lR-G-axk4Z5CbyaySbRso48&imgrefurl=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Ffunimation&docid=H2NQiqNKPCLRgM&tbnid=htZtZQ3PlKNz3M%3A&vet=10ahUKEwi5o5q1pbjlAhVFIKwKHcRJBdoQMwh_KAYwBg..i&w=200&h=200&bih=1030&biw=2046&q=funimation&ved=0ahUKEwi5o5q1pbjlAhVFIKwKHcRJBdoQMwh_KAYwBg&iact=mrc&uact=8
![0](https://user-images.githubusercontent.com/57019003/67603860-15629900-f748-11e9-9ce4-1229ff8c9536.png)

**Comment by frozaum** [comment]
duplicate #35
