### ISSUE TITLE
Wanflix | Wanflix.app

### ISSUE THREAD

**Issue by Dams678** [PreMiD/Presences#532]
**What's the name of the service?**
Ex. https://www.wanflix.app/| Wanflix

**What should the Presence display?**
Informations about browsing catalogs + the current video

**Why do you want support for this service?**
L&T is my favorite youtubers and this fan site is great for all wankil lovers 

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image
https://i.imgur.com/u5ETeIh.png
Or
https://i.imgur.com/DQkkUIt.png

**Comment by frozaum** [comment]
Hey @Dams678, can you provide a better reason for why you want support this service, otherwise thanks

**Comment by Dams678** [comment]
Update @frozaum

**Comment by Dams678** [comment]
Can you add the donator too plz ?  @frozaum

**Comment by eggsywashere** [comment]
Is this suppose to happen? Seems like the page does not contain anything for me.

![image](https://user-images.githubusercontent.com/13917975/67963215-4d1d8500-fc0f-11e9-886e-be9c2e977259.png)

**Comment by Dams678** [comment]
Hmm no i think the api is off for this moment you have to wait a little !

**Comment by Dams678** [comment]
@eggsywashere I have contact the developpers he says that wiil work tomorrow

**Comment by Dams678** [comment]
@eggsywashere It works now ;)

**Comment by eggsywashere** [comment]
Alright, will try to work on it when I got time.
