### ISSUE TITLE
[Presence | Feature Request] Plex

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5331]
### Discussed in https://github.com/PreMiD/Presences/discussions/4645

<div type='discussions-op-text'>

<sup>Originally posted by **DrKain** January 21, 2020</sup>
**Describe the Bug**

The Plex presence should include the season and episode number for TV series.  
Example: S01E02 - Episode Name

**Steps to Reproduce**

1. Enable Plex presence
2. Play any TV show / Anime
3. Status displays episode title but not the episode number or season

**Expected Behavior**

Season and Episode number in title: S01E02 - Episode Name

**Screenshots**
Current:  
![1](https://i.imgur.com/94z5zKA.png)    
Expected:   
![2](https://i.imgur.com/4xVDxJR.png)  

**Environment**

 - OS:  Windows 10
 - Browser:  Firefox
 - Version:  72.0.1
 
 
**Additional context**

</div>

**Comment by sweezyio** [comment]
This has already been done:
![image](https://user-images.githubusercontent.com/33377824/232194154-95626612-335f-4a28-8408-ef54442d3b11.png)
