### ISSUE TITLE
Automatic Artwork Allocation and hyperlinks for Soundcloud Rich Presence

### ISSUE THREAD

**Issue by d3gw33b** [PreMiD/Presences#535]
**Is your feature request related to a problem? Please describe.**
A problem with rich presence is, just showcasing the service logo doesn't catch the eye of someone looking at your status. Spotify is different in that it already supports a special form of Rich Presence allowing for easy links being embedded and artwork, without limitation. Similar things can be applied with user scripts to work around this artificial limitation that exists for non-Spotify rich presence, though they have their own limitations as well. Whether or not these can be dealt with (automated clearing of art / rich presence icons, as seen in below link) is unknown to me. If anything, it's just an idea you might want to try entertaining, if you have nothing else of priority to look into.

**Describe the solution you'd like**
Automatic artwork display and clickable links to the source of the rich presence.

**Describe alternatives you've considered**
My alternative was a custom github / discord workaround, it can be found here https://github.com/demaisj/soundcloud-rp

**Additional context**
Pictures can be found on the previous link, but a direct url to an example image is here:
![image](https://user-images.githubusercontent.com/57075973/67642242-0f9fbb80-f8e0-11e9-89a1-ce90156ccd8c.png)

**Comment by frozaum** [comment]
Yo, even though i'm not a developer and simply a guy who does some stuff here, so i will talk what i already know, everyone can correct me.

So, about the cover art situation, our developer (@Timeraa) already tried that with YouTube and their thumbnails, and it worked, but, Discord (for some reason) thinks it's not funny to use api from other services to use on Rich Presence, and it started to **ban everyone who did that**  and users that used this option from soundcloud-rp started to get banned, so, to PreMiD comply with the Discord's Terms of Service, he decided to scrap the idea,

And about the "hyperlink" idea, it's impossible and it's only restrict to Spotify.

[tl;dr](https://www.youtube.com/watch?v=JA560pf3Up4)

Closed.

**Comment by d3gw33b** [comment]
thanks for the reply. love yall 🙏
