### ISSUE TITLE
Set Filmizle | www.setfilmizle.vip

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5368]
### Discussed in https://github.com/PreMiD/Presences/discussions/4489

<div type='discussions-op-text'>

<sup>Originally posted by **vutix** September  8, 2020</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** ◈ VutiX#6666

**What's the name of the service?** https://www.setfilmizle.vip/

**What should the Presence display?** what we watch what we do on the site and more

**If possible, please provide a logo for the service (512x512 minimum)** https://hizliresim.com/p9scfv
</div>

**Comment by DarkVillager** [comment]
@Bas950 Website no longer seems to exist.
![image](https://user-images.githubusercontent.com/42322979/230732438-69698431-c5b7-45fa-bd6a-3da252a77860.png)
