### ISSUE TITLE
Mangago | mangago.com

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5399]
### Discussed in https://github.com/PreMiD/Presences/discussions/4529

<div type='discussions-op-text'>

<sup>Originally posted by **Stangtang** December  7, 2020</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**weewow#7272** 

**http://www.mangago.me** 

**What manga you are reading, what chapter, what page, and how long you have been reading.** 

**If possible, please provide a logo for the service (512x512 minimum)** 
</div>

**Comment by DarkVillager** [comment]
mangago.com redirects to mangago.me

@Bas950 both sites don't work
![image](https://user-images.githubusercontent.com/42322979/230732684-7bdc6767-4778-419c-9d75-2980107b15c1.png)
