### ISSUE TITLE
https://mangalivre.com/ | Manga Livre

### ISSUE THREAD

**Issue by Hyakkikkj** [PreMiD/Presences#540]
**What's the name of the service?**
Ex. www.youtube.com | YouTube

**What should the Presence display?**
Informations about the current video

**Why do you want support for this service?**
Tell us why you want to have support for this website. Please don't just tell us "I use it all the time"

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image

**Comment by Hyakkikkj** [comment]
Qual o nome do serviço? https://mangalivre.com

O que a presença deve exibir? titulo do manga sendo lido no momento

Por que você deseja suporte para este serviço? um ótimo sites de ler manga

![image](https://user-images.githubusercontent.com/57118915/67727991-3e925c00-f9ca-11e9-9b12-586559f12545.png)

**Comment by frozaum** [comment]
duplicate #516
