### ISSUE TITLE
Selective-Network

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5414]
### Discussed in https://github.com/PreMiD/Presences/discussions/4441

<div type='discussions-op-text'>

<sup>Originally posted by **HJMODS** January 18, 2020</sup>
* [ ] Is it a popular site?
* [x] Is the website older than 2 months?
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service?
* [ ] Does the website feature NSFW content?
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** Selective-Network  /  Selective-Network.co.uk

**What should the Presence display?** what page your on and name of the site

**If possible, please provide a logo for the service (512x512 minimum)** 
![LOGO](https://user-images.githubusercontent.com/54513673/72668267-088ad400-3a1d-11ea-9483-c74d35e14e02.png)
</div>

**Comment by DarkVillager** [comment]
@Bas950 site no longer seems to exist.
![image](https://user-images.githubusercontent.com/42322979/230732776-fc6b3fe1-572d-4f68-a53d-1142ec96c2f0.png)
