### ISSUE TITLE
Animes One HD | animesonehd.xyz

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5446]
### Discussed in https://github.com/PreMiD/Presences/discussions/4477

<div type='discussions-op-text'>

<sup>Originally posted by **davicosst** July 15, 2020</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Galactus#2655

**What's the name of the service?** https://animesonehd.xyz/

**What should the Presence display?** Animes One HD

**If possible, please provide a logo for the service (512x512 minimum)** https://prnt.sc/tibitg
</div>

**Comment by theusaf** [comment]
Website no longer exists
