### ISSUE TITLE
All MetaBrainz websites | metabrainz.org

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5460]
### Discussed in https://github.com/PreMiD/Presences/discussions/4454

<div type='discussions-op-text'>

<sup>Originally posted by **fr0r** March  3, 2020</sup>
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
fror#9493
**What's the name of the service?** 
MetaBrainz | metabrainz.org
MusicBrainz | musicbrainz.org
MusicBrainz Picard | picard.musicbrainz.org
Cover Art Archive | coverartarchive.org
CritiqueBrainz | critiquebrainz.org
AcousticBrainz | acousticbrainz.org
BookBrainz | bookbrainz.org
ListenBrainz | listenbrainz.org
MessyBrainz | messybrainz.org
**What should the Presence display?** 
A lot of stuff (What page/book/album are you seeing, wiki, etc.)
**If possible, please provide a logo for the service (512x512 minimum)** 
*MetaBrainz*
![](https://menma.is-inside.me/xPzLZIqK.png)

*MusicBrainz*
![](https://menma.is-inside.me/emMQKmoD.png)

*MessyBrainz*
![](https://menma.is-inside.me/EzWcuhel.png)

*ListenBrainz*
![](https://menma.is-inside.me/Zyte3Uts.png)

*BookBrainz*
![](https://menma.is-inside.me/ETplt8Al.png)

*AcousticBrainz*
![](https://menma.is-inside.me/JRF84C2f.png)

*CritiqueBrainz*
![](https://menma.is-inside.me/EDFsBfEB.png)

*Cover Art Archive*
![](https://menma.is-inside.me/YuGwnPx3.png)

*MusicBrainz Picard*
![](https://menma.is-inside.me/nnFXk7Ua.png)</div>

**Comment by theusaf** [comment]
Skipping Cover Art Archive - Not really a website that is presence-worthy
Skipping AcousticBrainz - The site is being shut down in a few months

**Comment by theusaf** [comment]
Skipping MessyBrainz - Redirects to ListenBrainz
