### ISSUE TITLE
mavostfr | mavostfr.com

### ISSUE THREAD

**Issue by SeMiD** [PreMiD/Presences#5464]
### Discussed in https://github.com/PreMiD/Presences/discussions/4457

<div type='discussions-op-text'>

<sup>Originally posted by **BigBoss320** April  3, 2020</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  Ewen.C#8705

**What's the name of the service?**  mavostfr.com | MaVostfr

**What should the Presence display?**  It's an anime website, so display the video that we watching (like YouTube Presence)

**If possible, please provide a logo for the service (512x512 minimum)** 
Choose your favorite.
Normal logo : 
![logo original](https://user-images.githubusercontent.com/44122706/78380615-6e2a3d80-75d4-11ea-9f88-cefba1afd821.jpg)
Logo created by me :
![logo perso](https://user-images.githubusercontent.com/44122706/78380650-7c785980-75d4-11ea-932d-57414b5212a9.jpg)

</div>

**Comment by DarkVillager** [comment]
@Bas950 website no longer seems to exist and just redirect.
![image](https://user-images.githubusercontent.com/42322979/230733093-89a66111-25ea-4632-b9dc-f7b0b36ea9fc.png)
