### ISSUE TITLE
Flightradar24 | flightradar24.com

### ISSUE THREAD

**Issue by EncryptedDev** [PreMiD/Presences#5486]
### Discussed in https://github.com/PreMiD/Presences/discussions/5485

<div type='discussions-op-text'>

<sup>Originally posted by **developedbyalex** January  3, 2022</sup>
Prerequisites and essential questions

- [x] Is it a popular site?
- [x] Is the website older than 2 months?
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**
ᴀʟᴇx#0001

**What's the name of the service?**
https://www.flightradar24.com/ I Flightradar24
**What should the Presence display?**
If they're tracking a flight, if so what flight they're tracking, the airport they're going from and landing. If not, just "viewing map"

If possible, please provide a logo for the service (512x512 minimum)
https://i.imgur.com/k0iE2zY.png</div>

**Comment by joerkig** [comment]
Working on this
