### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by andrecc-7** [PreMiD/Presences#5487]
### Description

I've tested both Netflix and Soundcloud and they work out of the box, however Youtube activity is not displayed on discord.

### Steps to Reproduce

1. Open any youtube video.
2. Play and look for the activity on your discord profile (for example, by clicking on the profile in a chat).

### Expected Behavior

Current yotube video playing displayed on activity status

### Actual Behavior

Status remains unchanged

### Page URL

https://www.youtube.com/watch?v=N36chN7a-aU

### Operating System (OS)

Windows 11

### Browser

Brave

### Browser Version

Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)

**Comment by andrecc-7** [comment]
The same happens on firefox.

**Comment by EncryptedDev** [comment]
Please take a screenshot of your console whilst you're on that page. 

You can open your console by pressing `ctrl + shift + r` and going to the "Console" tab

**Comment by andrecc-7** [comment]
![2022-01-04_15-08](https://user-images.githubusercontent.com/56041659/148079708-91fda135-7f6c-4a7f-a90a-601912bd4510.png)

**Comment by andrecc-7** [comment]
Okok, it's closed. I tested it and it works. Thanks!
