### ISSUE TITLE
Tio Anime | tioanime.com

### ISSUE THREAD

**Issue by Chocolateunu** [PreMiD/Presences#5490]
### Description

The chapters numbers that start with two digits, the presence spoils them, remaining as shown in the screenshot.

### Steps to Reproduce

1.- Go to the tioanime.com page
2.- Find any anime with more than 9 episodes
3.- You will see the result shown in the screenshot

### Screenshots

![sus](https://user-images.githubusercontent.com/69604481/147970152-fe17973e-ab68-4faf-bc8b-0a701dc99e85.png)

### Expected Behavior

Hope the numbers are placed correctly

### Actual Behavior

When this error occurs, it looks bad both aesthetically and understandably.

### Page URL

The error occurs with almost any anime. I recommend going to this https://tioanime.com/anime/slam-dunk , since it has 101 chapters.

### Operating System (OS)

Windows 10

### Browser

Chrome

### Browser Version

96.0.4664.110 (Build oficial) (64 bits)

**Comment by u0f** [comment]
Fixed. 
![image](https://user-images.githubusercontent.com/45316362/148196211-1ada2f78-1202-4e72-a0bc-156aaa83821e.png)
