### ISSUE TITLE
Netflix not displaying on status

### ISSUE THREAD

**Issue by gk345851** [PreMiD/Presences#5495]
### Description

Everything other than netflix comes up on status but not not netflix

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/76420721/148042610-4e2a4e49-1673-4c4e-8a4e-42b7f6b31327.png)

![image](https://user-images.githubusercontent.com/76420721/148042662-9593bd4b-da6c-4088-9e2f-bf170c42b507.png)

### Expected Behavior

to show netflix on status

### Actual Behavior

nothing is being display when netflix is being used

### Page URL

no where

### Operating System (OS)

Windows 11

### Browser

Firefox

### Browser Version

95.0.2 (64-bit)

**Comment by EncryptedDev** [comment]
Please fill in the template properly, there is always a page.
