### ISSUE TITLE
Amazon Music presence not working

### ISSUE THREAD

**Issue by gully32** [PreMiD/Presences#5496]
### Description

Hi, my Amazon Music presence if not working, I have completed the troubleshooting guide to no avail. If I have the Amazon presence enabled, it will display just Amazon. I had it working yesterday, but it decided to die on me today. Any help greatly appreciated 🙂

### Steps to Reproduce

1. go to https://music.amazon.co.uk/
2. Presence does not update.

### Screenshots

![image](https://user-images.githubusercontent.com/34196438/148044651-8625146d-74e9-4b27-989c-e2588af6f685.png)
![image](https://user-images.githubusercontent.com/34196438/148044730-8e2decf9-fe52-47c7-b6f2-898d3743efee.png)

### Expected Behavior

My presence to update and show my amazon music status

### Actual Behavior

It didn't update

### Page URL

https://music.amazon.co.uk/?ref=dm_lnd_hf_listn_bc786fec_DMM_acq_amvan

### Operating System (OS)

Windows 11

### Browser

Brave

### Browser Version

Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)

**Comment by StrikerFRFX** [comment]
Fixing 👍

**Comment by gully32** [comment]
Thanks :)
