### ISSUE TITLE
Hashnode | hashnode.com

### ISSUE THREAD

**Issue by kr-anurag** [PreMiD/Presences#5497]
### Website name

Hashnode

### Website URL

https://hashnode.com/

### Website logo

https://cdn.hashnode.com/res/hashnode/image/upload/v1611902473383/CDyAuTy75.png?auto=compress

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Hashnode is a blogging platform, so the presence should show user's activity, like on the homepage, reading an article, viewing someone's profile, viewing a blog, etc.

**Comment by kyrie25** [comment]
Every single blogger on the site has their own unique domains so a presence saying "Reading an article" might not be possible imo
<details>
<summary> Examples </summary>

![image](https://user-images.githubusercontent.com/77577746/148358014-fd408c28-3e7d-4f91-83de-2ee8c3400f01.png)
![image](https://user-images.githubusercontent.com/77577746/148358167-fdbb1dd3-9714-4c45-8f6c-0466586bac5c.png)
</details>
