### ISSUE TITLE
[Presence | Feature Request] e621 - Add "View Search" and "View Post" Buttons

### ISSUE THREAD

**Issue by StormeTheCat** [PreMiD/Presences#5506]
### Presence name

e621

### Description

Add a "View Search" button when the user is in a search on e621 and add a "View Post" button to replace that one when viewing a post. Most other presences have this kind of feature, and would be much more convenient than attempting to make the search yourself.

**Comment by DarkVillager** [comment]
Working on it @StormeTheCat
