### ISSUE TITLE
Nimo TV | nimo.tv

### ISSUE THREAD

**Issue by auliaahmad165** [PreMiD/Presences#5507]
### Website name

Nimo TV

### Website URL

https://www.nimo.tv/

### Website logo

https://www.nimo.tv/nms/images/apple-touch-icon.67a0300e238e3718b383b6b3b46fb3b8.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Can you make it like Twitch Presences?

**Comment by Isa27-0** [comment]
duplicate of #5352
