### ISSUE TITLE
Service Name | Service URL

### ISSUE THREAD

**Issue by ka0s01** [PreMiD/Presences#5516]
### Description

when i open soap2day it says checking out the homepage and when i start watching a movie it still shows checking out the homepage

### Steps to Reproduce

1. go to this link - https://www5.soap2day.video/series/teen-wolf-7j3w8/1-1
2. the discord status says browsing homepage even when you watch the show

### Screenshots

![image](https://user-images.githubusercontent.com/79192508/148389747-67182380-1655-4957-bf92-f388d0a6147a.png)

### Expected Behavior

i expected it to show what movie i am watching

### Actual Behavior

it says im in homepage

### Page URL

https://www5.soap2day.video

### Operating System (OS)

windows 10

### Browser

opera gx

### Browser Version

LVL3 (core: 82.0.4227.50)

**Comment by Isa27-0** [comment]
Actually, the domain `soap2day.video` is not supported by presence, only with `soap2day.com` (#4266)
