### ISSUE TITLE
GG App | ggapp.io

### ISSUE THREAD

**Issue by StormeTheCat** [PreMiD/Presences#5518]
### Website name

GG App or GG|

### Website URL

https://ggapp.io/home

### Website logo

https://play-lh.googleusercontent.com/619WdQPQJiQcA55fCpiLEPE77X9yHegptE8wvKyA8hXcdHnkAe3u-aCCe-7TFRPNhuI

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

"Viewing [User Profile]" in line one, "Want to Play, Playing, Beaten, Completed, Shelved, Abandoned, Ratings, Reviews, Lists, Played, Collection" in line two

"Reading Review" in line one, "[Review Title]" in line two, "by [Username]" in line three

"Viewing List" in line one, "[List Title]" in line two

"Viewing Game" in line one, "[Game Title]" in line two

"Editing Game" in line one, "[Game Title]" in line two, quill or pencil icon for small image

"Viewing Home Page" in line one, nothing in line two

"Searching for:" in line one, "[Search Query]" in line two, magnifying glass for small image

"Viewing Trending Page" in line one, nothing in line two

A button that leads to everything listed for line two, with an option to turn them off.

The large image replaced by the game cover art or user profile picture whenever possible, with an option to toggle this off.

An option to toggle whether it says "Playing GG App" or "Playing GG|" if possible.

An option to toggle on and off a time elapsed timer.

**Comment by kyrie25** [comment]
I'll claim this
