### ISSUE TITLE
Service Name | Service URL

### ISSUE THREAD

**Issue by rmj1001** [PreMiD/Presences#5530]
### Description

YouTube Music does not show up as a rich presence on Discord.

### Steps to Reproduce

1. Turn on PreMID application
2. Turn on Discord
3. Go to https://music.youtube.com/
4. View discord profile

### Expected Behavior

Expected to see YouTube Music show up in rich presence.

### Actual Behavior

Did not see any rich presence when using YouTube Music.

### Page URL

music.youtube.com

### Operating System (OS)

Linux (Fedora 35, using AppImage)

### Browser

Microsoft Edge

### Browser Version

97.0.1072.55

**Comment by Slowlife01** [comment]
This is unlikely Presence's bug, please open a ticket on our [support sever](https://discord.premid.app) first.
