### ISSUE TITLE
Jellyfin | jellyfin.org

### ISSUE THREAD

**Issue by RubberDuckShobe** [PreMiD/Presences#5540]
### Description

I have a Jellyfin server running in my local network at http://192.168.178.101:8096, but the Jellyfin presence doesn't show anything on Discord at all.

Going to the official site at https://jellyfin.org also shows nothing.

### Steps to Reproduce

1. Open Jellyfin Web client or official site
2. Open Discord
3. Look at your status

### Expected Behavior

Discord shows the Jellyfin Rich Presence

### Actual Behavior

The status is completely blank, not even something like "Playing Jellyfin" is shown

### Page URL

http://192.168.178.101:8096/web/index.html#!/video

https://jellyfin.org

### Operating System (OS)

Windows 10

### Browser

Firefox Nightly

### Browser Version

97.0a1

**Comment by alexbcberio** [comment]
Thanks for the report, I can reproduce your issue if I access using http protocol (gives autorización error on some requests). I'll take a look at the issue and implement a fix.

![image](https://user-images.githubusercontent.com/22194879/148644497-afc729d0-9d88-46c3-8c68-976c49c7a15c.png)

It does work correctly over https, here's my instance if you wanna test if out [`media.alexbcberio.eus`](https://media.alexbcberio.eus).

Regarding Jellyfin website, it does not show up either to me, I'll also check it out and fix it.

**Comment by RubberDuckShobe** [comment]
If I go to your instance, it still doesn't work on my end.

**Comment by alexbcberio** [comment]
Open the developer tools `F12` or `ctrl + shift + i` and check on the console tab. It should log a message like this one.

![image](https://user-images.githubusercontent.com/22194879/148647367-dc7ac28c-ded6-4240-a178-5cda60439ad2.png)

Try reloading the page if it does now show up

**Comment by RubberDuckShobe** [comment]
I've opened the console and reloaded, I don't get any message like that

**Comment by alexbcberio** [comment]
Perfect, I have found the issue why it does not show up on the official website so I will check out the other issue.

**Comment by alexbcberio** [comment]
I have found the issue, and I'm currently finishing a patch. The problem was that I was not refreshing the credentials after the user logged in.
The issue could be reproduced from both `http` and  `https`.
