### ISSUE TITLE
Funimation | Funimation.com

### ISSUE THREAD

**Issue by LiviYan** [PreMiD/Presences#5575]
### Description

So when viewing a video on Funimation, instead of having the "time left" and other info showing on my discord presence, it just shows "Funimation" and no other information about the video I'm watching, BUT it does flash the correct information when I play and pause the video. The correct information also seems to show when the video is paused, but NOT when the video is playing. Another weird thing I have noticed is that if I completely restart my Discord and then click play... it works and show the correct information of the video I am playing until I pause it and play it again, then it goes back to being broken. This is only happening with Funimation presence. Other things like Youtubes presence works perfectly for me. 

I would like to add that I also tried turning off all my extensions and the bug was still present. And reinstalled the Funimation Presence multiple times.

### Steps to Reproduce

1. Go to Funimation website ( with PreMiD and activity status on discord turned on )
2. Play any video
3. Check discord presence ( it will flash the correct info whenever you play a video but quickly hide it in place of just "Funimation" )

### Screenshots

https://i.gyazo.com/8ba4b09bd5aad150c58d0670d50b7340.mp4
![8ba4b09bd5aad150c58d0670d50b7340](https://user-images.githubusercontent.com/86540561/149211068-0807bfa9-2b6f-4e31-9f22-fa346527dbe7.gif)

### Expected Behavior

I expected for the video info to be displayed the whole time, not be hidden immediately. 

### Actual Behavior

The video playing's info will flash up when you click play, but is quickly hidden and replaced with just "Funimation"

### Page URL

https://www.funimation.com/v/angels-of-death/your-grave-is-not-here?lang=&a=1&qid=

### Operating System (OS)

Window 10

### Browser

Chrome and Opera GX

### Browser Version

Chrome Version 97.0.4692.71

**Comment by Ushiora** [comment]
I doubt this will ever get fixed because this bug has happened with FUNimation for the past couple of months and it still wasn't updated.

**Comment by LiviYan** [comment]
But did anyone report it in the last couple of months? Cause I saw no bug reports for this issue. Kinda needs to get reported to get fixed. Also, that means you've had this bug as well?
