### ISSUE TITLE
KissAsian, MyDramaList, Youtube Presences

### ISSUE THREAD

**Issue by Shiro-san95** [PreMiD/Presences#5604]
### Description

Not so sure if these are issues or broken pages, but list pages on MyDramaList doesn't seem to be specified as activity, like this: https://mydramalist.com/dramalist/chunyu / https://mydramalist.com/dramalist/KanashimiAngel / https://mydramalist.com/dramalist/xxmai 

Same goes for https://mydramalist.com/stats/leaderboards / https://mydramalist.com/people/top / https://mydramalist.com/messages / https://mydramalist.com/movies/popular / https://mydramalist.com/movies/upcoming / https://mydramalist.com/add/title/details / https://mydramalist.com/add/person/details etc. (will just give these ones as example, as it might not be something that's broken)

It doesn't have the activity icon pop up, but does seem to show without any time elapsed or specific page details if you click into discord profile. Maybe it's just like that and not broken?

Noticed the same thing for youtube: https://www.youtube.com/feed/explore (and i think same when you click into most of those options like "Trending, Music, Movies & Shows, Gaming, News, Sports" 
And short vids: https://www.youtube.com/shorts/LUg0vNVfCqM (which this one doesn't seem to show anything)

For KissAsian, same for pages like these: https://kissasian.li/BookmarkList / https://kissasian.li/Profile / https://kissasian.li/Message/GetKPoint / https://kissasian.li/RequestDrama / and actor pages like this: https://kissasian.li/Actor/Uhm-Hyun-Kyung

For spotify: https://open.spotify.com/ 

### Steps to Reproduce

1. go to these links: https://mydramalist.com/dramalist/chunyu / https://mydramalist.com/stats/leaderboards / https://mydramalist.com/people/top / https://mydramalist.com/messages / https://mydramalist.com/movies/popular / https://mydramalist.com/movies/upcoming / https://mydramalist.com/add/title/details / https://mydramalist.com/add/person/details /  https://www.youtube.com/feed/explore (and i think same when you click into most of those options like "Trending, Music, Movies & Shows, Gaming, News, Sports" / For KissAsian, same for pages like these: https://kissasian.li/BookmarkList / https://kissasian.li/Profile / https://kissasian.li/Message/GetKPoint / https://kissasian.li/RequestDrama / and actor pages like this: https://kissasian.li/Actor/Uhm-Hyun-Kyung / For https://open.spotify.com/ (think just any Spotify links)
2.  And can see it doesn't have the activity icon out, but does show if you click the discord profile, just without specified details or time elapsed. 
3. And then for youtube short vids like this https://www.youtube.com/shorts/LUg0vNVfCqM (which this one doesn't seem to show anything)

### Screenshots

![MDL Premid issue](https://user-images.githubusercontent.com/97920310/149842797-4e3f0aed-48a1-4644-8968-a91b10f0db58.png)

![KissAsian Premid Issue](https://user-images.githubusercontent.com/97920310/149842798-2d6adf30-e882-436f-85f9-d9d7456da34e.png)

![Youtube Premid issue](https://user-images.githubusercontent.com/97920310/149842799-0a59432f-eac3-4ea8-9215-606bacb936e3.png)

### Expected Behavior

To show details of the pages and have the activity icon in status bar.

### Actual Behavior

Not showing activity icon + no page details + no time elapsed 

### Page URL

https://mydramalist.com/dramalist/chunyu & https://www.youtube.com/feed/explore

### Operating System (OS)

Windows 10

### Browser

Chrome

### Browser Version

97.0.4692.71 (Official Build) (64-bit)

**Comment by DarkVillager** [comment]
Youtube shorts part will be resolved by #6780

**Comment by EncryptedDev** [comment]
Messy issue. Split each presence bug into a different issue
