### ISSUE TITLE
Vlive | Vive.tv

### ISSUE THREAD

**Issue by Shiro-san95** [PreMiD/Presences#5606]
### Description

It does not work every time when I install a new presence or uninstall a presence. I noticed that the presence setting for youtube and netflix also seems to reset back to default when i install/uninstall a presence (might be related?).  

### Steps to Reproduce

1. uninstall or install any sort of presence
2. go to vlive.tv 
3. Then check discord 
4. Go to vlive presence setting, and you will see the language option does not pop up

### Screenshots

![vlive premid issue](https://user-images.githubusercontent.com/97920310/149847479-61f79476-d74e-4f4d-b0e8-a3681ce472b8.png)

### Expected Behavior

Should show activity on discord

### Actual Behavior

Does not show anything 

### Page URL

vlive.tv

### Operating System (OS)

Windows 10

### Browser

Chrome

### Browser Version

97.0.4692.71 (Official Build) (64-bit)

**Comment by Slowlife01** [comment]
This is the Extension's issue.
