### ISSUE TITLE
Alternate Player for Twitch.tv | https://addons.mozilla.org/en-GB/firefox/addon/twitch_5/

### ISSUE THREAD

**Issue by admiralaspergerss** [PreMiD/Presences#5610]
### Website name

Alternate Player for Twitch.tv

### Website URL

https://addons.mozilla.org/en-GB/firefox/addon/twitch_5/

### Website logo

https://addons.mozilla.org/user-media/addon_icons/707/707675-64.png?modified=4a667809

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

So because twitch on firefox is absolute dogshit theres an alternate player extension for twitch and it is so much smoother and less pc taxing however it does not use the twitch.tv domain so the presence isnt picked up by PreMiD so i would be very greatful if it had its own presence or it was implemented into the current twitch.tv presence. thx

**Comment by Slowlife01** [comment]
If it doesn't have website then this won't work

**Comment by admiralaspergerss** [comment]
Did you even think of a way it could work before closing this?

**Comment by admiralaspergerss** [comment]
I just watched you edit that. the timing
