### ISSUE TITLE
Alternative player for twitch.tv

### ISSUE THREAD

**Issue by admiralaspergerss** [PreMiD/Presences#5612]
### Presence name

twitch.tv

### Description

So because twitch on firefox is absolute dogshit theres an alternate player extension for twitch and it is so much smoother and less pc taxing however it does not use the twitch.tv domain so the presence isnt picked up by PreMiD so i would be very greatful if it was implemented into the current twitch.tv presence to display it as if you were using the regular twitch.tv. thx

### Additional context

Link to the extension
[Alternative player for twitch.tv](https://addons.mozilla.org/en-GB/firefox/addon/twitch_5/)

**Comment by EncryptedDev** [comment]
This is an unofficial Twitch service

**Comment by admiralaspergerss** [comment]
Your point being?
