### ISSUE TITLE
HBO GO Asian Region

### ISSUE THREAD

**Issue by RazersMY** [PreMiD/Presences#5614]
### Presence name

HBO GO

### Description

Discord Activity Not Displaying While Streaming On HBO GO in Asian Region.
The Link For HBO GO Asian Region is : https://www.hbogoasia.my/

### Additional context

![HBO GO Asian Region](https://user-images.githubusercontent.com/97958605/149939460-18fc0911-2018-4e71-a509-056a14aeea2c.png)

**Comment by Northernside** [comment]
I made a pull request for this (#5620).
