### ISSUE TITLE
Stockx | stockx.com

### ISSUE THREAD

**Issue by fruitpunches** [PreMiD/Presences#5639]
### Website name

StockX

### Website URL

https://stockx.com/

### Website logo

https://d2hlo835aj7uqe.cloudfront.net/production/wp-content/uploads/2020/09/bloglogo_updated.jpg

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

I want to the items I click on with this presence, anything from shoes, hoodies, hats basically everything on the website. I also want it to display every category of the website also.

**Comment by kyrie25** [comment]
I'll claim this
