### ISSUE TITLE
Stockx | stockx.com

### ISSUE THREAD

**Issue by fruitpunches** [PreMiD/Presences#5648]
### Description

if i click a product in the related products section the presence doesn't update to the new product
or if i select an product from the home page it doesn't update either

ALSO after i search an product then click the product i searched the presence just stops working all together (only happened once)

![Screenshot 2022-01-23 122228](https://user-images.githubusercontent.com/98212456/150690205-575d44aa-91cc-45bc-b2fe-8e01a38fe08a.png)

### Steps to Reproduce

https://stockx.com/takashi-murakami-kaikai-kiki-flower-60-cm-cushion-rainbow

then click on ANY related product below it and the presence will not update 

### Expected Behavior

i expect the presence to update on every product i click

### Actual Behavior

After I clicked on my frist product everything works but when i click another under related products nothing happens, the presence also doesn't update if you are on the homepage then click any product form there.

### Page URL

https://stockx.com/ -- https://stockx.com/takashi-murakami-kaikai-kiki-flower-60-cm-cushion-rainbow

### Operating System (OS)

windows 10

### Browser

chrome

### Browser Version

Version 97.0.4692.99

**Comment by kyrie25** [comment]
None of these are reproduceable for me, double-check again on your side
