### ISSUE TITLE
Plex | app.plex.tv

### ISSUE THREAD

**Issue by diskxo** [PreMiD/Presences#5669]
### Description

When I play movies/TV series or music on Plex, using **either Firefox and Chrome**, 
I noticed that the presence is not shown to **other users**, but only on my **local client**.

Also, when I **maximize media** viewing within the Plex user interface (screenshot), 
the presence only shows the service title, and it seems to be visible to other users.

### Steps to Reproduce

1. Play Music/Films/TV Series on Plex

### Screenshots

![immagine](https://user-images.githubusercontent.com/64780086/151252104-f94404b4-d237-4d42-bf4e-a1f78fab18d7.png)
![photo_2022-01-26_22-45-40](https://user-images.githubusercontent.com/64780086/151252314-e57bf3bc-8953-4ab7-94e6-76fed0e745d9.jpg)
![immagine](https://user-images.githubusercontent.com/64780086/151252211-b4f5f1dd-1a53-4117-88f0-a3fff64c4032.png)

![photo_2022-01-26_22-45-45](https://user-images.githubusercontent.com/64780086/151252320-0b363538-c52a-46f1-a41d-1ceb51b1ca9c.jpg)

![immagine](https://user-images.githubusercontent.com/64780086/151253679-7492dc89-4002-4b42-b23b-a6bcc2da8d7f.png)

### Expected Behavior

show presence to other discord users

### Actual Behavior

the presence is not visible to other users

### Page URL

app.plex.tv

### Operating System (OS)

Windows 10

### Browser

Firefox

### Browser Version

96.0.2

**Comment by EncryptedDev** [comment]
>  I noticed that the presence is not shown to other users, but only on my local client.
This is a Discord issue, could be caused by the ongoing API issue or just a general issue. 

> Also, when I maximize media viewing within the Plex user interface (screenshot),
the presence only shows the service title, and it seems to be visible to other 
Very similar to #4908, just comment on that instead
