### ISSUE TITLE
AirSong | airsong.en.uptodown.com/android/download

### ISSUE THREAD

**Issue by FirestormDangerDash** [PreMiD/Presences#5676]
### Website name

AirSong

### Website URL

http://localhost:8088/

### Website logo

See attached

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

AirSong allows the unique ability for people with MP3 files on an android devices to stream the songs to a internal IP address using any web browser. I would like to see a method/Presence that allows PreMiD to grab song titles from that Chrome Tab. It solves two problems really. People with MP3 files still, and those with said files on their smartphone.
![logo_web](https://user-images.githubusercontent.com/8054455/151445715-4c6084f8-9f71-4d5e-8cf7-d0f4b41b7382.png)

**Comment by FirestormDangerDash** [comment]
I know you're doing your best, and might try the other ideas mentioned for better quality.

One further long shot idea is adding in hyperlinks to youtube basicly searching the current song/artist being played?
That should work perfectly for 95% of songs on peoples mp3s being played. :)

**Comment by kyrie25** [comment]
> I know you're doing your best, and might try the other ideas mentioned for better quality.
> 
> One further long shot idea is adding in hyperlinks to youtube basicly searching the current song/artist being played? That should work perfectly for 95% of songs on peoples mp3s being played. :)

I'm not sure I'm even allowed to do that, but have implemented other ones in the upcoming PR
