### ISSUE TITLE
OneNote | onenote.com

### ISSUE THREAD

**Issue by EncryptedDev** [PreMiD/Presences#5694]
### Discussed in https://github.com/PreMiD/Presences/discussions/5674

<div type='discussions-op-text'>

<sup>Originally posted by **AryanKrishnan** January 27, 2022</sup>
- [x] Is it a popular website?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** - OneNote

**What should the Presence display?** - Name of the Note as-well as the subtopic name we are writing on and how long we've been on the site.
 
![image](https://user-images.githubusercontent.com/65199490/151397927-4fdb0499-86b6-46c3-838b-64c6a24b6c0a.png)
</div>

**Comment by kyrie25** [comment]
I'll claim this
