### ISSUE TITLE
Nimo TV presence

### ISSUE THREAD

**Issue by zLuker** [PreMiD/Presences#5700]
### Website name

Nimo TV

### Website URL

https://www.nimo.tv

### Website logo

https://server-avatar.nimostatic.tv/1599514834540/202104061617693261163_1599514834540_avatar.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

the streamer I'm watching. twitch.tv presence model 😀🌸

**Comment by Slowlife01** [comment]
Duplicate of #5352
