### ISSUE TITLE
Archive of our own (AO3)

### ISSUE THREAD

**Issue by puddlee** [PreMiD/Presences#5714]
### Website name

Archive of our own

### Website URL

https://archiveofourown.org/

### Website logo

https://pbs.twimg.com/media/EkxZGVmVoAAgip3.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

just how it works on wattpad because ao3 is also a fanfic site :)

**Comment by Isa27-0** [comment]
Duplicate of #5343
