### ISSUE TITLE
Youtube Music presence should appear in Active Now tab

### ISSUE THREAD

**Issue by Utsav-Murudi** [PreMiD/Presences#5721]
### Presence name

YouTube Music

### Description

Currently the Youtube Music does not show up in Active Now tab.

It only shows like this:
![image](https://user-images.githubusercontent.com/76831372/152320377-f377e0b6-f8a1-471e-9ba6-caaeb0228874.png)

**Comment by DarkVillager** [comment]
> ### Description
> Currently the Youtube Music does not show up in Active Now tab.

Isn't this for all presences? or am I mistaken?

**Comment by Slowlife01** [comment]
No, this can be done by sending `startTimestamp`

**Comment by Utsav-Murudi** [comment]
@Slowlife01 Show Timestaps is enabled for Youtube Music but it still doesn't show up.
