### ISSUE TITLE
MangaLife | manga4life.com

### ISSUE THREAD

**Issue by BeoOL** [PreMiD/Presences#5727]
### Description

the "MangaLife" Presence isn't working, even tho the other ones are working just fine

### Steps to Reproduce

1. download the "mangalife" Presence from the presence store
2. go to [mangalife](https://manga4life.com) and read your desired manga
3. it doesn't show up on discord

### Screenshots

![image](https://user-images.githubusercontent.com/99027880/152538797-cf63a3c6-3e91-4493-8e24-d45efae63242.png)
![image](https://user-images.githubusercontent.com/99027880/152538934-c81d274b-2a89-46f0-ba1e-5721a801bb5c.png)
![image](https://user-images.githubusercontent.com/99027880/152539089-3baf9145-3b38-4e9e-87cb-cf898e811602.png)

### Expected Behavior

that it shows up on discord

### Actual Behavior

it doesn't show up

### Page URL

https://manga4life.com/read-online/Kaguya-Wants-To-Be-Confessed-To-chapter-252.html

### Operating System (OS)

windows 10

### Browser

Opera

### Browser Version

83.0.4254.27

**Comment by kyrie25** [comment]
Patched and waiting approval.
