### ISSUE TITLE
Abstract Radio | weareabstract.com

### ISSUE THREAD

**Issue by Bozzy171** [PreMiD/Presences#574]
**What's the name of the service?**
Ex. https://weareabstract.com | Abstract Radio

**What should the Presence display?**
Informations about the radio ( whats playing and who is live)

**Why do you want support for this service?**
Tell us why you want to have support for this website. Please don't just tell us "I use it all the time"

we love the idea of it for our radio as we have a fair few listeners and would love to see it show up on discord, we also want to have sting that stands for us.

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image
https://images-ext-2.discordapp.net/external/XEYqB2YMEm4kTzBgEmIGlb0vswX4GNwUx_wZbFYLYlw/https/abstractradio.kognise.repl.co/assets/favicon.png?width=375&height=375

**Comment by frozaum** [comment]
the image you provided is not 512x512.

**Comment by Bozzy171** [comment]
> the image you provided is not 512x512.

there you go 

https://cdn.discordapp.com/icons/632907934224875529/0ea5fc7c8d59144a8bef6dbf032bf5b1.png?size=128
