### ISSUE TITLE
YouTube Music | music.youtube.com

### ISSUE THREAD

**Issue by OfficialCRUGG** [PreMiD/Presences#5749]
### Description

When an artist doesn't have an artist profile (aka their video is on the "Various Artists - Topic" channel), their artist name isn't in an `<a>`-tag and doesn't get displayed in the rich presence.
This usually is the case for very new artists and some other random artists for some reason.

### Steps to Reproduce

1. Play this song https://music.youtube.com/watch?v=P8G-SL7iCW8
2. Observe rich presence

### Screenshots

![image](https://user-images.githubusercontent.com/25248999/152870838-208dac65-642d-4c6a-8ada-9a8ab643d84c.png)
![image](https://user-images.githubusercontent.com/25248999/152870848-e31fde9f-d5b8-4cad-ba9f-5f2f8ba67874.png)

### Expected Behavior

The artist should show up

### Actual Behavior

The artist doesn't show up

### Page URL

https://music.youtube.com/watch?v=P8G-SL7iCW8

### Operating System (OS)

macOS 12.1 Beta

### Browser

Edge

### Browser Version

Version 98.0.1108.43 (arm64)

**Comment by Kaisarion** [comment]
I'll claim this & look into it. Thanks

**Comment by EncryptedDev** [comment]
@Kaisarion Any updates?
