### ISSUE TITLE
Slaps | slaps.com

### ISSUE THREAD

**Issue by DieBraaiMeester** [PreMiD/Presences#5756]
### Website name

Slaps

### Website URL

https://slaps.com/

### Website logo

Original Logo

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Slaps is a Music sharing site where you can listen to entertainers music tracks to and support them

**Comment by Kaisarion** [comment]
Website is down lol

**Comment by Kaisarion** [comment]
It's fine now. Was not working when I went to visit.
