### ISSUE TITLE
VuiGhe.Net | Vui Ghê Anime Vietsub Online

### ISSUE THREAD

**Issue by dawkinnguyencentgaming** [PreMiD/Presences#577]
**What's the name of the service?**
https://vuighe.net/ | Vui Ghê Anime Vietsub Online

**What should the Presence display?**
Informations about the current video

**Why do you want support for this service?**
This is the best anime website in Vietnam, maintained by a company.

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image
https://i.imgur.com/THQfhnQ.png
https://i.imgur.com/HbICLoG.png

**Comment by popeyaho001** [comment]
pleaze, fix domain to vuighe1.com, vuighe.net don't work anymore, tks
