### ISSUE TITLE
Fbox Movies | www4.fbox.to

### ISSUE THREAD

**Issue by Zyxean** [PreMiD/Presences#5787]
### Description

Non working presence for fbox, and a request to clone the presence to work with fmovies.to ( same site 1-1, same code should work for both sites )

### Steps to Reproduce

1. Go to www4.fbox.to
2. Go to the Home page
3. Observe Discord Presence

### Screenshots

![Screenshot_5](https://user-images.githubusercontent.com/80055804/153749295-236d6825-9ff8-45ae-8827-74551defe30d.png)
![Screenshot_7](https://user-images.githubusercontent.com/80055804/153749299-673dd188-60ff-4648-9e9d-9790f5175d47.png)

### Expected Behavior

Presence should show that you are watching a movie, show or series, or just browsing.

### Actual Behavior

Presence doesn't show up on discord.

### Page URL

https://www4.fbox.to/home

### Operating System (OS)

Windows 10

### Browser

Chrome

### Browser Version

98.0.4758.82

**Comment by Isa27-0** [comment]
I checked and realized that actually this URL is not supported. Presence only supports with domain `https://www3.fbox.to/`
![image](https://user-images.githubusercontent.com/68751594/153751819-17914804-1577-4231-92e5-684fd11c3497.png)

**Comment by Zyxean** [comment]
> 

Hey, yes so.. I tried changing the code for the presence to www4, and also before that I tried to go through www3.fbox.to, but that just redirected me to www4..

**Comment by mike-ul** [comment]
I was also about to make a bug report about this issue but seems like you beat me to it :D the creator of this presence has updated the url but has yet to make a PR Request the updated metadata.json is here
https://github.com/vahya/Presences/commit/ed99dfd0cf79c5200835d13735c98768e4c9a83e
