### ISSUE TITLE
Plex.tv | https://app.plex.tv/

### ISSUE THREAD

**Issue by Dams678** [PreMiD/Presences#579]
**What's the name of the service?**
Ex. https://app.plex.tv/ | Plex

**What should the Presence display?**
Browsing catalogs , Current vidéos, movie / series + remaining time 

**Why do you want support for this service?**
I'd like to pester her by telling everyone what I'm watching on discord

**Are you able to provide an image for the service? (512x512 minimum)**
https://i.imgur.com/3fPHPNQ.png

**Comment by frozaum** [comment]
duplicate #18
