### ISSUE TITLE
Letterbox | letterboxd.com

### ISSUE THREAD

**Issue by elijaholmos** [PreMiD/Presences#5793]
### Description

Presence does not work at all due to a runtime error while attempting to retrieve the currently logged in user from `document.cookie`

### Steps to Reproduce

1. Go to https://letterboxd.com/
2. Observe Discord presence
3. Check console for error message similar to what is displayed in below screenshot

### Screenshots

![image](https://user-images.githubusercontent.com/35435704/153786686-404f7ed3-736f-4bdb-8827-ff0e46660654.png)

### Expected Behavior

Presence should function properly and display the status appropriate for the homepage

### Actual Behavior

Presence is not registered on Discord at all

### Page URL

https://letterboxd.com/

### Operating System (OS)

Windows 10

### Browser

Brave

### Browser Version

Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) (64-bit)

**Comment by Kaisarion** [comment]
Claiming this

**Comment by elijaholmos** [comment]
@Kaisarion I did indeed already create a PR and link it to the issue 😄

**Comment by Skaytacium** [comment]
Thanks for noticing this issue and making a PR, I've been really busy recently so didn't bother to check. The same issue is happening in my browser. I'm quite surprised as to how it was working before.

**Comment by elijaholmos** [comment]
No problem @Skaytacium! I thought it was just a bug on my end with how letterboxd was storing the cookie, since you had screenshots of it clearly working in the original PR. It was a really simple fix, don't worry about it at all
