### ISSUE TITLE
YouTube Music | music.youtube.com

### ISSUE THREAD

**Issue by GengGaming** [PreMiD/Presences#5808]
### Description

The rich presence doesn't display on discord

### Steps to Reproduce

It doesn't really appear to be working at all
![imagem_2022-02-15_144044](https://user-images.githubusercontent.com/52550135/154118344-17dead13-aa1f-426e-aff1-1356f073d8c5.png)
 
![imagem_2022-02-15_143857](https://user-images.githubusercontent.com/52550135/154118051-02200546-2e6e-4a56-a8be-490da226c5df.png)

### Screenshots

![imagem_2022-02-15_144213](https://user-images.githubusercontent.com/52550135/154118615-45f317d1-1e66-4cf3-bd89-5dc4de5a7c31.png)

### Expected Behavior

I expected that the rich presence would be showing on my Discord Account

### Actual Behavior

It doesn't appear to be working 

### Page URL

https://music.youtube.com/

### Operating System (OS)

Windows 10 Home 21H2

### Browser

Opera GX

### Browser Version

LVL3 (core: 83.0.4254.46)

**Comment by Slowlife01** [comment]
Your extension doesn't show your profile picture, it means that PreMiD app isn't connected to your Discord client.

Please open a ticket on our [Discord server](https://discord.premid.app) first.
