### ISSUE TITLE
Notion - Add page icon to presence display

### ISSUE THREAD

**Issue by elijaholmos** [PreMiD/Presences#5820]
### Presence name

Notion

### Description

Each page in Notion can include an icon, selected from a list of default emoji. Custom images can also be uploaded as icons for no additional charge. Example:
![image](https://user-images.githubusercontent.com/35435704/154310768-1e356c7f-00ef-4512-a0c7-7a806e1d8f36.png)

The `smallImageKey` should be set to this icon, if it exists. Pages without an icon can continue to use the default PreMiD edit/read icons.
![image](https://user-images.githubusercontent.com/35435704/154311419-c94c7341-4ee9-4fdf-b163-8b4a93b7ae13.png)
In this screenshot, the default PreMiD "read" icon would be replaced with the 📝emoji, since that is the icon that has been set for my Assignments page.

**Comment by Slowlife01** [comment]
Added in #5827 and please do note that if your page is private, it won't work.
