### ISSUE TITLE
crunchyroll doesn't show what you're watching

### ISSUE THREAD

**Issue by NightmoonxD** [PreMiD/Presences#584]
**Describe the bug**
crunchyroll doesn't show what you're watching

**To Reproduce**

**Expected behavior**
show what I'm watching in crunchyroll

**Screenshots**
https://imgur.com/a/dAEXB01

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version most recent

**Comment by TheDropX** [comment]
👮 - Currently investigating...

**Comment by TheDropX** [comment]
![Hmm](https://user-images.githubusercontent.com/35700745/68250267-3d47db80-0029-11ea-84ca-060d6b11c6c1.png)
It's working for me, is there any other layouts? (I don't use this xD)

**Comment by NightmoonxD** [comment]
![image](https://user-images.githubusercontent.com/25357402/68359193-de9e6280-00f9-11ea-9035-0c085537b133.png)
so it's just not work in pt-br version?

**Comment by NightmoonxD** [comment]
![image](https://user-images.githubusercontent.com/25357402/68550375-07b44100-03e1-11ea-99bb-8d38c6b58342.png)
just a update, Looks like it's working now, yayyy

**Comment by loverthehater** [comment]
I'm getting this exact problem again. Re-open?
Program: v2.1.4
Extension: v2.2.0
Browser: Chrome v87.0.4280.88
OS: Windows 10 v1909
