### ISSUE TITLE
feat(VLR.gg): add presence

### ISSUE THREAD

**Issue by MadsonMendes** [PreMiD/Presences#5840]
### Presence name

VLR.gg

### Description

**Describe the changes in this pull request:**

Adding VLR.gg presence

<details>
<summary>Proof showing the creation/modification is working as expected</summary>
<br>
![image](https://user-images.githubusercontent.com/50425778/154867156-ab45714e-3e21-4503-83aa-339cce563363.png)
<br>
![image](https://user-images.githubusercontent.com/50425778/154867205-42e62f4b-ee79-411a-9ab5-9585fd1a2cc3.png)
<br>
![image](https://user-images.githubusercontent.com/50425778/154867213-89fe4dc3-9264-4f47-bbc6-59752ec2ff34.png)
<br>
[image](https://user-images.githubusercontent.com/50425778/154867241-f6d68113-a0a9-4c66-8380-42c0551e394b.png)
<br>
[image](https://user-images.githubusercontent.com/50425778/154867250-f786a39b-7010-495e-a0f3-dc17a74883ed.png)
<br>
[image](https://user-images.githubusercontent.com/50425778/154867267-3647076d-bcc1-471c-9a6c-5bf80d507c27.png)
<br>
[image](https://user-images.githubusercontent.com/50425778/154867276-76f964dd-62b8-4e8a-8f7f-6af27e6c17d4.png)
<br>
[image](https://user-images.githubusercontent.com/50425778/154867301-1c1ef17d-835e-42de-aad8-338f00c02bfa.png)
<br>
[image](https://user-images.githubusercontent.com/50425778/154867379-b3c3d44c-b2b4-4518-93b8-e2c7ab545bd5.png)
<br>
[image](https://user-images.githubusercontent.com/50425778/154867450-476be885-05f0-4acd-b286-15f6fc5836d3.png)
<br>
[image](https://user-images.githubusercontent.com/50425778/154867460-936a790c-d899-4427-8816-47a42e1de0e9.png)
<br>
[image](https://user-images.githubusercontent.com/50425778/154867476-381b6ca8-c8aa-45ad-87df-997d71eea964.png)
</details>

**Comment by ImRodry** [comment]
My dude you made an issue with the title of a PR and images...?

**Comment by EncryptedDev** [comment]
I think you were suppose to open a pull request?
