### ISSUE TITLE
RedTube | www.redtube.com

### ISSUE THREAD

**Issue by g4merka** [PreMiD/Presences#5843]
### Description

Title on presence is wrong: he catching from recomendation video.

### Steps to Reproduce

1. Open any video on redtube.com;
2. Check title of this video:
3. Compare with title on presence;
4. Titile on presence is a suggest video on right side.

### Screenshots

![image](https://user-images.githubusercontent.com/40857098/154947890-996637fe-27df-43ba-984c-09c66f06428b.png)

### Expected Behavior

Right title of video

### Actual Behavior

Title of suggest video from recommendation

### Page URL

https://www.redtube.com/39252281

### Operating System (OS)

Windows 10 Home Single Language x64 (2009 build 19043)

### Browser

Brave 

### Browser Version

1.35.103 Chromium: 98.0.4758.102 official build x64

**Comment by tag27** [comment]
Issue should be closed because of NSFW content
