### ISSUE TITLE
Melody | itsmelody.pw

### ISSUE THREAD

**Issue by KeiranfromMelody** [PreMiD/Presences#5850]
### Website name

Melody

### Website URL

itsmelody.pw

### Website logo

https://itsmelody.pw/img/logo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Melody is a radio station

**Comment by KeiranfromSmash** [comment]
[melody premid.zip](https://github.com/PreMiD/Presences/files/8118335/melody.premid.zip)

**Comment by ImRodry** [comment]
> [melody premid.zip](https://github.com/PreMiD/Presences/files/8118335/melody.premid.zip)

now what the hell is this
