### ISSUE TITLE
Amazon Music | music.amazon.com

### ISSUE THREAD

**Issue by TooneyTurkey** [PreMiD/Presences#5856]
### Description

using the extention for amazon music all it does is show "browsing..."

### Steps to Reproduce

1. go to music.amazon.com
2. try to play something
3. look at disord

### Screenshots

![image](https://user-images.githubusercontent.com/66298544/155234484-47baa90a-8db8-4248-8e81-dfaed1e3bd15.png)

### Expected Behavior

show i was listening to "Nuestro Planeta [feat. Reykon] [Explicit]" by "kali uchis"

### Actual Behavior

just showed "browsing..."

### Page URL

music.amazon.com

### Operating System (OS)

endevour os (arch based distro)

### Browser

brave

### Browser Version

1.34.80

**Comment by Slowlife01** [comment]
# Cannot reproduce
#### Try upgrading your browser first.

![](https://user-images.githubusercontent.com/54318514/155253845-66903341-9960-4dc2-aee0-3f874e922db3.png)
# Environment
- **OS**: Windows 10
- **Browser**: Brave (1.35.103)
- **Version**:
   - **Extension**:  2.2.4.2
   - **App**: 2.2.1

**Comment by Slowlife01** [comment]
Inactive.
