### ISSUE TITLE
Anontpp | goplay.anontpp.com

### ISSUE THREAD

**Issue by xavxxrz** [PreMiD/Presences#5860]
### Presence name

Anontpp

### Description

Currently, the status shows for the top row: Watching Show
Bottom Row: Title + Episode

I think it would look more neater and nicer, if for the top row it shows the Title of the Show and the bottom row, it shows the Episode number instead.

### Additional context

![21312321](https://user-images.githubusercontent.com/89972668/155303137-39a4d656-a59f-445b-89eb-74d69d774c27.png)

**Comment by ndbiaw** [comment]
why?

**Comment by xavxxrz** [comment]
> why?

??? no i'm just saying if it is doable, then it simply looks more neater if the top row shows the title and bottom row shows the episode instead of chunking both status on the bottom row. as you can see, if the title is long, the episode is also hidden unless hovered.

**Comment by ndbiaw** [comment]
> > why?
> 
> ??? no i'm just saying if it is doable, then it simply looks more neater if the top row shows the title and bottom row shows the episode instead of chunking both status on the bottom row. as you can see, if the title is long, the episode is also hidden unless hovered.

Nope, the site includes "show" and "movie", changing it would break the general format
