### ISSUE TITLE
YouTube Music | music.youtube.com

### ISSUE THREAD

**Issue by Vlad-Games** [PreMiD/Presences#5870]
### Description

This bug affects the status when the music is being casted to a device
This bug was discovered while casting to a google nest hub from a Windows 11 computer on chrome 98(for more in depth versions check bellow)
This might be reproducabale on other casting devices other than google ones but since i do not own one i cannot say for sure

### Steps to Reproduce

1. Install the PreMiD extension and application
2. Install the Youtube Music presence
3. Buy a google speaker/display if you dont have one already
4. Go to music.youtube.com
5. Click the cast button and connect to your device
6. Play a music and the status will only show Youtube Music with no artist or song name(i have tried without casting and they show)

### Screenshots

![](https://cdn.e-z.host/e-zimagehosting/bceb5ef6-2705-4314-8f81-5600f8b530b2/42cf0638.png)
![](https://cdn.e-z.host/e-zimagehosting/bceb5ef6-2705-4314-8f81-5600f8b530b2/4cab2812.png)

### Expected Behavior

The status should show the song thats being played

### Actual Behavior

The status only shows Youtube Music without any song playing

### Page URL

https://music.youtube.com/

### Operating System (OS)

Windows 11 Pro Insider Preview Build 22538.rs_release.220114-1500

### Browser

Google Chrome

### Browser Version

98.0.4758.102 (Official Build) (64-bit) (cohort: Stable) Revision:273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}

**Comment by realtofuine** [comment]
it works for me on Win 11 Chrome 103.0.5060.66

**Comment by Vlad-Games** [comment]
I currently have switched to Mac from windows I can try it with a recent version of premid to see if the bug is still here on my old windows laptop
