### ISSUE TITLE
Sonic Retro | *sonicretro.org

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#5889]
### Website name

Sonic Retro

### Website URL

https://sonicretro.org (main page/news page), https://info.sonicretro.org (wiki page), https://forums.sonicretro.org (forum page)

### Website logo

![](https://sonicretro.org/wp-content/uploads/2019/07/247397_169599603104153_1428811_n.jpg)

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Well, on the main page it could show the news title and the time you have been on the page. On the wiki page it would look like sites like Wikipedia and Fandom, and on the forum page it could show the post and the author's name.

**Comment by BigBoi-TM** [comment]
@Isa27-0 I got u

**Comment by BigBoi-TM** [comment]
Almost done, needs debugging and some final touches

**Comment by BigBoi-TM** [comment]
@Isa27-0 Looks good and ready to go. If u wanna check out some screenshots feel free to dm my discord. Can't submit it yet cuz I got another presence being reviewed.

BigBoi©#7934
