### ISSUE TITLE
Quran | quran.com

### ISSUE THREAD

**Issue by ahmetdinc19822** [PreMiD/Presences#5891]
### Website name

Quran.com

### Website URL

https://quran.com/

### Website logo

you can find it on the website somewhere sorry

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

the quran is said to the be the final revelation from God and the last to come of the abrahamic religions and is the holy book of the muslims

**Comment by BigBoi-TM** [comment]
@ahmetdinc19822 I got u brother

**Comment by ahmetdinc19822** [comment]
you made it akhi ?

**Comment by ahmetdinc19822** [comment]
yes sure send it thru أحمد بن آدم#0906
