### ISSUE TITLE
Trakt | trakt.tv

### ISSUE THREAD

**Issue by Fasolovic** [PreMiD/Presences#5895]
### Website name

Trakt

### Website URL

https://trakt.tv/

### Website logo

https://trakt.tv/assets/logos/white-bg@2x-626e9680c03d0542b3e26c3305f58050d2178e5d4222fac7831d83cf37fef42b.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Trakt is a service that you can link almost most streaming websites to it, like Netflix and Stremio, etc. in order to auto-track your movies and shows. Also, if you were watching a movie from your tablet or TV and it will show to discord because we linked the APIs. But the PC that does have premid must be on

I hope it does have a dynamic cover, Timestamps, movie, and show details, buttons for the movie page, and the profile page

Thanks

**Comment by xKubsoneQ** [comment]
#6270
