### ISSUE TITLE
Reddit | Privacy Mode

### ISSUE THREAD

**Issue by SeanTheMan34** [PreMiD/Presences#5901]
### Presence name

Reddit

### Description

Please add a privacy setting that allows us to show the subreddit we are in, but not the post we are looking at. Especially for moderators, having an option to disable showing moderation stuff would be great.

**Comment by awooooool** [comment]
I'm interested in making this one. Not sure about the moderation stuff though, since I've never been a moderator in Reddit. Can you maybe elaborate more about this?

**Comment by SeanTheMan34** [comment]
Basically it shows when we are in modqueue or in mod tools. I'd rather it not show that since I moderate a pretty big subreddit and I don't want people knowing when I am in moderator tools.

**Comment by awooooool** [comment]
> Basically it shows when we are in modqueue or in mod tools. I'd rather it not show that since I moderate a pretty big subreddit and I don't want people knowing when I am in moderator tools.

When you in the mod tools, does the address bar in your browser has the subreddit name? Like `/r/AskReddit` for example, or is it something else?

**Comment by awooooool** [comment]
I forgot to claim this. Please assign this to me. I'm almost done.

**Comment by SeanTheMan34** [comment]
When in moderation queue it says:

Browsing....
r/AskReddit: moderation queue

**Comment by Isa27-0** [comment]
Can this Issue be closed? (#6442)

**Comment by RisingSunLight42** [comment]
Poke @EncryptedDev
