### ISSUE TITLE
lightnovelpub | www.lightnovelpub.com/web

### ISSUE THREAD

**Issue by degu-Tanya** [PreMiD/Presences#5916]
### Website name

LIGHT NOVEL PUB

### Website URL

https://www.lightnovelpub.com/web

### Website logo

https://static.lightnovelpub.com/content/img/lightnovelpub/logo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Reading "novel name", chapter you are on and max count "ch142/2000" and button that you can click that sends you to the novel on the site.

reading:
Novel name,
chapter 123/1230,
button to novel on site.

**Comment by yrnmsk** [comment]
i can do a really simple, really quick one for this. just give me an hour or a few more. worse would be a day, depends on how busy i could be due to univ stuffs
