### ISSUE TITLE
Spotify Podcasts | open.spotify.com

### ISSUE THREAD

**Issue by LaFontaine1** [PreMiD/Presences#5918]
### Description

The presence doesn't show

### Steps to Reproduce

1. Open https://open.spotify.com on the browser (any kind, I tried Brave, Edge, Chrome)
2. The presence doesn't show on Discord

### Expected Behavior

The presence show on Discord

### Actual Behavior

The presence doesn't show on Discord

### Page URL

https://open.spotify.com/

### Operating System (OS)

Windows 11

### Browser

Chrome, Edge, Brave

### Browser Version

Microsoft Edge Version 99.0.1150.36

**Comment by Slowlife01** [comment]
# Cannot reproduce
![](https://user-images.githubusercontent.com/54318514/158986828-186f41c0-f137-4fe0-8b1d-e6afd9c771a7.png)
# Environment
- **OS**: Windows 10
- **Browser**: Edge (101.0.1196.0, canary)
- **Version**:
   - **Extension**:  2.2.4.2
   - **App**: 2.2.0

**Comment by EncryptedDev** [comment]
I cannot reproduce this either - most likely invalid.
