### ISSUE TITLE
Spotify Podcast | https://open.spotify.com/

### ISSUE THREAD

**Issue by LaFontaine1** [PreMiD/Presences#5919]
### Description

The presence doesn't show

### Steps to Reproduce

1. Open https://open.spotify.com on the browser (any kind, I tried Brave, Edge, Chrome)
2. The presence doesn't show on Discord

### Expected Behavior

The presence show on Discord

### Actual Behavior

The presence doesn't show on Discord

### Page URL

https://open.spotify.com/

### Operating System (OS)

Windows 11

### Browser

Chrome, Edge, Brave

### Browser Version

Microsoft Edge Version 99.0.1150.36; Chrome is up to date Version 99.0.4844.51 (Official Build) (32-bit); Brave is up to date Version 1.36.111 Chromium: 99.0.4844.51

**Comment by EncryptedDev** [comment]
I'm going to close this issue as the template hasn't been filled in with sufficient detail to reproduce said issue.
