### ISSUE TITLE
TwitCasting | twitcasting.tv

### ISSUE THREAD

**Issue by riinka334** [PreMiD/Presences#5922]
### Website name

TwitCasting

### Website URL

twitcasting.tv

### Website logo

![](https://play-lh.googleusercontent.com/0bdy8wTBnp3l1lneU1HZwxE4qHqjfag8HDCWP8ckXisuHQYV3O-q17EIRZXH-fGRECk)

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

this is live streaming web service like twitch, youtube, etc. (originally japanese live stream web, i guess(?), idk. most of the streamer are japanese people)
presence like twitch, youtube (that already added in premid store) would be nice.
Thanks you.

**Comment by kyrie25** [comment]
I'll claim this
