### ISSUE TITLE
Cuevana 3 | cuevana3.plus

### ISSUE THREAD

**Issue by ESGT12** [PreMiD/Presences#5942]
### Description
The service's domain is now changed to `cuevana3.plus`

### Steps to Reproduce

1. Add the Presence from our store.
2. Go to the new domain.
3. Observe your Discord profile.

### Expected Behavior
The Presence show on my profile.

### Actual Behavior
The Presence is not showing on my profile.

### Page URL
https://cuevana3.plus/

### Operating System (OS)
Windows 10

### Browser
Chrome

### Browser Version
Chrome

**Comment by EncryptedDev** [comment]
Hi @ESGT12! 

Thank you for submitting the bug report. If there has been no further changes apart from the domain change, this should be dealt with fairly soon.

**Comment by magumboi** [comment]
done.
