### ISSUE TITLE
Apple TV+ | tv.apple.com

### ISSUE THREAD

**Issue by lukesgithubs** [PreMiD/Presences#595]
**What's the name of the service?**
tv.apple.com | Apple TV+

**What should the Presence display?**
Basically Netflix:
The Show
The Season & Episode
How much time left

**Why do you want support for this service?**
It's a new service from Apple and so far has great shows just exclusive to them.

![apple tv+](https://user-images.githubusercontent.com/57507946/68434985-ad24a600-0190-11ea-8448-9d6723611bc6.png)

**Comment by SlowLife1661** [comment]
I will make this
