### ISSUE TITLE
Jellyfin | jellyfin.org

### ISSUE THREAD

**Issue by Dirky14** [PreMiD/Presences#5956]
### Description

Presence doesn't work with my jellyfin service, but works with jellyfin.org.

### Steps to Reproduce

1. Connect to your jellyfin instance
2. Check the status

### Expected Behavior

Show the films I'm watching on the status

### Actual Behavior

Doensn't show anything on the instance

### Page URL

https://jellyfin.dirky.fr

### Operating System (OS)

Linux

### Browser

Firefox

### Browser Version

98.0

**Comment by alexbcberio** [comment]
I understand that nothing is being displayed, correct me if I'm wrong. What version of Jellyfin are you running?
I am running current latest version 10.7.7 (<https://media.alexbcberio.eus>) and its being correctly displayed, when I go to your instance (login page) it does also work.

Could you check on the browser console if PreMiD logs a message? It should say "Jellyfin web client detected" (see image below), if this message shows up the presence should be set on your Discord profile.

![image](https://user-images.githubusercontent.com/22194879/159142134-a54c95d4-5825-4d17-a247-0c16a8ce6f29.png)

**Comment by Dirky14** [comment]
Well, it seems like I don't have the message on the console, but the extension is connected to the software, I don't really understand why it doesn't work... I'm also running the version 10.7.7 !

**Comment by alexbcberio** [comment]
Does the console report any errors? If no, try doing this:

- Check if other extensions, there could be one interfearing with PreMiD,
- Open the developer tools and force reload the page ignoring the cache `ctrl`+ `F5`,
- Remove Jellyfin presence and add it back from the store,
- Close all browser windows and open only one tab with your Jellyfin web client,
- Restart the pc (you might have done this in the past days)

**Comment by RisingSunLight42** [comment]
Does this issue has been resolved ?

**Comment by zeroquinc** [comment]
This is still an issue. Doesn't work for me either

**Comment by alexbcberio** [comment]
I also log in automatically checking the remember me.
The presence works ok no matter what url you type, you don't need to be redirected from the login page. Some times the presence is not correctly injected/started and it mught cause this type of issues.
I'm not sure if its PreMiD related or its a deep chromium bug as it also happens with Tampermonkey scripts

I understand by the edit that you managed to solve the issue, else we can continue checking it.

**Comment by zeroquinc** [comment]
> I also log in automatically checking the remember me.
> The presence works ok no matter what url you type, you don't need to be redirected from the login page. Some times the presence is not correctly injected/started and it mught cause this type of issues.
> I'm not sure if its PreMiD related or its a deep chromium bug as it also happens with Tampermonkey scripts
> 
> I understand by the edit that you managed to solve the issue, else we can continue checking it.

Somehow for me it only works if I get redirected to the login page. I somehow got a workaround now so that my cookies for the Jellyfin domain get deleted whenever I close my browser.

The plug-in does not work for me if I don't clear my cookies and I get automatically logged in.

Any ideas?

**Comment by alexbcberio** [comment]
How have you deployed Jellyfin, on a (sub)domain or in a subpath (/jellyfin)?

Could you check if the issue replicates on other browser?

**Comment by StayBlueee** [comment]
Same issue for me, but closing the page and reopening it a couple of times fixes it for me. This issue is persistent on a domain and connecting to it directly via an IP.

**Comment by alexbcberio** [comment]
There are some cases where PreMiD does not correctly inject the presence on the first try. If the presence works after reloading the page is most probably this.

**Comment by alexbcberio** [comment]
Closing the issue due-to inactivity
