### ISSUE TITLE
YouTube Music | music.youtube.com

### ISSUE THREAD

**Issue by samurusov** [PreMiD/Presences#5979]
### Description

Premid stopped working itself. No interrupt, no change, no nothing. I was listening YouTube Music while I was coding background. It stopped after 2-3 hours. Just that.

I've just installed it. It was fresh installation. Besides, I've reinstalled extension, program, restarted pc. Nothing worked. It's still not working.

### Steps to Reproduce

1) Installed
2) It worked for 2-3 hours
3) Stopped itself
4) Reinstalled and restarted everything
5) Same

### Screenshots

<img width="839" alt="image" src="https://user-images.githubusercontent.com/14890643/160250258-07e3383a-ab40-4622-805c-0b645bdfbdd5.png">

### Expected Behavior

I expected it works

### Actual Behavior

Stopped after a while

### Page URL

https://music.youtube.com

### Operating System (OS)

Windows 11, Latest Updates.

### Browser

Edge

### Browser Version

Latest version by (26/03/2022 - 20:15)

**Comment by EncryptedDev** [comment]
Have you checked the console of the website for any errors?

**Comment by Slowlife01** [comment]
See #6115
