### ISSUE TITLE
Add 4anime presence

### ISSUE THREAD

**Issue by Chorizzy** [PreMiD/Presences#6002]
### Website name

4anime

### Website URL

https://4anime.gg/

### Website logo

https://4anime.biz/public/theme_4anime/images/logo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

I would really love that this site is back on premid because the server is back up and running

**Comment by EncryptedDev** [comment]
Looks like it was removed in #4309. Someone could look into rectifying the code if the website has a similar structure

**Comment by EncryptedDev** [comment]
https://www.reddit.com/r/4anime/comments/oj11j2/website_permanent_shutdown/
