### ISSUE TITLE
Webnovel | webnovel.com

### ISSUE THREAD

**Issue by degu-Tanya** [PreMiD/Presences#6006]
### Website name

Webnovel

### Website URL

https://www.webnovel.com/

### Website logo

https://files.catbox.moe/vcjhjo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Its a both free and paid service (free up to ch40~ varies per novel, but after that its paid. I think mobile app makes so you get more free chapters)

show what novel you are reading from the site, novel name, chapter count /name, cover image

playing game: Webnovel
Picture of novel cover from site
Novel name
chapter 123 "wandering coder"
button to novel on site
button to chapter on site

like this presence https://github.com/PreMiD/Presences/issues/5916

website logo: 
1. https://files.catbox.moe/vcjhjo.png
![bilde](https://user-images.githubusercontent.com/100243423/160991862-834d3c6a-fdbe-4d11-a065-75bed816d74d.png)

2. https://pbs.twimg.com/profile_images/1027939938250051585/QgahemWQ_400x400.jpg
![bilde](https://user-images.githubusercontent.com/100243423/160991249-10a0413e-2d7b-43d0-b7d0-5640d834fb6f.png)
![bilde](https://user-images.githubusercontent.com/100243423/160991558-4b26b055-971b-4227-94c7-77871992eb3c.png)

**Comment by Isa27-0** [comment]
> ### Prerequisites
> 
> - [X] It is a paid service

No need to be selected, because even if the site has a subscription, it is not 100% paid (Ex: Netflix)

**Comment by kyrie25** [comment]
I'll claim this
