### ISSUE TITLE
Anontpp | goplay.anontpp.com / goplay.ml

### ISSUE THREAD

**Issue by xavxxrz** [PreMiD/Presences#6015]
### Description

The site has changed its domain so it's no longer working for Premid! The old domain was goplay.anontpp.com and now it has changed to goplay.ml, please kindly change the domain so that it will work again.

### Steps to Reproduce

1. Go to goplay.ml

### Expected Behavior

Premid to work with site

### Actual Behavior

Not working anymore as domain changed

### Page URL

goplay.ml

### Operating System (OS)

Windows 10

### Browser

Chrome

### Browser Version

-

**Comment by EncryptedDev** [comment]
Hi! It looks like it is a completely new service

**Comment by DarkVillager** [comment]
@xavxxrz It seems to be white for me? Is this region locked?
![Screenshot_24](https://user-images.githubusercontent.com/42322979/161386062-c1a80601-767e-40e8-bc95-37de40769e31.jpg)
![Screenshot_23](https://user-images.githubusercontent.com/42322979/161386063-1094846b-6f39-4b9b-bbbb-0af508dfb258.jpg)

**Comment by xavxxrz** [comment]
> @xavxxrz It seems to be white for me? Is this region locked?
> 
> I tested without an adblocker on chrome & firefox. ![Screenshot_24](https://user-images.githubusercontent.com/42322979/161386062-c1a80601-767e-40e8-bc95-37de40769e31.jpg) ![Screenshot_23](https://user-images.githubusercontent.com/42322979/161386063-1094846b-6f39-4b9b-bbbb-0af508dfb258.jpg)

ah this site is using some token thingy, so please use this site to get in
https://www.reddit.com/r/koreanvariety/comments/723mtd/i_created_this_website_that_streams_korean_shows/
click on [Visit the site using an automatically generated Access Token.]
