### ISSUE TITLE
AniList | anilist.co

### ISSUE THREAD

**Issue by degu-Tanya** [PreMiD/Presences#6028]
### Presence name

AniList

### Description

buttons for the request that takes you to the site.

if you are on a anime/manga page - button show up so you can click it and get sent to the site.
(not needed just a suggestion; add cover from anime/manga as image maybe? like image below from animepahe)

on profile on a user, if I where on this profile https://anilist.co/user/Edo/ a button would come under playing saying "visit profile"(or "visit username")

(not needed just a suggestion; if it is possible maybe show image the user got as profile pic and anilist logo becomes the little logo bottom right)
![bilde](https://user-images.githubusercontent.com/100243423/161467233-12bdf9bb-27bf-4230-b785-6a798dc8a933.png)

### Additional context

![bilde](https://user-images.githubusercontent.com/100243423/161466967-051e80ac-5032-4ae8-b53f-721c4a095820.png)
like this just on anilist, button to "view anime/manga" when you got one up, and "visit profile" button if you are on a profile.

**Comment by RisingSunLight42** [comment]
I'm working on it
