### ISSUE TITLE
Crunchyroll   |  https://www.crunchyroll.com/

### ISSUE THREAD

**Issue by itzelmer** [PreMiD/Presences#603]
Name of the service: Crunchyroll  | https://www.crunchyroll.com/

What should the Presence display? : Informations about the show you're watching

The Problem :  It keeps saying ''Browsing..''. while you start watching the series.
 
I had to bring this up, because i think some people might find this annoying too.

Image:  https://i.gyazo.com/c46bdf8f21961e8aacf77e41a631e762.png

**Comment by eggsywashere** [comment]
Same with #584, developers already started working on it.

**Comment by frozaum** [comment]
duplicate #584
