### ISSUE TITLE
Free Web Novel | freewebnovel.com

### ISSUE THREAD

**Issue by degu-Tanya** [PreMiD/Presences#6035]
### Website name

Free Web Novel

### Website URL

https://freewebnovel.com/

### Website logo

https://files.catbox.moe/acvgh1.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Adding [Free Web Novel](https://freewebnovel.com/) as a pressence where when you are on the site it shows cover, browsing and button to it

When you are on a novel it shows cover of it on the pressence and button for it to the site
When you are on a chapter it shows cover for novel and buttons for it to the chapter and novel on site

Playing game: Free Web Novel
Logo to site when browsing 
Browsing Novel's 
00:01:53 elapsed
Button 1: Visit Site (link to site)

Playing game: Free Web Novel
Cover to novel you are on
Novel Title
00:11:48 elapsed
Button 1: Novel Title (links to novel)

Playing game: Free Web Novel
Cover to novel you are on
Novel Title
Chapter 123: wandering coder
00:03:13 elapsed
Button 1: Novel Title (links to novel)
Button 2: Chapter 123: Wandering Coder (links to chapter)

Alternative logo 400x400: (quick mockup of their site logo so it would fit better with discord cover for pressence)
with background  https://de.catbox.moe/5spncb.png
![bilde](https://user-images.githubusercontent.com/100243423/161909532-48ae8cd6-7c29-465f-ac2b-14b95e4333ab.png)

transparent background https://de.catbox.moe/nrx1xs.png
![bilde](https://user-images.githubusercontent.com/100243423/161909557-a9a3f228-f384-499c-99cc-a829a0f615b3.png)

**Comment by BigBoi-TM** [comment]
@degu-Tanya got a thumbnail?

**Comment by BigBoi-TM** [comment]
@degu-Tanya On it. The site is setup in such an annoying way tho.
