### ISSUE TITLE
Presence suggestion; NDTV

### ISSUE THREAD

**Issue by lolisfun** [PreMiD/Presences#6046]
### Website name

NDTV

### Website URL

https://www.ndtv.com/

### Website logo

https://cdn.ndtv.com/common/images/ogndtv.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

India's most credible source of news.

**Comment by EncryptedDev** [comment]
The template has not been filled in properly, you should read the information before submitting
