### ISSUE TITLE
niconico | https://premid.app/store/presences/niconico

### ISSUE THREAD

**Issue by Aidesu** [PreMiD/Presences#6049]
### Description

The rich presence of niconicodouga it doesn't work 

### Steps to Reproduce

1. add niconico rpc to PreMid from the PreMid store https://premid.app/store/presences/niconico
2. go on this link (you can also click on a video to witness it) https://www.nicovideo.jp/
3. and you can you can see that it doesn't work 

### Expected Behavior

it works again

### Actual Behavior

It doesn't work

### Page URL

https://nico.ms/sm38346249

### Operating System (OS)

Windows 10

### Browser

Opera and Chrome

### Browser Version

バージョン: 1.37.111 Chromium: 100.0.4896.79（Official Build） （64 ビット）

**Comment by EncryptedDev** [comment]
Poorly answered; fill in the template with accurately next time

**Comment by Aidesu** [comment]
What, I've filled everything can you tell me what is poorly ?
