### ISSUE TITLE
Animes Vision | animes.vision

### ISSUE THREAD

**Issue by GonFreecssPro** [PreMiD/Presences#6051]
### Description

The site underwent a frontend update and since then it doesn't display anything about the current episode you are watching or the site's home page.

### Steps to Reproduce

update the animes vision presences
go to an episode on animes.vision
and press play 

### Expected Behavior

should display website homepage, episode name, time left, anime list and more.

### Actual Behavior

The website has been updated and the presence functions no longer work.

### Page URL

animes.vision

### Operating System (OS)

Windows 11

### Browser

Opera GX

### Browser Version

LVL3 (core: 85.0.4341.65)

**Comment by RisingSunLight42** [comment]
Looks like it's area restricted

**Comment by RisingSunLight42** [comment]
> Looks like it's area restricted

Since I've now a VPN, I'll work on a patch in few days.
