### ISSUE TITLE
TopFlix | https://topflix.tv

### ISSUE THREAD

**Issue by yuukiee** [PreMiD/Presences#606]
**What's the name of the service?**
https://topflix.tv | TopFlix

**What should the Presence display?**
> Browsing
> Video Title
> Time left for video to finish

**Why do you want support for this service?**
TopFlix is ​​a brazilian movie and series site, as [vizer](https://github.com/PreMiD/Presences/issues/503) is not working indefinitely (and may not return) this site is a good option for watching movies and series online.

**Are you able to provide an image for the service? (512x512 minimum)**
![topflix](https://user-images.githubusercontent.com/42496876/68534528-34e6ed80-0314-11ea-83cd-b2dabe438058.png)

**Comment by Bas950** [comment]
If I open console it redirects me to Facebook?! Anyone else having this issue? @frozaum @yuukiee @Viruzaum you guys are from brazil so asking you.

Doesnt redirect on main page but it does on every other...

**Comment by Bas950** [comment]
For information about the status of this suggestion see #1129

**Comment by Viruzaum** [comment]
Yes, it does. There was an anime website that did the same thing and gave up on doing the presence because of it.

**Comment by Bas950** [comment]
I was able to bypass it on firefox somehow :/
