### ISSUE TITLE
Cda | www.cda.pl

### ISSUE THREAD

**Issue by hikusia** [PreMiD/Presences#6061]
### Description

The premid on this page is not working, it is not communicating to discord as if it were not detecting cda

### Steps to Reproduce

1. Go to the link
2. Click something
3. Discord's activity isnt showing that 

### Expected Behavior

Discord doesnt showing the activity from this page

### Actual Behavior

Discord doesnt showing the activity from this page

### Page URL

https://www.cda.pl

### Operating System (OS)

windows 11

### Browser

opera

### Browser Version

LVL3 (core: 85.0.4341.65)

**Comment by xKubsoneQ** [comment]
#6326
