### ISSUE TITLE
shinden | shinden.pl

### ISSUE THREAD

**Issue by hikusia** [PreMiD/Presences#6063]
### Description

Premid is not working properly, it does not detect when someone is watching something

### Steps to Reproduce

1. Go to the any anime series in shinden, for example https://shinden.pl/series/56293-date-a-live-iv
2. You check the activity on discord and it is either what in the first screenshot, or 'browsing' (2nd screen) where it worked normally before, such as anime name, watch time

### Screenshots

https://imgur.com/a/vqtNfHs 
https://imgur.com/a/yBd9yvv

### Expected Behavior

something broken

### Actual Behavior

 When it is on a page with a specific anime, premid does not detect it, it only works on the home page and on users' profiles, even if they click on a series, browsing (just like on the main page) or "shinden" is displayed. There used to be an anime name, episode, watch time etc.

### Page URL

https://shinden.pl/series/56293-date-a-live-iv for example, but it doesnt work on every anime series

### Operating System (OS)

windows 10

### Browser

Opera

### Browser Version

LVL3 (core: 85.0.4341.65)

**Comment by xKubsoneQ** [comment]
too many ads on this page...

**Comment by xKubsoneQ** [comment]
everything good using cda player, gdrive player, dailymotion player, vk player, and sibnet player
streamtape has too many ads, so i cant checked it (this page doesnt work with brave adblock)

image: cda player
![image](https://user-images.githubusercontent.com/63014799/177000601-d75bfaac-8f8b-4b67-affa-60162db6149e.png)

**Comment by xKubsoneQ** [comment]
"viewing serie" works too
![image](https://user-images.githubusercontent.com/63014799/177000683-6c64665f-81ac-46a9-a11f-651cf3800a2f.png)

**Comment by RisingSunLight42** [comment]
Everything works fine for me too.
