### ISSUE TITLE
Showtime | www.showtime.com

### ISSUE THREAD

**Issue by pyramidstv** [PreMiD/Presences#6064]
### Description

My Showtime presence only shows "Browsing..." whenever I'm watching something. It never shows the title of the show.

### Steps to Reproduce

1. Go to Showtime
2. Watch anything
3. Status doesn't update with show title/episode

### Screenshots

![image](https://user-images.githubusercontent.com/89791393/162806740-49c987db-4e3d-4fb3-ba79-ff6511f9f3f8.png)

### Expected Behavior

Show correct title and episode name

### Actual Behavior

Shows "Browsing..."

### Page URL

https://www.showtime.com/play/3507226

### Operating System (OS)

Windows 10

### Browser

Chrome

### Browser Version

Version 100.0.4896.75 (Official Build) (64-bit)

**Comment by DarkVillager** [comment]
Can reproduce.

**Comment by 0xYami** [comment]
@theusaf Presence should be deleted as app will be deleted "4/30/2024"
![image](https://github.com/PreMiD/Presences/assets/93791569/6d7aa72e-547d-47e4-a5a3-caadaae9affa)
