### ISSUE TITLE
Pokémon TV | watch.pokemon.com

### ISSUE THREAD

**Issue by Heartran** [PreMiD/Presences#608]
**What's the name of the service?**
https://www.pokemon.com/us/pokemon-episodes/ | Pokémon TV
https://www.pokemon.com/it/episodi-tv/
_Every localised version has it's own site_

**What should the Presence display?**
Information about the current episode & the Pokemon serie which it comes from

**Why do you want support for this service?**
Is the streaming service of the biggest franchise of all time.

**Are you able to provide an image for the service? (512x512 minimum)**
https://images-eu.ssl-images-amazon.com/images/I/51Ph66gHVVL.png

**Comment by Bas950** [comment]
> Every localised version has it's own site

oh god..

**Comment by Bas950** [comment]
For information about the status of this suggestion see #1129
