### ISSUE TITLE
agar ar | agar-ar.com

### ISSUE THREAD

**Issue by M4m71** [PreMiD/Presences#6080]
### Website name

Agar ar

### Website URL

https://agar-ar.com/

### Website logo

https://cdn.discordapp.com/icons/620322807238230047/effc951c5853ff34e100683f23f5c37a.webp?size=96

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Hi ,

it's a game like Agar.io but it's for An Arabic devlopr so i want it to show what server i'am in and what's my name in the game, Like you know make it like agar.io presence and something like that.. it's gonna be easy i think, 

Thank you!

**Comment by EncryptedDev** [comment]
Duplicate of #5423
