### ISSUE TITLE
Anicloud | anicloud.io

### ISSUE THREAD

**Issue by sneazy-ibo** [PreMiD/Presences#6089]
### Description

Anicloud.io changed their domain to Aniworld.to

### Steps to Reproduce

1. go to anicloud.io
2. it automatically changes to aniworld.to
3. the presence doesn't work

### Expected Behavior

Expected the Presence to show up on my dc profile

### Actual Behavior

it didn't show up

### Page URL

Aniworld.to

### Operating System (OS)

Windows 11

### Browser

Chrome

### Browser Version

100.0.4896.127

**Comment by RisingSunLight42** [comment]
Duplicated of #6146 (well, it was the first, but...)
Done in PR #6203 
@EncryptedDev could you close this issue ?

**Comment by sneazy-ibo** [comment]
> Duplicated of #6146 (well, it was the first, but...)
> Done in PR #6203 
> @EncryptedDev could you close this issue ?

ight
