### ISSUE TITLE
Youtube Music | music.youtube.com

### ISSUE THREAD

**Issue by DaniDani2006** [PreMiD/Presences#6093]
### Description

The problem is that I have to play the song from YouTube music with video, because when I play it audio only, it shows "Playing YouTube music" without showing info for the song

### Steps to Reproduce

I tried reinstalling, but doesn't work

### Screenshots

![image](https://user-images.githubusercontent.com/54793044/163727936-be9acdf0-7279-4a69-a47d-191cbb1b52fd.png)

### Expected Behavior

Showing the song name

### Actual Behavior

Showing "Playing Youtube Music"

### Page URL

https://music.youtube.com/

### Operating System (OS)

Windows 11

### Browser

Chrome

### Browser Version

100.0.4896.88

**Comment by Slowlife01** [comment]
Can you provide an example link?
