### ISSUE TITLE
shinden I shinden.pl

### ISSUE THREAD

**Issue by hikusia** [PreMiD/Presences#611]
What's the name of the service?
Shinden
https://shinden.pl/

What should the Presence display?
anime, episode and time remaining

Why do you want support for this service?
Shinden is a polish website with animes, and i can watching there. Some polish people want to do this too.

Are you able to provide an image for the service? (512x512 minimum)
![image](https://user-images.githubusercontent.com/57454113/68550855-3e9d4d80-0407-11ea-9b30-789313d50d72.png)

**Comment by hikusia** [comment]
or u can use it 
![image](https://user-images.githubusercontent.com/57454113/68550889-80c68f00-0407-11ea-93a8-2afc94e09009.png)

**Comment by Bas950** [comment]
@hikusia Please contact me on discord (Bas950#0950) if you can translate some strings to polish for me

**Comment by Bas950** [comment]
Need some help with supporting the website in general @hikusia
