### ISSUE TITLE
Discohook

### ISSUE THREAD

**Issue by IceyWolf17** [PreMiD/Presences#6117]
### Website name

Discohook

### Website URL

https://discohook.org/

### Website logo

https://avatars.githubusercontent.com/u/65213683?s=200&v=4

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

It's a website that is manipulated to make handy discord embeds.

**Comment by NinjaLabs-Dev** [comment]
Added in #6955

**Comment by Kuriel23** [comment]
@Bas950 close this issue please
