### ISSUE TITLE
SpankBang | spankbang.com

### ISSUE THREAD

**Issue by CECHEC** [PreMiD/Presences#6128]
### Website name

SpankBang

### Website URL

https://spankbang.com/

### Website logo

https://1000logos.net/spankbang-logo/

### Prerequisites

- [ ] It is a paid service
- [X] It displays NSFW content
- [ ] It is region restricted

### Description

I would like to be able to see the basic stuff, like on other presences, such as video name, video length and the logo next to all of that.

**Comment by theusaf** [comment]
Due to certain changes, services like these will be removed/disallowed soon.
