### ISSUE TITLE
Playerbros. 

### ISSUE THREAD

**Issue by alfredsaveron** [PreMiD/Presences#621]
**Service Name:**
-  https://playerbros.com/ | Playerbros

**What should the Presence display?**
Informations about the current page

**Why do you want support for this service?**
To see what news I read and what I did. 

**Are you able to provide an image for the service? (512x512 minimum)**

https://images.app.goo.gl/yaq5QXkbbtAxUUoK7

**Comment by eggsywashere** [comment]
>todo
