### ISSUE TITLE
Spotify Podcasts | open.spotify.com

### ISSUE THREAD

**Issue by Johii-OOF** [PreMiD/Presences#6217]
### Description

Spotify Podcast presence not showing on discord.

### Steps to Reproduce

Open https://open.spotify.com/
The presence is not showing on discord while you play a podcast.

### Screenshots

Presence not showing

### Expected Behavior

The presence to work properly

### Actual Behavior

showing nothing

### Page URL

https://open.spotify.com/

### Operating System (OS)

Windows 10

### Browser

Brave

### Browser Version

Brave Version 1.38.117  Chromium: 101.0.4951.67 (Official Build)  (64-bit)

**Comment by Dedsec1818** [comment]
same issue

**Comment by Slowlife01** [comment]
This is the Extension's issue. Try this:
![image](https://user-images.githubusercontent.com/54318514/171202028-4c29d1a9-7050-4feb-b547-4891c8276a24.png)
