### ISSUE TITLE
YouTube Music | Option to remove status when paused

### ISSUE THREAD

**Issue by ghost** [PreMiD/Presences#6226]
### Presence name

YouTube Music

### Description

Currently, when you pause music on YouTube Music, the Discord status removes timestamps and shows that it is paused. For people like me who keep the tab open with the music paused for many hours at once, the status becomes a little pointless on Discord. They don't open my new status when I'm actually doing something else, because they'll assume the status is still about the paused song (especially when we use the status line feature in Discord).

### Alternatives

It'll be good if we have a setting such that the status will be removed as long as the music is paused.

**Comment by renaldoaluska** [comment]
I upvote this. Same case.

**Comment by Slowlife01** [comment]
This is not possible on the Extension version 2.2.3

**Comment by amsyarasyiq** [comment]
I think this issue can be closed now.

**Comment by Balu-SomeNumbers** [comment]
@amsyarasyiq No, I think the issue should be open until a solution is achieved, even if it is not possible in the current version of the software.

**Comment by amsyarasyiq** [comment]
@Balu-SomeNumbers I assumed #6518 fixed this issue, guess it really does not then.

**Comment by joerkig** [comment]
@theusaf feel like this should be resolved now?
