### ISSUE TITLE
WoX Area | https://woxhub.com/

### ISSUE THREAD

**Issue by MorenaPluton** [PreMiD/Presences#623]
**What's the name of the service?**
WoXArea (Multiplayer Game Hacks and Cheats Platform)

**What should the Presence display?**
Subject, author, subject area (eg https://prnt.sc/pw093v)

**Why do you want support for this service?**
Because we did this project in an application made to our forum, but normally there is no add-on that we can use while browsing our forum. We wanted to get your help because we know that you are the best team in this business.

**Are you able to provide an image for the service? (512x512 minimum)**
https://cdn.discordapp.com/attachments/640525557427339276/640525684116029442/5.png

Note: My forum is a forum for game tricks. We have cheated as into most multiplayer games.So I wanted to warn you from the start. Apart from that, when you see what you do to +18 content sites, I said why not and I came to you. I hope you don't spare your support. And sorry for my bad english. I used translate.

**Comment by doomlerd** [comment]
@eggsywashere ^

**Comment by eggsywashere** [comment]
>> todo :^)
