### ISSUE TITLE
Youtube | https://www.youtube.com/

### ISSUE THREAD

**Issue by notpofkp** [PreMiD/Presences#6238]
### Description

The presence flat-out does not function at all. No matter what youtube video i go to, nothing is displayed in the status.

### Steps to Reproduce

1. Install YouTube presence from the PreMiD presence store
2. Go to https://www.youtube.com/
3. Go to _any_ youtube video of your liking.
4. Look at your discord status, where it would normally display what you are doing on youtube.

### Screenshots

![image](https://user-images.githubusercontent.com/105764795/168950216-8f945556-dd76-4f66-8c3e-41d4e0c072aa.png)
![image](https://user-images.githubusercontent.com/105764795/168950238-8b49e9ca-ad76-4df3-b578-5b1812a0f488.png)

### Expected Behavior

The status would display what YouTube video i'm currently watching, the current timestamp and also show buttons to click that send you to the video/channel.

### Actual Behavior

No status of this type was displayed at all.

### Page URL

https://www.youtube.com/ as a whole

### Operating System (OS)

Windows 10

### Browser

Brave & Waterfox

### Browser Version

Brave: Version 1.38.119 Waterfox: G4.1.1.1

**Comment by notpofkp** [comment]
i don't have the same issue whilst using youtube music. only youtube

**Comment by kyrie25** [comment]
There are no patches available at the moment, but this is a common bug with various fixes & workarounds listed in the [Discord server](https://discord.premid.app). Take a look there if you want.

**Comment by EncryptedDev** [comment]
Not reproducable, most likely a user issue. Please do as Anh suggested above
