### ISSUE TITLE
I'd Like to request a new website to be added to premid

### ISSUE THREAD

**Issue by Infernite** [PreMiD/Presences#6247]
### Website name

wiki.gg

### Website URL

https://wiki.gg/

### Website logo

https://media.discordapp.net/attachments/801353652181925899/977254615642935336/Screenshot_2022-05-20_233025.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

You can adjust the logo to what it fits, its not a big deal. I just normally use the website alot so it'd be nice to have a presence.

**Comment by EncryptedDev** [comment]
This request is vague - please include more detail in the fields as prompted
