### ISSUE TITLE
Roblox

### ISSUE THREAD

**Issue by kikckys** [PreMiD/Presences#6248]
### Description

The roblox extention is not logging or showing what game im playing correctly.

### Steps to Reproduce

1.

### Screenshots

https://gyazo.com/9ac228c870f292de411256c3100ae4a0

### Expected Behavior

Show the game Im on in the browser.

### Actual Behavior

Not showing and only showing the home page.

### Page URL

https://www.roblox.com/home

### Operating System (OS)

Windows 11.

### Browser

Chrome

### Browser Version

Newest

**Comment by ImRodry** [comment]
That screenshot is from the Roblox game presence. PreMiD supports websites only and we can't do anything about it at the current time. Also next time, please fill the issue form correctly
