### ISSUE TITLE
Facebook | facebook.com

### ISSUE THREAD

**Issue by PhilMinecraft** [PreMiD/Presences#6259]
### Description

The Facebook's presence uses the wrong shape of the Facebook's logo, use the circle one instead of the square one

### Steps to Reproduce

1. facebook.com

### Screenshots

![image](https://user-images.githubusercontent.com/67897800/169693256-b5b46dd1-fc61-4f1c-b8d8-8e254350cc3e.png)
![Facebook_f_logo_(2021)](https://user-images.githubusercontent.com/67897800/169693259-e57b2d52-61c0-4908-b36d-d854c09b77d8.png)

### Expected Behavior

Use latest Facebook's logo shape (circle)

### Actual Behavior

Only shows the square one (which is not correct)

### Page URL

facebook.com

### Operating System (OS)

Windows 7 (I don't have money for new laptop ;-;)

### Browser

Edge

### Browser Version

100.0.1185.50 (Opisyal na build) (64-bit)

**Comment by EncryptedDev** [comment]
Requires the owner of the clientId to change, added the author to do this

**Comment by PhilMinecraft** [comment]
> Requires the owner of the clientId to change, added the author to do this

wdym?

**Comment by Bas950** [comment]
Changed.

**Comment by PhilMinecraft** [comment]
it's still having the old logo
![image](https://user-images.githubusercontent.com/67897800/176449925-bd407db2-1183-4d4c-8a8f-2431469f32ba.png)

**Comment by PhilMinecraft** [comment]
ok, thanks, and synced to my Profile
![image](https://user-images.githubusercontent.com/67897800/176557756-a1b10357-98b7-452b-93af-5580c05df67f.png)
