### ISSUE TITLE
MangaOwl.net RP

### ISSUE THREAD

**Issue by ZUNII** [PreMiD/Presences#6267]
### Presence name

MangaOwl

### Description

**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [x] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
「ZXИII」#7777

**What's the name of the service?** 
https://mangaowl.net

**What should the Presence display?** 
The same like Netflix, Youtube etc. if possible

**If possible, please provide a logo for the service (512x512 minimum)** 
https://mangaowl.net/uploads/images/logo.png (it's 80x80)

**Comment by EncryptedDev** [comment]
Not sure how you've done this, but please use the new feature request template.
