### ISSUE TITLE
EDMDemons | edmdemons.com

### ISSUE THREAD

**Issue by MitchMitchellR** [PreMiD/Presences#6269]
### Website name

EDMDemons

### Website URL

http://edmdemons.com/

### Website logo

<img src="https://user-images.githubusercontent.com/104971430/170582668-2f6903ea-336b-4e7b-87bb-28d6d5c5393b.png"/>

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Viewing Home Page, and posts

**Comment by Isa27-0** [comment]
> Website logo
EDM DEMONS

Website logo is for the logo, not the name.

**Comment by MitchMitchellR** [comment]
Website logo:
![EDM Demons](https://user-images.githubusercontent.com/104971430/170582668-2f6903ea-336b-4e7b-87bb-28d6d5c5393b.png)

**Comment by joerkig** [comment]
Website was shut down on the first of September 2022 @theusaf
