### ISSUE TITLE
Roblox server count

### ISSUE THREAD

**Issue by ThatLazyBucket** [PreMiD/Presences#6271]
### Presence name

Roblox

### Description

You should add it where when you're inside a game, it shows how many players are in a roblox server with you and it could be live

The reason why is so friends could join if they wanted, possibly make it where there's a join button for the server too 
( it can be a setting ) 

### Alternatives

Basically it'll be a way to play easier with friends. If the server is full it'll say it, but if it's not it'll have the 14/20 or something

**Comment by EncryptedDev** [comment]
We do not support in-game presences, only website presences
