### ISSUE TITLE
Anizm.TV | https://anizm.net/

### ISSUE THREAD

**Issue by puffytr** [PreMiD/Presences#6275]
### Description

This presence is not working. I try to debug but I Can't add TMP Presence on my browser. I couldn't find the problem because I couldn't add it to the browser.

### Steps to Reproduce

Not working.

### Expected Behavior

Fix it.

### Actual Behavior

Fix it.

### Page URL

https://anizm.net/

### Operating System (OS)

Windows 10

### Browser

Chrome, Opera

### Browser Version

Chrome: 101.0.4951.67 / Opera: 86.0.4363.64

**Comment by EncryptedDev** [comment]
This is not descriptive. Fill the template in properly.
