### ISSUE TITLE
Plex | add support for local ip server http://127.0.0.1:32400/

### ISSUE THREAD

**Issue by pierrequiroul** [PreMiD/Presences#6276]
### Presence name

Plex

### Description

The Plex presence doesn't show up by using its local server url http://127.0.0.1:32400/

**Comment by RisingSunLight42** [comment]
It's basically impossible since it's a local server and the link has nothing related to plex that can help the presence to target locals servers.
@EncryptedDev I think this issue can be closed.

**Comment by RisingSunLight42** [comment]
> It's basically impossible since it's a local server and the link has nothing related to plex that can help the presence to target locals servers.
> @EncryptedDev I think this issue can be closed. 

@EncryptedDev sorry to disturb you TwT
