### ISSUE TITLE
Plex | https://app.plex.tv/

### ISSUE THREAD

**Issue by pierrequiroul** [PreMiD/Presences#6277]
### Description

When the show cover option is on, it doesn't show the cover of the movie. It only shows a broken link image.

### Steps to Reproduce

1. Show covers option on
2. Launch a movie

### Screenshots

![image](https://user-images.githubusercontent.com/35348696/171030471-ebcaf2f3-13c9-474f-baf0-71506a858968.png)

### Expected Behavior

The cover showed shoud be the movie one

### Actual Behavior

The cover showed is a broken link image

### Page URL

https://app.plex.tv/desktop/#!/media/49094ddc79354c3de4472afb9df8aa5d175a9d03/com.plexapp.plugins.library?source=3

### Operating System (OS)

windows 10

### Browser

Brave

### Browser Version

browser 1.39.111 chromium 102.0.5005.61

**Comment by xKubsoneQ** [comment]
broken (probably) only on localhost,

plex.tv:
![image](https://user-images.githubusercontent.com/63014799/175575995-c77f2724-fc2f-4b00-b339-44aeef54e522.png)

localhost:
![image](https://user-images.githubusercontent.com/63014799/175576085-bcfa3b7c-a0d8-491f-a559-01e1bb0656a7.png)
