### ISSUE TITLE
myCANAL doesn't display the current show

### ISSUE THREAD

**Issue by skoki2** [PreMiD/Presences#6290]
### Steps to Reproduce

1. Go to myCANAL
2. Play any video on the site

### Expected Behavior

Presence shows what you are watching

### Actual Behavior

Presence only displaying "Browsing..."

### Page URL

https://canalplus.com/fr/

### Operating System

Windows 10

### Browser and Version

Brave 1.39.111

**Comment by EncryptedDev** [comment]
Reproducable, contacting presence author
