### ISSUE TITLE
Airbnb presence request

### ISSUE THREAD

**Issue by MinerSpark** [PreMiD/Presences#6300]
### Website name

Air BnB

### Website URL

https://www.airbnb.co.uk/

### Website logo

https://static.dezeen.com/uploads/2014/07/Airbnb-rebrand-by-DesignStudio_dezeen_468_8.jpg

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

A website about buying/renting hotel locations and reserved dates.
Preferably displaying location, logo booking dates and time on page.
Your mind is your will

**Comment by Isa27-0** [comment]
> Website URL
> https://www.airbnb.co.uk/

This is the Airbnb subdomain for your country, its 'universal' URL is: https://www.airbnb.com

**Comment by MinerSpark** [comment]
Rich Presence for airbnb.co.uk doesn't work, The "universal" url isn't for the entire website, It redirects to your area, so .com will work, while .co.uk does not.
quick show: https://youtu.be/jRywZIN0lrM

**Comment by realtofuine** [comment]
nooooooooooooo
ok ill fix later
