### ISSUE TITLE
PreMiD | premid.app

### ISSUE THREAD

**Issue by HanaNoAme** [PreMiD/Presences#6313]
### Steps to Reproduce

1. Turn off PreMiD website presence
2. Go to premid.app

### Expected Behavior

Presence doesn't show on Discord

### Actual Behavior

Presence still shows on Discord

### Page URL

[premid.app](https://premid.app/store)

### Screenshots

![image](https://user-images.githubusercontent.com/59003645/173197101-e6557bf0-15f4-4c6c-a5ed-dbfde09ac72a.png)
![image](https://user-images.githubusercontent.com/59003645/173197264-749cf006-d0c3-4336-9587-df45bb06ac1b.png)

### Operating System

Windows 11

### Browser and Version

Google Chrome 102.0.5005.115

### Additional Comments

This is an issue that I've experienced a few years ago when I first used PreMiD

**Comment by ImRodry** [comment]
The only issue here is you being able to disable the presence as it shouldn't be disabled but, as you saw, it doesn't work and this is intentional. The same applies to PreMiD partners
