### ISSUE TITLE
KissAsian does not show the show you are watching

### ISSUE THREAD

**Issue by sendotxt** [PreMiD/Presences#633]
**Describe the bug**
KissAsian's rich presence currently does not show what show the user is watching.

**Expected behavior**
Show the show/movie the user is watching, as well as the details such as: what episode they're watching and how much time is left for the episode the user is watching.

**Screenshots**
When the user is browsing the site and clicks on a show/movie, it shows the drama they're viewing no problem. But once the user starts watching an episode of said show/movie, this is shown.
![image](https://user-images.githubusercontent.com/56758020/68890858-115ee100-0720-11ea-92f5-f29250973c14.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78.0.3904.97 (currently the latest version)

**Comment by doomlerd** [comment]
Can't reproduce, need more details and the exact page URL where it occurs.

![image](https://user-images.githubusercontent.com/26717942/69075344-82a8d780-0a31-11ea-8f07-04f94733ddfb.png)

**Comment by Bas950** [comment]
Please sent us the URL of where this occurs, I myself cannot reproduce it.

**Comment by sendotxt** [comment]
I found out that the problem only occurs outside of the "Alpha" and "KissAsian Beta" server on the site when viewing an episode. So when on the "FE", "HX", "FB" and "MP" server, the problem _does_ occur. 

Links to an episode in the different servers where this occurs:
https://kissasian.sh/Drama/Gracious-Revenge/Episode-1?id=51067&s=fe
https://kissasian.sh/Drama/Gracious-Revenge/Episode-1?id=51067&s=hx
https://kissasian.sh/Drama/Gracious-Revenge/Episode-1?id=51067&s=mp
(selecting the "FB" server seems to automatically redirect to the "FE" server, so it's the same link.)

And also an image of where the server select drop-down is located
![image](https://user-images.githubusercontent.com/56758020/69159835-d0cce200-0ae8-11ea-879f-4e6ef195d0db.png)

My apologies for not doing proper research about the problem before submitting the bug!
