### ISSUE TITLE
Roblox | roblox.com

### ISSUE THREAD

**Issue by mihaiofficialRO** [PreMiD/Presences#6330]
### Steps to Reproduce

1. https://www.roblox.com/games/9512938290/UPDATE-Gas-Station-Tycoon
2. Check Discord Activity
3. Obvserve that is showing the homepage, not the game itself - section About

### Expected Behavior

the game itself

### Actual Behavior

homepage itself

### Page URL

https://www.roblox.com/games/9512938290/UPDATE-Gas-Station-Tycoon

### Screenshots

![image](https://user-images.githubusercontent.com/38259440/176246455-485e631c-2db5-44b1-8249-81cc7da127dd.png)
![image](https://user-images.githubusercontent.com/38259440/176246487-153cb2b3-547b-43b2-91b1-88052dc76df7.png)

### Operating System

Windows 10

### Browser and Version

Brave: Version 1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit)

**Comment by ImRodry** [comment]
Fixed in https://github.com/PreMiD/Presences/commit/5422cf6329c24391b320fe59b8278b215928a87f
