### ISSUE TITLE
Epic Games | epicgames.com

### ISSUE THREAD

**Issue by mihaiofficialRO** [PreMiD/Presences#6333]
### Steps to Reproduce

1. https://store.epicgames.com/en-US/
2. Check Discord Activity

### Expected Behavior

to show the activity

### Actual Behavior

is showing nothing

### Page URL

https://store.epicgames.com/en-US/

### Operating System

Windows 10

### Browser and Version

Brave: Version 1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit)

**Comment by ImRodry** [comment]
The presence does not support that website therefore this is not a bug. You can make a PR to support it though, or open a feature request
