### ISSUE TITLE
MangaKakalot | mangakakalot.com, manganelo.com

### ISSUE THREAD

**Issue by yoheii** [PreMiD/Presences#634]
**What's the name of the service?**
https://mangakakalot.com, https://manganelo.com// | MangaKakalot, Mangaleno 
It's the same site but different domains i guess, bc the accounts are the same on both domains no need to log in the other site, most mangas open with the mangakakalot domain but some opens in manganelo.

**What should the Presence display?**
![test1](https://user-images.githubusercontent.com/57054593/68898112-955b9d80-070d-11ea-931d-2d3057ebea94.png)

**Why do you want support for this service?**
Easily the best manga site out there,hardly offline and has a huge library.

**Are you able to provide an image for the service? (512x512 minimum)**
![MangaKakalot](https://user-images.githubusercontent.com/57054593/68897793-f8990000-070c-11ea-9285-f5ffde3d4d27.png)

**Comment by dana0404** [comment]
I'll give it my best go. I have a working model as of now. Really want to get the page number right though
