### ISSUE TITLE
Google Sheets presence

### ISSUE THREAD

**Issue by EmmanuelOkunhon** [PreMiD/Presences#6344]
### Website name

Google Sheets

### Website URL

https://www.google.com/sheets/about/

### Website logo

https://play-lh.googleusercontent.com/keE2gN0Hqh8-Tsf_RYZ_-yS2uo6ToqYVyRBv_UZaLXsgeeHBd2YPcEUWEF4DEtfGyb1h=w600-h300-pc0xffffff-pd

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Same as Google Docs, I would like to have the name of the sheet displayed as well as how much time its been viewed/used. 
Thank you.

**Comment by EncryptedDev** [comment]
This is included under the Google Docs presence as shown in the supported URLs. 
If it does not work, it is an issue and you should create a bug report instead.
