### ISSUE TITLE
PreMiD | https://premid.app/

### ISSUE THREAD

**Issue by narko72** [PreMiD/Presences#6347]
### Steps to Reproduce

1) https://premid.app/
2) Install the application and the Chrome extension
3) Then go back to the site and click on store and add "Deezer"
4) Check on the Chrome extension that Deezer is activated
5) Launch Deezer on the (browser) and the discord application
6) And finally launch a music on Deezer and watch the profile on discord

### Expected Behavior

Display the application to use (Deezer) and the name of the music, the artist and the cover of the music

### Actual Behavior

Only the display of the application to use (Deezer)

### Page URL

No URL it was discord

### Screenshots

![Capture d’écran 2022-06-20 210907](https://user-images.githubusercontent.com/107889333/174676707-f4c266ab-6aef-4b49-b83b-95b1f496f3ce.jpg)

### Operating System

Windows 10 Pro

### Browser and Version

Google Chrome

**Comment by EncryptedDev** [comment]
Invalid as explained in https://github.com/PreMiD/Presences/issues/6347#issuecomment-1161879336
