### ISSUE TITLE
Cuevana3 | https://ww3.cuevana.pro/

### ISSUE THREAD

**Issue by DiegoYisus** [PreMiD/Presences#6351]
### Steps to Reproduce

https://ww3.cuevana.pro/
https://premid.app/store/presences/Cuevana%203

### Expected Behavior

that the presence of cuevana3 will function normally as the other premid 

### Actual Behavior

cuevana3 premid site is not working 

### Page URL

https://ww3.cuevana.pro/

### Screenshots

![Screenshot 2022-06-21 203544](https://user-images.githubusercontent.com/107974177/174938148-7b26cd87-b0df-49f5-920e-6a43dbf85e9b.jpg)

### Operating System

windows 10 home

### Browser and Version

brave, google

**Comment by realtofuine** [comment]
Reproducible
