### ISSUE TITLE
d Anime store custom status

### ISSUE THREAD

**Issue by neco222** [PreMiD/Presences#6352]
### Steps to Reproduce

d Even if I open the anime store, it is not reflected in discord

### Expected Behavior

When opened

### Actual Behavior

Nothing happens

### Page URL

https://animestore.docomo.ne.jp/animestore/tp_nm

### Screenshots

![20220622_155953](https://user-images.githubusercontent.com/107422195/174964502-43a24976-a91b-47b0-b555-cb245456fab8.jpg)

### Operating System

Windows11 Surface

### Browser and Version

Chrome 102.0.5005.115

### Additional Comments

Please take immediate action and repair.

**Comment by RisingSunLight42** [comment]
@EncryptedDev hello! Could you close this issue since there's no bug ? 🙏
Thank youuuu

**Comment by EncryptedDev** [comment]
Sorry! Didn't see your message sooner @RisingSunLight42

**Comment by RisingSunLight42** [comment]
> Sorry! Didn't see your message sooner @RisingSunLight42 

No worries ^^
