### ISSUE TITLE
GeoGuessr | geoguessr.com

### ISSUE THREAD

**Issue by NMW03** [PreMiD/Presences#636]
**What's the name of the service?**
Ex. www.geoguessr.com | GeoGuessr

**What should the Presence display?**
Informations about the current map

**Why do you want support for this service?**
I'd like to show what I'm playing on at the moment. I think the use of this presence would be high.

**Are you able to provide an image for the service? (512x512 minimum)**
https://upload.wikimedia.org/wikipedia/commons/3/3f/GeoGuessr_logo.svg

**Comment by Hans5958** [comment]
Hey, I'm going to do this. Expect this Saturday or Sunday if I have no difficulties.

**Comment by frozaum** [comment]
added #797
