### ISSUE TITLE
YouTube | youtube.com - not working

### ISSUE THREAD

**Issue by LostFelix** [PreMiD/Presences#6370]
### Steps to Reproduce

1. Go on to any youtube Video like https://www.youtube.com/watch?v=xGbxsiBZGPI
2. Reload

### Expected Behavior

Webpage is parsed for PreMid

### Actual Behavior

Webpage is not parsed for PreMid

### Page URL

https://www.youtube.com/watch?v=xGbxsiBZGPI

### Screenshots

Other Outputs in the developer console:
![image](https://user-images.githubusercontent.com/85457584/176044640-235f14f0-6250-4930-95f1-478776a47eed.png)

Discord Activity Missing Youtube:
![image](https://user-images.githubusercontent.com/85457584/176044702-15ff7ad5-81a0-448c-a80d-cbf88122940b.png)

Windows OS:
![image](https://user-images.githubusercontent.com/85457584/176044752-5e55bc29-94d3-46a5-920a-38d9ae370b12.png)

Chrome Build:
![image](https://user-images.githubusercontent.com/85457584/176044552-b87e0e01-6ada-4335-92a6-99990883d0ec.png)

### Operating System

Windows 10 Pro

### Browser and Version

Chrome - Version 103.0.5060.66 (Official Build) (64-bit)

**Comment by realtofuine** [comment]
It works for me.

I have the same chrome version, but I'm on Win 11.

![image](https://user-images.githubusercontent.com/73127480/176171444-1e03a079-5736-446c-9bc8-bd60544366a6.png)

**Comment by Jackelele** [comment]
It also works for me. 

I'm currently using Windows 10 Pro but using Brave. 
![image](https://user-images.githubusercontent.com/20693601/176210435-44d00ce3-2cea-4b5b-8312-2679e7ae3288.png)

**Comment by Isa27-0** [comment]
For me it's working normally, even with some options turned on (like incognito mode)
![image](https://user-images.githubusercontent.com/68751594/176969844-d9d58b09-4611-41bd-adaa-ba428da4621e.png)
I use Opera GX version 88.0.4412.65. Have you checked the PreMiD [troubleshooting](https://docs.premid.app/en/troubleshooting) page?

**Comment by mythicalgryffn** [comment]
Same thing is happening to me, it's a pain in the ass and I have to end up messing around with it for half an hour to get it working, a solution or a fix would be great.

I'm running Opera GX 88.0.4412.65 btw.

**Comment by lIIIlIlllI** [comment]
My preMid for Youtube can't work properly too.
It happened few days ago.
![image](https://user-images.githubusercontent.com/101412362/177315939-1ca99d8c-9e52-4678-a8b8-dd4ffd9a5b15.png)
Chrome Version: 103.0.5060.114 (Official Build) (64-bit)

**Comment by slademcg** [comment]
Not working for me either

**Comment by dalsoteez** [comment]
Not working for me, when on YouTube nothing shows at all on my discord presence

**Comment by ayyyiieneheuihues** [comment]
I am the guy from issue #7621 and now it works again for no reason when I haven't changed anything. I am happy but I doubt this is permanent. I hope this issue can somehow be fixed.

**Comment by ayyyiieneheuihues** [comment]
yeah, the presence is still glitching out, I hope this can be fixed
