### ISSUE TITLE
speedtest.net | Bug Report

### ISSUE THREAD

**Issue by callumok2004** [PreMiD/Presences#6374]
### Steps to Reproduce

1. Install the speedtest.net presence.
2. Visit the website
3. Notice in the developer console the errors you are receiving!

### Expected Behavior

It should show just fine.

### Actual Behavior

It gives errors.

### Page URL

https://www.speedtest.net

### Screenshots

![image](https://user-images.githubusercontent.com/35779365/176272759-c9aa70de-4ccd-4869-8f8b-06beb380420f.png)

### Operating System

Windows 11

### Browser and Version

Chrome - Latest

### Additional Comments

The speedtest.net website has had some recent UI changes which are most likely the cause of this, it is an issue several people have noticed.

The UI changes are in this section.
![image](https://user-images.githubusercontent.com/35779365/176272967-768af31c-33a4-47ce-9cb7-1f89cce5562a.png)

**Comment by StrikerFRFX** [comment]
Can reproduce
![opera_vu4Tyhzsr4](https://user-images.githubusercontent.com/34070194/176276466-00eae844-aaa0-4812-9869-535f7602df16.png)
