### ISSUE TITLE
Domino's Pizza (UK) | dominos.co.uk

### ISSUE THREAD

**Issue by arcadeio** [PreMiD/Presences#638]
**What's the name of the service?**
Dominos Pizza
https://www.dominos.co.uk/

**What should the Presence display?**
Information about your cart and what you're viewing

**Why do you want support for this service?**
bcos i want folk on discord to see me buying pizzas and make them jealous

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image
https://www.dominos.co.uk/Content/Images/Site/dominos_logo_small.png?v=2

**Comment by frozaum** [comment]
you need to provide a website link

**Comment by arcadeio** [comment]
Updated 👍
