### ISSUE TITLE
Spotify podcasts not working, wouldnt show up on discord.

### ISSUE THREAD

**Issue by Nee-Chan** [PreMiD/Presences#6415]
### Steps to Reproduce

1.https://open.spotify.com
2.Play any podcast

### Expected Behavior

Show what podcast I m playing on spotify web, on my discord.

### Actual Behavior

Did not show the podcast being played

### Page URL

https://open.spotify.com

### Operating System

Windows 10

### Browser and Version

Opera GX LVL 4 (core: 88.0.4412.75)

### Additional Comments

Premid seems to be working just fine, it just the spotify podcasts extension that is not working.

**Comment by Nee-Chan** [comment]
I tried chrome and it still didnt work

**Comment by SladeHazard** [comment]
+1, windows 11 brave browser

**Comment by DarkVillager** [comment]
Can reproduce, with presence from the store but not locally.

**Comment by Bas950** [comment]
> Can reproduce, with presence from the store but not locally only with the store version.
> 
> ![image](https://user-images.githubusercontent.com/42322979/182317905-3e24843f-f31e-4356-bf72-cf6d93ccf966.png)
> 
> Seems to be this (line 118):
> ```function asyncGeneratorStep(e, t, n, r, s, a, o) {
> 	try {
> 		var i = e[a](o),
> 			l = i.value;
> 	} catch (e) {
> 		return void n(e);
> 	}
> 	i.done ? t(l) : Promise.resolve(l).then(r, s);
> }

Feel free to pr it if you know a fix

**Comment by DarkVillager** [comment]
> > Can reproduce, with presence from the store but not locally only with the store version.
> > ![image](https://user-images.githubusercontent.com/42322979/182317905-3e24843f-f31e-4356-bf72-cf6d93ccf966.png)
> > Seems to be this (line 118):
> > ```
> > 	try {
> > 		var i = e[a](o),
> > 			l = i.value;
> > 	} catch (e) {
> > 		return void n(e);
> > 	}
> > 	i.done ? t(l) : Promise.resolve(l).then(r, s);
> > }
> > ```
> 
> Feel free to pr it if you know a fix

Tbh i have no clue

**Comment by SladeHazard** [comment]
please fix!!

**Comment by RisingSunLight42** [comment]
> please fix!!

We didn't find a fix for the moment sadly

**Comment by Arrow2001** [comment]
Same issue :(

**Comment by batuhank24** [comment]
I found something I don't know if it is the right place but this git page was given from PreMiD support. If you playing podcasts from "https://open.spotify.com/collection/episodes" it shows missing on Discord status but if you go to the stand-alone page of podcast and open it (I showed it below) the situation seems to be what you want. Hope it will be of use to those dealing with it.
> ### working:
![image](https://user-images.githubusercontent.com/58747856/186248299-4931c7e1-123a-4403-8541-219b5779f315.png)
![image](https://user-images.githubusercontent.com/58747856/186248403-dc1993e4-39c2-44e4-93b3-acaafd1b7c5f.png)
> ### missing:
![image](https://user-images.githubusercontent.com/58747856/186248517-3fa7143e-fd40-41ef-a1df-44300952909a.png)
![image](https://user-images.githubusercontent.com/58747856/186248582-7a1cccbd-d6a4-4a13-8452-1e085b57229e.png)

Version 104.0.5112.102 (Official Build) (64-bit) -> Google
Stable 142995 (adcce46) -> Discord
Host 1.0.9006 -> Discord
Windows 10 64-Bit (10.0.19043)

**Comment by DarkVillager** [comment]
> 

New issue as bug pls :)
