### ISSUE TITLE
YouTube Music | music.youtube.com

### ISSUE THREAD

**Issue by SuperMarioROCKS** [PreMiD/Presences#6421]
### Steps to Reproduce

Go to YT music
Play a song
Observe if album cover, song name, artist, and album appear

### Expected Behavior

All the information of a song should appear in status

### Actual Behavior

Your status instead just shows that you're on YT Music, or flat-out just won't show at all

### Page URL

https://music.youtube.com

### Operating System

Windows 11 AND Arch Linux

### Browser and Version

Microsoft Edge Version 103.0.1264.44 (Official build) (64-bit)

### Additional Comments

I've asked my friends who use premid to show their youtube music status if they had this bug, 2 to be exact, and 1 of them had this problem as well, while the other used it perfectly fine. Don't exactly know what browsers they were using (chances are Chrome), but I know that they were on Windows 10.

**Comment by SuperMarioROCKS** [comment]
the presence seems to be working again!
![image](https://user-images.githubusercontent.com/80995977/178135914-311adeae-b9c9-4615-943a-af9e0bd2ba51.png)

**Comment by SuperMarioROCKS** [comment]
problem came back a day later, lol

**Comment by RisingSunLight42** [comment]
Do an error shows up in the browser console when this error occur?

**Comment by SuperMarioROCKS** [comment]
> Do an error shows up in the browser console when this error occur?

nope, no errors.

**Comment by alex9997979z** [comment]
yeah the same thing happens to me here
doing anything just fixes it temporarily until it breaks again
