### ISSUE TITLE
9anime | https://9anime.vc/

### ISSUE THREAD

**Issue by PrincessNia** [PreMiD/Presences#6425]
### Steps to Reproduce

1. Download and install both PreMiD application and extension
2. Install "9anime" presence from the Presence Store
3. Open a 9anime page

### Expected Behavior

The 9anime presence within PreMiD should activate and display the current show, episode, and elapsed time

### Actual Behavior

Nothing is displayed in Discord, even PreMiD itself is absent. Browser console throws a wall of errors saying that "textContent" is null

### Page URL

https://9anime.vc/

### Screenshots

![image](https://user-images.githubusercontent.com/16831074/178084463-fa6ff771-d675-403b-977f-e59813e71d55.png)

### Operating System

Windows 10, 64-bit

### Browser and Version

Microsoft Edge Version 103.0.1264.44 (Official build) (64-bit)

### Additional Comments

Before refreshing discord to try and make it work "properly" there was a brief period where PreMiD displayed I was "playing 9anime" with a basic timer of how long I'd been on the webpage.

**Comment by EncryptedDev** [comment]
Hello. I have managed to reproduce this issue, hence why the label was removed. I've seen this issue occur many times, probably to do with the service changing constantly. 

Hopefully it is fixed within a timely manner & thank you for the report 🤞

**Comment by EncryptedDev** [comment]
Try to use the `9anime.me` domain instead of the `9anime.vc` domain
