### ISSUE TITLE
Channel 4 / All 4

### ISSUE THREAD

**Issue by shellacnails** [PreMiD/Presences#6429]
### Website name

Channel 4

### Website URL

https://www.channel4.com/

### Website logo

https://play-lh.googleusercontent.com/IJTA5B41Einoli3azzrLVHI3mQG3A4Ji97MTt2PbuK2XClWPi3SpOylyRcgXVPj7N-4

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [X] It is region restricted

### Description

It's a streaming service for TV, so preferrably something for when you are browsing and something for when you are watching a specific series or film like how the Netflix presence or BBC iPlayer presence looks. Elapsed time etc / time left of episode etc

**Comment by DarkVillager** [comment]
Duplicate #5447
