### ISSUE TITLE
Nad Games | nadgames.com

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [PreMiD/Presences#643]
**What's the name of the service?**
nadgames.com
**What should the Presence display?**
Playing games, match scores?

**Why do you want support for this service?**
There are lots of people playing in this website and perhaps their match should be shown.

**Are you able to provide an image for the service? (512x512 minimum)**
![image](https://user-images.githubusercontent.com/45579671/68985160-4f640f80-07c9-11ea-9acd-295b1cd8b190.png)

**Comment by frozaum** [comment]
Please provide us a logo instead of a screenshot, thanks.

**Comment by OfficialNOTORIOUS7302** [comment]
how do i do that?

**Comment by doomlerd** [comment]
Get it from the website, or crop it ( the logo in the screenshot ) to be square, must be ≥ 512px.

**Comment by OfficialNOTORIOUS7302** [comment]
![logohd](https://user-images.githubusercontent.com/45579671/69303038-5d060480-0bd0-11ea-825c-83653ea46e98.png)
:P

**Comment by Gurrman375** [comment]
Is anyone working on this presence?
