### ISSUE TITLE
GitHub Gist

### ISSUE THREAD

**Issue by Technetium1** [PreMiD/Presences#6435]
### Presence name

GitHub: https://github.com/PreMiD/Presences/tree/main/websites/G/GitHub

### Description

Gist is missing: https://gist.github.com/

### Alternatives

N/A

### Additional context

N/A

**Comment by EncryptedDev** [comment]
Lacking detail

**Comment by Technetium1** [comment]
What details would you like added @EncryptedDev?

**Comment by EncryptedDev** [comment]
Further detail of what you what supported, possible implementations etc

**Comment by Technetium1** [comment]
I would like https://gist.github.com supported as part of existing GitHub integration: https://github.com/PreMiD/Presences/tree/main/websites/G/GitHub. I don't know Typescript to suggest correct implementation, but I suspect it could be added as a path here: https://github.com/PreMiD/Presences/blob/5ccc89aca1c18bb5e8de37dca18f3e659e134b7b/websites/G/GitHub/presence.ts#L60 with an inclusion in the following switch statement.

**Comment by realtofuine** [comment]
ye I can try and put in the existing pr

I'll do it tmrw or smthng cuz I have stuff today :)

**Comment by realtofuine** [comment]
> I would like https://gist.github.com supported as part of existing GitHub integration: https://github.com/PreMiD/Presences/tree/main/websites/G/GitHub. I don't know Typescript to suggest correct implementation, but I suspect it could be added as a path here:
> 
> https://github.com/PreMiD/Presences/blob/5ccc89aca1c18bb5e8de37dca18f3e659e134b7b/websites/G/GitHub/presence.ts#L60
> 
> with an inclusion in the following switch statement.

lol it was much harder than that but i think the pr will fix it now (when it gets merged)
