### ISSUE TITLE
Rooster Teeth | roosterteeth.com

### ISSUE THREAD

**Issue by ELITE-NOTORIOUS-Supremacist** [PreMiD/Presences#644]
**What's the name of the service?**
https://roosterteeth.com/

**What should the Presence display?**
Informations about the current video

**Why do you want support for this service?**
Famous website where everyone can watch videos.

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image

**Comment by chaos511** [comment]
I will make this👍
