### ISSUE TITLE
Emuparadise  request 

### ISSUE THREAD

**Issue by DiegoYisus** [PreMiD/Presences#6458]
### Website name

Emuparadise

### Website URL

https://www.emuparadise.me/

### Website logo

Emu paradise

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

![Captura de pantalla 2022-07-15 145832](https://user-images.githubusercontent.com/107974177/179316668-f0309dda-072f-4e48-8140-fe7f5f4d3e7e.jpg)
It is a page to download roms for pc

**Comment by Isa27-0** [comment]
I don't think it would be possible to add, because this type of site is against the ToS of some companies.

**Comment by EncryptedDev** [comment]
> I don't think it would be possible to add, because this type of site is against the ToS of some companies, sorry.

Why exactly?

**Comment by DarkVillager** [comment]
> > I don't think it would be possible to add, because this type of site is against the ToS of some companies, sorry.
> 
> Why exactly?

Piracy?

**Comment by EncryptedDev** [comment]
Piracy issues
