### ISSUE TITLE
New Presence for Youtube TV

### ISSUE THREAD

**Issue by IsaiahXL** [PreMiD/Presences#6460]
### Website name

Youtube TV

### Website URL

https://tv.youtube.com/welcome/

### Website logo

https://www.allconnect.com/wp-content/uploads/2020/02/youtube-tv-review-hero-0224.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

YouTube TV is a streaming television service that offers live TV, on demand video and cloud-based DVR from more than 100 television networks.

**Comment by EncryptedDev** [comment]
Duplicate of #5285
