### ISSUE TITLE
request 4 anime presence

### ISSUE THREAD

**Issue by bloodzone09** [PreMiD/Presences#6472]
### Website name

4anime

### Website URL

https://4anime.gg/

### Website logo

4anime

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

is a website to watch anime, one of the more famous anime websites, a lot of people use 4anime

**Comment by EncryptedDev** [comment]
https://www.reddit.com/r/4anime/comments/oj11j2/website_permanent_shutdown/
