### ISSUE TITLE
discord premid it does not work

### ISSUE THREAD

**Issue by DiegoYisus** [PreMiD/Presences#6474]
### Steps to Reproduce

https://discord.com

download premid discord web 

### Expected Behavior

that works normally like the other premid

### Actual Behavior

chat username not working

### Page URL

https://discord.com/

### Screenshots

![eeeee](https://user-images.githubusercontent.com/107974177/180124850-7dd37409-5501-4910-bfa7-b6a2fc4b9f67.PNG)
![eee](https://user-images.githubusercontent.com/107974177/180124860-0d346327-eec3-4509-9680-4276fced67ea.PNG)

### Operating System

Windows 10 home

### Browser and Version

brave, google

**Comment by Isa27-0** [comment]
It's working normally for me, have you checked the [troubleshooting](https://docs.premid.app/en/troubleshooting) page?
![image](https://user-images.githubusercontent.com/68751594/180214974-c06ad0a9-a891-4cbf-80a2-839b1877ac41.png)

**Comment by DarkVillager** [comment]
**Operating System**
Windows 10 

**Browser and Version**
brave, google**

Can reproduce:
![image](https://user-images.githubusercontent.com/42322979/181200516-4fed5332-e276-4c16-9617-1e6097abbde2.png)
