### ISSUE TITLE
MSN | msn.com

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [PreMiD/Presences#648]
**What's the name of the service?**
www.msn.com

**What should the Presence display?**
Articles in which the user is reading and perhaps that they are playing a video within the article

**Why do you want support for this service?**
To determine what users are reading around MSN 

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image

**Comment by Leafageee** [comment]
Making now :D

**Comment by frozaum** [comment]
So, it's been 2 months without any updates about the Presence, so i will consider this Abandoned for now.

**Comment by Cairo2k18** [comment]
If no one else is doing this, assign it to me.
