### ISSUE TITLE
https://flixtor.to/home

### ISSUE THREAD

**Issue by tisyupepper** [PreMiD/Presences#6485]
### Steps to Reproduce

Go to link then play any movie.

### Expected Behavior

Activity should show on discord

### Actual Behavior

Activity is not shown on discord

### Page URL

https://flixtor.to/home

### Operating System

Windows 11

### Browser and Version

Chrome Version 103.0.5060.114 (Official Build) (64-bit)

**Comment by RisingSunLight42** [comment]
Bug reproduced, Application ID is not working.
