### ISSUE TITLE
Fixing Dramacool link that is being used at the moment

### ISSUE THREAD

**Issue by Sruoz** [PreMiD/Presences#6486]
### Presence name

Dramacool

### Description

Hello, I have noticed that whenever I load up dramacool, and I enable the presence on pre-mid for it. It never displays on my discord and I feel like the problem is the website that it is linked. I believe the current Dramacool presence is linked to this site 
![image](https://user-images.githubusercontent.com/109759870/180288865-f4936f40-1a29-4fd0-a2d1-bd7a8753ba66.png)

Only if I enter the website above it will show dramacool on discord, but the problem is it's an outdated website

While the updated site link is this one on the bottom, I am hoping it can be changed to
![image](https://user-images.githubusercontent.com/109759870/180289053-0de397f1-0799-4efd-a35f-926df3523e7f.png)
I say this link is the updated one because I have searched up dramas and found them through the search bar, while the one on the first screenshot, I couldn't find the dramas or they are not up to date.

I hope the website link can be changed to the  2nd screenshot I have shown, thank you in the future if this gets fixed.

### Additional context

https://www.dramacool9.co/

Updated website link I am hoping can be added, instead of the old one.

**Comment by DarkVillager** [comment]
@EncryptedDev this seems to have the wrong tag

**Comment by EncryptedDev** [comment]
This is likely due to the service changing domain as you said here: 
> I have noticed that whenever I load up dramacool, and I enable the presence on pre-mid for it. It never displays on my discord

As the presence doesn't work, it is classified as a bug and should be reported as a bug report instead.
