### ISSUE TITLE
desu-online.pl presence

### ISSUE THREAD

**Issue by Had4s** [PreMiD/Presences#6488]
### Website name

desu-online

### Website URL

https://desu-online.pl/

### Website logo

https://imgur.com/a/OJdlpjq

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

This is a polish site where you can watch various anime series, they have no ads

**Comment by xKubsoneQ** [comment]
#6309
