### ISSUE TITLE
9anime presence not working

### ISSUE THREAD

**Issue by Zanzancomms** [PreMiD/Presences#6489]
### Steps to Reproduce

9anime presence not working when opening the site, browsing through anime or watching

### Expected Behavior

should create a rich presence for the site, with browsing status, currently watching status

### Actual Behavior

does nothing

### Page URL

https://9anime.id/

### Screenshots

![image](https://user-images.githubusercontent.com/68141931/180309570-2289db53-3058-486a-99f5-14520079f133.png)
![image](https://user-images.githubusercontent.com/68141931/180309782-197fc30a-7f58-4650-aae5-e89cb678e48c.png)

### Operating System

windows 10

### Browser and Version

Google Chrome Version 103.0.5060.134 (Official Build) (64-bit)

### Additional Comments

seems to have been caused for an update to the site and it switching from 9anime.to to 9anime.id on said update
also something to do with how the episodes are organized now

**Comment by ericpremraju** [comment]
To add to the above issue, the extension works but doesn't show the anime being watched, it only shows like below.
![image](https://user-images.githubusercontent.com/58141370/180330676-6f8c48ad-c807-4b88-bb2b-e8829236843a.png)

**Comment by Zanzancomms** [comment]
yeah if you go to home then try watching something it will get stuck in **browsing..** instead of showing the anime and episode you are on

**Comment by RisingSunLight42** [comment]
I would like to fix it, but sadly, when trying to debug, a debugger keyword is raised by the presence / Premid by an unknown way and this block me from patching the presence.
Maybe @Slowlife01 is working on a fix ?
