### ISSUE TITLE
HBO Max | https://play.hbomax.com

### ISSUE THREAD

**Issue by AMufInABox** [PreMiD/Presences#6495]
### Steps to Reproduce

1. Watch a normal series/episode

2. Status shows "Watching movie" instead of the episode name

### Expected Behavior

Status is supposed to show the episode name & season, show and how many minutes are left

### Actual Behavior

It would show "Watching Movie" when I'm not watching a movie.

### Page URL

https://play.hbomax.com/

### Screenshots

Expected
![image](https://user-images.githubusercontent.com/74741218/180630111-0b71d3ba-4c35-4721-b96b-49cdcedaff34.png)

Actual
![image](https://user-images.githubusercontent.com/74741218/180630118-9dbafc7a-5881-4ff9-824a-62280c7db83f.png)

### Operating System

Windows 11

### Browser and Version

Brave Browser V1.41.100

**Comment by ItzEnzo** [comment]
Hopefully these issues can fixed. Also, I noticed it just shows "browsing" when looking through shows and movies, hopefully it can show the movie or show we're looking at.

Example:

Browsing TV Show
The Boondocks (2005)

Browsing Movie
Zack's Synder Justice League (2021)

**Comment by DarkVillager** [comment]
> Hopefully these issues can fixed. Also, I noticed it just shows "browsing" when looking through shows and movies, hopefully it can show the movie or show we're looking at.
> 
> Example:
> 
> Browsing TV Show The Boondocks (2005)
> 
> Browsing Movie Zack's Synder Justice League (2021)

Make an issue as a Feature Request.
