### ISSUE TITLE
ADN (Animation digital network) | https://animationdigitalnetwork.fr/

### ISSUE THREAD

**Issue by SimonJns** [PreMiD/Presences#6499]
### Steps to Reproduce

Go on https://animationdigitalnetwork.fr/, should show "Play ADN browsing" but not working. Support think Its the domain because this presence exist and was working a week ago. 

### Expected Behavior

Show browsing through anime or watching

### Actual Behavior

Nothing 

### Page URL

https://animationdigitalnetwork.fr/

### Screenshots

![Uploading image.png…]()

### Operating System

Windows 10

### Browser and Version

Google Chrome Version 103.0.5060.134 (Build officiel) (64 bits)

**Comment by RisingSunLight42** [comment]
Can confirm, the URL has changed, so the site cannot be recognized.

**Comment by RisingSunLight42** [comment]
Thanks for the report, I've fixed the issue in a Pull Request, the presence's bug will be patched soon.
