### ISSUE TITLE
Change the Facebook Watch icon

### ISSUE THREAD

**Issue by PhilMinecraft** [PreMiD/Presences#6511]
### Presence name

Facebook

### Description

Facebook Watch has its own dedicated icon, it doesn't fit if you just put Facebook on the logo alongside with the "Facebook Watch" name

### Alternatives

Change Facebook logo into Facebook Watch logo if I'm browsing or watching Facebook Watch contents

### Additional context

![image](https://user-images.githubusercontent.com/67897800/181003176-d21568ea-4d99-4cf5-962e-bc953f5a1a0f.png)
![svgexport-6](https://user-images.githubusercontent.com/67897800/181003217-9c5875e4-a611-4d76-9d3b-1372e130b2a3.svg)

**Comment by RisingSunLight42** [comment]
If not done today, I'll add it tomorrow

**Comment by DarkVillager** [comment]
@Slowlife01 Setting different client ids in one presence is only possible in the beta right?

**Comment by Slowlife01** [comment]
Kinda, only the clearActivity() function is broken

**Comment by PhilMinecraft** [comment]
> If not done today, I'll add it tomorrow

ok it's been 3 days, where is it now?
![image](https://user-images.githubusercontent.com/67897800/181871673-80c06171-3350-4b07-bc4c-c2f6f4754e89.png)

**Comment by DarkVillager** [comment]
> > If not done today, I'll add it tomorrow
> 
> ok it's been 3 days, where is it now? ![image](https://user-images.githubusercontent.com/67897800/181871673-80c06171-3350-4b07-bc4c-c2f6f4754e89.png) I put the Facebook Watch SVG icon on the bottom of the screenshot, use it for the presence's icon

It’s not impossible but kinda hard due to some functions not working on the normal version

**Comment by RisingSunLight42** [comment]
Yup, that's why I didn't add it. We need to wait for the creator to make an update for this to work fine.

**Comment by RisingSunLight42** [comment]
I've seen on #6552 that we can put imgur link in the largeImageKey value. Maybe we can do this way for this case?
Idk if this is fine, @EncryptedDev what do you think of that?

**Comment by EncryptedDev** [comment]
> I've seen on #6552 that we can put imgur link in the largeImageKey value. Maybe we can do this way for this case?
> Idk if this is fine, @EncryptedDev what do you think of that? 

Yep, you can

**Comment by DarkVillager** [comment]
> I've seen on #6552 that we can put imgur link in the largeImageKey value. Maybe we can do this way for this case? Idk if this is fine, @EncryptedDev what do you think of that?

Still they want the title to also be changed but that would require the methods that only work on beta atm.

**Comment by RisingSunLight42** [comment]
Perfect, so I take this issue, I'll create the PR to add the icon in the next hours
