### ISSUE TITLE
UKTV

### ISSUE THREAD

**Issue by shellacnails** [PreMiD/Presences#6514]
### Website name

UKTV Play

### Website URL

https://uktvplay.uktv.co.uk/

### Website logo

https://upload.wikimedia.org/wikipedia/en/2/2b/UKTV_logo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [X] It is region restricted

### Description

Streaming service - a "now watching" with elapsed time / time left, a browsing etc. Similar to Netflix

**Comment by EncryptedDev** [comment]
I think something went wrong with the website logo there @shellacnails

**Comment by shellacnails** [comment]
> I think something went wrong with the website logo there @shellacnails

Yeah it did a bit sorry 😭
