### ISSUE TITLE
Genius | https://genius.com/

### ISSUE THREAD

**Issue by Nalty** [PreMiD/Presences#6526]
### Steps to Reproduce

First you need to add the presence of the "Genius" site in the program store. Then go to this website and open any song lyrics. The Discord status will indicate "undefined - undefined" instead of the specific name of the song.

### Expected Behavior

The Discord status will indicate specifically the name of the song, the text of which I read on the Genius website.

### Actual Behavior

Instead of a specific name, the Discord status indicates "undefined - undefined".

### Page URL

https://genius.com/Joji-glimpse-of-us-lyrics

### Screenshots

![unknown](https://user-images.githubusercontent.com/77514143/181524918-7e66ff41-02fe-482d-96ce-9551c45b4c0c.png)

### Operating System

Windows 10

### Browser and Version

Google Chrome (Desktop x64 bit) (103.0.5060.134)

**Comment by RisingSunLight42** [comment]
I'll patch that tomorrow
