### ISSUE TITLE
PlaShiki | plashiki.online

### ISSUE THREAD

**Issue by Buliway** [PreMiD/Presences#653]
**What's the name of the service?**
Ex. https://plashiki.online/ | PlaShiki

**What should the Presence display?**
1) The name of the anime in English.
2) Episode I'm watching / Maximum number of episodes

**Why do you want support for this service?**
This is the most convenient site for viewing anime in Russia. I would like to share with my friends the fact that I'm watching. You have support for yummyanime, but few people use it in Russia. I think so.

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image
https://raw.githubusercontent.com/plashiki/plashiki/master/public/img/icons/android-chrome-512x512.png

**Comment by frozaum** [comment]
you need give an 512x512, not an 32x32

**Comment by Mirazex** [comment]
website is no longer available

**Comment by fr0r** [comment]
rip
