### ISSUE TITLE
Jut.su | Presence broken

### ISSUE THREAD

**Issue by alexbcberio** [PreMiD/Presences#6569]
### Steps to Reproduce

1. Add the presence from [the store](https://premid.app/store/presences/jut.su)
2. Go to the [website](https://jut.su/)
3. Presence does not show up on the Discord profile

### Expected Behavior

Presence should be set on the profile

### Actual Behavior

Presence does not show up on the profile

### Page URL

https://jut.su/

### Screenshots

![image](https://user-images.githubusercontent.com/22194879/182032711-a1fbdbfc-fa54-40bd-a724-c0a51b8f50a4.png)

Note: the warning "VM547:6773 crbug/1173575, non-JS module files deprecated." is reported even with the presence disabled.

### Operating System

Windows 10

### Browser and Version

Brave 1.41.100

### Additional Comments

The browser console does not report any errors related with the presence

**Comment by alexbcberio** [comment]
@yokkkoso, as the creator of the presence. Could you check up what's happening?

The presence is not being shown up, when I changed the application ID and set a valid image key it showed up.

**Comment by RisingSunLight42** [comment]
Since it's probably due to a deletion of the app in their developer portal, I'll wait few days to let them respond before patching it if not responded.

**Comment by yokkkoso** [comment]
> @yokkkoso, as the creator of the presence. Could you check up what's happening?
> 
> The presence is not being shown up, when I changed the application ID and set a valid image key it showed up.

Hi, my previous Discord account, on which the application was, was deleted due to ToS, I don’t have time to do PreMiD at the moment, so you can take ownership

**Comment by DarkVillager** [comment]
> > @yokkkoso, as the creator of the presence. Could you check up what's happening?
> > The presence is not being shown up, when I changed the application ID and set a valid image key it showed up.
> 
> Hi, my previous Discord account, on which the application was, was deleted due to ToS, I don’t have time to do PreMiD at the moment, so you can take ownership

Thanks for letting me know
