### ISSUE TITLE
animepahe presence causes massive lag

### ISSUE THREAD

**Issue by IcedShake** [PreMiD/Presences#6584]
### Steps to Reproduce

1. Watch any episode, let it sit for at least 10 minutes.
2. It starts to lag, noticeable by going in/out of full screen, trying to change episodes and quality.

### Expected Behavior

Nothing to barely noticeable lag

### Actual Behavior

Presence.getStrings gets called multiple times

### Page URL

URL changes every once in a while; unable to provide

### Screenshots

![Profiler](https://user-images.githubusercontent.com/81792933/182439213-efca2e62-ffc0-4438-a973-5a58b99383b7.png)
![devHelper.js](https://user-images.githubusercontent.com/81792933/182439518-67b6ec3d-c29f-4b51-b49b-9e36020c8814.png)

### Operating System

Windows 10

### Browser and Version

Chrome 103.0.5060.134 (Official Build) (64-bit)

**Comment by RisingSunLight42** [comment]
I've checked the code, looks like the the old and new lang a not stored to avoid useless refresh, causing the presence calling getStrings() every time the presence is refreshing.
I will work on a patch for that in next hours.

**Comment by RisingSunLight42** [comment]
Should be fixed in one or two days, just the time for the PR to be reviewed
