### ISSUE TITLE
Variable RPC Images?

### ISSUE THREAD

**Issue by karimawii** [PreMiD/Presences#6585]
### Presence name

AniMixPlay

### Description

I believe that Discord now supports RPC images via url, you can see an application of that in maximmax42's [Discord-CustomRP](https://github.com/maximmax42/Discord-CustomRP) where you can use an image url (including GIFs) to immediately change the RPC assets without uploading anything to the App's assets on the developer portal, I can see how this could be useful in Anime sites RPC to get the anime poster from the website nad add it to the RPC instead of just using the site's logo.

**Comment by RisingSunLight42** [comment]
So you want that AniMixPlay has the cover of the anime currently playing ?

**Comment by RisingSunLight42** [comment]
Because I can do that quite easily, but your issue title doesn't meet requirements...

**Comment by RisingSunLight42** [comment]
> Yeah, that's exactly what I mean, sorry for the title thing, I don't get what requirements you mean, but I appreciate the quick response and it would be amazing if you could add the covers as the "LargeImageKey"

The issues name should containt the website which need the new feature. I'll see to add it in the next hours after my break ^^

**Comment by RisingSunLight42** [comment]
> Yeah, that's exactly what I mean, sorry for the title thing, I don't get what requirements you mean, but I appreciate the quick response and it would be amazing if you could add the covers as the "LargeImageKey"

Sadly, there's no cover displayed when you're on an episode page, but I can display it when you're on the anime page with its informations.

**Comment by RisingSunLight42** [comment]
I'm going to investigate that to see if it's possible

**Comment by RisingSunLight42** [comment]
It seems not possible since it needs specific oauth and the token to access needs to be refreshed, that is difficult to implement (maybe impossible), with the actual structure of Premid.
I don't know if someone like @EncryptedDev can help to respond, but to be concise, the API need a bearer token that has short lifetime (1 month) and seems to be granted per user. The doc of the API is quite nebulous...

**Comment by joerkig** [comment]
> It seems not possible since it needs specific oauth and the token to access needs to be refreshed, that is difficult to implement (maybe impossible), with the actual structure of Premid. I don't know if someone like @EncryptedDev can help to respond, but to be concise, the API need a bearer token that has short lifetime (1 month) and seems to be granted per user. The doc of the API is quite nebulous...

Before doing api stuff have you tried the meta og:image below <head> to try and get it?

**Comment by RisingSunLight42** [comment]
Oh jeez, I'm SO dumb, I didn't think of the metadata image.

**Comment by RisingSunLight42** [comment]
So NOW, it is done, sorry for useless chat, I didn't think at all about the metadatas... Thanks again joerking, and sorry Encrypted for the disturbance by pinging you and, finally, thanks karimawii for your quick answers and your patience !

**Comment by RisingSunLight42** [comment]
No need to close the issue, the PR will close it anyways
