### ISSUE TITLE
Facebook Watch won't show up if I'm visiting a page with a Facebook Watch Page's UI

### ISSUE THREAD

**Issue by PhilMinecraft** [PreMiD/Presences#6588]
### Steps to Reproduce

1. on Facebook Watch feed, tap any creator's Page

### Expected Behavior

Should display "Watch - Viewing Sassa Gurl's Page"

### Actual Behavior

Displaying the page I've previous been

### Page URL

https://www.facebook.com/watch/Sassagurl/ (any Page with a 'watch/' URL alongside to their username)

### Screenshots

![image](https://user-images.githubusercontent.com/67897800/182580513-db916ff2-885b-4e84-9936-d0c0bf9eea70.png)
![image](https://user-images.githubusercontent.com/67897800/182580544-dfe57a4b-22b1-46d4-aa49-f90f980e97fe.png)
![image](https://user-images.githubusercontent.com/67897800/182580890-a1112ea2-08ba-4c65-8f40-53602ae92b0a.png)

### Operating System

Windows 7

### Browser and Version

103.0.1264.77 (Opisyal na build) (64-bit)

**Comment by RisingSunLight42** [comment]
Could you give link of these pages to help debugging?
Also, looks like by your first status that it could be a conflict with another RPC, try to test with only the tab which cause the bug opened

**Comment by RisingSunLight42** [comment]
Bug understood, the presence doesn't cover when you're viewing a watch user page.

**Comment by RisingSunLight42** [comment]
Will be patched when my PR will be merged, the presence was not handling the case of someone viewing the page of a Facebook Watch user.

**Comment by PhilMinecraft** [comment]
> Looks like by your first status that it could be a conflict with another RPC, try to test with only the tab which cause the bug opened

![image](https://user-images.githubusercontent.com/67897800/182827357-a0de340f-a603-40ee-a81f-55a57e63b5e5.png)

**Comment by RisingSunLight42** [comment]
> > Looks like by your first status that it could be a conflict with another RPC, try to test with only the tab which cause the bug opened
> 
> ![image](https://user-images.githubusercontent.com/67897800/182827357-a0de340f-a603-40ee-a81f-55a57e63b5e5.png)
> 

That's fine, I found the issue, this will be patched soon

**Comment by PhilMinecraft** [comment]
thank you so much! I found that this GitHub to be much useful than on your Discord server <3 :D

**Comment by PhilMinecraft** [comment]
it fixed
![image](https://user-images.githubusercontent.com/67897800/183240909-55af493f-ddb7-4225-ab32-fe492bb220b0.png)

but it still got some bugs including on my Page
![image](https://user-images.githubusercontent.com/67897800/183240898-24b78c47-302d-47ff-be3b-51d909d3b932.png)

**Comment by RisingSunLight42** [comment]
This new issue has been reported in #6606
