### ISSUE TITLE
WhatsApp | web.whatsapp.com

### ISSUE THREAD

**Issue by mihaiofficialRO** [PreMiD/Presences#6591]
### Steps to Reproduce

1. Go to [this link](web.whatsapp.com)
2. Check Discord Activity
3. It will show only the logo itself, and the text of whatsapp (nothing more...)

### Expected Behavior

Show full information (with privacy mode by default...)

### Actual Behavior

WhatsApp logo, and the text itself

### Page URL

https://web.whatsapp.com/

### Screenshots

https://prnt.sc/ByHegLDpN3Rt

### Operating System

Windows 10

### Browser and Version

Brave: Version 1.42.86 Chromium: 104.0.5112.81 (Official Build) (64-bit)

**Comment by DarkVillager** [comment]
Can reproduce. Will be working on a fix.
