### ISSUE TITLE
FMovies 

### ISSUE THREAD

**Issue by sevenaltered** [PreMiD/Presences#6596]
### Steps to Reproduce

1) Add the presence 2) turn on everything needed to get the presence working 3) check discord to see if presence is shown 4) presence is not shown 

### Expected Behavior

a presence labelled FMovies to appear on discord status

### Actual Behavior

nothing appears  

### Page URL

discord

### Operating System

windows 11

### Browser and Version

Chrome latest version

**Comment by RisingSunLight42** [comment]
I'll investigate this asap

**Comment by RisingSunLight42** [comment]
Works totally fine for me (even if I'm using a VPN to access the website and it is completely broken). Did you go on another URL than `fmovies.to` ? This is the only one supported by the presence, since it's the only flagged as official.

**Comment by RisingSunLight42** [comment]
@EncryptedDev you can close the issue since the actual presence is working fine on its URL.
