### ISSUE TITLE
Allow Hiding Buttons in Soundcloud Presence

### ISSUE THREAD

**Issue by snoweyfoxx** [PreMiD/Presences#6611]
### Presence name

Soundcloud

### Description

I would like to have the setting to disable the Listen Along button on Souncloud, as I listen to tracks that are private links that I don't necessarily want to have to disable the presence to hide every time.

### Additional context

![image](https://user-images.githubusercontent.com/56901798/183263480-01d069de-2af8-481e-a309-4d020c5926cd.png)
This is the button I want to be able to disable.

**Comment by RisingSunLight42** [comment]
I'll had that tomorrow
