### ISSUE TITLE
Apple Music Rich presence Discord

### ISSUE THREAD

**Issue by seventhsoul14** [PreMiD/Presences#6613]
### Steps to Reproduce

1. Apply Presence from store
2. Start playing song at https://music.Apple.com
3. Then look at status on discord

### Expected Behavior

I expected the playback time to be accurate

### Actual Behavior

Time would be off and usually jump to 6mins

### Page URL

https://music.Apple.com

### Screenshots

They’re on my pc will report later

### Operating System

Windows 10

### Browser and Version

Latest on Microsoft edge

**Comment by RisingSunLight42** [comment]
Works totally fine for me. Could you send your screenshots ?

**Comment by DarkVillager** [comment]
> Works totally fine for me. Could you send your screenshots ?

Same here

**Comment by EncryptedDev** [comment]
Seems like this is not a presence issue and instead I'd recommend you to reach out to support on our [Discord](https://discord.gg/premid).
