### ISSUE TITLE
Dizilla | dizilla.eu to dizilla5.com

### ISSUE THREAD

**Issue by Circir1337** [PreMiD/Presences#6625]
### Steps to Reproduce

1. Go to dizilla5.com
2. Change dizilla.eu to dizilla5.com

### Expected Behavior

I expected the Presence to be working.

### Actual Behavior

Currently presence doesnt working

### Page URL

https://dizilla5.com

### Operating System

Windows 10

### Browser and Version

Brave - 104.0.5112.81

**Comment by RisingSunLight42** [comment]
Bug located, will patch it

**Comment by RisingSunLight42** [comment]
Sadly the presence has bugs when we change the URL, and I can't understand the language, so I can't help.

**Comment by Circir1337** [comment]
I know the language, share problem on here so i can help.

RisingSunLight ***@***.***>, 10 Ağu 2022 Çar, 10:58 tarihinde
şunu yazdı:

**Comment by DarkVillager** [comment]
> I know the language, share problem on here so i can help. RisingSunLight ***@***.***>, 10 Ağu 2022 Çar, 10:58 tarihinde şunu yazdı:
> […](#)

Whats your discord? We can do this together. Or add mine  @Dark_Ville#2756
