### ISSUE TITLE
VLC Presence

### ISSUE THREAD

**Issue by Adrian400811** [PreMiD/Presences#6632]
### Steps to Reproduce

1. Add artist or album in metadata
2. Play media

### Expected Behavior

Title displaying on the first row, other information (e.g. artist name, album and track number) displaying on the second row

### Actual Behavior

Title being covered by track number and album name, artist name displaying normally

### Page URL

localhost:8080 (as requested in presence document)

### Screenshots

Metadata in the media
![image](https://user-images.githubusercontent.com/59413622/183931758-7ac5ba15-0ec7-4902-9dec-913281f6ffd2.png)

Presence when nothing is in metadata
![image](https://user-images.githubusercontent.com/59413622/183936053-b1692995-a894-446e-a10a-463d2dd08e1c.png)

Presence with only artist in metadata
![image](https://user-images.githubusercontent.com/59413622/183932076-710737fa-d202-41cf-bc1c-b359991c4eb9.png)

Presence with only album in metadata
![image](https://user-images.githubusercontent.com/59413622/183935601-8ca84a08-1e48-47f4-b814-fe4563846662.png)

Presence with both artist and album in metadata
![image](https://user-images.githubusercontent.com/59413622/183935108-da8440c5-e054-4576-b713-77d74ba82e0f.png)

### Operating System

Linux 5.18.16-200.fc36.x86_64 Fedora 36 Workstation

### Browser and Version

Firefox 103.0.1

### Additional Comments

I hope there is options to let user choose what is being displayed on the presence

**Comment by RisingSunLight42** [comment]
@Adrian400811 for the options to let user choose, please open a feature request.
