### ISSUE TITLE
dアニメストア

### ISSUE THREAD

**Issue by Bas950** [PreMiD/Presences#6633]
### Steps to Reproduce

I think it's using their old url in metadata.

Also if anyone is going to work on this, add altnames:
1. Docomo Anime Store
2. dAnime
3. dmkt

### Expected Behavior

Working

### Actual Behavior

Not working

### Page URL

https://animestore.docomo.ne.jp/

### Operating System

Windows 11

### Browser and Version

Edge

**Comment by Bas950** [comment]
@DarkVillager @RisingSunLight42 could one of you maybe look at this one, it might be as simple as changing the url in metadata. Not sure tho xD

**Comment by RisingSunLight42** [comment]
> @DarkVillager @RisingSunLight42 could one of you maybe look at this one, it might be as simple as changing the url in metadata. Not sure tho xD

Yeah, I've already tried, but I can't check if everything is working well since the part handled by the presence is behind a paywall ^^

**Comment by RisingSunLight42** [comment]
@eai04191 could you patch this presence since you're the owner. Since everything is in japanese and behind a paywall, I can't really check if the presence is working after the changes...

**Comment by eai04191** [comment]
As you know it is a paid service and I am no longer subscribing to it. So I can't maintain this. I'm sorry.
If only the URL has changed, the script is very simple, so I believe that it is a problem that can be easily fixed by people who can use rudimentary JavaScript, but the most difficult thing is to find people who are still using it.

**Comment by RisingSunLight42** [comment]
> ~~As you know it is a paid service and I am no longer subscribing to it. So I can't maintain this. I'm sorry.~~
> If only the URL has changed, the script is very simple, so I believe that it is a problem that can be easily fixed by people who can use rudimentary JavaScript, but the most difficult thing is to find people who are still using it.
> 
> UPDATE: I found a [sample video that can be viewed even if I am not a paid member](https://animestore.docomo.ne.jp/animestore/sc_d_pc?partId=10463999), so I am working on fixing it.

Oh perfect! Since I don't understand Japanese, I couldn't find this video, good luck for the update of the presence!

**Comment by Isa27-0** [comment]
I think can now close this Issue, it is resolved (#6967). ~Unless request to add altnames is being considered.~

**Comment by neco222** [comment]
I submitted a request to change the URL once. I don't know if it's been accepted, but if it is, it's not working

The current d anime store link is below
animestore.docomo.ne.jp

**Comment by neco222** [comment]
It is still unusable, but is it being fixed?
