### ISSUE TITLE
PreMiD not working with new crunchyroll Beta

### ISSUE THREAD

**Issue by Bkwarner0** [PreMiD/Presences#6635]
### Presence name

Crunchyroll

### Description

PreMiD works correctly with www.crunchyroll.com but does not work with https://beta.crunchyroll.com/

When using the beta version, the activity of crunchyroll pops up on discord but is stuck on browsing. Does not show what show you are watching, episode, timestamps, etc. All US users are forced to watch on the beta site and cannot watch from the regular site unless they are logged out of their crunchyroll account.

Thank you!

**Comment by RisingSunLight42** [comment]
I'll handle it !
