### ISSUE TITLE
Windows 11 update breaks PreMid

### ISSUE THREAD

**Issue by phamduyphat** [PreMiD/Presences#6646]
### Steps to Reproduce

1. Install discord and Premid and PreMID extension
2. Verify that presences is still working
3. Update Windows (Cumulative Update for Windows 11 for x64-based Systems (KB5016629))
4. No presences appears on discord

### Expected Behavior

presences works

### Actual Behavior

No presences appears on discord

### Page URL

youtube.com

### Operating System

Windows 11

### Browser and Version

1.42.88 Chromium: 104.0.5112.81 (Official Build) (64-bit) 

### Additional Comments

Temp fix: Reinstall PreMID app

**Comment by EncryptedDev** [comment]
This is a poor bug report. I cannot decipher whether you're saying the YouTube presence isn't working and/or your PreMiD generally isn't working. 

In the case PreMiD isn't working (wholly or just a few presences), contact support using our Community [Discord](https://discord.gg/premid).
