### ISSUE TITLE
PreMid

### ISSUE THREAD

**Issue by Plasma6** [PreMiD/Presences#6662]
### Steps to Reproduce

https://premid.app/

### Expected Behavior

My Crunchyroll to display with episode/time

### Actual Behavior

Only showed I was browsing as long as crunchyroll was open

### Page URL

The discord app status display

### Screenshots

![image](https://user-images.githubusercontent.com/111239227/184545167-b0e44171-bf1b-42c4-a2d8-641e70701764.png)

### Operating System

Windows 10

### Browser and Version

Google

### Additional Comments

No clue why this started happening but it also happens both google browser and firefox browser
2 weeks-1 month ago this 1st occured

**Comment by RisingSunLight42** [comment]
@Plasma6 are you using the beta version? If yes, this problem is known and a patch will be released soon
