### ISSUE TITLE
Add Manga Covers To LargeImageKey

### ISSUE THREAD

**Issue by karimawii** [PreMiD/Presences#6664]
### Presence name

MangaDex

### Description

Add option to toggle covers for the presence, and to show the manga cover when reading a chapter or viewing its page
`og:image` property can be used to implement that

Example:
```html
<meta property="og:image" content="https://og.mangadex.org/og-image/chapter/d98c8a69-aca4-4c34-a802-e77ea37a2a96">
```
Image:

![Image](https://og.mangadex.org/og-image/chapter/d98c8a69-aca4-4c34-a802-e77ea37a2a96)

You just need the left part (which is the cover), so that will need to be cropped to fit the square window of the Discord RPC

**Comment by RisingSunLight42** [comment]
I'll work on that tonight

**Comment by RisingSunLight42** [comment]
Unfortunately, we can't crop to match the cover since it's a source link.

**Comment by RisingSunLight42** [comment]
> > Unfortunately, we can't crop to match the cover since it's a source link.
> 
> you can't save it somewhere and call it back?

Nah, if we want to display the image cropped, we should get the image from the source link, manage to crop it, save it somewhere and get the link to give it to Discord.
