### ISSUE TITLE
Use file metadata or choose an image to be displayed instead of the VLC logo.

### ISSUE THREAD

**Issue by Sammie0210** [PreMiD/Presences#6671]
### Presence name

VLC

### Description

Use an image that exists on the file's metadata (if any) to be displayed instead of the usual VLC logo. If its not possible to use metadata image, user can assign image of choosing instead. Displaying a square images like what they have on Netflix's presence and other streaming sites. 
![Screenshot (1263)](https://user-images.githubusercontent.com/111458664/185227982-7cf39835-86c1-42e6-b049-395e5dfed7b1.png)
![Screenshot (1265)](https://user-images.githubusercontent.com/111458664/185228219-5a5c1785-b275-4f1b-9a0c-45bb2a592469.png)

### Alternatives

Since metadata file may contain images that varied in sizes and aspect ratio. The image that would be displayed as for this request should follow the 2x2, 4x4 inches or any equal proportion in terms of aspect ration as they were automatically be displayed as a square icon on the left side on the presence
![Screenshot (1260)](https://user-images.githubusercontent.com/111458664/185227390-ffadfe75-1304-48ba-8c6c-607312b8f945.png)

**Comment by RisingSunLight42** [comment]
Poke @EncryptedDev 
Cannot be done, file stored locally. No links available to display the cover as a largeImageKey.
