### ISSUE TITLE
YouTube | Showing wrong channel name

### ISSUE THREAD

**Issue by H0shizora** [PreMiD/Presences#6678]
### Steps to Reproduce

1.Open youtube
2,Open any youtube video

### Expected Behavior

Showing the channel I watching

### Actual Behavior

Showing the channel that I am not watching

### Page URL

https://www.youtube.com/

### Screenshots

![1](https://user-images.githubusercontent.com/111439780/185739458-6c69faa2-49db-40a2-aa8c-d5eefa07bd36.png)
![2](https://user-images.githubusercontent.com/111439780/185739459-ee01d2f1-7f53-4b96-bf64-ef64a1c83a9a.png)

### Operating System

Windows 10

### Browser and Version

Chrome Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by RisingSunLight42** [comment]
Edit the name of the issue please.

**Comment by H0shizora** [comment]
Done.

**Comment by Ghosty2004** [comment]
The author of this **YouTube Presence** can use this code to retrieve the channel name:

```js
const channelOwnerInfo = document.getElementsByTagName("ytd-video-owner-renderer")[0];
const uploadInfo = channelOwnerInfo.querySelectorAll("#text > a")[0];
console.log(uploadInfo.innerText);
```

**Comment by RisingSunLight42** [comment]
> The author of this **YouTube Presence** can use this code to retrieve the channel name:
> 
> ```js
> const channelOwnerInfo = document.getElementsByTagName("ytd-video-owner-renderer")[0];
> const title = channelOwnerInfo.querySelectorAll("#text > a")[0];
> console.log(title); // just to debug
> ```

This is already done in the presence in a similar way. Seems to be something weird from YouTube.

**Comment by callumok2004** [comment]
I have seen this issue reproduced by several people, definitely a bug.

**Comment by DarkVillager** [comment]
> I have seen this issue reproduced by several people, definitely a bug.

Yup

**Comment by RisingSunLight42** [comment]
I've tried to repro it in dev, but obviously I didn't reach it since it looks like this bug is quite random.

**Comment by DarkVillager** [comment]
### **Steps to Reproduce**

1. Open a youtube livestream. (e.g. [https://www.youtube.com/watch?v=7tNtU5XFwrU](https://www.youtube.com/watch?v=7tNtU5XFwrU))
2. 
Possible Option (1) - View the stream and observe this behaviour.
Possible Option (2) - Close the livestream and go to a video and observe this behaviour.

**Comment by DarkVillager** [comment]
Reproduce steps (* is optional):

1- Open a youtube video E.g. [https://www.youtube.com/watch?v=4BWOHnQDfxk](https://www.youtube.com/watch?v=4BWOHnQDfxk)
2- Make sure autoplay is enabled
3- Go to the video and skip to the end untill auto play starts counting down from 8 
4- Then scroll down and open a livestream/video thats showed on the side (That you haven't opened before, this bug only appears once or twice) In my case [https://www.youtube.com/watch?v=YZHaor7AE4s](https://www.youtube.com/watch?v=YZHaor7AE4s) 
![image](https://user-images.githubusercontent.com/42322979/185912737-d3b3be09-1e12-4d22-8222-79e0c353a155.png)
5- Observe the behaviour
