### ISSUE TITLE
Discord | DM Username showing as "Undefined"

### ISSUE THREAD

**Issue by callumok2004** [PreMiD/Presences#6684]
### Steps to Reproduce

Use the discord presence for premid and try viewing a DM, notice the users name shows as "undefined".

### Expected Behavior

It should give the name of the user

### Actual Behavior

It shows undefined

### Page URL

Any DM

### Operating System

Windows 11.

### Browser and Version

All browsers.

### Additional Comments

Can be reproduced by several people.

**Comment by DarkVillager** [comment]
Can reproduce.

**Comment by EncryptedDev** [comment]
@RisingSunLight42, can you look into this possibly?

**Comment by RisingSunLight42** [comment]
> @RisingSunLight42, can you look into this possibly? 

Yup, I'll check that when I have the time

**Comment by RisingSunLight42** [comment]
Currently working on it, can't repro on my side so it's maybe more complicated than it looks. I'm currently seeing with DarkVillager to find the source of the problem !
