### ISSUE TITLE
Show / Movie Title

### ISSUE THREAD

**Issue by buddy-codes** [PreMiD/Presences#6687]
### Presence name

Soap2Day

### Description

 Instead of the presence showing Relaxing to some TV, or watching a movie of some sorts. Make it actually show the TV show, or the movie name, or the sport name, etc. You can make it an option within the settings.

### Additional context

![image](https://user-images.githubusercontent.com/55510116/185943330-6598e69a-eaf4-4f8d-ac83-5de714cdd18b.png)

**Comment by RisingSunLight42** [comment]
Bad reference 👆, sorry
but I'll work on this feature.

**Comment by buddy-codes** [comment]
alright thanks!

I tried looking at soap2day, but the show title does not have a class. If it did i would have gladly helped.

**Comment by RisingSunLight42** [comment]
> alright thanks!
> 
> I tried looking at soap2day, but the show title does not have a class. If it did i would have gladly helped.

I will find a way ^^

**Comment by buddy-codes** [comment]
epic!

**Comment by RisingSunLight42** [comment]
Done, waiting now to be reviewed and merged.
