### ISSUE TITLE
Replit Presence Privacy

### ISSUE THREAD

**Issue by buddy-codes** [PreMiD/Presences#6689]
### Presence name

Replit

### Description

With the replit extension, I have realized that there is no privacy for Private repls! I'd like to see this feature come soon!

### Additional context

Currently, if you are editing a private repl it shows on your status. It should say "Editing a private repl." or have a privacy option! Hope this gets resolved.

**Comment by DaInfLoop** [comment]
There is a way to fix this that I can think of - however it requires having to have a library allowing to execute web requests. Does PreMiD have any libraries that I can use to fix this?

**Comment by buddy-codes** [comment]
well, @DaInfLoop you can possibly check this "Private" element and check if the bg color = the active color. 
![image](https://user-images.githubusercontent.com/55510116/185986044-dd2c66ff-7d69-4df0-a897-b5af3fea7077.png)

**Comment by DaInfLoop** [comment]
> well, @DaInfLoop you can possibly check this "Private" element and check if the bg color = the active color. ![image](https://user-images.githubusercontent.com/55510116/185986044-dd2c66ff-7d69-4df0-a897-b5af3fea7077.png)

Unfortunately Replit deletes that element when it's out of view - so when the menu bar isn't active there isn't any way to check that

**Comment by RisingSunLight42** [comment]
PreMiD can make web requests with `fetch()`.
But I will search for something else before using anything that need a web request, since It cost some resources and can slow navigator if badly executed.
Since you're talking about web requests, is there an API or something? I'll be thankful to you if you can link it.

**Comment by DaInfLoop** [comment]
> PreMiD can make web requests with `fetch()`. But I will search for something else before using anything that need a web request, since It cost some resources and can slow navigator if badly executed. Since you're talking about web requests, is there an API or something? I'll be thankful to you if you can link it.

Replit has a GraphQL API - the schema is private but I know some of the queries from looking at the Network tab in Devtools.

**Comment by RisingSunLight42** [comment]
I will work on it tomorrow.

**Comment by RisingSunLight42** [comment]
Well... Private repo are behind a paywall, I can't access it.

**Comment by DaInfLoop** [comment]
I have Hacker plan fortunately - I can help test it for you if you'd like.

**Comment by RisingSunLight42** [comment]
> I have Hacker plan fortunately - I can help test it for you if you'd like.

If you can work on it by yourself, feel free to do it.
If not, just check if there's something that show private that is in the page.
Also for the thing that is "public/private"  below,  is it really deleted from the DOM? Or just not displayed? Because if it's not displayed, we can fetch it..

**Comment by buddy-codes** [comment]
I also have the "Hacker Plan" I could help too. (dainfloop is a friend of mine).

**Comment by buddy-codes** [comment]
I don't think it's deleted from the DOM. I'll check.

**Comment by buddy-codes** [comment]
@RisingSunLight42 i think i got the code ready! i'll make a pr!

**Comment by RisingSunLight42** [comment]
No need to close it, wait for the PR to be approved
