### ISSUE TITLE
Presence for NameMC

### ISSUE THREAD

**Issue by InfoBlock** [PreMiD/Presences#6698]
### Steps to Reproduce

1. Get the NameMC Presence
2. Activate it

### Expected Behavior

Presence shows on Discord

### Actual Behavior

Nothing shows up

### Page URL

https://namemc.com

### Screenshots

https://i.imgur.com/MEcJ7nf.png

### Operating System

Windows 10 64-bit

### Browser and Version

Opera GX, LVL4 (core: 89.0.4447.104)

**Comment by RisingSunLight42** [comment]
I will check that when I can

**Comment by RisingSunLight42** [comment]
Everything works fine for me, does an error is thrown in your browser console ? The other presences are working ?

**Comment by InfoBlock** [comment]
Other presences working, no browser console errors by PreMiD

**Comment by RisingSunLight42** [comment]
> Other presences working, no browser console errors by PreMiD

Could you give the link of the websites? Maybe you go to a part unsupported.

**Comment by InfoBlock** [comment]
https://namemc.com/

**Comment by RisingSunLight42** [comment]
Well, I don't know, everything is working fine for me :/

**Comment by InfoBlock** [comment]
> Well, I don't know, everything is working fine for me :/

Well thats weird.. NameMC is the only presence having trouble for me rn

**Comment by DarkVillager** [comment]
> > Well, I don't know, everything is working fine for me :/
> 
> Well thats weird.. NameMC is the only presence having trouble for me rn

Have you tried uninstalling & reinstalling the presence?

**Comment by InfoBlock** [comment]
Yes, didn't fix the issue.

**Comment by theusaf** [comment]
If you wait a long time, does the presence eventually show up?

**Comment by InfoBlock** [comment]
Negative, even after waiting ~10 minutes nothing happens

**Comment by RisingSunLight42** [comment]
Maybe try on supported browser like Chrome

**Comment by InfoBlock** [comment]
I'm using Opera which is supported, only the NameMC Presence is making trouble

**Comment by EncryptedDev** [comment]
Closing this issue as it works for me and RisingSunLight42 & doubt it is a presence-related issue because there are no errors visible in console. 

You should open a support ticket for this to be resolved as it is a individual issue
