### ISSUE TITLE
Animes Vision | www.animesvision.com.br

### ISSUE THREAD

**Issue by khyrius** [PreMiD/Presences#671]
**What's the name of the service?**
https://www.animesvision.com.br/ | Animes Vision

**What should the Presence display?**
Anime that is currently playing, searching and home page (i think its enough)

**Why do you want support for this service?**
Because i think there is only 2 anime websites that supports Brazil (crunchyroll and superanimes) and since superanimes have really bad quality and crunchyroll keeps loading forever i think it will be a good idea cause animesvision provide a good quality (HD+) and the interface is pretty clean.

**Are you able to provide an image for the service? (512x512 minimum)**
I cant since the only logo website has is something like "animesvision free hq animes" etc

**Comment by maz1no** [comment]
Besides Crunchyroll and SuperAnimes, also has Animes Online, Branitube, Dream Animes, Goyabu, Yay Animes and Punch Fansub. You didn't look well. I'm brazilian too.

**Comment by khyrius** [comment]
> Besides Crunchyroll and SuperAnimes, also has Animes Online, Branitube, Dream Animes, Goyabu, Yay Animes and Punch Fansub. You didn't look well. I'm brazilian too.

yeah ur right, but still.. animevision has the best quality imo

**Comment by frozaum** [comment]
added #1342
