### ISSUE TITLE
India Today News

### ISSUE THREAD

**Issue by IceyWolf17** [PreMiD/Presences#6731]

**Comment by RisingSunLight42** [comment]
Change issue title with the name of the website please

**Comment by RisingSunLight42** [comment]
Also, you've used the wrong template.

**Comment by IceyWolf17** [comment]
> Also, you've used the wrong template.

What template was i supposed to use? I changed the issue title to the presence name.

**Comment by RisingSunLight42** [comment]
> > Also, you've used the wrong template.
> 
> What template was i supposed to use? I changed the issue title to the presence name.

The service request one, not the feature

**Comment by IceyWolf17** [comment]
> 

https://github.com/PreMiD/Presences/issues/6743#issue-1360273068

**Comment by RisingSunLight42** [comment]
@EncryptedDev could you close this one?

**Comment by DiscordAnaxes** [comment]
Currently working on this 👍
