### ISSUE TITLE
Presence for territorial.io

### ISSUE THREAD

**Issue by redtrillix** [PreMiD/Presences#6733]
### Website name

territorial.io

### Website URL

https://territorial.io/

### Website logo

https://i.imgur.com/RLJLePH.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Having a button to join the game (link to the home page or something similar).
It would also be cool to show some statistics on the game being played like singleplayer and multiplayer and maybe stuff like how much players are left, but i'm not sure if that's possible.

Description of game: Territorial.io is a strategy io game where players fight to expand their nations. Defend your territory, expand, and conquer the map in games of up to 500 players.

**Comment by DarkVillager** [comment]
I will take this one. Will let you know when im done.
