### ISSUE TITLE
NationStates | nationstates.net

### ISSUE THREAD

**Issue by SleetApp** [PreMiD/Presences#6735]
### Website name

NationStates

### Website URL

https://nationstates.net

### Website logo

https://www.saashub.com/nationstates-status

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

What nations, regions or worlds am I watching/interacting with, and also when dealing with issues.
With a button that leads to that nation they are looking at

**Comment by DarkVillager** [comment]
Will be resolved by #6634
