### ISSUE TITLE
Animu Radio Station | animu.com.br

### ISSUE THREAD

**Issue by FZero7** [PreMiD/Presences#674]
What's the name of the service?
www.animu.com.br | Animu FM - The most moe radio of Brazil

What should the Presence display?
information about current music and time duration, preference by use metadata from Icecast

Why do you want support for this service?
Animu is a webradio with awesome quality streaming and focused on moe anime musics and idols. Some listeners have talked about make a issue to put on PreMID Rpc
Are you able to provide an image for the service? (512x512 minimum)
![Icon_A_512](https://user-images.githubusercontent.com/38415943/69471454-c7a87300-0d7d-11ea-9e1a-eb0a93184c45.png)

**Comment by frozaum** [comment]
Olá, eu acho que vou cuidar disto.
