### ISSUE TITLE
아프리카TV, kakaoTV & SPOTV | afreecatv.com, tv.kakao.com & www.e-sportstv.net

### ISSUE THREAD

**Issue by matiplx** [PreMiD/Presences#675]
**What's the name of the service?**
http://afreecatv.com/#/home#menu | Afreecatv (you need chose in website Korean Langue) 
https://tv.kakao.com/ |KakoTV
http://www.e-sportstv.net/onair/onair_01.asp?MENU_CODE=01 | SPO E-Sport TV

**What should the Presence display?**
Informations about the current stream and browsing website 
Information about the current stream and browsing website 
Information about watching stream

**Why do you want support for this service?**
Afreecatv.com and Kakaotv is big Korean stream websites like Twitch. SPO E-sport TV is online television about E-Sport games. 

**Are you able to provide an image for the service? (512x512 minimum)**
https://media.glassdoor.com/sqls/2455618/afreecatv-squarelogo-1549924033785.png
https://static.tvmaze.com/uploads/images/large_landscape/173/432693.jpg
http://file.bodnara.co.kr/webedit/news/2014/1429235949-sum1.jpg

**Comment by Bas950** [comment]
@matiplx Are you korean yourself?
If so could you help us get PreMiD 100% translated in korean?

**Comment by Bas950** [comment]
Also I will do this website probs this week, just like:
mnet/mwave
kocowa
naver

**Comment by matiplx** [comment]
@Bas950 I'm so sorry I'm not Korean, but would love to see this website on presence and your site of course too :)
