### ISSUE TITLE
Youtube | Videos > 24 hours do not show days in "Remaining Time"

### ISSUE THREAD

**Issue by callumok2004** [PreMiD/Presences#6770]
### Steps to Reproduce

An example video you can see this on is https://www.youtube.com/watch?v=VPvVD8t02U8

### Expected Behavior

It should show 1:22:33:44

### Actual Behavior

It excludes the day, showing 22:33:44

### Page URL

https://www.youtube.com/watch?v=VPvVD8t02U8

### Screenshots

![zEsIkoGE58 1](https://user-images.githubusercontent.com/35779365/189196788-62db7e0c-d905-4ee4-8494-7450ed47ff94.png)

![XiveYAFA67 1](https://user-images.githubusercontent.com/35779365/189196855-a0c1e80e-1925-4e89-ba23-987bfecd9e7e.png)

### Operating System

Windows 11

### Browser and Version

All browsers.

### Additional Comments

Can be reproduced by myself and someone within a support ticket.

**Comment by xhayper** [comment]
seems to be discord fault,
when setting the end timestamp to ending in 24 hour and 2 seconds it show up as 00:00:02 left
but as soon as that 2 seconds end, it's followed up by  24:00:00

**Comment by xhayper** [comment]
Seems like discord doesn't support day as timestamp.

**Comment by xhayper** [comment]
![image](https://user-images.githubusercontent.com/46065349/189261642-e76193be-f676-4f6e-aad8-d4269e27173e.png)

**Comment by RisingSunLight42** [comment]
Yup
