### ISSUE TITLE
Ycombinator's Hacker News 

### ISSUE THREAD

**Issue by Technetium1** [PreMiD/Presences#6788]
### Presence name

Hacker News

### Description

I would like [Hacker News](https://news.ycombinator.com) to be a presence that shows what article and the source for it you're currently reading, or if you're [writing a new one](https://news.ycombinator.com/submit).

### Additional context

For example: [This article](https://news.ycombinator.com/item?id=32823436) should show `Show HN: Cachegrand – a fast OSS Key-Value store built for modern hardware`, and should (hopefully) show the link or domain for the article, either as shown on the page `github.com/danielealbano`, or as the article's [destination](https://github.com/danielealbano/cachegrand).

**Comment by DarkVillager** [comment]
@Technetium1 If this is a new presence, close the issue and create a Presence Request one.

**Comment by Technetium1** [comment]
Oops, thought that was what I clicked.

**Comment by Technetium1** [comment]
I opened `#6791`
