### ISSUE TITLE
Fandom.com presence not working

### ISSUE THREAD

**Issue by Juneybugged** [PreMiD/Presences#6798]
### Steps to Reproduce

1. Download Fandom.com presence from the presence store
2. Go to any fandom.com wiki (memory-alpha.fandom.com for example)
3. Presence should be showing site in Discord status, but it is not

### Expected Behavior

Visited website should be showing in Discord status

### Actual Behavior

Presence fails to work

### Page URL

any fandom.com wiki

### Screenshots

![image](https://user-images.githubusercontent.com/113805434/190878497-8c657764-2a8d-47c0-884c-aaeef55f3772.png)

### Operating System

Windows 11

### Browser and Version

Firefox 104.0.2 (64-bit)

### Additional Comments

Included screenshot is of the console when visiting memory-alpha.fandom.com with the presence installed

**Comment by DarkVillager** [comment]
Can't reproduce on the site. Is it a specific page @Juneybugged ?
![image](https://user-images.githubusercontent.com/42322979/190898729-6b7270ef-8065-40bd-815e-9d591158093c.png)

**Comment by EncryptedDev** [comment]
Can't repro
