### ISSUE TITLE
Serial | serialpodcast.org

### ISSUE THREAD

**Issue by BitesizedLion** [PreMiD/Presences#6808]
### Website name

Serial

### Website URL

https://SerialPodcast.org

### Website logo

https://media.wired.com/photos/59322cddaef9a462de98135a/master/w_1600%2Cc_limit/serial-logo-large.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

It would be nice if it displayed playback info such as: timestamp, season, episode, episode title

**Comment by DiscordAnaxes** [comment]
Working on this 👍

**Comment by BitesizedLion** [comment]
stale so closing
