### ISSUE TITLE
https://soap2day.rs/

### ISSUE THREAD

**Issue by Elmoscarex** [PreMiD/Presences#6810]
### Presence name

Soap2Day

### Description

I would like to see [https://soap2day.rs/](url) added to the soap2day sites

**Comment by EncryptedDev** [comment]
@RisingSunLight42, would you be able to look into this as you're a contributor to the presence?

**Comment by theusaf** [comment]
`.rs` does not appear to be an official mirror of SOAP2DAY.

**Comment by slademcg** [comment]
It is now the only working domain of soap2day, or at least it is one of the few ones that are still working
