### ISSUE TITLE
Snapchat presence's privacy mode is inverted

### ISSUE THREAD

**Issue by MaXfAa** [PreMiD/Presences#6818]
### Steps to Reproduce

I'm gonna use this text area to explain:
The privacy mode in the settings of the Snapchat presence is reversed. When you enable it, it actually becomes disabled (the chats' recipient is displayed) and when you disable it, it hides the private informations. I think this is simply a distraction error from the dev.

### Expected Behavior

Privacy mode is set to ON: no private info displayed. Privacy mode is set to OFF: private info displayed (like chats' recipient)

### Actual Behavior

Privacy mode is set to ON: private info displayed (like chats' recipient). Privacy mode is set to OFF: no private info displayed

### Page URL

https://web.snapchat.com/

### Operating System

Windows 11

### Browser and Version

Brave Version 1.45.68 Chromium: 106.0.5249.55 (Official Build) beta (64-bit)

**Comment by DarkVillager** [comment]
@N0chteil ^

**Comment by N0chteil** [comment]
Will look into this
