### ISSUE TITLE
[Youtube]Shorts

### ISSUE THREAD

**Issue by itoffie** [PreMiD/Presences#6842]
### Steps to Reproduce

1. Go to Youtube Homepage
2. Play Shorts
3. Go back to Youtube Homepage
4. Play Something in Recommendations
5. Check Premid on discord and it shows the wrong uploader

### Expected Behavior

updated the uploader

### Actual Behavior

it still uses shorts video uploader name

### Page URL

https://www.youtube.com/

### Screenshots

![image](https://user-images.githubusercontent.com/64309702/193450017-4c5e5cfa-16a2-40ea-889a-828a97aa66d7.png)
![image](https://user-images.githubusercontent.com/64309702/193450031-347ce2c0-92a6-4b4c-9a6b-6e2795c233a6.png)

### Operating System

Windows 7 64bit

### Browser and Version

Brave Browser v1.44.105

**Comment by DarkVillager** [comment]
on it rn
