### ISSUE TITLE
Merriam-Webster | www.merriam-webster.com

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [PreMiD/Presences#686]
**What's the name of the service?**
https://www.merriam-webster.com/

**What should the Presence display?**
Words that are being searched.

**Why do you want support for this service?**
To determine what words people are searching in the dictionary.

**Are you able to provide an image for the service? (512x512 minimum)**
![mw-logo 512](https://user-images.githubusercontent.com/45579671/69594029-e5f5b500-0faf-11ea-8466-49ec8404df82.png)

**Comment by frozaum** [comment]
this is not a 512x512 logo.
