### ISSUE TITLE
Presence for audible is not working on audible.fr

### ISSUE THREAD

**Issue by pierrequiroul** [PreMiD/Presences#6860]
### Steps to Reproduce

Start to listen to an audiobook on audible.fr

### Expected Behavior

Showing a status that i'm listening to an audiobook

### Actual Behavior

Nothing

### Page URL

https://www.audible.fr/

### Screenshots

![Capture d’écran 2022-10-06 215246](https://user-images.githubusercontent.com/35348696/194406177-7823f0a3-37a3-48fc-aba7-aee56615119a.png)

### Operating System

windows 11

### Browser and Version

opera gx LVL4 (core: 91.0.4516.36)

### Additional Comments

When you start to listen an audiobook, it opens a player in a popup window
The status on discord is not showing that i'm listening an audio book

**Comment by Kozou4ever** [comment]
Hello. Here's the reason why it is'nt working for you
![image](https://user-images.githubusercontent.com/72155852/199017780-35f97611-bfbc-43d8-85de-e0c8f3f5f383.png)
Basically, you need to visit this website audible.com to get the presence to perform
