### ISSUE TITLE
BibMe | www.bibme.org

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [PreMiD/Presences#687]
**What's the name of the service?**
http://www.bibme.org/ | BibMe

**What should the Presence display?**
A creating citation status. Which format it is in such as MLA, Chicago.

**Why do you want support for this service?**
To determine what people are citing to avoid getting caught with plagiarism. 

**Are you able to provide an image for the service? (512x512 minimum)**
Nope.

**Comment by frozaum** [comment]
Please provide us a logo in 512x512.

**Comment by frozaum** [comment]
Please provide us a 512x512 logo and a good reason to why we should support this service.
Invalid.

**Comment by Gurrman375** [comment]
![bibmelogo](https://user-images.githubusercontent.com/25113575/82357061-658d9b00-99b9-11ea-8822-7959b21e8f67.png)
