### ISSUE TITLE
IDLIX

### ISSUE THREAD

**Issue by ILnea** [PreMiD/Presences#6894]
### Website name

IDLIX

### Website URL

https://195.2.92.213/

### Website logo

https://195.2.92.213/wp-content/uploads/2020/07/logov4.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

its site for streaming Movies in Indonesia Language!

**Comment by DarkVillager** [comment]
On it.

**Comment by ILnea** [comment]
> On it. (80% done.)

tysm ~

**Comment by ILnea** [comment]
any info hows this project going?

**Comment by DarkVillager** [comment]
> any info hows this project going?

Give me a bit. Exams atm.

**Comment by ILnea** [comment]
> > any info hows this project going?
> 
> Give me a bit. Exams atm.

oh alright!

**Comment by DarkVillager** [comment]
@ILnea current progress is that I have done the main domain and will add other domains soon, be patient.

**Comment by DarkVillager** [comment]
@ILnea The domain issue is fixed and I just need to fix an issue with the episode title.

**Comment by ILnea** [comment]
> @ILnea The domain issue is fixed and I just need to fix an issue with the episode title.

alright! take your time~

**Comment by ILnea** [comment]
what happend?

**Comment by DarkVillager** [comment]
> what happend?

It’s currently waiting to be reviewed then it’ll be merged and added

**Comment by ILnea** [comment]
> > what happend?
> 
> It’s currently waiting to be reviewed then it’ll be merged and added

alr, thank you for your hard work~
