### ISSUE TITLE
LucidChart || https://www.lucidchart.com

### ISSUE THREAD

**Issue by OfficialNOTORIOUS7302** [PreMiD/Presences#692]
**What's the name of the service?**
https://www.lucidchart.com

**What should the Presence display?**
What document people are working on. Similar to Google Docs presence.

**Why do you want support for this service?**
To determine what others are working on the Lucid chart website.

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image

**Comment by frozaum** [comment]
Please provide us a 512x512 logo and a good reason to why we should support this service.
Invalid.
