### ISSUE TITLE
MyFlixer | myflixer.ru

### ISSUE THREAD

**Issue by ozziiiii** [PreMiD/Presences#6939]
### Website name

MyFlixer 

### Website URL

https://web.myflixer.ru/home

### Website logo

https://s1.bunnycdn.ru/assets/template_3/style_3/images/logo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

This is a movie & shows streaming free streaming service just like soap2day website, but this one is even better.

**Comment by theusaf** [comment]
Seems to be a duplicate of #5882
