### ISSUE TITLE
Crunchyroll | https://www.crunchyroll.com/

### ISSUE THREAD

**Issue by ByZorks** [PreMiD/Presences#6951]
### Steps to Reproduce

1. go to https://www.crunchyroll.com/
2. start an episode

### Expected Behavior

show anime title, episode....

### Actual Behavior

the presence just stops working, it doesn't even show on discord

### Page URL

https://www.crunchyroll.com/

### Operating System

Windows 11

### Browser and Version

Chrome 107.0.5304.88

### Additional Comments

The presence works well for all other things, but not for the episodes.

**Comment by theusaf** [comment]
This was fixed in #6916 and is a duplicate of #6925. Try removing and re-adding the Crunchyroll presence.

**Comment by ByZorks** [comment]
> This was fixed in #6916 and is a duplicate of #6925. Try removing and re-adding the Crunchyroll presence.

I did it hours ago, but it hadn't worked, now it does. Anyway, thanks!

**Comment by ByZorks** [comment]
It doesn't work anymore, removing and re-adding the presence doesn't work either. 
As soon as I start an episode, the presence stops being displayed on Discord. Moreover, afterwards it doesn't display anything until Discord and Premid have been restarted.

**Comment by theusaf** [comment]
> It doesn't work anymore, removing and re-adding the presence doesn't work either. As soon as I start an episode, the presence stops being displayed on Discord. Moreover, afterwards it doesn't display anything until Discord and Premid have been restarted.

I am unable to reproduce this on my side. Crunchyroll displays the episode information as expected.
Do you get any errors in the console while using Crunchyroll and this presence?

**Comment by ByZorks** [comment]
> 
![image](https://user-images.githubusercontent.com/80073731/199599589-778bbf29-195d-4d40-aeb6-13b0a98698e3.png)
![image](https://user-images.githubusercontent.com/80073731/199599647-91d13d6d-7034-4c39-84f6-678b24bd4a5b.png)

(Idk if it's the thing you want ?)

**Comment by theusaf** [comment]
Yes, this is what I wanted.
Looking at the image, there aren't any logs related to the presence breaking majorly. The first few errors in the first screenshot only occur while the page is still loading details.
Personally, I've not been having problems with the presence recently. Although sometimes, I have had various presences also stop working mysteriously at random times, requiring Discord to be restarted in order for the presence to re-appear.

**Comment by ByZorks** [comment]
> Yes, this is what I wanted. Looking at the image, there aren't any logs related to the presence breaking majorly. The first few errors in the first screenshot only occur while the page is still loading details. Personally, I've not been having problems with the presence recently. Although sometimes, I have had various presences also stop working mysteriously at random times, requiring Discord to be restarted in order for the presence to re-appear.

Personally, I only have this problem with this presence and only when watching an episode. There is no problem on the other pages of the site as long as I don't launch an episode.
Now the Presence displays the information about the episode, but whatever I do, it remains displayed as paused with this error when I press play/pause (1 time/click)
![image](https://user-images.githubusercontent.com/80073731/200120168-8239f0b6-aece-4c43-9b21-ec3321f521a7.png)

**Comment by ByZorks** [comment]
Can it be related to this ? (official Crunchyroll integration in discord)
https://twitter.com/discord/status/1593748499245727744

**Comment by DarkVillager** [comment]
This has to do with iframes on some parts it doesn't inject into the iframe @Bas950 @EncryptedDev 
Can't seem to solve this.

**Comment by ByZorks** [comment]
I've been using it for 2 weeks and it seems to work as expected again
