### ISSUE TITLE
Mubi.com - Service Add Request

### ISSUE THREAD

**Issue by thisanickname** [PreMiD/Presences#6956]
### Website name

Mubi

### Website URL

https://mubi.com

### Website logo

https://mubi.com/logo

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Mubi is a curated streaming service, which offers an ever-changing collection of hand-picked films, introducing one new film each day. Mubi is also a distributor and producer.

**Comment by thisanickname** [comment]
up

**Comment by DarkVillager** [comment]
I put this on my to-do list. Be patient tho.

**Comment by thisanickname** [comment]
Thank you so much

**Comment by thisanickname** [comment]
> I put this on my to-do list. Be patient tho.

Thank you so much

**Comment by thisanickname** [comment]
> I put this on my to-do list. Be patient tho.

hello any updates? :)

**Comment by DarkVillager** [comment]
> > I put this on my to-do list. Be patient tho.
> 
> hello any updates? :)

Been really bust. Sorry for the delay.

**Comment by thisanickname** [comment]
It's ok 😊

**Comment by thisanickname** [comment]
> > > I put this on my to-do list. Be patient tho.
> > 
> > 
> > hello any updates? :)
> 
> Been really busy. Sorry for the delay.

hi sorry for bothering i wonder if theres any updates? :)

**Comment by DarkVillager** [comment]
> > > > I put this on my to-do list. Be patient tho.
> > > 
> > > 
> > > hello any updates? :)
> > 
> > 
> > Been really busy. Sorry for the delay.
> 
> hi sorry for bothering i wonder if theres any updates? :)

I’ll be done today.

**Comment by thisanickname** [comment]
> > > > > I put this on my to-do list. Be patient tho.
> > > > 
> > > > 
> > > > hello any updates? :)
> > > 
> > > 
> > > Been really busy. Sorry for the delay.
> > 
> > 
> > hi sorry for bothering i wonder if theres any updates? :)
> 
> I’ll be done today or tmr.

oh thank you so much

**Comment by DarkVillager** [comment]
> > > > > > I put this on my to-do list. Be patient tho.
> > > > > 
> > > > > 
> > > > > hello any updates? :)
> > > > 
> > > > 
> > > > Been really busy. Sorry for the delay.
> > > 
> > > 
> > > hi sorry for bothering i wonder if theres any updates? :)
> > 
> > 
> > I’ll be done today or tmr.
> 
> oh thank you so much

My free trial has seem to expired. I don't know when I can fix that. Please be patient.

**Comment by thisanickname** [comment]
> > > > > > > I put this on my to-do list. Be patient tho.
> > > > > > 
> > > > > > 
> > > > > > hello any updates? :)
> > > > > 
> > > > > 
> > > > > Been really busy. Sorry for the delay.
> > > > 
> > > > 
> > > > hi sorry for bothering i wonder if theres any updates? :)
> > > 
> > > 
> > > I’ll be done today or tmr.
> > 
> > 
> > oh thank you so much
> 
> My free trial has seem to expired. I don't know when I can fix that. Please be patient.

oh its ok can you give me your discord id so i can share my mubi account with you

**Comment by thisanickname** [comment]
> > > > > > > I put this on my to-do list. Be patient tho.
> > > > > > 
> > > > > > 
> > > > > > hello any updates? :)
> > > > > 
> > > > > 
> > > > > Been really busy. Sorry for the delay.
> > > > 
> > > > 
> > > > hi sorry for bothering i wonder if theres any updates? :)
> > > 
> > > 
> > > I’ll be done today or tmr.
> > 
> > 
> > oh thank you so much
> 
> My free trial has seem to expired. I don't know when I can fix that. Please be patient.

oh its ok i shared my account details with you on discord
