### ISSUE TITLE
Microsoft Office Apps -  Word, Powerpoint, Excel etc

### ISSUE THREAD

**Issue by xAlphy** [PreMiD/Presences#6966]
### Website name

Office

### Website URL

https://www.office.com/

### Website logo

Office

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Basically a presence showing some details on the work you are working on. 

For example if you were on Microsoft Word it could be displayed like this.

[TITLE OF THE DOCUMENT]
[PAGE # OUT OF #]
[WORD COUNT]
[TIME SPENT]

**Comment by Isa27-0** [comment]
Already exists: https://premid.app/store/presences/Office

**Comment by xAlphy** [comment]
> Already exists: https://premid.app/store/presences/Office

It doesn't do what I said. It literally just tracks what your doing on the office website, which is completely useless.

**Comment by Isa27-0** [comment]
> t doesn't do what I said. It literally just tracks what your doing on the office website, which is completely useless.

Then you should use the [Feature Request](https://github.com/PreMiD/Presences/issues/new?assignees=&labels=feature+request&template=feature_request.yml), asking for more functions. Service Request is for adding presences that are not in the store.
