### ISSUE TITLE
Hitradio ÖE3 | oe3.orf.at

### ISSUE THREAD

**Issue by MauriceLPs** [PreMiD/Presences#697]
**What's the name of the service?**
Ex. https://oe3.orf.at/player/ | Hitradio Ö3

**What should the Presence display?**
Informations about the current Song & Artist and the current Show.

**Why do you want support for this service?**
Because Hitradio Ö3 is the national Radio of Austria and it have really good music and a great show. Of course, I listen it all time, because it also have a really good traffic info.

**Are you able to provide an image for the service? (512x512 minimum)**
https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Hitradio_%C3%963.svg/2000px-Hitradio_%C3%963.svg.png

**Comment by OfficialCRUGG** [comment]
Is there some fixed place where the current song is shown? (Besides the timeline thing)
Also, should the presence be in German or English Language? I mean it's an austrian radio so German would make the most sense wouldn't it?

**Comment by MauriceLPs** [comment]
Heya, there was an old player, but it's not accessible anymore. So it's only "readable" from the Timeline.
The presence can be in english, but german would make the most sense, yes :D

**Comment by OfficialCRUGG** [comment]
Okay. I don't know how I would do the presence then. Sorry. For whoever will do the presence: DM me on Discord (CRUGG#0001) if you need german strings! :)

**Comment by MauriceLPs** [comment]
Okay, thanks anyway :D
