### ISSUE TITLE
Premid

### ISSUE THREAD

**Issue by Busrobo1** [PreMiD/Presences#6977]
### Steps to Reproduce

Help

### Expected Behavior

not showing status

### Actual Behavior

status says undefined

### Page URL

discord.com

### Screenshots

![2022-11-04](https://user-images.githubusercontent.com/115512454/200137080-b42100e8-a643-414e-b49e-ccf925a97a83.png)

### Operating System

Windows 10

### Browser and Version

Chrome

### Additional Comments

It says Undefined

**Comment by mertcanserim** [comment]
waiting for fix   -_-
