### ISSUE TITLE
Blender Presence?

### ISSUE THREAD

**Issue by 3Rr0r418** [PreMiD/Presences#6981]
### Website name

Blender

### Website URL

https://www.blender.org/

### Website logo

https://commons.wikimedia.org/wiki/File:Blender_logo_no_text.svg

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

I'm thinking that having this as only a basic presence as I'm not sure how hard it would be to track more specific things you're doing in Blender
- Have the name of your file displayed as what you're working on
- Have a counter showing how long you've been working on it

**Comment by DiscordAnaxes** [comment]
If I recall correctly, blender is an app only application, meaning that a PreMiD presence can not be made for it, as PreMiD only works on the web. <-- Based on the functionality requirements (description) given.

**Comment by 3Rr0r418** [comment]
Ah Thank you for letting me know!
