### ISSUE TITLE
Clip Studio Paint Presence

### ISSUE THREAD

**Issue by 3Rr0r418** [PreMiD/Presences#6982]
### Website name

Clip Studio

### Website URL

https://www.clipstudio.net/en/

### Website logo

https://platinmods.com/attachments/wgamstli-nghn8ig5nw1ukh6wn3rsu_-rt93ic-d_olvmghsh8-jpg.275573/

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Another fairly simple presence I reckon, only tracking basic things to display;
- File name(s) (if you have multiple files open, and have it switch to which you're focused on)
- How long you've had CSP open, what version you have (DEBUT, PRO, EX)

**Comment by DiscordAnaxes** [comment]
Same thing as Blender presence. PreMiD only supports the web, not applications.

**Comment by 3Rr0r418** [comment]
Yeah my bad! Sorry abt that :'D
