### ISSUE TITLE
Add More Features to Microsoft Office Presence

### ISSUE THREAD

**Issue by xAlphy** [PreMiD/Presences#6986]
### Presence name

Office - https://premid.app/store/presences/Office

### Description

This presence only tracks what your doing on the Office website (Im pretty sure not that many people use it on the website), like it would be alot more cool if it did the Microsoft apps such as Word, PowerPoint, Excel etc. 

For example if you were on Microsoft Word it could be displayed like this.

[TITLE OF THE DOCUMENT]
[PAGE # OUT OF #]
[WORD COUNT]
[TIME SPENT]

### Additional context

Yes before u say, Ik there is already one out there that isn't a directly linked with premid:

https://github.com/7coil/DiscordForOffice

but this one doesnt really meet what is required and shows just page name.

**Comment by joerkig** [comment]
Are you talking about when you use word, etc in the browser? Because this should already be supported. If you are talking about the desktop application versions of word, etc. PreMiD does not currently support presences for applications
