### ISSUE TITLE
new presence request

### ISSUE THREAD

**Issue by ALIENSPECIES394** [PreMiD/Presences#6991]
### Website name

pokeflix

### Website URL

https://www.pokeflix.tv/

### Website logo

pokeflix

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

<img width="64" alt="image" src="https://user-images.githubusercontent.com/66906353/201473640-f2eb3aaa-5920-4bd4-926a-5f443d05e22d.png">

**Comment by DwifteJB** [comment]
Checking this out, thanks for showing this to me; I'll post any progress here.

**Comment by DwifteJB** [comment]
Quick progress.
![image](https://user-images.githubusercontent.com/67983181/202517898-cfaf2271-ba00-4784-b845-df91b397768f.png)

**Comment by DwifteJB** [comment]
![image](https://user-images.githubusercontent.com/67983181/202529486-6164f958-0e67-4954-8e46-b7ea455ba60b.png)
finished
