### ISSUE TITLE
Animedao bug

### ISSUE THREAD

**Issue by lowkey08301** [PreMiD/Presences#6997]
### Steps to Reproduce

1. Go to animedao.to
2. Open an episode of any anime

### Expected Behavior

Shows anime title and episode in status

### Actual Behavior

Does not show title, status, or any information other than "Animedao" twice

### Page URL

https://animedao.to/view/9607792013/

### Screenshots

![Screenshot 2022-11-12 222142](https://user-images.githubusercontent.com/118090626/201504067-08116926-a727-485f-a382-3e9c6ed3942a.jpg)

### Operating System

Windows 10

### Browser and Version

Google Chrome, Version 107.0.5304.107

### Additional Comments

In the past, it used to show the anime title and episode number, I'm not sure what changed, but this issue was noticed by me around mid-October.

From looking around, it appears similar issues have affected other websites as well, such as:
Crunchyroll: https://discord.com/channels/493130730549805057/1038615589050134558
https://github.com/PreMiD/Presences/issues/6951
Disney Plus: https://discord.com/channels/493130730549805057/1034821498294255686
MangaDex: https://discord.com/channels/493130730549805057/1036127176023621742

From the looks of it, this issue has affected multiple websites and multiple people, so hopefully a fix is found soon

Thanks

**Comment by DarkVillager** [comment]
animedao.to's issue has been resolved as per #7066
