### ISSUE TITLE
All anime website presences

### ISSUE THREAD

**Issue by utenm** [PreMiD/Presences#7002]
### Steps to Reproduce

1. https://animedao.to/ , https://www.crunchyroll.com/ , https://9anime.vc/
2. Start playing any anime
3. Check presence

### Expected Behavior

Display episode of anime + timestamp

### Actual Behavior

Animedao just says Animedao twice. Crunchyroll will display if you're browsing but will completely stop working once you start watching an anime. 9anime has the same issue as Crunchyroll.

### Page URL

https://animedao.to/ , https://www.crunchyroll.com/ , https://9anime.vc/

### Screenshots

![image](https://user-images.githubusercontent.com/118361667/202186584-a6d1e2ae-3786-4b5a-8ad6-69661037ecc1.png)
This is what shows up (Animedao)
Can't take a screenshot for Crunchyroll or 9anime because nothing shows up.

### Operating System

Windows 10

### Browser and Version

Google Chome Version 107.0.5304.107 (Official Build) (64-bit)

### Additional Comments

It's not my biggest concern, but it would also be nice if there was a settings button for Animedao like everything else.

**Comment by utenm** [comment]
Actually just double checked, https://9anime.vc/ is a fake website. https://9anime.gs/ (the official website) works perfectly fine on Premid!

**Comment by DarkVillager** [comment]
AnimeDao.to will be fixed soon.

**Comment by theusaf** [comment]
Closing as most of the presences listed were fixed, and making room for more specific issues.
