### ISSUE TITLE
Disney+ presence only showing browsing

### ISSUE THREAD

**Issue by kisrr** [PreMiD/Presences#7027]
### Steps to Reproduce

1. go to disneyplus.com (or for my case disneyplus.com/ph)
2. go to a movie or a show
3. check presence

### Expected Behavior

Show what movie / series i was watching

### Actual Behavior

Only showed browsing even if i was watching a movie

### Page URL

https://www.apps.disneyplus.com/ph/shows/modern-family/8549/en-garde/1770001034/watch

### Screenshots

![image](https://user-images.githubusercontent.com/111058813/202825249-b006421a-2df1-47a6-b442-9e4052a87679.png)

### Operating System

Windows 10

### Browser and Version

Firefox 106.0.5

**Comment by edwinarubygo** [comment]
Same thing happening to my discord

**Comment by mamasitamamamia** [comment]
same thing on my end. PH-based. please fix >.<
