### ISSUE TITLE
Add a button to view a beatmap

### ISSUE THREAD

**Issue by DJMakerMusician** [PreMiD/Presences#7028]
### Presence name

osu!ppy

### Description

I think that this could implemented similarly to the way that YouTube "Watch Video" button is implemented. Something like this ↓
![image](https://user-images.githubusercontent.com/73738591/202851604-59b59aed-f818-4640-8fd5-a51a9a4a15c8.png)

**Comment by joerkig** [comment]
There is currently a PR awaiting review #6893 which when merged should add this
