### ISSUE TITLE
Pixiv not working correctly

### ISSUE THREAD

**Issue by Zanzancomms** [PreMiD/Presences#7035]
### Steps to Reproduce

1. Go to https://www.pixiv.net/ (will show "Viewing home page" on status as intended so far)
2. Press any artwork or user in the site
3. Rich presence will stop working or just show "Viewing home page" as status

### Expected Behavior

Display the artwork/tag/user/ pretty much anything else it should display

### Actual Behavior

Just shows "Viewing home page" / "Viewing dashboard" / "User settings"

### Page URL

https://www.pixiv.net/

### Screenshots

![image](https://user-images.githubusercontent.com/68141931/203451410-5c403dae-9ef7-48f3-b125-ccec435fa63f.png)

### Operating System

Windows 10

### Browser and Version

 Chrome Version 107.0.5304.107 (Official Build) (64-bit)

### Additional Comments

Seems anything artwork/user related aside from the homepage and your own dashboard/settings is broken

**Comment by Zanzancomms** [comment]
would be a nice feature to add the artwork image in the presence too, as in the artstation rich presence, with a toggle for on and off

**Comment by RisingSunLight42** [comment]
On it, seems like something is messed up in the code due to some website's changes.
