### ISSUE TITLE
Requesting a presence

### ISSUE THREAD

**Issue by Troggydyte** [PreMiD/Presences#7065]
### Website name

4chan

### Website URL

https://www.4chan.org/

### Website logo

https://s.4cdn.org/image/fp/logo-transparent.png

### Prerequisites

- [ ] It is a paid service
- [X] It displays NSFW content
- [ ] It is region restricted

### Description

I would like for the presence to display that I am on the website, and what specific board I am using. If possible, the name of the thread I am in.

**Comment by DarkVillager** [comment]
Seems to be a decision by the management of premid. They removed it in #6814

**Comment by joerkig** [comment]
> Removing it seems to be a decision by the management of premid. It got removed in #6814

From the looks of the linked PR it was the presence devs request to remove it

**Comment by Bas950** [comment]
For ethical reasons we don't find this website appropriate to have on the store.
