### ISSUE TITLE
Soundcloud not appearing on my discord profile 

### ISSUE THREAD

**Issue by hauntedmilfs** [PreMiD/Presences#7077]
### Steps to Reproduce

1. Go to soundcloud.com
2. Play a track
3. Go to discord profile

### Expected Behavior

Song to appear on my discord profile

### Actual Behavior

Song doesn't appear on my discord profile 

### Page URL

soundcloud.com

### Operating System

Windows 11

### Browser and Version

Google Chrome 108.0.5359.125

### Additional Comments

All of the options for the soundcloud presence are on.

**Comment by theusaf** [comment]
Duplicate of #6430
