### ISSUE TITLE
Add Fite.tv

### ISSUE THREAD

**Issue by TheBaconSpace** [PreMiD/Presences#7079]
### Website name

Fite.tv

### Website URL

https://fite.tv/ 

### Website logo

https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/FITE_TV.svg/2560px-FITE_TV.svg.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

would like to see https://www.fite.tv/p/about/ also any plans on having wwe network for canada and uk presence since canada and uk dont have peacock

**Comment by sweezyio** [comment]
Duplicate of #7038.
