### ISSUE TITLE
H-NEXT | video.hnext.jp

### ISSUE THREAD

**Issue by 00028** [PreMiD/Presences#7082]
### Website name

H-NEXT

### Website URL

https://video.hnext.jp/

### Website logo

https://vod-osusume.net/wp-content/uploads/2021/01/HNEXT-logo.png

### Prerequisites

- [X] It is a paid service
- [X] It displays NSFW content
- [X] It is region restricted

### Description

#7081 Adult service operated by the company in Japan.

**Comment by theusaf** [comment]
Due to certain changes, services like these will be removed/disallowed soon.
