### ISSUE TITLE
Yugen Anime

### ISSUE THREAD

**Issue by crashbash317** [PreMiD/Presences#7090]
### Website name

Watch HD Anime for Free - YugenAnime

### Website URL

https://yugen.to/

### Website logo

(https://yugen.to/static/img/logo__light.png)

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Title of the anime.
What episode is being watched
timestamp

**Comment by DiscordAnaxes** [comment]
Will give it a go 👍
