### ISSUE TITLE
apple music presence

### ISSUE THREAD

**Issue by 00028** [PreMiD/Presences#7103]
### Steps to Reproduce

Play a song
Look at the time stamp in discord

### Expected Behavior

When you play a song in Apple Music, you should see a timestamp in Discord

### Actual Behavior

Time stamps are not displayed.

### Page URL

https://music.apple.com/tr/album/alive/1635561575?i=1635561576

### Screenshots

![キャプチャ](https://user-images.githubusercontent.com/87330832/210345402-52dc7385-6aff-4dba-b920-cafc3e108fd2.PNG)
![キャプチャ](https://user-images.githubusercontent.com/87330832/210345476-268f087a-bffc-4c37-804a-5d5ba4be8a88.PNG)

### Operating System

Windows 10

### Browser and Version

Firefox

**Comment by DarkVillager** [comment]
They are for me?
![image](https://github.com/PreMiD/Presences/assets/42322979/e4ba1905-cd5d-4441-9eb8-d75b96422e83)

**Comment by theusaf** [comment]
Marking as duplicate/related to #8409
