### ISSUE TITLE
Feature Request | Office

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#7136]
### Presence name

Office

### Description

Microsoft has discontinued the "Microsoft Office" brand, with all of its products primarily being branded "Microsoft 365". The icon has also been changed:

![image](https://user-images.githubusercontent.com/68751594/214645942-cb07d3a1-e8f0-421b-b327-f781fa1f10d9.png)

So, it would be nice to update the presence too, changing the name and logo.

### Alternatives

None

### Additional context

None

**Comment by DarkVillager** [comment]
@kyrie25

**Comment by kyrie25** [comment]
Will do some time in the future.
