### ISSUE TITLE
Requesting a presense

### ISSUE THREAD

**Issue by CharliDaiz** [PreMiD/Presences#7160]
### Presence name

Soundtrap

### Description

I feel would be cool to have soundtrap.com as a discord presence so that whenever you are working on a song, friends can see and join in on what kind of song you are making.
![image_2023-02-01_162439111](https://user-images.githubusercontent.com/124218302/216200186-a87efc4c-6010-449b-a305-aa9b5dc11142.png)

**Comment by DarkVillager** [comment]
Seems like an interesting site. I put this on my to-do list but if someone has time now take it.

**Comment by CharliDaiz** [comment]
Cool!!! Just glad you we're able to see the idea
