### ISSUE TITLE
"TRanimeizle" service needs an update.

### ISSUE THREAD

**Issue by tunahann0** [PreMiD/Presences#7162]
### Steps to Reproduce

Website's url changed, so it needs an update. New url: "tranimeizle.co"

### Expected Behavior

The app should show my activity

### Actual Behavior

It doesn't show my activity

### Page URL

tranimeizle.co

### Operating System

windows 7, 8, 10, 11

### Browser and Version

Brave Browser, latest version

**Comment by theusaf** [comment]
Confirmed. URLs listed in the presence redirect to the mentioned domain.

**Comment by tunahann0** [comment]
> Confirmed. URLs listed in the presence redirect to the mentioned domain.

So, will this change gonna release or should i do something myself? I'm not used to things like this so sorry for that. Do i have to just wait? And my English isn't good enough, sorry for that too.

**Comment by theusaf** [comment]
> > Confirmed. URLs listed in the presence redirect to the mentioned domain.
> 
> So, will this change gonna release or should i do something myself? I'm not used to things like this so sorry for that. Do i have to just wait? And my English isn't good enough, sorry for that too.

There is a PR already made to fix this issue by @RisingSunLight42. When the PR gets merged, it should be automatically updated in your extension. All you have to do is wait.

**Comment by tunahann0** [comment]
> > > Confirmed. URLs listed in the presence redirect to the mentioned domain.
> > 
> > 
> > So, will this change gonna release or should i do something myself? I'm not used to things like this so sorry for that. Do i have to just wait? And my English isn't good enough, sorry for that too.
> 
> There is a PR already made to fix this issue by @RisingSunLight42. When the PR gets merged, it should be automatically updated in your extension. All you have to do is wait.

oh okay. thank you
