### ISSUE TITLE
Skyshowtime

### ISSUE THREAD

**Issue by dkol** [PreMiD/Presences#7180]
### Website name

skyshowtime.com

### Website URL

https://www.skyshowtime.com/

### Website logo

https://i.imgur.com/xJToteM.png

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [X] It is region restricted

### Description

This is a new streaming platform in Europe supported by Peacock. Presence (functions) should be similar to Netflix/HBO Max, i.e. displaying the currently watched series/movie, season and episode and their duration, logo, buttons.

**Comment by DarkVillager** [comment]
@dkol is it similair to [https://www.showtime.com/](https://www.showtime.com/) that has [this presence](https://premid.app/store/presences/Showtime)

**Comment by dkol** [comment]
@DarkVillager it's hard for me to say, Showtime is American and I don't have access there, can't compare. If access to Skyshowtime (PL) would help you, I sent a DM on Discord.

**Comment by GodDirtman** [comment]
Bumping the idea, I just wanted to suggest it too. SkyShowtime is a big streaming service available in most EU countries and it recently completed the next rollout to some more. 

Showtime.com is available only in the US and has a different owner. I don't know about the technical side of this though. 

Hope this will be added soon.
