### ISSUE TITLE
About d anime store

### ISSUE THREAD

**Issue by neco222** [PreMiD/Presences#7183]
### Steps to Reproduce

①add d anime with premid
②start playing
③Not reflected in status

### Expected Behavior

Not reflected in status

### Actual Behavior

Nothing happens

### Page URL

https://animestore.docomo.ne.jp

### Operating System

windows 11

### Browser and Version

110.0.5481.96

### Additional Comments

Edited to new link but d anime store doesn't work.
Anyone know the cause?

**Comment by theusaf** [comment]
seems to be an extension-related issue. some testing has shown that the presence is likely working as intended.
