### ISSUE TITLE
Fiplay presence

### ISSUE THREAD

**Issue by Anonymousfin** [PreMiD/Presences#72]
![fiplay-footer-logo-300px](https://user-images.githubusercontent.com/53667344/62417799-22e51700-b662-11e9-9547-5c7088421f05.png)
**What's the name of the service?**
Fiplay 
http://fiplay.net/
**What should the Presence display?**
Informations about the current video

**Why do you want support for this service?**
Tell us why you want to have support for this website. Please don't just tell us "I use it all the time"

**Are you able to provide an image for the service? (512x512 minimum)**
If you can provide the logo pls paste a link in here or the image

**Comment by OfficialCRUGG** [comment]
Warning: Link has NSFW (really nsfw) ads

**Comment by TheDropX** [comment]
Presence done.
