### ISSUE TITLE
Kick

### ISSUE THREAD

**Issue by cappobaby** [PreMiD/Presences#7209]
### Website name

Kick

### Website URL

https://kick.com/

### Website logo

https://i.kym-cdn.com/entries/icons/original/000/042/927/kickcover.jpg

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Just like twitch it should show who your watching and how long you've been watching them.

**Comment by Kuriel23** [comment]
duplicated of #7200
