### ISSUE TITLE
Fmovies | Fmovies.to

### ISSUE THREAD

**Issue by murjss** [PreMiD/Presences#7211]
### Steps to Reproduce

go to https://premid.app/store/presences/FMovies

im trying to add fmovies as an presences and i added it in extension too but when i watch anything it doesnt show up on discord

### Expected Behavior

i expect it to display what im watching on discord 

### Actual Behavior

i've been watching outer banks and i've always checked if it would show up but it never shows up

### Page URL

https://premid.app/store/presences/FMovies

### Operating System

Windows 11

### Browser and Version

Opera gx (i tried zoro.to and it did work even tho i was using opera)

**Comment by DarkVillager** [comment]
@Bas950 rename to: Fmovies | Fmovies.to

**Comment by RisingSunLight42** [comment]
Works fine for me, did you try another browser ?

**Comment by DredDine** [comment]
the rpc is showing but it didnt display the infos of the movie/series!
i guess the new update on the [fmovies.to](https://fmovies.to/home) they change the layout and everything...
we need new update please for this presence
