### ISSUE TITLE
Facebook | https://web.facebook.com

### ISSUE THREAD

**Issue by TeeraphatCH15224** [PreMiD/Presences#7216]
### Steps to Reproduce

1 . download and install PreMiD 
2. install Facebook Presence in the PreMiD Store
3. open Facrbook

### Expected Behavior

Fix Facebook Presence back to Discoพd

### Actual Behavior

I have already installed Premid and went to install Presence as Facebook and it didn't show Facebook Presence but other Presence appeared normally. 

### Page URL

https://web.facebook.com

### Screenshots

 <img  src="https://cdn.discordapp.com/attachments/1082192639232856074/1082194408755179520/image.png">

 <img  src="https://cdn.discordapp.com/attachments/1082192639232856074/1082200467024654356/image.png">

### Operating System

windows 10

### Browser and Version

Google Chrome 110.0.5481.178
Brave 1.48.171 Chromium: 110.0.5481.177

**Comment by DarkVillager** [comment]
On it.

**Comment by TeeraphatCH15224** [comment]
Thank you very much, but if you are finished, you can tell me at this github or contact me at discord : Teeraphat_CH#0733
