### ISSUE TITLE
Fbox.to presence not working

### ISSUE THREAD

**Issue by xSoulls** [PreMiD/Presences#7229]
### Steps to Reproduce

open Fbox.to and turn on the presence for it, it doesn't detect me using fbox.to on discord

### Expected Behavior

my activity to be tracked

### Actual Behavior

presence not tracking properly

### Page URL

https://fbox.to

### Operating System

windows 11

### Browser and Version

Opera GX LVL 4 (core: 95.0.4635.74)

### Additional Comments

this will sometimes happen with other streaming services like 9anime and Soap2day. It usually works with official ones like Netflix or Hulu though. Youtube and Twitch presences work fine.

**Comment by DarkVillager** [comment]
Can reproduce.
