### ISSUE TITLE
Netflix | netflix.com

### ISSUE THREAD

**Issue by AMufInABox** [PreMiD/Presences#7260]
### Steps to Reproduce

1. Visit netflix.com
2. Watch any show on [PreMiD-Beta](https://premid.app/beta) (or stable #7466)

### Expected Behavior

 Would expect it to show the show I'm watching on status.

### Actual Behavior

Presence does not show what Netflix show I'm watching.

### Page URL

1118280%2CNES_E5DCB5B6CE0824EBD068CE353C42D8-994911DC4F528C-A992686634_p_1680293608503%2CNES_E5DCB5B6CE0824EBD068CE353C42D8_p_1680293608503%2C%2C%2C%2C%2CVideo%3A80057134%2CdetailsPagePlayButton

### Screenshots

![image](https://user-images.githubusercontent.com/74741218/229221820-a2a42905-d0d5-4d8a-b208-ace058c58f7b.png)
![image](https://user-images.githubusercontent.com/74741218/229221864-4d53e8c7-30d5-4779-8207-72e5a6c5f1c5.png)

### Operating System

Windows 11

### Browser and Version

Brave Browser | V 1.49.132

**Comment by AMufInABox** [comment]
Bump?

**Comment by lizsdswsd** [comment]
problem still occuring 
![image](https://github.com/PreMiD/Presences/assets/130219109/2d2053ea-888d-4b33-9bf2-ccb63374d6b7)

**Comment by zeroday-zaddy** [comment]
Bump

**Comment by DarkVillager** [comment]
I can reproduce.
