### ISSUE TITLE
Naruto Shippuden Ultimate Ninja Storm: Trilogy

### ISSUE THREAD

**Issue by IAmDaPlane** [PreMiD/Presences#7262]
### Website name

Ninja Storm: Trilogy

### Website URL

https://store.steampowered.com/app/495140/NARUTO_Ultimate_Ninja_STORM/

### Website logo

https://cdn.dekudeals.com/images/1cb675bbb1db04f8d13c6f1de0339825e20e3505/w500.jpg

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

its not a website but a game

**Comment by DarkVillager** [comment]
@Bas950 ^
