### ISSUE TITLE
Topluluk Papara | topluluk.papara.com

### ISSUE THREAD

**Issue by smilefate** [PreMiD/Presences#7270]
### Website name

Papara

### Website URL

https://topluluk.papara.com/

### Website logo

https://cdn.papara.com/web/Assets/img/icon/papara_icon.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Visit home page, visit categories, recent content and popular topics. 

When searching within the page: The searched word and the number of matching results.

When a topic is visited: Topic title and category name, author name, number of views of the topic.

When a user profile is visited: the name of the user visited, which sections of the user's profile the user has viewed (summary, activity and badges).

And, I would appreciate if a link with a button for the visited pages could be added ^-^)

**Comment by eggsy** [comment]
On it.
