### ISSUE TITLE
bandcamp | bandcamp.com

### ISSUE THREAD

**Issue by LIBTrishhhHH** [PreMiD/Presences#7271]
### Steps to Reproduce

The steps are the same as my last report (If you can't reopen it then it was just "Download PreMiD and get the Bandcamp presence via the presence store and figure out why it's not working.") Only difference is that I'm on my mac.

### Expected Behavior

For discord to display what I'm listening to on bandcamp.

### Actual Behavior

Nothing appearing on my profile.

### Page URL

https://bandcamp.com/

### Screenshots

![Screen Shot 2023-04-05 at 9 31 30 am](https://user-images.githubusercontent.com/129841950/229944818-53142b9c-6f4f-4445-bdb8-ed69eb61e38f.png)
![Screen Shot 2023-04-05 at 9 31 59 am](https://user-images.githubusercontent.com/129841950/229944828-e5c7627f-3205-4c5d-9b1d-2bacd342b3cc.png)

### Operating System

macOS Monterey Version 12.6

### Browser and Version

Google Chrome Version 111.0.5563.110 (Official Build) (x86_64)

### Additional Comments

Probably not a good idea to resubmit the same issue 2 days in a row but I wanted to tell you guys that I'm also having the same issue on my mac.

**Comment by DarkVillager** [comment]
@Bas950 rename to; bandcamp | bandcamp.com
