### ISSUE TITLE
Could you add a TheWatchCartoonOnline.tv prescence?

### ISSUE THREAD

**Issue by sapphelis** [PreMiD/Presences#7297]
### Presence name

TheWatchCartoonOnline

### Description

I want it to show the episode, show and time left for what I'm watching as its my main website for watching cartoons on. I also occasionally use it for anime when zoro.to isn't working or doesn't have it. The domain it uses are TheWatchCartoonOnline.tv and wcofun.com.

### Additional context

The logo
![Thewatchcartoononline-Symbol](https://user-images.githubusercontent.com/130873709/232333674-3f2a3afe-fa7c-4919-8d61-d2e27cefbfbb.png)

**Comment by DarkVillager** [comment]
@sapphelis close this and open a **Service Request** instead.

**Comment by Isa27-0** [comment]
Duplicate of #5412

**Comment by DarkVillager** [comment]
> Duplicate of #5412

@Bas950
