### ISSUE TITLE
Channel4 / All4 - channel4.com

### ISSUE THREAD

**Issue by CatPerson-co-uk** [PreMiD/Presences#7302]
### Website name

channel4 / all4

### Website URL

https://www.channel4.com/

### Website logo

https://www.channel4.com/favicon.ico

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Show your watching, timestamp, and browsing if your on home page

**Comment by Isa27-0** [comment]
Duplicate of #5447

**Comment by Isa27-0** [comment]
@Bas950 Can you close this Issue?
