### ISSUE TITLE
Discord presence easily breaks with SoundCloud

### ISSUE THREAD

**Issue by c4k3ss** [PreMiD/Presences#7310]
### Steps to Reproduce

1. Go to https://soundcloud.com/
2. Start listening to your music

### Expected Behavior

Discord showing the correct song at the correct timestamp.

### Actual Behavior

Discord either doesn't show any song, shows the wrong song or still shows a song is playing when SoundCloud is closed.

UPDATE: I have also managed to get it to show 2 songs at the same time, unintentionally.

### Page URL

https://soundcloud.com/

### Screenshots

![image](https://user-images.githubusercontent.com/77441265/233835653-430123bf-4dae-484c-a098-6d9bebf81cb8.png)

*^^ Song is playing on SoundCloud*

![image](https://user-images.githubusercontent.com/77441265/233835693-98ec53f2-3749-4944-9244-b1c444fec9c9.png)

*^^ No Discord Activity*

![image](https://user-images.githubusercontent.com/77441265/233835752-76dccc79-3f28-46b7-996d-457c0b2b2735.png)

*^^ PreMiD Already Running*

![image](https://user-images.githubusercontent.com/77441265/233835792-02d775a6-882e-4861-ad70-0b8312b5a831.png)

*^^ SoundCloud Presence is on*

![image](https://user-images.githubusercontent.com/77441265/233851317-2dcdeaf1-6604-41a5-9668-4f1a7d09e2b5.png)
*^^ 2 Songs playing at the same time somehow*

### Operating System

Windows 11

### Browser and Version

Chrome Version 112.0.5615.138

**Comment by un1ya** [comment]
I've had this same issue while using OperaGX and have previously had it in the past on Chrome too, the only way I've managed to fix it is by uninstalling the desktop PreMiD app and then reinstalling it

**Comment by c4k3ss** [comment]
> I've had this same issue while using OperaGX and have previously had it in the past on Chrome too, the only way I've managed to fix it is by uninstalling the desktop PreMiD app and then reinstalling it

I have noticed that doing that tends to resolve the problem, but it shouldn't be that way. I shouldn't have to do that every time I want my status to be updated when I listen to music on SoundCloud.

**Comment by Slowlife01** [comment]
This is an issue on the Extension side. It's fixed in the beta version
