### ISSUE TITLE
Gogogoanime | Bug

### ISSUE THREAD

**Issue by AMufInABox** [PreMiD/Presences#7330]
### Steps to Reproduce

1. Go to any show on gogoanime
2. It will say browsing in status but wont show what I am actually watching.

### Expected Behavior

 Would expect it to show the movie/show I amwatching on status.

### Actual Behavior

Presence does not show at all and console is spammed.

### Page URL

https://www3.gogoanime.me/fategrand-order-shuukyoku-tokuiten-kani-jikan-shinden-solomon-episode-1

### Screenshots

![image](https://user-images.githubusercontent.com/74741218/235774404-93c5d4ea-7840-4477-a37a-11fa257f0c70.png)

### Operating System

Windows 11

### Browser and Version

Brave Browser Stable | v1.50.121

**Comment by DarkVillager** [comment]
On it.
