### ISSUE TITLE
9anime status doesn't show

### ISSUE THREAD

**Issue by pmksch101** [PreMiD/Presences#7332]
### Steps to Reproduce

1. go to 9anime.to
2. try to browse for anime or play a show/movie
3. status doesnt display

### Expected Behavior

Show browsing or playing a movie/show

### Actual Behavior

Doesn't Display

### Page URL

https://9anime.to

### Operating System

MacOs Ventura 13.3.1

### Browser and Version

Safari Version 16.4

### Additional Comments

been like this since it was changed to video detection instead of domain based;
since DarkVillager thinks the domain changes are constant (they aren't)
the only domains 9anime is using and has been using for a very long time can be found at https://9anime.me but considering someone already told them this and they wouldnt go look for some reason
here is a list of them:
9anime.to
9anime.pl
9anime.gs

**Comment by DarkVillager** [comment]
I'm currently investigating the issue. This seems to be related to premid's extension.

**Comment by pmksch101** [comment]
> I'm currently investigating the issue. This seems to be related to premid's extension.
my apologies if it came across like i was making the assumption of it being the changes you made that was causing the issues from an outsider i simply meant it started to happen as you made those changes

**Comment by DarkVillager** [comment]
@pmksch101 Are you using the Stable, Beta or Alpha version?

**Comment by pmksch101** [comment]
> @pmksch101 Are you using the Stable, Beta or Alpha version?
> 
> If you're on alpha simply update. If you're not please respond. ![image](https://user-images.githubusercontent.com/42322979/236623791-305556f0-5255-46d3-92b9-a7aa36ae70b0.png)

I'm on Stable v2.2.0, and that isn't an official 9anime domain, i'm aware you made it video detection instead of website detection but thought id let you know anyway

**Comment by pmksch101** [comment]
> > @pmksch101 Are you using the Stable, Beta or Alpha version?
> > If you're on alpha simply update. If you're not please respond. ![image](https://user-images.githubusercontent.com/42322979/236623791-305556f0-5255-46d3-92b9-a7aa36ae70b0.png)
> 
> I'm on Stable v2.2.0, and that isn't an official 9anime domain, i'm aware you made it video detection instead of website detection but thought id let you know anyway

Going to jump onto beta client instead hope that doesn't cause confusion now

**Comment by pmksch101** [comment]
seems to be an error with safari if you ask me, 
![image](https://user-images.githubusercontent.com/124630148/236629329-57de6534-c4eb-4611-a7f6-fd4e5db39400.jpeg)
^Safari (Doesnt Display the Status on discord)
![image](https://user-images.githubusercontent.com/124630148/236629349-a96c2c86-b8eb-496a-9333-c4ef82c22bde.jpeg)
^Chrome (Does display the status on Discord)

**Comment by DarkVillager** [comment]
> seems to be an error with safari if you ask me, ![image](https://user-images.githubusercontent.com/124630148/236629329-57de6534-c4eb-4611-a7f6-fd4e5db39400.jpeg) ^Safari (Doesnt Display the Status on discord) ![image](https://user-images.githubusercontent.com/124630148/236629349-a96c2c86-b8eb-496a-9333-c4ef82c22bde.jpeg) ^Chrome (Does display the status on Discord)
> 
> Running Stable build on both browsers

Safari has been known to be unstable.

**Comment by DarkVillager** [comment]
@Bas950 Close this issue as its related to the safari extension and not the presence.
