### ISSUE TITLE
Mangakatana | mangakatana.com

### ISSUE THREAD

**Issue by RatioGhosty** [PreMiD/Presences#7336]
### Website name

Mangakatana

### Website URL

https://mangakatana.com

### Website logo

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAD00lEQVR4AcWWA4wlXRCF32/b5tq2bdsbZ73xBmvbtm3btr3Ptnn2pGduj5Nxd1KPt+p8t25Vdat+26rBn9u0+Hu7Fv/u0KLITh2K7dKhBK30Hj3K0irs1aPSPj2q7Deg+gEDah40oPYhI+odNqIBrfFRE5rSmh8zodVxE9qcMKPdSTM6njKj82kLup2xoMdZC3rR+p6zov95KwZesEoxFQNgTKhWv1YGoLwQTwLQxgoToFwqcVpE9dM602d/bNWtKQwAxkotPkY17/lHKunahvf+3q4xFiRAmbTiV1Xpr7+2ax8UFEBpWVy2PWnE/9huqPPXDm20IABK7talE6eteeNVrXvzjyT+6xb18j+3awMFUQOMIUQzM5tqzetZmbbhgAs2jLrpYMVmDtDiuBmrnnnBYSIApPW92WICoHgq8S83qLMGSQ9QlADeSBzxBBjMnCnAllc+6f9+51MAnrqi2KP2SwDFksXfXfMa0+65YA3G8XkWEJlmwB6MwR2KYSAF0gPUIIDOG0WMBPVTHcFLd0TKAjcgB59534Xr1hB+2aJJJZoNAG84jl2vfZh+z50BoCurOhxNwBqIpakBrS+Kdky9CDz0ih3njEF8IXaekyMIReMYfNmGo/pABoAJd5x45orgKS01gIEA/+1I2n3DI0a8ZkbEznMEUIZt42cGKlFMy1SXSwew540fBzUBXDKHBIDkZ/HH8P1mDX6kURyt2BEUyDlA5f16GCjMFsJVirRmWlMDvODO5zx045DGLwH8Q793GMjDmvlo3RsC+uDl52LMZK4Aah004rkjLAHMYRGNveWUAVqyK+7bwpjByt7NGqGPFOQTCpsIPfyyHTvZIc/o35ezP1cAjXl+r1xJAF05yc4ZAjLAbAKtfOrBsiceLH/skYN8t0kDO2vgNjP2zUY1+pwx4xL92IY5B2AfQ++JgABSAb4hTBMWWWUCPLKH0YkTbvEjDybddspB/qA/AdCTwvyO9yh8jgXchWtzDNCEGbAxWMnkUbzxuRf7eK4TWf0ntH78zrVT+Hkse14E+XubBlqCfrD2jfxbbc6LZ/YQ/uJ/OQJgqiUApl0CaHTUCDWD2/1RtE/u8xHs8Qm3UgA+Zg3ouSZ9ynueNuMCM9HsiJEbM+Gz9erszYHzOj960VncjFqypWiyUxVC7nnpwTupAh1X+1Aqk5tPM3bK6sdujLxsE+uFZf+ZMP1AYSC0YmY+XJeS8roHDSie3dbLCcBPQjz3lmsATjUhrgDAD0JcCYDvhbgCAJxqUqsoAsAxKsQVAPhaiCsB8JUQV8LEE6tS9hZfVtepTC+r6gAAAABJRU5ErkJggg==

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

It would be cool if it also could show which manga that im currently reading (and maybe even the chapter???) under the name of the website. Just like with all the other manga websites 😄

**Comment by shiseni** [comment]
😉
