### ISSUE TITLE
Pinterest | Pinterest.com

### ISSUE THREAD

**Issue by AMufInABox** [PreMiD/Presences#7365]
### Steps to Reproduce

1. Go to any board or profile on pinterest (example [Here](https://www.pinterest.com/glorybesatori/tally-hall/zubin//))
2. Visit a board or any page that isnt a pin or settings page
3. Status shows up as this.
![image](https://github.com/PreMiD/Presences/assets/74741218/50f8db4a-5c22-44a7-b968-3dbf883395cf)

### Expected Behavior

Presence would show what page am I looking at or what kind of page.

### Actual Behavior

It doesn't and just shows "Viewing: blank" 

### Page URL

https://www.pinterest.com/glorybesatori/tally-hall/

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/74741218/50f8db4a-5c22-44a7-b968-3dbf883395cf)

### Operating System

Windows 11

### Browser and Version

Brave Browser | V 1.51.118

### Additional Comments

If it wasn't originally a feature it would be nice if my status could possibly also have a button to link what page I'm looking at, and if I'm looking at a pin and the name of a pin or board etc

**Comment by DarkVillager** [comment]
I will look into this.
