### ISSUE TITLE
Apple Music no Presence

### ISSUE THREAD

**Issue by Solstice1818** [PreMiD/Presences#7366]
### Steps to Reproduce

Turn Discord
Go to Apple Music site
Playing Apple Music

### Expected Behavior

just work

### Actual Behavior

there is only a phrase, "Playing", without title, cover, timestamps

### Page URL

https://music.apple.com/kr

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/131523924/0cae7650-e6ab-4bb4-bc33-7af036fe834c)

While Apple Music is playing, it just says "Playing Game...".

### Operating System

Windows 11

### Browser and Version

Chrome

### Additional Comments

![image](https://github.com/PreMiD/Presences/assets/131523924/f0d7125a-56c5-489c-ab98-5174a6c5388e)

it works when Soundcloud is playing. just that.

**Comment by karma-police-007** [comment]
download cider
its free and it has a discord rich presence in it 
https://github.com/ciderapp/Cider

**Comment by DarkVillager** [comment]
Works for me:
![image](https://github.com/PreMiD/Presences/assets/42322979/df2d10b1-35ba-4939-b5b6-674addbb202e)
