### ISSUE TITLE
WCO not working as expected

### ISSUE THREAD

**Issue by luisv555** [PreMiD/Presences#7369]
### Steps to Reproduce

https://www.wcostream.net/
After selecting a video to watch, presence is only shown as "Video Errors & Solutions" rather than the series name or episode number/title. 

### Expected Behavior

Series name, episode number and perhaps time duration should be shown on presence.

### Actual Behavior

"Video Errors & Solutions" is shown.

### Page URL

https://www.wcostream.net/attack-on-titan-season-4-episode-1-english-dubbed

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/78295252/1fda7273-d23b-403c-917d-d393436959f4)

### Operating System

Windows 11

### Browser and Version

Edge Version 111.0.1661.54

**Comment by tag27** [comment]
Solved in #8277

**Comment by LuisV** [comment]
Thank you for fixing the presence however, it seems the title is missing. Below is link I am accessing and screenshot.

https://www.wcostream.tv/bluey-season-3-episode-48-ghostbasket

![image](https://github.com/PreMiD/Presences/assets/25356297/38f167ac-5c8f-4b99-9e6d-522e15ea22e1)
