### ISSUE TITLE
HBO Max | www.max.com — update implementation

### ISSUE THREAD

**Issue by thisanickname** [PreMiD/Presences#7371]
### Presence name

HBO MAX URL CHANGED

### Description

THEY CHANGED THEIR URL

**Comment by AMufInABox** [comment]
could say the url is https://www.max.com/

**Comment by StormeTheCat** [comment]
The new url is https://play.max.com/

**Comment by thisanickname** [comment]
any updates?

**Comment by Isa27-0** [comment]
> any updates?

https://github.com/PreMiD/Presences/pull/7384
Please don't create more Issues on this same topic, be patient.

**Comment by aseluxna** [comment]
it's been months and the code still hasn't been touched. what is the hold up? 
![image](https://github.com/PreMiD/Presences/assets/113052755/f7b49724-2ff6-4fef-a4b1-c9a88ca9df3f)

**Comment by joerkig** [comment]
> it's been months and the code still hasn't been touched. what is the hold up? ![image](https://private-user-images.githubusercontent.com/113052755/306014402-f7b49724-2ff6-4fef-a4b1-c9a88ca9df3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNjI2MzIsIm5iZiI6MTcwODM2MjMzMiwicGF0aCI6Ii8xMTMwNTI3NTUvMzA2MDE0NDAyLWY3YjQ5NzI0LTJmZjYtNGZlZi1hNGIxLWM5YTg4Y2E5ZGYzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxNzA1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzdkMmFlOGVlMjg3MmI2NzY3YWM0ZThjNzdhMjY3N2M2MjBhMWM5MzY3NzM3MzAzMzAxZjA2YzEwMmIxYzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qsd50nYsXoF5eI48vUMHDIYziN5X8i_31nWG46-v6PA)

[Max is not currently available everywhere](
https://help.max.com/US/Answer/Detail/000002518#:~:text=Max%20is%20coming%20to%20the%2022%20European%20countries%20that%20currently,and%20Belgium%20later%20in%202024.&text=We%20anticipate%20that%20Max%20will%20be%20available%20in%20South%20East,stay%20tuned%20for%20more%20info.)

**Comment by theusaf** [comment]
Reopening since current fix doesn't address service features.

**Comment by DznDani** [comment]
Any updates on this fix?

**Comment by thisanickname** [comment]
any updates?

**Comment by tag27** [comment]
> any updates?

Yes (#8534)
