### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ToxisionTheTank** [PreMiD/Presences#7382]
### Steps to Reproduce

Install the extension & application
Go to youtube play some video then it works
go to sleep 
wake up
turn on pc
it dosent work
relaunch all of them
Reinstall
works
restart pc
dosent work
infinite loop

### Expected Behavior

For it to work

### Actual Behavior

Nothing worked except installation and the applications saying it works when it dosent

### Page URL

Any page Netflix, Youtube, Crunchyroll

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/134818233/af22d3d2-2543-42fc-80ff-7deb7f056c58)

### Operating System

Win11

### Browser and Version

Opera Gx Latest , Tried brave and google too

**Comment by theusaf** [comment]
This issue is unrelated to Presences in this repository. Try visiting the Discord for troubleshooting steps. Waking up the computer after sleep may cause it to be disconnected, so you will have to restart Discord/PreMiD for it to start working again sometimes.
