### ISSUE TITLE
Yugen Anime | yugenanime.tv - changed their domain from yugen.to to yugenanime.tv

### ISSUE THREAD

**Issue by RenRenIsWeird** [PreMiD/Presences#7391]
### Presence name

Yugen Anime || https://premid.app/store/presences/Yugen%20Anime

### Description

Like the title said, Yugen Anime has changed their domain to yugenanime.tv

**Comment by plskz** [comment]
Already resolve. (#7547)

**Comment by DarkVillager** [comment]
@theusaf already resolved.
