### ISSUE TITLE
New Hbo www.max.com

### ISSUE THREAD

**Issue by thisanickname** [PreMiD/Presences#7396]
### Website name

Max

### Website URL

www.max.com

### Website logo

https://brandemia.org/contenido/subidas/2023/04/logo-max-no-hbo-1200x670.jpg

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [X] It is region restricted

### Description

new hbo max

**Comment by Isa27-0** [comment]
Duplicate of #7371
