### ISSUE TITLE
mangafire | mangafire.to

### ISSUE THREAD

**Issue by lizsdswsd** [PreMiD/Presences#7417]
### Website name

mangafire.to

### Website URL

https://mangafire.to/

### Website logo

https://cdn.discordapp.com/attachments/1019894854123278379/1116549089820160080/image.png

### Prerequisites

- [ ] It is a paid service
- [X] It displays NSFW content
- [ ] It is region restricted

### Description

example:
![presence tab](https://github.com/PreMiD/Presences/assets/130219109/b2ffa1da-491e-4c0a-9323-bbb94ee4246a)

**Comment by Isa27-0** [comment]
https://premid.app/store/presences/MangaFire

P.S: Remember to check this option in the store when looking for certain types of presence.
![image](https://github.com/PreMiD/Presences/assets/68751594/542dd19b-0071-45c7-b6f6-0b54d4bc153d)
