### ISSUE TITLE
FanFiction.Net | fanfiction.net

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#7420]
### Website name

FanFiction.Net

### Website URL

https://www.fanfiction.net (Mobile version: https://m.fanfiction.net)

### Website logo

https://play-lh.googleusercontent.com/P_T-8o-NJxOhQxjYPjbfc5K_XEOfvea2hWJuQiiy8NdJUyL6mJoWK_9FPh89ZPxGMK8

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Presence name, work name and chapter names, similar to other presences like AO3 and Spirit Fanfiction.

**Comment by Isa27-0** [comment]
P.S: It has a sister site called FictionPress.com (https://www.fictionpress.com) which only houses original content, but I'm not sure if I create another service request or edit it to make two sites in a single Issue.

**Comment by theusaf** [comment]
Considering that they are different, and there isn't a huge amount of sister sites, another service request may make more sense.

**Comment by Isa27-0** [comment]
> Considering that they are different, and there isn't a huge amount of sister sites, another service request may make more sense.

Thanks

**Comment by Isa27-0** [comment]
https://premid.app/store/presences/Fanfiction 
I should have researched beforehand.
