### ISSUE TITLE
taiko web | taiko.bui.pm - removed

### ISSUE THREAD

**Issue by ilovetaikonotatsujin** [PreMiD/Presences#7422]
### Steps to Reproduce

I cant play it

### Expected Behavior

Me playing Joubutsu2000

### Actual Behavior

Can’t play

### Page URL

https://taiko.bui.pm/

### Screenshots

![IMG_1711](https://github.com/PreMiD/Presences/assets/136159056/0c392b0a-ae32-4a82-853a-695bf60bc132)

### Operating System

iPad 16.5

### Browser and Version

Safari

### Additional Comments

Pls fix

**Comment by joerkig** [comment]
This isn't the repo for the taiko website, all we can do is remove the presence from the store since the website no longer exists

**Comment by Isa27-0** [comment]
Also, @ilovetaikonotatsujin, I believe you are in the wrong repository. PreMiD is only responsible for a presence and we are not connected to the Taiko Web project.
