### ISSUE TITLE
PreMid presence not appearing on Discord

### ISSUE THREAD

**Issue by Vxmpris** [PreMiD/Presences#7423]
### Steps to Reproduce

1. Open Discord
2. Run PreMid, then the browser you're using.
3. Go onto the website that's added as a Presence on PreMid and go back to Discord. 

### Expected Behavior

I expected Discord to pick up PreMid as a presence and display

### Actual Behavior

Discord didn't pick up/detect PreMid and didn't show it on my activity status although PreMid and the extension is running perfectly fine with no errors being picked up.

### Page URL

There's no page URL it's just that PreMid don't wanna work.

### Screenshots

![image_2023-06-10_153821652](https://github.com/PreMiD/Presences/assets/136179389/debc62fc-9623-4200-9e56-1aa46b969fae)

### Operating System

Windows 11

### Browser and Version

Opera GX (Idk the latest but I'm pretty sure whatever the latest one is, it's the one I have since there's no updates available) 

### Additional Comments

I did join the Discord and check the support channel and it told me to do this since I had the "Uncaught (in promise) undefined" error occurring.

**Comment by Isa27-0** [comment]
This repository is for presences only. If you're having a problem with PreMiD, go to the [troubleshooting page](https://docs.premid.app/en/troubleshooting) or the Discord server.
