### ISSUE TITLE
Podurama | podurama.com

### ISSUE THREAD

**Issue by JaxzKyd** [PreMiD/Presences#7428]
### Website name

Podurama

### Website URL

https://podurama.com/home

### Website logo

https://styles.redditmedia.com/t5_3g9ubx/styles/communityIcon_iugewhks9t061.png?width=256&v=enabled&s=9851af33833c0fffb02aef5f14c41d5f3cb6dad7

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

It should display the name of the app (Podurama), the name and episode of the currently playing podcast, as well as the podcast artwork
Kinda like the Google Podcast presence, but with the podcast artwork. 

![image](https://github.com/PreMiD/Presences/assets/39567321/a8677357-0492-4f5e-829d-f84ebb18fb32)

(a time remaining counter or a progress bar would also be nice, but idk if that's wildly difficult :P)

**Comment by JaxzKyd** [comment]
Different link to the website logo if the original one didn't suffice
https://i.imgur.com/CNkpXlB.png

**Comment by ION606** [comment]
I can try to work on this :3

**Comment by JaxzKyd** [comment]
OMG thank you!!! I truly thought this would go buried forever 😭

Also they changed their icon from the one I provided above, here is an updated link!
https://play-lh.googleusercontent.com/UI8afJLB0StFFz7RT3ZQP8rR1u3udBiseOssKsM58q_fTA2nYBpdknGwDGHL7hAxe4Fi=w480-h960 \ https://i.imgur.com/lTL13Yk.png

**Comment by ION606** [comment]
> OMG thank you!!! I truly thought this would go buried forever 😭
> 
> 
> 
> Also they changed their icon from the one I provided above, here is an updated link!
> 
> https://play-lh.googleusercontent.com/UI8afJLB0StFFz7RT3ZQP8rR1u3udBiseOssKsM58q_fTA2nYBpdknGwDGHL7hAxe4Fi=w480-h960 \ https://i.imgur.com/lTL13Yk.png

oh LMAO I just yoinked it from their website, also npnp ^^
