### ISSUE TITLE
Fbox.to picture of what show you are watching

### ISSUE THREAD

**Issue by KitAzren4401** [PreMiD/Presences#7431]
### Presence name

Fbox.to

### Description

Fbox.to used to have a feature where you can see what show you are watching and how long you are watching in your discord status now its gone.  

As you can see in the image below, the picture of what show you are watching is not present anymore

![](https://cdn.discordapp.com/attachments/1005435402859061329/1118812408807440394/image.png)

**Comment by DarkVillager** [comment]
I will look into this when I can.
