### ISSUE TITLE
diep.io rich presence

### ISSUE THREAD

**Issue by bryaby-bruh** [PreMiD/Presences#744]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**

bryaby#5749
**What's the name of the service?**

https://www.diep.io
**What should the Presence display?**

"Playing diep.io
 (name of gamemode)
 Level: (number)"
**If possible, please provide a logo for the service (512x512 minimum)**

![8JVBeJ-d_400x400](https://user-images.githubusercontent.com/58602008/70336746-ff1d2200-1849-11ea-95f6-f85a57192f8d.jpg)

**Comment by Alanexei** [comment]
I'll see if I can work on this one

**Comment by Bas950** [comment]
@Alanexei I tried, but couldnt get any data :/

**Comment by Alanexei** [comment]
> @Alanexei I tried, but couldnt get any data :/

Oh no :/

**Comment by Bas950** [comment]
> > @Alanexei I tried, but couldnt get any data :/
> 
> Oh no :/

![image](https://user-images.githubusercontent.com/34792838/71011168-3f538e80-20ed-11ea-90b4-9148c686d881.png)
Only thing I could say and couldnt find it in scripts.

**Comment by doomlerd** [comment]
Sorry @bryaby-bruh , can't be added due to technical limitations.

**Comment by bryaby-bruh** [comment]
alright, thanks anyway
