### ISSUE TITLE
Disney+ PH | disneyplus.com - still bugged

### ISSUE THREAD

**Issue by mamasitamamamia** [PreMiD/Presences#7448]
### Steps to Reproduce

![image_2023-06-28_032932188](https://github.com/PreMiD/Presences/assets/135991918/6a1b90f6-58f0-4a7d-b76a-217750bfed72)

### Expected Behavior

show what movie or series watch status

### Actual Behavior

stuck on "browsing" + timestamp latest fix working fine

### Page URL

https://www.apps.disneyplus.com/ph/movies/life-of-pi/1770000706/watch?filters=content_type%3Dmovie&fromBeginning=true

### Operating System

Windows 10

### Browser and Version

Opera, latest version

**Comment by DarkVillager** [comment]
Interesting. Which country are you using disney+ from?

**Comment by mamasitamamamia** [comment]
> Interesting. Which country are you using disney+ from?

philippines
