### ISSUE TITLE
Coursera | www.coursera.org

### ISSUE THREAD

**Issue by PedroBrantes** [PreMiD/Presences#7450]
### Website name

Coursera

### Website URL

https://www.coursera.org

### Website logo

https://d3njjcbhbojbot.cloudfront.net/web/images/favicons/android-chrome-v2-192x192.png

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Display the name of the course being studied along with the related videos and forums.

**Comment by Isa27-0** [comment]
Duplicate of #5274
