### ISSUE TITLE
Cuevana3 | cuevana3.ch - domain changed

### ISSUE THREAD

**Issue by Kadabra477** [PreMiD/Presences#7454]
### Steps to Reproduce

The presence of "Cuevana3" does not work, I do not show anything in discord, I think it is because they changed the domain of the page and it is not updated in the presence
(Im not speak english, in from Argentina Spanish)

### Expected Behavior

Read Steps to Reproduce

### Actual Behavior

No solutión

### Page URL

https://www11.cuevana3.ch/peliculas?page=4

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/120063236/bece302d-731c-4be1-9d70-3d45bc7ec116)
https://premid.app/store/presences/Cuevana%203

### Operating System

Windows 10

### Browser and Version

Opera GX, Google Chrome, Brave

### Additional Comments

This is presence
https://premid.app/store/presences/Cuevana%203

**Comment by DarkVillager** [comment]
Can reproduce

**Comment by Kadabra477** [comment]
¿Solution?

**Comment by DarkVillager** [comment]
> ¿Solution?

Patience. I will fix it when I have time.
