### ISSUE TITLE
myCANAL | www.canalplus.com - details not showing properly

### ISSUE THREAD

**Issue by TheLouD1** [PreMiD/Presences#7458]
### Steps to Reproduce

any channel actually, picked the first one that came in the live section. I started a movie on replay and it displayed everything properly (screenshot 1) but on live it just shows that im looking for a channel. Sadly cant screen that im ACTUALLY watching a chan cause canal puts a black screen .. 

### Expected Behavior

display the program and or channel

### Actual Behavior

showing "is navigating" 

### Page URL

https://www.canalplus.com/live/?channel=312

### Screenshots

![2023-07-01 19_49_23-#general _ BTS SIO - Discord](https://github.com/PreMiD/Presences/assets/70957994/b0b82157-9a03-4b72-bf73-a14f69f5720b)
not displaying the channel nor the show

![image](https://github.com/PreMiD/Presences/assets/70957994/ccd86fdc-df80-40c7-9e69-7b1162ae28ac)
even tho im watching one 

![image](https://github.com/PreMiD/Presences/assets/70957994/86a9a093-c4e9-43d7-a7c4-fc77c364c46b)
not live 

![image](https://github.com/PreMiD/Presences/assets/70957994/b1412832-07a9-4f5c-b9e8-395bf322c127)
and it works

### Operating System

win11

### Browser and Version

brave v 114 1 52 129

**Comment by TheLouD1** [comment]
actually, it works on replay and only on canal + channels

![image](https://github.com/PreMiD/Presences/assets/70957994/dbba93c1-e0b9-4aed-ae45-7a57496d8ea5)
here is a replay from another channel 

![image](https://github.com/PreMiD/Presences/assets/70957994/a8d2f7dc-aabe-4d3c-a54f-46a8cd2fd1bf)
and what it shows up in discord

**Comment by itsmelouis** [comment]
I can reproduce, here's the proof and the issue:

![image](https://github.com/PreMiD/Presences/assets/72155852/c3c4931f-5a09-45c0-bf25-8e8a194f94dc)

Please assign me this issue, I will fix it shortly.

**Comment by TheLouD1** [comment]
re-opening cause it's happening again 
![watching](https://github.com/PreMiD/Presences/assets/70957994/b0b5fb3b-20a7-4bce-8a97-293f28a622e0)
![proof](https://github.com/PreMiD/Presences/assets/70957994/78ab09c6-90ca-49cc-92c2-6ebf80c3ff73)
