### ISSUE TITLE
Audius, audio sharing service similar to SoundCloud

### ISSUE THREAD

**Issue by wolvvo** [PreMiD/Presences#746]
**Prerequisites and essential questions** 
* [growing? more people will probably move after soundcloud's new ToS] Is it a popular site?
* [Founded 2018] Is the website older than 2 months? 
* [not sure] Is the site locked to a specific country/region?
* [no] Is the site a paid service? (e.g. Netflix, Hulu)
* [nope] Are you a donator/patron?
* [yes] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**

**What's the name of the service?**

https://audius.co/   /   https://audius.co/diversa <- random artist's page
**What should the Presence display?**

what song is playing, name of artist and where you are in the song. same as soundcloud's discord prescence.
**If possible, please provide a logo for the service (512x512 minimum)**

https://miro.medium.com/max/3150/1*A7Tba_FmCe4FX33i6u4r9w.jpeg

**Comment by frozaum** [comment]
I WAS WAITING SOMEONE TO DO A REQUEST OF THAT 🙏

**Comment by doomlerd** [comment]
Please make sure to fill in the prerequisites correctly and make the request again ( like this #744 ).
