### ISSUE TITLE
Holodex | Add option to use VTuber channel image fetched from YouTube

### ISSUE THREAD

**Issue by RoonMoonlight** [PreMiD/Presences#7461]
### Presence name

Holodex

### Description

Unlike YouTube Presence, Holodex Presence does not have option to change icons by default. Would be great if there is option to change Holodex icon to VTuber's channel image.

### Alternatives

None.

### Additional context

None.

**Comment by DarkVillager** [comment]
Is the image also on holodex or only on youtube?

**Comment by RoonMoonlight** [comment]
> Is the image also on holodex or only on youtube?

It uses YouTube Channel Icons from Holodex

**Comment by DarkVillager** [comment]
I will do this. Just give me a day or two.
