### ISSUE TITLE
E-PAL | www.epal.gg

### ISSUE THREAD

**Issue by AYARI55** [PreMiD/Presences#7462]
### Presence name

Epal.gg

### Description

i want u to add epal.gg bcs ther is more than 5K ppl use that weeb site
https://www.epal.gg/

### Alternatives

https://www.epal.gg/

### Additional context

![Annotation 2023-07-02 141640](https://github.com/PreMiD/Presences/assets/138377204/e275a016-1f49-4ac3-9c63-20985576c56c)

**Comment by Isa27-0** [comment]
Watermelon took the wrong form. Feature Request is for suggesting new features for an existing presence. Use the [Service Request](https://github.com/PreMiD/Presences/issues/new?assignees=&labels=service+request&projects=&template=service_request.yml), which is for suggesting new presences.

**Comment by DarkVillager** [comment]
@AYARI55 I'm working on it.

**Comment by DarkVillager** [comment]
@theusaf close this pretty please

**Comment by AYARI55** [comment]
Did they added

**Comment by theusaf** [comment]
> Did they added

Yes. #7659
