### ISSUE TITLE
Premid not working at all

### ISSUE THREAD

**Issue by BereznikiSigmaMale** [PreMiD/Presences#7473]
### Steps to Reproduce

1. Open discord
2. Play any media etc that is connected visa presence 

### Expected Behavior

I expect to see the piece of media being depicted in the discord

### Actual Behavior

Nothing, Discord acts as if Premid didn't exist

### Page URL

Discord.com

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/87782981/6fb2c951-c773-4902-8ecd-7db1518f02f9)

### Operating System

Windows 10

### Browser and Version

Chrome 114.0.5735.199

**Comment by DarkVillager** [comment]
@BereznikiSigmaMale is a specific presence not working or premid in general?

**Comment by BereznikiSigmaMale** [comment]
Premid in general, niether soundcloud nor youtube showed up

**Comment by lizsdswsd** [comment]
it sometimes works for me
