### ISSUE TITLE
MoviesJoy | moviesjoy.is

### ISSUE THREAD

**Issue by lizsdswsd** [PreMiD/Presences#7485]
### Website name

MoviesJoy | moviesjoy.is

### Website URL

https://moviesjoy.is/

### Website logo

https://imgur.com/nIBrA95

### Prerequisites

- [ ] It is a paid service
- [X] It displays NSFW content
- [ ] It is region restricted

### Description
MoviesJoy is a streaming website where you can find almost any title that comes to mind to stream or download. We provide free movies and TV shows for every genre and occasion such as Action, Comedy, History, Thriller, Sports... New titles are updated on a daily basis to make sure you never need to leave.
MoviesJoy is one of the biggest gems you can find when it comes to free online movie streaming. More than ten thousands of titles are free for you to watch online or download with zero ads. Normally movie enthusiasts have to pay for paid content or sit through multiple ads and popups, but at MoviesJoy, all you need is the Internet, a device, and your time to enjoy our contents. 

### Quick suggestion of what i want in this extension
showing what show/movie i am watching. timestamps (being able to remove them aswell, buttons (to have the ability to remove the link to see the video), search info, AH and language pls, etc.
For ex;
1).
![image](https://github.com/PreMiD/Presences/assets/130219109/7976c836-ee6d-4323-bf19-79f602fe5810)
2).
![premd proof](https://github.com/PreMiD/Presences/assets/130219109/0ff2654e-5b75-4a1e-848f-5ad16e54b046)

**Comment by DarkVillager** [comment]
@theusaf please close this.
