### ISSUE TITLE
Omegle | omegle.com

### ISSUE THREAD

**Issue by slademcg** [PreMiD/Presences#7488]
### Website name

Omegle

### Website URL

omegle.com

### Website logo

https://www.omegle.com/static/icon.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Show if someone is using omegle, how long they've been on it, and what tag(s) they are using

**Comment by Isa27-0** [comment]
The website is dead.
![image](https://github.com/PreMiD/Presences/assets/68751594/e777bc45-3ae0-4c5e-88cc-0feb6b72917a)
