### ISSUE TITLE
9anime | https://9animehq.to 

### ISSUE THREAD

**Issue by REDENHEIST** [PreMiD/Presences#7497]
### Steps to Reproduce

1. Go to https://9animehq.to
2.  Search/Find a anime or movie
3.  watch the anime

### Expected Behavior

Should show the name of the anime with picture

### Actual Behavior

Shows site name and sub/dub and wrong episode number & without anime poster.

### Page URL

https://9animehq.to

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/103301514/e99f6983-6186-4d6a-86a5-3a08b95a2bfd)
![image](https://github.com/PreMiD/Presences/assets/103301514/3b876dd2-ae7f-4881-8518-39ca9c29017a)

### Operating System

WIndows 10

### Browser and Version

Brave Browser | Version 1.52.130 Chromium: 114.0.5735.198 (Official Build) (64-bit) 

### Additional Comments

the other domains of 9anime are banned in India and we only got this 9animehq.to working. Please help

**Comment by theusaf** [comment]
Confirmed. This is likely because those domains (hq) have a different ui.

**Comment by REDENHEIST** [comment]
Yes I figured but I can't access other domains. I was hoping the Presence developer can fix it

**Comment by DarkVillager** [comment]
> Yes I figured but I can't access other domains. I was hoping the Presence developer can fix it

On it.
