### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Tohsakass** [PreMiD/Presences#7498]
### Steps to Reproduce

It doesn't show up any statuses, like the video I'm watching on YT or something. The only thing that shows up is when I'm in the premid shop.

### Expected Behavior

That the statuses appeared

### Actual Behavior

The statuses don't look like in DC

### Page URL

https://premid.app/store

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/139945885/650a2679-38fe-44f8-ae51-50da5368df90)

No status appears outside of that.

![image](https://github.com/PreMiD/Presences/assets/139945885/40c8aab6-091e-4e54-858e-e4d94735c711)

### Operating System

Windows 10

### Browser and Version

Opera Gx

**Comment by theusaf** [comment]
This does not look like a relevant issue to this repository. For issues about the extension or app, visit the relevant support forum.
