### ISSUE TITLE
9anime | 9anime.to - Some anime doesn't show presence

### ISSUE THREAD

**Issue by Extiriority** [PreMiD/Presences#7508]
Probably not supported in older animes?

### Steps to Reproduce

1. click on on this specific anime on .to domain https://9anime.to/watch/golden-boy.70l1/ep-1 or https://9anime.to/watch/urusei-yatsura.z18p/ep-33
2. See discord profile - Only shows: Browsing...

### Expected Behavior

watching GOLDEN BOY
or
watching urusei yatsura

### Actual Behavior

Browsing...

### Page URL

https://9anime.to/watch/golden-boy.70l1/ep-1
https://9anime.to/watch/urusei-yatsura.z18p/ep-33

### Operating System

windows 11

### Browser and Version

Google Chrome 115.0.5790.102

**Comment by Isa27-0** [comment]
I was able to reproduce the bug. But strangely I can't inspect the site.
![image](https://github.com/PreMiD/Presences/assets/68751594/2c0261d5-4a56-4dc9-94ab-90b381f80347)

https://github.com/PreMiD/Presences/assets/68751594/a9bd9711-f5cd-4ed8-9343-fe267c2d9b1f

**Comment by Extiriority** [comment]
That is because 9anime enforce anti inspection so that is harder to copy the site. There is a way to deactivate the constant debugger but I'm not sure how.


> I was able to reproduce the bug. But strangely I can't inspect the site.
> 
> ![image](https://github.com/PreMiD/Presences/assets/68751594/2c0261d5-4a56-4dc9-94ab-90b381f80347)
> 
> 
> 
> https://github.com/PreMiD/Presences/assets/68751594/a9bd9711-f5cd-4ed8-9343-fe267c2d9b1f
> 
> 
> 
> ------------------------
> 
> 
> 
> OS: Windows 10
> 
> Browser: Opera GX LVL 5 (core: 99.0.4788.86)
> 
> 
> 
> 
> 
> 
> 
> 
> 
>

**Comment by Isa27-0** [comment]
> That is because 9anime enforce anti inspection so that is harder to copy the site. There is a way to deactivate the constant debugger but I'm not sure how.

Oh, I get it.

**Comment by Mk2Lighty** [comment]
9anime used to show one piece for me and many other animes but now it shows browsing...

**Comment by jirka000** [comment]
I also have the same issue.
