### ISSUE TITLE
 | Service URL

### ISSUE THREAD

**Issue by deezpiggywet** [PreMiD/Presences#7510]
### Steps to Reproduce

https://fmovies.to/home

### Expected Behavior

its supposed to show what move im watching,time laps like when the movie will finish

### Actual Behavior

its just showing elapsed{time u spent on the site} but its not showing what ur looking at like a series or a movie like the name it just shows elapse 

### Page URL

https://fmovies.to/genre/action?page=2

### Screenshots

<img width="1280" alt="Screen Shot 2023-07-22 at 4 10 34 AM" src="https://github.com/PreMiD/Presences/assets/140237715/dccac6b9-4604-423d-a051-e664923c2d66">

### Operating System

macOS big sur 11.7.8

### Browser and Version

google latest verison 115.0.5790.98

### Additional Comments

<img width="1280" alt="Screen Shot 2023-07-22 at 4 15 25 AM" src="https://github.com/PreMiD/Presences/assets/140237715/b859320b-72bd-4ae7-9547-299d0455aad8">
<img width="1280" alt="Screen Shot 2023-07-22 at 4 15 34 AM" src="https://github.com/PreMiD/Presences/assets/140237715/378af4aa-a7f5-465a-8909-30772aa501be">

**Comment by DarkVillager** [comment]
@deezpiggywet I will fix this.

**Comment by Isa27-0** [comment]
Huh, this Issue is not similar to #7211?

**Comment by deezpiggywet** [comment]
Thank uSent from my iPhoneOn Jul 22, 2023, at 7:51 AM, Dark_Ville ***@***.***> wrote:﻿
@deezpiggywet I will fix this.
