### ISSUE TITLE
Anix | anix.to

### ISSUE THREAD

**Issue by ephoroc** [PreMiD/Presences#7519]
### Website name

Anix

### Website URL

https://anix.to/

### Website logo

https://cdn.discordapp.com/attachments/1069829519000744027/1132862867708850176/logo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Same thing like any other anime website presence.

**Comment by ms5984** [comment]
Attempting to inspect any subpage causes Chrome DevTools' debugger to pause, and eventually terminates rendering before redirecting the user back to the homepage. Is there any way realistically to make a presence through reverse-engineering or should I put in a request to Anix directly? (If perhaps they could provide some guidance, or in the best case release an official presence.)
