### ISSUE TITLE
Disney+ | apps.disneyplus.com - presence doesn't show the show/movie your watching

### ISSUE THREAD

**Issue by OmriOn** [PreMiD/Presences#7531]
### Steps to Reproduce

1. Go to https://www.apps.disneyplus.com/il
2. Select any show or movie to watch

### Expected Behavior

Discord RPC shows show name and episode

### Actual Behavior

Discord RPC only says "Disney+" 

### Page URL

https://www.apps.disneyplus.com/il

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/76548146/d9d0995f-f870-47c2-89bc-7d6a87cc472e)

### Operating System

Windows 11

### Browser and Version

Google Chrome Version 114.0.5735.248

**Comment by veryCrunchy** [comment]
@theusaf ditto
