### ISSUE TITLE
Nitter | nitter.net

### ISSUE THREAD

**Issue by RoonMoonlight** [PreMiD/Presences#7540]
### Website name

Nitter

### Website URL

https://nitter.net

### Website logo

https://nitter.net/logo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description
**Notice: There is more instances besides nitter.net and can be [found here](https://github.com/zedeus/nitter/wiki/Instances).** IT IS SERVICE REQUEST THAT ALL INSTANCE SHOULD BE SUPPORTED!

Nitter is a free and open source alternative Twitter / X front-end focused on privacy and performance. Due to open-source nature, anyone can host the service. It also allows you to view someone's profile anonymously without login.

Would be great if you could make Profile avatar display when browsing someone's profile.

**Comment by RoonMoonlight** [comment]
Link to the repository: https://github.com/zedeus/nitter

**Comment by SaiasiZKS** [comment]
I agree, they should add this.
