### ISSUE TITLE
AniWave (9Anime)

### ISSUE THREAD

**Issue by SaiasiZKS** [PreMiD/Presences#7543]
### Presence name

Aniwave (9Anime)

### Description

9Anime has recently changed to aniwave.to , due to DMCA strikes and ISP blocking. The presence needs to update to it, or else it just doesn't work. 

Also on a sidenote, although almost all other official domains now redirect to aniwave.to , they have decided to keep 9animehq.to and 9animeto.io , as they are for alternate UI. It would be nice to implement those websites into this presence, although not nearly as necessary as changing to aniwave.to .

### Additional context

![image](https://github.com/PreMiD/Presences/assets/79766171/bcc72e59-1fae-4f34-bdcc-85532c5d1fa0)

proof from the official subreddit of the change:
![image](https://github.com/PreMiD/Presences/assets/79766171/b0472106-0afe-4877-a97b-791f49b72d17)

**Comment by Extiriority** [comment]
We are already aware of it, I (9a staff) told this situation in discord already #7546

**Comment by SaiasiZKS** [comment]
> We are already aware of it, I (9a staff) told this situation in discord already #7546

Oh okay! Thanks for responding!
