### ISSUE TITLE
anime-odcinki | anime-odcinki.pl 

### ISSUE THREAD

**Issue by Ezzker** [PreMiD/Presences#7548]
### Website name

anime-odcinki

### Website URL

https://anime-odcinki.pl/

### Website logo

A logo of the site

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [X] It is region restricted

### Description

I don't know what means "region restricted" but I checked it because this is is a Polish site but everyone can join her and watch I guess, just polish subtitles. 
Sorry if I did something wrong but I am doing it by first time :c 
Thanks for your patient and kindly please add this presence <3 

BIG THANKS AN LOVE ~Ezzker

**Comment by DarkVillager** [comment]
@Ezzker Do you have discord. If so please add me: @Dark_Ville

**Comment by Isa27-0** [comment]
> I don't know what means "region restricted" but I checked it because this is is a Polish site but everyone can join her and watch I guess, just polish subtitles.

I was in doubt if it was region restricted (Since it is the case that some domain is inaccessible in another country, and it does not have much to do with language) but I went to visit the site to remove these doubts. And yeah, the domain is really restricted (At least here in Brazil).

![image](https://github.com/PreMiD/Presences/assets/68751594/3812f7fd-8e9d-412d-85f6-81b483f5bd1e)

**Comment by Ezzker** [comment]
you can use vpn :D


sob., 5 sie 2023 o 00:20 #27 ***@***.***> napisał(a):

**Comment by Isa27-0** [comment]
> you can use vpn :D 

Yeah, I did that and I was able to access it normally, I was just thinking that the domain didn't have that restriction.

**Comment by Ezzker** [comment]
add me on discord: martinmobbyn

sob., 5 sie 2023 o 00:47 #27 ***@***.***> napisał(a):

**Comment by DarkVillager** [comment]
> > I don't know what means "region restricted" but I checked it because this is is a Polish site but everyone can join her and watch I guess, just polish subtitles.
> 
> I was in doubt if it was region restricted (Since it is the case that some domain is inaccessible in another country, and it does not have much to do with language) but I went to visit the site to remove these doubts. And yeah, the domain is really restricted (At least here in Brazil).
> 
> ![image](https://user-images.githubusercontent.com/68751594/258538691-3812f7fd-8e9d-412d-85f6-81b483f5bd1e.png)

It works for me (netherlands)
