### ISSUE TITLE
Character.ai | beta.character.ai

### ISSUE THREAD

**Issue by Razor7100** [PreMiD/Presences#7573]
### Website name

character.ai

### Website URL

https://beta.character.ai/

### Website logo

https://characterai.io/i/80/static/topic-pics/cai-light-on-dark.jpg

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

its partly paid, the characters arent locked behind the paywall its just these
![image](https://github.com/PreMiD/Presences/assets/121650332/4c8fab9d-45a9-4c6d-9a83-d84e70bc9dc6)
and to clear this up, i am not the website owner nor do i know the owner

**Comment by Isa27-0** [comment]
The site is not paid. Technically, paid sites are precisely those that can only be accessed for a payment (Ex: Netflix).

**Comment by Razor7100** [comment]
okay

**Comment by karma-police-007** [comment]
can we maybe have the free version of the site then?
