### ISSUE TITLE
ANIMETV7

### ISSUE THREAD

**Issue by Mathe2005** [PreMiD/Presences#7586]
### Website name

ANIMETV7

### Website URL

https://animetv7.com

### Website logo

https://media.discordapp.net/attachments/1140705701556146286/1141727410786684979/Luffy.jpg

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

What anime curently user viewing, what episode watching. Thats all i want to see as presence. Thanks.

**Comment by jamiereynolds1989** [comment]
Did they respond to your request?
