### ISSUE TITLE
SparkNotes | https://www.sparknotes.com

### ISSUE THREAD

**Issue by ELITE-NOTORIOUS-Supremacist** [PreMiD/Presences#760]
**Prerequisites and essential questions** 
* [x] Is it a popular site? Very likely
* [x] Is the website older than 2 months?  Yes
* [ ] Is the site locked to a specific country/region? No
* [ ] Is the site a paid service? (e.g. Netflix, Hulu) No
* [ ] Are you a donator/patron? No
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? Yes

**What's your Discord username?**  The NOTORIOUS7302#4624

**What's the name of the service?** 
https://www.sparknotes.com | SparkNotes
**What should the Presence display?**  The name of the story/play in what the user is reading. Examples can be page number, scene number and act.

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by doomlerd** [comment]
Has been added for a while :
https://premid.app/store/presences/Sparknotes
