### ISSUE TITLE
Tidal | listen.tidal.com - Presence errors on Firefox

### ISSUE THREAD

**Issue by R2D2VaderBeef** [PreMiD/Presences#7620]
### Steps to Reproduce

1. Install the PreMiD extension on Firefox from the [Downloads page](https://premid.app/downloads)
2. Install the Tidal presence from the [store](https://premid.app/store/presences/Tidal)
3. Navigate to Tidal's web player at [listen.tidal.com](https://listen.tidal.com/)
4. Play a song

### Expected Behavior

The rich presence appears on Discord, no errors in the browser console.

### Actual Behavior

The presence does not appear on Discord and errors spam in the console.

### Page URL

https://listen.tidal.com/

### Screenshots

Errors are spamming in the console while a song plays. They sometimes spam without a song even playing
![image](https://github.com/PreMiD/Presences/assets/52345992/b4646825-dd5e-4105-a515-2b6f0a88ba16)

Sometimes, "Tidal" with no further information flashes up on my Discord presence, before disappearing. 
![image](https://github.com/PreMiD/Presences/assets/52345992/149523a2-2e38-4bee-b036-909ec40a1f50)

### Operating System

Windows 11

### Browser and Version

Firefox 117.0

### Additional Comments

This error shows up once when the page loads, from `devHelper.js:1:1`
```
SyntaxError: redeclaration of let Presence
    <anonymous> moz-extension://ac2f731f-6b66-43f2-8f1f-fb5555ba18c1/js/devHelper.js:1
    inject resource://gre/modules/ExtensionContent.sys.mjs:581
    AsyncFunctionNext self-hosted:852
```

This error is spammed repeatedly, many times a second from `presence.ts:73:38`
```
TypeError: s is null
```

The Tidal presence currently works fine on Edge with no errors in console.

**Comment by VirusBLITZ** [comment]
I can't reproduce this on Firefox 119.0, Win 10, no errors from the presence in the console either...

**Comment by R2D2VaderBeef** [comment]
Seems to work now, thanks for letting me know
