### ISSUE TITLE
Osn new presence

### ISSUE THREAD

**Issue by Almukhtar1** [PreMiD/Presences#7622]
### Website name

Osn+

### Website URL

https://osnplus.com/

### Website logo

https://www.osn.com/osn/media/OSNMedia/osn-tv-home/apps-icon/osnplus-app.svg

### Prerequisites

- [X] It is a paid service
- [ ] It displays NSFW content
- [X] It is region restricted

### Description

same as netflix / Hbo

**Comment by theusaf** [comment]
Duplicate of #6827
