### ISSUE TITLE
YouTube Music: Remaining time doesn't get displayed correctly

### ISSUE THREAD

**Issue by ACertainCoder** [PreMiD/Presences#763]
**Describe the Bug**
When the current song changes automatically (in a playlist as sample), the presence starts showing invalid data about the remaining time.

**Steps to Reproduce**
1. Start listening to a playlist
2. Wait until a song has less than 30 seconds left
3. Look at the presence

**Expected Behavior**
It should still display correct informations, but it doesn't.

**Screenshots**
https://cdn.discordapp.com/attachments/573863189868052500/654052729081167873/2019-12-10_21-08-13.mp4
Well... I think a video is for this more useful. xD

**Environment**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 71.0 (64-Bit)
 
**Additional context**
This only happens when the song changes automatically. When you select one yourself, it works just fine.

**Comment by doomlerd** [comment]
@Bas950 @Timeraa

**Comment by Timeraa** [comment]
Will recode it soon

**Comment by doomlerd** [comment]
Cannot be reproduced, try with the most recent update and make another PR if the issue still occurs.
