### ISSUE TITLE
Roblox | devforum.roblox.com - add option to only show devforum

### ISSUE THREAD

**Issue by JustLeska** [PreMiD/Presences#7635]
### Website name

Roblox DevForum

### Website URL

https://devforum.roblox.com/

### Website logo

https://devforum-uploads.s3.dualstack.us-east-2.amazonaws.com/uploads/original/4X/5/2/b/52bce3b02f6c5dddf9dfd5390fa00a9b2be6fa38.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

it would be cool to display what post I am looking at and what profile (just like the github presence).

**Comment by Isa27-0** [comment]
It was already added about 2 years ago(#5128). Probably the presence broke in this subdomain and no longer shows.

**Comment by JustLeska** [comment]
> Already added within the Roblox presence about 2 years ago (#5128). Probably the presence broke in this subdomain and no longer shows.

Yep, it works but I would like (if possible) an option to disable the normal roblox presence as I use Bloxstrap and I only need teh devforum presence.
