### ISSUE TITLE
Service Name | Service URL

### ISSUE THREAD

**Issue by Tanishk7988** [PreMiD/Presences#7652]
### Steps to Reproduce

https://www.youtube.com/ 
after opening the page click on any video and the presence status will not show 

### Expected Behavior

i thought thata it will show the presence on discord 

### Actual Behavior

it did not worked

### Page URL

https://www.youtube.com/

### Operating System

windows 11

### Browser and Version

google chrome  and latest version

**Comment by DarkVillager** [comment]
Youtube | Youtube.com

**Comment by theusaf** [comment]
Duplicate of #6370
