### ISSUE TITLE
Kindle | read.amazon.com

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#7694]
### Website name

Kindle

### Website URL

https://read.amazon.com

### Website logo

https://play-lh.googleusercontent.com/48wwD4kfFSStoxwuwCIu6RdM2IeZmZKfb1ZeQkga0qEf1JKsiD-hK3Qf8qvxHL09lQ

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Name of the book, name of the author and the time it has been on the page.

P.S: This is a 'remake' of a Service Request (#2135) I had made before (And for some reason, I closed it). I decided to create a new one that uses the current template.

**Comment by joerkig** [comment]
@theusaf added in #8087
