### ISSUE TITLE
KissAsian | kissasian.fm - Update domain

### ISSUE THREAD

**Issue by Hersheesh** [PreMiD/Presences#7718]
### Presence name

KissAsian

### Description

The Supported URL : kissasian.li is not working anymore as the page isn't loading and cannot be accessed. I sincerely request to change the domain to kissasian.fm / kissasian.lu or any other working website. 

Please find Attach.

Thank You 
Hermes
![Screenshot_159](https://github.com/PreMiD/Presences/assets/149377493/84e4fb3f-d722-4610-9b9c-47b81c99c873)

**Comment by theusaf** [comment]
The domain linked in the description should be covered by the presence's url regex

**Comment by ION606** [comment]
@theusaf I think this is already covered, can you close it please?
