### ISSUE TITLE
Deezer | https://www.deezer.com/

### ISSUE THREAD

**Issue by 3uhd0u1** [PreMiD/Presences#7730]
### Steps to Reproduce

1. Go to this link : https://www.deezer.com/
2. The interface has changed 
3. The Premid Presence doesn't work, and don't display what i'm listening to on Discord.

### Expected Behavior

Listen music and share it with my friends on discord, with the Premid integration

### Actual Behavior

The interface has been redesigned, and the presence can't detect the music i'm listening to.

### Page URL

https://www.deezer.com/fr/

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/72729063/102701eb-852b-45bb-bb68-8e1ce63e2610)
![image](https://github.com/PreMiD/Presences/assets/72729063/f9dd314e-c37e-4a57-8527-45f4a779b143)
![image](https://github.com/PreMiD/Presences/assets/72729063/940fffa6-3810-4622-86f4-70517fe27759)
![image](https://github.com/PreMiD/Presences/assets/72729063/e2666753-f530-4314-8d1e-e60e24a2a164)

### Operating System

Windows 11

### Browser and Version

Google Chrome, Version 119.0.6045.105 

### Additional Comments

Before they redesigned the page, the player wasn't very stable, the music kept cutting out and, the name of the music wasn't displayed all the time....

**Comment by DarkVillager** [comment]
On it.
