### ISSUE TITLE
X | x.com

### ISSUE THREAD

**Issue by AMufInABox** [PreMiD/Presences#7733]
### Presence name

X.com

### Description

Hey! I'd like to request if its possible for the X Presence/Twitter Presence could have an option for it to be able to switch between X and Twitter? 

What I mean is that if its possible for in your status it could optionally still say Twitter instead of X.

**Comment by DarkVillager** [comment]
At this moment it is not possible.

**Comment by Bas950** [comment]
> At this moment it is not possible.

Well it is, but you would need to use multiple discord applications, which is a lil bit annoying.

**Comment by DarkVillager** [comment]
> > At this moment it is not possible.
> 
> Well it is, but you would need to use multiple discord applications, which is a lil bit annoying.

We could just use the same thing as the BBC presence.
