### ISSUE TITLE
Monkeytype status not showing

### ISSUE THREAD

**Issue by DonCappuccin0** [PreMiD/Presences#7754]
### Steps to Reproduce

Add Monkeytype presence to PreMiD.
Open and start Monkeytype in https://monkeytype.com/
Check your discord status and see if its showing Monkeytype or no.

### Expected Behavior

Your discord status show that you are playing Monkeytype

### Actual Behavior

Monkeytype doesn't show up in Discord status while you are using it

### Page URL

https://monkeytype.com/

### Operating System

Windows 11 22h2

### Browser and Version

Firefox 119.0.1

**Comment by Isa27-0** [comment]
Duplicate of #6413
