### ISSUE TITLE
studytogether | studytogether.com

### ISSUE THREAD

**Issue by divyanshxd** [PreMiD/Presences#7777]
### Website name

studytogether 

### Website URL

studytogether.com

### Website logo

https://photos.app.goo.gl/QN9cTr8nqgHgsiKy5

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Currently studying in room
number of people in group
time elapsed in room

**Comment by Isa27-0** [comment]
Duplicate of #6852
