### ISSUE TITLE
Duolingo | www.duolingo.com - Support Alphabet learning pages

### ISSUE THREAD

**Issue by joerkig** [PreMiD/Presences#7787]
### Presence name

Duolingo

### Description

On the duolingo presence it does not display anything when you are doing exercises to learn new alphabets/letters for for example Russian. I would like support for these pages to be added if possible ❤
https://www.duolingo.com/characters
![](https://i.joerkig.com/60zo0e.png)
![](https://i.joerkig.com/5o2khi.png)

**Comment by veryCrunchy** [comment]
It's being worked on ❤️
