### ISSUE TITLE
Hypixel | hypixel.net

### ISSUE THREAD

**Issue by AMufInABox** [PreMiD/Presences#7821]
### Steps to Reproduce

1. Go to any forum post on hypixel.net
[(Example)](https://hypixel.net/threads/guide-beginner-mid-late-game-money-making-methods.2641393/)
2. Presence does not display and gives errors in console. ![image](https://github.com/PreMiD/Presences/assets/74741218/84f332ca-35a8-4edf-b442-25822a49788e)

### Expected Behavior

Presence to display.

### Actual Behavior

Presence did not display and gave off errors.

### Page URL

https://hypixel.net/threads/guide-beginner-mid-late-game-money-making-methods.2641393/

### Screenshots

Troubleshooting page
![image](https://github.com/PreMiD/Presences/assets/74741218/ea9b8277-de1d-4a8d-9090-cc01fd16d960)

Discord Profile not displaying Presence
![image](https://github.com/PreMiD/Presences/assets/74741218/6daaa103-c701-4d22-bb09-ae1404b2c6d8)

### Operating System

Windows 11

### Browser and Version

Brave Browser | v1.61.104 

### Additional Comments

I am also using the latest PreMiD alpha extension along with this.

**Comment by veryCrunchy** [comment]
On it

**Comment by DarkVillager** [comment]
> On it

You still on it?

**Comment by veryCrunchy** [comment]
Yeah, have been really busy the past week. Will be finished it in the following two days

**Comment by veryCrunchy** [comment]
(Rewriting the presence)
