### ISSUE TITLE
BBC | www.bbc.co.uk - does not show status

### ISSUE THREAD

**Issue by shellacnails** [PreMiD/Presences#7852]
### Steps to Reproduce

If I click the link, it doesn't show up as my Discord status. I've tried other PreMiD presences and it's just this one not working.

### Expected Behavior

The BBC website would show up as my status.

### Actual Behavior

The BBC website did not show up as my status.

### Page URL

https://www.bbc.co.uk/

### Operating System

MacBook Air

### Browser and Version

Firefox 121.0

**Comment by DarkVillager** [comment]
On the homepage i have the same issue but when I click an article it works.
![image](https://github.com/PreMiD/Presences/assets/42322979/b9e3157c-370e-4e2e-a9b0-463ea7231297)

**Comment by shellacnails** [comment]
I'm also having this with iPlayer - when I just go to iPlayer's normal site it's fine, but as soon as I select something to watch it doesn't work and if you select a certain episode it doesn't show up either

**Comment by Slowlife01** [comment]
IPlayer does have some issues but I won't be able to fix it unless I find a working VPN

**Comment by DarkVillager** [comment]
> IPlayer does have some issues but I won't be able to fix it unless I found a working VPN

Same.
