### ISSUE TITLE
FlaviBot | flavibot.xyz

### ISSUE THREAD

**Issue by flav-code** [PreMiD/Presences#7853]
### Website name

FlaviBot

### Website URL

https://flavibot.xyz/

### Website logo

https://flavibot.xyz/_ipx/s_200x200/logos/flavibot_300x.svg

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

The page the user is on

**Comment by DarkVillager** [comment]
Lovely website, i enjoyed creating a presence for this.
