### ISSUE TITLE
FMovies | fmovies.ink - add new domain

### ISSUE THREAD

**Issue by BreadieSB** [PreMiD/Presences#7858]
### Steps to Reproduce

1. Visit fmovies.ink when the FMovies presence is installed

### Expected Behavior

Presence info to be displayed on Discord profile

### Actual Behavior

Nothing, URL is not recognised by presence

### Page URL

https://www.fmovies.ink

### Operating System

Windows 11

### Browser and Version

Vivaldi, ver 6.5.3206.48

**Comment by DarkVillager** [comment]
@Bas950 shouldn't we just implement a regex for this?
