### ISSUE TITLE
Fmovies | fmoviesz.to

### ISSUE THREAD

**Issue by ragxxv** [PreMiD/Presences#7890]
### Steps to Reproduce

Go to fmoviesz.to and start any episode of a series.

### Expected Behavior

Title of the series and episode number as well should show up on the presence.

### Actual Behavior

Only timer and site name appears, lacking series name and episode number.

### Page URL

https://fmoviesz.to/

### Screenshots

![BqC73fA](https://github.com/PreMiD/Presences/assets/75294599/f80cffa9-9447-45c0-9b7b-84523cc8f94d)

### Operating System

Windows 11

### Browser and Version

Brave v1.61.109

### Additional Comments

This was working as intended until yesterday; however, after the recent update, the presence was missing the title and episode number.

Those do show up on the presence if the website is fmovies.ink, but not with fmoviesz.to

**Comment by DarkVillager** [comment]
I will look into this.
