### ISSUE TITLE
Reddit | www.reddit.com - Presence causes memory leak

### ISSUE THREAD

**Issue by SofterKitty** [PreMiD/Presences#7891]
### Steps to Reproduce

1.  Add reddit presence
2. Go to reddit either old or new reddit

### Expected Behavior

Normal ram usage

### Actual Behavior

Ram fills quickly, fills page file, causes browser to lock up and if left for long enough your pc to bluescreen

### Page URL

https://www.reddit.com/

### Screenshots

https://github.com/PreMiD/Presences/assets/155543447/bc281ef5-1905-4716-8d24-c30b9bb3b504

### Operating System

Windows 10

### Browser and Version

Firefox 121 x64

### Additional Comments

I turned on privacy mode and typically when you first go to reddit when you have the presence it takes a few seconds before the ram spikes. with privacy mode it was instant.

**Comment by DarkVillager** [comment]
@SofterKitty interesting. Can you look in the console & copy & paste/screenshot the errors

**Comment by DarkVillager** [comment]
I will look into this since I can reproduce.
