### ISSUE TITLE
Animesuge | animesuge.to - changed their domain from .to to .net in some places

### ISSUE THREAD

**Issue by FakerTrash** [PreMiD/Presences#7912]
### Steps to Reproduce

well at least in Australia because they opened up a new domain and Australia can't access the old .to one

I was linked from the support page to go here.

### Expected Behavior

n/a

### Actual Behavior

n/a

### Page URL

from https://animesuge.to/ to https://animesuge.net/

### Operating System

Windows 11

### Browser and Version

Chrome

**Comment by DarkVillager** [comment]
I will look into this.
