### ISSUE TITLE
Kissasian | kissasion.lu - changed their domain from kissasian.li to kissasian.lu 

### ISSUE THREAD

**Issue by jasonnreformado** [PreMiD/Presences#7920]
### Website name

Kissasian

### Website URL

https://kissasian.lu

### Website logo

n/a

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

need to change the url

**Comment by Isa27-0** [comment]
It seems to be similar to #7718, but I can't really tell if it's a duplicate, because of the difference in domains.

**Comment by theusaf** [comment]
It's pretty much the same, I'll update the description of the other one.

Duplicate of #7718
