### ISSUE TITLE
Presences, store images/icons failing to load

### ISSUE THREAD

**Issue by zabersan** [PreMiD/Presences#7922]
### Steps to Reproduce

The store page takes a while to load, but when it does, about half the icons are little boxes, and then the presence icons are the generic bmp icon with text saying logo.

### Expected Behavior

Page/Presences load and act as normal

### Actual Behavior

Page loads slowly and incompletely/ Presences fail to work properly

### Page URL

https://premid.app/store?page=1&category=all

### Screenshots

![Screenshot 2024-01-07 204740](https://github.com/PreMiD/Presences/assets/30378622/4cc24885-9b2b-4733-a88e-9a39e11cc3a3)
![Screenshot 2024-01-07 204847](https://github.com/PreMiD/Presences/assets/30378622/71b0ce92-e85b-4ed5-9036-2fd29a4e03d4)

### Operating System

Windows 11 23H2

### Browser and Version

Microsoft Edge 

### Additional Comments

[premid.app-1704678245594.log](https://github.com/PreMiD/Presences/files/13855617/premid.app-1704678245594.log)

**Comment by theusaf** [comment]
Unrelated to the Presences repository. The CDN server was [down](https://premid-app.statuspage.io/). Just wait a bit, and the devs should get it back up again.
