### ISSUE TITLE
Monoschinos | monoschinos2.com - chapter number appears incorrectly

### ISSUE THREAD

**Issue by MillionaireD** [PreMiD/Presences#7932]
### Steps to Reproduce

1.https://monoschinos2.com/
2.https://monoschinos2.com/ver/pon-no-michi-episodio-2
3.The chapter number is not reflected in the state

### Expected Behavior

When selecting an anime episode, you can see the episode number next to the name in the discord status

### Actual Behavior

With the name of the chapter the following statement appears: presence.media.info.episode

### Page URL

https://monoschinos2.com/ver/pon-no-michi-episodio-2

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/137373133/96002320-3144-4e9f-8b68-32b76b1458da)

### Operating System

Windows 10 

### Browser and Version

Chrome Versión 120.0.6099.217 (Build oficial) (64 bits)

### Additional Comments

It's just a matter of reflecting next to the name of the series the number of the chapter being watched at the moment, everything else is fine.

**Comment by DarkVillager** [comment]
I will look into this

**Comment by MillionaireD** [comment]
Now another error remains and it is as follows:
 Apparently to get the number of the chapter, it takes the first number it
finds in the sentence, but keep in mind that for second or third seasons,
numbers are also used. I leave screenshots where it is shown that on the
web I am in chapter 3 but in the discord is reflected the 2, the same
happens if I go to chapter 1 for example
[image: image.png]

[image: image.png]

**Comment by theusaf** [comment]
@DarkVillager
