### ISSUE TITLE
Disney+ | disneyplus.com - does not properly show movie title

### ISSUE THREAD

**Issue by mizzylane111** [PreMiD/Presences#7933]
### Steps to Reproduce

I don't know

### Expected Behavior

I want to show a title on my disney+

### Actual Behavior

Cannot see the title what I am watching

### Page URL

https://www.apps.disneyplus.com/ph/movies/percy-jackson-and-the-olympians-the-lightning-thief/1770001604/watch?filters=content_type%3Dmovie

### Screenshots

![Capture](https://github.com/PreMiD/Presences/assets/156500210/8a328341-7ee7-43da-9ec3-4c8f7bfc0084)

### Operating System

windows 10

### Browser and Version

Premid

**Comment by Isa27-0** [comment]
Appears to be similar to issue #7531
