### ISSUE TITLE
YouTube | youtube.com - Occasional "undefined (undefined)" Section When Watching a YouTube Short

### ISSUE THREAD

**Issue by RattInsomniac** [PreMiD/Presences#7934]
### Steps to Reproduce

1. Start at YouTube homepage [https://www.youtube.com/](url)
2. Scroll down to the section labeled "Shorts"
3. Click on a short to watch
4. View discord profile presence with short still playing in the background

### Expected Behavior

Channel name and @ appears below the title of the YouTube Short

### Actual Behavior

Channel name and @ appears as "undefined (undefined)" 

### Page URL

https://www.youtube.com/shorts/ioxedeNCxZY

### Screenshots

Example of bugged user and @:
![image](https://github.com/PreMiD/Presences/assets/156503668/a4b238f7-a196-4a8d-8b35-640e27b14d93)

Example of proper user and @:
![image](https://github.com/PreMiD/Presences/assets/156503668/350b9206-c4db-45d5-888b-cce3db58607f)

### Operating System

Windows 10 Pro

### Browser and Version

Firefox 121.0.1 (64-bit)

### Additional Comments

No known pattern to this bug. Thanks for looking into it.

**Comment by DarkVillager** [comment]
Interesting, this used to happen before but I thought i fixed it. Not sure if this has an "easy" fix.
