### ISSUE TITLE
"Niconico" isn't working

### ISSUE THREAD

**Issue by sgoleo2021** [PreMiD/Presences#7949]
### Steps to Reproduce

1. Add "Niconico" to PreMiD
2. open niconico
3. start a video
4. check state in discord

### Expected Behavior

niconico show at state

### Actual Behavior

nothings is showing there

### Page URL

https://www.nicovideo.jp/watch/sm41606052

### Operating System

macos14.2

### Browser and Version

Chrome120.0.6099.109(mac)(arm64)

**Comment by Isa27-0** [comment]
Duplicate of #7194
