### ISSUE TITLE
Tumblr | tumblr.com - Not working

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#7950]
### Steps to Reproduce

1 - Add presence;
2 - Access the website, on any page;
3 - Go to Discord and observe.

### Expected Behavior

The presence would be appearing

### Actual Behavior

Presence does not appear

### Page URL

https:// [userpage] .tumblr.com

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/68751594/b5acb6fe-555c-4e72-9dba-915a01c5c253)

### Operating System

Windows 10

### Browser and Version

Opera GX LVL 5 (core: 105.0.4970.76) (64 Bits)

### Additional Comments

I believe it is not working because the last presence update was in 2019 (#578), when it was added.

**Comment by DarkVillager** [comment]
I will look into this.
