### ISSUE TITLE
Tumblr | tumblr.com - Only 'tumblr' appears

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#7984]
### Steps to Reproduce

1 - Add the presence;
2 - Access any user's website, without accessing the main page of Tumblr itself (ex: `sonicthehedgehog.tumblr.com`);
3 - Observe.

### Expected Behavior

More information should appear in the presence

### Actual Behavior

Only the logo with the name of the presence appears

### Page URL

https:// [userpage] .tumblr.com

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/68751594/81635c17-4efc-4593-ba85-9b68a20e9b4e)

### Operating System

Windows 10

### Browser and Version

Opera GX LVL 5 (core: 106.0.4998.42) (64 bits)

### Additional Comments

Other than that, profiles accessed with `www.tumblr.com` (in addition to the main page and the help center) are working normally:
![image](https://github.com/PreMiD/Presences/assets/68751594/4fa41aee-8b06-4fbe-ad9a-89d14084b369)
![image](https://github.com/PreMiD/Presences/assets/68751594/8ada0070-6a65-4ce5-924f-62341d04218c)
![image](https://github.com/PreMiD/Presences/assets/68751594/71f661cc-8fa8-4bb7-8630-05299554b202)

**Comment by DarkVillager** [comment]
Interesting.
