### ISSUE TITLE
CONTRIBUTING.md incorrect hyperlink for "common details"

### ISSUE THREAD

**Issue by NULLYUKI** [PreMiD/Presences#7985]
### Steps to Reproduce

1. Access the [CONTRIBUTING.md](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md) file.
2. Look for the hyperlink "common details" that can be found in the following sentence:
> Presences should use common details (strings starting with "general."). You can achieve this using multiLanguage with the provided strings. If your presence requires custom strings, then you shouldn't use multiLanguage until the presence gets 1000 users. You can find an example here.
3. Press on the hyperlink for "common details"
4. Notice the 404 error response.

### Expected Behavior

The user should be redirected to the common details without any issues.

### Actual Behavior

A 404 error response is being displayed for the user.

### Page URL

https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md

### Screenshots

Hyperlink that causes the error:
![grafik](https://github.com/PreMiD/Presences/assets/42326194/a246982e-fac7-4c7c-91df-15d7bbb7485e)
The error:
![grafik](https://github.com/PreMiD/Presences/assets/42326194/de88ac5c-a3fe-4dc5-8bcc-cd36ef994c45)

### Operating System

Windows 10 Pro

### Browser and Version

Mozilla Firefox 122.0 (64-Bit)

**Comment by Isa27-0** [comment]
It's giving an error because v2 no longer exists in the PreMiD API. They probably forgot to add the new one.
