### ISSUE TITLE
Adding anime website Anitube

### ISSUE THREAD

**Issue by Loli-Drakosha** [PreMiD/Presences#7988]
### Website name

AniTube

### Website URL

https://anitube.in.ua/

### Website logo

I don't know, maybe just make the logo look like the site icon in the browser, or I'll put another example in the description. 

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [X] It is region restricted

### Description

Best anime website to watch anime in Ukrainian.

I pate some pictures for examples (logo and preview)
![header_logo](https://github.com/PreMiD/Presences/assets/157768972/c23a1c10-663a-4731-b315-f17c23251712)
![chrome_XNDQXiurHO](https://github.com/PreMiD/Presences/assets/157768972/cbfed178-9820-469a-85c6-c79388bf4347)

**Comment by theusaf** [comment]
Duplicate of #7321

**Comment by Loli-Drakosha** [comment]
So this site not be added to PreMiD because there is a site with a similar name? Or will the site be added later? Sorry, i see this closed, but i need answer for this. It's realy important for me :D

**Comment by joerkig** [comment]
> So this site not be added to PreMiD because there is a site with a similar name? Or will the site be added later? Sorry, i see this closed, but i need answer for this. It's realy important for me :D

This request was closed because there is already a request open for the website
