### ISSUE TITLE
Otakudesu | otakudesu.cloud- update domain

### ISSUE THREAD

**Issue by hbdbuatkamu** [PreMiD/Presences#8014]
### Steps to Reproduce

Update domain Otakudesu

### Expected Behavior

domain Otakudesu.media not .cam

### Actual Behavior

new domain is .media

### Page URL

Otakudesu.media

### Screenshots

-

### Operating System

-

### Browser and Version

-

### Additional Comments

-

**Comment by mallusrgreatv2** [comment]
The actual domain now redirects me to otakudesu.cloud
