### ISSUE TITLE
Display Current Activity As A Status Message.

### ISSUE THREAD

**Issue by 0dmb** [PreMiD/Presences#8016]
### Steps to Reproduce

No presences i have work for discord. when i went to chrome-extension://agjnjboanicjcpenljmaaigopkgdnihi/src/entries/troubleshooting/index.html it says the only thing not connnected is Display Current Activity As A Status Message.

### Expected Behavior

activity to show on discord

### Actual Behavior

explained

### Page URL

all

### Screenshots

![54646456](https://github.com/PreMiD/Presences/assets/158781943/0d18e832-da48-4fd8-b306-91d757fbd164)

### Operating System

win10

### Browser and Version

Version 121.0.6167.140 Google Chrome

**Comment by Isa27-0** [comment]
Check the troubleshooting page or access the Discord server if you have problems with the extension or application. This repository is for presences only.
