### ISSUE TITLE
Youtube | www.youtube.com - shorts details do not work

### ISSUE THREAD

**Issue by Ggamegirl011158** [PreMiD/Presences#8023]
### Steps to Reproduce

1. Have discord open.
2. Watch any shorts.
3.  Go to your discord profile.
4.  See if the presence says loading, doesn't show the title or the thumbnail of the short and uploader of the short and doesn't show the play/pause button properly. (If you're lucky, it says you're watching a video even if privacy mode is off)

### Expected Behavior

The thumbnail of the video, title and uploader shows, presence doesnt say loading and play/pause button shows properly.

### Actual Behavior

 presence says loading, doesn't show the title or the thumbnail of the short and uploader of the short and doesn't show the play/pause button properly. (If you're lucky, it says you're watching a video even if privacy mode is off)

### Page URL

https://www.youtube.com/shorts/IA6eF-Sg5v4

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/53093223/1f840bfb-08a1-4cc8-8c2f-a8d7aedc079a)

### Operating System

Windows 11

### Browser and Version

 121.0.6167.140 

### Additional Comments

If you keep refreshing it, the presence may say watching a video but not showing the title and uploader BUT its shows the play/pause button right but when you pause and play it again it just stays at pause/play.

**Comment by theusaf** [comment]
Can confirm. Looks like selectors for shorts are out of date
