### ISSUE TITLE
9anime | 9animetv.to

### ISSUE THREAD

**Issue by Luh2Buzy** [PreMiD/Presences#8024]
### Website name

9Anime

### Website URL

9animetv.to

### Website logo

eee

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

![9anime](https://github.com/PreMiD/Presences/assets/114599798/eb1e6ec1-4d3a-4b29-be31-5d8d36ce2fdb)
 
 thats the lgo for it

**Comment by theusaf** [comment]
Note: "official" service is now known as "aniwave" (see 9anime.me). Question is if we should also support these clones as well

**Comment by Pokeylooted** [comment]
> Note: "official" service is now known as "aniwave" (see 9anime.me). Question is if we should also support these clones as well

We're supporting *clones*, of other services. Such as Movie-web, even though it was shutdown the community is big enough to continue hosting it. I think we should implement a way for manually entering clone urls in as in some of these, the designs stays the same just different branding.

**Comment by ION606** [comment]
> Note: "official" service is now known as "aniwave" (see 9anime.me). Question is if we should also support these clones as well

LMAO I think they rebranded to "hianime"
