### ISSUE TITLE
Youtube Music | music.youtube.com - not working

### ISSUE THREAD

**Issue by IAmFacebook** [PreMiD/Presences#8030]
### Steps to Reproduce

![image](https://github.com/PreMiD/Presences/assets/83931959/cec27482-f469-42de-8ef4-d54f93e78ed3)

### Expected Behavior

YT Nusic wont show

### Actual Behavior

Meant to show my song im listneing to in DRP

### Page URL

https://music.youtube.com/

### Operating System

win10

### Browser and Version

Opera Newest vers

**Comment by theusaf** [comment]
Duplicate of #7094
