### ISSUE TITLE
movie-web | movie-web.app - doesn't properly update

### ISSUE THREAD

**Issue by josephisticated** [PreMiD/Presences#8031]
### Steps to Reproduce

1. Go to https://movie-web.app/, presence activates
2. Go try to watch Rick and Morty
3. Presence won't change accordingly to the show

### Expected Behavior

Presence change accordingly to the show

### Actual Behavior

Presence won't change accordingly to the show

### Page URL

https://movie-web.app/media/tmdb-tv-60625-rick-and-morty/302503/3891509

### Operating System

Windows 11

### Browser and Version

Edge 121.0.2277.98 (Official build) (64-bit)

**Comment by mallusrgreatv2** [comment]
works fine

**Comment by vvirtues** [comment]
use alternate domains like `mw.lonelil.ru` instead, main instance is pretty much dead

**Comment by vvirtues** [comment]
they transferred database over so u can use exisiting account
