### ISSUE TITLE
Anicrush | anicrush.to

### ISSUE THREAD

**Issue by SeshanthKarthik** [PreMiD/Presences#8063]
### Presence name

Anicrush

### Description

as anicrush is a good anime streaming like aniwatch i think it deservers to have a presence so it will be nice to have it as a presence

**Comment by Isa27-0** [comment]
If you're going to ask to add another presence, I recommend using the Service Request [template](https://github.com/PreMiD/Presences/pull/8062). Feature requests are for presences that already exist in the store

**Comment by Isa27-0** [comment]
If you're going to ask to add another presence, I recommend using the Service Request [template](https://github.com/PreMiD/Presences/pull/8062). Feature requests are for presences that already exist in the store.

Edit: Apparently, the domain is https://anicrush.to/
