### ISSUE TITLE
MyOnlineRadio | myonlineradio.*

### ISSUE THREAD

**Issue by agot137** [PreMiD/Presences#8078]
### Website name

MyOnlineRadio

### Website URL

Various links besides country. Links on the bottom.
Example: Hungarian
https://myonlineradio.hu/

### Website logo

Various links besides country. Links on the bottom.
Example: Hungarian
https://myonlineradio.hu/public/img/favicon.ico

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Please add support for MyOnlineRadio.

It has more countries radio stations online.
It can use windows's media control panel over browser like chromium based.
![image](https://github.com/PreMiD/Presences/assets/13472855/bee1d195-1eba-46ca-b8f4-03b4f7333d30)

You can change between multiple audio sources, but it's not necesarry. 
![image](https://github.com/PreMiD/Presences/assets/13472855/a6ebc8f1-e112-439e-a827-7053d6c1cf3a)

It would be cool if you can see the active station name and if possible, the actual music/show name.
You can get it from the html page "actsSong" class
![image](https://github.com/PreMiD/Presences/assets/13472855/28e31303-fd0f-4e08-bd04-4426704b4259)

It has in the head section the property for the actual stations link and name
```
og:url
og:title
```
![image](https://github.com/PreMiD/Presences/assets/13472855/34bdbb2a-632c-44fb-bbfc-a3c3fee83ed1)

also there is the stations logo
```
og:image
```
![image](https://github.com/PreMiD/Presences/assets/13472855/c6252318-e648-4b7d-a269-a389aad81800)

Listening elapsed time not important, but there is a a class for it too
```
ctime js-cTime
```
![image](https://github.com/PreMiD/Presences/assets/13472855/a14aa83a-17d0-4b8c-b471-05019544d68b)

I can imagine like this on discord profile
![image](https://github.com/PreMiD/Presences/assets/13472855/0dd3b7e5-cafe-4ab0-95c7-d33e95904125)

Links for different countries:
[MyOnlineRadio.hu](https://myonlineradio.hu/) <- Mine country (could be the first added, also I can help you in testing.)
[MyRadioOnline.ro](https://myradioonline.ro/)
[MyOnlineRadio.sk](https://myonlineradio.sk/)
[MyOnlineRadio.de](https://myonlineradio.de/)
[UKRadioLive.com](https://ukradiolive.com/)
[MyOnlineRadio.at](https://myonlineradio.at/)
[MyRadioOnline.it](https://myradioonline.it/)
[MyRadioOnline.es](https://myradioonline.es/)
[MyRadioEnDirect.fr](https://myradioendirect.fr/)
[IrishRadioLive.com](https://irishradiolive.com/)
[MyRadioOnline.pl](https://myradioonline.pl/)
[MyOnlineRadio.nl](https://myonlineradio.nl/)
[MyRadioOnline.cl](https://myradioonline.cl/)
[MyRadioEnVivo.ar](https://myradioenvivo.ar/)
[MyRadioEnVivo.mx](https://myradioenvivo.mx/)

Thank you ^^

**Comment by ION606** [comment]
ooo I can try to add it

**Comment by agot137** [comment]
> ooo I can try to add it, but only in english (I don't speak Hungarian unfortunately)

That woudl be awesome!

The english part is no problem. If somebody help me how the translation works, I can add the prefered language to it.
