### ISSUE TITLE
Kittens Game | kittensgame.com

### ISSUE THREAD

**Issue by UlyssesZh** [PreMiD/Presences#8126]
### Website name

Kittens Game

### Website URL

https://kittensgame.com/web/

### Website logo

https://kittensgame.com/web/res/favicon.gif

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

A web game of building a village of cats.

Better, show the current in-game year and day in the presence.

**Comment by DarkVillager** [comment]
@UlyssesZh where is the year and day shown?

**Comment by DarkVillager** [comment]
I'm working on it, but since I don't have a lot time, please be patient.

**Comment by DarkVillager** [comment]
Update: I'm almost done. Will most likely finish next week.
