### ISSUE TITLE
YouTube Music | music.youtube.com - Correct Timestamps after resuming playback

### ISSUE THREAD

**Issue by RichardKanshen** [PreMiD/Presences#8131]
### Presence name

YouTube Music

### Description

After resuming playback, the timestamps get reset as if the video started midway.
![image](https://github.com/PreMiD/Presences/assets/73738591/ef6f91dd-5178-49bd-809b-58f2339503f5)
![image](https://github.com/PreMiD/Presences/assets/73738591/dab17c5c-a9e1-4408-9eb4-714434d71ffb)

### Additional context

After looking through the code of the presence, it should be fairly simple to fix, I believe just one change in the last function of the presence should fix it (snippet - YouTube Music // presence.ts - Lines 268 - 279)

```
function updateSongTimestamps() {
	const element = document
			.querySelector<HTMLSpanElement>("#left-controls > span")
			.textContent.trim()
			.split(" / "),
		[currTimes, totalTimes] = element;

	mediaTimestamps = presence.getTimestamps(
		presence.timestampFromFormat(currTimes),
		presence.timestampFromFormat(totalTimes)
	);
}
```

**Comment by DarkVillager** [comment]
There always seem to be a second difference. Let me see what I can do.

**Comment by DarkVillager** [comment]
Seems like it's only a 0.5 difference, that gets floored to a 1 sec diff

**Comment by DarkVillager** [comment]
Doesn't seem fixable.

**Comment by RichardKanshen** [comment]
The issue seems to be rather that the time resets after pausing. The song is shown shorter after pausing and resuming.

**Comment by DarkVillager** [comment]
I can't reproduce that.

**Comment by RichardKanshen** [comment]
I recorded it, maybe this might help?

https://github.com/PreMiD/Presences/assets/73738591/8310af05-b789-449a-8b77-4dcaf1d017a7
