### ISSUE TITLE
hqporner | hqporner.com

### ISSUE THREAD

**Issue by killuzii** [PreMiD/Presences#8135]
### Website name

hqporner

### Website URL

hqporner.com

### Website logo

https://logos-world.net/wp-content/uploads/2023/01/HQPorner-Logo-500x281.png

### Prerequisites

- [ ] It is a paid service
- [X] It displays NSFW content
- [ ] It is region restricted

### Description

just showing video name and timestamp with a thumbnail is fine.

**Comment by theusaf** [comment]
Due to certain changes, sites like these will be removed/disallowed soon.

**Comment by killuzii** [comment]
all nsfw presences?

**Comment by theusaf** [comment]
Yeah
