### ISSUE TITLE
Add pony town

### ISSUE THREAD

**Issue by Hymandois** [PreMiD/Presences#8211]
### Website name

Pony Town

### Website URL

https://pony.town/

### Website logo

https://pony.town/assets/images/logo-stacked-6bddd18e27.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

What server youre playing on and how long youve been playing on for.

**Comment by theusaf** [comment]
Duplicate of #5416
