### ISSUE TITLE
Replit | replit.com - doesn't work directly on replit.com

### ISSUE THREAD

**Issue by ItsEpicBeast** [PreMiD/Presences#8218]
### Steps to Reproduce

The replit presence works if you open it from replit.it (which changes to com) but if you try to open it from replit.com (currently URL) then it doesn't work. Also, the logo is outdated so the logo should be changed. 

### Expected Behavior

If I working on something with replit.com, then it should be detected 

### Actual Behavior

You have to open replit.it first before so it starts working

### Page URL

https://replit.com/

### Operating System

Windows 11

### Browser and Version

Chrome Ver. 123.0.6312.60

### Additional Comments

As long as it works on replit.com then the issue should be fixed.

**Comment by DarkVillager** [comment]
I'll look into this.
