### ISSUE TITLE
gogoanime | www10.gogoanime.io

### ISSUE THREAD

**Issue by NarutoVsGoku** [PreMiD/Presences#823]
**Prerequisites and essential questions** 
* [ ] Is it a popular site? Yes
* [ ] Is the website older than 2 months?  Yes it is older than 2 months
* [ ] Is the site locked to a specific country/region? I don't think so.
* [ ] Is the site a paid service? (e.g. Netflix, Hulu) No
* [ ] Does the website feature NSFW content? (e.g. porn, etc...) No
* [ ] Are you a donator/patron? No
* [ ] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? Yes i am aware

**What's your Discord username?**  Super Saiyan Blue Goku『Izuku』#2003

**What's the name of the service?**  https://www10.gogoanime.io/ - gogoanime

**What should the Presence display?**  The name of anime, episode and what your browsing through. Simialr to YouTube or other anime sites.

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by doomlerd** [comment]
Correct the prerequisites please.

**Comment by Gurrman375** [comment]
the website is now https://www18.gogoanime.io/

**Comment by dana0404** [comment]
Can be closed this is done
