### ISSUE TITLE
MyDramaList | mydramalist.com

### ISSUE THREAD

**Issue by JB220** [PreMiD/Presences#824]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  

**What's the name of the service?**  [https://mydramalist.com/](url)
**What should the Presence display?**  It should display when a user is browsing the homepage. If possible, it should also show when a user is viewing a specific show. 

**If possible, please provide a logo for the service (512x512 minimum)**  Logo can be found by searching Mydramalist on google images, the one with the blue and white MDL logo.

**Comment by doomlerd** [comment]
Correct the prerequisites please.

**Comment by JB220** [comment]
Have ticked the boxes, please tell me if I still need to change anything

**Comment by Bas950** [comment]
remove the "yes" after older than 2 months.

**Comment by JB220** [comment]
done
