### ISSUE TITLE
mydramalist request 

### ISSUE THREAD

**Issue by Jakester-1111** [PreMiD/Presences#825]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?**  https://mydramalist.com/

**What should the Presence display?**  Viewing home page (Like myanimelist) and if possible which dramas you are viewing

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by frozaum** [comment]
and duplicate #824
