### ISSUE TITLE
YouTube Music | music.youtube.com - add ability to switch between progress time types

### ISSUE THREAD

**Issue by PurKus** [PreMiD/Presences#8262]
### Presence name

Youtube Music

### Description

An button maybe with which you can change the type of Song progress shown between: -time left- (like right now) or the normal progress how far you listened. I find the default of time left kinda confusing since no other App ik shows progress it like that xD

**Comment by tag27** [comment]
> or the normal progress how far you listened.

I don't know if PreMiD can support this. Yes, there are timestamps that use the normal time in most presences, but usually in presences that are for music streams, the "remaining time" is used. As I'm not a developer, I don't know if it's possible for the normal time to appear exclusively for the song in question.
