### ISSUE TITLE
WCOstream | wcostream.tv

### ISSUE THREAD

**Issue by FirestormDangerDash** [PreMiD/Presences#8268]
### Steps to Reproduce

WCOstream changed url so presence no longer function.

### Expected Behavior

Presence should connect to discord and display.

### Actual Behavior

Nothing.

### Page URL

wcostream.tv

### Operating System

Win 11

### Browser and Version

Chrome 123.0.6312.106

**Comment by DarkVillager** [comment]
I will look into it.
