### ISSUE TITLE
YouTube | www.youtube.com - No longer displaying video title information after youtube update

### ISSUE THREAD

**Issue by Kaympe20** [PreMiD/Presences#8269]
### Steps to Reproduce

1. Be part of the group that had their UI's forcibly changed
2. Use PreMID
3. No video title

### Expected Behavior

All relevant information on a video to show up

### Actual Behavior

PreMID and discord no longer display video title

### Page URL

Issue occurs on any video

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/117483128/ceba3ed5-8ca8-4441-a946-972371273177)
![image](https://github.com/PreMiD/Presences/assets/117483128/235a804f-ff4e-4757-af08-699148a4492d)

### Operating System

Windows 11

### Browser and Version

Brave Browser - 1.64.116

**Comment by LIs4TheWayULookAtMe** [comment]
I just realized this issue was already posted so I'll place mine here for more information and delete the one I put up:

![Same_issue](https://github.com/PreMiD/Presences/assets/167165929/b5832a6a-4205-4189-b968-fe79aee69949)

Someone else also mentioned they experienced this issue in the discord.
