### ISSUE TITLE
Stremio (Addon)

### ISSUE THREAD

**Issue by DX666XD** [PreMiD/Presences#829]
**Prerequisites and essential questions** 
* [Maybe, I don't know] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [x] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
RDanX#0334

**What's the name of the service?** 
www.stremio.com | stremio

**What should the Presence display?** 
What you're watching, what category it is & how long is left.

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/38041711/71383455-5eae5800-25d4-11ea-877d-9d2dfe83fc76.png)

**Comment by Suburbanno** [comment]
https://github.com/Stremio/stremio-features/issues/120

**Comment by frozaum** [comment]
1. PreMiD only supports web services and we couldn't find a web version of Stremio, therefore, this presence request is invalid.
2. We searched both of your names and we couldn't find you being a patron, can you give us your Patreon nickname?
@DX666XD

**Comment by frozaum** [comment]
(will leave this ticket open until response)

**Comment by doomlerd** [comment]
You are not a donator so may I ask why did you check it?

**Comment by jaruba** [comment]
@frozaum You're wrong. Here is the web version of Stremio: http://app.strem.io/shell-v4.4/#/

**Comment by doomlerd** [comment]
> @frozaum You're wrong. Here is the web version of Stremio: http://app.strem.io/shell-v4.4/#/

It's been discussed, we're allowing both the web version and the addon. although the addon won't reach the store at the moment even if it was added because they're not supported yet. The web version will be fine though.

**Comment by alqadhiyasir1982** [comment]
Please you can tell hiw get more add-ons on my stremio on tv or phone in one time . I am installing the add-ons on stremio but im asking how get more.

**Comment by ririxidev** [comment]
#842 is better request.

**Comment by sluzy-nos4a2** [comment]
Could it be added to https://peario.xyz/?
