### ISSUE TITLE
YouTube Music not displaying

### ISSUE THREAD

**Issue by ION606** [PreMiD/Presences#8332]
### Steps to Reproduce

1. install the youtube music presence
2. turn off the `Show Browsing` setting

### Expected Behavior

The presence should still be visible

### Actual Behavior

The presence dissapears

### Page URL

https://music.youtube.com/

### Operating System

Window 10

### Browser and Version

Firefox 124

**Comment by theusaf** [comment]
Duplicate of #7094

**Comment by ION606** [comment]
are you sure? Because there are no errors in my console
