### ISSUE TITLE
Anime Site

### ISSUE THREAD

**Issue by MrsVNF** [PreMiD/Presences#8354]
### Website name

animension.to

### Website URL

https://animension.to/

### Website logo

https://imgur.com/om1jxSP

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

Hello , i'd like for this site to be added, dont have logo image on me!, i'd like a presence where it shows anime name , title,etc.

Ty!.

**Comment by tag27** [comment]
Duplicate of #7286

**Comment by MrsVNF** [comment]
> Duplicate of #7286

Ain't no way dawg , ain't no way , i swwear i didn't know 😭 wthhhhhhh lmao
