### ISSUE TITLE
PokéRogue | pokerogue.net

### ISSUE THREAD

**Issue by Staybink** [PreMiD/Presences#8357]
### Website name

PokéRogue

### Website URL

pokerogue.net

### Website logo

https://pokerogue.net/logo512.png

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

I would love for this presence to display what wave the player is on, and maybe how much money they have when in game. Have it display if they are playing classic mode, endless mode, or the daily run. Also display if they are in the main menu, the egg gacha, achievements, etc. Thanks in advance, really looking forward to this presence being added and how you guys execute it.

**Comment by DarkVillager** [comment]
I'll look into this cuz it is possible.

**Comment by DarkVillager** [comment]
Seems like I can only load data from the first save interesting.

**Comment by DarkVillager** [comment]
I’m 90% done.
