### ISSUE TITLE
YouTube | youtube.com - "pervideoprivacytooltip" is turned off by default, not showing any video

### ISSUE THREAD

**Issue by SaamariYT** [PreMiD/Presences#8383]
### Steps to Reproduce

1. Open youtube
2. Tooltip is crossed

### Expected Behavior

I would expect the tooltip to be in "show mode" by default

### Actual Behavior

The tooltip hides the video

### Page URL

https://www.youtube.com

### Operating System

Win10PRO 22H2

### Browser and Version

 Firefox 126.0(64bit)

**Comment by SaamariYT** [comment]
Running ublock origin with base settings and dark reader, both installed on 19th may

**Comment by theusaf** [comment]
Hmm. I can't seem to reproduce this issue. What settings do you have for the YouTube presence?

**Comment by SaamariYT** [comment]
settings cant seem to load for some reason
![image](https://github.com/PreMiD/Presences/assets/93148656/4e71daa6-b6e3-4d18-9cdb-cbf093e9e6a4)
