### ISSUE TITLE
Radiko.jp - Japan Local Internet Radios

### ISSUE THREAD

**Issue by matiplx** [PreMiD/Presences#839]
What's the name of the service?
http://radiko.jp/  | Official Website (Requires Firefox or Chrome Plugin Called "Rajiko by jackyzy823")

What should the Presence display?
Informations about the current stream and program and time elapse 

Why do you want support for this service?
Radiko is Japanese Local internet radio, you can listen (Tokyo FM or other stations)
if think, many peapole don't know this services and don't know that worki with that plugin

Are you able to provide an image for the service? (512x512 minimum)
https://addons.cdn.mozilla.net/user-media/addon_icons/951/951266-64.png

**Comment by frozaum** [comment]
Please,[ use the new request template.](https://github.com/PreMiD/Presences/issues/new?template=service_request.md)
