### ISSUE TITLE
radiko (ラジコ) | radiko.jp

### ISSUE THREAD

**Issue by matiplx** [PreMiD/Presences#840]
**Prerequisites and essential questions**
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [x] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** http://radiko.jp/ 
**What should the Presence display?** Information about current stream and time elapse.
****If possible, please provide a logo for the service** 
![obraz](https://user-images.githubusercontent.com/58110535/71485807-54c66800-2813-11ea-91c9-8c750c5a010d.png)

**Extra Info** This site is neeed Firefox or Chrome plugin called **"Rajiko" by jackyzy823** to use this website.

**Comment by Isa27-0** [comment]
@matiplx presence has been added, check the store! (https://premid.app/store/presences/Radiko)
