### ISSUE TITLE
Soundcloud | www.soundcloud.com - stuck at "Discovering..."

### ISSUE THREAD

**Issue by MattiVboiii** [PreMiD/Presences#8412]
### Steps to Reproduce

1. Open Soundcloud
2. Play music
3. Check your discord

### Expected Behavior

Showing the title and timestamp

### Actual Behavior

Stuck at showing "Discovering..."

### Page URL

www.soundcloud.com

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/57048210/0a51b1cb-67ab-4c8d-979e-d037e2de031a)
![image](https://github.com/PreMiD/Presences/assets/57048210/fca282c9-67e3-4648-81a8-826c49371e31)

### Operating System

Windows 11

### Browser and Version

AVG Secure Browser

### Additional Comments

I'm using AVG Secure browser since I use the subscription

**Comment by DarkVillager** [comment]
I cant reproduce
