### ISSUE TITLE
Stremio (Web Application) | app.strem.io

### ISSUE THREAD

**Issue by CyclonePT** [PreMiD/Presences#842]
**Prerequisites and essential questions** 
* [X] Is it a popular site?
* [X] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region? It might be for some regions not sure
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)- It is totally free
* [ ] Does the website feature NSFW content? (e.g. porn, etc...) I think it doesnt have
* [ ] Are you a donator/patron? No
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Cyclone#1234

**What's the name of the service?** 
Stremio - https://www.stremio.com/
**What should the Presence display?**  similar as others streaming presences for example. (what TV show/movie is been watch, and maybe the time left to end)

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/45118834/71491341-17200a00-2828-11ea-9c41-85a6c11203db.png)

**Comment by Bas950** [comment]
app.strem.io is the webplayer I think (quick google search)

**Comment by frozaum** [comment]
I don't know if i can consider this as a duplicate from #829, going to leave it open for now.
