### ISSUE TITLE
Dumpert | Dumpert.nl

### ISSUE THREAD

**Issue by jlkjlkjkljkljlkjkljkljkl** [PreMiD/Presences#844]
Prerequisites and essential questions

 

* [x] Is it a popular site?
* [x] Is the website older than 2 months?
* [ ] Is the site locked to a specific country/region? - **Netherlands/Belgium (dutch language)**
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...) **Only when you turn nsfw video's on**
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

What's your Discord username? **Josh.#2277**

What's the name of the service? **https://dumpert.nl - Dumpert** 

What should the Presence display? **What video is being watched with title. Time left etc. Maybe display if you are browsing the "new" feed or the "toppers"(top rated) feed.** 

If possible, please provide a logo for the service (512x512 minimum) their official logo

![DWR0GyWI](https://user-images.githubusercontent.com/38816611/71537020-6c3a4980-2916-11ea-9f23-cab717134ca5.jpg)

**Comment by doomlerd** [comment]
It's not locked ( at least for me ), @frozaum can you test it please?

**Comment by Bas950** [comment]
It not locked but whole site is in dutch, I will make it in a week probs

**Comment by frozaum** [comment]
@doomlerd not region-locked, but the platform allows not safe for work videos

**Comment by doomlerd** [comment]
Not nsfw when not dedicated to porn.

**Comment by Bas950** [comment]
Update: Will be released when presence settings are released.

**Comment by doomlerd** [comment]
btw @jlkjlkjkljkljlkjkljkljkl josh you don't have to use a throwaway account lols ( but i'll still let you keep your privacy )

**Comment by jlkjlkjkljkljlkjkljkljkl** [comment]
> btw @jlkjlkjkljkljlkjkljkljkl josh you don't have to use a throwaway account lols ( but i'll still let you keep your privacy )

What exactly do you mean? I don't have an alt account on github i just couldnt come up with a good name

**Comment by doomlerd** [comment]
> What exactly do you mean? I don't have an alt account on github i just couldnt come up with a good name
DM me in discord ( if you're able to ) and i'll explain
