### ISSUE TITLE
Plex | app.plex.tv - presence not functioning properly

### ISSUE THREAD

**Issue by Exlosia** [PreMiD/Presences#8470]
### Steps to Reproduce

For the plex presence (https://app.plex.tv/desktop/#!/), it works on the home page but when watching a movie/show it doesnt. this started happening ever since 2.6.0

### Expected Behavior

It should show what movie/show im watching

### Actual Behavior

Doesnt show anything

### Page URL

Any movie/show on https://app.plex.tv/desktop/#!/

### Operating System

Windows 10

### Browser and Version

Opera GX (version unknown but its june right now and this has been going on for a while)

**Comment by TheVisual** [comment]
![image](https://github.com/PreMiD/Presences/assets/132447890/c8b44811-4e16-4d60-b5c0-b4d87e5522fe)

Do you mean the no movie / TV image? Or you having another issue?

**Comment by Exlosia** [comment]
it just doesnt show the movie or show at all

**Comment by DarkVillager** [comment]
I'll look into it.

**Comment by Exlosia** [comment]
no

**Comment by DarkVillager** [comment]
I can now reproduce.
