### ISSUE TITLE
Stremio | app.strem.io - not working correctly

### ISSUE THREAD

**Issue by josephisticated** [PreMiD/Presences#8488]
### Steps to Reproduce

1. Run Stremio Service for Windows or Stremio for Windows
2. Go to https://app.strem.io/ or https://web.stremio.com/ to watch something

### Expected Behavior

Show the movie that is currently being watched

### Actual Behavior

Getting stuck at "Board" or not showing up at all / how much left until it ends keep going backwards even though it's stopped

### Page URL

https://app.strem.io/, https://web.stremio.com/

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/53388005/ff15e5c8-2935-47c6-86ea-cbcf9726916d)
![image](https://github.com/PreMiD/Presences/assets/53388005/70f42302-2ad2-4ae0-8b84-a276c5d7f3b7)

### Operating System

Windows 11

### Browser and Version

Microsoft Edge Version 125.0.2535.92 (Official build) (64-bit)

### Additional Comments

The rich presence works on https://app.strem.io/ as shown in the first picture, from what I understand, is a deprecated web version of Stremio because subtitles and dubbing don't work.
Where it doesn't work is https://web.stremio.com/, the newer version of the Stremio Web, it gets stuck on board as shown in the second picture.

**Comment by DarkVillager** [comment]
@josephisticated i'll look into this when i have time.

**Comment by sleeyax** [comment]
Steps to reproduce:

1. Play any movie once
2. Go to https://web.strem.io/#/ > Board
3. Play the movie directly from 'Continue watching

Now you should notice that the presence is stuck on 'Board'. Player info is not being updated.
