### ISSUE TITLE
YouTube | youtube.com - not showing timestamps and buttons when using the new Beta UI for YouTube Premium users

### ISSUE THREAD

**Issue by honzawashere** [PreMiD/Presences#8501]
### Steps to Reproduce

1. Go to YouTube Experiments (only for Premium users)
2. Enable the new Beta UI (if you can)
3. Play any video with Premid enabled.

### Expected Behavior

Timestamps (time left or elapsed) + buttons should be showing

### Actual Behavior

Timestamps and buttons are not showing

### Page URL

https://www.youtube.com/watch?v=ig7lyuYBbnI or any other YouTube Video

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/109418897/feabba92-5e28-4e5b-b6e1-46db9fe7d803)
![image](https://github.com/PreMiD/Presences/assets/109418897/30b54e5d-6054-4343-a0d9-b3c2ddcfab54)
![image](https://github.com/PreMiD/Presences/assets/109418897/908ec548-de25-4e9e-8e5c-6c86fa4f02a1)

### Operating System

Windows 11

### Browser and Version

Google Chrome Version 125.0.6422.142 (Official Build) (64-bit)

### Additional Comments

Please fix this as soon as possible, I'm in love with the new UI and i'm kinda sad it doesn't work

**Comment by tag27** [comment]
The timestamps and buttons don't appear because you're using the "watching" status. This is a problem with Discord itself, not with PreMiD or presence. If you want the timestamps back, activate this switch in the extension settings:

![image](https://github.com/PreMiD/Presences/assets/68751594/f32a2612-e20b-4632-a781-ebf8ead1e3b7)

**Comment by honzawashere** [comment]
Hey, thanks a lot for your reply! Will try it out tomorrow.

**Comment by theusaf** [comment]
Issue is related to Discord/extension
