### ISSUE TITLE
Aniwave Lite | lite.aniwave.to - displays incorrect information

### ISSUE THREAD

**Issue by hir0xygen** [PreMiD/Presences#8502]
### Steps to Reproduce

1. Enable the Aniwave presence
2. Start watching an Anime on lite.aniwave.to
3. Compare presence to what it displays when watching on aniwave.to

### Expected Behavior

It shows the same information, regardless if you're using the lite version or not

### Actual Behavior

It shows "Notification - Episode 1" instead of the anime title and correct episode number, cover image is missing

### Page URL

https://lite.aniwave.to/watch/tv-kaijuu-8-gou-llrk6/ep-2

### Screenshots

On aniwave.to:
![](https://i.imgur.com/Jxtj9Jx.png)
On lite.aniwave.to:
![](https://i.imgur.com/LBxLkxJ.png)
In the second screenshot, I am also on episode 2, not even episode 1.

### Operating System

Artix Linux

### Browser and Version

Firefox 127.0.1 (64-bit)

**Comment by tag27** [comment]
This issue has to be closed because Aniwave's presence no longer exists.

**Comment by hir0xygen** [comment]
Yep.
