### ISSUE TITLE
Mangadex | mangadex.org - images do not display correctly

### ISSUE THREAD

**Issue by FA4ST** [PreMiD/Presences#8530]
### Steps to Reproduce

1.

### Expected Behavior

I want to know how to fix it

### Actual Behavior

The image on mangadex does not appear

### Page URL

mangadex.org

### Screenshots

![image](https://github.com/PreMiD/Presences/assets/172389155/05b00613-acb9-492b-b76f-2ffb6a8d76ba)

### Operating System

10

### Browser and Version

chrome Version 126.0.6478.114

**Comment by DarkVillager** [comment]
I can reproduce

**Comment by itsmeeudrino** [comment]
I'm able to reproduce the bug aswell, it appears that discord cdn can't access that domain, sending the image link in chat fails to show the thumbnail.
any ideas to get around that?

**Comment by theusaf** [comment]
For future developer: solution could be to download the image via fetch and pass the blob/blob url as the image key when setting activity.
