### ISSUE TITLE
Pulsus | pulsus.cc

### ISSUE THREAD

**Issue by tag27** [PreMiD/Presences#8532]
### Website name

Pulsus

### Website URL

https://www.pulsus.cc (Redirects to https://www.pulsus.cc/play)

### Website logo

https://pulsus.cc/client/resources/img/logo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

Name of the presence, name of the beatmap, and the remaining time of the song. Just like other presences inside and outside PreMiD, such as Osu and Quaver.

**Comment by mallusrgreatv2** [comment]
there is no element in the code that shows the name of the beatmap
