### ISSUE TITLE
BetterAnime | betteranime.net - Use 'Watching' status instead of 'Playing'

### ISSUE THREAD

**Issue by rukasu2424** [PreMiD/Presences#8570]
### Presence name

BetterAnime

### Description

I wish they would change the playing to watching

**Comment by DarkVillager** [comment]
@theusaf Site has been closed. So close this please.
![image](https://github.com/user-attachments/assets/6cc8782d-504e-4a87-b6f1-cb58d6d25869)

**Comment by rukasu2424** [comment]
> @theusaf Site has been closed. So close this please. ![image](https://private-user-images.githubusercontent.com/42322979/350689756-6cc8782d-504e-4a87-b6f1-cb58d6d25869.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzcyNjIsIm5iZiI6MTcyMTQ3Njk2MiwicGF0aCI6Ii80MjMyMjk3OS8zNTA2ODk3NTYtNmNjODc4MmQtNTA0ZS00YTg3LWI2ZjEtY2I1OGQ2ZDI1ODY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEyMDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNTEyZTk1ZjhkOTBjNDViNDlmNmRmZGQzZDRhYWM5NGQ3NmI2MTA0MGE3YTBmY2M0OTE5ZDE2NTk0MTc0M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WjTt5tOrKQfYP6r535Uj6_GHlB_nqskSbzbRNBc7PWg)

The website still works, just click on that person icon and log in with your account.
and they are still uploading anime

**Comment by DarkVillager** [comment]
> > @theusaf Site has been closed. So close this please. ![image](https://private-user-images.githubusercontent.com/42322979/350689756-6cc8782d-504e-4a87-b6f1-cb58d6d25869.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzcyNjIsIm5iZiI6MTcyMTQ3Njk2MiwicGF0aCI6Ii80MjMyMjk3OS8zNTA2ODk3NTYtNmNjODc4MmQtNTA0ZS00YTg3LWI2ZjEtY2I1OGQ2ZDI1ODY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEyMDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNTEyZTk1ZjhkOTBjNDViNDlmNmRmZGQzZDRhYWM5NGQ3NmI2MTA0MGE3YTBmY2M0OTE5ZDE2NTk0MTc0M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WjTt5tOrKQfYP6r535Uj6_GHlB_nqskSbzbRNBc7PWg)
> 
> The website still works, just click on that person icon and log in with your account. and they are still uploading anime

bruh
