### ISSUE TITLE
Konachan.com

### ISSUE THREAD

**Issue by weebskinosu** [PreMiD/Presences#858]
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [x] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** : SleepingD#9170

**What's the name of the service?** : https://konachan.com/

**What should the Presence display?** see post / what picture i watching / what i do in this site etc.

**If possible, please provide a logo for the service (512x512 minimum)** : ![](http://www.userlogos.org/files/logos/motoko-chan/logo_0.png)

**Comment by doomlerd** [comment]
Has a SFW derivative which is operated under the same name but a different domain :
http://konachan.net
