### ISSUE TITLE
Plex | Support Watching status and Title as Presence Name

### ISSUE THREAD

**Issue by pierrequiroul** [PreMiD/Presences#8606]
### Presence name

Plex

### Description

Can you add support for Watching status when watching a film/series and Listening to status when listening to music?
Also can you add support for changing the Presence name to the name of the movie/series you're watching, like Netflix Precense?

### Additional context

![image_2024-07-24_235244061](https://github.com/user-attachments/assets/c38c2c89-9d53-4946-8c19-3059f89d6d1f)
![image_2024-07-24_235348187](https://github.com/user-attachments/assets/8fb0f5dc-06e5-441a-ad34-5d579c04219d)

**Comment by DarkVillager** [comment]
Sure
