### ISSUE TITLE
Google Meet | meet.google.com - add title of the room in presence display

### ISSUE THREAD

**Issue by sambhavsaxena** [PreMiD/Presences#8608]
### Presence name

Google Meet

### Description

Can we not have title of the room in the response of presence status? Just like we get the number of people in the room?

**Comment by DarkVillager** [comment]
So you want an option to hide the title?

**Comment by sambhavsaxena** [comment]
oh no, I'm using presence on my portfolio like so:
![image](https://github.com/user-attachments/assets/0b514051-0909-4cb5-98b8-4d8e96bdf8ba)

But for Google Meet, I get only the number of people in the room, but not the room title, which looks something like this:
![image](https://github.com/user-attachments/assets/0e1ffaaf-ab22-4fb6-aec5-447f82a3697f)
