### ISSUE TITLE
Netflix | www.netflix.com - Add a "Show Images" setting

### ISSUE THREAD

**Issue by brxndonroux** [PreMiD/Presences#8610]
### Presence name

Netflix

### Description

can there be a "Show Images" button be added to netflix

**Comment by DarkVillager** [comment]
@brxndonroux what do u mean?

**Comment by brxndonroux** [comment]
okay so when i watch a movie or series it shows the thumbnail of what im watching, by adding a button you can either choose to show the thumb or not (just the netflix logo)

**Comment by DarkVillager** [comment]
> okay so when i watch a movie or series it shows the thumbnail of what im watching, by adding a button you can either choose to show the thumb or not (just the netflix logo)

Ah, i'll look into that for u

**Comment by brxndonroux** [comment]
awesome thanks!
