### ISSUE TITLE
YouTube Music | music.youtube.com - video title with special font doesn't display in Discord

### ISSUE THREAD

**Issue by CoolPeachGaming** [PreMiD/Presences#8636]
### Steps to Reproduce

1. Go to https://music.youtube.com/watch?v=VjnG4oYTiMg
2. Play song
3. Observe no change in Discord activity

### Expected Behavior

The song is supposed to display in Discord

### Actual Behavior

The last updated action is displayed instead, or when listening to another song, that song is displayed.

### Page URL

https://music.youtube.com/watch?v=VjnG4oYTiMg

### Screenshots

![image](https://github.com/user-attachments/assets/9d2db4fb-cc6b-4e1f-8ef3-e334e9d19a34)
![image](https://github.com/user-attachments/assets/2071a5a7-f358-4c3d-9508-6c94e12afa72)

### Operating System

Windows 11

### Browser and Version

Thorium Version 124.0.6367.218

### Additional Comments

Videos titles with other fonts successfully display in Discord, but this specific font doesn't seem to like being displayed.

**Comment by Slowlife01** [comment]
It's not the font it's the length

**Comment by DarkVillager** [comment]
> It's not the font it's the length

This seems to be a bug in the extension, since before it'd remove after 128 and now it just returns. It has been reported in [a post for the alpha/beta](https://ptb.discord.com/channels/493130730549805057/1269261303483072512).

**Comment by DarkVillager** [comment]
It's fixed in the next alpha. It indeed was the font causing it to not be cut after 128 characters.

**Comment by theusaf** [comment]
Closing since it is an extension bug, not a presence one. Seems to be fixed in an upcoming extension update.
