### ISSUE TITLE
Braflix | www.braflix.ru

### ISSUE THREAD

**Issue by degu-Tanya** [PreMiD/Presences#8644]
### Website name

Braflix

### Website URL

https://www.braflix.ru

### Website logo

https://www.braflix.ru/logo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

https://premid.app/store/presences/FMovies just for Braflix
Or something similar to fbox, netflix, disney etc from the store for Braflix 

what content Braflix offers, it would be nice for the presence to work on all these tabs it has.
![image](https://github.com/user-attachments/assets/f844c913-0772-4ceb-9b4a-48b1858a5649)

**Comment by KauaAniceto** [comment]
I really wanted a presence for this site

**Comment by Kuriel23** [comment]
Braflix has officially closed.

![image](https://github.com/user-attachments/assets/ad244e12-ed3e-47d7-bd02-a6ad1d167b9b)

@theusaf can you close this issue?
