### ISSUE TITLE
Pony Town | pony.town

### ISSUE THREAD

**Issue by FalafelToJa** [PreMiD/Presences#8656]
### Website name

Pony Town

### Website URL

https://pony.town

### Website logo

https://i.imgur.com/D4tPKtj.png

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

Can I add how long you play Pony Town and on which server? And maybe what the name of our pony is

**Comment by tag27** [comment]
Duplicate of #5416
