### ISSUE TITLE
Hurawatch | hurawatch.cc

### ISSUE THREAD

**Issue by soulrunsu** [PreMiD/Presences#8657]
### Website name

Hurawatch

### Website URL

https://hurawatch.cc/

### Website logo

https://img.hurawatch.cc/xxrz/400x400/100/88/52/88526f5e66ecc3b78ee9a1744d4c8457/88526f5e66ecc3b78ee9a1744d4c8457.png

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

its a movie website

**Comment by theusaf** [comment]
Duplicate of #5253
