### ISSUE TITLE
Jummbox | jummb.us - presence no longer works after URL change

### ISSUE THREAD

**Issue by kam106** [PreMiD/Presences#8664]
### Steps to Reproduce

1. Visit https://jummb.us (new url for Jummbox)
2. Attempt to use the site normally

### Expected Behavior

The presence would activate from the new jummb.us domain

### Actual Behavior

The presence tries to detect jummbus.bitbucket.io instead, effectively disabling the rich presence when it redirects to the new domain

### Page URL

https://jummb.us/

### Operating System

Windows 11 x64

### Browser and Version

Floorp v11.17.4

### Additional Comments

The music site Jummbox changed urls from a bitbucket URL to their own domain, jummb.us very recently. Since then, the old domain always redirects the user to the new domain, effectively making it's rich presence outdated, as the new url is never detected.

This could be very easily fixed by replacing instances of jummbus.bitbucket.io to jummb.us where possible. [I assume that's done through the metadata.json file.](https://github.com/PreMiD/Presences/blob/main/websites/J/Jummbox/metadata.json)

**Comment by kam106** [comment]
I'm unsure which URL to use for the issue title. Should the old or the new URL be used?

**Comment by poyribn** [comment]
i thought you would automatically register the URL i entered at the beginning of [the form](https://webcompat.com/issues/new?url=https://jummb.us/) into the issue.
the URL is https://jummb.us
