### ISSUE TITLE
Youtube | youtube.com - Broken status text

### ISSUE THREAD

**Issue by skullysmods** [PreMiD/Presences#8679]
### Steps to Reproduce

Go to Youtube and watch any video. The status will be broken some of the time

### Expected Behavior

Status texts (title, channel name, etc.) must appear on the status.

### Actual Behavior

The status texts are broken

### Page URL

https://www.youtube.com/watch?v=ZMILtWGywZA

### Screenshots

![image](https://github.com/user-attachments/assets/79d685d3-e906-4608-8079-154c035f237c)
![image](https://github.com/user-attachments/assets/f49473be-5298-4d9b-9883-05ec1135ce98)

### Operating System

Windows 11

### Browser and Version

Brave Browser | Version 1.69.153 Chromium: 128.0.6613.85 (Official build) (64 bits)

**Comment by skullysmods** [comment]
(If you open a new Youtube tab or relaunch the browser, it works normally again.)

**Comment by tag27** [comment]
If I'm not mistaken, this is not exactly a problem of presence, but it is of extension.

**Comment by vfhbfyyf** [comment]
Боже мой... как здорово! благодетель вы наш)) спасибо огромное!

**Comment by theusaf** [comment]
Closing as issue is an issue related to the extension rather than presence code
