### ISSUE TITLE
Cisco Networking Academy | www.netacad.com - Add Legacy URL

### ISSUE THREAD

**Issue by murcat0** [PreMiD/Presences#8695]
### Presence name

Cisco Networking Academy

### Description

**Cisco Networking Academy has two websites one for new NetAcad and one for Legacy.**

The legacy website is not working, adding a second URL for legacy would be nice.
The legacy url is https://legacy.netacad.com
The URL for new NetAcad remains www.netacad.com

**Comment by darkvillager2** [comment]
@theusaf  / @Bas950 issue resolved, close this please.
