### ISSUE TITLE
SoundCloud | soundcloud.com | v2.4.14 - Issue Title

### ISSUE THREAD

**Issue by shay6ix** [PreMiD/Presences#8703]
### Steps to Reproduce

i dont really know how you could fix it

### Expected Behavior

to be on time, and show the timestamps when i have it enabled

### Actual Behavior

whenever i skip the song it doesnt show that i skipped it until 10-20 seconds after (for some reason its different everytime)same with pausing and it doesnt show what time im at or anything just the song title and artist

### Page URL

soundcloud.com

### Screenshots

![Screenshot_283](https://github.com/user-attachments/assets/3f7c4aca-62e3-44d0-a456-43c62febc0a8)

### Operating System

windows 11

### Browser and Version

opera gx core 112.0.5197.104

**Comment by tag27** [comment]
The timestamps don't appear because you're using the "listening" status. This is a problem with Discord itself, not with PreMiD or presence.

**Comment by theusaf** [comment]
Closing as behavior is Discord-side related, not presence related.
