### ISSUE TITLE
Netflix | www.netflix.com - presence doesn't appear

### ISSUE THREAD

**Issue by moonie7272** [PreMiD/Presences#8714]
### Steps to Reproduce

Netflix presence doesnt show on Discord.

### Expected Behavior

No presence seen in DIscord

### Actual Behavior

Presence of netflix

### Page URL

https://www.netflix.com/watch/81704692?trackId=14170286&tctx=2%2C1%2Cfeca1d35-75b8-407b-a64e-07c2c4282309-95562949%2CNES_EB649CA0285EBC07A6E2DBBBA5FB6F-994911DC4F528C-2D88349201_p_1725719002407%2CNES_EB649CA0285EBC07A6E2DBBBA5FB6F_p_1725718129205%2C%2C%2C%2C%2CVideo%3A81704692%2CminiDpPlayButton

### Operating System

Windows 10

### Browser and Version

Chrome

**Comment by theusaf** [comment]
Duplicate of #8400
