### ISSUE TITLE
Uncaught (in promise) Error: Access to storage is not allowed from this context.

### ISSUE THREAD

**Issue by notMohab** [PreMiD/Presences#8717]
### Steps to Reproduce

any website that i want to show it says the same thing Access to storage is not allowed

### Expected Behavior

to work

### Actual Behavior

doesnt 

### Page URL

https://www.netflix.com/watch/70206694?trackId=155573560           ....   https://soundcloud.com/you/likes

### Screenshots

![image](https://github.com/user-attachments/assets/71ccb253-c80f-481c-a4ed-6bbf2d0372f3)
![image](https://github.com/user-attachments/assets/fbe10454-1917-44a3-8bcb-7bee3ab9090c)

### Operating System

windows 11 

### Browser and Version

brave v1.69.162

### Additional Comments

love yall i hope i can fix it or u give me a fix

**Comment by tag27** [comment]
https://github.com/PreMiD/Presences/issues/8708#issuecomment-2327380372
