### ISSUE TITLE
Emby |  * - Latest version breaks presence, only browsing

### ISSUE THREAD

**Issue by ProfessorFartsalot** [PreMiD/Presences#8749]
### Steps to Reproduce

With Emby v4.8.8 it seems the rich presence assumes I am always browsing music or (in 4.9 beta) at the home page, even if I play music.

### Expected Behavior

I expected the emby presence to show the music I am currently playing

### Actual Behavior

The emby presence says I am on the home page, or browsing. It never shows the music or content I am playing.

### Page URL

https://us-e-argon.firehostredux.com:2096/

### Screenshots

![image](https://github.com/user-attachments/assets/e1dadfce-ac9f-4142-b724-4d5dcc497c96)

### Operating System

Windows 11

### Browser and Version

Firefox 130.0.1 (64-bit)

**Comment by ProfessorFartsalot** [comment]
Just rolled back to Emby 4.7.11 and everything does seem to work as intended again, I think it's due to their UI changes in 4.8.X (they added a sidebar and changed the admin menu slightly too, also when you play music it queues everything in the folder/group you clicked so not a huge fan of the 4.8 version anyway...). As such, I'm assuming the presence is looking for an element that no longer exists in 4.8 and is why the extension behaves like this.

If this does get fixed, is it possible to maintain compatibility with Emby 4.7.X as well? I honestly think I'd rather stay on 4.7 due to some annoying changes made to emby in 4.8+.

**Comment by darkvillager2** [comment]
> Just rolled back to Emby 4.7.11 and everything does seem to work as intended again, I think it's due to their UI changes in 4.8.X (they added a sidebar and changed the admin menu slightly too, also when you play music it queues everything in the folder/group you clicked so not a huge fan of the 4.8 version anyway...). As such, I'm assuming the presence is looking for an element that no longer exists in 4.8 and is why the extension behaves like this.
> 
> If this does get fixed, is it possible to maintain compatibility with Emby 4.7.X as well? I honestly think I'd rather stay on 4.7 due to some annoying changes made to emby in 4.8+.

I'll look into it. I think it should be possible to maintain compatibility with both.

**Comment by darkvillager2** [comment]
I've started the work required to make it work.

**Comment by darkvillager2** [comment]
Day 2 update:
Seems like i can make both versions work, so im looking into the way i wanna persue for this.

**Comment by ProfessorFartsalot** [comment]
Thank you, yes I will add you to stay up to date.
