### ISSUE TITLE
WWE Network

### ISSUE THREAD

**Issue by ghostboy777** [PreMiD/Presences#8752]
### Website name

WWE Network

### Website URL

https://network.wwe.com/home

### Website logo

https://static.diceplatform.com/prod/AUTOx350/dce.wwe/settings/network_logo_new.png?ts=1552562839

### Prerequisites

- [X] It is a paid service
- [ ] It is region restricted

### Description

It's like netflix but wwe, someone already asked but it was in 2022 so i try again, thanks if you add it.

**Comment by tag27** [comment]
Duplicate of #5474
