### ISSUE TITLE
Kindle | read.amazon.in - presence doesn't support `.in` tld

### ISSUE THREAD

**Issue by ZYMONE135** [PreMiD/Presences#8755]
### Steps to Reproduce

go to kindle libray, start reading any ebook, go to discord to check if premid is showing that as a public activity ot not.

### Expected Behavior

It was expected for premid to show kindle activity

### Actual Behavior

It didn't show 

### Page URL

https://read.amazon.in/kindle-library

### Screenshots

![image](https://github.com/user-attachments/assets/2e824eae-ee74-4136-a20c-9f0aaf9ab785)
![image](https://github.com/user-attachments/assets/8e2cfe10-189a-4e43-900f-a5c1608f21bc)

### Operating System

Windows 11

### Browser and Version

Microsoft Edge - Version 129.0.2792.52 (Official build) (64-bit)

**Comment by tag27** [comment]
The problem with presence not being recognized is simply that it doesn't support the `read.amazon.in` domain. It only supports the German subdomain (`lesen.amazon.de`) and the English domain (`read.amazon.com`) ![image](https://github.com/user-attachments/assets/66e08c22-af2d-453d-a277-c089f157c924)
