### ISSUE TITLE
x.com plugin

### ISSUE THREAD

**Issue by daglaroglou** [PreMiD/Presences#8757]
### Steps to Reproduce

i noticed that whichever site ends with x.com like netflix.com or hackthebox.com or even roblox.com, x's extension shows up with empty state and details

### Expected Behavior

not show x.com plugin

### Actual Behavior

show corresponding plugin  presence

### Page URL

any supported site ending at ...x.com like hackthebox.com or netflix.com

### Operating System

Windows 11

### Browser and Version

Brave v1.70.117

**Comment by darkvillager2** [comment]
Can reproduce.

**Comment by darkvillager2** [comment]
@Timeraa fixed it in latest ALPHA.

**Comment by daglaroglou** [comment]
cool, should i close the issue?

**Comment by theusaf** [comment]
Issue is related to extension, not presences, and is a known and fixed problem (in alpha). Closing.
