### ISSUE TITLE
Netflix | www.netflix.com | v6.0.0 - Issue Details

### ISSUE THREAD

**Issue by Infer2** [PreMiD/Presences#8764]
### Steps to Reproduce

1. go to netflix.com
2. Check the discord status

### Expected Behavior

Display the episodes

### Actual Behavior

details are messed

### Page URL

https://www.netflix.com/watch/81313452

### Screenshots

![image](https://github.com/user-attachments/assets/84d3c231-54d9-4c24-a721-f0797616372e)

### Operating System

Windows 11

### Browser and Version

Brave

**Comment by theusaf** [comment]
This could be a temporary localization issue with the extension. Try reloading/reinstalling the presence/extension and see if that fixes the issue.
