### ISSUE TITLE
AnimationDigitalNetwork | animationdigitalnetwork.com

### ISSUE THREAD

**Issue by ByZorks** [PreMiD/Presences#8786]
### Steps to Reproduce

1. Go to animationdigitalnetwork.com

### Expected Behavior

Seeing the presence on your profile

### Actual Behavior

Nothing appear

### Page URL

animationdigitalnetwork.com

### Operating System

Windows 11

### Browser and Version

Chrome 129.0.6668.90

**Comment by darkvillager2** [comment]
I’ll look into iy

**Comment by darkvillager2** [comment]
Can't reproduce
![image](https://github.com/user-attachments/assets/8f67c0b8-a8cc-4084-a571-73540a421b33)

**Comment by ByZorks** [comment]
removing and adding back the presence several times seems to have fixed it...
