### ISSUE TITLE
bol.com

### ISSUE THREAD

**Issue by nbeerten** [PreMiD/Presences#881]
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** nbeerten#2620

**What's the name of the service?** https://www.bol.com/

**What should the Presence display?** It should display it like this: 
**bol.com**
Viewing [homepage/product]
[Product Catogery]

**If possible, please provide a logo for the service (512x512 minimum)** 
![image](https://user-images.githubusercontent.com/59444993/71778472-9ba02480-2fae-11ea-80f3-870efaeb933c.png)

**Comment by QkeleQ10** [comment]
I can do this one :D

**Comment by QkeleQ10** [comment]
@nbeerten could you close this one?
