### ISSUE TITLE
HBO GO | hbogo.ro | v2.3.7 - Issue Title

### ISSUE THREAD

**Issue by lai52066** [PreMiD/Presences#8820]
### Steps to Reproduce

"Playing videos from [https://www.hbogoasia.tw/ ](https://www.hbogoasia.tw/)does not show up in the Discord status bar

### Expected Behavior

Show status bar

### Actual Behavior

No status displayed

### Page URL

https://www.hbogoasia.tw/

### Screenshots

![image](https://github.com/user-attachments/assets/b59f16cb-d069-4016-89cb-7b0d93d34a0f)
![image](https://github.com/user-attachments/assets/1540a1ee-b8ba-4338-a2e4-931313ceaf63)

### Operating System

Windows 11

### Browser and Version

Microsoft Edge 版本 130.0.2849.35

**Comment by theusaf** [comment]
Merging into #8820
