### ISSUE TITLE
BATOTO | bato.to

### ISSUE THREAD

**Issue by seatofsacrifice** [PreMiD/Presences#8824]
### Website name

BATOTO

### Website URL

https://bato.to/v3x

### Website logo

https://bato.to/public-assets/img/bato-favicon.ico?v1

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

It's a manga reading site, I'd personally like for it to be similar to other manga site presences like Comick.

**Comment by tag27** [comment]
Duplicate of #5687
