### ISSUE TITLE
Braflix | www.braflix.is

### ISSUE THREAD

**Issue by brxndonnn** [PreMiD/Presences#8833]
### Website name

Braflix

### Website URL

https://www.braflix.is/

### Website logo

https://www.braflix.is/logo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

I’d like to request adding a Braflix presence to Premid.

This feature should update in real time to reflect what users are watching on Braflix.

**Comment by tag27** [comment]
Duplicate of #8644
