### ISSUE TITLE
YouTube Music | music.youtube.com - disabling "Show Browsing" hides the music

### ISSUE THREAD

**Issue by elfi-ox** [PreMiD/Presences#8838]
### Steps to Reproduce

![image](https://github.com/user-attachments/assets/ccbcc885-591b-4c85-89d8-7ca3a2a2404a)
1. Use these setting
2. When "Show Browsing" is deselected the presence disappear 

### Expected Behavior

the presence should stay unless no music is selected 

### Actual Behavior

the presence disappear no matter what

### Page URL

https://music.youtube.com/watch?v=8s-NKe-2ZAk&list=RDAMVM2KuWjZD6PBA

### Screenshots

![Show Browsing off](https://github.com/user-attachments/assets/b396904d-5e24-4242-84ff-73db09bad9d4)
![Show Browsing off](https://github.com/user-attachments/assets/7d2c32f1-8a2c-4359-93da-1b7dde7ad0ba)

### Operating System

Windows 11 23H2

### Browser and Version

Firefox 131.0.3

### Additional Comments

Premid 2.6.12
Youtube Music Pressence 3.0.22

**Comment by slxdy** [comment]
I can confirm I'm having the same issue on Chrome for Windows, Premid with linked acc (no app)

**Comment by darkvillager2** [comment]
I can reproduce.
