### ISSUE TITLE
Stadia | stadia.google.com

### ISSUE THREAD

**Issue by Phase10-5828** [PreMiD/Presences#884]
* [X] Is it a popular site? Somewhat, currently only open as a $129USD Paid-Beta
* [x] Is the website older than 2 months?  Yes
* [X] Is the site locked to a specific country/region? Yes, to the following locations (at time of published): Belgium, Canada, Denmark, Finland, France, Germany, Ireland, Italy, Netherlands, Norway, Spain, Sweden, United Kingdom, United States
* [X] Is the site a paid service? (e.g. Netflix, Hulu) No, There is a premium option, but is not needed to play (there's also a free 2-month trial right now!) You do need to buy the games though.
* [ ] Does the website feature NSFW content? (e.g. porn, etc...) No, highest rated games are M
* [ ] Are you a donator/patron? No, but if I had money I would
* [X] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? Yes

**What's your Discord username?**  Phase10#5828

**What's the name of the service?** 
stadia.google.com | www.stadia.com | Stadia

**What should the Presence display?**  
Current Game being played, and time elapsed within that game. I would also like for one of the pictures (attached to the rich presence) to be the games logo. If possible, add what your doing in that game (I doubt that last one is doable).

**If possible, please provide a logo for the service (512x512 minimum)**  Attached are two possible logos to choose from:

![google_stadia_logo_new](https://user-images.githubusercontent.com/59545966/71790398-db3e2f00-2ff5-11ea-9658-79ffaba9eff1.jpg)
![google-stadia-logo-1280x1279](https://user-images.githubusercontent.com/59545966/71790405-e1cca680-2ff5-11ea-98e1-61a953f534a5.png)

**Comment by doomlerd** [comment]
> I would also like for one of the pictures (attached to the rich presence) to be the games logo. If possible, add what your doing in that game (I doubt that last one is doable).

Both are impossible, the first is theoretically possible but still can't be done because of technical issues and Discord's ToS.

**Comment by Phase10-5828** [comment]
Thanks for the reply! Ok, at least it should still be able to see what game there playing in time elapsed right? Those were just extras that I didn't think would work anyways!

**Comment by doomlerd** [comment]
Can it be played on a webpage ( HTML5 ) ?

**Comment by Phase10-5828** [comment]
Yes, it is played either, in the mobile app (Pixel devices), in the chrome browser, or on a chromecast ultra. Within the website itself, it says the games your friends/you are playing, so should be easy to grab that info.

**Comment by Phase10-5828** [comment]
I'm pretty sure it is using HTML5, considering it was made recently, although, it was probably made long before the website was publicly available (registered under the stadia.google.com domain)

**Comment by doomlerd** [comment]
> I'm pretty sure it is using HTML5, considering it was made recently, although, it was probably made long before the website was publicly available (registered under the stadia.google.com domain)

Then it is possible to add the game you're currently playing and also the time ( may be a little bit tricky though ).

**Comment by Phase10-5828** [comment]
Ok, thanks for the quick responses. Good luck to whomever ends up working on it!

**Comment by SnoweyFoxx** [comment]
Just a little update, I have started working on a presence for Stadia. :)
