### ISSUE TITLE
kick

### ISSUE THREAD

**Issue by mojo1234mojo** [PreMiD/Presences#8845]
### Presence name

kick

### Description

![Screenshot 2024-10-27 192622](https://github.com/user-attachments/assets/b897b28b-8a39-4a35-a8bb-adca6fffdce1)
regardless of what I'm looking at on Kik or if I'm watching a stream it says I'm browsing Kick...

**Comment by tag27** [comment]
It has already been fixed via #8827 pr. For now, it is only in the BETA and ALPHA version of the extension.

**Comment by mojo1234mojo** [comment]
Thanks Riley Hanon(250) ***@***.*** On Oct 28, 2024, at 8:48 AM, #27 ***@***.***> wrote:﻿
It has already been fixed via #8827 pr. For now, it is only in the BETA and ALPHA version of the extension.
