### ISSUE TITLE
Archive of Our Own | archiveofourown.org | v1.0.7 - Issue Title

### ISSUE THREAD

**Issue by frightsnights** [PreMiD/Presences#8846]
### Steps to Reproduce

I do not know how to reproduce this, as it randomly happened.

### Expected Behavior

When I closed Ao3, i expected the presence to go away.

### Actual Behavior

It did not go away.

### Page URL

https://archiveofourown.org/

### Screenshots

![image](https://github.com/user-attachments/assets/94ff5a90-0bc3-4998-99e6-192cbb4815b3) 
![image](https://github.com/user-attachments/assets/b4cb0b78-4ec8-406d-b954-00c28831a504)

### Operating System

Windows 11

### Browser and Version

Opera GX core: 114.0.5282.123

**Comment by theusaf** [comment]
This is unlikely to be a presence issue, but an extension issue. Try directing this to the relevant repositories or support server.
