### ISSUE TITLE
Board Game Arena | boardgamearena.com - not showing game name

### ISSUE THREAD

**Issue by audabas** [PreMiD/Presences#8847]
### Steps to Reproduce

1. Start playing any game on BGA

### Expected Behavior

Showing "Playing [game name]"

### Actual Behavior

Shows "Playing undefined"

### Page URL

https://boardgamearena.com/

### Screenshots

![image](https://github.com/user-attachments/assets/91a75d86-3c75-4cc9-9ec1-34ae0972c294)

### Operating System

Windows 10

### Browser and Version

Brave v1.71.118

**Comment by darkvillager2** [comment]
I can't reproduce
![image](https://github.com/user-attachments/assets/5d0ae190-964e-44c2-a83e-aa41bab6dcbb)

**Comment by audabas** [comment]
> I can't reproduce

That's strange.
I tried on Google Chrome, changed BGA language to english, started a Framework solo game and still have the same issue...
