### ISSUE TITLE
Request | diziay.me

### ISSUE THREAD

**Issue by smilefate** [PreMiD/Presences#886]
**Prerequisites and essential questions** 
* [ ] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  
♔ ♕ 【Emir「SmileFate」】#9595
**What's the name of the service?** 
https://diziay.me | diziay
**What should the Presence display?** 
series and movie tracking information
**If possible, please provide a logo for the service (512x512 minimum)** 
https://diziay.me/views/default/assets/img/logo.png

**Comment by MrSpinne** [comment]
I'll try to get it done for you in the next days.

**Comment by doomlerd** [comment]
@smilefate please agree to the last checkbox or the issue will be closed if @MrSpinne doesn't add it.

**Comment by smilefate** [comment]
@doomlerd is it OK ? Would you check?

**Comment by doomlerd** [comment]
> @doomlerd is it OK ? Would you check?
> 
> sorry I don't use Github much, so I don't know much

It's all good.

**Comment by emirkabal** [comment]
#890 pull request is waiting

**Comment by smilefate** [comment]
waow good, thank you^-^)

**Comment by emirkabal** [comment]
closes #886
