### ISSUE TITLE
YouTube | www.youtube.com | v5.13.3 - Issue Title

### ISSUE THREAD

**Issue by htfq** [PreMiD/Presences#8861]
### Steps to Reproduce

watch a yt video let it end then it just keeps saying its being played then turn off pc like shutdown and then its just stuck forever

### Expected Behavior

i didnt attempt its a bug

### Actual Behavior

i didnt attempt its a bug

### Page URL

https://www.youtube.com/watch?v=tHEceFYgNaY

### Operating System

Windows 11

### Browser and Version

Brave 1.71.121

**Comment by theusaf** [comment]
This issue is related to the extension, not the presence. The devs are aware of this issue and are working on solutions.
