### ISSUE TITLE
https://www.freefilm.to

### ISSUE THREAD

**Issue by Thalleya** [PreMiD/Presences#888]
**Prerequisites and essential questions** 
* [ ] Is it a popular site?
* [x] Is the website older than 2 months? 
* [x] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [ ] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** 

**What should the Presence display?** 

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Thalleya** [comment]
Its Slovak website for films. I prefer it

**Comment by doomlerd** [comment]
That's not how the template works, plus the domain is WHOIS protected and we don't guarantee support for unpopular services because simply no one would volunteer for it and secondly because we're trying to keep it all clean.
