### ISSUE TITLE
DashNet: Memory Leak

### ISSUE THREAD

**Issue by Reycko** [PreMiD/Presences#8881]
### Steps to Reproduce

1. Get DashNet / Cookie Clicker presence
2. Huge amounts of ram usage. On Firefox, at least.

### Expected Behavior

Proper RPC without any memory leaks.

### Actual Behavior

16GB of ram used in less than a minute.

### Page URL

https://orteil.dashnet.org/cookieclicker/

### Operating System

Windows 11 23H2

### Browser and Version

Firefox Nightly 134.0a1 (2024-11-10) (64-bit)

**Comment by darkvillager2** [comment]
I can reproduce.
Will see if i can fix it later today.

**Comment by darkvillager2** [comment]
Found a fix, but might rewrite the whole presence.
