### ISSUE TITLE
Add NBA website for basketball streams (If you have the league pass)

### ISSUE THREAD

**Issue by AL-Dawg** [PreMiD/Presences#8889]
### Website name

NBA

### Website URL

https://www.nba.com/

### Website logo

NBA logo

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

Presence to show when i am watching any type of basketball game. This is the offiial NBA website also.

**Comment by tag27** [comment]
Duplicate of #5908
