### ISSUE TITLE
YouTube | www.youtube.com | v5.13.3 - Discord's status message not showing what is intended to show

### ISSUE THREAD

**Issue by KMRDul** [PreMiD/Presences#8903]
### Steps to Reproduce

1. Go to Youtube
2. Click on a video

### Expected Behavior

To show me the title, uploader and time stamp of the video in Discord's RP

### Actual Behavior

Discord status showing me "general.watchingVid" and time stamp instead of infos about the video I'm watching

### Page URL

youtube.com

### Screenshots

![Screenshot_6](https://github.com/user-attachments/assets/69cbd86f-3719-4c0e-b8c1-fe0d30a84084)

### Operating System

Windows 10

### Browser and Version

Brave Version 1.73.91 Chromium: 131.0.6778.85

### Additional Comments

Also this bug persist when I'm browsing, or watching a Livestream.
![image](https://github.com/user-attachments/assets/08410fd1-dcf9-4876-afd1-1a412effa328)
![image](https://github.com/user-attachments/assets/a77b4b30-325e-4666-8394-471b7b094cc1)

**Comment by Espressocodes** [comment]
Issue is privacy mode. Please refer to the [Youtube Malfunction](https://pre.docs.pmd.crun.zip/troubleshooting/issues/media-presence-based.html#youtube-malfunction) documentation for further information
