### ISSUE TITLE
Apple Music Presence | https://premid.app/store/presences/Apple%20Music

### ISSUE THREAD

**Issue by eliqts** [PreMiD/Presences#8905]
### Steps to Reproduce

1. Go to Apple Music, sign into an account and play a song.
2. Go to your Discord profile and view the presence after a few minutes of a song playing.

### Expected Behavior

The presence is supposed to appear on your profile and accurately state the timestamps of the song.

### Actual Behavior

The presence gets stuck on certain timestamps, and then freezes.

### Page URL

N/A

### Screenshots

https://github.com/user-attachments/assets/6171afe6-742f-4e36-81e6-ef38550f2e0e

### Operating System

Windows 11

### Browser and Version

Google Chome Version 131.0.6778.86

### Additional Comments

Contact me on Discord if you need further assistance:
@eliqts

**Comment by Espressocodes** [comment]
![image](https://github.com/user-attachments/assets/a59b0069-8f7d-4ef3-a08f-840ab2cdea48)
Tested on PreMiD Extension V.2.7.0 (67c3d34)
Bug is resolved in test builds & will not be a problem after pre-flight is moved to release.

**Comment by eliqts** [comment]
Awesome, thank you so much
