### ISSUE TITLE
Stremio | stremio.com - add better image assets

### ISSUE THREAD

**Issue by ragxxv** [PreMiD/Presences#8906]
### Presence name

Stremio

### Description

Could a better source be used to get the assets of the media currently being watched? It's more than often the image turns out to not fit within the 1:1 image ratio of the activity.

![image](https://github.com/user-attachments/assets/dadadbbf-8daa-4196-a252-1bc126204525)

**Comment by darkvillager2** [comment]
Will look into this, will most likely look better when changed to watching.

**Comment by darkvillager2** [comment]
Seems like discord isn't fully ready for this to work? But i can still PR the change.

**Comment by ragxxv** [comment]
Isn't fully ready? Curious how it is.

**Comment by darkvillager2** [comment]
> Isn't fully ready? Curious what's happening.

Only some websites allow posters (full images) to be displayed. Something to do with discord.

**Comment by veryCrunchy** [comment]
Working on it

**Comment by veryCrunchy** [comment]
@ragxxv what do you think of this?
![image](https://github.com/user-attachments/assets/95da8849-ae02-4577-bba2-f7cf87d4131e)
![image](https://github.com/user-attachments/assets/276078f7-6dc4-4aa8-ad31-cb50d2856d0f)
![image](https://github.com/user-attachments/assets/3f9845a0-29fc-4a46-8dc8-09d4a28a5f09)
![image](https://github.com/user-attachments/assets/80014447-4a2b-43e8-9050-9bc14385d4e6)
