### ISSUE TITLE
Apple Music | Native App

### ISSUE THREAD

**Issue by AGZhark** [PreMiD/Presences#8914]
### Steps to Reproduce

1. Open Discord
2. Open Apple Music app

### Expected Behavior

The Apple Music app status would be displayed

### Actual Behavior

I expected the app to work alongside the extension, but never does. This forces me to open my browser and listen to Apple Music that way

### Page URL

https://music.apple.com/us/new

### Operating System

Windows 11

### Browser and Version

Microsoft Edge, Edge 131

**Comment by Timeraa** [comment]
Since PreMiD only supports websites at this point I'll close this issue, we did add Safari support not to long ago so perhaps you want to give that one a shot!
