### ISSUE TITLE
Netflix | www.netflix.com | v6.0.3 - Issue Title

### ISSUE THREAD

**Issue by leilai-lai** [PreMiD/Presences#8921]
### Steps to Reproduce

![image](https://github.com/user-attachments/assets/654714ba-fc68-4bb7-a0d9-9105a3126e85)

### Expected Behavior

i expected it to display on my discord profile

### Actual Behavior

its not working 

### Page URL

aawa

### Screenshots

![image](https://github.com/user-attachments/assets/6e395889-8e1a-40bd-b7c6-a75e694ae210)
![image](https://github.com/user-attachments/assets/42e8553e-a63d-48ab-8556-dfa7923b88a5)

### Operating System

awa

### Browser and Version

awaw

### Additional Comments

awwa

**Comment by moyaimoment** [comment]
It's because your using the Netflix app, not the website. Maybe if you actually filled out the form correctly you would've realized this.
