### ISSUE TITLE
Store not showing up. 

### ISSUE THREAD

**Issue by Voxsin** [PreMiD/Presences#8934]
### Steps to Reproduce

 Fixing any errors after an update. 

### Expected Behavior

I expect to see the store with the different apps to select. 

### Actual Behavior

Error code kept popping up no matter what i did to try and fix it.

### Page URL

https://premid.app/store

### Screenshots

![Screenshot 2024-12-04 194207](https://github.com/user-attachments/assets/fe380e33-cf48-4c41-a0df-f2e61b608152)

### Operating System

Windows

### Browser and Version

Chrome, 131.0.6778.108

**Comment by theusaf** [comment]
This was a temporary outage unrelated to the Presences repository
