### ISSUE TITLE
Presence Suggestion: Comick

### ISSUE THREAD

**Issue by mgiles1** [PreMiD/Presences#8944]
### Website name

Comick

### Website URL

https://comick.io

### Website logo

https://comick.io/_next/image?url=%2Fstatic%2Ficons%2Funicorn-64.png&w=144&q=75

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

### Description

Comick is a free online manga reader that caters to all languages.

**Comment by theusaf** [comment]
This presence already exists. https://premid.app/store/presences/ComicK

**Comment by mgiles1** [comment]
I swear I went through all the categories like 2 or 3 times but couldn't
find it. thank you though
