### ISSUE TITLE
Drrr.com | Durarara Web Chat

### ISSUE THREAD

**Issue by DawkinIT** [PreMiD/Presences#896]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Dawkin Nguyen#7590

**What's the name of the service?** drrr.com | Durarara Web Chat

**What should the Presence display?** Lounge, Room Name (when user join or create room)

**If possible, please provide a logo for the service (512x512 minimum)** https://dollars-bbs.org/images/dollars_logo.jpg

**Comment by doomlerd** [comment]
To whoever willing to make this please make sure not to include names or what is being typed in order to respect the user's privacy.

**Comment by doomlerd** [comment]
Has been added : 
https://premid.app/store/presences/Durarara
