### ISSUE TITLE
Twitch | twitch.tv - 'show streamer's picture' is not working

### ISSUE THREAD

**Issue by mabskmk** [PreMiD/Presences#8973]
### Steps to Reproduce

1. Install/Enable Twitch Presence
2. Got to Twitch config
2a. disable Privacy Mode (in order to show stuff)
2b. enable Show Streamer's Picture
3. Watch a random Twitch Stream
4. Check the activity on discord

### Expected Behavior

The activity icon shows the Streamer's profile picture

### Actual Behavior

It shows a white icon with a question mark.

### Page URL

www.twitch.tv

### Screenshots

![Nova Imagem de Bitmap](https://github.com/user-attachments/assets/b8f9ac58-e047-40f6-bae1-aff7c0d80679)

### Operating System

Win10

### Browser and Version

Firefox 133.0.3

### Additional Comments

It worked before (3 weeks ago maybe) I'm using the Firefox extension
Twitch changed his UI a few days ago

**Comment by darkvillager2** [comment]
It has since been updated and resolved, seems like they were using the version before #8956 ?
![image](https://github.com/user-attachments/assets/c27167a5-8228-4573-b34e-136be2dfb674)
![image](https://github.com/user-attachments/assets/78e4e110-5d6c-4cbe-969e-838679b175d5)
