### ISSUE TITLE
TuneIn | tunein.com - presence stuck on browsing when listening to station with TuneIn switch support

### ISSUE THREAD

**Issue by realCallMeJ** [PreMiD/Presences#8983]
### Steps to Reproduce

1. go to [tunein.com/search](https://tunein.com/search/)
2. find a station with the TuneIn switch banner (looks like a lightning bolt) 
![image](https://github.com/user-attachments/assets/f4f89823-613c-4668-b1dd-065039677e3d)
3. play that station (and wait for advertisement to end if there is one)
4. check discord presence

### Expected Behavior

presence should display as it normally would on a station that does not have TuneIn switch

### Actual Behavior

presence is just stuck on "browsing..."

### Page URL

https://tunein.com/countryroads/ - this is just one example station with TuneIn switch, there are many more

### Operating System

Windows 10

### Browser and Version

Google Chrome Version 131.0.6778.205

### Additional Comments

just some extra info if you aren't sure what TuneIn switch does
when listening to a station with TuneIn switch, it changes the player in the bottom left to this with 2 cover images and the switch button
![image](https://github.com/user-attachments/assets/5e04082e-b722-4cdc-ab80-a420af90d369)
you can click the lightning bolt and it seems to switch you to a song that is similar to what you are listening to

**Comment by darkvillager2** [comment]
I will look into it
