### ISSUE TITLE
rich presence always on

### ISSUE THREAD

**Issue by Shayphlex** [PreMiD/Presences#8990]
### Steps to Reproduce

1. open youtube with rich presense enabled
2. uninstall premid extention and on computer

### Expected Behavior

stop the presense

### Actual Behavior

ongoing for ever

### Page URL

https://www.youtube.com/

### Screenshots

![image](https://github.com/user-attachments/assets/3be1e632-3fc9-4066-ba8d-26d5c66f9037)
![image](https://github.com/user-attachments/assets/f1b864bd-af9a-4eb7-bfb4-c602002114ef)

### Operating System

windows 10

### Browser and Version

chrome

### Additional Comments

even after restarting my computer, discord, and chrome and messing with the settings i still have a presense that is being showed no matter what. I tried every setting in premid aswell and uninstalled it and the youtube presense too. nothing works
![image](https://github.com/user-attachments/assets/4d4651ea-c761-4316-bca3-4b3ae6e51719)

**Comment by Slowlife01** [comment]
![Screenshot_2024-12-23-15-36-39-48_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/user-attachments/assets/208c0a9e-05a8-4760-979e-8532505c9d6e)

Same goes for uninstalling

**Comment by Timeraa** [comment]
Closing this, You have to disable the Activity in PreMiD itself, Discord is really messy when it comes to that Activity setting...
