### ISSUE TITLE
YouTube | www.youtube.com - The image keeps changing it back to thumbnail eventhough i set it to channel for youtube

### ISSUE THREAD

**Issue by lezzyadri** [PreMiD/Presences#9022]
### Steps to Reproduce

1. Click on premid extension
2. Click on youtube
3. Change image to channel
4. Click any other button, it resets back to thumbnail

### Expected Behavior

Channel's logo to display on discord when watching youtube videos

### Actual Behavior

Thumbnail displays on discord when watching youtube videos

### Page URL

youtube.com

### Screenshots

https://github.com/user-attachments/assets/f339b032-b357-40f3-b121-8ccf435af2a2

### Operating System

Windows 10

### Browser and Version

Google Chrome, Chrome 131

**Comment by theusaf** [comment]
This is an extension issue, not related to the presence code. Please send this bug report to the relevant community or repository.
