### ISSUE TITLE
YouTube: Doesn't show rich presence properly when casting video to a different device

### ISSUE THREAD

**Issue by INeedTogepi** [PreMiD/Presences#906]
**Describe the Bug**
YouTube Rich Presence in the discord app just has the YouTube logo and the text `YouTube`.

**Steps to Reproduce**
1. You have to have a device linked to your computer by following the instructions listed here: [https://www.youtube.com/pair](https://www.youtube.com/pair)
2. Then pick a video and click the button near the bottom right corner of the video player to start streaming to your device.
3. View Rich Presence result in Discord app.

**Expected Behavior**
I would like it if it showed the normal information, (video title, playing/paused status, channel name, etc.)

**Screenshots**

Here's an image of what it looks like when I am casting/streaming a video from my computer to my TV:
![Example of Bug](https://i.gyazo.com/86018c1087c54e5658072db7c9bdd446.png)

This is what I want/expect it to behave like:
![Expected Behavior](https://i.gyazo.com/d9f36c0d68c399f4a7a45f0c11c8c256.png)

**Environment**

 - OS: Windows 10
 - Browser: Brave Browser
 - Version: Version 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)

**Comment by doomlerd** [comment]
Are you able to watch a video that you're casting ( on the computer not the TV )?

**Comment by INeedTogepi** [comment]
> Are you able to watch a video that you're casting ( on the computer not the TV )?

When Casting it just shows the video's thumbnail in place of the actual video (on my computer). Because of this, I can only watch the video on my TV when casting.

**Comment by doomlerd** [comment]
> When Casting it just shows the video's thumbnail in place of the actual video

And that's why it's not possible to get the video's contents etc.. so it's not a bug, but I'll still change this to a feature request, maybe you're lucky the presence author or other contributors find a way to detect that ( @Bas950 can you look into this if possible ).

**Comment by Bas950** [comment]
I won't be able to help with this one, sorry  :/

**Comment by frozaum** [comment]
i have access to the casting system, if you guys want help, please dm me

**Comment by INeedTogepi** [comment]
It does still show the video player controls and also the title of the video when casting

**Comment by Alanexei** [comment]
The video element itself doesn't report any data, however, the controls report data back from the cast. You will have to scrub off the data, then convert it into the proper values. Luckily I have a method for that. I will try and fix it.

**Comment by doomlerd** [comment]
> The video element itself doesn't report any data, however, the controls report data back from the cast. You will have to scrub off the data, then convert it into the proper values. The video duration isn't displayed, but I think the video still has that data.

Maybe we need a sort of global function to grab casted video elements, since it's possible everywhere on Chrome.

**Comment by ririxidev** [comment]
Probably fixed.
