### ISSUE TITLE
SoloLearn - Presence Idea

### ISSUE THREAD

**Issue by BerfanK** [PreMiD/Presences#918]
**Prerequisites and essential questions** 
* [X] Is it a popular site?
* [X] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [X] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Nykloon#0002

**What's the name of the service?** 
www.sololearn.com

**What should the Presence display?** 
Programm Language you're currently learning (or challenges etc.); Your XP; Time elapsed

**If possible, please provide a logo for the service (512x512 minimum)** 
https://i1.wp.com/androidmag.de/wp-content/uploads/2016/11/t-10.jpg?fit=660%2C347&ssl=1

**Comment by Alanexei** [comment]
I use SoloLearn so I will work on this.
