### ISSUE TITLE
Wonderfulsubs | www.wonderfulsubs.com

### ISSUE THREAD

**Issue by VictorChenJ** [PreMiD/Presences#919]
**Prerequisites and essential questions** 
* [ ] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  

**What's the name of the service?**  https://www.wonderfulsubs.com/

**What should the Presence display?**  I belive it should be the same as the twist.moe one. It should show which episode you are watching and time left etc

**If possible, please provide a logo for the service (512x512 minimum)**  
https://www.wonderfulsubs.com/img/avatar200.jpg

Couldn't find a better logo for the website.

**Comment by doomlerd** [comment]
Not nsfw, at least not what it seems to be.

**Comment by VictorChenJ** [comment]
I mean, technically it does have some nsfw like ecchi or hentai, but it doesn't really advertise it I guess.
