### ISSUE TITLE
Selective-Network 

### ISSUE THREAD

**Issue by Cobra-Designs** [PreMiD/Presences#924]
* [ ] Is it a popular site?
* [x] Is the website older than 2 months?
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service?
* [ ] Does the website feature NSFW content?
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** Selective-Network  /  Selective-Network.co.uk

**What should the Presence display?** what page your on and name of the site

**If possible, please provide a logo for the service (512x512 minimum)** 
![LOGO](https://user-images.githubusercontent.com/54513673/72668267-088ad400-3a1d-11ea-9483-c74d35e14e02.png)

**Comment by MrBartusek** [comment]
I guess website died before anyone made a presence for it

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/23432278/98519649-58b77900-2271-11eb-9480-bededf35f016.png)

</details>
