### ISSUE TITLE
Aniflix Video bug (time elapsed)

### ISSUE THREAD

**Issue by LordHainzAniflix** [PreMiD/Presences#927]
**Describe the Bug**

When i watch a Anime video on aniflix, the player is irrelevant, there stands Time elapsed and normally there would stand time left like by the others i dont know why this problem is only for me I used chrome and firefox and both did not work. 

**Steps to Reproduce**

https://www2.aniflix.tv/show/kyokou-suiri/ger-sub/season/1/episode/2

Go on this link click on it Use player "anistream" or " Crazyloads"
This is how it should not look
![grafik](https://user-images.githubusercontent.com/46389324/72670984-4a7b4080-3a44-11ea-9bc1-ae632454fbcb.png)
Verstrichen = time elapsed
https://www2.aniflix.tv/show/kyokou-suiri/ger-sub/season/1/episode/2
1.
2.
3.

**Expected Behavior**
This is how it should look
![grafik](https://user-images.githubusercontent.com/46389324/72671004-95955380-3a44-11ea-93ef-0515986eae19.png)
Verbleibend = time left

**Screenshots**

**Environment**

Windows 10 
 - Browser: Firefox or Chrome
 - Version: 72.0.1 (64-Bit) Firefox  | 79.0.3945.130  (64-Bit) Chrome

 
**Additional context**
Ths problem only fucks me bruh

**Comment by Bas950** [comment]
@LordHainzAniflix Please contact me on discord Bas950#0950
I dont not have this issue, but would like your help on the issue.

**Comment by Bas950** [comment]
Same issue as others have reported, presence not able to get the element even though its there.

**Comment by doomlerd** [comment]
Closing this as we've made a lot of changes since January, make sure to check it again with the latest version of the app/extension.
