### ISSUE TITLE
PreMİD Öneri

### ISSUE THREAD

**Issue by Suprise-Battle** [PreMiD/Presences#928]
Muud | https://www.muud.com.tr/

Yemek Sepeti | https://www.yemeksepeti.com/

Tubitak | https://www.tubitak.gov.tr/

Biletix | https://www.tubitak.gov.tr/

MyNet | https://www.mynet.com/

Şikayet Var | https://www.sikayetvar.com/

DigiTurk | http://www.digiturk.com.tr/

Reddit | https://www.reddit.com/

Tamİndir |  https://www.tamindir.com/

Nesine | https://www.nesine.com/

FotoMac | https://www.fotomac.com.tr/

Cumhuriyet | http://www.cumhuriyet.com.tr/

Msn | https://www.msn.com/tr-tr/

Tumblr | https://www.tumblr.com/

Kariyer | https://www.kariyer.net/

CnnTurk | https://www.cnnturk.com/

Eba | http://www.eba.gov.tr/

Trend Yol | https://www.trendyol.com/

**Comment by Bas950** [comment]
Some are already added see: https://premid.app/
Please use the correct format to suggest a website, and please create an issue for each website.
https://github.com/PreMiD/Presences/issues/new?template=service_request.md
