### ISSUE TITLE
Opera Presence Bug (Google)

### ISSUE THREAD

**Issue by Hexishu** [PreMiD/Presences#937]
When I search something with google on the new opera browser (Opera GX) it doesn't show, but everything other (e.g youtube, netflix, pornhub etc.) does. When I use Chrome it's fine but with opera it's bugged, tried to reinstall and restart premid a dozen times but didn't work out at all.

**Comment by frozaum** [comment]
What?

**Comment by Hexishu** [comment]
When I use opera gx
and I search something in google (goolge presence) 
it doesn't show...

**Comment by Hexishu** [comment]
> What?

...
