### ISSUE TITLE
[Presence | Feature Request] Plex

### ISSUE THREAD

**Issue by DrKain** [PreMiD/Presences#938]
**Describe the Bug**

The Plex presence should include the season and episode number for TV series.  
Example: S01E02 - Episode Name

**Steps to Reproduce**

1. Enable Plex presence
2. Play any TV show / Anime
3. Status displays episode title but not the episode number or season

**Expected Behavior**

Season and Episode number in title: S01E02 - Episode Name

**Screenshots**
Current:  
![1](https://i.imgur.com/94z5zKA.png)    
Expected:   
![2](https://i.imgur.com/4xVDxJR.png)  

**Environment**

 - OS:  Windows 10
 - Browser:  Firefox
 - Version:  72.0.1
 
 
**Additional context**

**Comment by ririxidev** [comment]
@Bas950 hmm, maybe you will do it someday? 🤔
