### ISSUE TITLE
PartydoosMediaGroup | partydoosmediagroup.weebly.com

### ISSUE THREAD

**Issue by Feestbox** [PreMiD/Presences#956]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [x] Is the site locked to a specific country/region?
* [] Is the site a paid service? (e.g. Netflix, Hulu)
* [] Does the website feature NSFW content? (e.g. porn, etc...)
* [] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  PartydoosMG#5741

**What's the name of the service?** 
partydoosmediagroup.weebly.com | PartydoosMediaGroup (soon .com, of course)

**What should the Presence display?** 

Checking the PartydoosMediaGroup website for... (specific service like PRTYDS, web hosting, Cloud, dashboard, etc)

**If possible, please provide a logo for the service (512x512 minimum)** 
![pmg app logo](https://user-images.githubusercontent.com/39923540/73078978-a8d07500-3ec3-11ea-9402-5dd87842ff49.png)

**Comment by Alanexei** [comment]
As long as the website gets moved to a permanent domain in the future, I will make it the presence regardless of the free domain.
