### ISSUE TITLE
CyTube | cytu.be

### ISSUE THREAD

**Issue by frozaum** [PreMiD/Presences#961]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [x] Does the website feature NSFW content? (e.g. porn, etc...) - It depends what room you are.
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  
fror#9493
**What's the name of the service?** 
cytu.be | Cytube
**What should the Presence display?** 
It should look like this
![](https://menma.is-inside.me/gQXcSa1D.png)
**If possible, please provide a logo for the service (512x512 minimum)** 
![](https://menma.is-inside.me/MKKwFzQo.png)

bonus: thumbnail
![](https://menma.is-inside.me/fQhgUJB7.png)

**Comment by MulverineX** [comment]
I've got this one

**Comment by frozaum** [comment]
done and closed #964
