### ISSUE TITLE
Niantic Wayfarer | wayfarer.nianticlabs.com

### ISSUE THREAD

**Issue by 123321mario** [PreMiD/Presences#962]
**Prerequisites and essential questions** 
* [x] Is it a popular site? Yes, super popular in the Pokémon GO and Ingress communities
* [x] Is the website older than 2 months?  Yes. It was launched in October 2019
* [ ] Is the site locked to a specific country/region? Some regions are banned but most of the world can access
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [x] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
123321mario#1337

**What's the name of the service?** 
wayfarer.nianticlabs.com | Niantic Wayfarer

**What should the Presence display?** 
Show on wich module the user is currently working.
Modules : 
Showcase : /
Review : /review
Nominations : /nominations
Wayfinder : /profile
Help : /help
Settings : /settings

On review it would be nice to know the title of the nomination, for example if someone sees their nomination he could DM the person who is verifying.

Note : The website is only avaliable for some players of the Niantic's games, DM me on discord if you need more info

**If possible, please provide a logo for the service (512x512 minimum)** 

White SVG : https://wayfarer.nianticlabs.com/imgpub/logos/niantic-wayfarer-white.svg
Color SVG : https://wayfarer.nianticlabs.com/imgpub/logos/niantic-wayfarer-color.svg
Icon PNG : https://wayfarer.nianticlabs.com/imgpub/favicon-256.png

**Comment by Bas950** [comment]
For information about the status of this suggestion see #1129
