### ISSUE TITLE
Chordify | chordify.net

### ISSUE THREAD

**Issue by uShaadow** [PreMiD/Presences#971]
**Prerequisites and essential questions** 
* [X] Is it a popular site?
* [X] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [X] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  vadia#5750

**What's the name of the service?**  www.chordify.net | Chordify

**What should the Presence display?**  Playing [ music the user is playing, in the musical sense, like playing Starway to Heaven in guitar ] I don't know if the API can catch the instrument choice of the user in the site, like guitar, piano or ukulele.. but it would be nice if so
![images](https://user-images.githubusercontent.com/40726159/73130220-10c1b100-3fd3-11ea-89f8-3bbc6398fd97.jpg)

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by marinofranz** [comment]
I'll take it

**Comment by uShaadow** [comment]
Thank you, it means a lot to me!

Em qui., 21 de mai. de 2020 às 17:33, marinofranz <notifications@github.com>
escreveu:

**Comment by marinofranz** [comment]
No problem. Just to mention, as I am volunteering to do this. This may take some time. I will get back to you when it is nearly finished.

**Comment by uShaadow** [comment]
Don't worry bout the time, bro take any time you need to, tnx for
volunteering, I am looking forward to this!

Em sex., 22 de mai. de 2020 às 21:57, marinofranz <notifications@github.com>
escreveu:

**Comment by marinofranz** [comment]
#1750 for progress

**Comment by marinofranz** [comment]
No longer interested/motivated to do this, sorry bud
