### ISSUE TITLE
Tête a claques | www.tetesaclaques.tv

### ISSUE THREAD

**Issue by Tigrouu** [PreMiD/Presences#972]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [x] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
𝖀𝖓𝖊𝕻𝖔𝖚𝖘𝖘𝖎𝖊̀𝖗𝖊𝕯𝖊𝕿𝖎𝖌𝖗𝖊..💔 (𝕿𝖎𝖌𝖗𝖔𝖚)#1912

**What's the name of the service?** 
Tête a claques | www.tetesaclaques.tv

**What should the Presence display?** 
I would like it to look like youtube, the name of the video is displayed, the minutes and when we pause and when we watch the video

**If possible, please provide a logo for the service (512x512 minimum)** 
https://imgur.com/XexVLGw.png

**Comment by ELITE-NOTORIOUS-Supremacist** [comment]
omg lol this website that i found from French class!
