### ISSUE TITLE
Express Radio Presence

### ISSUE THREAD

**Issue by AviaMisto2** [PreMiD/Presences#988]
**Prerequisites and essential questions** 
* [ ] Is it a popular site? No
* [ ] Is the website older than 2 months?  Yes
* [ ] Is the site locked to a specific country/region? No
* [ ] Is the site a paid service? (e.g. Netflix, Hulu) No
* [ ] Does the website feature NSFW content? (e.g. porn, etc...) No
* [ ] Are you a donator/patron? No
* [ ] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority? Yes

**What's your Discord username?**  Chxrlie#1111
**What's the name of the service?** 
https://expressradio.tk/ (Or expressradio.co website isnt set up yet but we own domain for it) | Express Radio
**What should the Presence display?** 
DJ and the Song
**If possible, please provide a logo for the service (512x512 minimum)** 
![EXPRESS RADIO AGAIN](https://user-images.githubusercontent.com/59765752/73488947-a8dbe380-43a1-11ea-816b-b36082ba05dc.png)

**Comment by doomlerd** [comment]
Sorry, we don't accept requests for sites that are unstable or with free domains anymore, you can make another request in 2 months if your site survives until that time and if it gets an actual paid domain.

**Comment by AviaMisto2** [comment]
Hi I do have a paid domain, we are publishing the website right now we just
needed to verify it
