### ISSUE TITLE
Pulse Radio

### ISSUE THREAD

**Issue by EthanTK** [PreMiD/Presences#994]
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Ethan#6302

**What's the name of the service?** 
Pulse Radio

**What should the Presence display?** 
1. Title
2. Logo
3. Listening to: Artist - Song name

**If possible, please provide a logo for the service (512x512 minimum)** 
https://imgur.com/mqYHGOC

**Comment by Bas950** [comment]
@EthanTK link?

**Comment by EthanTK** [comment]
> @EthanTK link?

@Bas950 https://itspulse.net/

**Comment by EthanTK** [comment]
Hi. Is there an update on this request?

**Comment by callumok2004** [comment]
I will start working on this in a few moments if it has not already been started.

**Comment by callumok2004** [comment]
#1071

**Comment by callumok2004** [comment]
https://premid.app/store/presences/Pulse
