### ISSUE TITLE
Manga Dex Presence doesn't always show the chapter name

### ISSUE THREAD

**Issue by Viruzaum** [PreMiD/Presences#996]
@RisingChops 
The Presence is getting the chapter title instead of the number but not all manga have chapter names, so sometimes it shows nothing.
![image](https://user-images.githubusercontent.com/23330390/73590347-285fd480-44c0-11ea-8756-df8ec6f12945.png)
Instead of getting the chapter name bellow the title, I think it's better to use the chapter number that sometimes comes with the chapter name.
![image](https://user-images.githubusercontent.com/23330390/73590362-56451900-44c0-11ea-9e3f-983124841917.png)

**Comment by doomlerd** [comment]
Please use the bug report template.
