### ISSUE TITLE
TMNF TMX Exchange | https://tmnforever.tm-exchange.com/

### ISSUE THREAD

**Issue by ELITE-NOTORIOUS-Supremacist** [PreMiD/Presences#998]
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  ELITE NOTORIOUS The Supremacist#4624

**What's the name of the service?** 
https://tmnforever.tm-exchange.com/ | Trackmania Nations Forever Exchange

**What should the Presence display?**  What page somebody is on and possibly what map they are looking at for records or to download.

**If possible, please provide a logo for the service (512x512 minimum)**

**Comment by Hans5958** [comment]
I'm going to do this, along with the other sites on the TrackMania Exchange network. This probably going to take a week or so.
